import type { Lesson } from "../../types";
import { t, ln, mp } from "./helpers";

export const lessons2: Lesson[] = [
  // ─────────────────────────────── L06 — Travel mishaps
  {
    id: "hsk3-l06",
    level: 3,
    order: 6,
    title: t("Galères de voyage", "Travel mishaps"),
    subtitle: t("Vol, annulation et imprévus", "Theft, cancellations and surprises"),
    theme: "travel",
    goals: [
      t("Raconter un incident désagréable avec le passif en 被", "Describe an unpleasant incident with the 被 passive"),
      t("Enchaîner les événements d'un récit avec 于是", "Link events in a story with 于是"),
      t("Exprimer une surprise ou une inquiétude avec 却 et 恐怕", "Express surprise or worry with 却 and 恐怕"),
      t("Utiliser les compléments de résultat 住, 掉, 成, 好, 到", "Use the result complements 住, 掉, 成, 好, 到"),
    ],
    dialogue: {
      context: t(
        "Zhang Liang et Chen Jing voyagent ensemble. Ils se retrouvent à l'aéroport après une journée pleine de galères.",
        "Zhang Liang and Chen Jing are travelling together. They meet up at the airport after a day full of mishaps."
      ),
      lines: [
        ln("陈静", "张亮，你怎么了？脸色这么难看。", "Zhāng Liàng, nǐ zěnme le? Liǎnsè zhème nánkàn.", "Zhang Liang, qu'est-ce qui t'arrive ? Tu fais une de ces têtes.", "Zhang Liang, what's wrong? You look awful."),
        ln("张亮", "别提了！我的钱包在地铁上被偷了。", "Bié tí le! Wǒ de qiánbāo zài dìtiě shang bèi tōu le.", "M'en parle pas ! On m'a volé mon portefeuille dans le métro.", "Don't ask! My wallet got stolen on the subway."),
        ln("陈静", "啊？里面有护照吗？", "Á? Lǐmiàn yǒu hùzhào ma?", "Quoi ? Ton passeport était dedans ?", "What? Was your passport in it?"),
        ln("张亮", "还好，护照没被偷，可是银行卡和钱都没了。", "Hái hǎo, hùzhào méi bèi tōu, kěshì yínhángkǎ hé qián dōu méi le.", "Heureusement, pas le passeport, mais ma carte bancaire et mon argent, oui.", "Luckily the passport wasn't taken, but my bank card and cash are gone."),
        ln("陈静", "真倒霉！那你怎么办？", "Zhēn dǎoméi! Nà nǐ zěnme bàn?", "Quelle poisse ! Et tu as fait quoi ?", "What bad luck! So what did you do?"),
        ln("张亮", "我找不到警察，于是给酒店打了电话，他们帮我报了警。", "Wǒ zhǎo bu dào jǐngchá, yúshì gěi jiǔdiàn dǎ le diànhuà, tāmen bāng wǒ bào le jǐng.", "Je ne trouvais pas de policier, alors j'ai appelé l'hôtel, et ils ont prévenu la police pour moi.", "I couldn't find a police officer, so I called the hotel and they reported it for me."),
        ln("陈静", "我今天也不顺利。我们的航班被取消了。", "Wǒ jīntiān yě bú shùnlì. Wǒmen de hángbān bèi qǔxiāo le.", "Moi non plus, ma journée n'a pas été terrible. Notre vol a été annulé.", "My day hasn't gone well either. Our flight's been cancelled."),
        ln("张亮", "什么？天气这么好，航班却取消了？", "Shénme? Tiānqì zhème hǎo, hángbān què qǔxiāo le?", "Quoi ? Il fait super beau, et pourtant le vol est annulé ?", "What? The weather's great, and yet the flight's cancelled?"),
        ln("陈静", "听说是飞机出了问题。恐怕我们今天走不了了。", "Tīngshuō shì fēijī chū le wèntí. Kǒngpà wǒmen jīntiān zǒu bu liǎo le.", "Il paraît que l'avion a un problème. J'ai bien peur qu'on ne puisse pas partir aujourd'hui.", "Apparently there's a problem with the plane. I'm afraid we can't leave today."),
        ln("张亮", "那我们得再找一家酒店了。", "Nà wǒmen děi zài zhǎo yì jiā jiǔdiàn le.", "Alors il va falloir trouver un autre hôtel.", "Then we'll have to find another hotel."),
        ln("陈静", "我已经订好了。对了，你记住了吗？明天早上八点的飞机。", "Wǒ yǐjīng dìnghǎo le. Duì le, nǐ jìzhù le ma? Míngtiān zǎoshang bā diǎn de fēijī.", "C'est déjà réservé. Au fait, tu as bien retenu ? L'avion est demain à 8 heures.", "I've already booked one. By the way, have you got it? Our flight's at 8 tomorrow morning."),
        ln("张亮", "记住了。这次我一定把东西看好，不会再丢掉了！", "Jìzhù le. Zhè cì wǒ yídìng bǎ dōngxi kānhǎo, bú huì zài diūdiào le!", "C'est noté. Cette fois, je surveille bien mes affaires, je ne perdrai plus rien !", "Got it. This time I'll keep a close eye on my things — I won't lose anything again!"),
        ln("陈静", "哈哈，旅行嘛，总会遇到一些意外。", "Hāhā, lǚxíng ma, zǒng huì yùdào yìxiē yìwài.", "Haha, c'est ça les voyages : il y a toujours des imprévus.", "Haha, that's travel — there are always a few surprises."),
      ],
    },
    vocab: ["旅行", "钱包", "偷", "被", "护照", "银行卡", "倒霉", "警察", "于是", "酒店", "顺利", "航班", "取消", "却", "恐怕", "订", "记住", "丢", "意外", "遇到", "行李", "机场", "导游", "司机", "迷路", "票", "着急", "办法", "解决"],
    grammar: ["hsk3-g27", "hsk3-g28", "hsk3-g29", "hsk3-g30", "hsk3-g31"],
    culture: {
      title: t("Voyager pendant la « Golden Week »", "Travelling during \"Golden Week\""),
      body: t(
        "Deux fois par an, pour la fête nationale (1ᵉʳ octobre) et le Nouvel An chinois, la Chine connaît une semaine de congés appelée **黄金周** (« semaine d'or »). Des centaines de millions de personnes voyagent en même temps : sites touristiques bondés, billets de train épuisés en quelques minutes sur l'appli **12306**…\n\nQuelques réflexes utiles : garde une **photo de ton passeport** sur ton téléphone, retiens les numéros d'urgence — **110** (police), **120** (ambulance), **119** (pompiers) — et n'hésite pas à demander de l'aide à ton hôtel : le personnel a l'habitude.",
        "Twice a year, for National Day (1 October) and Chinese New Year, China has a week off called **黄金周** (\"Golden Week\"). Hundreds of millions of people travel at the same time: packed tourist sites, train tickets sold out within minutes on the **12306** app…\n\nA few useful habits: keep a **photo of your passport** on your phone, memorise the emergency numbers — **110** (police), **120** (ambulance), **119** (fire) — and don't hesitate to ask your hotel for help: the staff are used to it."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« On m'a volé mon téléphone. »", "\"My phone was stolen.\""),
        options: ["我的手机被偷。", "我的手机被偷了。", "我的手机叫偷了。", "我的手机偷被了。"],
        answer: 1,
        explain: t("Le verbe après 被 ne reste pas seul : 了.", "The verb after 被 can't stand alone: add 了."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase négative est correcte ?", "Which negative sentence is correct?"),
        options: ["我的护照被没偷。", "我的护照没被偷。", "我的护照被偷没。", "我的护照不被偷了。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("« J'ai trouvé mon passeport. » (résultat atteint)", "\"I found my passport.\" (result achieved)"),
        options: ["我找了护照。", "我不找到护照。", "我找到了护照。", "我找住了护照。"],
        answer: 2,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "酒店没有房间了，",
        after: "我们换了一家。",
        options: ["于是", "恐怕", "却", "被"],
        answer: 0,
        tr: t("L'hôtel était complet, alors on en a pris un autre.", "The hotel was full, so we went to another one."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "天气预报说晴天，",
        after: "下了一整天雨。",
        options: ["于是", "却", "恐怕", "被"],
        answer: 1,
        tr: t("La météo annonçait du soleil, et il a plu toute la journée.", "The forecast said sunny, yet it rained all day."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "路上堵车，",
        after: "我们要迟到了。",
        options: ["却", "于是", "恐怕", "被"],
        answer: 2,
        tr: t("Il y a des bouchons, j'ai bien peur qu'on soit en retard.", "There's traffic — I'm afraid we'll be late."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我们的", "航班", "被", "取消", "了"],
        tr: t("Notre vol a été annulé.", "Our flight was cancelled."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["请", "记住", "你的", "房间号"],
        tr: t("Retiens bien ton numéro de chambre.", "Please remember your room number."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["司机", "把“西安”", "听成了", "“西湖”"],
        tr: t("Le chauffeur a compris « Xihu » au lieu de « Xi'an ».", "The driver misheard \"Xi'an\" as \"Xihu\"."),
      },
      {
        type: "listen",
        zh: "我的钱包在地铁上被偷了。",
        options: ["我的钱包在出租车上被偷了。", "我的护照在地铁上被偷了。", "我的钱包在地铁上被偷了。", "我在地铁上找到了钱包。"],
        answer: 2,
        tr: t("On m'a volé mon portefeuille dans le métro.", "My wallet was stolen on the subway."),
      },
      {
        type: "listen",
        zh: "恐怕我们今天走不了了。",
        options: ["恐怕我们今天走不了了。", "我们今天走得了。", "恐怕我们明天走不了了。", "我们今天不想走了。"],
        answer: 0,
        tr: t("J'ai bien peur qu'on ne puisse pas partir aujourd'hui.", "I'm afraid we can't leave today."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("护照", "hùzhào", "passeport", "passport"),
          mp("航班", "hángbān", "vol (avion)", "flight"),
          mp("取消", "qǔxiāo", "annuler", "cancel"),
          mp("警察", "jǐngchá", "policier", "police officer"),
          mp("行李", "xíngli", "bagages", "luggage"),
        ],
      },
      {
        type: "choice",
        prompt: t("Avec 叫 ou 让 au passif, l'agent est…", "With passive 叫 or 让, the agent is…"),
        options: [
          t("interdit", "forbidden"),
          t("facultatif", "optional"),
          t("obligatoire", "required"),
          t("placé à la fin", "placed at the end"),
        ],
        answer: 2,
      },
    ],
  },

  // ─────────────────────────────── L07 — Relationships & friendship
  {
    id: "hsk3-l07",
    level: 3,
    order: 7,
    title: t("Une amitié à l'épreuve", "A friendship put to the test"),
    subtitle: t("Disputes, malentendus et réconciliation", "Quarrels, misunderstandings and making up"),
    theme: "feelings",
    goals: [
      t("Parler de ses sentiments et de ses relations", "Talk about your feelings and relationships"),
      t("Dire « quel que soit » et « même si » avec 无论/不管……都 et 即使……也", "Say \"no matter\" and \"even if\" with 无论/不管……都 and 即使……也"),
      t("Décrire quelqu'un avec 既……又", "Describe someone with 既……又"),
      t("Exprimer la surprise avec 难道 et l'effet d'une chose avec 让 / 使", "Show surprise with 难道 and talk about effects with 让 / 使"),
    ],
    dialogue: {
      context: t(
        "Xiaoyu est contrariée : sa meilleure amie Lili n'est pas venue à son anniversaire. Elle en parle à sa colocataire Lin Na.",
        "Xiaoyu is upset: her best friend Lili didn't come to her birthday party. She talks about it with her roommate Lin Na."
      ),
      lines: [
        ln("林娜", "小雨，你怎么不高兴？", "Xiǎoyǔ, nǐ zěnme bù gāoxìng?", "Xiaoyu, qu'est-ce qui ne va pas ?", "Xiaoyu, why so down?"),
        ln("小雨", "我跟丽丽吵架了。她没来参加我的生日聚会。", "Wǒ gēn Lìli chǎojià le. Tā méi lái cānjiā wǒ de shēngrì jùhuì.", "Je me suis disputée avec Lili. Elle n'est pas venue à ma fête d'anniversaire.", "I had a fight with Lili. She didn't come to my birthday party."),
        ln("林娜", "难道她忘了吗？你们不是最好的朋友吗？", "Nándào tā wàng le ma? Nǐmen bú shì zuì hǎo de péngyou ma?", "Ne me dis pas qu'elle a oublié ? Vous n'êtes pas meilleures amies ?", "Don't tell me she forgot? Aren't you best friends?"),
        ln("小雨", "她说她要加班。可是即使再忙，也可以打个电话啊。", "Tā shuō tā yào jiābān. Kěshì jíshǐ zài máng, yě kěyǐ dǎ ge diànhuà a.", "Elle dit qu'elle devait faire des heures sup. Mais même débordée, elle aurait pu appeler !", "She says she had to work late. But even if you're super busy, you can still call!"),
        ln("林娜", "她这样做让你很难过吧？", "Tā zhèyàng zuò ràng nǐ hěn nánguò ba?", "Ça t'a fait beaucoup de peine, hein ?", "That must have really hurt you."),
        ln("小雨", "是啊。我觉得她不关心我了。", "Shì a. Wǒ juéde tā bù guānxīn wǒ le.", "Oui. J'ai l'impression que je ne compte plus pour elle.", "Yeah. I feel like she doesn't care about me any more."),
        ln("林娜", "我觉得丽丽既热情又大方，不会是故意的。", "Wǒ juéde Lìli jì rèqíng yòu dàfang, bú huì shì gùyì de.", "Lili est chaleureuse et généreuse, je ne pense pas qu'elle l'ait fait exprès.", "Lili's warm and generous — I don't think she did it on purpose."),
        ln("小雨", "你说得也对。上次我生病，不管多晚，她都来医院看我。", "Nǐ shuō de yě duì. Shàng cì wǒ shēngbìng, bùguǎn duō wǎn, tā dōu lái yīyuàn kàn wǒ.", "C'est vrai. La dernière fois que j'étais malade, elle venait me voir à l'hôpital, peu importe l'heure.", "You're right. Last time I was ill, she came to see me in hospital no matter how late it was."),
        ln("林娜", "所以啊，你们应该好好儿聊一聊。", "Suǒyǐ a, nǐmen yīnggāi hǎohāor liáo yi liáo.", "Tu vois ? Vous devriez en parler tranquillement.", "See? You two should have a proper talk."),
        ln("小雨", "可是我不知道怎么跟她说。", "Kěshì wǒ bù zhīdào zěnme gēn tā shuō.", "Mais je ne sais pas comment lui en parler.", "But I don't know how to bring it up with her."),
        ln("林娜", "你请她周末来家里吃饭吧。无论发生什么事，朋友之间都需要互相理解。", "Nǐ qǐng tā zhōumò lái jiā lǐ chīfàn ba. Wúlùn fāshēng shénme shì, péngyou zhījiān dōu xūyào hùxiāng lǐjiě.", "Invite-la à dîner ce week-end. Quoi qu'il arrive, entre amis, il faut se comprendre.", "Invite her over for dinner this weekend. Whatever happens, friends need to understand each other."),
        ln("小雨", "好主意！谢谢你，有你这个朋友真好。", "Hǎo zhǔyi! Xièxie nǐ, yǒu nǐ zhège péngyou zhēn hǎo.", "Bonne idée ! Merci, c'est génial d'avoir une amie comme toi.", "Good idea! Thanks — I'm so lucky to have a friend like you."),
      ],
    },
    vocab: ["吵架", "参加", "聚会", "难道", "即使", "难过", "关心", "既", "热情", "大方", "故意", "生病", "不管", "无论", "聊天", "发生", "之间", "互相", "理解", "主意", "感情", "友谊", "原谅", "相信", "误会", "感动", "联系", "性格", "请", "使", "让"],
    grammar: ["hsk3-g32", "hsk3-g33", "hsk3-g34", "hsk3-g35", "hsk3-g36"],
    culture: {
      title: t("L'amitié à la chinoise", "Friendship, Chinese style"),
      body: t(
        "En Chine, l'amitié se montre souvent par des **actes** plus que par des mots : aider à déménager, apporter à manger quand l'autre est malade… Au restaurant, les amis se disputent pour **payer l'addition** (抢着买单) : laisser l'autre payer à chaque fois ferait perdre la face.\n\nQuelques mots d'argot sympa : **闺蜜** (guīmì) = meilleure amie (entre filles), **哥们儿** (gēmenr) = pote (entre garçons), **老铁** (lǎotiě) = ami fidèle, très à la mode dans le nord. Et lors d'une dispute, on évite souvent la confrontation directe pour préserver **le visage** (面子) de chacun.",
        "In China, friendship is often shown through **actions** more than words: helping someone move, bringing food when they're ill… At restaurants, friends fight to **pay the bill** (抢着买单): always letting the other pay would mean losing face.\n\nSome fun slang: **闺蜜** (guīmì) = best friend (between girls), **哥们儿** (gēmenr) = buddy (between guys), **老铁** (lǎotiě) = loyal mate, very trendy in the north. And in a quarrel, people often avoid direct confrontation to protect everyone's **face** (面子)."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Qu'il vente ou qu'il pleuve, il vient me voir. »", "\"Rain or shine, he comes to see me.\""),
        options: ["不管刮风或者下雨，他都来看我。", "不管刮风还是下雨，他都来看我。", "不管刮风还是下雨，他就来看我。", "虽然刮风还是下雨，他都来看我。"],
        answer: 1,
        explain: t("Alternative après 不管 → 还是 ; puis 都.", "Alternatives after 不管 use 还是, followed by 都."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase exprime une hypothèse (« même si ») ?", "Which sentence expresses a hypothesis (\"even if\")?"),
        options: ["虽然下雨，我还是去了。", "即使明天下雨，我也去。", "因为下雨，所以我没去。", "尽管下雨了，他还是来了。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("« Maman ne me laisse pas sortir. »", "\"Mum won't let me go out.\""),
        options: ["妈妈让我不出去。", "妈妈不让我出去。", "妈妈让不我出去。", "妈妈让我出去不。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "她",
        after: "是我的同事，又是我最好的朋友。",
        options: ["既", "即使", "不管", "难道"],
        answer: 0,
        tr: t("C'est à la fois ma collègue et ma meilleure amie.", "She's both my colleague and my best friend."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "",
        after: "你忘了今天是我的生日吗？",
        options: ["不管", "难道", "即使", "既然"],
        answer: 1,
        tr: t("Ne me dis pas que tu as oublié que c'est mon anniversaire ?", "Don't tell me you forgot it's my birthday?"),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "朋友的话",
        after: "我很感动。",
        options: ["被", "把", "让", "对"],
        answer: 2,
        tr: t("Les mots de mon ami m'ont beaucoup touché.", "My friend's words really moved me."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["不管你", "去哪儿，", "我", "都", "支持你"],
        tr: t("Où que tu ailles, je te soutiendrai.", "Wherever you go, I'll support you."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["即使", "很忙，", "他", "也会", "给我打电话"],
        tr: t("Même quand il est très pris, il m'appelle.", "Even when he's really busy, he calls me."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["他", "请我们", "周末", "去他家", "吃饭"],
        tr: t("Il nous a invités à dîner chez lui ce week-end.", "He invited us to his place for dinner this weekend."),
      },
      {
        type: "listen",
        zh: "即使再忙，也可以打个电话啊。",
        options: ["因为很忙，所以没打电话。", "即使再忙，也可以打个电话啊。", "再忙也不能打电话。", "即使不忙，也不打电话。"],
        answer: 1,
        tr: t("Même débordé, on peut toujours passer un coup de fil !", "Even if you're super busy, you can still call!"),
      },
      {
        type: "listen",
        zh: "朋友之间需要互相理解。",
        options: ["朋友之间需要互相帮助。", "同学之间需要互相理解。", "朋友之间需要互相理解。", "朋友之间不需要理解。"],
        answer: 2,
        tr: t("Entre amis, il faut se comprendre.", "Friends need to understand each other."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("吵架", "chǎojià", "se disputer", "quarrel"),
          mp("原谅", "yuánliàng", "pardonner", "forgive"),
          mp("误会", "wùhuì", "malentendu", "misunderstanding"),
          mp("关心", "guānxīn", "se soucier de", "care about"),
          mp("故意", "gùyì", "exprès", "on purpose"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quel verbe convient pour « provoquer un sentiment » à l'écrit ?", "Which verb fits \"cause a feeling\" in written style?"),
        options: ["使", "请", "叫", "被"],
        answer: 0,
      },
    ],
  },

  // ─────────────────────────────── L08 — Chinese festivals in depth
  {
    id: "hsk3-l08",
    level: 3,
    order: 8,
    title: t("Les grandes fêtes chinoises", "China's great festivals"),
    subtitle: t("Nouvel An, mi-automne et bateaux-dragons", "Spring Festival, Mid-Autumn and Dragon Boat"),
    theme: "culture",
    goals: [
      t("Décrire les traditions des principales fêtes chinoises", "Describe the traditions of the main Chinese festivals"),
      t("Distinguer 按照 et 根据 (« selon »)", "Tell 按照 and 根据 (\"according to\") apart"),
      t("Faire une énumération avec 等 / 等等 et utiliser 各, 其他, 另外", "List things with 等 / 等等 and use 各, 其他, 另外"),
      t("Compter les actions avec 次, 遍, 趟, 顿, 场", "Count actions with 次, 遍, 趟, 顿, 场"),
      t("Utiliser les mots interrogatifs au sens de « tout le monde, rien » (谁都…)", "Use question words to mean \"everyone, nothing\" (谁都…)"),
    ],
    dialogue: {
      context: t(
        "Marc, étudiant français à Pékin, interroge son ami Li Hua sur les fêtes chinoises.",
        "Marc, a French student in Beijing, asks his friend Li Hua about Chinese festivals."
      ),
      lines: [
        ln("马克", "李华，春节你回老家吗？", "Lǐ Huá, Chūnjié nǐ huí lǎojiā ma?", "Li Hua, tu rentres chez toi pour le Nouvel An ?", "Li Hua, are you going home for Spring Festival?"),
        ln("李华", "当然！每年春节，各地的人都要回家过年，谁都不想一个人过。", "Dāngrán! Měi nián Chūnjié, gè dì de rén dōu yào huí jiā guònián, shéi dōu bù xiǎng yí ge rén guò.", "Bien sûr ! Chaque année, les gens de toutes les régions rentrent fêter le Nouvel An : personne ne veut le passer seul.", "Of course! Every year people everywhere go home for the New Year — nobody wants to spend it alone."),
        ln("马克", "按照传统，春节要做什么？", "Ànzhào chuántǒng, Chūnjié yào zuò shénme?", "Selon la tradition, qu'est-ce qu'on fait pour le Nouvel An ?", "Traditionally, what do people do at Spring Festival?"),
        ln("李华", "贴春联、包饺子、放鞭炮、给红包等等。除夕晚上，全家人一起吃一顿年夜饭。", "Tiē chūnlián, bāo jiǎozi, fàng biānpào, gěi hóngbāo děng děng. Chúxī wǎnshang, quánjiārén yìqǐ chī yí dùn niányèfàn.", "On colle des sentences sur les portes, on fait des raviolis, on tire des pétards, on offre des enveloppes rouges… Le soir du réveillon, toute la famille dîne ensemble.", "We put up couplets, make dumplings, set off firecrackers, give red envelopes and so on. On New Year's Eve, the whole family has the reunion dinner together."),
        ln("马克", "春节是哪一天？每年都不一样吗？", "Chūnjié shì nǎ yì tiān? Měi nián dōu bù yíyàng ma?", "C'est quel jour, le Nouvel An ? Ça change chaque année ?", "What day is Spring Festival? Is it different every year?"),
        ln("李华", "对，春节是根据农历算的，一般在一月底或者二月。", "Duì, Chūnjié shì gēnjù nónglì suàn de, yìbān zài yī yuè dǐ huòzhě èr yuè.", "Oui, il est calculé d'après le calendrier lunaire ; en général fin janvier ou en février.", "Yes, it's based on the lunar calendar — usually late January or February."),
        ln("马克", "除了春节，中国还有其他重要的节日吗？", "Chúle Chūnjié, Zhōngguó hái yǒu qítā zhòngyào de jiérì ma?", "À part le Nouvel An, il y a d'autres fêtes importantes en Chine ?", "Besides Spring Festival, are there other important festivals in China?"),
        ln("李华", "有啊，中秋节、端午节等。中秋节大家吃月饼、看月亮。", "Yǒu a, Zhōngqiū Jié, Duānwǔ Jié děng. Zhōngqiū Jié dàjiā chī yuèbing, kàn yuèliang.", "Oui : la fête de la mi-automne, la fête des bateaux-dragons… À la mi-automne, on mange des gâteaux de lune et on admire la lune.", "Sure — Mid-Autumn, Dragon Boat and others. At Mid-Autumn, everyone eats mooncakes and admires the moon."),
        ln("马克", "端午节呢？", "Duānwǔ Jié ne?", "Et la fête des bateaux-dragons ?", "And the Dragon Boat Festival?"),
        ln("李华", "端午节吃粽子、看龙舟比赛。我去年去看了一场，热闹极了！", "Duānwǔ Jié chī zòngzi, kàn lóngzhōu bǐsài. Wǒ qùnián qù kàn le yì chǎng, rènao jí le!", "On mange des zongzi et on regarde les courses de bateaux-dragons. J'en ai vu une l'an dernier, quelle ambiance !", "We eat zongzi and watch dragon boat races. I went to one last year — it was so lively!"),
        ln("马克", "真想去看看！今年春节我能跟你回一趟老家吗？", "Zhēn xiǎng qù kànkan! Jīnnián Chūnjié wǒ néng gēn nǐ huí yí tàng lǎojiā ma?", "J'aimerais trop voir ça ! Je peux venir avec toi dans ta famille pour le Nouvel An ?", "I'd love to see that! Could I come home with you this Spring Festival?"),
        ln("李华", "当然可以！我爸妈一定很欢迎你。另外，别忘了带点儿礼物。", "Dāngrán kěyǐ! Wǒ bà mā yídìng hěn huānyíng nǐ. Lìngwài, bié wàng le dài diǎnr lǐwù.", "Bien sûr ! Mes parents seront ravis. Et n'oublie pas d'apporter un petit cadeau.", "Of course! My parents will be delighted. Oh, and don't forget to bring a little gift."),
      ],
    },
    vocab: ["春节", "老家", "过年", "各", "传统", "按照", "根据", "饺子", "红包", "等等", "除夕", "顿", "农历", "其他", "节日", "中秋节", "月饼", "月亮", "比赛", "热闹", "趟", "另外", "欢迎", "礼物", "庆祝", "当然", "一般", "全家", "场", "遍", "次"],
    grammar: ["hsk3-g37", "hsk3-g38", "hsk3-g39", "hsk3-g40", "hsk3-g41"],
    culture: {
      title: t("Les enveloppes rouges et la grande migration", "Red envelopes and the great migration"),
      body: t(
        "Avant le Nouvel An a lieu le **春运** (chūnyùn), la plus grande migration humaine au monde : des centaines de millions de trajets en quelques semaines pour rentrer en famille.\n\nPendant la fête, on offre des **红包** (enveloppes rouges contenant de l'argent), surtout aux enfants et aux aînés. On évite les montants avec le chiffre **4** (四 sì ressemble à 死 sǐ, « mourir ») et on préfère les nombres pairs ou avec **8** (八 bā, qui évoque 发 fā, « s'enrichir »). Aujourd'hui, beaucoup de 红包 sont **numériques**, envoyés sur WeChat — c'est même devenu un jeu dans les groupes familiaux !",
        "Before New Year comes **春运** (chūnyùn), the largest human migration on Earth: hundreds of millions of trips in a few weeks as people head home.\n\nDuring the festival, people give **红包** (red envelopes with money), especially to children and elders. Amounts containing **4** are avoided (四 sì sounds like 死 sǐ, \"death\"), while even numbers or **8** (八 bā, evoking 发 fā, \"to prosper\") are preferred. Today many 红包 are **digital**, sent on WeChat — it's even become a game in family chat groups!"
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Selon la tradition… » (on suit une coutume)", "\"According to tradition…\" (following a custom)"),
        options: ["根据传统，……", "按照传统，……", "关于传统，……", "对于传统，……"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("« Je suis rentré (faire un aller-retour) dans ma ville natale. »", "\"I made a trip back to my hometown.\""),
        options: ["我回了一顿老家。", "我回了一场老家。", "我回了一趟老家。", "我回了一遍老家。"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: t("« Je ne mange rien. »", "\"I don't eat anything.\""),
        options: ["我不什么都吃。", "我什么都不吃。", "我都什么不吃。", "我什么不都吃。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "",
        after: "天气预报，明天会下雪。",
        options: ["按照", "根据", "关于", "另外"],
        answer: 1,
        tr: t("D'après la météo, il va neiger demain.", "According to the forecast, it'll snow tomorrow."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "除夕晚上，全家人一起吃一",
        after: "年夜饭。",
        options: ["趟", "顿", "遍", "场"],
        answer: 1,
        tr: t("Le soir du réveillon, toute la famille partage le dîner du Nouvel An.", "On New Year's Eve, the whole family has the reunion dinner."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这个办法不行，我们试试",
        after: "一个吧。",
        options: ["其他", "各", "另外", "每"],
        answer: 2,
        tr: t("Cette méthode ne marche pas, essayons-en une autre.", "This method doesn't work, let's try another."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["春节的时候，", "谁", "都", "想", "回家"],
        tr: t("Au Nouvel An, tout le monde veut rentrer chez soi.", "At Spring Festival, everyone wants to go home."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["这个故事", "我", "听过", "好几遍", "了"],
        tr: t("Cette histoire, je l'ai entendue plusieurs fois.", "I've heard this story several times."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "去过", "北京、上海", "等", "城市"],
        tr: t("Je suis allé dans des villes comme Pékin et Shanghai.", "I've been to cities like Beijing and Shanghai."),
      },
      {
        type: "listen",
        zh: "中秋节大家吃月饼、看月亮。",
        options: ["春节大家吃饺子、放鞭炮。", "中秋节大家吃月饼、看月亮。", "端午节大家吃粽子、看比赛。", "中秋节大家吃饺子、看月亮。"],
        answer: 1,
        tr: t("À la mi-automne, on mange des gâteaux de lune et on admire la lune.", "At Mid-Autumn, everyone eats mooncakes and admires the moon."),
      },
      {
        type: "listen",
        zh: "春节是根据农历算的。",
        options: ["春节是按照老师说的做的。", "中秋节是根据农历算的。", "春节是根据农历算的。", "春节不是根据农历算的。"],
        answer: 2,
        tr: t("La date du Nouvel An est calculée d'après le calendrier lunaire.", "Spring Festival is calculated according to the lunar calendar."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("红包", "hóngbāo", "enveloppe rouge", "red envelope"),
          mp("除夕", "chúxī", "réveillon du Nouvel An", "New Year's Eve"),
          mp("农历", "nónglì", "calendrier lunaire", "lunar calendar"),
          mp("月饼", "yuèbing", "gâteau de lune", "mooncake"),
          mp("传统", "chuántǒng", "tradition", "tradition"),
          mp("热闹", "rènao", "animé, festif", "lively"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quel signe sépare les éléments d'une énumération en chinois ?", "Which mark separates list items in Chinese?"),
        options: ["，", "。", "、", "；"],
        answer: 2,
      },
    ],
  },

  // ─────────────────────────────── L09 — Education system
  {
    id: "hsk3-l09",
    level: 3,
    order: 9,
    title: t("Le gaokao et moi", "The gaokao and me"),
    subtitle: t("Comparer les systèmes éducatifs", "Comparing education systems"),
    theme: "school",
    goals: [
      t("Parler de sa scolarité et des examens", "Talk about your schooling and exams"),
      t("Comparer avec précision : 不如, 没有……那么, 比……得多, 跟……一样", "Compare precisely: 不如, 没有……那么, 比……得多, 跟……一样"),
      t("Exprimer une contrainte avec 只好", "Express having no choice with 只好"),
      t("Tirer une conclusion avec 既然……就", "Draw a conclusion with 既然……就"),
    ],
    dialogue: {
      context: t(
        "Lucie, étudiante française, discute avec Zhang Wei de l'école en Chine et en France.",
        "Lucie, a French student, talks with Zhang Wei about school in China and France."
      ),
      lines: [
        ln("露西", "张伟，听说中国的高中生学习特别辛苦，是真的吗？", "Zhāng Wěi, tīngshuō Zhōngguó de gāozhōngshēng xuéxí tèbié xīnkǔ, shì zhēn de ma?", "Zhang Wei, il paraît que les lycéens chinois travaillent très dur, c'est vrai ?", "Zhang Wei, I hear Chinese high-school students study really hard — is that true?"),
        ln("张伟", "是真的。我高三的时候，每天早上六点起床，晚上十一点才睡觉。", "Shì zhēn de. Wǒ gāosān de shíhou, měi tiān zǎoshang liù diǎn qǐchuáng, wǎnshang shíyī diǎn cái shuìjiào.", "Oui. En terminale, je me levais à six heures et je ne me couchais pas avant onze heures.", "It is. In my final year, I got up at six every morning and didn't go to bed till eleven."),
        ln("露西", "法国的高中生没有你们那么忙。", "Fǎguó de gāozhōngshēng méiyǒu nǐmen nàme máng.", "Les lycéens français ne sont pas aussi occupés que vous.", "French high-schoolers aren't as busy as you."),
        ln("张伟", "因为有高考。高考比其他考试难得多，它决定你能上哪所大学。", "Yīnwèi yǒu gāokǎo. Gāokǎo bǐ qítā kǎoshì nán de duō, tā juédìng nǐ néng shàng nǎ suǒ dàxué.", "C'est à cause du gaokao. Il est bien plus dur que les autres examens, et c'est lui qui décide de ton université.", "Because of the gaokao. It's much harder than other exams, and it decides which university you can go to."),
        ln("露西", "法国也有毕业考试，可是跟高考不一样，压力没有那么大。", "Fǎguó yě yǒu bìyè kǎoshì, kěshì gēn gāokǎo bù yíyàng, yālì méiyǒu nàme dà.", "En France aussi il y a un examen de fin d'études, mais ce n'est pas comme le gaokao, il y a moins de pression.", "France has a final exam too, but it's different from the gaokao — there's less pressure."),
        ln("张伟", "我第一次高考考得不好，不如我的同学，只好又复习了一年。", "Wǒ dì-yī cì gāokǎo kǎo de bù hǎo, bùrú wǒ de tóngxué, zhǐhǎo yòu fùxí le yì nián.", "La première fois, je l'ai raté : j'ai eu de moins bons résultats que mes camarades, alors j'ai dû refaire une année.", "The first time I did badly — worse than my classmates — so I had to study another year."),
        ln("露西", "那一定很累吧！第二年考得怎么样？", "Nà yídìng hěn lèi ba! Dì-èr nián kǎo de zěnmeyàng?", "Ça a dû être épuisant ! Et la deuxième fois ?", "That must have been exhausting! How did the second year go?"),
        ln("张伟", "比第一年好多了，我考上了现在的大学。", "Bǐ dì-yī nián hǎo duō le, wǒ kǎoshang le xiànzài de dàxué.", "Beaucoup mieux, j'ai été admis dans mon université actuelle.", "Much better than the first — I got into my current university."),
        ln("露西", "你的专业是什么？", "Nǐ de zhuānyè shì shénme?", "Tu étudies quoi ?", "What's your major?"),
        ln("张伟", "计算机。不过我其实更喜欢历史。", "Jìsuànjī. Búguò wǒ qíshí gèng xǐhuan lìshǐ.", "L'informatique. Mais en fait, je préfère l'histoire.", "Computer science. But actually I prefer history."),
        ln("露西", "既然你喜欢历史，为什么不换专业呢？", "Jìrán nǐ xǐhuan lìshǐ, wèi shénme bú huàn zhuānyè ne?", "Puisque tu aimes l'histoire, pourquoi ne pas changer de filière ?", "Since you like history, why not switch majors?"),
        ln("张伟", "我也在考虑。既然还年轻，就应该做自己喜欢的事！", "Wǒ yě zài kǎolǜ. Jìrán hái niánqīng, jiù yīnggāi zuò zìjǐ xǐhuan de shì!", "J'y réfléchis. Puisqu'on est encore jeunes, autant faire ce qu'on aime !", "I'm thinking about it. Since I'm still young, I should do what I love!"),
      ],
    },
    vocab: ["高中", "辛苦", "起床", "考试", "高考", "其他", "决定", "所", "大学", "毕业", "压力", "不如", "只好", "复习", "考上", "专业", "计算机", "历史", "其实", "既然", "考虑", "年轻", "成绩", "数学", "作业", "教育", "学期", "图书馆", "留学", "小学", "中学"],
    grammar: ["hsk3-g42", "hsk3-g43", "hsk3-g44", "hsk3-g45", "hsk3-g46"],
    culture: {
      title: t("Le gaokao, un rite national", "The gaokao, a national rite"),
      body: t(
        "Chaque année, les **7 et 8 juin**, plus de dix millions de lycéens passent le **高考** (gāokǎo), le concours d'entrée à l'université. Tout le pays retient son souffle : on interdit les klaxons près des centres d'examen, la police escorte parfois les candidats en retard, et les parents attendent devant les grilles.\n\nLa scolarité obligatoire dure **neuf ans** (九年义务教育) : six ans de primaire (小学) et trois ans de collège (初中), suivis de trois ans de lycée (高中). Beaucoup d'élèves suivent aussi des cours du soir ou du week-end (补习班).",
        "Every year on **7 and 8 June**, over ten million students sit the **高考** (gāokǎo), the university entrance exam. The whole country holds its breath: honking is banned near exam centres, police sometimes escort late candidates, and parents wait outside the gates.\n\nCompulsory education lasts **nine years** (九年义务教育): six years of primary school (小学) and three of junior high (初中), followed by three years of senior high (高中). Many students also attend evening or weekend cram classes (补习班)."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Il est beaucoup plus grand que moi. »", "\"He's much taller than me.\""),
        options: ["他比我很高。", "他比我高得多。", "他比我非常高。", "他比我多高。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Négation naturelle de 他比我高 :", "Natural negative of 他比我高:"),
        options: ["他比我不高。", "他不比我很高。", "他没有我高。", "他比我没高。"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: t("« Je ne suis pas comme lui. »", "\"I'm not the same as him.\""),
        options: ["我不跟他一样。", "我跟他不一样。", "我跟他一样不。", "我没跟他一样。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "图书馆关门了，我们",
        after: "回宿舍学习。",
        options: ["只好", "最好", "既然", "不如"],
        answer: 0,
        tr: t("La bibliothèque était fermée, on a dû retourner réviser au dortoir.", "The library was closed, so we had to go back to the dorm to study."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "既然你喜欢画画，",
        after: "去学美术吧。",
        options: ["才", "所以", "就", "都"],
        answer: 2,
        tr: t("Puisque tu aimes dessiner, étudie donc les beaux-arts.", "Since you like drawing, go and study art."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这次考试比上次好",
        after: "。",
        options: ["一点儿", "很", "非常", "太"],
        answer: 0,
        tr: t("Cet examen s'est un peu mieux passé que le précédent.", "This exam went a bit better than the last."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["这所大学", "不如", "那所大学", "有名"],
        tr: t("Cette université est moins connue que l'autre.", "This university isn't as famous as that one."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我妹妹", "比我", "小", "五岁"],
        tr: t("Ma petite sœur a cinq ans de moins que moi.", "My younger sister is five years younger than me."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["小学的作业", "没有", "中学", "那么多"],
        tr: t("À l'école primaire, il y a moins de devoirs qu'au collège.", "Primary school homework isn't as heavy as secondary school."),
      },
      {
        type: "listen",
        zh: "高考比其他考试难得多。",
        options: ["高考没有其他考试难。", "高考跟其他考试一样难。", "高考比其他考试难得多。", "其他考试比高考难得多。"],
        answer: 2,
        tr: t("Le gaokao est bien plus difficile que les autres examens.", "The gaokao is much harder than other exams."),
      },
      {
        type: "listen",
        zh: "既然还年轻，就应该做自己喜欢的事。",
        options: ["既然还年轻，就应该做自己喜欢的事。", "因为还年轻，所以不知道喜欢什么。", "虽然还年轻，但是要做自己的事。", "既然不年轻了，就别做喜欢的事。"],
        answer: 0,
        tr: t("Puisqu'on est encore jeunes, autant faire ce qu'on aime.", "Since we're still young, we should do what we love."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("专业", "zhuānyè", "spécialité, filière", "major"),
          mp("复习", "fùxí", "réviser", "review, revise"),
          mp("成绩", "chéngjì", "notes, résultats", "grades"),
          mp("毕业", "bìyè", "obtenir son diplôme", "graduate"),
          mp("压力", "yālì", "pression, stress", "pressure"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle est la différence entre 只好 et 最好 ?", "What's the difference between 只好 and 最好?"),
        options: [
          t("只好 = pas le choix ; 最好 = le mieux serait de", "只好 = no choice; 最好 = had better"),
          t("Aucune différence", "No difference"),
          t("只好 = le mieux ; 最好 = pas le choix", "只好 = had better; 最好 = no choice"),
          t("只好 = seulement bien ; 最好 = très bien", "只好 = only good; 最好 = very good"),
        ],
        answer: 0,
      },
    ],
  },

  // ─────────────────────────────── L10 — Sharing opinions
  {
    id: "hsk3-l10",
    level: 3,
    order: 10,
    title: t("Grande ville ou petite ville ?", "Big city or small town?"),
    subtitle: t("Donner et défendre son opinion", "Giving and defending your opinion"),
    theme: "society",
    goals: [
      t("Donner son avis et exprimer son désaccord poliment", "Give your opinion and disagree politely"),
      t("Introduire un sujet avec 关于 / 对于", "Introduce a topic with 关于 / 对于"),
      t("Corriger et nuancer avec 不是……而是, 其实, 并不", "Correct and nuance with 不是……而是, 其实, 并不"),
      t("Faire une concession avec 尽管……还是 et exprimer l'inattendu avec 反而", "Concede with 尽管……还是 and express the unexpected with 反而"),
    ],
    dialogue: {
      context: t(
        "Gao Fei et Liu Yang, deux étudiants bientôt diplômés, débattent : où vaut-il mieux travailler ?",
        "Gao Fei and Liu Yang, two students about to graduate, debate where it's better to work."
      ),
      lines: [
        ln("高飞", "关于毕业以后去哪儿工作，你有什么看法？", "Guānyú bìyè yǐhòu qù nǎr gōngzuò, nǐ yǒu shénme kànfǎ?", "Sur la question d'où travailler après le diplôme, tu en penses quoi ?", "What's your view on where to work after graduating?"),
        ln("刘洋", "我觉得应该去大城市。大城市机会多，工资也高。", "Wǒ juéde yīnggāi qù dà chéngshì. Dà chéngshì jīhuì duō, gōngzī yě gāo.", "Je pense qu'il faut aller dans une grande ville. Il y a plus d'opportunités et les salaires sont plus élevés.", "I think you should go to a big city. More opportunities, higher salaries."),
        ln("高飞", "我不太同意。大城市工资高，可是房租更高，生活压力反而更大。", "Wǒ bú tài tóngyì. Dà chéngshì gōngzī gāo, kěshì fángzū gèng gāo, shēnghuó yālì fǎn'ér gèng dà.", "Je ne suis pas trop d'accord. Les salaires sont plus hauts, mais les loyers encore plus : au final, la vie est plus stressante.", "I don't really agree. Salaries are higher, but rents are even higher — so life is actually more stressful."),
        ln("刘洋", "对于年轻人来说，压力大一点儿并不是坏事。", "Duìyú niánqīngrén lái shuō, yālì dà yìdiǎnr bìng bú shì huài shì.", "Pour les jeunes, un peu plus de pression, ce n'est pas forcément une mauvaise chose.", "For young people, a bit more pressure isn't actually a bad thing."),
        ln("高飞", "我不是怕压力，而是觉得生活质量也很重要。", "Wǒ bú shì pà yālì, ér shì juéde shēnghuó zhìliàng yě hěn zhòngyào.", "Ce n'est pas que j'ai peur de la pression, c'est que la qualité de vie compte aussi.", "It's not that I'm afraid of pressure — I just think quality of life matters too."),
        ln("刘洋", "其实小城市现在发展得也很快。", "Qíshí xiǎo chéngshì xiànzài fāzhǎn de yě hěn kuài.", "C'est vrai que les petites villes se développent vite aussi, maintenant.", "Actually, small cities are developing fast too these days."),
        ln("高飞", "没错。而且离父母近，可以照顾他们。", "Méi cuò. Érqiě lí fùmǔ jìn, kěyǐ zhàogù tāmen.", "Exactement. Et on est près de ses parents, on peut s'occuper d'eux.", "Exactly. And you're close to your parents, so you can look after them."),
        ln("刘洋", "尽管你说得有道理，我还是想先去大城市试一试。", "Jǐnguǎn nǐ shuō de yǒu dàolǐ, wǒ háishi xiǎng xiān qù dà chéngshì shì yi shì.", "Même si tu as raison sur certains points, j'ai quand même envie de tenter ma chance dans une grande ville d'abord.", "Although you make a good point, I still want to give a big city a try first."),
        ln("高飞", "我尊重你的选择。每个人的情况不一样。", "Wǒ zūnzhòng nǐ de xuǎnzé. Měi ge rén de qíngkuàng bù yíyàng.", "Je respecte ton choix. Chacun a sa situation.", "I respect your choice. Everyone's situation is different."),
        ln("刘洋", "对。关于这个问题，并没有标准答案。", "Duì. Guānyú zhège wèntí, bìng méiyǒu biāozhǔn dá'àn.", "Oui. Sur cette question, il n'y a pas de bonne réponse.", "Right. There's no single right answer to this question."),
        ln("高飞", "说得好！那我们下次讨论什么？", "Shuō de hǎo! Nà wǒmen xià cì tǎolùn shénme?", "Bien dit ! Et la prochaine fois, on débat de quoi ?", "Well said! So what shall we debate next time?"),
        ln("刘洋", "讨论一下年轻人应不应该早结婚吧！", "Tǎolùn yíxià niánqīngrén yīng bu yīnggāi zǎo jiéhūn ba!", "Si les jeunes doivent se marier tôt ou pas !", "Whether young people should marry early!"),
      ],
    },
    vocab: ["关于", "对于", "看法", "同意", "反对", "房租", "压力", "反而", "并", "质量", "其实", "发展", "照顾", "尽管", "道理", "尊重", "选择", "情况", "标准", "答案", "讨论", "结婚", "意见", "认为", "相信", "支持", "年轻人", "父母", "机会", "工资"],
    grammar: ["hsk3-g47", "hsk3-g48", "hsk3-g49", "hsk3-g50", "hsk3-g51", "hsk3-g52"],
    culture: {
      title: t("Dire « non » sans froisser", "Saying \"no\" without offending"),
      body: t(
        "Dans une discussion en chinois, on évite souvent de dire directement **你不对** (« tu as tort »). On préfère des formules qui **préservent la face** (面子) de l'autre :\n- 你说得有道理，不过…… (tu as raison, mais…)\n- 我不太同意…… (je ne suis pas tout à fait d'accord)\n- 我的看法有点儿不一样 (mon avis est un peu différent)\n\nBeaucoup de jeunes Chinois hésitent aujourd'hui entre **北上广深** (Pékin, Shanghai, Canton, Shenzhen) et le retour dans une ville plus petite : c'est un vrai débat de société !",
        "In a Chinese discussion, people usually avoid saying **你不对** (\"you're wrong\") directly. Phrases that **save face** (面子) are preferred:\n- 你说得有道理，不过…… (you have a point, but…)\n- 我不太同意…… (I don't quite agree)\n- 我的看法有点儿不一样 (my view is a bit different)\n\nMany young Chinese today hesitate between **北上广深** (Beijing, Shanghai, Guangzhou, Shenzhen) and moving back to a smaller city — it's a real social debate!"
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["我关于这件事有意见。", "关于这件事，我有意见。", "这是一本对于音乐的书。", "我关于他很满意。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("« Ce n'est pas mon prof, c'est mon camarade. »", "\"He's not my teacher, he's my classmate.\""),
        options: ["他不是我的老师，就是我的同学。", "他不是我的老师，而是我的同学。", "他不是我的老师，但是我的同学。", "他不是我的老师，还是我的同学。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Que signifie 其实 ?", "What does 其实 mean?"),
        options: [
          t("actuellement", "currently"),
          t("en fait, en réalité", "actually, in fact"),
          t("pourtant", "yet"),
          t("finalement", "finally"),
        ],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我帮他说话，他",
        after: "生我的气。",
        options: ["反而", "其实", "并", "尽管"],
        answer: 0,
        tr: t("J'ai pris sa défense, et c'est à moi qu'il en veut !", "I stood up for him, and instead he got angry at me!"),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "网上的消息",
        after: "不都是真的。",
        options: ["反而", "并", "尽管", "关于"],
        answer: 1,
        tr: t("Les infos en ligne ne sont pas toutes vraies, loin de là.", "Not everything online is true, you know."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "尽管大家都反对，他",
        after: "坚持自己的意见。",
        options: ["就", "才", "还是", "反而"],
        answer: 2,
        tr: t("Bien que tout le monde soit contre, il maintient son avis.", "Although everyone objected, he stuck to his view."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["关于这个问题，", "每个人", "都有", "自己的看法"],
        tr: t("Sur cette question, chacun a son avis.", "Everyone has their own view on this issue."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["成功的关键", "不是聪明，", "而是", "努力"],
        tr: t("La clé du succès, ce n'est pas l'intelligence mais le travail.", "The key to success isn't intelligence, it's hard work."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["钱多", "并", "不一定", "幸福"],
        tr: t("Avoir beaucoup d'argent ne rend pas forcément heureux.", "Having lots of money doesn't necessarily make you happy."),
      },
      {
        type: "listen",
        zh: "我不是怕压力，而是觉得生活质量也很重要。",
        options: ["我很怕压力，所以生活质量不好。", "我不是怕压力，而是觉得生活质量也很重要。", "我不怕压力，也不觉得生活质量重要。", "压力不重要，生活质量也不重要。"],
        answer: 1,
        tr: t("Ce n'est pas que j'ai peur de la pression, c'est que la qualité de vie compte aussi.", "It's not that I fear pressure — quality of life matters too."),
      },
      {
        type: "listen",
        zh: "尽管你说得有道理，我还是想试一试。",
        options: ["因为你说得有道理，所以我想试一试。", "你说得没有道理，我不想试。", "尽管你说得有道理，我还是想试一试。", "即使你说得有道理，我也不想试。"],
        answer: 2,
        tr: t("Même si tu as raison, j'ai quand même envie d'essayer.", "Although you have a point, I still want to give it a go."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("看法", "kànfǎ", "avis, point de vue", "view, opinion"),
          mp("同意", "tóngyì", "être d'accord", "agree"),
          mp("反对", "fǎnduì", "s'opposer", "oppose"),
          mp("尊重", "zūnzhòng", "respecter", "respect"),
          mp("讨论", "tǎolùn", "discuter, débattre", "discuss"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle formule permet d'exprimer un désaccord poliment ?", "Which phrase expresses disagreement politely?"),
        options: ["你不对！", "你说得有道理，不过……", "你错了。", "你难道不知道吗？"],
        answer: 1,
      },
    ],
  },
];
