import type { Lesson } from "../../types";
import { t, ln, mp } from "./helpers";

export const lessons1: Lesson[] = [
  // ─────────────────────────────── L01 — Job interview
  {
    id: "hsk3-l01",
    level: 3,
    order: 1,
    title: t("L'entretien d'embauche", "The job interview"),
    subtitle: t("Présenter son parcours et ses motivations", "Presenting your background and motivation"),
    theme: "work",
    goals: [
      t("Présenter son parcours professionnel avec 曾经", "Describe your work background with 曾经"),
      t("Préciser quand, où et comment une chose s'est passée avec 是……的", "Say when, where and how something happened with 是……的"),
      t("Structurer ses arguments avec 首先……其次……最后", "Structure your arguments with 首先……其次……最后"),
      t("Donner son point de vue personnel avec 对……来说", "Give your personal point of view with 对……来说"),
    ],
    dialogue: {
      context: t(
        "Li Wen passe un entretien d'embauche avec M. Wang, directeur d'une entreprise à Pékin.",
        "Li Wen is interviewing with Mr Wang, a manager at a company in Beijing."
      ),
      lines: [
        ln("王经理", "你好，请坐。先简单介绍一下你自己吧。", "Nǐ hǎo, qǐng zuò. Xiān jiǎndān jièshào yíxià nǐ zìjǐ ba.", "Bonjour, asseyez-vous. Présentez-vous brièvement, pour commencer.", "Hello, have a seat. First, tell me a bit about yourself."),
        ln("李文", "好的。我叫李文，今年二十六岁，大学学的是经济。", "Hǎo de. Wǒ jiào Lǐ Wén, jīnnián èrshíliù suì, dàxué xué de shì jīngjì.", "Bien sûr. Je m'appelle Li Wen, j'ai 26 ans et j'ai fait des études d'économie.", "Sure. My name is Li Wen, I'm 26, and I studied economics at university."),
        ln("王经理", "你是怎么知道这个工作机会的？", "Nǐ shì zěnme zhīdào zhège gōngzuò jīhuì de?", "Comment avez-vous entendu parler de ce poste ?", "How did you hear about this job opening?"),
        ln("李文", "我是通过一个朋友知道的，他以前在这儿工作过。", "Wǒ shì tōngguò yí ge péngyou zhīdào de, tā yǐqián zài zhèr gōngzuò guo.", "Par un ami, qui a travaillé ici avant.", "Through a friend who used to work here."),
        ln("王经理", "你以前做过什么工作？", "Nǐ yǐqián zuò guo shénme gōngzuò?", "Quelle expérience professionnelle avez-vous ?", "What jobs have you done before?"),
        ln("李文", "我曾经在一家外国公司工作过两年，主要负责跟客人联系。", "Wǒ céngjīng zài yì jiā wàiguó gōngsī gōngzuò guo liǎng nián, zhǔyào fùzé gēn kèrén liánxì.", "J'ai travaillé deux ans dans une entreprise étrangère, où je m'occupais surtout de la relation client.", "I worked for a foreign company for two years, mainly in charge of liaising with clients."),
        ln("王经理", "你为什么想来我们公司？", "Nǐ wèi shénme xiǎng lái wǒmen gōngsī?", "Pourquoi voulez-vous rejoindre notre entreprise ?", "Why do you want to join our company?"),
        ln("李文", "首先，我对这个工作很感兴趣；其次，贵公司的发展机会很多；最后，这里离我家也很近。", "Shǒuxiān, wǒ duì zhège gōngzuò hěn gǎn xìngqù; qícì, guì gōngsī de fāzhǎn jīhuì hěn duō; zuìhòu, zhèlǐ lí wǒ jiā yě hěn jìn.", "D'abord, ce poste m'intéresse beaucoup ; ensuite, votre entreprise offre de nombreuses perspectives d'évolution ; enfin, c'est tout près de chez moi.", "First, I'm very interested in this job; secondly, your company offers lots of opportunities to grow; finally, it's close to where I live."),
        ln("王经理", "对你来说，工资重要还是工作环境重要？", "Duì nǐ lái shuō, gōngzī zhòngyào háishi gōngzuò huánjìng zhòngyào?", "Pour vous, qu'est-ce qui compte le plus : le salaire ou l'environnement de travail ?", "For you, what matters more: the salary or the work environment?"),
        ln("李文", "对我来说，环境更重要。我希望能跟同事们一起进步。", "Duì wǒ lái shuō, huánjìng gèng zhòngyào. Wǒ xīwàng néng gēn tóngshìmen yìqǐ jìnbù.", "Pour moi, c'est l'environnement. J'aimerais progresser avec mes collègues.", "For me, the environment matters more. I hope to grow together with my colleagues."),
        ln("王经理", "好的。我们会在一个星期内通知你面试结果。", "Hǎo de. Wǒmen huì zài yí ge xīngqī nèi tōngzhī nǐ miànshì jiéguǒ.", "Très bien. Nous vous communiquerons notre réponse d'ici une semaine.", "All right. We'll let you know the result within a week."),
        ln("李文", "谢谢王经理，希望有机会跟您一起工作！", "Xièxie Wáng jīnglǐ, xīwàng yǒu jīhuì gēn nín yìqǐ gōngzuò!", "Merci, Monsieur Wang. J'espère avoir l'occasion de travailler avec vous !", "Thank you, Mr Wang. I hope I get the chance to work with you!"),
      ],
    },
    vocab: ["面试", "经理", "介绍", "简单", "自己", "专业", "经济", "通过", "机会", "曾经", "公司", "负责", "联系", "客人", "主要", "首先", "其次", "最后", "感兴趣", "发展", "工资", "环境", "重要", "同事", "进步", "希望", "通知", "结果", "经验", "能力"],
    grammar: ["hsk3-g01", "hsk3-g02", "hsk3-g03", "hsk3-g04", "hsk3-g05"],
    culture: {
      title: t("Les codes de l'entretien en Chine", "Interview etiquette in China"),
      body: t(
        "En Chine, on s'adresse au recruteur par son **nom de famille + sa fonction** : 王经理 (directeur Wang), 李老师, 张总 (pour un PDG). Utiliser 您 plutôt que 你 est un signe de respect.\n\nLe CV (简历) comporte souvent une **photo**, l'âge et parfois la ville d'origine. On apprécie la **modestie** (谦虚) : plutôt que de se vanter, on dit 我还需要学习很多 (j'ai encore beaucoup à apprendre). Enfin, pour parler de l'entreprise de son interlocuteur, on emploie la forme honorifique **贵公司** (« votre honorable entreprise »).",
        "In China, you address the interviewer by **surname + title**: 王经理 (Manager Wang), 李老师, 张总 (for a CEO). Using 您 rather than 你 shows respect.\n\nA CV (简历) usually includes a **photo**, your age and sometimes your hometown. **Modesty** (谦虚) is valued: instead of boasting, people say 我还需要学习很多 (I still have a lot to learn). And when talking about the other person's company, use the honorific **贵公司** (\"your esteemed company\")."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle phrase met correctement en relief le moment de l'arrivée ?", "Which sentence correctly emphasises when the person arrived?"),
        options: ["我是昨天到了。", "我昨天是到了。", "我到的是昨天了。", "我是昨天到的。"],
        answer: 3,
        explain: t("是 + moment + V + 的, sans 了.", "是 + time + V + 的, with no 了."),
      },
      {
        type: "choice",
        prompt: t("Que signifie 曾经 ?", "What does 曾经 mean?"),
        options: [
          t("déjà (résultat qui compte maintenant)", "already (result matters now)"),
          t("autrefois, il m'est arrivé de (passé révolu)", "once, used to (finished past)"),
          t("jamais", "never"),
          t("bientôt", "soon"),
        ],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Quelle est la bonne forme négative ?", "Which is the correct negative form?"),
        options: ["我是不坐飞机来的。", "我不坐飞机来的。", "我不是坐飞机来的。", "我没是坐飞机来的。"],
        answer: 2,
        explain: t("La négation porte sur 是 : 不是……的.", "Negate 是 itself: 不是……的."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我是",
        after: "网站找到这份工作的。",
        options: ["通过", "为了", "关于", "对"],
        answer: 0,
        tr: t("J'ai trouvé ce travail via un site internet.", "I found this job through a website."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "首先，我有相关的经验；",
        after: "，我很喜欢这个工作。",
        options: ["曾经", "其次", "以后", "通过"],
        answer: 1,
        tr: t("D'abord, j'ai de l'expérience dans le domaine ; ensuite, ce travail me plaît beaucoup.", "First, I have relevant experience; secondly, I really like this job."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "他",
        after: "是我们公司的经理，现在去了别的公司。",
        options: ["已经", "马上", "曾经", "正在"],
        answer: 2,
        tr: t("Il a été directeur dans notre entreprise ; maintenant il est parti ailleurs.", "He used to be a manager at our company; now he's moved to another one."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "是", "坐地铁", "来", "的"],
        tr: t("Je suis venu en métro.", "I came by subway."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["对我来说，", "工作环境", "比工资", "更重要"],
        tr: t("Pour moi, l'environnement de travail compte plus que le salaire.", "For me, the work environment matters more than the salary."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "曾经", "在外国公司", "工作过", "两年"],
        tr: t("J'ai travaillé deux ans dans une entreprise étrangère.", "I once worked at a foreign company for two years."),
      },
      {
        type: "listen",
        zh: "你是怎么知道这个工作机会的？",
        options: ["你是什么时候知道这个工作机会的？", "你是怎么找到这个工作的？", "你是怎么知道这个工作机会的？", "你怎么不知道这个工作机会？"],
        answer: 2,
        tr: t("Comment as-tu appris l'existence de ce poste ?", "How did you hear about this job opening?"),
      },
      {
        type: "listen",
        zh: "我们会在一个星期内通知你面试结果。",
        options: ["我们会在一个星期内通知你面试结果。", "我们会在一个月内通知你面试时间。", "我们一个星期以后跟你面试。", "你会在一个星期内通知我们结果。"],
        answer: 0,
        tr: t("Nous te communiquerons le résultat de l'entretien d'ici une semaine.", "We'll let you know the interview result within a week."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("面试", "miànshì", "entretien", "interview"),
          mp("工资", "gōngzī", "salaire", "salary"),
          mp("同事", "tóngshì", "collègue", "colleague"),
          mp("经验", "jīngyàn", "expérience", "experience"),
          mp("负责", "fùzé", "être responsable de", "be in charge of"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["对我说，这个工作很合适。", "对我来说，这个工作很合适。", "为我来说，这个工作很合适。", "我对来说，这个工作很合适。"],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L02 — Moving city
  {
    id: "hsk3-l02",
    level: 3,
    order: 2,
    title: t("Nouvelle ville, nouvel appart", "New city, new flat"),
    subtitle: t("Déménager et s'installer à Shanghai", "Moving and settling in Shanghai"),
    theme: "home",
    goals: [
      t("Dire ce qu'on fait des objets avec la phrase en 把", "Say what you do with objects using 把 sentences"),
      t("Indiquer où l'on pose ou à qui l'on remet quelque chose (把……放在 / 交给)", "Say where you put things or who you give them to (把……放在 / 交给)"),
      t("Décrire un mouvement avec les compléments directionnels composés", "Describe movement with compound directional complements"),
      t("Décrire un lieu avec les phrases d'existence (桌子上放着……)", "Describe a place with existential sentences (桌子上放着……)"),
    ],
    dialogue: {
      context: t(
        "Xiao Lin vient d'emménager à Shanghai. Son ami David l'aide à monter les cartons.",
        "Xiao Lin has just moved to Shanghai. His friend David is helping him carry boxes upstairs."
      ),
      lines: [
        ln("大卫", "小林，箱子都搬上来了吗？", "Xiǎo Lín, xiāngzi dōu bān shanglai le ma?", "Xiao Lin, tous les cartons sont montés ?", "Xiao Lin, have all the boxes been brought up?"),
        ln("小林", "还没有，楼下还放着三个大箱子。", "Hái méiyǒu, lóu xià hái fàng zhe sān ge dà xiāngzi.", "Pas encore, il reste trois gros cartons en bas.", "Not yet, there are still three big boxes downstairs."),
        ln("大卫", "没关系，我去把它们搬上来。", "Méi guānxi, wǒ qù bǎ tāmen bān shanglai.", "Pas de souci, je vais les monter.", "No problem, I'll go bring them up."),
        ln("小林", "太谢谢你了！你把那个小箱子放在厨房吧，里面是碗和盘子。", "Tài xièxie nǐ le! Nǐ bǎ nàge xiǎo xiāngzi fàng zài chúfáng ba, lǐmiàn shì wǎn hé pánzi.", "Merci mille fois ! Pose le petit carton dans la cuisine, il y a les bols et les assiettes dedans.", "Thanks so much! Put that small box in the kitchen — it's got the bowls and plates."),
        ln("大卫", "好的。这个房子真不错，除了厨房有点儿小以外，别的都很好。", "Hǎo de. Zhège fángzi zhēn búcuò, chúle chúfáng yǒudiǎnr xiǎo yǐwài, bié de dōu hěn hǎo.", "D'accord. Il est super, cet appart : à part la cuisine un peu petite, tout est bien.", "OK. This place is really nice — apart from the kitchen being a bit small, everything's great."),
        ln("小林", "是啊，而且离公司很近，走路十分钟就到了。", "Shì a, érqiě lí gōngsī hěn jìn, zǒulù shí fēnzhōng jiù dào le.", "Oui, et en plus c'est près du bureau : dix minutes à pied.", "Yeah, and it's close to the office too — just ten minutes' walk."),
        ln("大卫", "你为什么决定搬到上海来？", "Nǐ wèi shénme juédìng bāndào Shànghǎi lái?", "Pourquoi tu as décidé de venir t'installer à Shanghai ?", "Why did you decide to move to Shanghai?"),
        ln("小林", "公司让我到上海的办公室工作。除了工作以外，我也想换一个环境。", "Gōngsī ràng wǒ dào Shànghǎi de bàngōngshì gōngzuò. Chúle gōngzuò yǐwài, wǒ yě xiǎng huàn yí ge huánjìng.", "Ma boîte m'a muté au bureau de Shanghai. Et à part le travail, j'avais aussi envie de changer d'air.", "My company sent me to the Shanghai office. Besides work, I also wanted a change of scene."),
        ln("大卫", "对了，刚才门口站着一个人，好像在找你。", "Duì le, gāngcái ménkǒu zhàn zhe yí ge rén, hǎoxiàng zài zhǎo nǐ.", "Au fait, il y avait quelqu'un devant la porte tout à l'heure, on aurait dit qu'il te cherchait.", "By the way, there was someone standing at the door just now — looked like they were looking for you."),
        ln("小林", "那一定是房东。她说要把钥匙交给我。", "Nà yídìng shì fángdōng. Tā shuō yào bǎ yàoshi jiāogěi wǒ.", "Ça doit être la propriétaire. Elle a dit qu'elle devait me remettre les clés.", "That must be the landlady. She said she'd hand me the keys."),
        ln("大卫", "你快下去吧，我在这儿把书放到桌子上。", "Nǐ kuài xiàqu ba, wǒ zài zhèr bǎ shū fàngdào zhuōzi shang.", "Descends vite, moi je mets les livres sur la table.", "Go on down, I'll put the books on the table."),
        ln("小林", "好，我马上回来。晚上我请你吃饭！", "Hǎo, wǒ mǎshàng huílai. Wǎnshang wǒ qǐng nǐ chīfàn!", "OK, je reviens tout de suite. Ce soir, je t'invite à dîner !", "OK, I'll be right back. Dinner's on me tonight!"),
      ],
    },
    vocab: ["搬家", "搬", "箱子", "楼下", "厨房", "碗", "盘子", "除了", "以外", "而且", "离", "决定", "办公室", "环境", "换", "门口", "站", "房东", "钥匙", "交", "放", "挂", "墙", "邻居", "房租", "收拾", "干净", "客厅", "沙发", "地图", "城市", "行李"],
    grammar: ["hsk3-g06", "hsk3-g07", "hsk3-g08", "hsk3-g09", "hsk3-g10"],
    culture: {
      title: t("Louer et pendre la crémaillère", "Renting and house-warming"),
      body: t(
        "Dans les grandes villes chinoises, la location se fait souvent en **押一付三** (yā yī fù sān) : on verse **un mois de caution** et on paie **trois mois de loyer d'avance**. On passe généralement par une agence (中介).\n\nUne fois installé, on invite ses proches pour **温锅** (« réchauffer la marmite ») ou **暖房** : c'est la crémaillère ! Les invités apportent des fruits, des plantes ou des objets porte-bonheur. Beaucoup de familles choisissent aussi un **jour faste** (好日子) dans le calendrier pour emménager.",
        "In big Chinese cities, renting often works as **押一付三** (yā yī fù sān): you pay **one month's deposit** and **three months' rent upfront**, usually through an agency (中介).\n\nOnce settled in, you invite friends and family to **温锅** (\"warm the pot\") or **暖房** — a house-warming party! Guests bring fruit, plants or lucky objects. Many families also pick an **auspicious day** (好日子) from the calendar to move in."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle phrase en 把 est correcte ?", "Which 把 sentence is correct?"),
        options: ["我把饭吃。", "我把一本书看完了。", "我把那本书看完了。", "我把中文喜欢。"],
        answer: 2,
        explain: t("Objet défini + verbe suivi d'un complément.", "Definite object + verb followed by a complement."),
      },
      {
        type: "choice",
        prompt: t("« Pose les clés sur la table. »", "\"Put the keys on the table.\""),
        options: ["你放钥匙在桌子上。", "你把钥匙放在桌子上。", "你把钥匙放桌子。", "你在桌子上把钥匙放。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Tu es dans l'appartement. Ton ami est dehors. Tu lui dis :", "You're inside the flat. Your friend is outside. You say:"),
        options: ["快进去吧！", "快出来吧！", "快进来吧！", "快下去吧！"],
        answer: 2,
        explain: t("Le mouvement va vers toi : 进来.", "The movement is towards you: 进来."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "请把这封信交",
        after: "房东。",
        options: ["在", "给", "到", "成"],
        answer: 1,
        tr: t("Remets cette lettre au propriétaire, s'il te plaît.", "Please give this letter to the landlord."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "除了厨房以外，别的房间",
        after: "很大。",
        options: ["还", "也", "都", "就"],
        answer: 2,
        tr: t("À part la cuisine, toutes les pièces sont grandes.", "Apart from the kitchen, all the rooms are big."),
        explain: t("Exclusion → 都.", "Exclusion → 都."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "墙上挂",
        after: "一张城市地图。",
        options: ["着", "在", "了过", "的"],
        answer: 0,
        tr: t("Un plan de la ville est accroché au mur.", "A city map is hanging on the wall."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我们", "把沙发", "搬到", "客厅", "吧"],
        tr: t("Mettons le canapé dans le salon.", "Let's move the sofa into the living room."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["他", "走进", "教室", "来", "了"],
        tr: t("Il est entré dans la salle de classe.", "He walked into the classroom."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["除了房租，", "我", "还要", "付水电费"],
        tr: t("En plus du loyer, je dois aussi payer l'eau et l'électricité.", "Besides rent, I also have to pay for water and electricity."),
      },
      {
        type: "listen",
        zh: "楼下还放着三个大箱子。",
        options: ["楼上还放着三个大箱子。", "楼下还放着三个大箱子。", "楼下还有四个小箱子。", "楼下放着三个大桌子。"],
        answer: 1,
        tr: t("Il reste trois gros cartons en bas.", "There are still three big boxes downstairs."),
      },
      {
        type: "listen",
        zh: "我们楼里搬来了一位新邻居。",
        options: ["我们楼里搬走了一位老邻居。", "我们楼里来了一位新同事。", "我们楼里搬来了一位新邻居。", "我们搬到了一个新楼里。"],
        answer: 2,
        tr: t("Un nouveau voisin a emménagé dans notre immeuble.", "A new neighbour has moved into our building."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("房东", "fángdōng", "propriétaire", "landlord"),
          mp("钥匙", "yàoshi", "clé", "key"),
          mp("邻居", "línjū", "voisin", "neighbour"),
          mp("房租", "fángzū", "loyer", "rent"),
          mp("厨房", "chúfáng", "cuisine", "kitchen"),
          mp("箱子", "xiāngzi", "carton, caisse", "box"),
        ],
      },
      {
        type: "choice",
        prompt: t("« En plus du chinois, il parle aussi français. »", "\"Besides Chinese, he also speaks French.\""),
        options: ["除了中文，他都会说法语。", "除了中文，他还会说法语。", "除了中文，他不会说法语。", "他除了会说法语，都会中文。"],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L03 — Health & habits
  {
    id: "hsk3-l03",
    level: 3,
    order: 3,
    title: t("Chez le médecin", "At the doctor's"),
    subtitle: t("Santé et bonnes habitudes", "Health and good habits"),
    theme: "health",
    goals: [
      t("Décrire ses symptômes et ses habitudes", "Describe your symptoms and habits"),
      t("Exprimer une condition suffisante ou nécessaire (只要……就 / 只有……才)", "Express sufficient or necessary conditions (只要……就 / 只有……才)"),
      t("Parler d'une évolution avec 越来越 et 越……越", "Talk about change with 越来越 and 越……越"),
      t("Donner des conseils avec 必须, 得, 不用 et 稍微", "Give advice with 必须, 得, 不用 and 稍微"),
    ],
    dialogue: {
      context: t(
        "Ma Li, épuisée par son travail, consulte le docteur Zhang.",
        "Ma Li, worn out by work, goes to see Dr Zhang."
      ),
      lines: [
        ln("张医生", "你哪儿不舒服？", "Nǐ nǎr bù shūfu?", "Qu'est-ce qui ne va pas ?", "What seems to be the problem?"),
        ln("马丽", "我最近总是很累，晚上也睡不好。", "Wǒ zuìjìn zǒngshì hěn lèi, wǎnshang yě shuì bu hǎo.", "Ces derniers temps, je suis tout le temps fatiguée et je dors mal.", "I've been tired all the time lately, and I don't sleep well."),
        ln("张医生", "你每天几点睡觉？", "Nǐ měi tiān jǐ diǎn shuìjiào?", "À quelle heure vous couchez-vous ?", "What time do you go to bed?"),
        ln("马丽", "一般十二点以后，有时候还要加班。", "Yìbān shí'èr diǎn yǐhòu, yǒu shíhou hái yào jiābān.", "En général après minuit, et parfois je fais des heures sup.", "Usually after midnight, and sometimes I work overtime too."),
        ln("张医生", "你锻炼身体吗？", "Nǐ duànliàn shēntǐ ma?", "Vous faites du sport ?", "Do you exercise?"),
        ln("马丽", "我从来不锻炼，工作太忙了。", "Wǒ cónglái bú duànliàn, gōngzuò tài máng le.", "Jamais, le travail me prend tout mon temps.", "Never — work's too busy."),
        ln("张医生", "这可不行。你必须早点儿睡觉。只有休息好了，身体才会健康。", "Zhè kě bù xíng. Nǐ bìxū zǎo diǎnr shuìjiào. Zhǐyǒu xiūxi hǎo le, shēntǐ cái huì jiànkāng.", "Ça ne va pas du tout. Vous devez vous coucher plus tôt. Il n'y a qu'en vous reposant bien que vous serez en bonne santé.", "That won't do. You must go to bed earlier. Only if you rest properly will you be healthy."),
        ln("马丽", "可是我越想睡，越睡不着。", "Kěshì wǒ yuè xiǎng shuì, yuè shuì bu zháo.", "Mais plus j'essaie de dormir, moins j'y arrive.", "But the more I try to sleep, the less I can."),
        ln("张医生", "睡觉前别看手机。只要每天运动半个小时，就会睡得好一些。", "Shuìjiào qián bié kàn shǒujī. Zhǐyào měi tiān yùndòng bàn ge xiǎoshí, jiù huì shuì de hǎo yìxiē.", "Ne regardez pas votre téléphone avant de dormir. Il suffit de bouger une demi-heure par jour pour mieux dormir.", "No phone before bed. As long as you exercise for half an hour a day, you'll sleep better."),
        ln("马丽", "我需要吃药吗？", "Wǒ xūyào chī yào ma?", "Est-ce que j'ai besoin de médicaments ?", "Do I need medicine?"),
        ln("张医生", "不用吃药。不过你得稍微少喝一点儿咖啡。", "Bú yòng chī yào. Búguò nǐ děi shāowēi shǎo hē yìdiǎnr kāfēi.", "Pas besoin. Mais il faudra boire un peu moins de café.", "No need for medicine. But you'll have to drink a bit less coffee."),
        ln("马丽", "好的，我从明天开始改变我的生活习惯。", "Hǎo de, wǒ cóng míngtiān kāishǐ gǎibiàn wǒ de shēnghuó xíguàn.", "D'accord, dès demain je change mes habitudes.", "OK, starting tomorrow I'll change my habits."),
      ],
    },
    vocab: ["舒服", "最近", "总是", "一般", "加班", "锻炼", "身体", "从来", "必须", "休息", "健康", "只有", "只要", "越", "运动", "需要", "药", "不用", "稍微", "咖啡", "改变", "生活", "习惯", "医生", "感冒", "发烧", "检查", "注意", "睡着", "不过"],
    grammar: ["hsk3-g11", "hsk3-g12", "hsk3-g13", "hsk3-g14", "hsk3-g15", "hsk3-g16"],
    culture: {
      title: t("« Bois de l'eau chaude ! »", "\"Drink hot water!\""),
      body: t(
        "Si tu dis à un ami chinois que tu es malade, la première réponse sera souvent **多喝热水** (« bois beaucoup d'eau chaude ») ! Selon la médecine traditionnelle chinoise (中医), le froid affaiblit le corps : on évite les boissons glacées, surtout quand on est malade.\n\nLes Chinois accordent aussi une grande importance à **养生** (yǎngshēng, « nourrir la vie ») : se coucher tôt, faire du **太极拳** (tai-chi) au parc le matin ou danser le soir sur les places (**广场舞**), très populaire chez les retraités.",
        "Tell a Chinese friend you're ill, and the first answer will often be **多喝热水** (\"drink lots of hot water\")! In traditional Chinese medicine (中医), cold weakens the body, so people avoid iced drinks, especially when unwell.\n\nChinese people also care a lot about **养生** (yǎngshēng, \"nourishing life\"): going to bed early, practising **太极拳** (tai chi) in the park in the morning, or evening **square dancing** (广场舞), hugely popular with retirees."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Il suffit de faire du sport tous les jours pour être en forme. »", "\"As long as you exercise every day, you'll be fit.\""),
        options: ["只有每天运动，身体就好。", "只要每天运动，身体就会好。", "只要每天运动，身体才会好。", "每天运动只要，身体就好。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « Tu n'as pas besoin de venir » ?", "How do you say \"You don't need to come\"?"),
        options: ["你不必须来。", "你不得来。", "你不用来。", "你没必须来。"],
        answer: 2,
        explain: t("La négation de 必须 / 得 est 不用 (ou 不必).", "The negative of 必须 / 得 is 不用 (or 不必)."),
      },
      {
        type: "choice",
        prompt: t("Dans 我得走了, comment se prononce 得 ?", "In 我得走了, how is 得 pronounced?"),
        options: ["dé", "de", "děi", "dài"],
        answer: 2,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "只有休息好了，身体",
        after: "会健康。",
        options: ["就", "才", "都", "也"],
        answer: 1,
        tr: t("Il n'y a qu'en se reposant bien qu'on est en bonne santé.", "Only if you rest well will you be healthy."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我爷爷",
        after: "不抽烟。",
        options: ["从来", "曾经", "一直在", "已经"],
        answer: 0,
        tr: t("Mon grand-père ne fume jamais.", "My grandfather never smokes."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "请",
        after: "等一下，医生马上来。",
        options: ["稍微", "越来越", "从来", "必须不"],
        answer: 0,
        tr: t("Patientez un instant, le médecin arrive.", "Please wait a moment, the doctor's coming."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["他的身体", "越来越", "好", "了"],
        tr: t("Il est de plus en plus en forme.", "His health is getting better and better."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "从来", "没", "这么累", "过"],
        tr: t("Je n'ai jamais été aussi fatigué.", "I've never been this tired."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["你", "应该", "稍微", "少吃", "一点儿", "甜的"],
        tr: t("Tu devrais manger un peu moins sucré.", "You should eat slightly less sweet stuff."),
      },
      {
        type: "listen",
        zh: "我越想睡，越睡不着。",
        options: ["我越来越想睡觉。", "我越想睡，越睡不着。", "我想睡，可是睡不好。", "我越睡越想睡。"],
        answer: 1,
        tr: t("Plus j'essaie de dormir, moins j'y arrive.", "The more I try to sleep, the less I can."),
      },
      {
        type: "listen",
        zh: "不用吃药，不过你得少喝咖啡。",
        options: ["你得吃药，不要喝咖啡。", "不用喝咖啡，不过你得吃药。", "你不用吃药，也不用少喝咖啡。", "不用吃药，不过你得少喝咖啡。"],
        answer: 3,
        tr: t("Pas besoin de médicaments, mais tu dois boire moins de café.", "No need for medicine, but you must drink less coffee."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("锻炼", "duànliàn", "faire de l'exercice", "work out"),
          mp("健康", "jiànkāng", "santé, sain", "healthy"),
          mp("习惯", "xíguàn", "habitude", "habit"),
          mp("感冒", "gǎnmào", "rhume", "cold (illness)"),
          mp("发烧", "fāshāo", "avoir de la fièvre", "have a fever"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est incorrecte ?", "Which sentence is incorrect?"),
        options: ["天气越来越冷。", "雨越下越大。", "天气越来越很冷。", "我越来越喜欢跑步。"],
        answer: 2,
        explain: t("Pas de 很 après 越来越.", "No 很 after 越来越."),
      },
    ],
  },

  // ─────────────────────────────── L04 — Environment
  {
    id: "hsk3-l04",
    level: 3,
    order: 4,
    title: t("Protéger la planète", "Protecting the planet"),
    subtitle: t("Environnement, tri et gestes verts", "Environment, recycling and green habits"),
    theme: "nature",
    goals: [
      t("Parler de pollution et de gestes écologiques", "Talk about pollution and eco-friendly habits"),
      t("Exprimer un but avec 为了 et une cause formelle avec 由于……因此", "Express purpose with 为了 and formal cause with 由于……因此"),
      t("Enchaîner des arguments avec 不但……而且 et 甚至", "Build arguments with 不但……而且 and 甚至"),
      t("Lire et dire fractions, pourcentages et multiples", "Read and say fractions, percentages and multiples"),
    ],
    dialogue: {
      context: t(
        "Anna, étudiante étrangère, discute avec son ami Wang Qiang d'un projet sur l'environnement.",
        "Anna, an international student, chats with her friend Wang Qiang about an environment project."
      ),
      lines: [
        ln("安娜", "王强，你们学校也在做垃圾分类吗？", "Wáng Qiáng, nǐmen xuéxiào yě zài zuò lājī fēnlèi ma?", "Wang Qiang, ton école fait aussi le tri des déchets ?", "Wang Qiang, is your school sorting rubbish too?"),
        ln("王强", "对，为了保护环境，学校要求每个人都要分类。", "Duì, wèile bǎohù huánjìng, xuéxiào yāoqiú měi ge rén dōu yào fēnlèi.", "Oui, pour protéger l'environnement, l'école demande à tout le monde de trier.", "Yes — to protect the environment, the school requires everyone to sort."),
        ln("安娜", "我听说，由于汽车越来越多，城市的空气越来越差。", "Wǒ tīngshuō, yóuyú qìchē yuè lái yuè duō, chéngshì de kōngqì yuè lái yuè chà.", "J'ai entendu dire qu'avec de plus en plus de voitures, l'air en ville est de pire en pire.", "I heard that because there are more and more cars, city air is getting worse and worse."),
        ln("王强", "是啊。这个城市的汽车比十年前多了一倍。", "Shì a. Zhège chéngshì de qìchē bǐ shí nián qián duō le yí bèi.", "Oui. Il y a deux fois plus de voitures qu'il y a dix ans dans cette ville.", "That's right. The number of cars here has doubled in ten years."),
        ln("安娜", "因此，现在很多人不开车了，改骑自行车。", "Yīncǐ, xiànzài hěn duō rén bù kāichē le, gǎi qí zìxíngchē.", "C'est pourquoi beaucoup de gens ont arrêté la voiture pour passer au vélo.", "That's why lots of people have stopped driving and switched to cycling."),
        ln("王强", "骑自行车不但环保，而且对身体也好。", "Qí zìxíngchē búdàn huánbǎo, érqiě duì shēntǐ yě hǎo.", "Le vélo, c'est non seulement écolo, mais aussi bon pour la santé.", "Cycling is not only green, it's good for your health too."),
        ln("安娜", "我们小区有百分之七十的人都支持少开车。", "Wǒmen xiǎoqū yǒu bǎi fēn zhī qīshí de rén dōu zhīchí shǎo kāichē.", "Dans ma résidence, 70 % des gens sont pour moins utiliser la voiture.", "In my neighbourhood, 70% of people support driving less."),
        ln("王强", "真不错！有的人甚至把车卖了。", "Zhēn búcuò! Yǒu de rén shènzhì bǎ chē mài le.", "Super ! Certains ont même vendu leur voiture.", "Great! Some people have even sold their cars."),
        ln("安娜", "我觉得节约用水也很重要。地球上只有很少一部分水能喝。", "Wǒ juéde jiéyuē yòng shuǐ yě hěn zhòngyào. Dìqiú shang zhǐyǒu hěn shǎo yí bùfen shuǐ néng hē.", "Je pense qu'économiser l'eau est aussi important. Seule une toute petite partie de l'eau sur Terre est potable.", "I think saving water matters too. Only a tiny part of the Earth's water is drinkable."),
        ln("王强", "对，不到百分之一。所以洗澡的时间应该短一点儿。", "Duì, bú dào bǎi fēn zhī yī. Suǒyǐ xǐzǎo de shíjiān yīnggāi duǎn yìdiǎnr.", "Oui, moins de 1 %. Donc on devrait prendre des douches plus courtes.", "Right, less than 1%. So we should take shorter showers."),
        ln("安娜", "下个周末我们一起去公园种树吧？", "Xià ge zhōumò wǒmen yìqǐ qù gōngyuán zhòng shù ba?", "Le week-end prochain, on va planter des arbres au parc ensemble ?", "Shall we go plant trees in the park next weekend?"),
        ln("王强", "好主意！为了下一代，我们每个人都应该做点儿什么。", "Hǎo zhǔyi! Wèile xià yí dài, wǒmen měi ge rén dōu yīnggāi zuò diǎnr shénme.", "Bonne idée ! Pour les générations futures, chacun de nous doit faire quelque chose.", "Good idea! For the next generation, each of us should do something."),
      ],
    },
    vocab: ["环境", "保护", "垃圾", "分类", "要求", "由于", "因此", "空气", "差", "倍", "环保", "支持", "百分之", "甚至", "不但", "而且", "节约", "地球", "部分", "洗澡", "种", "树", "主意", "污染", "自然", "气候", "温度", "变化", "减少", "解决", "自行车", "为了"],
    grammar: ["hsk3-g17", "hsk3-g18", "hsk3-g19", "hsk3-g20", "hsk3-g21"],
    culture: {
      title: t("Le tri des déchets à la chinoise", "Rubbish sorting, Chinese style"),
      body: t(
        "Depuis 2019, Shanghai puis d'autres grandes villes ont rendu le **tri des déchets** (垃圾分类) obligatoire, avec quatre catégories : **可回收物** (recyclables), **有害垃圾** (dangereux), **湿垃圾 / 厨余垃圾** (déchets alimentaires) et **干垃圾 / 其他垃圾** (autres). Au début, beaucoup de gens étaient perdus, et des applis pour savoir « quel déchet va où » sont devenues très populaires !\n\nLe **12 mars** est la **journée de l'arbre** (植树节) : écoles et entreprises organisent des plantations. Et la campagne **光盘行动** (« opération assiette vide ») encourage à ne pas gaspiller la nourriture au restaurant.",
        "Since 2019, Shanghai and then other big cities have made **rubbish sorting** (垃圾分类) compulsory, with four bins: **可回收物** (recyclables), **有害垃圾** (hazardous), **湿垃圾 / 厨余垃圾** (food waste) and **干垃圾 / 其他垃圾** (residual). At first many people were confused, and \"which bin?\" apps became hugely popular!\n\n**12 March** is **Tree-Planting Day** (植树节): schools and companies organise planting events. And the **光盘行动** (\"Clean Plate campaign\") encourages people not to waste food in restaurants."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment dit-on « un tiers » ?", "How do you say \"one third\"?"),
        options: ["一分之三", "三分之一", "三之分一", "一三分"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Choisis la phrase qui exprime un but.", "Pick the sentence that expresses a purpose."),
        options: ["因为保护环境，我骑车。", "为了保护环境，我骑车上班。", "由于保护环境，因此骑车。", "保护环境所以我为了骑车。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("« 60 % » se dit :", "\"60%\" is said:"),
        options: ["六十百分之", "百分之六十", "百分六十", "六十分之百"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "骑自行车不但环保，",
        after: "对身体好。",
        options: ["但是", "而且", "因此", "甚至不"],
        answer: 1,
        tr: t("Le vélo est non seulement écologique, mais aussi bon pour la santé.", "Cycling is not only green but also good for your health."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "由于空气污染严重，",
        after: "很多人戴上了口罩。",
        options: ["因此", "为了", "甚至", "不但"],
        answer: 0,
        tr: t("À cause de la forte pollution, beaucoup de gens ont mis un masque.", "Due to severe pollution, many people put on masks."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "很多人，",
        after: "孩子，都知道垃圾分类。",
        options: ["为了", "由于", "甚至", "因此"],
        answer: 2,
        tr: t("Beaucoup de gens, et même les enfants, connaissent le tri.", "Many people, even children, know about sorting rubbish."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["为了", "节约用水，", "请", "随手关水"],
        tr: t("Pour économiser l'eau, pense à fermer le robinet.", "To save water, please turn off the tap."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["地球上", "三分之二", "是", "水"],
        tr: t("Les deux tiers de la Terre sont de l'eau.", "Two thirds of the Earth is water."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我们", "种树", "是为了", "让空气", "更好"],
        tr: t("Nous plantons des arbres pour améliorer l'air.", "We plant trees to make the air better."),
      },
      {
        type: "listen",
        zh: "这个城市的汽车比十年前多了一倍。",
        options: ["这个城市的汽车比十年前少了一半。", "这个城市的汽车比十年前多了一倍。", "这个城市的自行车比十年前多了一倍。", "这个城市十年前的汽车很多。"],
        answer: 1,
        tr: t("Il y a deux fois plus de voitures qu'il y a dix ans.", "The number of cars has doubled in ten years."),
      },
      {
        type: "listen",
        zh: "有的人甚至把车卖了。",
        options: ["有的人甚至把车卖了。", "有的人甚至买了新车。", "有的人把自行车卖了。", "有的人不想把车卖了。"],
        answer: 0,
        tr: t("Certains ont même vendu leur voiture.", "Some people have even sold their cars."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("保护", "bǎohù", "protéger", "protect"),
          mp("污染", "wūrǎn", "pollution", "pollution"),
          mp("垃圾", "lājī", "déchets", "rubbish"),
          mp("节约", "jiéyuē", "économiser", "save, conserve"),
          mp("空气", "kōngqì", "air", "air"),
        ],
      },
      {
        type: "choice",
        prompt: t("Que signifie 因此 ?", "What does 因此 mean?"),
        options: [
          t("parce que", "because"),
          t("c'est pourquoi, par conséquent", "therefore, as a result"),
          t("pour, afin de", "in order to"),
          t("même", "even"),
        ],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L05 — Tech & phones
  {
    id: "hsk3-l05",
    level: 3,
    order: 5,
    title: t("Mamie et son smartphone", "Grandma's smartphone"),
    subtitle: t("Technologie et téléphone au quotidien", "Tech and phones in daily life"),
    theme: "tech",
    goals: [
      t("Parler de ce qu'on peut ou ne peut pas faire avec les compléments de possibilité", "Say what you can or can't do with potential complements"),
      t("Utiliser 了 (liǎo), 动 et 下 pour la capacité", "Use 了 (liǎo), 动 and 下 for ability and capacity"),
      t("Évaluer un objet avec V + 起来 (用起来很方便)", "Evaluate something with V + 起来 (用起来很方便)"),
      t("Insister avec 连……都 et situer un changement avec 自从", "Emphasise with 连……都 and date a change with 自从"),
    ],
    dialogue: {
      context: t(
        "Xiao Ming aide sa grand-mère à utiliser son nouveau smartphone.",
        "Xiao Ming helps his grandmother use her new smartphone."
      ),
      lines: [
        ln("奶奶", "小明，这个手机我用不了，字太小了，我看不清楚。", "Xiǎo Míng, zhège shǒujī wǒ yòng bu liǎo, zì tài xiǎo le, wǒ kàn bu qīngchu.", "Xiao Ming, je n'y arrive pas avec ce téléphone, les caractères sont trop petits, je ne vois rien.", "Xiao Ming, I can't use this phone — the text is too small, I can't see it clearly."),
        ln("小明", "奶奶，我帮您把字调大一点儿。您看，现在看得清楚吗？", "Nǎinai, wǒ bāng nín bǎ zì tiáo dà yìdiǎnr. Nín kàn, xiànzài kàn de qīngchu ma?", "Mamie, je t'agrandis le texte. Regarde, tu vois bien maintenant ?", "Grandma, let me make the text bigger. Look — can you see it now?"),
        ln("奶奶", "清楚多了！自从有了这个手机，我什么都想学。", "Qīngchu duō le! Zìcóng yǒu le zhège shǒujī, wǒ shénme dōu xiǎng xué.", "C'est beaucoup mieux ! Depuis que j'ai ce téléphone, j'ai envie de tout apprendre.", "Much clearer! Ever since I got this phone, I want to learn everything."),
        ln("小明", "您想学什么？我教您。", "Nín xiǎng xué shénme? Wǒ jiāo nín.", "Qu'est-ce que tu veux apprendre ? Je vais te montrer.", "What do you want to learn? I'll teach you."),
        ln("奶奶", "我想用微信给你姑姑发视频。连楼下的王奶奶都会用了。", "Wǒ xiǎng yòng Wēixìn gěi nǐ gūgu fā shìpín. Lián lóu xià de Wáng nǎinai dōu huì yòng le.", "Je veux envoyer des vidéos à ta tante sur WeChat. Même Mamie Wang d'en bas sait le faire !", "I want to send videos to your aunt on WeChat. Even Granny Wang downstairs can do it!"),
        ln("小明", "这个很简单，用起来很方便。先点这里，再点“视频通话”。", "Zhège hěn jiǎndān, yòng qilai hěn fāngbiàn. Xiān diǎn zhèlǐ, zài diǎn “shìpín tōnghuà”.", "C'est très simple et pratique. Tu appuies d'abord ici, puis sur « appel vidéo ».", "It's easy and really handy to use. Tap here first, then tap \"video call\"."),
        ln("奶奶", "哎呀，怎么没有声音？我听不见你姑姑说话。", "Āiyā, zěnme méiyǒu shēngyīn? Wǒ tīng bu jiàn nǐ gūgu shuōhuà.", "Oh là là, pourquoi il n'y a pas de son ? Je n'entends pas ta tante.", "Oh dear, why is there no sound? I can't hear your aunt."),
        ln("小明", "别着急，可能是网不太好，我们去客厅试试。", "Bié zháojí, kěnéng shì wǎng bú tài hǎo, wǒmen qù kètīng shìshi.", "Pas de panique, c'est peut-être le réseau. Essayons dans le salon.", "Don't worry, maybe the connection's bad. Let's try in the living room."),
        ln("奶奶", "好了，好了，听得见了！", "Hǎo le, hǎo le, tīng de jiàn le!", "Ça y est, ça y est, j'entends !", "There we go — I can hear now!"),
        ln("小明", "对了，您的手机太满了，存不下新照片了。", "Duì le, nín de shǒujī tài mǎn le, cún bu xià xīn zhàopiàn le.", "Au fait, ton téléphone est plein, il ne peut plus enregistrer de nouvelles photos.", "By the way, your phone is full — it can't store any new photos."),
        ln("奶奶", "那怎么办？这些照片我都想留着。", "Nà zěnme bàn? Zhèxiē zhàopiàn wǒ dōu xiǎng liú zhe.", "Comment on fait ? Je veux garder toutes ces photos.", "So what do we do? I want to keep all these photos."),
        ln("小明", "没问题，我把照片都放到电脑里，您想看的时候随时可以看。", "Méi wèntí, wǒ bǎ zhàopiàn dōu fàngdào diànnǎo lǐ, nín xiǎng kàn de shíhou suíshí kěyǐ kàn.", "Pas de problème, je les mets toutes sur l'ordinateur, tu pourras les regarder quand tu veux.", "No problem, I'll put them all on the computer — you can look at them any time."),
        ln("奶奶", "我想起来了，你上次也是这么说的，可是后来忘了！", "Wǒ xiǎng qilai le, nǐ shàng cì yě shì zhème shuō de, kěshì hòulái wàng le!", "Ça me revient : tu m'avais déjà dit ça la dernière fois, et après tu as oublié !", "Now I remember — you said that last time too, and then you forgot!"),
      ],
    },
    vocab: ["智能手机", "清楚", "自从", "微信", "视频", "发", "连", "简单", "方便", "声音", "着急", "网", "试", "存", "照片", "电脑", "随时", "后来", "软件", "下载", "密码", "充电", "上网", "信息", "使用", "技术", "短信", "屏幕", "重", "满"],
    grammar: ["hsk3-g22", "hsk3-g23", "hsk3-g24", "hsk3-g25", "hsk3-g26"],
    culture: {
      title: t("WeChat, l'appli qui fait tout", "WeChat, the everything app"),
      body: t(
        "En Chine, **微信** (WeChat) n'est pas qu'une messagerie : on l'utilise pour **payer** (微信支付), commander un taxi, prendre rendez-vous chez le médecin, payer ses factures… On paie presque partout en **scannant un QR code** (扫码), même chez les petits vendeurs de rue.\n\nPour les personnes âgées, ce « tout numérique » est parfois un défi. Beaucoup de familles apprennent aux grands-parents à utiliser leur smartphone, et certaines villes proposent des cours gratuits. Des applis ont aussi une **version pour seniors** (长辈模式) avec de gros caractères.",
        "In China, **微信** (WeChat) is far more than a messenger: people use it to **pay** (微信支付), book taxis, make doctor's appointments, pay bills… You pay almost everywhere by **scanning a QR code** (扫码), even at small street stalls.\n\nFor older people, this \"all-digital\" life can be a challenge. Many families teach grandparents to use smartphones, and some cities offer free classes. Many apps also have a **senior mode** (长辈模式) with large text."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Je ne comprends pas (à l'écoute). »", "\"I can't understand (what I hear).\""),
        options: ["我不能听懂。", "我听不懂。", "我听懂不。", "我不听懂。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Le carton est trop lourd, tu n'arrives pas à le porter :", "The box is too heavy for you to carry:"),
        options: ["我拿不下。", "我拿不了。", "我拿不动。", "我不拿动。"],
        answer: 2,
        explain: t("Force physique → 动.", "Physical strength → 动."),
      },
      {
        type: "choice",
        prompt: t("Où place-t-on l'objet avec 起来 ?", "Where does the object go with 起来?"),
        options: ["他唱起来歌了。", "他唱歌起来了。", "他起来唱歌了。", "他唱起歌来了。"],
        answer: 3,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我奶奶",
        after: "微信都会用。",
        options: ["连", "自从", "只要", "除了"],
        answer: 0,
        tr: t("Même ma grand-mère sait utiliser WeChat.", "Even my grandma can use WeChat."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这个软件用",
        after: "很简单。",
        options: ["下去", "起来", "出来", "上来"],
        answer: 1,
        tr: t("Cette appli est très simple à utiliser.", "This app is very easy to use."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我的手机太旧，装不",
        after: "新软件了。",
        options: ["动", "了", "下", "完"],
        answer: 2,
        tr: t("Mon téléphone est trop vieux, il n'a plus de place pour une nouvelle appli.", "My phone's too old; there's no room for new apps."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["自从", "有了智能手机，", "我", "很少", "看报纸了"],
        tr: t("Depuis que j'ai un smartphone, je lis rarement le journal.", "Since I got a smartphone, I rarely read newspapers."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["屏幕", "太小了，", "我", "看不清楚"],
        tr: t("L'écran est trop petit, je ne vois pas bien.", "The screen is too small, I can't see clearly."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我手机里", "连", "一张照片", "也", "没有了"],
        tr: t("Il ne reste plus une seule photo dans mon téléphone.", "There isn't a single photo left on my phone."),
      },
      {
        type: "listen",
        zh: "我听不见你姑姑说话。",
        options: ["我听不懂你姑姑说话。", "我看不见你姑姑。", "我听不见你姑姑说话。", "你姑姑听不见我说话。"],
        answer: 2,
        tr: t("Je n'entends pas ta tante.", "I can't hear your aunt."),
      },
      {
        type: "listen",
        zh: "您的手机太满了，存不下新照片了。",
        options: ["您的手机太满了，存不下新照片了。", "您的手机太旧了，拍不了新照片了。", "您的电脑太满了，存不下新照片了。", "您的手机没电了，看不了照片了。"],
        answer: 0,
        tr: t("Ton téléphone est plein, il ne peut plus stocker de nouvelles photos.", "Your phone is full; it can't store new photos."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("密码", "mìmǎ", "mot de passe", "password"),
          mp("下载", "xiàzài", "télécharger", "download"),
          mp("充电", "chōngdiàn", "recharger", "charge (a battery)"),
          mp("视频", "shìpín", "vidéo", "video"),
          mp("软件", "ruǎnjiàn", "logiciel, appli", "software, app"),
          mp("上网", "shàngwǎng", "aller sur internet", "go online"),
        ],
      },
      {
        type: "choice",
        prompt: t("Dans 吃不了, 了 se prononce :", "In 吃不了, 了 is pronounced:"),
        options: ["le", "liǎo", "lè", "lāo"],
        answer: 1,
      },
    ],
  },
];
