import type { Lesson } from "../../types";
import { t, ln, mp } from "./helpers";

export const lessons3: Lesson[] = [
  // ─────────────────────────────── L11 — News & social media
  {
    id: "hsk3-l11",
    level: 3,
    order: 11,
    title: t("Vrai ou faux ?", "Real or fake?"),
    subtitle: t("Actualités et réseaux sociaux", "News and social media"),
    theme: "society",
    goals: [
      t("Parler d'une info ou d'une vidéo virale", "Talk about a news story or a viral video"),
      t("Donner des chiffres approximatifs (左右, 多, 几十)", "Give approximate figures (左右, 多, 几十)"),
      t("Insister sur une question avec 到底 / 究竟", "Press a question with 到底 / 究竟"),
      t("Utiliser 出来 (repérer) et 下去 (continuer) au sens figuré", "Use figurative 出来 (spot) and 下去 (continue)"),
      t("Employer les mots interrogatifs au sens vague (在哪儿 = quelque part)", "Use question words vaguely (在哪儿 = somewhere)"),
    ],
    dialogue: {
      context: t(
        "Au bureau, Xiao Liu montre à son collègue Lao Zhou une vidéo qui fait le buzz.",
        "At the office, Xiao Liu shows his colleague Lao Zhou a video that's going viral."
      ),
      lines: [
        ln("小刘", "老周，你看这个视频，已经有一百万左右的人看过了！", "Lǎo Zhōu, nǐ kàn zhège shìpín, yǐjīng yǒu yìbǎi wàn zuǒyòu de rén kàn guo le!", "Lao Zhou, regarde cette vidéo : elle a déjà été vue par environ un million de personnes !", "Lao Zhou, look at this video — about a million people have already watched it!"),
        ln("老周", "什么视频？我好像在哪儿看过。", "Shénme shìpín? Wǒ hǎoxiàng zài nǎr kàn guo.", "Quelle vidéo ? Il me semble l'avoir vue quelque part.", "What video? I think I've seen it somewhere."),
        ln("小刘", "一个年轻人在河里救了一只小狗。网上有几千条留言。", "Yí ge niánqīngrén zài hé lǐ jiù le yì zhī xiǎo gǒu. Wǎng shang yǒu jǐ qiān tiáo liúyán.", "Un jeune homme sauve un petit chien dans une rivière. Il y a des milliers de commentaires.", "A young man rescues a puppy from a river. There are thousands of comments."),
        ln("老周", "可是我听说这个视频是假的。", "Kěshì wǒ tīngshuō zhège shìpín shì jiǎ de.", "Mais j'ai entendu dire que c'était un fake.", "But I heard this video is fake."),
        ln("小刘", "啊？那到底是真的还是假的？", "Á? Nà dàodǐ shì zhēn de háishi jiǎ de?", "Hein ? Alors, c'est vrai ou c'est faux, au juste ?", "What? So is it real or fake?"),
        ln("老周", "你仔细看，看得出来吗？那只狗一点儿也不害怕，好像在演戏。", "Nǐ zǐxì kàn, kàn de chūlai ma? Nà zhī gǒu yìdiǎnr yě bú hàipà, hǎoxiàng zài yǎnxì.", "Regarde bien, tu ne remarques rien ? Le chien n'a pas peur du tout, on dirait qu'il joue la comédie.", "Look closely — can you tell? The dog isn't scared at all; it's like it's acting."),
        ln("小刘", "真的！我怎么没看出来？", "Zhēn de! Wǒ zěnme méi kàn chulai?", "C'est vrai ! Comment j'ai pu ne pas le voir ?", "You're right! How did I not notice?"),
        ln("老周", "现在有的人为了让更多人关注自己，什么都做得出来。", "Xiànzài yǒu de rén wèile ràng gèng duō rén guānzhù zìjǐ, shénme dōu zuò de chūlai.", "Aujourd'hui, certains sont prêts à tout pour avoir plus d'abonnés.", "These days some people will do anything to get more followers."),
        ln("小刘", "那究竟应该相信什么呢？", "Nà jiūjìng yīnggāi xiāngxìn shénme ne?", "Alors, à quoi est-ce qu'on doit se fier, finalement ?", "So what on earth should we believe?"),
        ln("老周", "看新闻最好看大的网站，别只看朋友圈。", "Kàn xīnwén zuìhǎo kàn dà de wǎngzhàn, bié zhǐ kàn péngyouquān.", "Pour l'actu, mieux vaut consulter les grands sites, pas seulement ton fil WeChat.", "For news, it's best to use major websites, not just your WeChat Moments."),
        ln("小刘", "我每天看两个多小时手机，看到的消息一半是假的吧？", "Wǒ měi tiān kàn liǎng ge duō xiǎoshí shǒujī, kàndào de xiāoxi yíbàn shì jiǎ de ba?", "Je passe plus de deux heures par jour sur mon téléphone… la moitié de ce que je vois est fausse ?", "I spend over two hours a day on my phone — is half of what I see fake?"),
        ln("老周", "哈哈，那倒不一定。不过这样下去，你的眼睛可受不了！", "Hāhā, nà dào bù yídìng. Búguò zhèyàng xiaqu, nǐ de yǎnjing kě shòu bu liǎo!", "Haha, pas forcément. Mais si tu continues comme ça, ce sont tes yeux qui vont trinquer !", "Haha, not necessarily. But if you keep this up, your eyes won't survive it!"),
      ],
    },
    vocab: ["新闻", "视频", "左右", "好像", "救", "留言", "假", "真", "到底", "究竟", "仔细", "害怕", "关注", "相信", "网站", "消息", "一半", "眼睛", "受不了", "记者", "报纸", "电视", "节目", "信息", "发生", "社会", "世界", "国际", "继续", "看法"],
    grammar: ["hsk3-g53", "hsk3-g54", "hsk3-g55", "hsk3-g56", "hsk3-g57"],
    culture: {
      title: t("Weibo, Douyin et « recherches tendance »", "Weibo, Douyin and \"hot searches\""),
      body: t(
        "Les Chinois s'informent beaucoup sur les réseaux : **微博** (Weibo, proche de X/Twitter), **抖音** (Douyin, la version chinoise de TikTok) et le **朋友圈** (« cercle d'amis », le fil d'actualité de WeChat). Le classement des **热搜** (« recherches brûlantes ») de Weibo dicte chaque jour les sujets de conversation.\n\nFace aux rumeurs (**谣言**), les médias officiels publient régulièrement des démentis sous l'étiquette **辟谣** (« réfuter une rumeur »). Un bon réflexe : vérifier la source (来源) avant de partager !",
        "Chinese people get a lot of their news from social media: **微博** (Weibo, similar to X/Twitter), **抖音** (Douyin, the Chinese TikTok) and **朋友圈** (\"Moments\", WeChat's feed). Weibo's **热搜** (\"hot searches\") ranking sets the day's talking points.\n\nTo fight rumours (**谣言**), official media regularly publish fact-checks tagged **辟谣** (\"debunking\"). Good habit: check the source (来源) before sharing!"
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle question avec 到底 est correcte ?", "Which question with 到底 is correct?"),
        options: ["你到底去吗？", "你到底去不去？", "到底你去吗？", "你去到底吗？"],
        answer: 1,
        explain: t("到底 ne s'emploie pas avec 吗.", "到底 doesn't combine with 吗."),
      },
      {
        type: "choice",
        prompt: t("« Plus d'une heure » se dit :", "\"Over an hour\" is:"),
        options: ["一多个小时", "一个多小时", "一个小时多个", "多一个小时"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Tu reconnais immédiatement la voix de quelqu'un au téléphone :", "You instantly recognise someone's voice on the phone:"),
        options: ["我听起来是你。", "我听出来是你。", "我听下去是你。", "我听上来是你。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这个视频有一百万",
        after: "的人看过。",
        options: ["左右", "多个", "几", "上下来"],
        answer: 0,
        tr: t("Environ un million de personnes ont vu cette vidéo.", "About a million people have watched this video."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "你说得很好，请继续说",
        after: "。",
        options: ["起来", "出来", "下去", "下来"],
        answer: 2,
        tr: t("C'est très bien, continue, je t'en prie.", "You're doing great — please go on."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我好像在",
        after: "见过他。",
        options: ["哪儿", "什么", "谁", "怎么"],
        answer: 0,
        tr: t("Il me semble l'avoir vu quelque part.", "I think I've seen him somewhere."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["这条新闻", "到底", "是真的", "还是", "假的"],
        tr: t("Cette info, elle est vraie ou fausse, au juste ?", "So is this news actually true or false?"),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["你", "看得出来", "这张照片", "是假的吗"],
        tr: t("Tu arrives à voir que cette photo est truquée ?", "Can you tell this photo is fake?"),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "每天", "看", "两个多小时", "手机"],
        tr: t("Je passe plus de deux heures par jour sur mon téléphone.", "I spend over two hours a day on my phone."),
      },
      {
        type: "listen",
        zh: "我好像在哪儿看过这条新闻。",
        options: ["我在哪儿能看这条新闻？", "我好像在哪儿看过这条新闻。", "我没看过这条新闻。", "我好像在电视上看过这个节目。"],
        answer: 1,
        tr: t("Il me semble avoir vu cette info quelque part.", "I think I've seen this news somewhere."),
      },
      {
        type: "listen",
        zh: "这样下去，你的眼睛可受不了。",
        options: ["这样下去，你的眼睛可受不了。", "你的眼睛这样看不下去。", "这样下去，你的身体会越来越好。", "你的眼睛受得了。"],
        answer: 0,
        tr: t("Si tu continues comme ça, tes yeux ne vont pas tenir.", "If you keep this up, your eyes won't take it."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("新闻", "xīnwén", "actualités, info", "news"),
          mp("记者", "jìzhě", "journaliste", "journalist"),
          mp("消息", "xiāoxi", "nouvelle, message", "news, message"),
          mp("网站", "wǎngzhàn", "site web", "website"),
          mp("仔细", "zǐxì", "attentivement", "carefully"),
        ],
      },
      {
        type: "choice",
        prompt: t("Que veut dire 你想吃点儿什么吗？", "What does 你想吃点儿什么吗？ mean?"),
        options: [
          t("Qu'est-ce que tu veux manger ?", "What do you want to eat?"),
          t("Tu veux manger quelque chose ?", "Do you want something to eat?"),
          t("Tu as mangé quoi ?", "What did you eat?"),
          t("Tu ne manges rien ?", "Aren't you eating anything?"),
        ],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L12 — Cooking a recipe
  {
    id: "hsk3-l12",
    level: 3,
    order: 12,
    title: t("Tomates sautées aux œufs", "Tomato and egg stir-fry"),
    subtitle: t("Suivre une recette pas à pas", "Following a recipe step by step"),
    theme: "food",
    goals: [
      t("Expliquer les étapes d'une recette (先……再……然后……最后)", "Explain recipe steps (先……再……然后……最后)"),
      t("Donner des consignes avec 把 : 把……切成……, 别把……", "Give instructions with 把: 把……切成……, 别把……"),
      t("Placer correctement la négation et les modaux dans une phrase en 把", "Place negation and modals correctly in 把 sentences"),
      t("Enchaîner deux actions immédiates avec 一……就", "Chain two immediate actions with 一……就"),
    ],
    dialogue: {
      context: t(
        "Amy, une étudiante étrangère, apprend à cuisiner un plat familial avec sa voisine, Mme Wang.",
        "Amy, an international student, learns to cook a home-style dish with her neighbour, Mrs Wang."
      ),
      lines: [
        ln("艾米", "王阿姨，您做的西红柿炒鸡蛋太好吃了，能教我吗？", "Wáng āyí, nín zuò de xīhóngshì chǎo jīdàn tài hǎochī le, néng jiāo wǒ ma?", "Madame Wang, vos tomates sautées aux œufs sont délicieuses, vous pouvez m'apprendre ?", "Mrs Wang, your tomato and egg stir-fry is so good — can you teach me?"),
        ln("王阿姨", "当然可以，这个菜很简单。先把西红柿洗干净，再切成小块。", "Dāngrán kěyǐ, zhège cài hěn jiǎndān. Xiān bǎ xīhóngshì xǐ gānjìng, zài qiēchéng xiǎo kuài.", "Bien sûr, c'est très simple. D'abord, lave bien les tomates, puis coupe-les en petits morceaux.", "Of course, it's very easy. First wash the tomatoes, then cut them into small pieces."),
        ln("艾米", "等一下，我把做法记下来。……好了，然后呢？", "Děng yíxià, wǒ bǎ zuòfǎ jì xialai. …… Hǎo le, ránhòu ne?", "Attendez, je note la recette… Voilà, et ensuite ?", "Hang on, let me write this down… OK, then what?"),
        ln("王阿姨", "然后把鸡蛋打在碗里，加一点儿盐。", "Ránhòu bǎ jīdàn dǎ zài wǎn lǐ, jiā yìdiǎnr yán.", "Ensuite, casse les œufs dans un bol et ajoute un peu de sel.", "Then crack the eggs into a bowl and add a little salt."),
        ln("艾米", "要放多少油？", "Yào fàng duōshao yóu?", "Je mets combien d'huile ?", "How much oil should I use?"),
        ln("王阿姨", "别把油放得太多，两勺就够了。油一热，就把鸡蛋倒进去。", "Bié bǎ yóu fàng de tài duō, liǎng sháo jiù gòu le. Yóu yí rè, jiù bǎ jīdàn dào jinqu.", "Ne mets pas trop d'huile, deux cuillères suffisent. Dès que l'huile est chaude, verse les œufs.", "Don't use too much oil — two spoonfuls is enough. As soon as the oil is hot, pour in the eggs."),
        ln("艾米", "鸡蛋什么时候拿出来？", "Jīdàn shénme shíhou ná chulai?", "Et je sors les œufs quand ?", "When do I take the eggs out?"),
        ln("王阿姨", "鸡蛋一变黄，就先盛出来，再炒西红柿。", "Jīdàn yí biàn huáng, jiù xiān chéng chulai, zài chǎo xīhóngshì.", "Dès que les œufs dorent, tu les mets de côté, puis tu fais sauter les tomates.", "As soon as the eggs turn golden, take them out first, then stir-fry the tomatoes."),
        ln("艾米", "要放糖吗？我听说北方人和南方人的做法不一样。", "Yào fàng táng ma? Wǒ tīngshuō běifāngrén hé nánfāngrén de zuòfǎ bù yíyàng.", "On met du sucre ? Il paraît que les gens du Nord et du Sud ne le font pas pareil.", "Do I add sugar? I've heard northerners and southerners make it differently."),
        ln("王阿姨", "对，我们家放一点儿糖。最后把鸡蛋放回去，再炒一分钟就好了。", "Duì, wǒmen jiā fàng yìdiǎnr táng. Zuìhòu bǎ jīdàn fàng huiqu, zài chǎo yì fēnzhōng jiù hǎo le.", "Oui, chez nous on en met un peu. Pour finir, remets les œufs et fais sauter encore une minute, c'est prêt.", "Yes, in our family we add a little. Finally, put the eggs back in and stir-fry for another minute — done."),
        ln("艾米", "糟糕，我刚才把糖看成盐了！", "Zāogāo, wǒ gāngcái bǎ táng kànchéng yán le!", "Zut, j'ai confondu le sucre avec le sel tout à l'heure !", "Oh no, I just mistook the sugar for salt!"),
        ln("王阿姨", "没关系，还没把菜做完呢，再试一次！这个菜谱是我妈妈传下来的，你一定学得会。", "Méi guānxi, hái méi bǎ cài zuòwán ne, zài shì yí cì! Zhège càipǔ shì wǒ māma chuán xialai de, nǐ yídìng xué de huì.", "Pas grave, le plat n'est pas encore fini, on recommence ! Cette recette me vient de ma mère, tu vas y arriver.", "Never mind, the dish isn't finished yet — try again! This recipe was handed down from my mum; you'll definitely get it."),
      ],
    },
    vocab: ["西红柿", "鸡蛋", "炒", "教", "洗", "干净", "切", "块", "记", "做法", "碗", "加", "盐", "油", "够", "热", "倒", "变", "黄", "糖", "北方", "南方", "最后", "糟糕", "菜谱", "传", "味道", "厨房", "锅", "米饭", "香", "然后"],
    grammar: ["hsk3-g58", "hsk3-g59", "hsk3-g60", "hsk3-g61", "hsk3-g62"],
    culture: {
      title: t("Sucré ou salé ? Le grand débat", "Sweet or savoury? The great debate"),
      body: t(
        "Le **西红柿炒鸡蛋** est sans doute le plat familial le plus connu de Chine : c'est souvent le premier que les étudiants apprennent à cuisiner ! Mais faut-il y mettre du **sucre** ? Au sud (Shanghai, Canton), beaucoup disent oui ; au nord, on préfère le salé.\n\nCe débat sucré/salé est célèbre avec le **豆腐脑** (flan de tofu) : les « **甜党** » (parti du sucré) du Sud contre les « **咸党** » (parti du salé) du Nord s'affrontent chaque année en ligne. La Chine compte d'ailleurs **八大菜系**, huit grandes traditions culinaires régionales, du Sichuan épicé au Cantonais délicat.",
        "**西红柿炒鸡蛋** is probably China's best-known home dish — often the first thing students learn to cook! But should you add **sugar**? In the south (Shanghai, Guangdong), many say yes; in the north, people prefer it savoury.\n\nThis sweet-vs-savoury debate is famous with **豆腐脑** (tofu pudding): the southern \"**甜党**\" (sweet party) and northern \"**咸党**\" (savoury party) clash online every year. China also has **八大菜系**, eight great regional cuisines, from fiery Sichuan to delicate Cantonese."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Je n'ai pas fini mes devoirs. »", "\"I haven't finished my homework.\""),
        options: ["我把作业没写完。", "我没把作业写完。", "我把没作业写完。", "我把作业写没完。"],
        answer: 1,
        explain: t("La négation se place avant 把.", "Negation goes before 把."),
      },
      {
        type: "choice",
        prompt: t("« Coupe les pommes de terre en julienne. »", "\"Cut the potatoes into strips.\""),
        options: ["切土豆成丝。", "把土豆切到丝。", "把土豆切成丝。", "把土豆成丝切。"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: t("Dans une recette (instructions), on dit :", "In a recipe (instructions), you say:"),
        options: ["先洗菜，又切菜。", "先洗菜，再切菜。", "再洗菜，先切菜。", "洗菜先，切菜再。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "水一开，",
        after: "把面条放进去。",
        options: ["才", "就", "再", "又"],
        answer: 1,
        tr: t("Dès que l'eau bout, mets les nouilles.", "As soon as the water boils, put the noodles in."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我把做法都记",
        after: "了。",
        options: ["下去", "起来", "下来", "出去"],
        answer: 2,
        tr: t("J'ai noté toute la méthode.", "I wrote down all the steps."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "请把这个菜谱翻译",
        after: "法语。",
        options: ["到", "成", "在", "给"],
        answer: 1,
        tr: t("Traduis cette recette en français, s'il te plaît.", "Please translate this recipe into French."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["别", "把油", "放得", "太多"],
        tr: t("Ne mets pas trop d'huile.", "Don't put in too much oil."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["先把西红柿", "洗干净，", "再", "切成小块"],
        tr: t("Lave d'abord les tomates, puis coupe-les en petits morceaux.", "First wash the tomatoes, then cut them into small pieces."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["这个菜谱", "是我奶奶", "传下来", "的"],
        tr: t("Cette recette m'a été transmise par ma grand-mère.", "This recipe was handed down from my grandmother."),
      },
      {
        type: "listen",
        zh: "油一热，就把鸡蛋倒进去。",
        options: ["油一热，就把鸡蛋倒进去。", "油热了以后，把鸡蛋拿出来。", "鸡蛋一热，就把油倒进去。", "油不热，别把鸡蛋倒进去。"],
        answer: 0,
        tr: t("Dès que l'huile est chaude, verse les œufs.", "As soon as the oil is hot, pour in the eggs."),
      },
      {
        type: "listen",
        zh: "我刚才把糖看成盐了。",
        options: ["我刚才把盐看成糖了。", "我刚才把糖放进去了。", "我刚才把糖看成盐了。", "我刚才没看见糖和盐。"],
        answer: 2,
        tr: t("J'ai confondu le sucre avec le sel tout à l'heure.", "I just mistook the sugar for salt."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("炒", "chǎo", "faire sauter", "stir-fry"),
          mp("切", "qiē", "couper", "cut"),
          mp("盐", "yán", "sel", "salt"),
          mp("糖", "táng", "sucre", "sugar"),
          mp("锅", "guō", "wok, marmite", "wok, pot"),
          mp("味道", "wèidao", "goût", "taste"),
        ],
      },
      {
        type: "choice",
        prompt: t("« Je veux absolument apprendre ce plat. »", "\"I'm determined to learn this dish.\""),
        options: ["我把这个菜一定要学会。", "我一定要把这个菜学会。", "我把这个菜学会一定要。", "我一定把要这个菜学会。"],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L13 — Sports events
  {
    id: "hsk3-l13",
    level: 3,
    order: 13,
    title: t("La finale de ping-pong", "The table tennis final"),
    subtitle: t("Vivre un match en direct", "Watching a match live"),
    theme: "hobbies",
    goals: [
      t("Commenter un match et exprimer des émotions fortes (极了, 死了)", "Comment on a match and express strong emotions (极了, 死了)"),
      t("Dire combien de temps dure une activité (compléments de durée)", "Say how long an activity lasts (duration complements)"),
      t("Distinguer 马上, 立刻, 刚 et 刚才", "Tell 马上, 立刻, 刚 and 刚才 apart"),
      t("Argumenter avec 一方面……另一方面 et décrire une hésitation avec V来V去", "Argue with 一方面……另一方面 and describe hesitation with V来V去"),
    ],
    dialogue: {
      context: t(
        "Jack et Wang Lei regardent ensemble la finale de tennis de table à la télévision.",
        "Jack and Wang Lei are watching the table tennis final together on TV."
      ),
      lines: [
        ln("王磊", "快点儿，比赛马上就开始了！", "Kuài diǎnr, bǐsài mǎshàng jiù kāishǐ le!", "Dépêche-toi, le match va commencer !", "Hurry up, the match is about to start!"),
        ln("杰克", "来了来了！我刚到。今天是乒乓球决赛吗？", "Lái le lái le! Wǒ gāng dào. Jīntiān shì pīngpāngqiú juésài ma?", "J'arrive ! Je viens d'arriver. C'est la finale de ping-pong aujourd'hui ?", "Coming! I just got here. Is today the table tennis final?"),
        ln("王磊", "对，中国队对日本队。为了看这场比赛，我等了一个星期了。", "Duì, Zhōngguó duì duì Rìběn duì. Wèile kàn zhè chǎng bǐsài, wǒ děng le yí ge xīngqī le.", "Oui, la Chine contre le Japon. Ça fait une semaine que j'attends ce match.", "Yes, China versus Japan. I've been waiting a whole week for this match."),
        ln("杰克", "你每天都打乒乓球吗？", "Nǐ měi tiān dōu dǎ pīngpāngqiú ma?", "Tu joues au ping-pong tous les jours ?", "Do you play table tennis every day?"),
        ln("王磊", "差不多，每天打一个小时。打乒乓球一方面可以锻炼身体，另一方面也可以交朋友。", "Chàbuduō, měi tiān dǎ yí ge xiǎoshí. Dǎ pīngpāngqiú yì fāngmiàn kěyǐ duànliàn shēntǐ, lìng yì fāngmiàn yě kěyǐ jiāo péngyou.", "Presque, une heure par jour. Le ping-pong, d'un côté ça fait faire du sport, de l'autre ça permet de se faire des amis.", "Pretty much — an hour a day. Table tennis keeps you fit on the one hand, and helps you make friends on the other."),
        ln("杰克", "你看，球一过来，他立刻就打回去了，太快了！", "Nǐ kàn, qiú yí guòlai, tā lìkè jiù dǎ huiqu le, tài kuài le!", "Regarde, dès que la balle arrive, il la renvoie immédiatement, c'est trop rapide !", "Look — as soon as the ball comes, he hits it straight back. So fast!"),
        ln("王磊", "他是世界冠军，已经练了二十年了。", "Tā shì shìjiè guànjūn, yǐjīng liàn le èrshí nián le.", "C'est un champion du monde, ça fait vingt ans qu'il s'entraîne.", "He's a world champion — he's been training for twenty years."),
        ln("杰克", "哎呀，刚才那个球没接住，丢了一分。", "Āiyā, gāngcái nàge qiú méi jiēzhù, diū le yì fēn.", "Oh non, il a raté la balle, il a perdu un point.", "Oh no, he missed that one just now — lost a point."),
        ln("王磊", "别担心，还是十比八。你看教练在场边走来走去，比我们还紧张。", "Bié dānxīn, háishi shí bǐ bā. Nǐ kàn jiàoliàn zài chǎng biān zǒu lái zǒu qù, bǐ wǒmen hái jǐnzhāng.", "T'inquiète, c'est toujours dix à huit. Regarde l'entraîneur qui fait les cent pas, il est encore plus stressé que nous.", "Don't worry, it's still ten–eight. Look at the coach pacing up and down — he's even more nervous than us."),
        ln("杰克", "赢了！赢了！太精彩了！", "Yíng le! Yíng le! Tài jīngcǎi le!", "Gagné ! Gagné ! C'était génial !", "They won! They won! That was brilliant!"),
        ln("王磊", "我高兴极了！喊了两个小时，累死了！", "Wǒ gāoxìng jí le! Hǎn le liǎng ge xiǎoshí, lèi sǐ le!", "Je suis fou de joie ! J'ai crié pendant deux heures, je suis mort !", "I'm over the moon! I've been shouting for two hours — I'm exhausted!"),
        ln("杰克", "我想来想去，决定明天开始跟你一起学打乒乓球！", "Wǒ xiǎng lái xiǎng qù, juédìng míngtiān kāishǐ gēn nǐ yìqǐ xué dǎ pīngpāngqiú!", "J'ai bien réfléchi : dès demain, j'apprends le ping-pong avec toi !", "I've thought it over — starting tomorrow, I'm learning table tennis with you!"),
      ],
    },
    vocab: ["比赛", "马上", "刚", "刚才", "立刻", "乒乓球", "队", "场", "锻炼", "方面", "运动员", "世界", "冠军", "练", "接", "分", "担心", "教练", "紧张", "赢", "输", "精彩", "极", "喊", "决定", "体育馆", "足球", "篮球", "游泳", "跑步", "差不多"],
    grammar: ["hsk3-g63", "hsk3-g64", "hsk3-g65", "hsk3-g66", "hsk3-g67"],
    culture: {
      title: t("Le ping-pong, « balle nationale »", "Table tennis, the \"national ball\""),
      body: t(
        "En Chine, le tennis de table est surnommé **国球** (« le sport national »). L'équipe chinoise domine la discipline depuis des décennies, et on trouve des tables en béton dans presque tous les parcs et toutes les écoles.\n\nLe ping-pong a même joué un rôle diplomatique : en 1971, la **« diplomatie du ping-pong »** (乒乓外交) a rapproché la Chine et les États-Unis. Autres sports très suivis : le **basket** (篮球), le **football** (足球) — malgré les résultats décevants de l'équipe nationale — et le **volley féminin** (女排), dont les victoires sont un symbole de persévérance.",
        "In China, table tennis is nicknamed **国球** (\"the national ball\"). The Chinese team has dominated the sport for decades, and there are concrete tables in nearly every park and school.\n\nPing-pong even played a diplomatic role: in 1971, **\"ping-pong diplomacy\"** (乒乓外交) helped bring China and the USA closer. Other hugely popular sports: **basketball** (篮球), **football** (足球) — despite the national team's disappointing results — and **women's volleyball** (女排), whose victories symbolise perseverance."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« J'ai joué au basket pendant deux heures. »", "\"I played basketball for two hours.\""),
        options: ["我两个小时打篮球了。", "我打了两个小时篮球。", "我打篮球了两个小时。", "我两个小时打了篮球。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est incorrecte ?", "Which sentence is incorrect?"),
        options: ["我高兴极了。", "我累死了。", "我很累死了。", "比赛紧张得不得了。"],
        answer: 2,
        explain: t("Pas de 很 avec 死了.", "No 很 with 死了."),
      },
      {
        type: "choice",
        prompt: t("« Où étais-tu tout à l'heure ? »", "\"Where were you just now?\""),
        options: ["刚你去哪儿了？", "刚才你去哪儿了？", "你马上去哪儿了？", "你立刻去哪儿了？"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "我在体育馆等了",
        after: "半个小时！",
        options: ["他", "了", "过", "的"],
        answer: 0,
        tr: t("Je l'ai attendu une demi-heure au gymnase !", "I waited for him at the gym for half an hour!"),
        explain: t("Un pronom se place avant la durée.", "A pronoun comes before the duration."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "运动一方面可以锻炼身体，",
        after: "也可以交朋友。",
        options: ["其他方面", "另一方面", "一边", "然后"],
        answer: 1,
        tr: t("Le sport permet d'une part de se maintenir en forme, d'autre part de se faire des amis.", "Sport keeps you fit on the one hand, and helps you make friends on the other."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "球票我找来",
        after: "也没找到。",
        options: ["找去", "找来", "去找", "走去"],
        answer: 0,
        tr: t("J'ai cherché mon billet partout, impossible de le trouver.", "I searched everywhere but couldn't find the ticket."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["她", "练游泳", "练了", "十年", "了"],
        tr: t("Ça fait dix ans qu'elle s'entraîne à la natation.", "She's been training in swimming for ten years."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["快点儿，", "比赛", "马上", "就", "开始了"],
        tr: t("Dépêche-toi, le match va commencer !", "Hurry up, the match is about to start!"),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["教练", "在场边", "走来走去"],
        tr: t("L'entraîneur fait les cent pas au bord du terrain.", "The coach paces up and down the sideline."),
      },
      {
        type: "listen",
        zh: "我高兴极了！喊了两个小时，累死了！",
        options: ["我累极了，睡了两个小时。", "我高兴极了！喊了两个小时，累死了！", "我不高兴，等了两个小时。", "他高兴极了，跑了两个小时。"],
        answer: 1,
        tr: t("Je suis fou de joie ! J'ai crié deux heures, je suis mort !", "I'm over the moon! Two hours of shouting — I'm exhausted!"),
      },
      {
        type: "listen",
        zh: "他是世界冠军，已经练了二十年了。",
        options: ["他是世界冠军，已经练了十年了。", "他想当世界冠军，练了二十年。", "他是世界冠军，已经练了二十年了。", "他是教练，已经教了二十年了。"],
        answer: 2,
        tr: t("C'est un champion du monde, il s'entraîne depuis vingt ans.", "He's a world champion who's been training for twenty years."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("赢", "yíng", "gagner", "win"),
          mp("输", "shū", "perdre (un match)", "lose (a match)"),
          mp("冠军", "guànjūn", "champion", "champion"),
          mp("教练", "jiàoliàn", "entraîneur", "coach"),
          mp("精彩", "jīngcǎi", "passionnant, génial", "brilliant, exciting"),
        ],
      },
      {
        type: "choice",
        prompt: t("« Je viens d'arriver. »", "\"I've just arrived.\""),
        options: ["我刚到。", "刚我到。", "我立刻到了。", "我马上到了。"],
        answer: 0,
      },
    ],
  },

  // ─────────────────────────────── L14 — Money & banking
  {
    id: "hsk3-l14",
    level: 3,
    order: 14,
    title: t("Fin de mois difficile", "Broke by month's end"),
    subtitle: t("Argent, banque et épargne", "Money, banks and saving"),
    theme: "shopping",
    goals: [
      t("Parler de son budget, d'emprunt et d'épargne", "Talk about budgets, borrowing and saving"),
      t("Décrire une alternative habituelle avec 不是……就是", "Describe habitual alternatives with 不是……就是"),
      t("Insister avec la double négation (不得不, 没有……不) et les questions rhétoriques", "Emphasise with double negatives (不得不, 没有……不) and rhetorical questions"),
      t("Faire des hypothèses avec 要是 / 假如……的话 et exagérer avec 简直", "Make suppositions with 要是 / 假如……的话 and exaggerate with 简直"),
    ],
    dialogue: {
      context: t(
        "He Xue découvre que son ami Zhou Ming a encore besoin d'emprunter de l'argent.",
        "He Xue finds out her friend Zhou Ming needs to borrow money again."
      ),
      lines: [
        ln("何雪", "周明，你怎么又借钱？你不是上个月刚发了工资吗？", "Zhōu Míng, nǐ zěnme yòu jiè qián? Nǐ bú shì shàng ge yuè gāng fā le gōngzī ma?", "Zhou Ming, tu empruntes encore de l'argent ? Tu n'as pas été payé le mois dernier ?", "Zhou Ming, borrowing money again? Didn't you just get paid last month?"),
        ln("周明", "别提了。我的工资不是交房租，就是还信用卡，每个月都不够花。", "Bié tí le. Wǒ de gōngzī bú shì jiāo fángzū, jiù shì huán xìnyòngkǎ, měi ge yuè dōu bú gòu huā.", "M'en parle pas. Mon salaire passe soit dans le loyer, soit dans la carte de crédit : chaque mois, ça ne suffit pas.", "Don't ask. My salary goes either on rent or on my credit card — it's never enough."),
        ln("何雪", "你简直是“月光族”！", "Nǐ jiǎnzhí shì “yuèguāngzú”!", "Tu es carrément un « claque-tout-son-salaire » !", "You're a total \"moonlight clan\" member — broke every month!"),
        ln("周明", "我不是不想存钱，是真的存不下来。", "Wǒ bú shì bù xiǎng cún qián, shì zhēn de cún bu xialai.", "Ce n'est pas que je ne veux pas économiser, c'est que je n'y arrive vraiment pas.", "It's not that I don't want to save — I really can't manage it."),
        ln("何雪", "要是你每个月存一点儿的话，一年以后就是一笔不少的钱。", "Yàoshi nǐ měi ge yuè cún yìdiǎnr dehuà, yì nián yǐhòu jiù shì yì bǐ bù shǎo de qián.", "Si tu mettais un peu de côté chaque mois, au bout d'un an ça ferait une jolie somme.", "If you saved a little each month, after a year you'd have quite a sum."),
        ln("周明", "可是存在银行，利息太少了。", "Kěshì cún zài yínháng, lìxī tài shǎo le.", "Mais à la banque, les intérêts sont ridicules.", "But in the bank, the interest is so low."),
        ln("何雪", "少也比没有好啊！你怎么能把钱都花光呢？", "Shǎo yě bǐ méiyǒu hǎo a! Nǐ zěnme néng bǎ qián dōu huāguāng ne?", "C'est toujours mieux que rien ! Comment tu peux dépenser tout ton argent ?", "A little is better than nothing! How can you spend every last penny?"),
        ln("周明", "你说得对。这个月我不得不向我哥借了两千块。", "Nǐ shuō de duì. Zhège yuè wǒ bùdébù xiàng wǒ gē jiè le liǎng qiān kuài.", "Tu as raison. Ce mois-ci, j'ai été obligé d'emprunter deux mille yuans à mon frère.", "You're right. This month I had to borrow two thousand yuan from my brother."),
        ln("何雪", "明天我陪你去银行，办一张新卡，专门用来存钱。", "Míngtiān wǒ péi nǐ qù yínháng, bàn yì zhāng xīn kǎ, zhuānmén yònglái cún qián.", "Demain, je t'accompagne à la banque ouvrir une nouvelle carte, juste pour l'épargne.", "Tomorrow I'll go to the bank with you to get a new card, just for savings."),
        ln("周明", "好吧。假如我一年能存一万块，我就请你吃大餐！", "Hǎo ba. Jiǎrú wǒ yì nián néng cún yí wàn kuài, wǒ jiù qǐng nǐ chī dà cān!", "D'accord. Si j'arrive à mettre dix mille yuans de côté en un an, je t'invite dans un grand resto !", "Fine. If I manage to save ten thousand yuan in a year, I'll treat you to a feast!"),
        ln("何雪", "一言为定！没有人不喜欢存钱成功的感觉。", "Yì yán wéi dìng! Méiyǒu rén bù xǐhuan cún qián chénggōng de gǎnjué.", "Marché conclu ! Tout le monde aime la sensation d'avoir réussi à épargner.", "It's a deal! Everybody loves the feeling of saving successfully."),
        ln("周明", "哈哈，一万块？我哪儿有那么多钱啊！先存一千试试吧。", "Hāhā, yí wàn kuài? Wǒ nǎr yǒu nàme duō qián a! Xiān cún yì qiān shìshi ba.", "Haha, dix mille ? Où veux-tu que je trouve autant ? On va commencer par mille.", "Haha, ten thousand? Where would I get that kind of money! Let me try saving a thousand first."),
      ],
    },
    vocab: ["借", "还", "工资", "房租", "信用卡", "够", "花", "简直", "存", "要是", "银行", "利息", "不得不", "向", "陪", "办", "卡", "专门", "假如", "万", "感觉", "成功", "现金", "付", "换", "人民币", "价格", "便宜", "收入", "经济", "取"],
    grammar: ["hsk3-g68", "hsk3-g69", "hsk3-g70", "hsk3-g71", "hsk3-g72"],
    culture: {
      title: t("« Moonlight clan » et paiement mobile", "The \"moonlight clan\" and mobile payment"),
      body: t(
        "**月光族** (yuèguāngzú) est un jeu de mots : 月 = mois, 光 = épuisé (et aussi « lumière ») → ceux qui **dépensent tout leur salaire** (月) jusqu'au dernier centime (光). Traditionnellement, les Chinois épargnent pourtant beaucoup : le taux d'épargne des ménages est l'un des plus élevés au monde.\n\nAujourd'hui, on paie surtout avec **支付宝** (Alipay) ou **微信支付** (WeChat Pay), et beaucoup de jeunes n'ont presque jamais d'espèces sur eux. À l'oral, on compte en **块** (kuài) plutôt qu'en 元 (yuán), et 10 centimes se disent **毛** (máo).",
        "**月光族** (yuèguāngzú) is a pun: 月 = month, 光 = used up (also \"light\") → people who **spend their whole monthly salary** (月) down to the last cent (光). Traditionally, though, Chinese people save a lot: household savings rates are among the world's highest.\n\nToday people mostly pay with **支付宝** (Alipay) or **微信支付** (WeChat Pay), and many young people hardly ever carry cash. In speech, money is counted in **块** (kuài) rather than 元 (yuán), and 10 cents is **毛** (máo)."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("« Le week-end, soit je cuisine, soit je fais les courses. »", "\"At weekends I either cook or go shopping.\""),
        options: ["周末我不是做饭，而是买东西。", "周末我不是做饭，就是买东西。", "周末我不是做饭，还是买东西。", "周末我不做饭，也不买东西。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Que signifie 没有人不喜欢他 ?", "What does 没有人不喜欢他 mean?"),
        options: [
          t("Personne ne l'aime.", "Nobody likes him."),
          t("Tout le monde l'aime.", "Everybody likes him."),
          t("Il n'aime personne.", "He likes nobody."),
          t("Quelques personnes l'aiment.", "Some people like him."),
        ],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["我得不得去银行。", "我不得不去银行。", "我不得去不银行。", "我不不得去银行。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "要是你的银行卡丢了",
        after: "，要马上给银行打电话。",
        options: ["的话", "以后", "的时候了", "就"],
        answer: 0,
        tr: t("Si tu perds ta carte bancaire, appelle la banque tout de suite.", "If you lose your bank card, call the bank straight away."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这里的房价",
        after: "太高了！",
        options: ["简直", "稍微", "并", "不得不"],
        answer: 0,
        tr: t("Les prix de l'immobilier ici sont carrément délirants !", "House prices here are just ridiculous!"),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "这么多钱，我怎么能一个人花",
        after: "？",
        options: ["吗", "呢", "吧", "了"],
        answer: 1,
        tr: t("Tout cet argent, comment pourrais-je le dépenser seul ?", "How could I spend all this money by myself?"),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["你", "不是", "上个月", "刚发了工资", "吗"],
        tr: t("Tu n'as pas été payé le mois dernier ?", "Didn't you just get paid last month?"),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我", "不是", "不想买，", "是", "太贵了"],
        tr: t("Ce n'est pas que je ne veux pas l'acheter, c'est trop cher.", "It's not that I don't want to buy it — it's too expensive."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["假如", "我有很多钱，", "我", "就去", "环游世界"],
        tr: t("Si j'avais beaucoup d'argent, je ferais le tour du monde.", "If I had lots of money, I'd travel around the world."),
      },
      {
        type: "listen",
        zh: "我的工资不是交房租，就是还信用卡。",
        options: ["我的工资不是交房租，而是还信用卡。", "我的工资不够交房租。", "我的工资不是交房租，就是还信用卡。", "我用信用卡交房租。"],
        answer: 2,
        tr: t("Mon salaire passe soit dans le loyer, soit dans la carte de crédit.", "My salary goes either on rent or on my credit card."),
      },
      {
        type: "listen",
        zh: "这个月我不得不向我哥借钱。",
        options: ["这个月我不想向我哥借钱。", "这个月我不得不向我哥借钱。", "这个月我哥不得不向我借钱。", "这个月我不用向我哥借钱。"],
        answer: 1,
        tr: t("Ce mois-ci, j'ai été obligé d'emprunter de l'argent à mon frère.", "This month I had to borrow money from my brother."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("借", "jiè", "emprunter, prêter", "borrow, lend"),
          mp("存", "cún", "épargner, déposer", "save, deposit"),
          mp("利息", "lìxī", "intérêts", "interest"),
          mp("现金", "xiànjīn", "espèces", "cash"),
          mp("信用卡", "xìnyòngkǎ", "carte de crédit", "credit card"),
          mp("收入", "shōurù", "revenu", "income"),
        ],
      },
      {
        type: "choice",
        prompt: t("我哪儿有钱啊！ signifie :", "我哪儿有钱啊！ means:"),
        options: [
          t("Où est mon argent ?", "Where's my money?"),
          t("Je n'ai pas du tout d'argent !", "I've got no money at all!"),
          t("J'ai de l'argent quelque part.", "I have money somewhere."),
          t("Où puis-je trouver de l'argent ?", "Where can I find money?"),
        ],
        answer: 1,
      },
    ],
  },

  // ─────────────────────────────── L15 — A short story
  {
    id: "hsk3-l15",
    level: 3,
    order: 15,
    title: t("Les brioches d'un soir de neige", "Buns on a snowy night"),
    subtitle: t("Lire et raconter une petite histoire", "Reading and telling a short story"),
    theme: "culture",
    goals: [
      t("Comprendre un court récit au passé", "Understand a short story set in the past"),
      t("Rendre une description vivante avec le redoublement (AABB, ABB)", "Make descriptions vivid with reduplication (AABB, ABB)"),
      t("Faire des comparaisons imagées avec 像……一样 / 似的", "Use vivid comparisons with 像……一样 / 似的"),
      t("Raconter une évolution avec 渐渐, V着V着 et 互相", "Narrate change with 渐渐, V着V着 and 互相"),
    ],
    dialogue: {
      context: t(
        "Un court récit : un soir d'hiver, Xiao Lin, qui rentre du travail à pied, découvre une petite boutique de brioches à la vapeur.",
        "A short story: one winter evening, Xiao Lin, walking home from work, comes across a little steamed-bun shop."
      ),
      lines: [
        ln("旁白", "那是一个很冷的冬天，雪下得像棉花一样。", "Nà shì yí ge hěn lěng de dōngtiān, xuě xià de xiàng miánhua yíyàng.", "C'était un hiver très froid ; la neige tombait comme du coton.", "It was a bitterly cold winter; the snow fell like cotton."),
        ln("旁白", "小林下班以后，一个人慢慢地走在回家的路上。", "Xiǎo Lín xiàbān yǐhòu, yí ge rén mànmàn de zǒu zài huí jiā de lù shang.", "Après le travail, Xiao Lin rentrait seule chez elle, lentement.", "After work, Xiao Lin walked home alone, slowly."),
        ln("旁白", "走着走着，天渐渐黑了，路上的人越来越少。", "Zǒu zhe zǒu zhe, tiān jiànjiàn hēi le, lù shang de rén yuè lái yuè shǎo.", "Tandis qu'elle marchait, la nuit tombait peu à peu et les passants se faisaient rares.", "As she walked on, it gradually grew dark and there were fewer and fewer people about."),
        ln("旁白", "突然，她看见路边有一家小小的包子店，里面亮亮的，热热闹闹的。", "Tūrán, tā kànjiàn lù biān yǒu yì jiā xiǎoxiǎo de bāozi diàn, lǐmiàn liàngliàng de, rèrènāonāo de.", "Soudain, elle aperçut au bord de la route une toute petite boutique de brioches, bien éclairée et pleine de vie.", "Suddenly she saw a tiny bun shop by the road, all lit up and bustling."),
        ln("老板", "姑娘，外面冷，快进来吃个包子吧！", "Gūniang, wàimiàn lěng, kuài jìnlai chī ge bāozi ba!", "Mademoiselle, il fait froid dehors, entrez donc manger une brioche !", "Miss, it's cold out there — come in and have a bun!"),
        ln("小林", "可是我忘了带钱包……", "Kěshì wǒ wàng le dài qiánbāo……", "Mais j'ai oublié mon portefeuille…", "But I forgot my wallet…"),
        ln("老板", "没关系，下次再给！", "Méi guānxi, xià cì zài gěi!", "Ce n'est pas grave, vous paierez la prochaine fois !", "Never mind, pay next time!"),
        ln("旁白", "老板给她拿来两个热乎乎的包子，还有一碗汤。", "Lǎobǎn gěi tā nálai liǎng ge rèhūhū de bāozi, hái yǒu yì wǎn tāng.", "Le patron lui apporta deux brioches toutes chaudes et un bol de soupe.", "The owner brought her two piping-hot buns and a bowl of soup."),
        ln("旁白", "小林吃着吃着，眼睛就红了，好像又回到了小时候似的。", "Xiǎo Lín chī zhe chī zhe, yǎnjing jiù hóng le, hǎoxiàng yòu huídào le xiǎo shíhou shìde.", "En mangeant, Xiao Lin sentit ses yeux s'embuer, comme si elle était redevenue petite fille.", "As she ate, Xiao Lin's eyes filled with tears, as if she were a child again."),
        ln("小林", "这个味道，跟我奶奶做的一模一样。", "Zhège wèidao, gēn wǒ nǎinai zuò de yìmú-yíyàng.", "Ce goût… c'est exactement celui des brioches de ma grand-mère.", "This taste… it's exactly like my grandma's."),
        ln("旁白", "第二天，小林高高兴兴地来还钱，还给老板带了一盒点心。", "Dì-èr tiān, Xiǎo Lín gāogāoxìngxìng de lái huán qián, hái gěi lǎobǎn dài le yì hé diǎnxin.", "Le lendemain, Xiao Lin revint toute joyeuse pour payer, avec une boîte de pâtisseries pour le patron.", "The next day, Xiao Lin happily came back to pay, bringing the owner a box of pastries."),
        ln("旁白", "渐渐地，他们成了好朋友，经常互相帮助。", "Jiànjiàn de, tāmen chéng le hǎo péngyou, jīngcháng hùxiāng bāngzhù.", "Peu à peu, ils devinrent de bons amis et s'entraidaient souvent.", "Little by little, they became good friends and often helped each other."),
        ln("旁白", "从那以后，每个下雪的晚上，小林都会想起那两个热乎乎的包子。", "Cóng nà yǐhòu, měi ge xià xuě de wǎnshang, Xiǎo Lín dōu huì xiǎngqǐ nà liǎng ge rèhūhū de bāozi.", "Depuis, chaque soir de neige, Xiao Lin repense à ces deux brioches toutes chaudes.", "Ever since, on every snowy evening, Xiao Lin remembers those two piping-hot buns."),
      ],
    },
    vocab: ["冬天", "雪", "像", "一样", "似的", "下班", "慢", "渐渐", "黑", "突然", "包子", "店", "亮", "热闹", "老板", "姑娘", "钱包", "碗", "汤", "眼睛", "好像", "小时候", "味道", "奶奶", "还", "盒", "点心", "互相", "帮助", "想起", "经常", "故事"],
    grammar: ["hsk3-g73", "hsk3-g74", "hsk3-g75", "hsk3-g76", "hsk3-g77"],
    culture: {
      title: t("Le 人情味 : la chaleur humaine", "人情味: human warmth"),
      body: t(
        "Les Chinois aiment les histoires pleines de **人情味** (rénqíngwèi), littéralement « le goût des sentiments humains » : la gentillesse d'un inconnu, l'entraide entre voisins, un petit commerçant qui fait crédit… Ce genre de récit est très fréquent dans les manuels scolaires et sur les réseaux sociaux.\n\nLes **包子** (brioches farcies cuites à la vapeur) sont le petit-déjeuner ou l'en-cas populaire par excellence. Dans les quartiers, les petites boutiques de **早点** (petit-déjeuner) ouvrent dès 6 heures et les habitués connaissent souvent le patron par son nom : c'est tout un monde de relations de quartier (街坊).",
        "Chinese people love stories full of **人情味** (rénqíngwèi), literally \"the flavour of human feeling\": a stranger's kindness, neighbours helping each other, a shopkeeper giving credit… Such stories are common in school textbooks and on social media.\n\n**包子** (steamed stuffed buns) are the classic popular breakfast or snack. In residential areas, little **早点** (breakfast) shops open from 6 a.m., and regulars often know the owner by name — a whole world of neighbourhood ties (街坊)."
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle forme redoublée est correcte ?", "Which reduplicated form is correct?"),
        options: ["很干干净净", "干净干净的", "干干净净的", "干干净的净"],
        answer: 2,
      },
      {
        type: "choice",
        prompt: t("« Petit à petit, nous sommes devenus amis. »", "\"Little by little, we became friends.\""),
        options: ["渐渐地，我们成了好朋友。", "马上，我们成了好朋友。", "我们渐渐很好朋友。", "我们成了渐渐好朋友。"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: t("Comment se prononce 似的 ?", "How is 似的 pronounced?"),
        options: ["sìde", "shìde", "sìdí", "shǐde"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "孩子听着",
        after: "就睡着了。",
        options: ["听着", "看着", "听了", "听过"],
        answer: 0,
        tr: t("L'enfant s'est endormi en écoutant.", "The child fell asleep while listening."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "那天的雪下得像棉花",
        after: "。",
        options: ["一样", "一起", "似", "一点儿"],
        answer: 0,
        tr: t("Ce jour-là, la neige tombait comme du coton.", "That day the snow fell like cotton."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Fill in the blank."),
        before: "邻居之间应该",
        after: "帮助。",
        options: ["渐渐", "互相", "一起来", "似的"],
        answer: 1,
        tr: t("Entre voisins, il faut s'entraider.", "Neighbours should help each other."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["孩子们", "高高兴兴地", "回家", "了"],
        tr: t("Les enfants sont rentrés chez eux tout joyeux.", "The children went home happily."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["我们", "聊着聊着，", "突然", "下起雨来了"],
        tr: t("On discutait quand soudain il s'est mis à pleuvoir.", "We were chatting when it suddenly started to rain."),
      },
      {
        type: "order",
        prompt: t("Remets les mots dans l'ordre.", "Put the words in order."),
        tokens: ["他", "跑得飞快，", "好像", "有人追他", "似的"],
        tr: t("Il courait à toute vitesse, comme si quelqu'un le poursuivait.", "He ran like the wind, as if someone were chasing him."),
      },
      {
        type: "listen",
        zh: "走着走着，天渐渐黑了。",
        options: ["走着走着，天渐渐亮了。", "走着走着，天渐渐黑了。", "天黑了，我们走吧。", "我们一边走一边说话。"],
        answer: 1,
        tr: t("Tandis qu'elle marchait, la nuit tombait peu à peu.", "As she walked on, it gradually grew dark."),
      },
      {
        type: "listen",
        zh: "老板给她拿来两个热乎乎的包子。",
        options: ["老板给她拿来两个热乎乎的包子。", "老板给她拿来两碗热乎乎的汤。", "她给老板拿来两个包子。", "老板给她做了三个包子。"],
        answer: 0,
        tr: t("Le patron lui apporta deux brioches toutes chaudes.", "The owner brought her two piping-hot buns."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à sa traduction.", "Match each word with its meaning."),
        pairs: [
          mp("突然", "tūrán", "soudain", "suddenly"),
          mp("老板", "lǎobǎn", "patron", "boss, owner"),
          mp("味道", "wèidao", "goût", "taste"),
          mp("故事", "gùshi", "histoire, récit", "story"),
          mp("想起", "xiǎngqǐ", "se rappeler", "recall"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est incorrecte ?", "Which sentence is incorrect?"),
        options: ["我们互相帮助。", "他们互相看了一眼。", "我互相帮助他。", "邻居应该互相帮助。"],
        answer: 2,
        explain: t("互相 demande un sujet pluriel.", "互相 needs a plural subject."),
      },
    ],
  },
];
