import type { GrammarPoint } from "../../types";
import { ex, t } from "./helpers";

export const grammarA: GrammarPoint[] = [
  {
    id: "hsk2-g01",
    level: 2,
    title: t("Les mots de localisation : 里边, 旁边, 对面…", "Location words: 里边, 旁边, 对面…"),
    pattern: "Nom + 上边 / 里边 / 旁边 / 对面…",
    category: "名词 / nouns (方位名词)",
    explanation: t(
      "Pour dire **où** se trouve quelque chose, le chinois place le **mot de localisation après le nom**, à l'inverse du français : « dans la chambre » se dit 房间**里边** (litt. « chambre-intérieur »).\n\nLes plus fréquents : **上边** (dessus), **下边** (dessous), **里边** (dedans), **外边** (dehors), **前边** (devant), **后边** (derrière), **左边 / 右边** (à gauche / à droite), **旁边** (à côté), **对面** (en face), **中间** (au milieu), et les points cardinaux **东边, 南边, 西边, 北边**.\n\n边 peut souvent être remplacé par **面** (上面, 里面) ou **头** (里头, 外头, plus oral). Après un nom, on abrège souvent en **上 / 里** : 桌子上, 房间里.\n\nOn les combine avec **在** (« se trouver ») ou avec **有** (« il y a ») : 超市在银行**旁边**。/ 银行**旁边**有一个超市。",
      "To say **where** something is, Chinese puts the **location word after the noun** — the opposite of English: \"in the room\" is 房间**里边** (lit. \"room-inside\").\n\nThe most common ones: **上边** (on top), **下边** (under), **里边** (inside), **外边** (outside), **前边** (in front), **后边** (behind), **左边 / 右边** (left / right), **旁边** (next to), **对面** (opposite), **中间** (in the middle), and the compass points **东边, 南边, 西边, 北边**.\n\n边 can often be replaced by **面** (上面, 里面) or **头** (里头, 外头, more colloquial). After a noun, it is often shortened to **上 / 里**: 桌子上, 房间里.\n\nCombine them with **在** (\"to be located\") or **有** (\"there is\"): 超市在银行**旁边**。/ 银行**旁边**有一个超市。",
    ),
    examples: [
      ex("超市在银行旁边。", "Chāoshì zài yínháng pángbiān.", "Le supermarché est à côté de la banque.", "The supermarket is next to the bank."),
      ex("我家对面有一个公园。", "Wǒ jiā duìmiàn yǒu yí ge gōngyuán.", "Il y a un parc en face de chez moi.", "There is a park opposite my home."),
      ex("你的手机在桌子上。", "Nǐ de shǒujī zài zhuōzi shang.", "Ton téléphone est sur la table.", "Your phone is on the table."),
      ex("房间里边很干净。", "Fángjiān lǐbian hěn gānjìng.", "L'intérieur de la chambre est très propre.", "It's very clean inside the room."),
    ],
    pitfalls: t(
      "Ne mets pas le mot de localisation avant le nom : ✗ 在旁边银行 → ✓ 在银行旁边.\nAvec un nom de pays ou de ville, on n'ajoute pas 里 : ✗ 在中国里 → ✓ 在中国.",
      "Don't put the location word before the noun: ✗ 在旁边银行 → ✓ 在银行旁边.\nWith a country or city name, don't add 里: ✗ 在中国里 → ✓ 在中国.",
    ),
  },
  {
    id: "hsk2-g02",
    level: 2,
    title: t("La distance avec 离", "Distance with 离"),
    pattern: "A + 离 + B + 很近 / 很远 / 不远",
    category: "介词 / prepositions",
    explanation: t(
      "**离** (lí) sert à exprimer la **distance** entre deux points (dans l'espace ou dans le temps). A 离 B 很近 = « A est près de B ».\n\nL'ordre est fixe : **lieu 1 + 离 + lieu 2 + adjectif** (近, 远) ou quantité (一公里, 五分钟). 离 n'est pas un verbe principal : il faut un prédicat après.\n\nOn l'utilise aussi pour le temps : 离春节**还有**三天 (« il reste trois jours avant la fête du Printemps »).",
      "**离** (lí) expresses the **distance** between two points (in space or time). A 离 B 很近 = \"A is close to B\".\n\nThe order is fixed: **place 1 + 离 + place 2 + adjective** (近, 远) or an amount (一公里, 五分钟). 离 is not the main verb: something must follow it.\n\nIt also works for time: 离春节**还有**三天 (\"there are still three days until Spring Festival\").",
    ),
    examples: [
      ex("我家离地铁站很近。", "Wǒ jiā lí dìtiězhàn hěn jìn.", "Chez moi, c'est tout près du métro.", "My place is very close to the subway station."),
      ex("公司离这儿远不远？", "Gōngsī lí zhèr yuǎn bu yuǎn?", "L'entreprise est loin d'ici ?", "Is the company far from here?"),
      ex("学校离我家只有五分钟。", "Xuéxiào lí wǒ jiā zhǐ yǒu wǔ fēnzhōng.", "L'école n'est qu'à cinq minutes de chez moi.", "The school is only five minutes from my home."),
      ex("离考试还有一个星期。", "Lí kǎoshì hái yǒu yí ge xīngqī.", "Il reste encore une semaine avant l'examen.", "There's still a week until the exam."),
    ],
    pitfalls: t(
      "Ne confonds pas 离 (distance) et 从 (point de départ) : ✗ 我家从公司很近 → ✓ 我家离公司很近.\nN'utilise pas 是 avec l'adjectif : ✗ 我家离公司是很近 → ✓ 我家离公司很近.",
      "Don't confuse 离 (distance) and 从 (starting point): ✗ 我家从公司很近 → ✓ 我家离公司很近.\nNo 是 before the adjective: ✗ 我家离公司是很近 → ✓ 我家离公司很近.",
    ),
  },
  {
    id: "hsk2-g03",
    level: 2,
    title: t("Nouveaux classificateurs : 间, 层, 张, 件, 辆…", "New measure words: 间, 层, 张, 件, 辆…"),
    pattern: "Nombre / 这 / 那 + classificateur + Nom",
    category: "量词 / measure words",
    explanation: t(
      "En chinois, on ne peut pas dire « deux chambres » directement : il faut un **classificateur** entre le nombre et le nom. Au niveau 1 tu as vu 个, 本, 口… Voici ceux du niveau 2, qui dépendent souvent de la **forme** ou de la **nature** de l'objet :\n\n**间** (pièces : 一间卧室), **层** (étages : 三层), **张** (objets plats : 一张床, 一张桌子, 一张票), **件** (vêtements du haut, affaires : 一件衣服, 一件事), **条** (objets longs : 一条裤子, 一条路, 一条鱼), **双** (paires : 一双鞋), **辆** (véhicules : 一辆车), **位** (personnes, poli : 一位老师), **种** (sortes : 两种颜色).\n\nRappel : devant un classificateur, « deux » se dit **两**, pas 二.",
      "In Chinese you can't say \"two rooms\" directly: a **measure word** must sit between the number and the noun. In level 1 you learned 个, 本, 口… Level 2 adds these, often chosen by the object's **shape** or **nature**:\n\n**间** (rooms: 一间卧室), **层** (floors: 三层), **张** (flat things: 一张床, 一张桌子, 一张票), **件** (tops, matters: 一件衣服, 一件事), **条** (long things: 一条裤子, 一条路, 一条鱼), **双** (pairs: 一双鞋), **辆** (vehicles: 一辆车), **位** (people, polite: 一位老师), **种** (kinds: 两种颜色).\n\nReminder: before a measure word, \"two\" is **两**, not 二.",
    ),
    examples: [
      ex("这个房子有两间卧室。", "Zhège fángzi yǒu liǎng jiān wòshì.", "Cet appartement a deux chambres.", "This apartment has two bedrooms."),
      ex("我住在六层。", "Wǒ zhù zài liù céng.", "J'habite au sixième étage.", "I live on the sixth floor."),
      ex("房间里有一张床和一张桌子。", "Fángjiān li yǒu yì zhāng chuáng hé yì zhāng zhuōzi.", "Dans la chambre, il y a un lit et un bureau.", "There's a bed and a desk in the room."),
      ex("我想买一双鞋和一条裤子。", "Wǒ xiǎng mǎi yì shuāng xié hé yì tiáo kùzi.", "Je voudrais acheter une paire de chaussures et un pantalon.", "I'd like to buy a pair of shoes and a pair of trousers."),
      ex("那位先生是我们的老师。", "Nà wèi xiānsheng shì wǒmen de lǎoshī.", "Ce monsieur est notre professeur.", "That gentleman is our teacher."),
    ],
    pitfalls: t(
      "✗ 两个床 → ✓ 两张床 (个 est acceptable à l'oral pour beaucoup de choses, mais pas élégant).\n✗ 二辆车 → ✓ 两辆车.\n位 s'emploie pour être poli : ✗ 一位小偷 (un voleur) sonne bizarre → ✓ 一个小偷.",
      "✗ 两个床 → ✓ 两张床 (个 is tolerated in casual speech for many things, but sounds clumsy).\n✗ 二辆车 → ✓ 两辆车.\n位 is polite: ✗ 一位小偷 (a thief) sounds odd → ✓ 一个小偷.",
    ),
  },
  {
    id: "hsk2-g04",
    level: 2,
    title: t("又…又… : à la fois… et…", "又…又…: both… and…"),
    pattern: "Sujet + 又 + Adj/V + 又 + Adj/V",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "**又 A 又 B** relie deux qualités ou deux actions qui existent **en même temps**. C'est l'équivalent de « à la fois A et B ».\n\nLes deux éléments vont en général **dans le même sens** (deux qualités positives, ou deux négatives) : 又便宜又干净 (pas cher et propre), 又累又饿 (fatigué et affamé).\n\nAvec 又…又…, on **n'ajoute pas 很** devant les adjectifs.",
      "**又 A 又 B** links two qualities or actions that are true **at the same time**: \"both A and B\".\n\nBoth items usually point **the same way** (two positives or two negatives): 又便宜又干净 (cheap and clean), 又累又饿 (tired and hungry).\n\nWith 又…又…, **don't add 很** before the adjectives.",
    ),
    examples: [
      ex("这个房间又大又干净。", "Zhège fángjiān yòu dà yòu gānjìng.", "Cette chambre est à la fois grande et propre.", "This room is both big and clean."),
      ex("她做的菜又好看又好吃。", "Tā zuò de cài yòu hǎokàn yòu hǎochī.", "Ses plats sont aussi beaux que bons.", "Her dishes look good and taste good."),
      ex("我今天又累又饿。", "Wǒ jīntiān yòu lèi yòu è.", "Aujourd'hui je suis crevé et j'ai faim.", "I'm tired and hungry today."),
      ex("孩子们又唱又跳，非常高兴。", "Háizimen yòu chàng yòu tiào, fēicháng gāoxìng.", "Les enfants chantent et dansent, ils sont ravis.", "The kids sing and dance, very happy."),
    ],
    pitfalls: t(
      "✗ 又很大又很干净 → ✓ 又大又干净.\nÉvite de mélanger positif et négatif : ✗ 又便宜又不好 sonne maladroit → dis plutôt 虽然便宜，但是不好.",
      "✗ 又很大又很干净 → ✓ 又大又干净.\nAvoid mixing positive and negative: ✗ 又便宜又不好 sounds clumsy → say 虽然便宜，但是不好 instead.",
    ),
  },
  {
    id: "hsk2-g05",
    level: 2,
    title: t("有点儿 ou 一点儿 ?", "有点儿 vs 一点儿"),
    pattern: "有点儿 + Adj   /   Adj + 一点儿",
    category: "副词 / adverbs",
    explanation: t(
      "Les deux se traduisent par « un peu », mais leur **place** et leur **nuance** diffèrent.\n\n**有点儿 + adjectif** (AVANT l'adjectif) : « un peu trop », souvent une **plainte** ou quelque chose de négatif : 房租**有点儿**贵 (le loyer est un peu cher).\n\n**Adjectif + 一点儿** (APRÈS l'adjectif) : sert à **comparer** ou à **demander** : 便宜**一点儿**吧！(un peu moins cher, s'il vous plaît !). 一点儿 peut aussi suivre un verbe devant un nom : 喝一点儿水.",
      "Both translate as \"a little\", but their **position** and **nuance** differ.\n\n**有点儿 + adjective** (BEFORE the adjective): \"a bit too\", usually a **complaint** or something negative: 房租**有点儿**贵 (the rent is a bit expensive).\n\n**Adjective + 一点儿** (AFTER the adjective): used to **compare** or **request**: 便宜**一点儿**吧！(a bit cheaper, please!). 一点儿 can also follow a verb before a noun: 喝一点儿水.",
    ),
    examples: [
      ex("这个房子有点儿小。", "Zhège fángzi yǒudiǎnr xiǎo.", "Ce logement est un peu petit.", "This place is a bit small."),
      ex("能便宜一点儿吗？", "Néng piányi yìdiǎnr ma?", "Vous pouvez faire un peu moins cher ?", "Can you make it a bit cheaper?"),
      ex("我今天有点儿不舒服。", "Wǒ jīntiān yǒudiǎnr bù shūfu.", "Aujourd'hui je ne me sens pas très bien.", "I'm feeling a bit unwell today."),
      ex("请说慢一点儿。", "Qǐng shuō màn yìdiǎnr.", "Parle un peu plus lentement, s'il te plaît.", "Please speak a bit more slowly."),
    ],
    pitfalls: t(
      "✗ 这个房间一点儿小 → ✓ 这个房间有点儿小.\n✗ 请说有点儿慢 → ✓ 请说慢一点儿.\n有点儿 + adjectif positif sonne souvent bizarre : ✗ 我有点儿高兴 (possible mais rare) — préfère 我很高兴.",
      "✗ 这个房间一点儿小 → ✓ 这个房间有点儿小.\n✗ 请说有点儿慢 → ✓ 请说慢一点儿.\n有点儿 + a positive adjective often sounds odd: 我有点儿高兴 is rare — prefer 我很高兴.",
    ),
  },
  {
    id: "hsk2-g06",
    level: 2,
    title: t("得 (děi) : devoir, il faut", "得 (děi): must, have to"),
    pattern: "Sujet + 得 (děi) + Verbe",
    category: "能愿动词 / modal verbs",
    explanation: t(
      "Prononcé **děi**, 得 est un verbe modal très oral qui exprime une **nécessité** : « il faut que », « je dois ».\n\nC'est le même caractère que le 得 (de) du complément de degré, mais le sens et la prononciation sont différents : ici, il se place **devant le verbe**.\n\nAttention à la négation : on ne dit **jamais** 不得 (děi) dans ce sens. Pour « pas besoin de », on dit **不用**.",
      "Pronounced **děi**, 得 is a very colloquial modal verb expressing **necessity**: \"have to\", \"must\".\n\nIt's the same character as the 得 (de) of the degree complement, but with a different meaning and sound: here it goes **before the verb**.\n\nWatch the negative: **never** say 不得 (děi) for this meaning. For \"no need to\", use **不用**.",
    ),
    examples: [
      ex("你发烧了，得去医院。", "Nǐ fāshāo le, děi qù yīyuàn.", "Tu as de la fièvre, il faut aller à l'hôpital.", "You have a fever, you need to go to the hospital."),
      ex("太晚了，我得走了。", "Tài wǎn le, wǒ děi zǒu le.", "Il est trop tard, je dois y aller.", "It's too late, I've got to go."),
      ex("这个药一天得吃三次。", "Zhège yào yì tiān děi chī sān cì.", "Ce médicament, il faut le prendre trois fois par jour.", "This medicine has to be taken three times a day."),
      ex("A：我得带护照吗？B：不用。", "A: Wǒ děi dài hùzhào ma? B: Búyòng.", "A : Je dois apporter mon passeport ? B : Pas besoin.", "A: Do I have to bring my passport? B: No need."),
    ],
    pitfalls: t(
      "✗ 你不得去 (pour « tu n'as pas besoin d'y aller ») → ✓ 你不用去.\nNe le prononce pas « de » : 我**děi**走了.",
      "✗ 你不得去 (for \"you don't have to go\") → ✓ 你不用去.\nDon't pronounce it \"de\" here: 我**děi**走了.",
    ),
  },
  {
    id: "hsk2-g07",
    level: 2,
    title: t("应该 : devoir (conseil, obligation morale)", "应该: should, ought to"),
    pattern: "Sujet + (不) 应该 + Verbe",
    category: "能愿动词 / modal verbs",
    explanation: t(
      "**应该** (yīnggāi) exprime ce qui est **normal, conseillé ou juste** : « tu devrais », « on doit ». C'est plus doux que 得 (děi) et sert beaucoup pour donner des **conseils**.\n\nNégation : **不应该** = « on ne devrait pas ». Question : 应该不应该…？ ou 应该…吗？\n\n应该 peut aussi exprimer une **supposition** forte : 他应该到了 (« il devrait être arrivé »).",
      "**应该** (yīnggāi) expresses what is **normal, advisable or right**: \"you should\", \"one ought to\". It's softer than 得 (děi) and very common for **advice**.\n\nNegative: **不应该** = \"shouldn't\". Question: 应该不应该…？ or 应该…吗？\n\n应该 can also express a confident **assumption**: 他应该到了 (\"he should have arrived by now\").",
    ),
    examples: [
      ex("你应该多喝水，多休息。", "Nǐ yīnggāi duō hē shuǐ, duō xiūxi.", "Tu devrais boire beaucoup d'eau et bien te reposer.", "You should drink plenty of water and rest a lot."),
      ex("感冒了，不应该去游泳。", "Gǎnmào le, bù yīnggāi qù yóuyǒng.", "Quand on est enrhumé, on ne devrait pas aller nager.", "With a cold, you shouldn't go swimming."),
      ex("我们应该几点出发？", "Wǒmen yīnggāi jǐ diǎn chūfā?", "À quelle heure devrions-nous partir ?", "What time should we leave?"),
      ex("现在七点，他应该到家了。", "Xiànzài qī diǎn, tā yīnggāi dào jiā le.", "Il est sept heures, il devrait être rentré.", "It's seven now, he should be home."),
    ],
    pitfalls: t(
      "应该 se place avant le verbe, pas à la fin : ✗ 你休息应该 → ✓ 你应该休息.\nPour « il ne faut pas » très fort (interdiction), 不能 ou 别 est plus naturel : 这儿不能抽烟.",
      "应该 goes before the verb: ✗ 你休息应该 → ✓ 你应该休息.\nFor a firm prohibition, 不能 or 别 is more natural: 这儿不能抽烟.",
    ),
  },
  {
    id: "hsk2-g08",
    level: 2,
    title: t("别 : ne… pas (interdiction)", "别: don't (negative imperative)"),
    pattern: "别 + Verbe (+ 了)",
    category: "副词 / adverbs",
    explanation: t(
      "**别** (bié) sert à dire à quelqu'un de **ne pas faire** quelque chose : c'est l'impératif négatif, comme « ne… pas ! » ou « arrête de… ».\n\n**别 + verbe** : conseil ou interdiction (别担心 = ne t'inquiète pas).\n**别 + verbe + 了** : demander d'**arrêter** une action en cours (别说了 = arrête de parler, ça suffit).\n\n别 équivaut à 不要, un peu plus court et plus oral.",
      "**别** (bié) tells someone **not to do** something: it's the negative imperative, \"don't!\".\n\n**别 + verb**: advice or prohibition (别担心 = don't worry).\n**别 + verb + 了**: asks someone to **stop** an ongoing action (别说了 = stop talking, that's enough).\n\n别 means the same as 不要, but is shorter and more colloquial.",
    ),
    examples: [
      ex("别担心，你的病不严重。", "Bié dānxīn, nǐ de bìng bù yánzhòng.", "Ne t'inquiète pas, ta maladie n'est pas grave.", "Don't worry, your illness isn't serious."),
      ex("别喝冰水。", "Bié hē bīngshuǐ.", "Ne bois pas d'eau glacée.", "Don't drink iced water."),
      ex("别玩手机了，快睡觉吧！", "Bié wán shǒujī le, kuài shuìjiào ba!", "Arrête de jouer sur ton téléphone, va vite dormir !", "Stop playing on your phone, go to sleep!"),
      ex("别忘了吃药。", "Bié wàngle chī yào.", "N'oublie pas de prendre ton médicament.", "Don't forget to take your medicine."),
    ],
    pitfalls: t(
      "别 ne sert pas à nier un fait : ✗ 我别去 → ✓ 我不去.\n别 s'adresse à quelqu'un (tu/vous/nous) : 我们别等了 (n'attendons plus).",
      "别 doesn't negate facts: ✗ 我别去 → ✓ 我不去.\n别 is addressed to someone (you / us): 我们别等了 (let's not wait any longer).",
    ),
  },
  {
    id: "hsk2-g09",
    level: 2,
    title: t("La durée : V + (了) + durée", "Duration: V + (了) + time span"),
    pattern: "Verbe + (了) + durée (+ 的) + Objet   /   V + O + V + durée",
    category: "补语 / complements (时量补语)",
    explanation: t(
      "Pour dire **combien de temps** dure une action, le chinois met la durée **après le verbe** (contrairement à une date, qui va avant) : 我学了两年 = j'ai étudié pendant deux ans.\n\nAvec un objet, deux solutions :\n1) **V + durée + (的) + O** : 我看了两个小时(的)书.\n2) **V + O + V + durée** (on répète le verbe) : 我看书看了两个小时.\n\nSi la durée continue jusqu'à maintenant, on ajoute un **了 final** : 我头疼了三天了 (j'ai mal à la tête depuis trois jours — et ça continue).",
      "To say **how long** an action lasts, Chinese puts the duration **after the verb** (unlike a point in time, which goes before): 我学了两年 = I studied for two years.\n\nWith an object, two options:\n1) **V + duration + (的) + O**: 我看了两个小时(的)书.\n2) **V + O + V + duration** (repeat the verb): 我看书看了两个小时.\n\nIf it's still going on now, add a **final 了**: 我头疼了三天了 (I've had a headache for three days — and still do).",
    ),
    examples: [
      ex("我咳嗽了一个星期了。", "Wǒ késou le yí ge xīngqī le.", "Je tousse depuis une semaine.", "I've been coughing for a week."),
      ex("昨天我睡了十个小时。", "Zuótiān wǒ shuìle shí ge xiǎoshí.", "Hier, j'ai dormi dix heures.", "I slept ten hours yesterday."),
      ex("他学中文学了三年。", "Tā xué Zhōngwén xuéle sān nián.", "Il a étudié le chinois pendant trois ans.", "He studied Chinese for three years."),
      ex("请等一会儿。", "Qǐng děng yíhuìr.", "Attends un instant, s'il te plaît.", "Please wait a moment."),
    ],
    pitfalls: t(
      "✗ 我两个小时看书 → ✓ 我看了两个小时书 (la durée va après le verbe).\n✗ 我学中文了三年 → ✓ 我学了三年中文 / 我学中文学了三年.",
      "✗ 我两个小时看书 → ✓ 我看了两个小时书 (duration comes after the verb).\n✗ 我学中文了三年 → ✓ 我学了三年中文 / 我学中文学了三年.",
    ),
  },
  {
    id: "hsk2-g10",
    level: 2,
    title: t("可能 : peut-être, possible", "可能: maybe, possibly"),
    pattern: "Sujet + 可能 + Verbe  /  可能 + Phrase",
    category: "能愿动词 / modal verbs",
    explanation: t(
      "**可能** (kěnéng) exprime la **possibilité** ou la **probabilité** : « peut-être », « il se peut que ».\n\nIl se place **avant le verbe** (他可能不来) ou en **tête de phrase** (可能他不来). Pour renforcer : **很可能** (très probablement).\n\nC'est aussi un nom/adjectif : 有可能 (c'est possible), 不可能！(impossible !).",
      "**可能** (kěnéng) expresses **possibility** or **probability**: \"maybe\", \"might\".\n\nIt goes **before the verb** (他可能不来) or at the **start of the sentence** (可能他不来). To strengthen it: **很可能** (very likely).\n\nIt's also a noun/adjective: 有可能 (it's possible), 不可能！(impossible!).",
    ),
    examples: [
      ex("你可能感冒了。", "Nǐ kěnéng gǎnmào le.", "Tu as peut-être attrapé un rhume.", "You may have caught a cold."),
      ex("明天可能下雨。", "Míngtiān kěnéng xià yǔ.", "Il va peut-être pleuvoir demain.", "It might rain tomorrow."),
      ex("他今天很可能不来上班。", "Tā jīntiān hěn kěnéng bù lái shàngbān.", "Il est très probable qu'il ne vienne pas travailler aujourd'hui.", "He very likely won't come to work today."),
      ex("这不可能！", "Zhè bù kěnéng!", "C'est impossible !", "That's impossible!"),
    ],
    pitfalls: t(
      "✗ 他来可能 → ✓ 他可能来.\nNe confonds pas 可能 (possibilité) et 可以 (permission) : ✗ 明天可以下雨 → ✓ 明天可能下雨.",
      "✗ 他来可能 → ✓ 他可能来.\nDon't confuse 可能 (possibility) with 可以 (permission): ✗ 明天可以下雨 → ✓ 明天可能下雨.",
    ),
  },
  {
    id: "hsk2-g11",
    level: 2,
    title: t("先…然后/再… : d'abord… ensuite…", "先…然后/再…: first… then…"),
    pattern: "先 + V1，然后 (再) + V2",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "Pour décrire des **étapes dans l'ordre**, on utilise **先** (d'abord) devant la première action, puis **然后** (ensuite) et/ou **再** devant la seconde.\n\n先 et 再 sont des **adverbes** : ils se placent **après le sujet, devant le verbe**. 然后 est un connecteur qui se met en **début de proposition**.\n\nOn peut enchaîner : 先…，然后…，最后… (d'abord… puis… enfin…).",
      "To describe **steps in order**, put **先** (first) before the first action, and **然后** (then) and/or **再** before the second.\n\n先 and 再 are **adverbs**: they go **after the subject, before the verb**. 然后 is a connector at the **start of the clause**.\n\nYou can chain them: 先…，然后…，最后… (first… then… finally…).",
    ),
    examples: [
      ex("我们先去上海，然后去杭州。", "Wǒmen xiān qù Shànghǎi, ránhòu qù Hángzhōu.", "On va d'abord à Shanghai, ensuite à Hangzhou.", "We'll go to Shanghai first, then Hangzhou."),
      ex("你先吃饭，再做作业。", "Nǐ xiān chī fàn, zài zuò zuòyè.", "Mange d'abord, fais tes devoirs après.", "Eat first, then do your homework."),
      ex("我先买票，然后再订酒店。", "Wǒ xiān mǎi piào, ránhòu zài dìng jiǔdiàn.", "J'achète d'abord les billets, puis je réserve l'hôtel.", "I'll buy the tickets first, then book the hotel."),
      ex("先洗手，然后吃饭，最后休息。", "Xiān xǐ shǒu, ránhòu chī fàn, zuìhòu xiūxi.", "D'abord on se lave les mains, puis on mange, et enfin on se repose.", "First wash your hands, then eat, and finally rest."),
    ],
    pitfalls: t(
      "✗ 先我去上海 → ✓ 我先去上海 (先 après le sujet).\n✗ 我然后去杭州 → ✓ 然后我去杭州 / 我再去杭州.",
      "✗ 先我去上海 → ✓ 我先去上海 (先 after the subject).\n✗ 我然后去杭州 → ✓ 然后我去杭州 / 我再去杭州.",
    ),
  },
  {
    id: "hsk2-g12",
    level: 2,
    title: t("从…到… : de… à…", "从…到…: from… to…"),
    pattern: "从 + A + 到 + B (+ Verbe)",
    category: "介词 / prepositions",
    explanation: t(
      "**从 A 到 B** indique le **point de départ** et le **point d'arrivée**, dans l'espace ou dans le temps : 从北京到上海 (de Pékin à Shanghai), 从九点到五点 (de neuf heures à cinq heures).\n\nLe groupe 从…到… se place **avant le verbe** (ou sert de sujet). On l'utilise souvent avec 要 / 需要 + durée : 从这儿到机场要一个小时.\n\n从 seul marque l'origine : 我从法国来 (je viens de France).",
      "**从 A 到 B** marks the **starting point** and **end point**, in space or time: 从北京到上海 (from Beijing to Shanghai), 从九点到五点 (from nine to five).\n\nThe 从…到… phrase goes **before the verb** (or acts as the subject). It often pairs with 要 / 需要 + duration: 从这儿到机场要一个小时.\n\n从 alone marks the origin: 我从法国来 (I come from France).",
    ),
    examples: [
      ex("从北京到上海坐高铁要四个多小时。", "Cóng Běijīng dào Shànghǎi zuò gāotiě yào sì ge duō xiǎoshí.", "De Pékin à Shanghai, il faut un peu plus de quatre heures en TGV.", "Beijing to Shanghai takes a bit over four hours by high-speed train."),
      ex("我从九点到五点上班。", "Wǒ cóng jiǔ diǎn dào wǔ diǎn shàngbān.", "Je travaille de neuf heures à cinq heures.", "I work from nine to five."),
      ex("从我家到公司不太远。", "Cóng wǒ jiā dào gōngsī bú tài yuǎn.", "De chez moi à l'entreprise, ce n'est pas très loin.", "It's not very far from my place to the office."),
      ex("我们从一号到七号放假。", "Wǒmen cóng yī hào dào qī hào fàngjià.", "On est en vacances du 1er au 7.", "We're on holiday from the 1st to the 7th."),
    ],
    pitfalls: t(
      "L'ordre français « je travaille de 9 h à 5 h » ne marche pas : ✗ 我上班从九点到五点 → ✓ 我从九点到五点上班.\nPour la distance, c'est 离, pas 从 : ✗ 我家从公司很近 → ✓ 我家离公司很近.",
      "English word order doesn't work: ✗ 我上班从九点到五点 → ✓ 我从九点到五点上班.\nFor distance use 离, not 从: ✗ 我家从公司很近 → ✓ 我家离公司很近.",
    ),
  },
  {
    id: "hsk2-g13",
    level: 2,
    title: t("或者 ou 还是 ? (« ou »)", "或者 vs 还是 (\"or\")"),
    pattern: "A 或者 B (affirmation)  /  A 还是 B？ (question)",
    category: "连词 / conjunctions",
    explanation: t(
      "Le français n'a qu'un « ou », le chinois en a deux :\n\n**还是** s'emploie dans une **question à choix** : 你喝茶**还是**咖啡？(Tu bois du thé ou du café ?). La phrase n'a pas besoin de 吗.\n\n**或者** s'emploie dans une **affirmation** (ou une proposition) : 我们坐火车**或者**坐飞机都可以 (on peut prendre le train ou l'avion, peu importe).\n\nAstuce : si tu attends que l'autre **choisisse**, c'est 还是.",
      "English has one \"or\", Chinese has two:\n\n**还是** is used in a **choice question**: 你喝茶**还是**咖啡？(Tea or coffee?). No 吗 needed.\n\n**或者** is used in **statements** (or suggestions): 我们坐火车**或者**坐飞机都可以 (we can take the train or the plane, either is fine).\n\nTip: if you expect the listener to **pick one**, it's 还是.",
    ),
    examples: [
      ex("我们坐火车去还是坐飞机去？", "Wǒmen zuò huǒchē qù háishi zuò fēijī qù?", "On y va en train ou en avion ?", "Are we going by train or by plane?"),
      ex("周六或者周日出发都可以。", "Zhōuliù huòzhě zhōurì chūfā dōu kěyǐ.", "On peut partir samedi ou dimanche, les deux vont.", "Leaving on Saturday or Sunday are both fine."),
      ex("你想去海边还是去山上？", "Nǐ xiǎng qù hǎibiān háishi qù shān shang?", "Tu veux aller à la mer ou à la montagne ?", "Do you want to go to the seaside or the mountains?"),
      ex("你可以给我打电话或者发微信。", "Nǐ kěyǐ gěi wǒ dǎ diànhuà huòzhě fā Wēixìn.", "Tu peux m'appeler ou m'envoyer un WeChat.", "You can call me or send me a WeChat message."),
    ],
    pitfalls: t(
      "✗ 你喝茶或者咖啡？ → ✓ 你喝茶还是咖啡？\n✗ 你喝茶还是咖啡吗？ → pas de 吗 avec 还是.",
      "✗ 你喝茶或者咖啡？ → ✓ 你喝茶还是咖啡？\n✗ 你喝茶还是咖啡吗？ → no 吗 with 还是.",
    ),
  },
  {
    id: "hsk2-g14",
    level: 2,
    title: t("Moyen de transport : 坐/骑/开 + véhicule + 去", "Means of transport: 坐/骑/开 + vehicle + 去"),
    pattern: "Sujet + 坐 / 骑 / 开 + véhicule + 去 / 来 + lieu",
    category: "句型 / sentence patterns (连动句)",
    explanation: t(
      "Le chinois enchaîne deux verbes dans l'**ordre logique** : on « prend le train » PUIS on « va » : 坐火车**去**上海. Le moyen se place donc **avant** le déplacement (« en train » vient avant « aller »).\n\nLe verbe dépend du véhicule : **坐** pour ce où l'on est assis en passager (坐飞机, 坐地铁, 坐出租车, 坐公共汽车), **骑** pour ce que l'on enfourche (骑自行车, 骑马), **开** pour ce que l'on conduit (开车). À pied : **走路**去.\n\nPour demander : 你**怎么**去？(Tu y vas comment ?)",
      "Chinese chains two verbs in **logical order**: you \"take the train\" THEN you \"go\": 坐火车**去**上海. So the means comes **before** the movement.\n\nThe verb depends on the vehicle: **坐** for anything you sit in as a passenger (坐飞机, 坐地铁, 坐出租车, 坐公共汽车), **骑** for what you straddle (骑自行车, 骑马), **开** for what you drive (开车). On foot: **走路**去.\n\nTo ask: 你**怎么**去？(How are you getting there?)",
    ),
    examples: [
      ex("我们坐高铁去西安。", "Wǒmen zuò gāotiě qù Xī'ān.", "On va à Xi'an en TGV.", "We're going to Xi'an by high-speed train."),
      ex("他每天骑自行车上班。", "Tā měi tiān qí zìxíngchē shàngbān.", "Il va au travail à vélo tous les jours.", "He cycles to work every day."),
      ex("你怎么去机场？——打车去。", "Nǐ zěnme qù jīchǎng? — Dǎchē qù.", "Tu vas comment à l'aéroport ? — En taxi.", "How are you getting to the airport? — By taxi."),
      ex("我们走路去吧，不远。", "Wǒmen zǒulù qù ba, bù yuǎn.", "Allons-y à pied, ce n'est pas loin.", "Let's walk there, it's not far."),
    ],
    pitfalls: t(
      "✗ 我去上海坐火车 (sonne comme « je vais à Shanghai pour prendre le train ») → ✓ 我坐火车去上海.\n✗ 坐自行车 → ✓ 骑自行车.",
      "✗ 我去上海坐火车 (sounds like \"I go to Shanghai to take a train\") → ✓ 我坐火车去上海.\n✗ 坐自行车 → ✓ 骑自行车.",
    ),
  },
  {
    id: "hsk2-g15",
    level: 2,
    title: t("给 : pour, à (bénéficiaire)", "给: for, to (recipient)"),
    pattern: "Sujet + 给 + Personne + Verbe (+ Objet)",
    category: "介词 / prepositions",
    explanation: t(
      "Comme préposition, **给** introduit la personne qui **reçoit** ou **bénéficie** de l'action : 给我打电话 (m'appeler, litt. « à-moi téléphoner »).\n\nLe groupe **给 + personne** se place **avant le verbe**, pas après comme en français (« appelle-moi »).\n\nVerbes fréquents : 给…打电话, 给…发微信, 给…写信, 给…介绍, 给…拿, 给…做饭.",
      "As a preposition, **给** introduces the person who **receives** or **benefits** from the action: 给我打电话 (call me, lit. \"to-me make a call\").\n\nThe **给 + person** phrase goes **before the verb**, not after as in English (\"call me\").\n\nCommon verbs: 给…打电话, 给…发微信, 给…写信, 给…介绍, 给…拿, 给…做饭.",
    ),
    examples: [
      ex("服务员，请给我们拿一下菜单。", "Fúwùyuán, qǐng gěi wǒmen ná yíxià càidān.", "S'il vous plaît, vous pouvez nous apporter la carte ?", "Excuse me, could you bring us the menu?"),
      ex("我给你介绍一下，这是小王。", "Wǒ gěi nǐ jièshào yíxià, zhè shì Xiǎo Wáng.", "Je te présente : voici Xiao Wang.", "Let me introduce you: this is Xiao Wang."),
      ex("到了给我发个微信。", "Dàole gěi wǒ fā ge Wēixìn.", "Envoie-moi un WeChat quand tu es arrivé.", "Send me a WeChat when you arrive."),
      ex("妈妈每天给我们做饭。", "Māma měi tiān gěi wǒmen zuò fàn.", "Maman nous fait à manger tous les jours.", "Mom cooks for us every day."),
    ],
    pitfalls: t(
      "✗ 我打电话给你 est possible à l'oral, mais la forme de base est ✓ 我给你打电话.\n✗ 请拿菜单给我们 → ✓ 请给我们拿菜单.",
      "✗ 我打电话给你 is heard in speech, but the standard form is ✓ 我给你打电话.\n✗ 请拿菜单给我们 → ✓ 请给我们拿菜单.",
    ),
  },
  {
    id: "hsk2-g16",
    level: 2,
    title: t("Le double complément : 送/给/教/问 + qqn + qqch", "Double objects: 送/给/教/问 + someone + something"),
    pattern: "Sujet + Verbe + Personne + Chose",
    category: "句型 / sentence patterns (双宾语句)",
    explanation: t(
      "Certains verbes acceptent **deux objets** directement, sans préposition : d'abord la **personne**, puis la **chose**. 他送我一本书 = il m'offre un livre.\n\nVerbes courants : **给** (donner), **送** (offrir), **教** (enseigner), **问** (demander), **告诉** (dire à), **还** (rendre), **借** (prêter/emprunter), **找** (rendre la monnaie).\n\nC'est comme en anglais « give me a book », jamais « give a book me ».",
      "Some verbs take **two objects** directly, with no preposition: first the **person**, then the **thing**. 他送我一本书 = he gives me a book.\n\nCommon verbs: **给** (give), **送** (give as a gift), **教** (teach), **问** (ask), **告诉** (tell), **还** (return), **借** (lend/borrow), **找** (give change).\n\nJust like English \"give me a book\" — never \"give a book me\".",
    ),
    examples: [
      ex("请给我一杯水。", "Qǐng gěi wǒ yì bēi shuǐ.", "Un verre d'eau, s'il vous plaît.", "A glass of water, please."),
      ex("老师教我们中文。", "Lǎoshī jiāo wǒmen Zhōngwén.", "Le professeur nous enseigne le chinois.", "The teacher teaches us Chinese."),
      ex("我想问你一个问题。", "Wǒ xiǎng wèn nǐ yí ge wèntí.", "J'aimerais te poser une question.", "I'd like to ask you a question."),
      ex("找您二十块。", "Zhǎo nín èrshí kuài.", "Je vous rends vingt yuans.", "Here's twenty yuan change."),
      ex("告诉我你的电话号码。", "Gàosu wǒ nǐ de diànhuà hàomǎ.", "Donne-moi ton numéro de téléphone.", "Tell me your phone number."),
    ],
    pitfalls: t(
      "✗ 他送一本书我 → ✓ 他送我一本书 (personne d'abord).\n说 n'accepte pas deux objets : ✗ 说我一件事 → ✓ 告诉我一件事 / 跟我说一件事.",
      "✗ 他送一本书我 → ✓ 他送我一本书 (person first).\n说 can't take two objects: ✗ 说我一件事 → ✓ 告诉我一件事 / 跟我说一件事.",
    ),
  },
  {
    id: "hsk2-g17",
    level: 2,
    title: t("Exclamations : 太…了, 真…, 非常, 特别", "Exclamations: 太…了, 真…, 非常, 特别"),
    pattern: "太 + Adj + 了！  /  真 + Adj！  /  非常 / 特别 + Adj",
    category: "句类 / sentence types (感叹句)",
    explanation: t(
      "Pour réagir avec émotion, on renforce l'adjectif :\n\n**太 + Adj + 了** : « trop » (critique) ou « tellement ! » (enthousiasme) selon le contexte : 太贵了！(c'est trop cher !), 太好吃了！(c'est délicieux !).\n**真 + Adj** : « vraiment », exclamation spontanée : 这个菜真辣！\n**非常 / 特别 + Adj** : « très, extrêmement », plus descriptif et neutre.\n\nAu négatif, **不太** adoucit : 不太好 = pas terrible.",
      "To react emotionally, intensify the adjective:\n\n**太 + Adj + 了**: \"too\" (criticism) or \"so…!\" (enthusiasm) depending on context: 太贵了！(way too expensive!), 太好吃了！(so delicious!).\n**真 + Adj**: \"really\", a spontaneous exclamation: 这个菜真辣！\n**非常 / 特别 + Adj**: \"very, extremely\", more descriptive and neutral.\n\nIn the negative, **不太** softens: 不太好 = not great.",
    ),
    examples: [
      ex("这个鱼太好吃了！", "Zhège yú tài hǎochī le!", "Ce poisson est délicieux !", "This fish is so good!"),
      ex("今天的菜真辣！", "Jīntiān de cài zhēn là!", "Les plats d'aujourd'hui sont vraiment épicés !", "Today's food is really spicy!"),
      ex("这家饭馆特别有名。", "Zhè jiā fànguǎn tèbié yǒumíng.", "Ce restaurant est particulièrement célèbre.", "This restaurant is especially famous."),
      ex("我不太饿，吃一点儿就行。", "Wǒ bú tài è, chī yìdiǎnr jiù xíng.", "Je n'ai pas très faim, un petit peu suffira.", "I'm not very hungry, just a little is fine."),
    ],
    pitfalls: t(
      "N'oublie pas le 了 : ✗ 太贵！ → ✓ 太贵了！\n真 ne se met pas devant un nom avec 的 pour décrire : ✗ 他是真好的人 → ✓ 他人真好 / 他是一个非常好的人.",
      "Don't forget 了: ✗ 太贵！ → ✓ 太贵了！\n真 doesn't sit well in front of 的 + noun: ✗ 他是真好的人 → ✓ 他人真好 / 他是一个非常好的人.",
    ),
  },
  {
    id: "hsk2-g18",
    level: 2,
    title: t("还 : encore, aussi, en plus", "还: still, also, else"),
    pattern: "Sujet + 还 + Verbe / Adj",
    category: "副词 / adverbs",
    explanation: t(
      "**还** (hái) est un adverbe à plusieurs sens, toujours placé **devant le verbe** :\n\n1. **En plus, aussi** : 我要一碗米饭，**还**要一个汤 (je veux un bol de riz, et aussi une soupe). 还要别的吗？(Autre chose ?)\n2. **Encore, toujours** (continuité) : 他**还**在吃饭 (il est encore en train de manger). 还没 = pas encore.\n3. **Assez, plutôt** (avec 还 + adj positif) : 味道**还**可以 (le goût est pas mal / correct).",
      "**还** (hái) is a multi-purpose adverb, always **before the verb**:\n\n1. **Also, in addition**: 我要一碗米饭，**还**要一个汤 (a bowl of rice, and a soup too). 还要别的吗？(Anything else?)\n2. **Still** (continuation): 他**还**在吃饭 (he's still eating). 还没 = not yet.\n3. **Fairly, OK** (还 + positive adj): 味道**还**可以 (the taste is OK / not bad).",
    ),
    examples: [
      ex("还要别的吗？", "Hái yào bié de ma?", "Vous désirez autre chose ?", "Anything else?"),
      ex("我们要一个鱼，还要两碗米饭。", "Wǒmen yào yí ge yú, hái yào liǎng wǎn mǐfàn.", "On prend un poisson, et aussi deux bols de riz.", "We'll have a fish, and two bowls of rice as well."),
      ex("十点了，他还在工作。", "Shí diǎn le, tā hái zài gōngzuò.", "Il est dix heures, il travaille encore.", "It's ten o'clock and he's still working."),
      ex("这家的菜还可以，不太贵。", "Zhè jiā de cài hái kěyǐ, bú tài guì.", "La cuisine ici est correcte, pas trop chère.", "The food here is OK, not too expensive."),
    ],
    pitfalls: t(
      "✗ 我要米饭，还我要汤 → ✓ 我要米饭，还要汤 / 我还要汤 (还 devant le verbe, après le sujet).\nNe le confonds pas avec 还 huán (rendre) : 还书 = rendre un livre.",
      "✗ 我要米饭，还我要汤 → ✓ 我要米饭，还要汤 / 我还要汤 (还 before the verb, after the subject).\nDon't confuse it with 还 huán (to return): 还书 = return a book.",
    ),
  },
  {
    id: "hsk2-g19",
    level: 2,
    title: t("一共 et 只 : au total, seulement", "一共 and 只: in total, only"),
    pattern: "一共 + (Verbe) + quantité   /   只 + Verbe (+ quantité)",
    category: "副词 / adverbs (范围)",
    explanation: t(
      "**一共** (yígòng) = « en tout, au total ». Il précède le verbe ou directement le montant : 一共多少钱？(Ça fait combien en tout ?) 我们一共五个人.\n\n**只** (zhǐ) = « seulement, ne… que ». Il se place **devant le verbe**, jamais devant le sujet ou directement devant un nom : 我只要一碗面 (je ne prends qu'un bol de nouilles).\n\nPour « seulement » + nombre, on dit souvent **只有** : 只有两个人.",
      "**一共** (yígòng) = \"altogether, in total\". It comes before the verb or directly before the amount: 一共多少钱？(How much altogether?) 我们一共五个人.\n\n**只** (zhǐ) = \"only\". It goes **before the verb**, never before the subject or directly before a noun: 我只要一碗面 (I'll just have a bowl of noodles).\n\nFor \"only\" + number, **只有** is common: 只有两个人.",
    ),
    examples: [
      ex("一共一百二十八块。", "Yígòng yìbǎi èrshíbā kuài.", "Ça fait 128 yuans en tout.", "That's 128 yuan in total."),
      ex("我们一共四个人。", "Wǒmen yígòng sì ge rén.", "Nous sommes quatre en tout.", "There are four of us altogether."),
      ex("我只要一杯茶，谢谢。", "Wǒ zhǐ yào yì bēi chá, xièxie.", "Je prendrai juste un thé, merci.", "Just a cup of tea for me, thanks."),
      ex("这家店只有周末开门。", "Zhè jiā diàn zhǐ yǒu zhōumò kāimén.", "Cette boutique n'ouvre que le week-end.", "This shop only opens at weekends."),
    ],
    pitfalls: t(
      "✗ 只我要茶 → ✓ 我只要茶 (只 après le sujet).\n✗ 一共是多少钱 est possible, mais ✗ 多少钱一共 → ✓ 一共多少钱.",
      "✗ 只我要茶 → ✓ 我只要茶 (只 after the subject).\n✗ 多少钱一共 → ✓ 一共多少钱.",
    ),
  },
  {
    id: "hsk2-g20",
    level: 2,
    title: t("Le complément de degré : V + 得 + Adj", "Degree complement: V + 得 + Adj"),
    pattern: "Sujet + Verbe + 得 + (很) + Adj",
    category: "补语 / complements (程度补语)",
    explanation: t(
      "Pour **évaluer comment** une action est faite (bien, vite, mal…), le chinois ajoute **得 (de) + adjectif** après le verbe : 他跑**得很快** = il court vite.\n\nC'est l'équivalent de nos adverbes de manière (« vite », « bien »), mais ils se placent **après** le verbe avec 得.\n\nNégation : on nie l'adjectif, pas le verbe : 他跑得**不**快. Question : 他跑得快**不快**？ / 他跑得**怎么样**？",
      "To **evaluate how** an action is done (well, fast, badly…), Chinese adds **得 (de) + adjective** after the verb: 他跑**得很快** = he runs fast.\n\nIt's the counterpart of English manner adverbs (\"fast\", \"well\"), placed **after** the verb with 得.\n\nNegative: negate the adjective, not the verb: 他跑得**不**快. Question: 他跑得快**不快**？ / 他跑得**怎么样**？",
    ),
    examples: [
      ex("他跑得非常快。", "Tā pǎo de fēicháng kuài.", "Il court très vite.", "He runs very fast."),
      ex("你说得很好！", "Nǐ shuō de hěn hǎo!", "Tu parles très bien !", "You speak very well!"),
      ex("我昨天睡得不太好。", "Wǒ zuótiān shuì de bú tài hǎo.", "Hier, je n'ai pas très bien dormi.", "I didn't sleep very well yesterday."),
      ex("她游得怎么样？", "Tā yóu de zěnmeyàng?", "Elle nage comment ?", "How well does she swim?"),
    ],
    pitfalls: t(
      "✗ 他很快跑 (pour évaluer) → ✓ 他跑得很快.\n✗ 他不跑得快 → ✓ 他跑得不快.\nNe confonds pas 得 (complément), 的 (possession) et 地 (manière avant le verbe).",
      "✗ 他很快跑 (to evaluate) → ✓ 他跑得很快.\n✗ 他不跑得快 → ✓ 他跑得不快.\nDon't mix up 得 (complement), 的 (possessive) and 地 (manner, before the verb).",
    ),
  },
  {
    id: "hsk2-g21",
    level: 2,
    title: t("Degré avec objet : (V) + O + V + 得 + Adj", "Degree with an object: (V) + O + V + 得 + Adj"),
    pattern: "Sujet + (V) + O + V + 得 + Adj   /   Sujet + O + V + 得 + Adj",
    category: "补语 / complements (程度补语)",
    explanation: t(
      "Problème : 得 doit suivre **directement** le verbe, donc on ne peut pas dire ✗ 他打篮球得很好. Solution : **répéter le verbe**.\n\n**V + O + V + 得 + Adj** : 他**打**篮球**打**得很好 (il joue bien au basket).\n\nOn peut aussi **omettre le premier verbe** et mettre l'objet en tête : 他篮球打得很好. C'est très fréquent à l'oral.",
      "Problem: 得 must follow the verb **directly**, so ✗ 他打篮球得很好 is wrong. Solution: **repeat the verb**.\n\n**V + O + V + 得 + Adj**: 他**打**篮球**打**得很好 (he plays basketball well).\n\nYou can also **drop the first verb** and put the object first: 他篮球打得很好. Very common in speech.",
    ),
    examples: [
      ex("他打篮球打得很好。", "Tā dǎ lánqiú dǎ de hěn hǎo.", "Il joue très bien au basket.", "He plays basketball very well."),
      ex("你中文说得真流利！", "Nǐ Zhōngwén shuō de zhēn liúlì!", "Tu parles vraiment couramment chinois !", "Your Chinese is really fluent!"),
      ex("她唱歌唱得特别好听。", "Tā chàng gē chàng de tèbié hǎotīng.", "Elle chante vraiment bien.", "She sings beautifully."),
      ex("我游泳游得不快。", "Wǒ yóuyǒng yóu de bú kuài.", "Je ne nage pas vite.", "I don't swim fast."),
    ],
    pitfalls: t(
      "✗ 他说中文得很好 → ✓ 他说中文说得很好 / 他中文说得很好.\nPour les verbes séparables (游泳, 唱歌, 跑步), on répète le premier caractère : 游泳**游**得, 跑步**跑**得.",
      "✗ 他说中文得很好 → ✓ 他说中文说得很好 / 他中文说得很好.\nFor separable verbs (游泳, 唱歌, 跑步), repeat the first syllable: 游泳**游**得, 跑步**跑**得.",
    ),
  },
  {
    id: "hsk2-g22",
    level: 2,
    title: t("会, 能, 可以 : savoir, pouvoir", "会, 能, 可以: can"),
    pattern: "Sujet + 会 / 能 / 可以 + Verbe",
    category: "能愿动词 / modal verbs",
    explanation: t(
      "Trois verbes pour « pouvoir », avec des nuances :\n\n**会** = savoir faire grâce à un **apprentissage** : 我会游泳 (je sais nager). Aussi : probabilité future (明天会下雨).\n**能** = **capacité** physique ou **conditions** qui le permettent : 我今天不能游泳，我感冒了 (je ne peux pas nager aujourd'hui).\n**可以** = **permission** : 这儿可以游泳吗？(On a le droit de nager ici ?)\n\nPour refuser une permission, on dit en général **不能** (pas 不可以, un peu sec) : 这儿不能抽烟.",
      "Three verbs for \"can\", with nuances:\n\n**会** = know how to, thanks to **learning**: 我会游泳 (I can swim). Also future likelihood (明天会下雨).\n**能** = physical **ability** or **circumstances** allowing it: 我今天不能游泳，我感冒了 (I can't swim today, I have a cold).\n**可以** = **permission**: 这儿可以游泳吗？(Is swimming allowed here?)\n\nTo deny permission, **不能** is usual (不可以 sounds stern): 这儿不能抽烟.",
    ),
    examples: [
      ex("你会打乒乓球吗？", "Nǐ huì dǎ pīngpāngqiú ma?", "Tu sais jouer au ping-pong ?", "Can you play table tennis?"),
      ex("我脚疼，今天不能跑步。", "Wǒ jiǎo téng, jīntiān bù néng pǎobù.", "J'ai mal au pied, je ne peux pas courir aujourd'hui.", "My foot hurts, I can't run today."),
      ex("这里可以踢足球吗？", "Zhèlǐ kěyǐ tī zúqiú ma?", "On peut jouer au foot ici ?", "Can we play football here?"),
      ex("他一分钟能跑四百米。", "Tā yì fēnzhōng néng pǎo sìbǎi mǐ.", "Il peut courir 400 mètres en une minute.", "He can run 400 metres in a minute."),
    ],
    pitfalls: t(
      "✗ 我可以说中文 (pour « je parle chinois ») → ✓ 我会说中文.\n✗ 我会游泳一千米 (performance mesurée) → ✓ 我能游一千米.",
      "✗ 我可以说中文 (for \"I speak Chinese\") → ✓ 我会说中文.\n✗ 我会游一千米 (measured performance) → ✓ 我能游一千米.",
    ),
  },
  {
    id: "hsk2-g23",
    level: 2,
    title: t("每…都… : chaque… (sans exception)", "每…都…: every…"),
    pattern: "每 + (数) + 量 + Nom + 都 + Verbe",
    category: "代词 / pronouns (每)",
    explanation: t(
      "**每** (měi) = « chaque ». Il est suivi d'un classificateur (每个人, 每天, 每年 — 天/年/周 n'ont pas besoin de classificateur).\n\nOn ajoute presque toujours **都** devant le verbe pour souligner « sans exception » : **每**天**都**跑步 = courir tous les jours.\n\nC'est l'un des réflexes les plus typiques du chinois : quand il y a 每, pense à 都.",
      "**每** (měi) = \"every, each\". It's followed by a measure word (每个人, 每天, 每年 — 天/年/周 need no measure word).\n\nYou almost always add **都** before the verb to stress \"without exception\": **每**天**都**跑步 = run every day.\n\nOne of the most typical Chinese reflexes: when you see 每, think 都.",
    ),
    examples: [
      ex("我每天早上都跑步。", "Wǒ měi tiān zǎoshang dōu pǎobù.", "Je cours tous les matins.", "I run every morning."),
      ex("他每个周末都去游泳。", "Tā měi ge zhōumò dōu qù yóuyǒng.", "Il va nager tous les week-ends.", "He goes swimming every weekend."),
      ex("每个人都很高兴。", "Měi ge rén dōu hěn gāoxìng.", "Tout le monde est très content.", "Everyone is very happy."),
      ex("每次比赛他都来看。", "Měi cì bǐsài tā dōu lái kàn.", "Il vient voir chaque match.", "He comes to watch every match."),
    ],
    pitfalls: t(
      "✗ 我每天跑步 n'est pas faux, mais ✓ 我每天都跑步 est plus naturel.\n✗ 都每天 → ✓ 每天都 (都 juste avant le verbe).\n✗ 每人书 → ✓ 每个人.",
      "✗ 我每天跑步 isn't wrong, but ✓ 我每天都跑步 is more natural.\n✗ 都每天 → ✓ 每天都 (都 right before the verb).\n✗ 每人书 → ✓ 每个人.",
    ),
  },
  {
    id: "hsk2-g24",
    level: 2,
    title: t("La fréquence : 常常, 经常, 有时候, 总是, 一直", "Frequency: 常常, 经常, 有时候, 总是, 一直"),
    pattern: "Sujet + 常常 / 经常 / 有时候 / 总是 + Verbe",
    category: "副词 / adverbs (频率)",
    explanation: t(
      "Les adverbes de fréquence se placent **après le sujet et avant le verbe** :\n\n**总是** (toujours, sans faute — souvent avec une nuance d'agacement), **经常 / 常常** (souvent), **有时候** (parfois — peut aussi se mettre en tête de phrase), **不常** (pas souvent).\n\n**一直** signifie « sans interruption, depuis toujours » : 我一直想学太极拳 (ça fait longtemps que je veux apprendre le tai-chi).\n\nNégation de 常常 : **不常**, pas ✗ 不常常.",
      "Frequency adverbs go **after the subject and before the verb**:\n\n**总是** (always — often with a hint of annoyance), **经常 / 常常** (often), **有时候** (sometimes — can also start the sentence), **不常** (not often).\n\n**一直** means \"continuously, all along\": 我一直想学太极拳 (I've long wanted to learn tai chi).\n\nNegative of 常常: **不常**, not ✗ 不常常.",
    ),
    examples: [
      ex("我经常去健身房。", "Wǒ jīngcháng qù jiànshēnfáng.", "Je vais souvent à la salle de sport.", "I often go to the gym."),
      ex("有时候我们周末去爬山。", "Yǒu shíhou wǒmen zhōumò qù pá shān.", "Parfois, on va faire de la randonnée le week-end.", "Sometimes we go hiking at the weekend."),
      ex("他总是迟到。", "Tā zǒngshì chídào.", "Il est toujours en retard.", "He's always late."),
      ex("我不常运动。", "Wǒ bù cháng yùndòng.", "Je ne fais pas souvent de sport.", "I don't exercise often."),
      ex("雨一直下，比赛不能开始。", "Yǔ yìzhí xià, bǐsài bù néng kāishǐ.", "Il n'arrête pas de pleuvoir, le match ne peut pas commencer.", "It keeps raining, the match can't start."),
    ],
    pitfalls: t(
      "✗ 我去常常健身房 → ✓ 我常常去健身房.\n✗ 我不常常运动 → ✓ 我不常运动.",
      "✗ 我去常常健身房 → ✓ 我常常去健身房.\n✗ 我不常常运动 → ✓ 我不常运动.",
    ),
  },
  {
    id: "hsk2-g25",
    level: 2,
    title: t("快要…了 / 就要…了 : bientôt, sur le point de", "快要…了 / 就要…了: about to, soon"),
    pattern: "(快)要 / 快 / 就要 + Verbe / Nom + 了",
    category: "动作的态 / aspect (将来)",
    explanation: t(
      "Pour dire qu'un événement va **arriver très bientôt**, on encadre le verbe (ou le nom) par **快要…了**, **快…了** ou **就要…了**. Le **了 final** est obligatoire.\n\n**快…了** peut porter directement sur un nom de temps : 快春节了 (c'est bientôt le Nouvel An).\n**就要…了** peut s'utiliser avec une **date précise** : 明天就要放假了. À l'inverse, ✗ 明天快要放假了 est incorrect : 快要 ne supporte pas d'expression de temps précise.",
      "To say something is **about to happen**, wrap the verb (or noun) in **快要…了**, **快…了** or **就要…了**. The **final 了** is required.\n\n**快…了** can apply directly to a time noun: 快春节了 (Spring Festival is almost here).\n**就要…了** can be used with a **specific time**: 明天就要放假了. By contrast, ✗ 明天快要放假了 is wrong: 快要 doesn't combine with a precise time expression.",
    ),
    examples: [
      ex("快要过年了！", "Kuài yào guò nián le!", "On va bientôt fêter le Nouvel An !", "New Year is coming soon!"),
      ex("快十二点了，我们走吧。", "Kuài shí'èr diǎn le, wǒmen zǒu ba.", "Il est bientôt midi, allons-y.", "It's almost twelve, let's go."),
      ex("下个星期就要放假了。", "Xià ge xīngqī jiù yào fàngjià le.", "On est en vacances dès la semaine prochaine.", "The holidays start next week."),
      ex("火车快要开了，快上车！", "Huǒchē kuài yào kāi le, kuài shàng chē!", "Le train va partir, monte vite !", "The train's about to leave, get on quickly!"),
    ],
    pitfalls: t(
      "✗ 快要过年 (sans 了) → ✓ 快要过年了.\n✗ 下个星期快要放假了 → ✓ 下个星期就要放假了.",
      "✗ 快要过年 (without 了) → ✓ 快要过年了.\n✗ 下个星期快要放假了 → ✓ 下个星期就要放假了.",
    ),
  },
  {
    id: "hsk2-g26",
    level: 2,
    title: t("…的时候 : quand, au moment où", "…的时候: when, while"),
    pattern: "Proposition / Nom + 的时候，Phrase principale",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "Pour dire « quand… », le chinois met la subordonnée **en premier**, suivie de **的时候** : 我小**的时候** = quand j'étais petit.\n\nL'ordre est l'inverse du français (« quand j'étais petit » peut aller en fin de phrase en français, pas en chinois) : la proposition de temps vient **avant** la principale.\n\nOn peut ajouter 在 devant pour un style plus écrit : 在吃饭的时候.",
      "To say \"when…\", Chinese puts the time clause **first**, followed by **的时候**: 我小**的时候** = when I was little.\n\nUnlike English, where \"when…\" can come last, in Chinese the time clause comes **before** the main clause.\n\n在 can be added in front for a more formal style: 在吃饭的时候.",
    ),
    examples: [
      ex("过春节的时候，我们一家人一起吃饭。", "Guò Chūnjié de shíhou, wǒmen yì jiā rén yìqǐ chī fàn.", "Pour la fête du Printemps, toute la famille mange ensemble.", "At Spring Festival, the whole family eats together."),
      ex("我小的时候很喜欢放鞭炮。", "Wǒ xiǎo de shíhou hěn xǐhuan fàng biānpào.", "Quand j'étais petit, j'adorais faire éclater des pétards.", "When I was little I loved setting off firecrackers."),
      ex("吃饭的时候别看手机。", "Chī fàn de shíhou bié kàn shǒujī.", "Ne regarde pas ton téléphone en mangeant.", "Don't look at your phone while eating."),
      ex("你有空的时候给我打电话。", "Nǐ yǒu kòng de shíhou gěi wǒ dǎ diànhuà.", "Appelle-moi quand tu auras un moment.", "Call me when you're free."),
    ],
    pitfalls: t(
      "✗ 我很喜欢放鞭炮的时候我小 → ✓ 我小的时候很喜欢放鞭炮.\n✗ 当我小 (sans 的时候) → ✓ 我小的时候.",
      "✗ 我很喜欢放鞭炮的时候我小 → ✓ 我小的时候很喜欢放鞭炮.\n✗ 当我小 (without 的时候) → ✓ 我小的时候.",
    ),
  },
  {
    id: "hsk2-g27",
    level: 2,
    title: t("跟…一起 : avec, ensemble", "跟…一起: with, together"),
    pattern: "Sujet + 跟 / 和 + Personne + 一起 + Verbe",
    category: "介词 / prepositions",
    explanation: t(
      "« Faire quelque chose **avec** quelqu'un » : **跟 + personne + 一起 + verbe**. Le groupe se place **avant le verbe**, pas à la fin comme en français.\n\n**和** peut remplacer 跟. 一起 peut rester seul : 我们一起去吧 (allons-y ensemble).\n\n跟 sert aussi avec des verbes de communication : **跟**他说 (lui dire), **跟**我来 (viens avec moi / suis-moi).",
      "\"Do something **with** someone\": **跟 + person + 一起 + verb**. The phrase goes **before the verb**, not at the end as in English.\n\n**和** can replace 跟. 一起 can stand alone: 我们一起去吧 (let's go together).\n\n跟 also works with verbs of speaking: **跟**他说 (tell him), **跟**我来 (come with me / follow me).",
    ),
    examples: [
      ex("春节我跟家人一起过。", "Chūnjié wǒ gēn jiārén yìqǐ guò.", "Je passe la fête du Printemps avec ma famille.", "I spend Spring Festival with my family."),
      ex("你想跟我们一起去看灯吗？", "Nǐ xiǎng gēn wǒmen yìqǐ qù kàn dēng ma?", "Tu veux venir voir les lanternes avec nous ?", "Do you want to come and see the lanterns with us?"),
      ex("我跟朋友一起包饺子。", "Wǒ gēn péngyou yìqǐ bāo jiǎozi.", "Je fais des raviolis avec des amis.", "I make dumplings with friends."),
      ex("你跟他说了吗？", "Nǐ gēn tā shuō le ma?", "Tu lui en as parlé ?", "Have you told him?"),
    ],
    pitfalls: t(
      "✗ 我吃饭跟朋友 → ✓ 我跟朋友一起吃饭.\n✗ 我一起跟朋友吃饭 → ✓ 我跟朋友一起吃饭 (一起 après la personne).",
      "✗ 我吃饭跟朋友 → ✓ 我跟朋友一起吃饭.\n✗ 我一起跟朋友吃饭 → ✓ 我跟朋友一起吃饭 (一起 after the person).",
    ),
  },
  {
    id: "hsk2-g28",
    level: 2,
    title: t("请 / 让 / 叫 : inviter, faire faire", "请 / 让 / 叫: invite, let, make someone do"),
    pattern: "A + 请 / 让 / 叫 + B + Verbe",
    category: "句型 / sentence patterns (兼语句)",
    explanation: t(
      "Dans cette structure, la personne B est à la fois **l'objet** du premier verbe et le **sujet** du second : 妈妈**让**我回家 = maman me fait rentrer / me dit de rentrer.\n\n**请** = inviter, prier poliment (我请你吃饭 = je t'invite à manger). **让** = laisser, faire faire, demander de (neutre). **叫** = dire de, faire faire (plus oral et direct).\n\nNégation : devant le premier verbe : 妈妈**不让**我吃糖 (maman ne me laisse pas manger de bonbons).",
      "Here person B is both the **object** of the first verb and the **subject** of the second: 妈妈**让**我回家 = mom has me come home / tells me to come home.\n\n**请** = invite, ask politely (我请你吃饭 = I'll treat you to a meal). **让** = let, make, ask to (neutral). **叫** = tell to, make (more colloquial and direct).\n\nNegative: before the first verb: 妈妈**不让**我吃糖 (mom doesn't let me eat sweets).",
    ),
    examples: [
      ex("中秋节我请你吃月饼。", "Zhōngqiū Jié wǒ qǐng nǐ chī yuèbing.", "Pour la fête de la Mi-Automne, je t'offre des gâteaux de lune.", "I'll treat you to mooncakes for Mid-Autumn Festival."),
      ex("老板让我们早点儿回家。", "Lǎobǎn ràng wǒmen zǎo diǎnr huí jiā.", "Le patron nous laisse rentrer un peu plus tôt.", "The boss is letting us go home a bit early."),
      ex("妈妈叫我去买东西。", "Māma jiào wǒ qù mǎi dōngxi.", "Maman m'envoie faire des courses.", "Mom told me to go shopping."),
      ex("医生不让他喝酒。", "Yīshēng bú ràng tā hē jiǔ.", "Le médecin lui interdit de boire de l'alcool.", "The doctor won't let him drink."),
    ],
    pitfalls: t(
      "✗ 妈妈让回家我 → ✓ 妈妈让我回家.\n✗ 妈妈让我不吃糖 (sens différent : « me dit de ne pas ») — pour « ne me laisse pas », ✓ 妈妈不让我吃糖.",
      "✗ 妈妈让回家我 → ✓ 妈妈让我回家.\n妈妈让我不吃糖 means \"tells me not to\" — for \"doesn't let me\", ✓ 妈妈不让我吃糖.",
    ),
  },
  {
    id: "hsk2-g29",
    level: 2,
    title: t("Particules finales 吧, 啊, 呢", "Sentence-final particles 吧, 啊, 呢"),
    pattern: "Phrase + 吧 / 啊 / 呢",
    category: "助词 / particles (语气助词)",
    explanation: t(
      "Ces petites particules donnent le **ton** de la phrase :\n\n**吧** : proposition (我们走**吧** = allons-y), ou supposition qu'on veut confirmer (你是法国人**吧**？ = tu es français, non ?).\n**啊** : exclamation, chaleur, insistance (好**啊**！= carrément ! ; 多漂亮**啊**！= que c'est beau !). Il devient 呀 après une voyelle.\n**呢** : question de retour (我很好，你**呢**？= et toi ?), où est… ? (我的手机**呢**？), ou action en cours (他在吃饭**呢**).",
      "These little particles set the sentence's **tone**:\n\n**吧**: suggestion (我们走**吧** = let's go), or an assumption you want confirmed (你是法国人**吧**？ = you're French, right?).\n**啊**: exclamation, warmth, emphasis (好**啊**！= sure!; 多漂亮**啊**！= how beautiful!). It often becomes 呀 after a vowel.\n**呢**: bounce-back question (我很好，你**呢**？= and you?), where's…? (我的手机**呢**？), or ongoing action (他在吃饭**呢**).",
    ),
    examples: [
      ex("我们一起去看烟花吧！", "Wǒmen yìqǐ qù kàn yānhuā ba!", "Allons voir le feu d'artifice ensemble !", "Let's go and watch the fireworks together!"),
      ex("A：明天来我家吃饭吧？B：好啊！", "A: Míngtiān lái wǒ jiā chī fàn ba? B: Hǎo a!", "A : Viens dîner chez moi demain ? B : Avec plaisir !", "A: Come over for dinner tomorrow? B: Sure!"),
      ex("我春节回老家，你呢？", "Wǒ Chūnjié huí lǎojiā, nǐ ne?", "Je rentre dans ma ville natale pour le Nouvel An, et toi ?", "I'm going back to my hometown for New Year, how about you?"),
      ex("今天的月亮多圆啊！", "Jīntiān de yuèliang duō yuán a!", "Que la lune est ronde ce soir !", "How round the moon is tonight!"),
    ],
    pitfalls: t(
      "吧 + question fermée : pas de 吗 en plus : ✗ 你是法国人吧吗？ → ✓ 你是法国人吧？\n呢 ne remplace pas 吗 : ✗ 你好呢？ → ✓ 你好吗？",
      "吧 questions take no extra 吗: ✗ 你是法国人吧吗？ → ✓ 你是法国人吧？\n呢 doesn't replace 吗: ✗ 你好呢？ → ✓ 你好吗？",
    ),
  },
  {
    id: "hsk2-g30",
    level: 2,
    title: t("La comparaison avec 比", "Comparisons with 比"),
    pattern: "A + 比 + B + Adj",
    category: "句型 / sentence patterns (比字句)",
    explanation: t(
      "Pour dire « A est plus … que B » : **A 比 B + adjectif**. 今天比昨天冷 = aujourd'hui il fait plus froid qu'hier.\n\n**Pas de 很 ni de 非常** devant l'adjectif ! Le 比 suffit à exprimer « plus ». Pour renforcer, on utilise **更** ou **还** (encore plus) : 北京比上海**更**冷.\n\nNégation de base : **A 没有 B + adj** (A n'est pas aussi… que B). 不比 existe mais a une nuance de réfutation.",
      "To say \"A is more … than B\": **A 比 B + adjective**. 今天比昨天冷 = today is colder than yesterday.\n\n**No 很 or 非常** before the adjective! 比 already means \"more\". To intensify, use **更** or **还** (even more): 北京比上海**更**冷.\n\nThe basic negative is **A 没有 B + adj** (A isn't as… as B). 不比 exists but sounds like a rebuttal.",
    ),
    examples: [
      ex("今天比昨天冷。", "Jīntiān bǐ zuótiān lěng.", "Aujourd'hui il fait plus froid qu'hier.", "Today is colder than yesterday."),
      ex("北京的冬天比巴黎冷。", "Běijīng de dōngtiān bǐ Bālí lěng.", "L'hiver à Pékin est plus froid qu'à Paris.", "Winter in Beijing is colder than in Paris."),
      ex("南方比北方更热。", "Nánfāng bǐ běifāng gèng rè.", "Le sud est encore plus chaud que le nord.", "The south is even hotter than the north."),
      ex("我比我哥哥高。", "Wǒ bǐ wǒ gēge gāo.", "Je suis plus grand que mon grand frère.", "I'm taller than my older brother."),
    ],
    pitfalls: t(
      "✗ 今天比昨天很冷 → ✓ 今天比昨天冷 / 今天比昨天冷多了.\n✗ 今天冷比昨天 → ✓ 今天比昨天冷 (比 B avant l'adjectif).",
      "✗ 今天比昨天很冷 → ✓ 今天比昨天冷 / 今天比昨天冷多了.\n✗ 今天冷比昨天 → ✓ 今天比昨天冷 (比 B before the adjective).",
    ),
  },
  {
    id: "hsk2-g31",
    level: 2,
    title: t("比 + écart : un peu, beaucoup, précis", "比 + difference: a bit, much, exact amount"),
    pattern: "A + 比 + B + Adj + 一点儿 / 得多 / 多了 / quantité",
    category: "句型 / sentence patterns (比字句)",
    explanation: t(
      "Pour préciser **l'écart** dans une comparaison, on ajoute un élément **après** l'adjectif :\n\n**一点儿** (un peu) : 今天比昨天暖和**一点儿**.\n**得多 / 多了** (beaucoup) : 这儿比那儿冷**得多** / 冷**多了**.\n**Quantité précise** : 今天比昨天高**五度** (5 degrés de plus). 他比我大**两岁** (il a deux ans de plus que moi).\n\nTout se place **après** l'adjectif, jamais avant.",
      "To specify **how big the difference** is, add something **after** the adjective:\n\n**一点儿** (a bit): 今天比昨天暖和**一点儿**.\n**得多 / 多了** (much): 这儿比那儿冷**得多** / 冷**多了**.\n**Exact amount**: 今天比昨天高**五度** (5 degrees higher). 他比我大**两岁** (he's two years older than me).\n\nAll of these come **after** the adjective, never before.",
    ),
    examples: [
      ex("今天比昨天暖和一点儿。", "Jīntiān bǐ zuótiān nuǎnhuo yìdiǎnr.", "Aujourd'hui il fait un peu plus doux qu'hier.", "Today is a bit warmer than yesterday."),
      ex("哈尔滨比上海冷多了。", "Hā'ěrbīn bǐ Shànghǎi lěng duō le.", "Harbin est beaucoup plus froid que Shanghai.", "Harbin is much colder than Shanghai."),
      ex("今天比昨天低八度。", "Jīntiān bǐ zuótiān dī bā dù.", "Aujourd'hui il fait huit degrés de moins qu'hier.", "Today is eight degrees lower than yesterday."),
      ex("他比我大两岁。", "Tā bǐ wǒ dà liǎng suì.", "Il a deux ans de plus que moi.", "He's two years older than me."),
    ],
    pitfalls: t(
      "✗ 今天比昨天一点儿冷 → ✓ 今天比昨天冷一点儿.\n✗ 他比我两岁大 → ✓ 他比我大两岁.\n✗ 今天比昨天有点儿冷 → ✓ 今天比昨天冷一点儿 (有点儿 ne va pas avec 比).",
      "✗ 今天比昨天一点儿冷 → ✓ 今天比昨天冷一点儿.\n✗ 他比我两岁大 → ✓ 他比我大两岁.\n✗ 今天比昨天有点儿冷 → ✓ 今天比昨天冷一点儿 (有点儿 doesn't go with 比).",
    ),
  },
  {
    id: "hsk2-g32",
    level: 2,
    title: t("越来越 : de plus en plus", "越来越: more and more"),
    pattern: "Sujet + 越来越 + Adj / Verbe psychologique",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "**越来越 + adjectif** décrit une **évolution progressive** : 天气越来越冷 (il fait de plus en plus froid).\n\nComme avec 比, **pas de 很** devant l'adjectif. On le combine souvent avec un **了 final** pour souligner le changement : 越来越冷了.\n\nÇa marche aussi avec des verbes de sentiment : 我越来越喜欢这个城市.",
      "**越来越 + adjective** describes a **gradual change**: 天气越来越冷 (it's getting colder and colder).\n\nAs with 比, **no 很** before the adjective. A **final 了** often underlines the change: 越来越冷了.\n\nIt also works with verbs of feeling: 我越来越喜欢这个城市.",
    ),
    examples: [
      ex("天气越来越冷了。", "Tiānqì yuè lái yuè lěng le.", "Il fait de plus en plus froid.", "The weather is getting colder and colder."),
      ex("白天越来越短。", "Báitiān yuè lái yuè duǎn.", "Les journées raccourcissent.", "The days are getting shorter and shorter."),
      ex("你的中文越来越好了！", "Nǐ de Zhōngwén yuè lái yuè hǎo le!", "Ton chinois s'améliore de plus en plus !", "Your Chinese keeps getting better!"),
      ex("我越来越喜欢秋天了。", "Wǒ yuè lái yuè xǐhuan qiūtiān le.", "J'aime de plus en plus l'automne.", "I like autumn more and more."),
    ],
    pitfalls: t(
      "✗ 越来越很冷 → ✓ 越来越冷.\n✗ 越来越多冷 → ✓ 越来越冷.",
      "✗ 越来越很冷 → ✓ 越来越冷.\n✗ 越来越多冷 → ✓ 越来越冷.",
    ),
  },
  {
    id: "hsk2-g33",
    level: 2,
    title: t("了 de changement : « maintenant, c'est… »", "Change-of-state 了: \"now it's…\""),
    pattern: "Phrase + 了 (fin de phrase)",
    category: "助词 / particles (语气助词 了)",
    explanation: t(
      "En **fin de phrase**, 了 signale un **changement de situation** : quelque chose est devenu vrai alors que ce n'était pas le cas avant.\n\n天冷**了** = il s'est mis à faire froid (avant, il faisait bon). 下雨**了** = il pleut (maintenant). 我不去**了** = finalement, je n'y vais plus (changement de décision).\n\nCe 了 n'a rien à voir avec le passé : il peut s'appliquer au présent ou au futur (快冬天了).",
      "At the **end of a sentence**, 了 signals a **change of situation**: something has become true that wasn't before.\n\n天冷**了** = it's turned cold (it was mild before). 下雨**了** = it's started raining. 我不去**了** = I'm not going after all (change of plan).\n\nThis 了 has nothing to do with past tense: it works for present or future too (快冬天了).",
    ),
    examples: [
      ex("下雪了！", "Xià xuě le!", "Il neige !", "It's snowing!"),
      ex("秋天到了，树叶黄了。", "Qiūtiān dào le, shùyè huáng le.", "L'automne est arrivé, les feuilles ont jauni.", "Autumn is here, the leaves have turned yellow."),
      ex("天气不好，我不去爬山了。", "Tiānqì bù hǎo, wǒ bú qù pá shān le.", "Il fait mauvais, finalement je ne vais pas faire la randonnée.", "The weather's bad, so I'm not going hiking any more."),
      ex("我二十五岁了。", "Wǒ èrshíwǔ suì le.", "J'ai (maintenant) vingt-cinq ans.", "I'm twenty-five now."),
    ],
    pitfalls: t(
      "Sans 了, c'est une simple description : 天很冷 (il fait froid) ≠ 天冷了 (il s'est mis à faire froid).\nAvec 了 de changement, on retire souvent 很 : ✗ 天很冷了 est possible mais ✓ 天冷了 est plus naturel.",
      "Without 了 it's a plain description: 天很冷 (it's cold) ≠ 天冷了 (it's turned cold).\nWith change 了, 很 usually disappears: ✓ 天冷了 is more natural than 天很冷了.",
    ),
  },
  {
    id: "hsk2-g34",
    level: 2,
    title: t("Approximations : 左右, 多, 几", "Approximate numbers: 左右, 多, 几"),
    pattern: "Nombre + 左右  /  Nombre + 多 + 量  /  几 + 量",
    category: "数词 / numerals (概数)",
    explanation: t(
      "Trois façons de donner un chiffre **approximatif** :\n\n**左右** (environ) se met **après** la quantité : 二十度**左右** (une vingtaine de degrés).\n**多** (et quelques, plus de) : après un nombre rond **avant** le classificateur (二十**多**个人 = plus de vingt personnes), ou **après** le classificateur si le nombre est inférieur à 10 (两个**多**小时 = plus de deux heures).\n**几** (quelques) : 十几个 (une dizaine et quelques), 几天 (quelques jours).",
      "Three ways to give an **approximate** number:\n\n**左右** (about) goes **after** the amount: 二十度**左右** (around twenty degrees).\n**多** (more than, -odd): after a round number and **before** the measure word (二十**多**个人 = twenty-odd people), or **after** the measure word when the number is under 10 (两个**多**小时 = over two hours).\n**几** (a few, several): 十几个 (a dozen or so), 几天 (a few days).",
    ),
    examples: [
      ex("明天最高气温三十度左右。", "Míngtiān zuì gāo qìwēn sānshí dù zuǒyòu.", "Demain, la température maximale sera d'environ trente degrés.", "Tomorrow's high will be around thirty degrees."),
      ex("这儿冬天有二十多天下雪。", "Zhèr dōngtiān yǒu èrshí duō tiān xià xuě.", "Ici, en hiver, il neige plus de vingt jours.", "Here it snows on more than twenty days in winter."),
      ex("雨下了两个多小时。", "Yǔ xiàle liǎng ge duō xiǎoshí.", "Il a plu pendant plus de deux heures.", "It rained for over two hours."),
      ex("过几天就暖和了。", "Guò jǐ tiān jiù nuǎnhuo le.", "Dans quelques jours, il fera plus doux.", "It'll be warmer in a few days."),
    ],
    pitfalls: t(
      "✗ 左右二十度 → ✓ 二十度左右.\n✗ 两多个小时 → ✓ 两个多小时 (nombre < 10 : 多 après le classificateur).",
      "✗ 左右二十度 → ✓ 二十度左右.\n✗ 两多个小时 → ✓ 两个多小时 (number < 10: 多 after the measure word).",
    ),
  },
  {
    id: "hsk2-g35",
    level: 2,
    title: t("L'action en cours : 正在 / 在 …(呢)", "Actions in progress: 正在 / 在 …(呢)"),
    pattern: "Sujet + 正在 / 在 + Verbe (+ 呢)",
    category: "动作的态 / aspect (进行)",
    explanation: t(
      "Pour dire qu'une action est **en train de se dérouler**, on met **在** ou **正在** devant le verbe, et souvent **呢** à la fin : 我**正在**开会**呢** (je suis en pleine réunion).\n\n**正在** insiste sur le moment précis (« juste maintenant, pile au moment où… »). **在** est plus neutre. **呢** seul à la fin peut aussi suffire à l'oral : 他打电话呢.\n\nNégation : **没(在)** + verbe : 我没在工作 (je ne suis pas en train de travailler).",
      "To say an action is **in progress**, put **在** or **正在** before the verb, often with **呢** at the end: 我**正在**开会**呢** (I'm in a meeting right now).\n\n**正在** stresses the exact moment (\"right now, just when…\"). **在** is more neutral. **呢** alone at the end also works in speech: 他打电话呢.\n\nNegative: **没(在)** + verb: 我没在工作 (I'm not working).",
    ),
    examples: [
      ex("王经理正在开会呢。", "Wáng jīnglǐ zhèngzài kāihuì ne.", "M. Wang, le directeur, est en réunion en ce moment.", "Manager Wang is in a meeting right now."),
      ex("你在做什么？——我在写报告。", "Nǐ zài zuò shénme? — Wǒ zài xiě bàogào.", "Qu'est-ce que tu fais ? — J'écris un rapport.", "What are you doing? — I'm writing a report."),
      ex("你来的时候，我正在打电话。", "Nǐ lái de shíhou, wǒ zhèngzài dǎ diànhuà.", "Quand tu es arrivé, j'étais au téléphone.", "When you came, I was on the phone."),
      ex("他没在工作，他在休息。", "Tā méi zài gōngzuò, tā zài xiūxi.", "Il ne travaille pas, il fait une pause.", "He's not working, he's taking a break."),
    ],
    pitfalls: t(
      "✗ 我正在开会了 → ✓ 我正在开会呢 (了 et 正在 ne vont pas ensemble).\n✗ 我不在工作 → ✓ 我没在工作 (négation avec 没).",
      "✗ 我正在开会了 → ✓ 我正在开会呢 (了 doesn't go with 正在).\n✗ 我不在工作 → ✓ 我没在工作 (negate with 没).",
    ),
  },
  {
    id: "hsk2-g36",
    level: 2,
    title: t("已经…了 : déjà", "已经…了: already"),
    pattern: "Sujet + 已经 + Verbe / Adj + 了",
    category: "副词 / adverbs (时间)",
    explanation: t(
      "**已经** (yǐjīng) = « déjà ». Il se place **avant le verbe** et s'accompagne presque toujours d'un **了** (après le verbe ou en fin de phrase) : 我**已经**做完**了**.\n\nIl marche aussi avec un nombre ou un moment : 已经十点了 (il est déjà dix heures), 我已经工作三年了 (ça fait déjà trois ans que je travaille).\n\nLa réponse négative habituelle est **还没(有)…(呢)** (pas encore).",
      "**已经** (yǐjīng) = \"already\". It goes **before the verb** and almost always comes with **了** (after the verb or at the end): 我**已经**做完**了**.\n\nIt also works with numbers or times: 已经十点了 (it's already ten), 我已经工作三年了 (I've already been working for three years).\n\nThe usual negative answer is **还没(有)…(呢)** (not yet).",
    ),
    examples: [
      ex("报告我已经写好了。", "Bàogào wǒ yǐjīng xiěhǎo le.", "Le rapport, je l'ai déjà terminé.", "I've already finished the report."),
      ex("已经八点了，快起床！", "Yǐjīng bā diǎn le, kuài qǐchuáng!", "Il est déjà huit heures, lève-toi vite !", "It's already eight, get up!"),
      ex("我在这家公司已经工作五年了。", "Wǒ zài zhè jiā gōngsī yǐjīng gōngzuò wǔ nián le.", "Ça fait déjà cinq ans que je travaille dans cette entreprise.", "I've already worked at this company for five years."),
      ex("他已经下班了。", "Tā yǐjīng xiàbān le.", "Il a déjà quitté le bureau.", "He's already left work."),
    ],
    pitfalls: t(
      "✗ 我已经吃饭 (sans 了) → ✓ 我已经吃饭了.\n✗ 已经我吃了 → ✓ 我已经吃了.",
      "✗ 我已经吃饭 (without 了) → ✓ 我已经吃饭了.\n✗ 已经我吃了 → ✓ 我已经吃了.",
    ),
  },
  {
    id: "hsk2-g37",
    level: 2,
    title: t("Complément de résultat : 完 et 好", "Result complements: 完 and 好"),
    pattern: "Verbe + 完 / 好 (+ 了)  /  没 + Verbe + 完 / 好",
    category: "补语 / complements (结果补语)",
    explanation: t(
      "Le chinois ajoute souvent au verbe un second élément qui indique le **résultat** de l'action.\n\n**V + 完** = finir complètement de faire : 吃完 (finir de manger), 做完 (terminer), 用完 (épuiser).\n**V + 好** = faire jusqu'à ce que ce soit **prêt / bien fait** : 准备好 (être prêt), 写好 (avoir rédigé), 说好 (se mettre d'accord).\n\nNégation avec **没** (pas 不) : 我还**没**做**完**. Question : 做完了吗？/ 做完了没有？",
      "Chinese often adds a second element to the verb showing the **result** of the action.\n\n**V + 完** = finish doing completely: 吃完 (finish eating), 做完 (finish), 用完 (use up).\n**V + 好** = do until it's **ready / done properly**: 准备好 (be ready), 写好 (have written), 说好 (agree on).\n\nNegate with **没** (not 不): 我还**没**做**完**. Question: 做完了吗？/ 做完了没有？",
    ),
    examples: [
      ex("你的工作做完了吗？", "Nǐ de gōngzuò zuòwán le ma?", "Tu as fini ton travail ?", "Have you finished your work?"),
      ex("会议的材料我准备好了。", "Huìyì de cáiliào wǒ zhǔnbèi hǎo le.", "J'ai préparé les documents pour la réunion.", "I've got the meeting documents ready."),
      ex("打印纸用完了。", "Dǎyìnzhǐ yòngwán le.", "Il n'y a plus de papier pour l'imprimante.", "The printer paper has run out."),
      ex("我还没吃完，等我一下。", "Wǒ hái méi chīwán, děng wǒ yíxià.", "Je n'ai pas encore fini de manger, attends-moi.", "I haven't finished eating yet, wait for me."),
    ],
    pitfalls: t(
      "✗ 我不做完 → ✓ 我没做完.\n✗ 我做了完 → ✓ 我做完了 (了 après le complément).",
      "✗ 我不做完 → ✓ 我没做完.\n✗ 我做了完 → ✓ 我做完了 (了 after the complement).",
    ),
  },
];
