import type { GrammarPoint } from "../../types";
import { ex, t } from "./helpers";

export const grammarB: GrammarPoint[] = [
  {
    id: "hsk2-g38",
    level: 2,
    title: t("还没…(呢) : pas encore", "还没…(呢): not yet"),
    pattern: "Sujet + 还没(有) + Verbe (+ 呢)",
    category: "副词 / adverbs (否定)",
    explanation: t(
      "Pour dire qu'une chose **n'a pas encore eu lieu** (mais devrait arriver), on utilise **还没(有) + verbe**, souvent avec **呢** à la fin pour adoucir.\n\nC'est la réponse naturelle à une question avec 已经…了 ou …了吗 : 你吃饭了吗？——**还没呢**.\n\nAttention : **pas de 了** dans une phrase avec 还没, puisque l'action n'est pas réalisée.",
      "To say something **hasn't happened yet** (but is expected to), use **还没(有) + verb**, often with **呢** at the end to soften it.\n\nIt's the natural answer to a question with 已经…了 or …了吗: 你吃饭了吗？——**还没呢**.\n\nCareful: **no 了** in a 还没 sentence, since the action hasn't happened.",
    ),
    examples: [
      ex("A：你下班了吗？B：还没呢。", "A: Nǐ xiàbān le ma? B: Hái méi ne.", "A : Tu as fini ta journée ? B : Pas encore.", "A: Are you off work yet? B: Not yet."),
      ex("客户还没回邮件。", "Kèhù hái méi huí yóujiàn.", "Le client n'a pas encore répondu à l'e-mail.", "The client hasn't replied to the email yet."),
      ex("会议还没开始呢。", "Huìyì hái méi kāishǐ ne.", "La réunion n'a pas encore commencé.", "The meeting hasn't started yet."),
      ex("我还没想好。", "Wǒ hái méi xiǎnghǎo.", "Je n'ai pas encore décidé.", "I haven't made up my mind yet."),
    ],
    pitfalls: t(
      "✗ 我还没吃饭了 → ✓ 我还没吃饭(呢).\n✗ 我还不吃饭 (sens : « je ne mange toujours pas », refus) ≠ 我还没吃饭 (pas encore mangé).",
      "✗ 我还没吃饭了 → ✓ 我还没吃饭(呢).\n我还不吃饭 (\"I'm still not eating\", refusal) ≠ 我还没吃饭 (haven't eaten yet).",
    ),
  },
  {
    id: "hsk2-g39",
    level: 2,
    title: t("刚 et 刚才 : venir de, tout à l'heure", "刚 and 刚才: just, a moment ago"),
    pattern: "Sujet + 刚 + Verbe   /   刚才 + Sujet + Verbe",
    category: "副词 / adverbs (时间)",
    explanation: t(
      "Les deux parlent d'un passé **très proche**, mais ce ne sont pas les mêmes mots :\n\n**刚** (adverbe) = « venir de » : se place **devant le verbe**, jamais en tête. Pas de 了 en général : 我**刚**到公司. Il peut porter sur une période plus large (我刚来北京一个月).\n**刚才** (nom de temps) = « tout à l'heure, il y a un instant » : peut aller **en tête de phrase** ou après le sujet, et accepte 了 et la négation : **刚才**你去哪儿**了**？",
      "Both refer to the **very recent** past, but they're different words:\n\n**刚** (adverb) = \"just\": goes **before the verb**, never at the start. Usually no 了: 我**刚**到公司. It can cover a longer span (我刚来北京一个月 = I only came to Beijing a month ago).\n**刚才** (time noun) = \"a moment ago\": can **start the sentence** or follow the subject, and takes 了 and negation: **刚才**你去哪儿**了**？",
    ),
    examples: [
      ex("我刚到办公室。", "Wǒ gāng dào bàngōngshì.", "Je viens d'arriver au bureau.", "I've just arrived at the office."),
      ex("刚才经理找你了。", "Gāngcái jīnglǐ zhǎo nǐ le.", "Le directeur te cherchait tout à l'heure.", "The manager was looking for you a moment ago."),
      ex("他刚来公司两个月。", "Tā gāng lái gōngsī liǎng ge yuè.", "Ça ne fait que deux mois qu'il est dans l'entreprise.", "He only joined the company two months ago."),
      ex("刚才的会你为什么没来？", "Gāngcái de huì nǐ wèi shénme méi lái?", "Pourquoi tu n'es pas venu à la réunion de tout à l'heure ?", "Why didn't you come to the meeting just now?"),
    ],
    pitfalls: t(
      "✗ 刚我到了 → ✓ 我刚到 / 刚才我到了.\n✗ 我刚没去 → ✓ 我刚才没去 (刚 ne se nie pas).",
      "✗ 刚我到了 → ✓ 我刚到 / 刚才我到了.\n✗ 我刚没去 → ✓ 我刚才没去 (刚 can't be negated).",
    ),
  },
  {
    id: "hsk2-g40",
    level: 2,
    title: t("Compléments de résultat : 懂, 见, 到, 会, 错, 对", "Result complements: 懂, 见, 到, 会, 错, 对"),
    pattern: "Verbe + 懂 / 见 / 到 / 会 / 错 / 对 (+ 了)",
    category: "补语 / complements (结果补语)",
    explanation: t(
      "Le verbe dit l'**action**, le complément dit si elle a **abouti** :\n\n**听懂 / 看懂** = comprendre en écoutant / en lisant (听 = écouter ; 听懂 = comprendre).\n**看见 / 听见** = voir, entendre (percevoir).\n**找到 / 买到 / 收到** = réussir à trouver / acheter / recevoir.\n**学会** = avoir appris, maîtriser.\n**写错 / 说错 / 做对** = mal écrire, se tromper en parlant, faire juste.\n\nNégation : **没** + V + complément : 我**没**听懂. En français, « écouter » ≠ « entendre » : c'est exactement 听 ≠ 听见.",
      "The verb names the **action**, the complement says whether it **succeeded**:\n\n**听懂 / 看懂** = understand by listening / reading (听 = listen; 听懂 = understand).\n**看见 / 听见** = see, hear (perceive).\n**找到 / 买到 / 收到** = manage to find / buy / receive.\n**学会** = have learned, master.\n**写错 / 说错 / 做对** = write wrongly, misspeak, get right.\n\nNegative: **没** + V + complement: 我**没**听懂. Just like English \"look\" ≠ \"see\": 看 ≠ 看见.",
    ),
    examples: [
      ex("老师说的话你听懂了吗？", "Lǎoshī shuō de huà nǐ tīngdǒng le ma?", "Tu as compris ce que le prof a dit ?", "Did you understand what the teacher said?"),
      ex("这个字你写错了。", "Zhège zì nǐ xiěcuò le.", "Tu as mal écrit ce caractère.", "You wrote this character wrong."),
      ex("我找到那本书了！", "Wǒ zhǎodào nà běn shū le!", "J'ai trouvé ce livre !", "I found that book!"),
      ex("我已经学会用这个软件了。", "Wǒ yǐjīng xuéhuì yòng zhège ruǎnjiàn le.", "J'ai déjà appris à utiliser ce logiciel.", "I've already learned how to use this software."),
      ex("你看见我的笔了吗？", "Nǐ kànjiàn wǒ de bǐ le ma?", "Tu as vu mon stylo ?", "Have you seen my pen?"),
    ],
    pitfalls: t(
      "✗ 我不听懂 → ✓ 我没听懂 (ou 我听不懂 = je ne peux pas comprendre, forme potentielle).\n✗ 我找了我的笔 (= j'ai cherché) ≠ ✓ 我找到了我的笔 (= j'ai trouvé).",
      "✗ 我不听懂 → ✓ 我没听懂 (or 我听不懂 = I can't understand, potential form).\n我找了我的笔 (= I looked for) ≠ ✓ 我找到了我的笔 (= I found).",
    ),
  },
  {
    id: "hsk2-g41",
    level: 2,
    title: t("Combien de fois : 次, 遍, 下", "How many times: 次, 遍, 下"),
    pattern: "Verbe + (了/过) + nombre + 次 / 遍 / 下 (+ Objet)",
    category: "补语 / complements (动量补语)",
    explanation: t(
      "Pour compter les **occurrences** d'une action, on place un classificateur verbal **après le verbe** :\n\n**次** = une fois, une occurrence (去过两**次**, 一个星期三**次**).\n**遍** = une fois **du début à la fin** (lire, écouter, répéter en entier) : 请再说一**遍** (répète encore une fois, en entier).\n**下** = un petit coup, une action brève : 敲了三**下**门 (frapper trois coups). **V + 一下** adoucit une demande (看一下).\n\nAvec un nom commun comme objet : V + 次数 + O (看了两遍书). Avec un pronom : V + O + 次数 (找过他两次).",
      "To count how many **times** an action happens, put a verbal measure word **after the verb**:\n\n**次** = a time, an occurrence (去过两**次**, 一个星期三**次**).\n**遍** = once **from start to finish** (reading, listening, repeating in full): 请再说一**遍** (please say it all again).\n**下** = a quick stroke, a brief action: 敲了三**下**门 (knock three times). **V + 一下** softens a request (看一下).\n\nWith a noun object: V + count + O (看了两遍书). With a pronoun: V + O + count (找过他两次).",
    ),
    examples: [
      ex("请再说一遍，好吗？", "Qǐng zài shuō yí biàn, hǎo ma?", "Tu peux répéter encore une fois, s'il te plaît ?", "Could you say that again, please?"),
      ex("这个课文我听了三遍。", "Zhège kèwén wǒ tīngle sān biàn.", "J'ai écouté ce texte trois fois.", "I listened to this text three times."),
      ex("我一个星期上两次中文课。", "Wǒ yí ge xīngqī shàng liǎng cì Zhōngwén kè.", "J'ai cours de chinois deux fois par semaine.", "I have Chinese class twice a week."),
      ex("我去过他家一次。", "Wǒ qùguo tā jiā yí cì.", "Je suis allé chez lui une fois.", "I've been to his place once."),
      ex("你看一下这个句子。", "Nǐ kàn yíxià zhège jùzi.", "Jette un œil à cette phrase.", "Take a look at this sentence."),
    ],
    pitfalls: t(
      "✗ 我三次去了北京 → ✓ 我去了三次北京 / 我去过北京三次.\n✗ 我找过两次他 → ✓ 我找过他两次 (pronom avant le nombre).",
      "✗ 我三次去了北京 → ✓ 我去了三次北京 / 我去过北京三次.\n✗ 我找过两次他 → ✓ 我找过他两次 (pronoun before the count).",
    ),
  },
  {
    id: "hsk2-g42",
    level: 2,
    title: t("虽然…但是… : bien que… (mais)", "虽然…但是…: although… (but)"),
    pattern: "虽然 + A，但是 / 可是 + B",
    category: "复句 / complex sentences (转折)",
    explanation: t(
      "Pour exprimer une **concession**, le chinois utilise un duo : **虽然** dans la première proposition, **但是** (ou 可是) dans la seconde.\n\nEn français on dit « **Bien que** ce soit difficile, j'aime ça » — sans « mais ». En chinois, on garde **les deux** mots : 虽然很难，**但是**我很喜欢. Ça paraît redondant, mais c'est la norme.\n\n虽然 peut se placer avant ou après le sujet de la 1re proposition.",
      "To express a **concession**, Chinese uses a pair: **虽然** in the first clause, **但是** (or 可是) in the second.\n\nIn English, \"**Although** it's hard, I like it\" has no \"but\". In Chinese you keep **both**: 虽然很难，**但是**我很喜欢. It looks redundant, but it's the norm.\n\n虽然 can go before or after the subject of the first clause.",
    ),
    examples: [
      ex("虽然汉字很难，但是很有意思。", "Suīrán Hànzì hěn nán, dànshì hěn yǒu yìsi.", "Les caractères sont difficiles, mais passionnants.", "Although characters are hard, they're really interesting."),
      ex("他虽然很忙，但是每天都学习一个小时。", "Tā suīrán hěn máng, dànshì měi tiān dōu xuéxí yí ge xiǎoshí.", "Bien qu'il soit très occupé, il étudie une heure chaque jour.", "Although he's very busy, he studies an hour every day."),
      ex("虽然考得不太好，可是我不难过。", "Suīrán kǎo de bú tài hǎo, kěshì wǒ bù nánguò.", "Même si mon examen ne s'est pas très bien passé, je ne suis pas triste.", "Although the exam didn't go that well, I'm not upset."),
      ex("这本书虽然很旧，但是很有用。", "Zhè běn shū suīrán hěn jiù, dànshì hěn yǒuyòng.", "Ce livre est vieux, mais très utile.", "This book is old but very useful."),
    ],
    pitfalls: t(
      "Ne mets pas de sujet entre 但是 et une virgule : ✗ 但是，我很喜欢 est lourd → ✓ 但是我很喜欢.\n✗ 虽然…所以… : 虽然 va avec 但是/可是, pas avec 所以.",
      "No comma right after 但是 is needed: ✓ 但是我很喜欢.\n✗ 虽然…所以…: 虽然 pairs with 但是/可是, not 所以.",
    ),
  },
  {
    id: "hsk2-g43",
    level: 2,
    title: t("因为…所以… : parce que… donc…", "因为…所以…: because… so…"),
    pattern: "因为 + cause，所以 + conséquence",
    category: "复句 / complex sentences (因果)",
    explanation: t(
      "**因为** introduit la **cause**, **所以** la **conséquence**. Comme pour 虽然…但是, le chinois aime utiliser **les deux** ensemble, alors que le français choisit l'un ou l'autre.\n\nOrdre habituel : **cause d'abord**, conséquence ensuite. On peut omettre l'un des deux mots à l'oral : 因为下雨，我没去 / 下雨了，所以我没去.\n\nPour répondre à 为什么, on commence par **因为**.",
      "**因为** introduces the **cause**, **所以** the **result**. As with 虽然…但是, Chinese likes to use **both**, while English picks one.\n\nUsual order: **cause first**, result second. In speech one of them can be dropped: 因为下雨，我没去 / 下雨了，所以我没去.\n\nTo answer 为什么, start with **因为**.",
    ),
    examples: [
      ex("因为明天考试，所以我今天得复习。", "Yīnwèi míngtiān kǎoshì, suǒyǐ wǒ jīntiān děi fùxí.", "Comme j'ai un examen demain, je dois réviser aujourd'hui.", "Because I have an exam tomorrow, I have to revise today."),
      ex("因为他很认真，所以成绩很好。", "Yīnwèi tā hěn rènzhēn, suǒyǐ chéngjì hěn hǎo.", "Il est très sérieux, c'est pour ça qu'il a de bonnes notes.", "He's very diligent, so his grades are good."),
      ex("A：你为什么学中文？B：因为我对中国文化很感兴趣。", "A: Nǐ wèi shénme xué Zhōngwén? B: Yīnwèi wǒ duì Zhōngguó wénhuà hěn gǎn xìngqù.", "A : Pourquoi tu apprends le chinois ? B : Parce que la culture chinoise m'intéresse beaucoup.", "A: Why are you learning Chinese? B: Because I'm very interested in Chinese culture."),
      ex("昨天我生病了，所以没来上课。", "Zuótiān wǒ shēngbìng le, suǒyǐ méi lái shàngkè.", "Hier j'étais malade, donc je ne suis pas venu en cours.", "I was sick yesterday, so I didn't come to class."),
    ],
    pitfalls: t(
      "✗ 所以我没来，因为我生病了 (ordre français) : possible avec 因为 en 2e position seulement si on retire 所以 → ✓ 我没来，因为我生病了.",
      "✗ 所以我没来，因为我生病了: if the cause comes second, drop 所以 → ✓ 我没来，因为我生病了.",
    ),
  },
  {
    id: "hsk2-g44",
    level: 2,
    title: t("对 : envers, pour, à propos de", "对: to, towards, about"),
    pattern: "A + 对 + B + Adj / 感兴趣 / 有帮助",
    category: "介词 / prepositions",
    explanation: t(
      "La préposition **对** indique la **cible** d'une attitude ou d'un effet. Elle se place **avant** l'adjectif ou le verbe.\n\nExpressions clés : **对…感兴趣** (s'intéresser à), **对…很好** (être gentil avec), **对…有帮助** (être utile pour), **对…来说** (pour… , du point de vue de).\n\nComme adjectif, 对 veut aussi dire « juste, correct » : 你说得对 (tu as raison).",
      "The preposition **对** marks the **target** of an attitude or effect. It goes **before** the adjective or verb.\n\nKey expressions: **对…感兴趣** (be interested in), **对…很好** (be nice to), **对…有帮助** (be helpful for), **对…来说** (for…, from the point of view of).\n\nAs an adjective, 对 also means \"right, correct\": 你说得对 (you're right).",
    ),
    examples: [
      ex("我对中国历史很感兴趣。", "Wǒ duì Zhōngguó lìshǐ hěn gǎn xìngqù.", "Je m'intéresse beaucoup à l'histoire chinoise.", "I'm very interested in Chinese history."),
      ex("我们的老师对学生特别好。", "Wǒmen de lǎoshī duì xuésheng tèbié hǎo.", "Notre prof est très gentille avec les élèves.", "Our teacher is especially kind to the students."),
      ex("多听多说对学中文很有帮助。", "Duō tīng duō shuō duì xué Zhōngwén hěn yǒu bāngzhù.", "Écouter et parler beaucoup aide énormément pour apprendre le chinois.", "Listening and speaking a lot really helps with learning Chinese."),
      ex("对我来说，声调最难。", "Duì wǒ lái shuō, shēngdiào zuì nán.", "Pour moi, les tons sont le plus difficile.", "For me, tones are the hardest part."),
    ],
    pitfalls: t(
      "✗ 我感兴趣中国历史 → ✓ 我对中国历史感兴趣.\n✗ 他很好对我 → ✓ 他对我很好.",
      "✗ 我感兴趣中国历史 → ✓ 我对中国历史感兴趣.\n✗ 他很好对我 → ✓ 他对我很好.",
    ),
  },
  {
    id: "hsk2-g45",
    level: 2,
    title: t("往 + direction : vers, en direction de", "往 + direction: towards"),
    pattern: "往 + 前 / 左 / 右 / 东… + Verbe",
    category: "介词 / prepositions",
    explanation: t(
      "**往** (wǎng) indique la **direction** d'un mouvement. On l'utilise surtout pour **indiquer le chemin** : **往前走** (allez tout droit), **往左拐** (tournez à gauche), **往右拐** (tournez à droite).\n\nLe groupe **往 + direction** se place **devant le verbe**. On peut aussi dire 往 + lieu : 往地铁站走.\n\n**向** est un synonyme plus écrit : 向前走.",
      "**往** (wǎng) shows the **direction** of movement. It's the go-to word for **giving directions**: **往前走** (go straight ahead), **往左拐** (turn left), **往右拐** (turn right).\n\nThe **往 + direction** phrase goes **before the verb**. It also works with a place: 往地铁站走.\n\n**向** is a more formal synonym: 向前走.",
    ),
    examples: [
      ex("一直往前走，到了路口往右拐。", "Yìzhí wǎng qián zǒu, dàole lùkǒu wǎng yòu guǎi.", "Allez tout droit, et au carrefour, tournez à droite.", "Go straight ahead, and turn right at the intersection."),
      ex("往左拐就是银行。", "Wǎng zuǒ guǎi jiù shì yínháng.", "Tournez à gauche, c'est la banque.", "Turn left and it's the bank."),
      ex("这辆车往哪儿开？", "Zhè liàng chē wǎng nǎr kāi?", "Ce bus va dans quelle direction ?", "Which way is this bus heading?"),
      ex("你往东走十分钟就到了。", "Nǐ wǎng dōng zǒu shí fēnzhōng jiù dào le.", "Marche dix minutes vers l'est et tu y es.", "Walk east for ten minutes and you're there."),
    ],
    pitfalls: t(
      "✗ 走往前 → ✓ 往前走.\n✗ 左拐往 → ✓ 往左拐.",
      "✗ 走往前 → ✓ 往前走.\n✗ 左拐往 → ✓ 往左拐.",
    ),
  },
  {
    id: "hsk2-g46",
    level: 2,
    title: t("Complément directionnel simple : V + 来 / 去", "Simple directional complement: V + 来 / 去"),
    pattern: "Verbe + 来 / 去   /   Verbe + Lieu + 来 / 去",
    category: "补语 / complements (趋向补语)",
    explanation: t(
      "**来** et **去** après un verbe de mouvement indiquent la direction **par rapport au locuteur** : **来** = vers moi (ici), **去** = loin de moi (là-bas).\n\n进**来** (entre — je suis dedans), 进**去** (entre — je suis dehors), 回**来** (revenir ici), 回**去** (retourner là-bas), 上**来**, 下**去**…\n\nAvec un **lieu**, celui-ci se place **entre le verbe et 来/去** : 回**家**去, 进**教室**来, 上**楼**来.",
      "**来** and **去** after a movement verb show the direction **relative to the speaker**: **来** = towards me (here), **去** = away from me (there).\n\n进**来** (come in — I'm inside), 进**去** (go in — I'm outside), 回**来** (come back here), 回**去** (go back there), 上**来**, 下**去**…\n\nWith a **place**, it goes **between the verb and 来/去**: 回**家**去, 进**教室**来, 上**楼**来.",
    ),
    examples: [
      ex("外面冷，快进来吧！", "Wàimiàn lěng, kuài jìnlai ba!", "Il fait froid dehors, entre vite !", "It's cold outside, come on in!"),
      ex("你几点回来？", "Nǐ jǐ diǎn huílai?", "Tu rentres à quelle heure ?", "What time are you coming back?"),
      ex("我在楼下等你，你下来吧。", "Wǒ zài lóu xià děng nǐ, nǐ xiàlai ba.", "Je t'attends en bas, descends.", "I'm waiting for you downstairs, come down."),
      ex("他已经回家去了。", "Tā yǐjīng huí jiā qù le.", "Il est déjà rentré chez lui.", "He's already gone home."),
    ],
    pitfalls: t(
      "✗ 回来家 → ✓ 回家来.\n✗ 进去教室 → ✓ 进教室去.\nLe choix de 来/去 dépend de **ta** position : au téléphone, si tu es chez toi : 你什么时候回**来**？",
      "✗ 回来家 → ✓ 回家来.\n✗ 进去教室 → ✓ 进教室去.\n来 vs 去 depends on **your** position: on the phone from home: 你什么时候回**来**？",
    ),
  },
  {
    id: "hsk2-g47",
    level: 2,
    title: t("Directionnels : 上, 下, 进, 出, 回, 过, 起 (+ 来/去)", "Directionals: 上, 下, 进, 出, 回, 过, 起 (+ 来/去)"),
    pattern: "Verbe + 上 / 下 / 进 / 出 / 回 / 过 / 起 (+ 来 / 去)",
    category: "补语 / complements (趋向补语)",
    explanation: t(
      "Ces verbes de direction se collent à un **verbe d'action** pour préciser le trajet : 走 (marcher) + 进 (entrer) = **走进** (entrer à pied). 跑 + 出 = **跑出** (sortir en courant).\n\nOn peut ajouter 来/去 pour indiquer le point de vue : **走过去** (traverser, aller de l'autre côté), **站起来** (se lever), **拿出来** (sortir qqch), **开过来** (arriver en voiture vers ici).\n\nC'est très utile pour décrire un trajet : **走过**这条街 (traverser cette rue), **开进**停车场.",
      "These direction verbs attach to an **action verb** to specify the path: 走 (walk) + 进 (enter) = **走进** (walk in). 跑 + 出 = **跑出** (run out).\n\nAdd 来/去 for the viewpoint: **走过去** (walk over / across), **站起来** (stand up), **拿出来** (take out), **开过来** (drive over here).\n\nVery handy for routes: **走过**这条街 (cross this street), **开进**停车场 (drive into the car park).",
    ),
    examples: [
      ex("过了马路，你就能看见地铁站。", "Guòle mǎlù, nǐ jiù néng kànjiàn dìtiězhàn.", "Une fois la rue traversée, tu verras la station de métro.", "Once you cross the road, you'll see the subway station."),
      ex("出租车开过来了。", "Chūzūchē kāi guòlai le.", "Le taxi arrive (vers nous).", "The taxi is coming over."),
      ex("他从包里拿出来一张地图。", "Tā cóng bāo li ná chūlai yì zhāng dìtú.", "Il a sorti un plan de son sac.", "He took a map out of his bag."),
      ex("请大家站起来。", "Qǐng dàjiā zhàn qǐlai.", "Levez-vous tous, s'il vous plaît.", "Everyone please stand up."),
    ],
    pitfalls: t(
      "Avec un lieu, il se met avant 来/去 : ✗ 走进来房间 → ✓ 走进房间来.\n✗ 起来站 → ✓ 站起来 (le verbe d'action d'abord).",
      "With a place, it goes before 来/去: ✗ 走进来房间 → ✓ 走进房间来.\n✗ 起来站 → ✓ 站起来 (action verb first).",
    ),
  },
  {
    id: "hsk2-g48",
    level: 2,
    title: t("一…就… : dès que…", "一…就…: as soon as…"),
    pattern: "Sujet + 一 + V1，(Sujet) + 就 + V2",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "**一 A 就 B** : « dès que A, (aussitôt) B ». Les deux actions s'enchaînent **immédiatement**, ou B arrive **à chaque fois** que A arrive.\n\n一 et 就 sont des **adverbes** : ils se placent **devant les verbes**, après les sujets : 我**一**到**就**给你打电话.\n\nPour les indications : 你**一**出门**就**能看见 (dès que tu sors, tu le vois).",
      "**一 A 就 B**: \"as soon as A, B\". The two actions follow **immediately**, or B happens **every time** A does.\n\n一 and 就 are **adverbs**: they go **before the verbs**, after any subject: 我**一**到**就**给你打电话.\n\nGreat for directions: 你**一**出门**就**能看见 (you'll see it as soon as you step out).",
    ),
    examples: [
      ex("我一到就给你打电话。", "Wǒ yí dào jiù gěi nǐ dǎ diànhuà.", "Je t'appelle dès que j'arrive.", "I'll call you as soon as I arrive."),
      ex("你一出地铁站就能看见那个商场。", "Nǐ yì chū dìtiězhàn jiù néng kànjiàn nàge shāngchǎng.", "Dès que tu sors du métro, tu verras le centre commercial.", "As soon as you exit the subway, you'll see the mall."),
      ex("他一下班就回家了。", "Tā yí xiàbān jiù huí jiā le.", "Il est rentré chez lui dès la fin du travail.", "He went home as soon as he finished work."),
      ex("我一喝咖啡就睡不着。", "Wǒ yì hē kāfēi jiù shuì bu zháo.", "Dès que je bois du café, je n'arrive pas à dormir.", "Whenever I drink coffee, I can't sleep."),
    ],
    pitfalls: t(
      "✗ 一我到就… → ✓ 我一到就… (一 après le sujet).\nAvec deux sujets : ✗ 我一到，就他来了 → ✓ 我一到，他就来了.\nN'oublie pas la variation tonale de 一 : yí devant un 4e ton, yì devant les autres.",
      "✗ 一我到就… → ✓ 我一到就… (一 after the subject).\nWith two subjects: ✗ 我一到，就他来了 → ✓ 我一到，他就来了.\nMind the tone change of 一: yí before a 4th tone, yì before the others.",
    ),
  },
  {
    id: "hsk2-g49",
    level: 2,
    title: t("多 + Adj ? : à quelle distance, combien de temps…", "多 + Adj?: how far, how long…"),
    pattern: "(有) + 多 + 远 / 长 / 大 / 高 / 久？",
    category: "代词 / pronouns (疑问)",
    explanation: t(
      "**多 + adjectif** forme une question sur le **degré** : 多远 (à quelle distance), 多长时间 (combien de temps), 多大 (quel âge / quelle taille), 多高 (quelle hauteur / taille), 多久 (combien de temps).\n\nOn ajoute souvent **有** devant : 离这儿**有多远**？\n\nDans une exclamation, 多 veut dire « comme… ! » : 多漂亮啊！(Que c'est beau !)",
      "**多 + adjective** asks about **degree**: 多远 (how far), 多长时间 (how long), 多大 (how old / how big), 多高 (how tall), 多久 (how long).\n\n**有** is often added in front: 离这儿**有多远**？\n\nIn an exclamation, 多 means \"how…!\": 多漂亮啊！(How beautiful!)",
    ),
    examples: [
      ex("火车站离这儿有多远？", "Huǒchēzhàn lí zhèr yǒu duō yuǎn?", "La gare est à quelle distance d'ici ?", "How far is the train station from here?"),
      ex("走路要多长时间？", "Zǒulù yào duō cháng shíjiān?", "Ça prend combien de temps à pied ?", "How long does it take on foot?"),
      ex("你的孩子多大了？", "Nǐ de háizi duō dà le?", "Quel âge a ton enfant ?", "How old is your child?"),
      ex("这座楼有多高？", "Zhè zuò lóu yǒu duō gāo?", "Quelle est la hauteur de ce bâtiment ?", "How tall is this building?"),
    ],
    pitfalls: t(
      "✗ 多少远 → ✓ 多远 (多少 = combien, pour les quantités).\n✗ 你几大？ → ✓ 你多大？ (几 seulement pour les enfants : 你几岁？).",
      "✗ 多少远 → ✓ 多远 (多少 = how many / how much).\n✗ 你几大？ → ✓ 你多大？ (几 only for young children: 你几岁？).",
    ),
  },
  {
    id: "hsk2-g50",
    level: 2,
    title: t("如果…就… : si… alors…", "如果…就…: if… then…"),
    pattern: "如果 + condition，(Sujet) + 就 + résultat",
    category: "复句 / complex sentences (假设)",
    explanation: t(
      "**如果** introduit une **hypothèse**, **就** introduit la **conséquence**. 就 est un adverbe : il se met **après le sujet** de la 2e proposition, devant le verbe.\n\nOn ajoute souvent **的话** à la fin de la condition, surtout à l'oral : 如果你不喜欢**的话**，就退了吧.\n\n如果 peut être omis à l'oral : 你不喜欢，就退了吧.",
      "**如果** introduces a **condition**, **就** the **consequence**. 就 is an adverb: it goes **after the subject** of the second clause, before the verb.\n\n**的话** is often added at the end of the condition, especially in speech: 如果你不喜欢**的话**，就退了吧.\n\nIn speech 如果 itself can be dropped: 你不喜欢，就退了吧.",
    ),
    examples: [
      ex("如果你不满意，就可以退货。", "Rúguǒ nǐ bù mǎnyì, jiù kěyǐ tuìhuò.", "Si tu n'es pas satisfait, tu peux renvoyer l'article.", "If you're not satisfied, you can return it."),
      ex("如果今天下单，明天就能到。", "Rúguǒ jīntiān xiàdān, míngtiān jiù néng dào.", "Si tu commandes aujourd'hui, ça arrive demain.", "If you order today, it'll arrive tomorrow."),
      ex("如果有问题的话，你就给我打电话。", "Rúguǒ yǒu wèntí dehuà, nǐ jiù gěi wǒ dǎ diànhuà.", "S'il y a un problème, appelle-moi.", "If there's any problem, give me a call."),
      ex("如果太贵，我就不买了。", "Rúguǒ tài guì, wǒ jiù bù mǎi le.", "Si c'est trop cher, je ne l'achète pas.", "If it's too expensive, I won't buy it."),
    ],
    pitfalls: t(
      "✗ 如果太贵，就我不买 → ✓ 如果太贵，我就不买 (就 après le sujet).\nPas de « alors » en tête comme en français : 就 est un adverbe, pas une conjonction.",
      "✗ 如果太贵，就我不买 → ✓ 如果太贵，我就不买 (就 after the subject).\n就 is an adverb, not a conjunction like \"then\" in English.",
    ),
  },
  {
    id: "hsk2-g51",
    level: 2,
    title: t("就 et 才 : tôt/facile ou tard/difficile", "就 vs 才: early/easy vs late/hard"),
    pattern: "Temps / Quantité + 就 + V + 了   /   Temps / Quantité + 才 + V",
    category: "副词 / adverbs (时间)",
    explanation: t(
      "Ces deux adverbes ajoutent le **jugement** du locuteur sur un moment ou une quantité :\n\n**就** = plus tôt / plus vite / plus facilement que prévu. Souvent avec 了 : 我八点**就**到了 (j'étais déjà là à 8 h — tôt !).\n**才** = plus tard / plus lentement / plus difficilement que prévu. **Sans 了** : 他十点**才**到 (il n'est arrivé qu'à 10 h — tard !).\n\nAvec une quantité, **才** peut aussi signifier « seulement » : 这件衣服**才**五十块 (ce vêtement ne coûte que 50 yuans).",
      "These two adverbs add the speaker's **judgement** about a time or amount:\n\n**就** = earlier / faster / easier than expected. Usually with 了: 我八点**就**到了 (I was there by 8 — early!).\n**才** = later / slower / harder than expected. **No 了**: 他十点**才**到 (he didn't arrive until 10 — late!).\n\nWith an amount, **才** can also mean \"only\": 这件衣服**才**五十块 (this top is only 50 yuan).",
    ),
    examples: [
      ex("我昨天下单，今天就到了。", "Wǒ zuótiān xiàdān, jīntiān jiù dào le.", "J'ai commandé hier, c'est déjà arrivé aujourd'hui.", "I ordered yesterday and it's already arrived today."),
      ex("快递一个星期才到。", "Kuàidì yí ge xīngqī cái dào.", "Le colis a mis une semaine à arriver.", "The parcel took a whole week to arrive."),
      ex("他十一点才起床。", "Tā shíyī diǎn cái qǐchuáng.", "Il ne s'est levé qu'à onze heures.", "He didn't get up until eleven."),
      ex("这双鞋才一百块，太便宜了！", "Zhè shuāng xié cái yìbǎi kuài, tài piányi le!", "Ces chaussures ne coûtent que cent yuans, c'est donné !", "These shoes are only 100 yuan, what a bargain!"),
    ],
    pitfalls: t(
      "✗ 他十点才到了 → ✓ 他十点才到 (pas de 了 avec 才).\n✗ 才他十点到 → ✓ 他十点才到 (才 devant le verbe).",
      "✗ 他十点才到了 → ✓ 他十点才到 (no 了 with 才).\n✗ 才他十点到 → ✓ 他十点才到 (才 before the verb).",
    ),
  },
  {
    id: "hsk2-g52",
    level: 2,
    title: t("什么都 / 谁都 / 哪儿都 : tout, tout le monde, partout", "什么都 / 谁都 / 哪儿都: everything, everyone, everywhere"),
    pattern: "什么 / 谁 / 哪儿 / 怎么 + 都 / 也 + (不/没) + Verbe",
    category: "代词 / pronouns (任指)",
    explanation: t(
      "Un mot interrogatif suivi de **都** ou **也** perd son sens de question et devient **général** :\n\n**什么都** = tout, **谁都** = tout le monde, **哪儿都** = partout, **怎么都** = de toute façon.\n\nÀ la forme négative, on obtient « rien, personne, nulle part » : 我**什么都不**想买 (je ne veux rien acheter), **谁都没**来 (personne n'est venu).\n\nL'ordre est clé : le mot interrogatif vient **avant** le verbe (comme un sujet ou un objet déplacé devant).",
      "A question word followed by **都** or **也** stops being a question and becomes **all-inclusive**:\n\n**什么都** = everything, **谁都** = everyone, **哪儿都** = everywhere, **怎么都** = no matter how.\n\nIn the negative you get \"nothing, nobody, nowhere\": 我**什么都不**想买 (I don't want to buy anything), **谁都没**来 (nobody came).\n\nWord order is key: the question word comes **before** the verb (as a subject or a fronted object).",
    ),
    examples: [
      ex("网上什么都能买到。", "Wǎng shang shénme dōu néng mǎidào.", "On peut tout acheter en ligne.", "You can buy anything online."),
      ex("我今天什么都不想买。", "Wǒ jīntiān shénme dōu bù xiǎng mǎi.", "Aujourd'hui je ne veux rien acheter.", "I don't want to buy anything today."),
      ex("这个软件谁都会用。", "Zhège ruǎnjiàn shéi dōu huì yòng.", "Tout le monde sait utiliser cette appli.", "Anyone can use this app."),
      ex("周末我哪儿也没去。", "Zhōumò wǒ nǎr yě méi qù.", "Ce week-end, je ne suis allé nulle part.", "I didn't go anywhere at the weekend."),
    ],
    pitfalls: t(
      "✗ 我不想买什么都 → ✓ 我什么都不想买.\n✗ 我没去哪儿都 → ✓ 我哪儿都没去.",
      "✗ 我不想买什么都 → ✓ 我什么都不想买.\n✗ 我没去哪儿都 → ✓ 我哪儿都没去.",
    ),
  },
  {
    id: "hsk2-g53",
    level: 2,
    title: t("地 : la manière (adverbe + 地 + verbe)", "地: manner (adverbial + 地 + verb)"),
    pattern: "Adj / Adj redoublé + 地 + Verbe",
    category: "助词 / particles (结构助词)",
    explanation: t(
      "**地** (de) transforme un adjectif en **adverbe de manière** placé **avant le verbe**, comme « -ment » en français : 认真**地**看 = regarder attentivement.\n\nOn le voit surtout avec des adjectifs de deux syllabes ou redoublés : 慢慢**地**, 高高兴兴**地**, 认真**地**, 仔细**地**.\n\nRécap des trois « de » : **的** + nom (我的书), **地** + verbe (认真地学), verbe + **得** + adj (学得好).",
      "**地** (de) turns an adjective into a **manner adverbial** placed **before the verb**, like \"-ly\" in English: 认真**地**看 = look carefully.\n\nIt's mostly used with two-syllable or reduplicated adjectives: 慢慢**地**, 高高兴兴**地**, 认真**地**, 仔细**地**.\n\nThe three \"de\" in a nutshell: **的** + noun (我的书), **地** + verb (认真地学), verb + **得** + adj (学得好).",
    ),
    examples: [
      ex("买东西以前，你要认真地看评价。", "Mǎi dōngxi yǐqián, nǐ yào rènzhēn de kàn píngjià.", "Avant d'acheter, lis attentivement les avis.", "Before buying, read the reviews carefully."),
      ex("他高高兴兴地打开了快递。", "Tā gāogāoxìngxìng de dǎkāile kuàidì.", "Il a ouvert son colis tout joyeux.", "He happily opened his parcel."),
      ex("请慢慢地说。", "Qǐng mànmàn de shuō.", "Parle lentement, s'il te plaît.", "Please speak slowly."),
      ex("孩子们安静地坐着。", "Háizimen ānjìng de zuòzhe.", "Les enfants sont assis tranquillement.", "The children are sitting quietly."),
    ],
    pitfalls: t(
      "✗ 认真的学习 (dans une phrase verbale) → ✓ 认真地学习.\n✗ 他说地很快 → ✓ 他说得很快 (après le verbe = 得).",
      "✗ 认真的学习 (in a verbal sentence) → ✓ 认真地学习.\n✗ 他说地很快 → ✓ 他说得很快 (after the verb = 得).",
    ),
  },
  {
    id: "hsk2-g54",
    level: 2,
    title: t("Grands nombres : 百, 千, 万", "Big numbers: 百, 千, 万"),
    pattern: "… 万 … 千 … 百 … 十 …",
    category: "数词 / numerals",
    explanation: t(
      "Le chinois compte par **dix mille** (**万** wàn), pas par mille : 10 000 = 一万, 100 000 = 十万, 1 000 000 = 一百万.\n\nÉtapes : 百 (100), 千 (1 000), 万 (10 000). 3 580 = 三千五百八十. Un **零** marque les zéros internes : 205 = 两百零五 / 二百零五, 1 005 = 一千零五.\n\nDevant 百, 千, 万, on dit souvent **两** : 两百, 两千, 两万. Dans les prix, le dernier chiffre peut tomber à l'oral : 两百五 = 250.",
      "Chinese counts in **ten-thousands** (**万** wàn), not thousands: 10,000 = 一万, 100,000 = 十万, 1,000,000 = 一百万.\n\nSteps: 百 (100), 千 (1,000), 万 (10,000). 3,580 = 三千五百八十. **零** marks inner zeros: 205 = 两百零五 / 二百零五, 1,005 = 一千零五.\n\nBefore 百, 千, 万, **两** is common: 两百, 两千, 两万. In prices the last unit is often dropped in speech: 两百五 = 250.",
    ),
    examples: [
      ex("这个手机三千八百块。", "Zhège shǒujī sānqiān bābǎi kuài.", "Ce téléphone coûte 3 800 yuans.", "This phone costs 3,800 yuan."),
      ex("这家店有两万多个评价。", "Zhè jiā diàn yǒu liǎngwàn duō ge píngjià.", "Cette boutique a plus de 20 000 avis.", "This shop has over 20,000 reviews."),
      ex("一共一百零五块。", "Yígòng yìbǎi líng wǔ kuài.", "Ça fait 105 yuans en tout.", "That's 105 yuan in total."),
      ex("我们公司有一千五百个人。", "Wǒmen gōngsī yǒu yìqiān wǔbǎi ge rén.", "Notre entreprise compte 1 500 personnes.", "Our company has 1,500 people."),
    ],
    pitfalls: t(
      "✗ 十千 (10 000) → ✓ 一万.\n✗ 一百五 = 150 (pas 105) ; 105 = 一百零五.",
      "✗ 十千 (10,000) → ✓ 一万.\n一百五 = 150 (not 105); 105 = 一百零五.",
    ),
  },
  {
    id: "hsk2-g55",
    level: 2,
    title: t("是不是 : …, non ? (demande de confirmation)", "是不是: …, right? (confirmation)"),
    pattern: "Phrase + 是不是？ / Sujet + 是不是 + Verbe…？",
    category: "句类 / sentence types (疑问句)",
    explanation: t(
      "**是不是** sert à **vérifier une supposition** : tu penses que c'est vrai et tu veux une confirmation, comme « …, non ? » ou « c'est bien ça ? ».\n\nIl peut se placer **devant le verbe** (你**是不是**不舒服？= tu ne te sens pas bien, c'est ça ?), **en tête** ou **en fin** de phrase (你明天有空，**是不是**？).\n\nÀ la différence de 吗 (question neutre), 是不是 montre que tu as déjà **une idée** de la réponse.",
      "**是不是** is used to **check an assumption**: you think something is true and want confirmation — like \"…, right?\" or \"isn't it?\".\n\nIt can go **before the verb** (你**是不是**不舒服？= you're not feeling well, are you?), at the **start** or at the **end** (你明天有空，**是不是**？).\n\nUnlike 吗 (neutral question), 是不是 shows you already **have an idea** of the answer.",
    ),
    examples: [
      ex("你周六是不是有空？", "Nǐ zhōuliù shì bu shì yǒu kòng?", "Tu es libre samedi, non ?", "You're free on Saturday, aren't you?"),
      ex("是不是你的生日快到了？", "Shì bu shì nǐ de shēngrì kuài dào le?", "C'est bientôt ton anniversaire, non ?", "Isn't your birthday coming up?"),
      ex("我们七点见，是不是？", "Wǒmen qī diǎn jiàn, shì bu shì?", "On se voit à sept heures, c'est bien ça ?", "We're meeting at seven, right?"),
      ex("你是不是累了？", "Nǐ shì bu shì lèi le?", "Tu es fatigué, c'est ça ?", "Are you tired?"),
    ],
    pitfalls: t(
      "✗ 你是不是有空吗？ → ✓ 你是不是有空？ (pas de 吗).\nAvec un adjectif, pas besoin d'enlever 是不是 : ✓ 你是不是很忙？",
      "✗ 你是不是有空吗？ → ✓ 你是不是有空？ (no 吗).\nIt works with adjectives too: ✓ 你是不是很忙？",
    ),
  },
  {
    id: "hsk2-g56",
    level: 2,
    title: t("Redoublement du verbe et V + 一下", "Verb reduplication and V + 一下"),
    pattern: "V V / V 一 V / V 了 V / AB AB / V + 一下",
    category: "动词重叠 / verb reduplication",
    explanation: t(
      "Redoubler un verbe lui donne une nuance **« un peu, rapidement, juste pour essayer »** et rend une proposition plus **décontractée** : 你**看看** (jette un œil), 我们**聊聊** (discutons un peu).\n\nFormes : **看看 / 看一看** (1 syllabe), **休息休息 / 介绍介绍** (2 syllabes : ABAB), **看了看** (au passé). La 2e syllabe est au ton neutre.\n\n**V + 一下** a le même effet : 等一下, 介绍一下. Attention : les verbes séparables redoublent seulement le verbe : 散**散**步, 聊**聊**天.",
      "Reduplicating a verb adds a sense of **\"a little, briefly, give it a try\"** and makes a suggestion more **casual**: 你**看看** (have a look), 我们**聊聊** (let's chat a bit).\n\nForms: **看看 / 看一看** (1 syllable), **休息休息 / 介绍介绍** (2 syllables: ABAB), **看了看** (past). The repeated syllable is neutral tone.\n\n**V + 一下** does the same: 等一下, 介绍一下. Note: separable verbs repeat only the verb part: 散**散**步, 聊**聊**天.",
    ),
    examples: [
      ex("你看看这个，怎么样？", "Nǐ kànkan zhège, zěnmeyàng?", "Jette un œil à ça, qu'est-ce que tu en penses ?", "Take a look at this — what do you think?"),
      ex("周末我们一起去公园散散步吧。", "Zhōumò wǒmen yìqǐ qù gōngyuán sànsan bù ba.", "Ce week-end, allons nous balader un peu au parc.", "Let's take a little walk in the park this weekend."),
      ex("你太累了，休息休息吧。", "Nǐ tài lèi le, xiūxi xiūxi ba.", "Tu es trop fatigué, repose-toi un peu.", "You're exhausted — rest a bit."),
      ex("我想一想再告诉你。", "Wǒ xiǎng yi xiǎng zài gàosu nǐ.", "Je réfléchis un peu et je te dis.", "Let me think about it and I'll tell you."),
    ],
    pitfalls: t(
      "✗ 散步散步 → ✓ 散散步.\n✗ 休休息息 → ✓ 休息休息 (AB AB, pas AABB — AABB est pour les adjectifs).\nOn ne redouble pas un verbe suivi d'un complément de durée ou de 着 : ✗ 看看了三个小时.",
      "✗ 散步散步 → ✓ 散散步.\n✗ 休休息息 → ✓ 休息休息 (ABAB, not AABB — AABB is for adjectives).\nDon't reduplicate with a duration or 着: ✗ 看看了三个小时.",
    ),
  },
  {
    id: "hsk2-g57",
    level: 2,
    title: t("一边…一边… : tout en…", "一边…一边…: while…"),
    pattern: "Sujet + 一边 + V1，一边 + V2",
    category: "固定格式 / fixed patterns",
    explanation: t(
      "**一边 A 一边 B** décrit deux actions faites **simultanément** par la même personne : « faire A **tout en** faisant B ».\n\nLes deux 一边 se placent **devant les verbes**. À l'oral, on peut abréger en **边…边…** : 边吃边聊.\n\nPour deux qualités simultanées (adjectifs), on utilise plutôt 又…又….",
      "**一边 A 一边 B** describes two actions done **at the same time** by the same person: \"do A **while** doing B\".\n\nBoth 一边 go **before the verbs**. In speech it's often shortened to **边…边…**: 边吃边聊.\n\nFor two simultaneous qualities (adjectives), use 又…又… instead.",
    ),
    examples: [
      ex("我们一边吃饭一边聊天吧。", "Wǒmen yìbiān chī fàn yìbiān liáotiān ba.", "Discutons en mangeant.", "Let's chat over dinner."),
      ex("他喜欢一边听音乐一边跑步。", "Tā xǐhuan yìbiān tīng yīnyuè yìbiān pǎobù.", "Il aime courir en écoutant de la musique.", "He likes to run while listening to music."),
      ex("别一边开车一边打电话！", "Bié yìbiān kāichē yìbiān dǎ diànhuà!", "Ne téléphone pas en conduisant !", "Don't talk on the phone while driving!"),
      ex("大家边喝茶边看节目。", "Dàjiā biān hē chá biān kàn jiémù.", "Tout le monde regarde l'émission en buvant du thé.", "Everyone watches the show while drinking tea."),
    ],
    pitfalls: t(
      "✗ 一边我吃饭一边我聊天 → ✓ 我一边吃饭一边聊天 (sujet une seule fois, en tête).\n✗ 一边高兴一边累 → ✓ 又高兴又累 (adjectifs = 又…又…).",
      "✗ 一边我吃饭一边我聊天 → ✓ 我一边吃饭一边聊天 (subject once, at the start).\n✗ 一边高兴一边累 → ✓ 又高兴又累 (adjectives = 又…又…).",
    ),
  },
  {
    id: "hsk2-g58",
    level: 2,
    title: t("为什么 et 怎么 : pourquoi, comment se fait-il", "为什么 and 怎么: why, how come"),
    pattern: "Sujet + 为什么 / 怎么 + (不/没) + Verbe？",
    category: "代词 / pronouns (疑问)",
    explanation: t(
      "**为什么** = « pourquoi » : question neutre sur la **raison**. On y répond avec 因为.\n\n**怎么** peut aussi signifier « **comment se fait-il que** » : il exprime la **surprise** ou un léger reproche : 你**怎么**没来？(Comment ça, tu n'es pas venu ?).\n\n**怎么了？** = « qu'est-ce qui se passe ? / qu'est-ce qui t'arrive ? ». Rappel : **怎么 + verbe** (sans surprise) = « comment faire » : 怎么走？(Par où on passe ?)",
      "**为什么** = \"why\": a neutral question about the **reason**. Answer with 因为.\n\n**怎么** can also mean \"**how come**\": it shows **surprise** or mild reproach: 你**怎么**没来？(How come you didn't come?).\n\n**怎么了？** = \"what's wrong? / what's up?\". Reminder: **怎么 + verb** (no surprise) = \"how to\": 怎么走？(Which way do I go?)",
    ),
    examples: [
      ex("你为什么不去参加聚会？", "Nǐ wèi shénme bú qù cānjiā jùhuì?", "Pourquoi tu ne vas pas à la fête ?", "Why aren't you going to the party?"),
      ex("你怎么还没到？大家都在等你。", "Nǐ zěnme hái méi dào? Dàjiā dōu zài děng nǐ.", "Comment ça, tu n'es pas encore là ? Tout le monde t'attend.", "How come you're not here yet? Everyone's waiting."),
      ex("你怎么了？不舒服吗？", "Nǐ zěnme le? Bù shūfu ma?", "Qu'est-ce qui t'arrive ? Tu ne te sens pas bien ?", "What's wrong? Are you unwell?"),
      ex("A：你为什么这么高兴？B：因为明天放假！", "A: Nǐ wèi shénme zhème gāoxìng? B: Yīnwèi míngtiān fàngjià!", "A : Pourquoi tu es si content ? B : Parce que demain c'est férié !", "A: Why are you so happy? B: Because tomorrow's a day off!"),
    ],
    pitfalls: t(
      "✗ 为什么你不来？ est possible, mais le plus naturel est ✓ 你为什么不来？ (après le sujet).\n✗ 你怎么了吗？ → ✓ 你怎么了？",
      "为什么你不来？ is possible, but ✓ 你为什么不来？ (after the subject) is most natural.\n✗ 你怎么了吗？ → ✓ 你怎么了？",
    ),
  },
  {
    id: "hsk2-g59",
    level: 2,
    title: t("再 ou 又 ? (encore, de nouveau)", "再 vs 又 (again)"),
    pattern: "再 + V (futur)   /   又 + V + 了 (passé)",
    category: "副词 / adverbs (频率)",
    explanation: t(
      "Les deux signifient « encore, de nouveau », mais :\n\n**再** = répétition **à venir** (pas encore faite) : 下次**再**来 (reviens la prochaine fois), 请**再**说一遍.\n**又** = répétition **déjà réalisée** : 他昨天来了，今天**又**来了 (il est venu hier, et il est revenu aujourd'hui). Souvent avec 了.\n\nExceptions : avec 是, 要, 想, 可以, 会 on dit 又 même pour le futur : 明天**又**是星期一了.",
      "Both mean \"again\", but:\n\n**再** = repetition **still to come**: 下次**再**来 (come again next time), 请**再**说一遍.\n**又** = repetition **that already happened**: 他昨天来了，今天**又**来了 (he came yesterday and came again today). Usually with 了.\n\nException: before 是, 要, 想, 可以, 会, 又 is used even for the future: 明天**又**是星期一了.",
    ),
    examples: [
      ex("欢迎你下次再来！", "Huānyíng nǐ xià cì zài lái!", "Reviens quand tu veux !", "Come again any time!"),
      ex("他今天又迟到了。", "Tā jīntiān yòu chídào le.", "Il est encore arrivé en retard aujourd'hui.", "He was late again today."),
      ex("我们明天再聊吧。", "Wǒmen míngtiān zài liáo ba.", "On en reparle demain.", "Let's talk about it again tomorrow."),
      ex("明天又是星期一了！", "Míngtiān yòu shì xīngqīyī le!", "Demain, c'est encore lundi !", "It's Monday again tomorrow!"),
    ],
    pitfalls: t(
      "✗ 昨天我再去了 → ✓ 昨天我又去了.\n✗ 明天我又来 → ✓ 明天我再来.",
      "✗ 昨天我再去了 → ✓ 昨天我又去了.\n✗ 明天我又来 → ✓ 明天我再来.",
    ),
  },
  {
    id: "hsk2-g60",
    level: 2,
    title: t("跟…一样 : pareil que, aussi… que", "跟…一样: the same as, as… as"),
    pattern: "A + 跟 / 和 + B + (不)一样 (+ Adj)",
    category: "句型 / sentence patterns (比较)",
    explanation: t(
      "**A 跟 B 一样** = « A est pareil que B ». Ajoute un adjectif pour préciser le point commun : A 跟 B **一样贵** (A est aussi cher que B).\n\nNégation : **不一样** (différent) : A 跟 B **不一样**.\n\n一样 peut aussi être un adjectif devant un nom : **一样的**颜色 (la même couleur).",
      "**A 跟 B 一样** = \"A is the same as B\". Add an adjective to specify how: A 跟 B **一样贵** (A is as expensive as B).\n\nNegative: **不一样** (different): A 跟 B **不一样**.\n\n一样 can also act as an adjective before a noun: **一样的**颜色 (the same colour).",
    ),
    examples: [
      ex("这个跟那个一样大。", "Zhège gēn nàge yíyàng dà.", "Celui-ci est aussi grand que celui-là.", "This one is as big as that one."),
      ex("我的手机跟你的一样。", "Wǒ de shǒujī gēn nǐ de yíyàng.", "J'ai le même téléphone que toi.", "My phone is the same as yours."),
      ex("这两件衣服的颜色不一样。", "Zhè liǎng jiàn yīfu de yánsè bù yíyàng.", "Ces deux vêtements n'ont pas la même couleur.", "These two garments are different colours."),
      ex("网上的价格和店里的一样吗？", "Wǎng shang de jiàgé hé diàn li de yíyàng ma?", "Le prix en ligne est-il le même qu'en boutique ?", "Is the online price the same as in the store?"),
    ],
    pitfalls: t(
      "✗ 这个一样大跟那个 → ✓ 这个跟那个一样大.\n✗ 这个跟那个不一样大 existe, mais pour « pas aussi… que » on préfère ✓ 这个没有那个大.",
      "✗ 这个一样大跟那个 → ✓ 这个跟那个一样大.\n这个跟那个不一样大 exists, but for \"not as… as\" ✓ 这个没有那个大 is preferred.",
    ),
  },
  {
    id: "hsk2-g61",
    level: 2,
    title: t("A 没有 B (那么) Adj : pas aussi… que", "A 没有 B (那么) Adj: not as… as"),
    pattern: "A + 没有 + B + (这么 / 那么) + Adj",
    category: "句型 / sentence patterns (比较)",
    explanation: t(
      "C'est la **négation naturelle** de 比 : **A 没有 B + adj** = « A n'est pas aussi … que B ».\n\n这个没有那个贵 = celui-ci n'est pas aussi cher que celui-là (= il est moins cher).\n\nOn ajoute souvent **那么** ou **这么** devant l'adjectif pour insister : 没有那个**那么**贵. Forme affirmative plus rare : A **有** B 那么 adj (A est aussi … que B).",
      "This is the **natural negative** of 比: **A 没有 B + adj** = \"A is not as … as B\".\n\n这个没有那个贵 = this one isn't as expensive as that one (= it's cheaper).\n\n**那么** or **这么** is often added before the adjective: 没有那个**那么**贵. The affirmative is rarer: A **有** B 那么 adj (A is as … as B).",
    ),
    examples: [
      ex("这个手机没有那个贵。", "Zhège shǒujī méiyǒu nàge guì.", "Ce téléphone n'est pas aussi cher que l'autre.", "This phone isn't as expensive as that one."),
      ex("地铁没有出租车那么快。", "Dìtiě méiyǒu chūzūchē nàme kuài.", "Le métro n'est pas aussi rapide que le taxi.", "The subway isn't as fast as a taxi."),
      ex("我没有我妹妹那么高。", "Wǒ méiyǒu wǒ mèimei nàme gāo.", "Je ne suis pas aussi grand que ma petite sœur.", "I'm not as tall as my younger sister."),
      ex("他有你这么高吗？", "Tā yǒu nǐ zhème gāo ma?", "Il est aussi grand que toi ?", "Is he as tall as you?"),
    ],
    pitfalls: t(
      "✗ 这个比那个不贵 (maladroit) → ✓ 这个没有那个贵.\n✗ 这个没有那个很贵 → ✓ 这个没有那个(那么)贵.",
      "✗ 这个比那个不贵 (clumsy) → ✓ 这个没有那个贵.\n✗ 这个没有那个很贵 → ✓ 这个没有那个(那么)贵.",
    ),
  },
  {
    id: "hsk2-g62",
    level: 2,
    title: t("这么 / 那么 / 这样 / 那样 : si, tellement, comme ça", "这么 / 那么 / 这样 / 那样: so, like this / that"),
    pattern: "这么 / 那么 + Adj / Verbe   ;   这样 / 那样 + (的) + Nom",
    category: "代词 / pronouns (指示)",
    explanation: t(
      "**这么 / 那么 + adjectif** = « si, tellement » : 这么贵！(si cher !), 没那么难 (pas si difficile).\n\n**这么 / 那么 + verbe** = « de cette façon » : 这个字**这么**写 (ce caractère s'écrit comme ça).\n\n**这样 / 那样** fonctionnent comme des adjectifs ou des pronoms : **这样的**衣服 (des vêtements comme ça), 就**这样**吧 (disons comme ça). 这 = proche, 那 = éloigné, comme toujours.",
      "**这么 / 那么 + adjective** = \"so, that\": 这么贵！(so expensive!), 没那么难 (not that hard).\n\n**这么 / 那么 + verb** = \"like this / that\": 这个字**这么**写 (this character is written like this).\n\n**这样 / 那样** work as adjectives or pronouns: **这样的**衣服 (clothes like these), 就**这样**吧 (let's leave it like that). 这 = near, 那 = far, as always.",
    ),
    examples: [
      ex("这件衣服怎么这么贵？", "Zhè jiàn yīfu zěnme zhème guì?", "Comment ce vêtement peut-il être si cher ?", "How come this top is so expensive?"),
      ex("中文没有你想的那么难。", "Zhōngwén méiyǒu nǐ xiǎng de nàme nán.", "Le chinois n'est pas aussi difficile que tu le penses.", "Chinese isn't as hard as you think."),
      ex("我想要一个这样的包。", "Wǒ xiǎng yào yí ge zhèyàng de bāo.", "Je voudrais un sac comme celui-ci.", "I'd like a bag like this."),
      ex("好，就这样吧！", "Hǎo, jiù zhèyàng ba!", "OK, on fait comme ça !", "OK, let's do it that way!"),
    ],
    pitfalls: t(
      "✗ 这么的衣服 → ✓ 这样的衣服 (devant un nom : 这样的).\n✗ 这样贵 est moins naturel que ✓ 这么贵 devant un adjectif.",
      "✗ 这么的衣服 → ✓ 这样的衣服 (before a noun: 这样的).\n这样贵 is less natural than ✓ 这么贵 before an adjective.",
    ),
  },
  {
    id: "hsk2-g63",
    level: 2,
    title: t("更 et 最 : encore plus, le plus", "更 and 最: even more, the most"),
    pattern: "更 + Adj   /   最 + Adj",
    category: "副词 / adverbs (程度)",
    explanation: t(
      "**更** (gèng) = « encore plus » : il compare implicitement ou explicitement avec autre chose qui a déjà la qualité. 这个很好，那个**更**好 (celui-ci est bien, celui-là est encore mieux).\n\n**最** (zuì) = « le plus » : superlatif. 这是**最**便宜的 (c'est le moins cher / le plus bon marché).\n\nAvec 比, on peut dire A 比 B **更** Adj (mais jamais 很).",
      "**更** (gèng) = \"even more\": it compares with something that already has the quality. 这个很好，那个**更**好 (this one's good, that one's even better).\n\n**最** (zuì) = \"the most\": superlative. 这是**最**便宜的 (this is the cheapest).\n\nWith 比 you can say A 比 B **更** Adj (but never 很).",
    ),
    examples: [
      ex("这个颜色更好看。", "Zhège yánsè gèng hǎokàn.", "Cette couleur est encore plus jolie.", "This colour looks even better."),
      ex("三个手机里，这个最便宜。", "Sān ge shǒujī li, zhège zuì piányi.", "Parmi les trois téléphones, celui-ci est le moins cher.", "Of the three phones, this one is the cheapest."),
      ex("坐高铁比坐飞机更方便。", "Zuò gāotiě bǐ zuò fēijī gèng fāngbiàn.", "Le TGV est encore plus pratique que l'avion.", "The high-speed train is even more convenient than flying."),
      ex("你最喜欢哪一个？", "Nǐ zuì xǐhuan nǎ yí ge?", "Lequel préfères-tu ?", "Which one do you like best?"),
    ],
    pitfalls: t(
      "✗ 更很好 → ✓ 更好.\n✗ 这个是更便宜的三个里 → ✓ 三个里这个最便宜 (superlatif = 最).",
      "✗ 更很好 → ✓ 更好.\n✗ 这个是更便宜的三个里 → ✓ 三个里这个最便宜 (superlative = 最).",
    ),
  },
  {
    id: "hsk2-g64",
    level: 2,
    title: t("Le groupe en 的 : 红的, 我的, 大的…", "的-phrases: 红的, 我的, 大的…"),
    pattern: "Adj / Pronom / Verbe + 的 (= celui/celle qui…)",
    category: "短语 / phrases (的字短语)",
    explanation: t(
      "Quand le nom est **évident**, on peut le supprimer et garder seulement **… + 的** : 红的 = « le rouge / celui qui est rouge », 我的 = « le mien », 新买的 = « celui que j'ai acheté récemment ».\n\nC'est l'équivalent de « celui / celle » en français ou de « the red one » en anglais.\n\nTrès utile en magasin : 我要**大的** (je prends le grand), 有没有**便宜一点儿的**？(Vous en avez un moins cher ?)",
      "When the noun is **obvious**, you can drop it and keep just **… + 的**: 红的 = \"the red one\", 我的 = \"mine\", 新买的 = \"the one I just bought\".\n\nIt's like \"the … one\" in English.\n\nVery useful in shops: 我要**大的** (I'll take the big one), 有没有**便宜一点儿的**？(Do you have a cheaper one?)",
    ),
    examples: [
      ex("你要红的还是黑的？", "Nǐ yào hóng de háishi hēi de?", "Tu veux le rouge ou le noir ?", "Do you want the red one or the black one?"),
      ex("有没有便宜一点儿的？", "Yǒu méiyǒu piányi yìdiǎnr de?", "Vous en avez un un peu moins cher ?", "Do you have a cheaper one?"),
      ex("这本书不是我的，是图书馆的。", "Zhè běn shū bú shì wǒ de, shì túshūguǎn de.", "Ce livre n'est pas à moi, il est à la bibliothèque.", "This book isn't mine, it's the library's."),
      ex("新买的比旧的好用多了。", "Xīn mǎi de bǐ jiù de hǎoyòng duō le.", "Le nouveau est bien plus pratique que l'ancien.", "The new one is much easier to use than the old one."),
    ],
    pitfalls: t(
      "✗ 我要红 → ✓ 我要红的.\n✗ 这是我 (pour « c'est le mien ») → ✓ 这是我的.",
      "✗ 我要红 → ✓ 我要红的.\n✗ 这是我 (for \"it's mine\") → ✓ 这是我的.",
    ),
  },
  {
    id: "hsk2-g65",
    level: 2,
    title: t("着 : état qui dure", "着: ongoing state"),
    pattern: "Verbe + 着 (+ Objet)",
    category: "动作的态 / aspect (持续)",
    explanation: t(
      "**着** (zhe) après un verbe indique un **état qui se maintient** après l'action : 穿**着**红衣服 = « portant des vêtements rouges », 门开**着** = « la porte est ouverte ».\n\nDifférence avec 在 : 他**在**穿衣服 = il est en train de s'habiller (action) ; 他穿**着**红衣服 = il porte des habits rouges (état).\n\nOn l'utilise beaucoup pour **décrire** quelqu'un : 戴着眼镜, 拿着包, 笑着说.\n\nNégation : **没** + V + 着 : 门没开着.",
      "**着** (zhe) after a verb marks a **state that continues** after the action: 穿**着**红衣服 = \"wearing red clothes\", 门开**着** = \"the door is open\".\n\nDifference with 在: 他**在**穿衣服 = he's getting dressed (action); 他穿**着**红衣服 = he's wearing red (state).\n\nIt's great for **describing** people: 戴着眼镜, 拿着包, 笑着说.\n\nNegative: **没** + V + 着: 门没开着.",
    ),
    examples: [
      ex("那个穿着白衬衫的人是我哥哥。", "Nàge chuānzhe bái chènshān de rén shì wǒ gēge.", "L'homme en chemise blanche, c'est mon grand frère.", "The man in the white shirt is my older brother."),
      ex("她戴着一副眼镜。", "Tā dàizhe yí fù yǎnjìng.", "Elle porte des lunettes.", "She's wearing glasses."),
      ex("门开着，你进来吧。", "Mén kāizhe, nǐ jìnlai ba.", "La porte est ouverte, entre.", "The door's open, come in."),
      ex("他笑着说：“没问题！”", "Tā xiàozhe shuō: “Méi wèntí!”", "Il a dit en souriant : « Pas de problème ! »", "He said with a smile: \"No problem!\""),
    ],
    pitfalls: t(
      "✗ 她戴眼镜着 → ✓ 她戴着眼镜 (着 juste après le verbe).\n✗ 门不开着 → ✓ 门没开着.",
      "✗ 她戴眼镜着 → ✓ 她戴着眼镜 (着 right after the verb).\n✗ 门不开着 → ✓ 门没开着.",
    ),
  },
  {
    id: "hsk2-g66",
    level: 2,
    title: t("Phrase d'existence : lieu + V着 + chose", "Existential sentence: place + V着 + thing"),
    pattern: "Lieu + Verbe + 着 + (数量) + Nom",
    category: "句型 / sentence patterns (存现句)",
    explanation: t(
      "Pour **décrire une scène** (« Sur le mur est accrochée une photo »), le chinois commence par le **lieu**, puis le verbe + 着, puis la chose : 墙上**挂着**一张照片.\n\nC'est une version plus précise de « lieu + 有 + chose » : au lieu de dire seulement « il y a », on dit **comment** la chose est là (posée 放着, accrochée 挂着, assise 坐着, debout 站着, écrite 写着).\n\nLa chose est souvent **indéfinie** (un, des) : 一张, 很多, 两个.",
      "To **describe a scene** (\"On the wall hangs a photo\"), Chinese starts with the **place**, then verb + 着, then the thing: 墙上**挂着**一张照片.\n\nIt's a more precise version of \"place + 有 + thing\": instead of just \"there is\", you say **how** it's there (placed 放着, hung 挂着, seated 坐着, standing 站着, written 写着).\n\nThe thing is usually **indefinite** (a, some): 一张, 很多, 两个.",
    ),
    examples: [
      ex("墙上挂着一张全家福。", "Qiáng shang guàzhe yì zhāng quánjiāfú.", "Au mur est accrochée une photo de famille.", "A family photo hangs on the wall."),
      ex("桌子上放着很多书。", "Zhuōzi shang fàngzhe hěn duō shū.", "Il y a plein de livres posés sur la table.", "There are lots of books on the table."),
      ex("门口站着一个高个子的男人。", "Ménkǒu zhànzhe yí ge gāo gèzi de nánrén.", "Un homme grand se tient à l'entrée.", "A tall man is standing at the door."),
      ex("本子上写着他的名字。", "Běnzi shang xiězhe tā de míngzi.", "Son nom est écrit sur le cahier.", "His name is written on the notebook."),
    ],
    pitfalls: t(
      "✗ 在墙上挂着一张照片 est possible, mais la forme de base commence sans 在 : ✓ 墙上挂着一张照片.\n✗ 一张照片挂着墙上 → ✓ 墙上挂着一张照片 (le lieu d'abord).",
      "在墙上挂着一张照片 is heard, but the basic form has no 在: ✓ 墙上挂着一张照片.\n✗ 一张照片挂着墙上 → ✓ 墙上挂着一张照片 (place first).",
    ),
  },
  {
    id: "hsk2-g67",
    level: 2,
    title: t("有的…有的… : certains… d'autres…", "有的…有的…: some… others…"),
    pattern: "有的 (+ Nom) + V1，有的 (+ Nom) + V2",
    category: "代词 / pronouns",
    explanation: t(
      "**有的** = « certains, quelques-uns ». En répétant **有的…有的…**, on répartit un groupe en sous-groupes : « certains…, d'autres… ».\n\n有的 se place **en tête** (en position de sujet), jamais après le verbe. Quand on parle d'un groupe connu, on peut commencer par ce groupe : 我的同事，有的…有的….\n\nOn peut ajouter **还有的** pour un troisième groupe.",
      "**有的** = \"some\". Repeating **有的…有的…** splits a group into sub-groups: \"some…, others…\".\n\n有的 goes **first** (as the subject), never after the verb. When talking about a known group, you can start with that group: 我的同事，有的…有的….\n\nAdd **还有的** for a third group.",
    ),
    examples: [
      ex("我的同事有的很高，有的很矮。", "Wǒ de tóngshì yǒude hěn gāo, yǒude hěn ǎi.", "Parmi mes collègues, certains sont grands, d'autres petits.", "Some of my colleagues are tall, some are short."),
      ex("有的人喜欢喝茶，有的人喜欢喝咖啡。", "Yǒude rén xǐhuan hē chá, yǒude rén xǐhuan hē kāfēi.", "Certains aiment le thé, d'autres le café.", "Some people like tea, others like coffee."),
      ex("周末，同学们有的去爬山，有的在家休息，还有的去打工。", "Zhōumò, tóngxuémen yǒude qù pá shān, yǒude zài jiā xiūxi, hái yǒude qù dǎgōng.", "Le week-end, certains camarades font de la randonnée, d'autres se reposent, d'autres encore vont travailler.", "At weekends, some classmates go hiking, some rest at home, and others go to part-time jobs."),
    ],
    pitfalls: t(
      "✗ 我喜欢有的菜 (pas faux mais maladroit) → ✓ 有的菜我喜欢，有的我不喜欢.\n✗ 有的人们 → ✓ 有的人 (pas de 们 après 有的 + nom).",
      "我喜欢有的菜 is clumsy → ✓ 有的菜我喜欢，有的我不喜欢.\n✗ 有的人们 → ✓ 有的人 (no 们 after 有的 + noun).",
    ),
  },
  {
    id: "hsk2-g68",
    level: 2,
    title: t("长得 + Adj et 怎么样 : décrire, évaluer", "长得 + Adj and 怎么样: describing and evaluating"),
    pattern: "Qqn + 长得 + (很) + Adj   /   … + 怎么样？",
    category: "代词 / pronouns (疑问 怎么样)",
    explanation: t(
      "**长得** (zhǎng de, litt. « a grandi de telle façon ») décrit l'**apparence physique** : 他**长得**很帅 (il est beau garçon), 她**长得**像妈妈 (elle ressemble à sa mère).\n\n**怎么样** demande une **évaluation ou un avis** : 他人**怎么样**？(Il est comment, comme personne ?), 他长得**怎么样**？(Il est comment physiquement ?). Il sert aussi à proposer : 我们明天去，**怎么样**？(On y va demain, ça te va ?).\n\nPour le caractère, on utilise 人 + adj : 他**人**很好 (il est gentil).",
      "**长得** (zhǎng de, lit. \"has grown in such a way\") describes **physical appearance**: 他**长得**很帅 (he's good-looking), 她**长得**像妈妈 (she looks like her mom).\n\n**怎么样** asks for an **evaluation or opinion**: 他人**怎么样**？(What's he like as a person?), 他长得**怎么样**？(What does he look like?). It also makes suggestions: 我们明天去，**怎么样**？(Let's go tomorrow — how's that?).\n\nFor personality, use 人 + adj: 他**人**很好 (he's a nice guy).",
    ),
    examples: [
      ex("你的新同事长得怎么样？", "Nǐ de xīn tóngshì zhǎng de zěnmeyàng?", "Il ressemble à quoi, ton nouveau collègue ?", "What does your new colleague look like?"),
      ex("她长得很漂亮，个子不高。", "Tā zhǎng de hěn piàoliang, gèzi bù gāo.", "Elle est très jolie, pas très grande.", "She's very pretty and not very tall."),
      ex("你长得跟你爸爸很像。", "Nǐ zhǎng de gēn nǐ bàba hěn xiàng.", "Tu ressembles beaucoup à ton père.", "You look a lot like your dad."),
      ex("他人怎么样？——人很好，也很热情。", "Tā rén zěnmeyàng? — Rén hěn hǎo, yě hěn rèqíng.", "Il est comment ? — Très gentil et très chaleureux.", "What's he like? — Very nice, and very warm."),
    ],
    pitfalls: t(
      "✗ 他长很帅 → ✓ 他长得很帅 (avec 得, lu zhǎng de).\n✗ 他怎么样长得？ → ✓ 他长得怎么样？",
      "✗ 他长很帅 → ✓ 他长得很帅 (with 得, read zhǎng de).\n✗ 他怎么样长得？ → ✓ 他长得怎么样？",
    ),
  },
  {
    id: "hsk2-g69",
    level: 2,
    title: t("Redoublement des adjectifs : 高高的, 干干净净", "Adjective reduplication: 高高的, 干干净净"),
    pattern: "AA + 的   /   AABB + 的",
    category: "形容词重叠 / adjective reduplication",
    explanation: t(
      "Redoubler un adjectif le rend plus **vivant et descriptif**, souvent affectueux : 大大的眼睛 (de grands yeux), 长长的头发 (de longs cheveux).\n\n1 syllabe : **AA + 的** (高高的, 红红的). 2 syllabes : **AABB** (干干净净, 高高兴兴, 漂漂亮亮).\n\nLe redoublement **contient déjà l'intensité** : on n'ajoute **ni 很, ni 非常**, et on ne le nie pas.",
      "Reduplicating an adjective makes it more **vivid and descriptive**, often affectionate: 大大的眼睛 (big eyes), 长长的头发 (long hair).\n\n1 syllable: **AA + 的** (高高的, 红红的). 2 syllables: **AABB** (干干净净, 高高兴兴, 漂漂亮亮).\n\nReduplication **already carries intensity**: add **no 很 or 非常**, and don't negate it.",
    ),
    examples: [
      ex("她有一双大大的眼睛。", "Tā yǒu yì shuāng dàdà de yǎnjing.", "Elle a de grands yeux.", "She has big eyes."),
      ex("我妹妹的头发长长的。", "Wǒ mèimei de tóufa chángcháng de.", "Ma petite sœur a de longs cheveux.", "My little sister's hair is long."),
      ex("孩子们高高兴兴地回家了。", "Háizimen gāogāoxìngxìng de huí jiā le.", "Les enfants sont rentrés à la maison tout contents.", "The kids went home happily."),
      ex("房间打扫得干干净净的。", "Fángjiān dǎsǎo de gāngānjìngjìng de.", "La chambre est nettoyée de fond en comble.", "The room has been cleaned spotless."),
    ],
    pitfalls: t(
      "✗ 很高高的 → ✓ 高高的.\n✗ 干净干净 → ✓ 干干净净 (AABB pour les adjectifs, ABAB pour les verbes).\n✗ 不高高的 → ✓ 不高.",
      "✗ 很高高的 → ✓ 高高的.\n✗ 干净干净 → ✓ 干干净净 (AABB for adjectives, ABAB for verbs).\n✗ 不高高的 → ✓ 不高.",
    ),
  },
  {
    id: "hsk2-g70",
    level: 2,
    title: t("过 : avoir déjà fait (expérience)", "过: have done before (experience)"),
    pattern: "Sujet + Verbe + 过 + (Objet)   /   没 + Verbe + 过",
    category: "动作的态 / aspect (经历)",
    explanation: t(
      "**过** (guo) après un verbe exprime une **expérience vécue** au moins une fois dans le passé : 我去**过**中国 = je suis déjà allé en Chine (ça fait partie de mon vécu).\n\nDifférence avec 了 : 我去**了**中国 = je suis allé en Chine (événement précis, je suis peut-être encore là-bas) ; 我去**过**中国 = j'y suis déjà allé (et j'en suis revenu).\n\nNégation : **没(有) + V + 过** (on garde 过 !) : 我**没**吃**过**北京烤鸭. Question : 你…过吗？/ 你…过没有？",
      "**过** (guo) after a verb expresses an **experience** you've had at least once: 我去**过**中国 = I've been to China (it's part of my life experience).\n\nDifference with 了: 我去**了**中国 = I went to China (a specific event; I may still be there); 我去**过**中国 = I've been to China (and came back).\n\nNegative: **没(有) + V + 过** (keep 过!): 我**没**吃**过**北京烤鸭. Question: 你…过吗？/ 你…过没有？",
    ),
    examples: [
      ex("你去过长城吗？", "Nǐ qùguo Chángchéng ma?", "Tu es déjà allé à la Grande Muraille ?", "Have you ever been to the Great Wall?"),
      ex("我吃过一次北京烤鸭。", "Wǒ chīguo yí cì Běijīng kǎoyā.", "J'ai mangé une fois du canard laqué.", "I've had Peking duck once."),
      ex("我从来没坐过高铁。", "Wǒ cónglái méi zuòguo gāotiě.", "Je n'ai jamais pris le TGV chinois.", "I've never taken the high-speed train."),
      ex("他以前学过两年中文。", "Tā yǐqián xuéguo liǎng nián Zhōngwén.", "Il a étudié le chinois pendant deux ans autrefois.", "He studied Chinese for two years in the past."),
    ],
    pitfalls: t(
      "✗ 我没去过了 → ✓ 我没去过.\n✗ 我没去 (= je n'y suis pas allé, cette fois) ≠ ✓ 我没去过 (= je n'y suis jamais allé).",
      "✗ 我没去过了 → ✓ 我没去过.\n我没去 (= I didn't go, this time) ≠ ✓ 我没去过 (= I've never been).",
    ),
  },
  {
    id: "hsk2-g71",
    level: 2,
    title: t("是…的 : insister sur les détails d'un fait passé", "是…的: stressing details of a past event"),
    pattern: "Sujet + (是) + quand / où / comment / avec qui + Verbe + 的",
    category: "句型 / sentence patterns (是…的)",
    explanation: t(
      "Quand on **sait déjà** qu'une action a eu lieu et qu'on veut parler d'un **détail** (quand ? où ? comment ? avec qui ?), on encadre ce détail avec **是…的**.\n\n你**是**什么时候来**的**？(Tu es arrivé quand ?) 我**是**坐飞机来**的** (je suis venu en avion).\n\n是 peut disparaître à l'affirmatif, mais **的 reste**. Négation : **不是…的** : 我不是一个人去的.\n\nAvec un objet, 的 se place souvent **avant** l'objet : 我是在北京学**的**中文.",
      "When you **already know** an action happened and want to talk about a **detail** (when? where? how? with whom?), frame that detail with **是…的**.\n\n你**是**什么时候来**的**？(When did you get here?) 我**是**坐飞机来**的** (I came by plane).\n\n是 can drop in affirmative sentences, but **的 stays**. Negative: **不是…的**: 我不是一个人去的.\n\nWith an object, 的 often goes **before** the object: 我是在北京学**的**中文.",
    ),
    examples: [
      ex("你是什么时候来中国的？", "Nǐ shì shénme shíhou lái Zhōngguó de?", "Tu es arrivé en Chine quand ?", "When did you come to China?"),
      ex("我是二〇一九年来的。", "Wǒ shì èr líng yī jiǔ nián lái de.", "Je suis arrivé en 2019.", "I came in 2019."),
      ex("我们是坐火车去的。", "Wǒmen shì zuò huǒchē qù de.", "On y est allés en train.", "We went by train."),
      ex("我不是一个人去的，是跟朋友一起去的。", "Wǒ bú shì yí ge rén qù de, shì gēn péngyou yìqǐ qù de.", "Je n'y suis pas allé seul, j'y suis allé avec des amis.", "I didn't go alone, I went with friends."),
      ex("你在哪儿学的中文？", "Nǐ zài nǎr xué de Zhōngwén?", "Où as-tu appris le chinois ?", "Where did you learn Chinese?"),
    ],
    pitfalls: t(
      "✗ 我是坐飞机来了 → ✓ 我是坐飞机来的 (是…的, pas 了).\n是…的 ne sert qu'au passé : ✗ 我明天是坐飞机去的.",
      "✗ 我是坐飞机来了 → ✓ 我是坐飞机来的 (是…的, not 了).\n是…的 is only for past events: ✗ 我明天是坐飞机去的.",
    ),
  },
  {
    id: "hsk2-g72",
    level: 2,
    title: t("了 d'accomplissement : V + 了 + quantité + objet", "Completion 了: V + 了 + amount + object"),
    pattern: "Sujet + Verbe + 了 + quantité + Nom   /   没 + Verbe",
    category: "动作的态 / aspect (完成)",
    explanation: t(
      "**了 après le verbe** indique qu'une action est **accomplie**. Quand l'objet porte une **quantité** ou une précision, la phrase peut s'arrêter là : 我买**了**两本书.\n\nSans quantité, une phrase comme ✗ 我买了书 sonne inachevée : il faut soit une quantité, soit un 了 final (我买书了), soit une suite (我买了书就回家了).\n\nNégation : **没(有) + V**, **sans 了** : 我没买.",
      "**了 after the verb** marks an action as **completed**. When the object carries a **quantity** or detail, the sentence can end there: 我买**了**两本书.\n\nWithout a quantity, ✗ 我买了书 sounds unfinished: add a quantity, a final 了 (我买书了), or a follow-up (我买了书就回家了).\n\nNegative: **没(有) + V**, **no 了**: 我没买.",
    ),
    examples: [
      ex("去年我去了三个国家。", "Qùnián wǒ qùle sān ge guójiā.", "L'année dernière, je suis allé dans trois pays.", "Last year I went to three countries."),
      ex("我在那儿拍了很多照片。", "Wǒ zài nàr pāile hěn duō zhàopiàn.", "J'ai pris plein de photos là-bas.", "I took lots of photos there."),
      ex("我下了课就去找你。", "Wǒ xiàle kè jiù qù zhǎo nǐ.", "Après le cours, je viens te voir.", "I'll come and find you after class."),
      ex("昨天我没去上班。", "Zuótiān wǒ méi qù shàngbān.", "Hier, je ne suis pas allé travailler.", "I didn't go to work yesterday."),
    ],
    pitfalls: t(
      "✗ 我没去了 → ✓ 我没去.\n✗ 我昨天买书了三本 → ✓ 我昨天买了三本书.\n了 n'est pas un « passé » : les habitudes passées n'en prennent pas : ✓ 我以前常常去那儿.",
      "✗ 我没去了 → ✓ 我没去.\n✗ 我昨天买书了三本 → ✓ 我昨天买了三本书.\n了 isn't a past tense: past habits don't take it: ✓ 我以前常常去那儿.",
    ),
  },
  {
    id: "hsk2-g73",
    level: 2,
    title: t("…以前 / …以后 : avant, après", "…以前 / …以后: before, after"),
    pattern: "Moment / Proposition + 以前 / 以后，Phrase principale",
    category: "名词 / nouns (时间)",
    explanation: t(
      "**以前** (avant) et **以后** (après) se placent **après** l'élément de temps, à l'inverse du français : 吃饭**以前** = avant de manger, 三年**以后** = trois ans plus tard, 毕业**以后** = après le diplôme.\n\nSeuls en tête de phrase, ils veulent dire « **autrefois** » et « **à l'avenir** » : **以前**我住在上海 (avant, j'habitais à Shanghai). **以后**我想去西藏 (plus tard, je voudrais aller au Tibet).\n\nVariantes courtes à l'écrit : 前 / 后 (三天后).",
      "**以前** (before) and **以后** (after) come **after** the time element — the reverse of English: 吃饭**以前** = before eating, 三年**以后** = three years later, 毕业**以后** = after graduating.\n\nAlone at the start of a sentence, they mean \"**in the past**\" and \"**in the future**\": **以前**我住在上海 (I used to live in Shanghai). **以后**我想去西藏 (someday I'd like to go to Tibet).\n\nShort written forms: 前 / 后 (三天后).",
    ),
    examples: [
      ex("来中国以前，我一句中文也不会说。", "Lái Zhōngguó yǐqián, wǒ yí jù Zhōngwén yě bú huì shuō.", "Avant de venir en Chine, je ne savais pas dire un mot de chinois.", "Before coming to China, I couldn't say a word of Chinese."),
      ex("大学毕业以后，我去了北京工作。", "Dàxué bìyè yǐhòu, wǒ qùle Běijīng gōngzuò.", "Après la fac, je suis allé travailler à Pékin.", "After graduating, I went to work in Beijing."),
      ex("以前我不喜欢吃辣的，现在很喜欢。", "Yǐqián wǒ bù xǐhuan chī là de, xiànzài hěn xǐhuan.", "Avant, je n'aimais pas les plats épicés ; maintenant j'adore.", "I didn't use to like spicy food; now I love it."),
      ex("三天以后，我们到了西安。", "Sān tiān yǐhòu, wǒmen dàole Xī'ān.", "Trois jours plus tard, nous sommes arrivés à Xi'an.", "Three days later, we arrived in Xi'an."),
    ],
    pitfalls: t(
      "✗ 以前吃饭 (pour « avant de manger ») → ✓ 吃饭以前.\n✗ 以后三年 → ✓ 三年以后.",
      "✗ 以前吃饭 (for \"before eating\") → ✓ 吃饭以前.\n✗ 以后三年 → ✓ 三年以后.",
    ),
  },
  {
    id: "hsk2-g74",
    level: 2,
    title: t("一…也/都 + 不/没 : pas un seul, pas du tout", "一…也/都 + 不/没: not a single, not at all"),
    pattern: "一 + 量 (+ Nom) + 也 / 都 + 不 / 没 + Verbe   /   一点儿也不 + Adj",
    category: "固定格式 / fixed patterns (强调否定)",
    explanation: t(
      "Pour une **négation totale** (« pas un seul », « pas du tout »), on met **一 + classificateur (+ nom)** devant le verbe, suivi de **也** ou **都** et de la négation.\n\n我**一次也没**去过 = je n'y suis pas allé une seule fois. 他**一句话都没**说 = il n'a pas dit un seul mot.\n\nAvec un adjectif : **一点儿也不 + adj** = pas du tout : 一点儿也不累 (pas fatigué du tout). Rappel : 一 devient yí devant un 4e ton (一次 yí cì) et yì devant les autres (一点儿 yìdiǎnr).",
      "For **total negation** (\"not a single\", \"not at all\"), put **一 + measure word (+ noun)** before the verb, then **也** or **都** and the negative.\n\n我**一次也没**去过 = I've never been there, not once. 他**一句话都没**说 = he didn't say a single word.\n\nWith an adjective: **一点儿也不 + adj** = not at all: 一点儿也不累 (not tired at all). Reminder: 一 becomes yí before a 4th tone (一次 yí cì) and yì before others (一点儿 yìdiǎnr).",
    ),
    examples: [
      ex("那个地方我一次也没去过。", "Nàge dìfang wǒ yí cì yě méi qùguo.", "Je ne suis jamais allé là-bas, pas une seule fois.", "I've never been there, not even once."),
      ex("爬了一天山，我一点儿也不累。", "Pále yì tiān shān, wǒ yìdiǎnr yě bú lèi.", "J'ai marché en montagne toute la journée et je ne suis pas du tout fatigué.", "I hiked all day and I'm not tired at all."),
      ex("他一句话都没说就走了。", "Tā yí jù huà dōu méi shuō jiù zǒu le.", "Il est parti sans dire un mot.", "He left without saying a word."),
      ex("那天我一分钱也没花。", "Nà tiān wǒ yì fēn qián yě méi huā.", "Ce jour-là, je n'ai pas dépensé un centime.", "I didn't spend a penny that day."),
    ],
    pitfalls: t(
      "✗ 我没去过一次 → ✓ 我一次也没去过 (la quantité avant le verbe).\n✗ 一点儿不累 (sans 也) → ✓ 一点儿也不累.",
      "✗ 我没去过一次 → ✓ 我一次也没去过 (amount before the verb).\n✗ 一点儿不累 (without 也) → ✓ 一点儿也不累.",
    ),
  },
];
