import type { Lesson } from "../../types";
import { P, choice, fill, listen, ln, match, order, t } from "./helpers";

export const lessonsA: Lesson[] = [
  // ───────────────────────── L01 — Renting ─────────────────────────
  {
    id: "hsk2-l01",
    level: 2,
    order: 1,
    title: t("Trouver un appartement", "Finding a Flat"),
    subtitle: t("Visiter un logement et négocier le loyer", "Viewing a place and negotiating the rent"),
    theme: "home",
    goals: [
      t("Décrire un logement : pièces, étage, meubles", "Describe a home: rooms, floor, furniture"),
      t("Situer des lieux avec 旁边, 对面, 里边…", "Locate places with 旁边, 对面, 里边…"),
      t("Dire si c'est près ou loin avec 离", "Say whether something is near or far with 离"),
      t("Se plaindre poliment et négocier avec 有点儿 / 一点儿", "Complain politely and bargain with 有点儿 / 一点儿"),
    ],
    dialogue: {
      context: t(
        "Marc, un Français qui vient d'arriver à Pékin, visite un appartement avec M. Li, le propriétaire.",
        "Marc, a Frenchman who just arrived in Beijing, is viewing a flat with Mr Li, the landlord.",
      ),
      lines: [
        ln("李先生", "你好，你是来看房子的吧？请进。", "Nǐ hǎo, nǐ shì lái kàn fángzi de ba? Qǐng jìn.", "Bonjour, vous venez pour la visite, c'est ça ? Entrez.", "Hello, you're here to see the flat, right? Come in."),
        ln("马克", "您好！这个房子一个月多少钱？", "Nín hǎo! Zhège fángzi yí ge yuè duōshao qián?", "Bonjour ! Le loyer est de combien par mois ?", "Hello! How much is it per month?"),
        ln("李先生", "四千五百块。有两间卧室、一个客厅，还有一个厨房。", "Sìqiān wǔbǎi kuài. Yǒu liǎng jiān wòshì, yí ge kètīng, hái yǒu yí ge chúfáng.", "4 500 yuans. Il y a deux chambres, un salon et une cuisine.", "4,500 yuan. There are two bedrooms, a living room and a kitchen."),
        ln("马克", "房间又大又干净，可是房租有点儿贵。", "Fángjiān yòu dà yòu gānjìng, kěshì fángzū yǒudiǎnr guì.", "Les pièces sont grandes et propres, mais le loyer est un peu cher.", "The rooms are big and clean, but the rent is a bit high."),
        ln("李先生", "这儿离地铁站很近，走路只要五分钟。", "Zhèr lí dìtiězhàn hěn jìn, zǒulù zhǐ yào wǔ fēnzhōng.", "C'est tout près du métro, cinq minutes à pied seulement.", "It's very close to the subway — only a five-minute walk."),
        ln("马克", "附近有超市吗？", "Fùjìn yǒu chāoshì ma?", "Il y a un supermarché dans le coin ?", "Is there a supermarket nearby?"),
        ln("李先生", "有，楼下就有一个。对面还有一个公园。", "Yǒu, lóu xià jiù yǒu yí ge. Duìmiàn hái yǒu yí ge gōngyuán.", "Oui, il y en a un juste en bas. Et il y a un parc en face.", "Yes, there's one right downstairs. And there's a park opposite."),
        ln("马克", "这是几层？有电梯吗？", "Zhè shì jǐ céng? Yǒu diàntī ma?", "On est à quel étage ? Il y a un ascenseur ?", "Which floor is this? Is there a lift?"),
        ln("李先生", "十二层，有电梯。你看，窗户外边就是公园。", "Shí'èr céng, yǒu diàntī. Nǐ kàn, chuānghu wàibian jiù shì gōngyuán.", "Douzième étage, avec ascenseur. Regardez, le parc est juste sous la fenêtre.", "Twelfth floor, with a lift. Look, the park is right outside the window."),
        ln("马克", "真不错！能便宜一点儿吗？", "Zhēn búcuò! Néng piányi yìdiǎnr ma?", "Pas mal du tout ! Vous pouvez baisser un peu ?", "Really nice! Could you make it a bit cheaper?"),
        ln("李先生", "四千三，不能再少了。", "Sìqiān sān, bù néng zài shǎo le.", "4 300, je ne peux pas descendre plus bas.", "4,300 — I can't go any lower."),
        ln("马克", "好，我租了！", "Hǎo, wǒ zū le!", "D'accord, je le prends !", "OK, I'll take it!"),
      ],
    },
    vocab: ["房子", "租", "房租", "卧室", "客厅", "厨房", "洗手间", "间", "层", "张", "床", "桌子", "椅子", "楼", "电梯", "附近", "旁边", "对面", "外边", "里边", "离", "近", "远", "干净", "安静", "又", "有点儿", "超市", "公园", "窗户", "便宜", "走路"],
    grammar: ["hsk2-g01", "hsk2-g02", "hsk2-g03", "hsk2-g04", "hsk2-g05"],
    culture: {
      title: t("Louer en Chine : « 押一付三 »", "Renting in China: \"押一付三\""),
      body: t(
        "En ville, la plupart des locations passent par une agence (**中介** zhōngjiè). La formule classique est **押一付三** : un mois de caution et trois mois de loyer payés d'avance — prévois donc quatre mois de loyer à l'arrivée.\n\nLes annonces indiquent la surface en m² (平米 píngmǐ) et la disposition : **两室一厅** = deux chambres + un salon. Les appartements se louent souvent **meublés**, et le paiement se fait presque toujours via WeChat Pay ou Alipay.\n\nAstuce : les étrangers doivent se **déclarer au commissariat** (住宿登记) dans les 24 heures après avoir emménagé — le propriétaire t'y accompagne souvent.",
        "In cities, most rentals go through an agency (**中介** zhōngjiè). The classic deal is **押一付三**: one month's deposit plus three months' rent up front — so budget four months' rent when you move in.\n\nListings give the size in m² (平米 píngmǐ) and the layout: **两室一厅** = two bedrooms + a living room. Flats are usually rented **furnished**, and payment is almost always via WeChat Pay or Alipay.\n\nTip: foreigners must **register with the local police** (住宿登记) within 24 hours of moving in — landlords often go with you.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Chez moi, c'est loin du métro.", "My place is far from the subway."), t("Chez moi, c'est tout près du métro.", "My place is very close to the subway."), t("Chez moi, c'est à côté du supermarché.", "My place is next to the supermarket."), t("Il y a un métro en face de chez moi.", "There's a subway station opposite my place.")], 1, { zh: "我家离地铁站很近。", pinyin: "Wǒ jiā lí dìtiězhàn hěn jìn." }),
      choice(P.correct, ["超市在旁边银行。", "旁边超市在银行。", "超市在银行旁边。", "超市银行在旁边。"], 2, { explain: t("Le mot de localisation se place après le nom : 银行旁边.", "The location word comes after the noun: 银行旁边.") }),
      fill(P.fill, "房间里有一", "床。", ["件", "张", "辆", "双"], 1, t("Il y a un lit dans la chambre.", "There's a bed in the room."), t("张 s'emploie pour les objets plats : lits, tables, billets.", "张 is for flat objects: beds, tables, tickets.")),
      fill(P.fill, "这个房子", "贵，能便宜一点儿吗？", ["一点儿", "有点儿", "得", "了"], 1, t("Ce logement est un peu cher, vous pouvez baisser un peu ?", "This place is a bit expensive, can you lower the price a bit?"), t("有点儿 se place avant l'adjectif pour se plaindre.", "有点儿 goes before the adjective to complain.")),
      fill(P.fill, "我家", "公司不太远。", ["从", "离", "在", "到"], 1, t("Chez moi, ce n'est pas très loin du bureau.", "My place isn't very far from the office.")),
      fill(P.fill, "客厅又大", "安静。", ["又", "也", "和", "很"], 0, t("Le salon est grand et calme.", "The living room is big and quiet.")),
      order(P.order, ["我家", "对面", "有", "一个", "公园"], t("Il y a un parc en face de chez moi.", "There's a park opposite my home.")),
      order(P.order, ["这儿", "离", "地铁站", "很", "近"], t("C'est tout près du métro.", "It's very close to the subway.")),
      listen("卧室里有一张床和一张桌子。", ["卧室里有两张床和一张桌子。", "客厅里有一张床和一张桌子。", "卧室里有一张床和一张桌子。", "卧室里有一张床和一把椅子。"], 2, t("Dans la chambre, il y a un lit et un bureau.", "In the bedroom there's a bed and a desk.")),
      listen("房租一个月四千三。", ["房租一个月四千三。", "房租一个月三千四。", "房租一个月四千五。", "房租一个月一千三。"], 0, t("Le loyer est de 4 300 par mois.", "The rent is 4,300 a month.")),
      match(P.match, [
        ["厨房", "chúfáng", "cuisine", "kitchen"],
        ["卧室", "wòshì", "chambre", "bedroom"],
        ["电梯", "diàntī", "ascenseur", "lift / elevator"],
        ["窗户", "chuānghu", "fenêtre", "window"],
        ["对面", "duìmiàn", "en face", "opposite"],
      ]),
      choice(t("Comment demander poliment une petite baisse de prix ?", "How do you politely ask for a small discount?"), ["能便宜一点儿吗？", "能有点儿便宜吗？", "能便宜有点儿吗？", "能一点儿便宜吗？"], 0, { explain: t("Pour demander « un peu plus… », on met 一点儿 après l'adjectif.", "To ask for \"a bit more…\", put 一点儿 after the adjective.") }),
    ],
  },

  // ───────────────────────── L02 — Doctor ─────────────────────────
  {
    id: "hsk2-l02",
    level: 2,
    order: 2,
    title: t("Chez le médecin", "At the Doctor's"),
    subtitle: t("Décrire ses symptômes et comprendre les conseils", "Describing symptoms and understanding advice"),
    theme: "health",
    goals: [
      t("Dire où on a mal et depuis combien de temps", "Say where it hurts and for how long"),
      t("Comprendre une obligation (得) et un conseil (应该)", "Understand an obligation (得) and advice (应该)"),
      t("Donner et recevoir des interdictions avec 别", "Give and understand warnings with 别"),
      t("Exprimer une possibilité avec 可能", "Express possibility with 可能"),
    ],
    dialogue: {
      context: t(
        "Anna ne se sent pas bien depuis deux jours. Elle consulte un médecin dans un hôpital de quartier.",
        "Anna hasn't felt well for two days. She sees a doctor at a local hospital.",
      ),
      lines: [
        ln("医生", "请坐。你哪儿不舒服？", "Qǐng zuò. Nǐ nǎr bù shūfu?", "Asseyez-vous. Qu'est-ce qui ne va pas ?", "Have a seat. What seems to be the problem?"),
        ln("安娜", "我头疼，还有点儿发烧。", "Wǒ tóu téng, hái yǒudiǎnr fāshāo.", "J'ai mal à la tête, et un peu de fièvre.", "I have a headache and a bit of a fever."),
        ln("医生", "疼了几天了？", "Téngle jǐ tiān le?", "Depuis combien de jours ?", "How many days has it been hurting?"),
        ln("安娜", "两天了。昨天晚上三十八度五。", "Liǎng tiān le. Zuótiān wǎnshang sānshíbā dù wǔ.", "Deux jours. Hier soir, j'avais 38,5.", "Two days. Last night I had 38.5."),
        ln("医生", "我给你检查一下。……你可能感冒了，不太严重。", "Wǒ gěi nǐ jiǎnchá yíxià. …… Nǐ kěnéng gǎnmào le, bú tài yánzhòng.", "Je vais vous examiner… Vous avez sans doute attrapé un rhume, ce n'est pas bien grave.", "Let me examine you… You've probably caught a cold, it's not serious."),
        ln("安娜", "我得吃药吗？", "Wǒ děi chī yào ma?", "Je dois prendre des médicaments ?", "Do I need to take medicine?"),
        ln("医生", "得吃。这个药一天吃三次，饭后吃。", "Děi chī. Zhège yào yì tiān chī sān cì, fàn hòu chī.", "Oui. Ce médicament, trois fois par jour, après les repas.", "Yes. Take this three times a day, after meals."),
        ln("安娜", "我明天能去上班吗？", "Wǒ míngtiān néng qù shàngbān ma?", "Je peux aller travailler demain ?", "Can I go to work tomorrow?"),
        ln("医生", "你应该在家休息两天。多喝热水，别喝冰水。", "Nǐ yīnggāi zài jiā xiūxi liǎng tiān. Duō hē rè shuǐ, bié hē bīngshuǐ.", "Vous devriez vous reposer deux jours chez vous. Buvez beaucoup d'eau chaude, pas d'eau glacée.", "You should rest at home for two days. Drink lots of hot water, no iced water."),
        ln("安娜", "好的。要打针吗？", "Hǎo de. Yào dǎzhēn ma?", "D'accord. Il faut une piqûre ?", "OK. Do I need an injection?"),
        ln("医生", "不用。如果后天还发烧，你再来医院。", "Búyòng. Rúguǒ hòutiān hái fāshāo, nǐ zài lái yīyuàn.", "Pas besoin. Si vous avez encore de la fièvre après-demain, revenez.", "No need. If you still have a fever the day after tomorrow, come back."),
        ln("安娜", "谢谢医生！", "Xièxie yīshēng!", "Merci docteur !", "Thank you, doctor!"),
      ],
    },
    vocab: ["医院", "医生", "病", "生病", "舒服", "头", "疼", "发烧", "感冒", "检查", "药", "吃药", "休息", "严重", "身体", "眼睛", "肚子", "次", "得", "应该", "别", "可能", "热", "冰", "担心", "打针", "不用", "后天", "饭后"],
    grammar: ["hsk2-g06", "hsk2-g07", "hsk2-g08", "hsk2-g09", "hsk2-g10"],
    culture: {
      title: t("« Bois de l'eau chaude ! » (多喝热水)", "\"Drink hot water!\" (多喝热水)"),
      body: t(
        "En Chine, on va souvent **directement à l'hôpital**, même pour un rhume : il n'y a pas vraiment de médecin généraliste de quartier comme en France. On commence par **挂号** (guàhào, s'enregistrer et choisir le service), souvent sur une appli, puis on attend son tour.\n\nLe conseil universel, c'est **多喝热水** — « bois beaucoup d'eau chaude ». Selon la médecine traditionnelle chinoise, le froid (eau glacée, climatisation) affaiblit le corps. La phrase est tellement fréquente qu'elle est devenue un mème sur les réseaux !\n\nLa **médecine chinoise** (中医 zhōngyī) coexiste avec la médecine occidentale (西医 xīyī) : beaucoup d'hôpitaux proposent les deux.",
        "In China people often go **straight to the hospital**, even for a cold: there isn't really a neighbourhood GP system like in the West. First you **挂号** (guàhào, register and choose a department), often via an app, then wait your turn.\n\nThe universal advice is **多喝热水** — \"drink plenty of hot water\". According to traditional Chinese medicine, cold (iced drinks, air-con) weakens the body. The phrase is so common it has become an online meme!\n\n**Traditional Chinese medicine** (中医 zhōngyī) coexists with Western medicine (西医 xīyī): many hospitals offer both.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Tu devrais te reposer à la maison.", "You should rest at home."), t("Tu dois aller à l'hôpital.", "You must go to the hospital."), t("Ne te repose pas à la maison.", "Don't rest at home."), t("Tu t'es peut-être reposé à la maison.", "You may have rested at home.")], 0, { zh: "你应该在家休息。", pinyin: "Nǐ yīnggāi zài jiā xiūxi." }),
      choice(t("Comment dit-on « Tu n'as pas besoin de prendre de médicament » ?", "How do you say \"You don't need to take medicine\"?"), ["你不得吃药。", "你别得吃药。", "你不用吃药。", "你没得吃药。"], 2, { explain: t("La négation de 得 (děi) est 不用, jamais 不得.", "The negative of 得 (děi) is 不用, never 不得.") }),
      choice(P.correct, ["我三天头疼了。", "我头疼了三天了。", "我头疼三天了了。", "我了头疼三天。"], 1, { explain: t("La durée se place après le verbe ; le 了 final montre que ça continue.", "Duration goes after the verb; final 了 shows it's still going on.") }),
      fill(P.fill, "你发烧了，", "去医院。", ["得", "过", "着", "的"], 0, t("Tu as de la fièvre, il faut aller à l'hôpital.", "You have a fever, you need to go to the hospital.")),
      fill(P.fill, "", "喝冰水，多喝热水。", ["别", "得", "应该", "可能"], 0, t("Ne bois pas d'eau glacée, bois beaucoup d'eau chaude.", "Don't drink iced water, drink lots of hot water.")),
      fill(P.fill, "明天", "下雨，你带伞吧。", ["可以", "可能", "正在", "已经"], 1, t("Il va peut-être pleuvoir demain, prends un parapluie.", "It might rain tomorrow, take an umbrella."), t("可能 = possibilité ; 可以 = permission.", "可能 = possibility; 可以 = permission.")),
      order(P.order, ["这个药", "一天", "吃", "三次"], t("Ce médicament se prend trois fois par jour.", "Take this medicine three times a day.")),
      order(P.order, ["你", "应该", "多", "休息"], t("Tu devrais te reposer davantage.", "You should rest more.")),
      listen("我头疼，还有点儿发烧。", ["我头疼，还有点儿发烧。", "我肚子疼，还有点儿发烧。", "我头疼，没有发烧。", "我眼睛疼，还有点儿发烧。"], 0, t("J'ai mal à la tête et un peu de fièvre.", "I have a headache and a slight fever.")),
      listen("你可能感冒了，别担心。", ["你感冒了，很严重。", "你可能发烧了，别担心。", "你别感冒了。", "你可能感冒了，别担心。"], 3, t("Tu as sans doute un rhume, ne t'inquiète pas.", "You've probably got a cold, don't worry.")),
      match(P.match, [
        ["发烧", "fāshāo", "avoir de la fièvre", "have a fever"],
        ["感冒", "gǎnmào", "rhume ; s'enrhumer", "cold; catch a cold"],
        ["检查", "jiǎnchá", "examiner", "examine"],
        ["药", "yào", "médicament", "medicine"],
        ["疼", "téng", "avoir mal", "hurt"],
      ]),
      choice(t("Le médecin dit : 别担心。 Qu'est-ce que ça veut dire ?", "The doctor says 别担心. What does it mean?"), [t("Il faut s'inquiéter.", "You should worry."), t("Ne t'inquiète pas.", "Don't worry."), t("Tu t'inquiètes peut-être.", "You may be worried."), t("Je ne suis pas inquiet.", "I'm not worried.")], 1),
    ],
  },

  // ───────────────────────── L03 — Travel planning ─────────────────────────
  {
    id: "hsk2-l03",
    level: 2,
    order: 3,
    title: t("Préparer un voyage", "Planning a Trip"),
    subtitle: t("Itinéraire, transports et réservations", "Itinerary, transport and bookings"),
    theme: "travel",
    goals: [
      t("Organiser des étapes avec 先…然后…", "Sequence steps with 先…然后…"),
      t("Indiquer un trajet avec 从…到…", "Describe a route with 从…到…"),
      t("Choisir entre deux options avec 还是 / 或者", "Choose between options with 还是 / 或者"),
      t("Dire comment on voyage : 坐高铁去, 骑车去…", "Say how you travel: 坐高铁去, 骑车去…"),
    ],
    dialogue: {
      context: t(
        "Xiao Lin et Marc, deux collègues, préparent un voyage pour la « semaine dorée » de la Fête nationale.",
        "Xiao Lin and Marc, two colleagues, are planning a trip for the National Day \"Golden Week\".",
      ),
      lines: [
        ln("小林", "国庆节放七天假，你有什么打算？", "Guóqìng Jié fàng qī tiān jià, nǐ yǒu shénme dǎsuàn?", "On a sept jours de congé pour la Fête nationale. Tu as des projets ?", "We get seven days off for National Day. Any plans?"),
        ln("马克", "我想去旅游，可是还没想好去哪儿。", "Wǒ xiǎng qù lǚyóu, kěshì hái méi xiǎnghǎo qù nǎr.", "J'aimerais voyager, mais je ne sais pas encore où.", "I want to travel, but I haven't decided where yet."),
        ln("小林", "我们一起去吧！先去西安，然后去成都。", "Wǒmen yìqǐ qù ba! Xiān qù Xī'ān, ránhòu qù Chéngdū.", "Partons ensemble ! D'abord Xi'an, ensuite Chengdu.", "Let's go together! Xi'an first, then Chengdu."),
        ln("马克", "好主意！我们坐飞机去还是坐高铁去？", "Hǎo zhǔyi! Wǒmen zuò fēijī qù háishi zuò gāotiě qù?", "Bonne idée ! On y va en avion ou en TGV ?", "Good idea! Shall we fly or take the high-speed train?"),
        ln("小林", "坐高铁吧。从北京到西安只要四个多小时。", "Zuò gāotiě ba. Cóng Běijīng dào Xī'ān zhǐ yào sì ge duō xiǎoshí.", "En TGV. De Pékin à Xi'an, ça ne prend qu'un peu plus de quatre heures.", "Let's take the train. Beijing to Xi'an is only a bit over four hours."),
        ln("马克", "那从西安到成都呢？", "Nà cóng Xī'ān dào Chéngdū ne?", "Et de Xi'an à Chengdu ?", "And from Xi'an to Chengdu?"),
        ln("小林", "坐高铁或者坐飞机都很方便。", "Zuò gāotiě huòzhě zuò fēijī dōu hěn fāngbiàn.", "Le TGV ou l'avion, les deux sont pratiques.", "Either the train or a plane — both are convenient."),
        ln("马克", "我们几号出发？", "Wǒmen jǐ hào chūfā?", "On part le combien ?", "What date do we leave?"),
        ln("小林", "一号早上出发，六号回来。", "Yī hào zǎoshang chūfā, liù hào huílai.", "On part le 1er au matin et on rentre le 6.", "We leave on the morning of the 1st and come back on the 6th."),
        ln("马克", "国庆节人很多，我们得早点儿买票。", "Guóqìng Jié rén hěn duō, wǒmen děi zǎo diǎnr mǎi piào.", "Il y a beaucoup de monde pendant la Fête nationale, il faut acheter les billets tôt.", "It's really crowded at National Day, we need to buy tickets early."),
        ln("小林", "对！我先在网上买票，然后再订酒店。", "Duì! Wǒ xiān zài wǎng shang mǎi piào, ránhòu zài dìng jiǔdiàn.", "Exactement ! J'achète d'abord les billets en ligne, puis je réserve l'hôtel.", "Right! I'll buy the tickets online first, then book the hotel."),
        ln("马克", "太好了，我去准备护照和行李箱！", "Tài hǎo le, wǒ qù zhǔnbèi hùzhào hé xínglixiāng!", "Super, je vais préparer mon passeport et ma valise !", "Great, I'll go get my passport and suitcase ready!"),
      ],
    },
    vocab: ["旅游", "打算", "放假", "出发", "回来", "先", "然后", "从", "到", "高铁", "飞机", "火车", "机场", "火车站", "票", "订", "酒店", "护照", "行李箱", "方便", "或者", "还是", "坐", "骑", "开车", "自行车", "地图", "准备", "主意", "网上"],
    grammar: ["hsk2-g11", "hsk2-g12", "hsk2-g13", "hsk2-g14"],
    culture: {
      title: t("La « semaine dorée » (黄金周)", "\"Golden Week\" (黄金周)"),
      body: t(
        "Deux fois par an, la Chine s'arrête presque entièrement : pour la **fête du Printemps** (janvier-février) et pour la **Fête nationale** (国庆节, du 1er au 7 octobre). On appelle ces congés la **« semaine dorée »** (黄金周).\n\nDes centaines de millions de personnes voyagent en même temps : les sites touristiques sont bondés et les billets partent en quelques minutes. Pour le train, on réserve sur l'appli officielle **12306** — les étrangers peuvent s'inscrire avec leur passeport, qu'il faut montrer à l'embarquement.\n\nLe réseau de **TGV chinois** (高铁 gāotiě) est le plus grand du monde : plus de 45 000 km, souvent plus pratique que l'avion entre grandes villes.",
        "Twice a year China almost shuts down: for **Spring Festival** (Jan–Feb) and for **National Day** (国庆节, 1–7 October). These holidays are called **\"Golden Week\"** (黄金周).\n\nHundreds of millions of people travel at once: sights are packed and tickets sell out in minutes. For trains, book on the official **12306** app — foreigners can register with their passport, which you show when boarding.\n\nChina's **high-speed rail** (高铁 gāotiě) network is the world's largest — over 45,000 km, and often handier than flying between big cities.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("On va à Xi'an en avion.", "We're flying to Xi'an."), t("On va d'abord à Xi'an, puis à Chengdu.", "We go to Xi'an first, then Chengdu."), t("On va de Xi'an à Chengdu en train.", "We're taking the train from Xi'an to Chengdu."), t("On va à Chengdu ou à Xi'an.", "We're going to Chengdu or Xi'an.")], 1, { zh: "我们先去西安，然后去成都。", pinyin: "Wǒmen xiān qù Xī'ān, ránhòu qù Chéngdū." }),
      choice(P.correct, ["你喝茶或者咖啡？", "你喝茶还是咖啡吗？", "你喝茶还是咖啡？", "你喝茶或者咖啡吗还是？"], 2, { explain: t("Dans une question à choix, on utilise 还是, sans 吗.", "In a choice question use 还是, with no 吗.") }),
      choice(P.correct, ["我去上班骑自行车。", "我骑自行车去上班。", "我坐自行车去上班。", "我去骑自行车上班。"], 1, { explain: t("Le moyen de transport vient avant le déplacement, et on « enfourche » (骑) un vélo.", "The means comes before the movement, and you \"ride\" (骑) a bike.") }),
      fill(P.fill, "", "北京到上海坐高铁要五个小时。", ["从", "离", "在", "往"], 0, t("De Pékin à Shanghai, il faut cinq heures en TGV.", "It takes five hours from Beijing to Shanghai by high-speed train.")),
      fill(P.fill, "周六", "周日出发都可以。", ["还是", "或者", "然后", "从"], 1, t("On peut partir samedi ou dimanche.", "We can leave on Saturday or Sunday."), t("Affirmation → 或者 ; question → 还是.", "Statement → 或者; question → 还是.")),
      fill(P.fill, "我先买票，", "订酒店。", ["然后", "或者", "还是", "从"], 0, t("J'achète d'abord les billets, puis je réserve l'hôtel.", "I'll buy the tickets first, then book the hotel.")),
      order(P.order, ["我们", "坐", "高铁", "去", "西安"], t("On va à Xi'an en TGV.", "We're going to Xi'an by high-speed train.")),
      order(P.order, ["我", "从九点", "到五点", "上班"], t("Je travaille de 9 h à 17 h.", "I work from nine to five.")),
      listen("我们一号早上出发，六号回来。", ["我们一号晚上出发，六号回来。", "我们六号早上出发，一号回来。", "我们一号早上出发，六号回来。", "我们一号早上出发，七号回来。"], 2, t("On part le 1er au matin et on rentre le 6.", "We leave on the morning of the 1st and return on the 6th.")),
      listen("你打算怎么去机场？", ["你打算怎么去机场？", "你打算几点去机场？", "你打算怎么去火车站？", "你什么时候去机场？"], 0, t("Comment comptes-tu aller à l'aéroport ?", "How are you planning to get to the airport?")),
      match(P.match, [
        ["护照", "hùzhào", "passeport", "passport"],
        ["出发", "chūfā", "partir", "set off"],
        ["订", "dìng", "réserver", "book"],
        ["行李箱", "xínglixiāng", "valise", "suitcase"],
        ["方便", "fāngbiàn", "pratique", "convenient"],
      ]),
      choice(t("Tu veux demander à un ami s'il préfère la mer ou la montagne. Tu dis :", "You want to ask a friend whether they prefer the sea or the mountains. You say:"), ["你想去海边或者山上？", "你想去海边还是山上？", "你想去海边和山上吗？", "你想去海边然后山上？"], 1),
    ],
  },

  // ───────────────────────── L04 — Restaurant ─────────────────────────
  {
    id: "hsk2-l04",
    level: 2,
    order: 4,
    title: t("Au restaurant", "At the Restaurant"),
    subtitle: t("Commander, réagir et payer l'addition", "Ordering, reacting and paying the bill"),
    theme: "food",
    goals: [
      t("Commander plusieurs plats et boissons", "Order several dishes and drinks"),
      t("Demander quelque chose au serveur avec 给", "Ask the waiter for things with 给"),
      t("Réagir avec 太…了 et 真…", "React with 太…了 and 真…"),
      t("Comprendre le total et payer (一共, 只, 还)", "Understand the total and pay (一共, 只, 还)"),
    ],
    dialogue: {
      context: t(
        "Wang Li emmène Marc dans un restaurant du Sichuan près de leur bureau.",
        "Wang Li takes Marc to a Sichuan restaurant near their office.",
      ),
      lines: [
        ln("服务员", "欢迎光临！几位？", "Huānyíng guānglín! Jǐ wèi?", "Bienvenue ! Vous êtes combien ?", "Welcome! How many?"),
        ln("王丽", "两位。请给我们拿一下菜单。", "Liǎng wèi. Qǐng gěi wǒmen ná yíxià càidān.", "Deux. Vous pouvez nous apporter la carte ?", "Two. Could you bring us the menu, please?"),
        ln("服务员", "好的，这是菜单。你们想吃什么？", "Hǎo de, zhè shì càidān. Nǐmen xiǎng chī shénme?", "Voici la carte. Qu'est-ce que vous prenez ?", "Here's the menu. What would you like?"),
        ln("马克", "你们这儿什么菜最有名？", "Nǐmen zhèr shénme cài zuì yǒumíng?", "Quel est votre plat le plus connu ?", "What's your most famous dish?"),
        ln("服务员", "我们的鱼特别好吃，宫保鸡丁也不错。", "Wǒmen de yú tèbié hǎochī, gōngbǎo jīdīng yě búcuò.", "Notre poisson est excellent, et le poulet Gongbao est très bon aussi.", "Our fish is especially good, and the kung pao chicken is great too."),
        ln("王丽", "那我们要一个鱼、一个宫保鸡丁，还要两碗米饭。", "Nà wǒmen yào yí ge yú, yí ge gōngbǎo jīdīng, hái yào liǎng wǎn mǐfàn.", "Alors un poisson, un poulet Gongbao, et aussi deux bols de riz.", "Then we'll have a fish, a kung pao chicken, and two bowls of rice."),
        ln("服务员", "还要别的吗？喝点儿什么？", "Hái yào bié de ma? Hē diǎnr shénme?", "Autre chose ? Qu'est-ce que vous buvez ?", "Anything else? Something to drink?"),
        ln("马克", "给我一瓶啤酒。她只要一杯茶。", "Gěi wǒ yì píng píjiǔ. Tā zhǐ yào yì bēi chá.", "Une bière pour moi. Elle, juste un thé.", "A bottle of beer for me. She'll just have a tea."),
        ln("马克", "这个鱼太好吃了！就是有点儿辣。", "Zhège yú tài hǎochī le! Jiùshì yǒudiǎnr là.", "Ce poisson est délicieux ! Juste un peu épicé.", "This fish is so good! Just a little spicy."),
        ln("王丽", "服务员，买单！", "Fúwùyuán, mǎidān!", "L'addition, s'il vous plaît !", "Excuse me, the bill please!"),
        ln("服务员", "一共一百三十八块。扫这个码就可以。", "Yígòng yìbǎi sānshíbā kuài. Sǎo zhège mǎ jiù kěyǐ.", "Ça fait 138 yuans en tout. Vous pouvez scanner ce code.", "That's 138 yuan in total. Just scan this code."),
        ln("王丽", "马克，今天我请你！", "Mǎkè, jīntiān wǒ qǐng nǐ!", "Marc, aujourd'hui c'est moi qui t'invite !", "Marc, today it's my treat!"),
      ],
    },
    vocab: ["饭馆", "服务员", "菜单", "菜", "点菜", "鱼", "鸡", "米饭", "碗", "盘子", "筷子", "瓶", "杯", "啤酒", "茶", "辣", "甜", "好吃", "饿", "饱", "有名", "一共", "只", "还", "给", "买单", "别的", "味道", "请", "特别"],
    grammar: ["hsk2-g15", "hsk2-g16", "hsk2-g17", "hsk2-g18", "hsk2-g19"],
    culture: {
      title: t("Qui paie l'addition ?", "Who pays the bill?"),
      body: t(
        "En Chine, on partage rarement l'addition (AA制 existe entre jeunes, mais reste moins courant qu'en France). Le plus souvent, **une personne invite** — et on se bat parfois littéralement pour payer (**抢着买单**) ! C'est une question de **face** (面子) et de relation : la prochaine fois, ce sera à l'autre d'inviter.\n\nLes plats sont posés **au centre** et **tout le monde partage** avec ses baguettes. On commande en général un plat de plus que le nombre de convives.\n\nOn paie presque toujours en **scannant un QR code** (扫码) avec WeChat ou Alipay. Pas de pourboire : ce n'est pas l'usage.",
        "In China people rarely split the bill (AA制 exists among young people, but is less common than in the West). Usually **one person pays** — and people sometimes literally fight to pay (**抢着买单**)! It's about **face** (面子) and relationships: next time, it's the other person's turn.\n\nDishes are placed **in the middle** and **everyone shares** with their chopsticks. The rule of thumb is to order one dish more than the number of diners.\n\nPayment is almost always by **scanning a QR code** (扫码) with WeChat or Alipay. No tipping: it isn't customary.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Ça fait 138 yuans en tout.", "That's 138 yuan in total."), t("Ça fait 183 yuans en tout.", "That's 183 yuan in total."), t("Il n'y a que 138 yuans.", "There's only 138 yuan."), t("Encore 138 yuans.", "Another 138 yuan.")], 0, { zh: "一共一百三十八块。", pinyin: "Yígòng yìbǎi sānshíbā kuài." }),
      choice(P.correct, ["请拿菜单给我们。", "请给我们拿菜单。", "请我们给拿菜单。", "请拿给菜单我们。"], 1, { explain: t("给 + personne se place avant le verbe.", "给 + person goes before the verb.") }),
      choice(P.correct, ["他送一本书我。", "他送给一本书我。", "他送我一本书。", "他一本书送我。"], 2, { explain: t("Double objet : personne d'abord, chose ensuite.", "Double object: person first, then the thing.") }),
      fill(P.fill, "这个菜太好吃", "！", ["了", "的", "吗", "过"], 0, t("Ce plat est délicieux !", "This dish is so good!")),
      fill(P.fill, "我们要两碗米饭，", "要一瓶啤酒。", ["还", "只", "一共", "都"], 0, t("On prend deux bols de riz, et aussi une bière.", "We'll have two bowls of rice, and a beer too.")),
      fill(P.fill, "我不太饿，", "要一碗面条。", ["一共", "还", "只", "都"], 2, t("Je n'ai pas très faim, je prends juste un bol de nouilles.", "I'm not very hungry, just a bowl of noodles for me.")),
      order(P.order, ["服务员", "请", "给我", "一杯", "茶"], t("S'il vous plaît, un thé pour moi.", "Excuse me, a cup of tea for me please.")),
      order(P.order, ["我们", "一共", "五个", "人"], t("Nous sommes cinq en tout.", "There are five of us altogether.")),
      listen("还要别的吗？", ["还要米饭吗？", "还要别的吗？", "还有别的吗？", "要不要别的？"], 1, t("Vous désirez autre chose ?", "Anything else?")),
      listen("这个鱼有点儿辣。", ["这个鱼有点儿甜。", "这个鱼一点儿也不辣。", "这个鸡有点儿辣。", "这个鱼有点儿辣。"], 3, t("Ce poisson est un peu épicé.", "This fish is a bit spicy.")),
      match(P.match, [
        ["菜单", "càidān", "carte, menu", "menu"],
        ["筷子", "kuàizi", "baguettes", "chopsticks"],
        ["辣", "là", "épicé", "spicy"],
        ["买单", "mǎidān", "payer l'addition", "pay the bill"],
        ["饱", "bǎo", "rassasié", "full"],
        ["碗", "wǎn", "bol", "bowl"],
      ]),
      choice(t("Tu veux inviter ton ami au restaurant. Tu dis :", "You want to treat your friend to dinner. You say:"), ["今天你请我！", "今天我请你！", "今天我们请！", "今天请我你！"], 1),
    ],
  },

  // ───────────────────────── L05 — Sports ─────────────────────────
  {
    id: "hsk2-l05",
    level: 2,
    order: 5,
    title: t("Le sport et moi", "Sport and Me"),
    subtitle: t("Parler de ses habitudes sportives et de son niveau", "Talking about your exercise habits and skill level"),
    theme: "hobbies",
    goals: [
      t("Dire à quelle fréquence on fait du sport", "Say how often you exercise"),
      t("Évaluer une performance avec V + 得 + Adj", "Evaluate performance with V + 得 + Adj"),
      t("Distinguer 会, 能 et 可以", "Tell 会, 能 and 可以 apart"),
      t("Parler d'habitudes avec 每…都…", "Talk about routines with 每…都…"),
    ],
    dialogue: {
      context: t(
        "À la pause, Xiao Zhang et Anna parlent de sport.",
        "During a break, Xiao Zhang and Anna chat about sport.",
      ),
      lines: [
        ln("小张", "安娜，你平时喜欢做什么运动？", "Ānnà, nǐ píngshí xǐhuan zuò shénme yùndòng?", "Anna, quel sport tu fais d'habitude ?", "Anna, what sports do you usually do?"),
        ln("安娜", "我经常跑步，有时候也去游泳。你呢？", "Wǒ jīngcháng pǎobù, yǒu shíhou yě qù yóuyǒng. Nǐ ne?", "Je cours souvent, et parfois je vais nager. Et toi ?", "I often go running, and sometimes swimming. You?"),
        ln("小张", "我喜欢打篮球，每个周末都跟朋友一起打。", "Wǒ xǐhuan dǎ lánqiú, měi ge zhōumò dōu gēn péngyou yìqǐ dǎ.", "Moi j'aime le basket, j'y joue avec des amis tous les week-ends.", "I like basketball — I play with friends every weekend."),
        ln("安娜", "你打得怎么样？", "Nǐ dǎ de zěnmeyàng?", "Tu joues bien ?", "How good are you?"),
        ln("小张", "还可以，可是我跑得不快。", "Hái kěyǐ, kěshì wǒ pǎo de bú kuài.", "Pas mal, mais je ne cours pas vite.", "Not bad, but I'm not a fast runner."),
        ln("安娜", "我每天早上都跑五公里。", "Wǒ měi tiān zǎoshang dōu pǎo wǔ gōnglǐ.", "Moi, je cours cinq kilomètres tous les matins.", "I run five kilometres every morning."),
        ln("小张", "真厉害！你跑步跑得快吗？", "Zhēn lìhai! Nǐ pǎobù pǎo de kuài ma?", "Impressionnant ! Tu cours vite ?", "Impressive! Are you fast?"),
        ln("安娜", "不太快，但是我能跑很长时间。", "Bú tài kuài, dànshì wǒ néng pǎo hěn cháng shíjiān.", "Pas très, mais je peux courir longtemps.", "Not very, but I can run for a long time."),
        ln("小张", "你会打乒乓球吗？", "Nǐ huì dǎ pīngpāngqiú ma?", "Tu sais jouer au ping-pong ?", "Can you play table tennis?"),
        ln("安娜", "会一点儿，可是打得不好。", "Huì yìdiǎnr, kěshì dǎ de bù hǎo.", "Un peu, mais je ne joue pas bien.", "A little, but I'm not good."),
        ln("小张", "没关系，我教你！明天下午可以吗？", "Méi guānxi, wǒ jiāo nǐ! Míngtiān xiàwǔ kěyǐ ma?", "Pas grave, je t'apprends ! Demain après-midi, ça te va ?", "No problem, I'll teach you! Does tomorrow afternoon work?"),
        ln("安娜", "好啊，明天见！", "Hǎo a, míngtiān jiàn!", "Avec plaisir, à demain !", "Sure, see you tomorrow!"),
      ],
    },
    vocab: ["运动", "跑步", "游泳", "打篮球", "篮球", "足球", "踢", "乒乓球", "比赛", "健身房", "公里", "快", "慢", "经常", "常常", "有时候", "总是", "平时", "每", "会", "能", "可以", "教", "身体", "健康", "累", "厉害", "爬山", "周末"],
    grammar: ["hsk2-g20", "hsk2-g21", "hsk2-g22", "hsk2-g23", "hsk2-g24"],
    culture: {
      title: t("Ping-pong, tai-chi et danse de place", "Ping-pong, tai chi and square dancing"),
      body: t(
        "Le **ping-pong** (乒乓球) est le sport national : on trouve des tables en béton dans presque tous les parcs et cours d'immeuble. Le **basket** est le sport le plus populaire chez les jeunes.\n\nTôt le matin, les parcs se remplissent de retraités qui pratiquent le **tai-chi** (太极拳 tàijíquán). Le soir, c'est l'heure de la **danse de place** (广场舞 guǎngchǎngwǔ) : des groupes, surtout de femmes d'âge mûr, dansent en rythme sur des haut-parleurs — à la grande joie… ou au grand désespoir des voisins !\n\nFaire du sport en groupe, dehors et gratuitement, fait partie de la vie de quartier.",
        "**Table tennis** (乒乓球) is the national sport: there are concrete tables in almost every park and housing compound. **Basketball** is the most popular sport among young people.\n\nEarly in the morning, parks fill with retirees practising **tai chi** (太极拳 tàijíquán). In the evening it's time for **square dancing** (广场舞 guǎngchǎngwǔ): groups, mostly of middle-aged women, dance in sync to loudspeakers — to the neighbours' delight… or despair!\n\nExercising together, outdoors and for free, is part of neighbourhood life.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Il court tous les jours.", "He runs every day."), t("Il court très vite.", "He runs very fast."), t("Il aime courir.", "He likes running."), t("Il court lentement.", "He runs slowly.")], 1, { zh: "他跑得很快。", pinyin: "Tā pǎo de hěn kuài." }),
      choice(P.correct, ["他打篮球得很好。", "他打篮球打得很好。", "他很好打篮球。", "他打得篮球很好。"], 1, { explain: t("Avec un objet, on répète le verbe avant 得.", "With an object, repeat the verb before 得.") }),
      choice(t("« Je sais nager » (je l'ai appris) se dit :", "\"I can swim\" (I've learned how) is:"), ["我可以游泳。", "我能游泳。", "我会游泳。", "我得游泳。"], 2, { explain: t("会 = savoir faire grâce à un apprentissage.", "会 = know how to, through learning.") }),
      fill(P.fill, "我每天早上", "跑步。", ["都", "过", "了", "着"], 0, t("Je cours tous les matins.", "I run every morning.")),
      fill(P.fill, "她游泳游", "非常快。", ["的", "地", "得", "了"], 2, t("Elle nage très vite.", "She swims very fast.")),
      fill(P.fill, "我脚疼，今天不", "踢足球。", ["就", "能", "得", "过"], 1, t("J'ai mal au pied, je ne peux pas jouer au foot aujourd'hui.", "My foot hurts, I can't play football today."), t("Empêchement physique ou circonstanciel → 能.", "Physical or circumstantial inability → 能.")),
      order(P.order, ["他", "每个周末", "都", "去", "游泳"], t("Il va nager tous les week-ends.", "He goes swimming every weekend.")),
      order(P.order, ["你", "中文", "说得", "真", "好"], t("Tu parles vraiment bien chinois.", "Your Chinese is really good.")),
      listen("我不常运动，有时候去爬山。", ["我常常运动，有时候去爬山。", "我不常运动，有时候去爬山。", "我不常运动，有时候去游泳。", "我不运动，也不爬山。"], 1, t("Je ne fais pas souvent de sport, parfois de la randonnée.", "I don't exercise often; sometimes I go hiking.")),
      listen("这里可以踢足球吗？", ["这里可以踢足球吗？", "这里能打篮球吗？", "你会踢足球吗？", "这里可以游泳吗？"], 0, t("On peut jouer au foot ici ?", "Can we play football here?")),
      match(P.match, [
        ["跑步", "pǎobù", "courir", "run, jog"],
        ["游泳", "yóuyǒng", "nager", "swim"],
        ["比赛", "bǐsài", "match, compétition", "match, competition"],
        ["健身房", "jiànshēnfáng", "salle de sport", "gym"],
        ["厉害", "lìhai", "impressionnant, fort", "impressive, awesome"],
      ]),
      choice(P.correct, ["我不常常去健身房。", "我不常去健身房。", "我去常常健身房。", "我常常不去健身房了。"], 1, { explain: t("La négation de 常常 est 不常.", "The negative of 常常 is 不常.") }),
    ],
  },
];
