import type { Lesson } from "../../types";
import { P, choice, fill, listen, ln, match, order, t } from "./helpers";

export const lessonsB: Lesson[] = [
  // ───────────────────────── L06 — Festivals ─────────────────────────
  {
    id: "hsk2-l06",
    level: 2,
    order: 6,
    title: t("Bientôt le Nouvel An chinois", "Chinese New Year Is Coming"),
    subtitle: t("Fêtes, traditions et invitations en famille", "Festivals, traditions and family invitations"),
    theme: "culture",
    goals: [
      t("Dire qu'un événement approche avec 快要…了", "Say an event is coming up with 快要…了"),
      t("Décrire ce qu'on fait « quand… » avec …的时候", "Describe what you do \"when…\" with …的时候"),
      t("Inviter et faire faire avec 请 / 让 / 叫", "Invite and get someone to do something with 请 / 让 / 叫"),
      t("Nuancer ses phrases avec 吧, 啊, 呢", "Add tone with 吧, 啊, 呢"),
    ],
    dialogue: {
      context: t(
        "Mi-janvier. Wang Li demande à Marc où il va passer la fête du Printemps.",
        "Mid-January. Wang Li asks Marc where he'll spend Spring Festival.",
      ),
      lines: [
        ln("王丽", "马克，快要过春节了，你回法国吗？", "Mǎkè, kuài yào guò Chūnjié le, nǐ huí Fǎguó ma?", "Marc, c'est bientôt la fête du Printemps, tu rentres en France ?", "Marc, Spring Festival is almost here — are you going back to France?"),
        ln("马克", "不回，机票太贵了。你呢？", "Bù huí, jīpiào tài guì le. Nǐ ne?", "Non, les billets d'avion sont trop chers. Et toi ?", "No, flights are too expensive. What about you?"),
        ln("王丽", "我回老家，跟家人一起过年。你来我家过年吧！", "Wǒ huí lǎojiā, gēn jiārén yìqǐ guò nián. Nǐ lái wǒ jiā guò nián ba!", "Je rentre chez mes parents, fêter le Nouvel An en famille. Viens chez nous !", "I'm going back to my hometown to celebrate with my family. Come and spend New Year with us!"),
        ln("马克", "真的吗？你爸爸妈妈会不会不高兴？", "Zhēn de ma? Nǐ bàba māma huì bu huì bù gāoxìng?", "C'est vrai ? Tes parents ne vont pas être embêtés ?", "Really? Won't your parents mind?"),
        ln("王丽", "当然不会！我妈妈让我请你来。", "Dāngrán bú huì! Wǒ māma ràng wǒ qǐng nǐ lái.", "Bien sûr que non ! C'est ma mère qui m'a dit de t'inviter.", "Of course not! My mom told me to invite you."),
        ln("马克", "太好了！过春节的时候，你们做什么？", "Tài hǎo le! Guò Chūnjié de shíhou, nǐmen zuò shénme?", "Génial ! Qu'est-ce que vous faites pendant la fête ?", "Great! What do you do at Spring Festival?"),
        ln("王丽", "除夕晚上，大家一起包饺子、看春晚。", "Chúxī wǎnshang, dàjiā yìqǐ bāo jiǎozi, kàn Chūnwǎn.", "Le soir du réveillon, on fait des raviolis tous ensemble et on regarde le gala télévisé.", "On New Year's Eve, we all make dumplings together and watch the Spring Festival Gala."),
        ln("马克", "我听说大人还要给孩子红包，是吗？", "Wǒ tīngshuō dàrén hái yào gěi háizi hóngbāo, shì ma?", "J'ai entendu dire que les adultes donnent des enveloppes rouges aux enfants, c'est ça ?", "I heard adults give red envelopes to the kids, right?"),
        ln("王丽", "对啊！十二点的时候，还要放鞭炮。", "Duì a! Shí'èr diǎn de shíhou, hái yào fàng biānpào.", "Oui ! Et à minuit, on fait éclater des pétards.", "Yes! And at midnight, we set off firecrackers."),
        ln("马克", "我应该带什么礼物呢？", "Wǒ yīnggāi dài shénme lǐwù ne?", "Qu'est-ce que je devrais apporter comme cadeau ?", "What gift should I bring?"),
        ln("王丽", "带点儿水果就行了，别买太贵的。", "Dài diǎnr shuǐguǒ jiù xíng le, bié mǎi tài guì de.", "Un peu de fruits, ça suffit. N'achète rien de trop cher.", "Some fruit is fine — don't buy anything too expensive."),
        ln("马克", "好啊，我太高兴了！", "Hǎo a, wǒ tài gāoxìng le!", "D'accord, je suis trop content !", "OK, I'm so happy!"),
      ],
    },
    vocab: ["春节", "过年", "节日", "中秋节", "老家", "家人", "跟", "一起", "饺子", "包", "红包", "礼物", "鞭炮", "烟花", "月饼", "月亮", "除夕", "请", "让", "叫", "快要", "时候", "水果", "当然", "听说", "大人", "孩子", "高兴", "机票"],
    grammar: ["hsk2-g25", "hsk2-g26", "hsk2-g27", "hsk2-g28", "hsk2-g29"],
    culture: {
      title: t("La fête du Printemps : la plus grande migration du monde", "Spring Festival: the world's biggest migration"),
      body: t(
        "La **fête du Printemps** (春节) suit le calendrier lunaire : elle tombe entre fin janvier et mi-février. Pendant le **春运** (chūnyùn, la « période de transport »), des centaines de millions de Chinois rentrent chez leurs parents : c'est la plus grande migration humaine annuelle.\n\nLe soir du **réveillon** (除夕 chúxī), la famille dîne ensemble, fait des **raviolis** (surtout dans le nord) et regarde le **gala du Nouvel An** (春晚) à la télévision. Les adultes offrent aux enfants et aux personnes âgées des **enveloppes rouges** (红包) contenant de l'argent — aujourd'hui souvent envoyées sur WeChat.\n\nAutre grande fête : la **fête de la Mi-Automne** (中秋节), où l'on admire la pleine lune en mangeant des **gâteaux de lune** (月饼).",
        "**Spring Festival** (春节) follows the lunar calendar, falling between late January and mid-February. During **春运** (chūnyùn, \"the travel rush\"), hundreds of millions of people go home to their parents — the largest annual human migration.\n\nOn **New Year's Eve** (除夕 chúxī), families eat together, make **dumplings** (especially in the north) and watch the **Spring Festival Gala** (春晚) on TV. Adults give children and elders **red envelopes** (红包) containing money — nowadays often sent via WeChat.\n\nAnother big festival: **Mid-Autumn Festival** (中秋节), when people admire the full moon while eating **mooncakes** (月饼).",
      ),
    },
    exercises: [
      choice(P.meaning, [t("La fête du Printemps est finie.", "Spring Festival is over."), t("C'est bientôt la fête du Printemps.", "Spring Festival is coming soon."), t("J'aime la fête du Printemps.", "I like Spring Festival."), t("La fête du Printemps dure longtemps.", "Spring Festival lasts a long time.")], 1, { zh: "快要过春节了。", pinyin: "Kuài yào guò Chūnjié le." }),
      choice(P.correct, ["我吃饭跟家人一起。", "我一起跟家人吃饭。", "我跟家人一起吃饭。", "跟家人我一起吃饭。"], 2, { explain: t("跟 + personne + 一起 se place avant le verbe.", "跟 + person + 一起 goes before the verb.") }),
      choice(P.correct, ["下个星期快要放假了。", "下个星期就要放假了。", "下个星期快放假。", "下个星期要快放假了。"], 1, { explain: t("Avec une date précise, on utilise 就要…了, pas 快要…了.", "With a specific time, use 就要…了, not 快要…了.") }),
      fill(P.fill, "我小", "时候很喜欢放鞭炮。", ["的", "得", "地", "了"], 0, t("Quand j'étais petit, j'adorais faire éclater des pétards.", "When I was little I loved setting off firecrackers.")),
      fill(P.fill, "妈妈", "我请你来我家过年。", ["让", "给", "跟", "对"], 0, t("Ma mère m'a demandé de t'inviter pour le Nouvel An.", "My mom asked me to invite you over for New Year.")),
      fill(P.fill, "我春节回老家，你", "？", ["吗", "呢", "吧", "的"], 1, t("Je rentre chez moi pour la fête du Printemps, et toi ?", "I'm going home for Spring Festival — how about you?")),
      order(P.order, ["快要", "过", "中秋节", "了"], t("C'est bientôt la fête de la Mi-Automne.", "Mid-Autumn Festival is almost here.")),
      order(P.order, ["中秋节", "我", "请你", "吃", "月饼"], t("Pour la Mi-Automne, je t'offre des gâteaux de lune.", "I'll treat you to mooncakes at Mid-Autumn.")),
      listen("吃饭的时候别看手机。", ["吃饭的时候别看手机。", "吃饭的时候看手机吧。", "睡觉的时候别看手机。", "吃饭以后别看手机。"], 0, t("Ne regarde pas ton téléphone en mangeant.", "Don't look at your phone while eating.")),
      listen("我们一起去看烟花吧！", ["我们一起去看电影吧！", "我们一起去放鞭炮吧！", "你们一起去看烟花吗？", "我们一起去看烟花吧！"], 3, t("Allons voir le feu d'artifice ensemble !", "Let's go and watch the fireworks together!")),
      match(P.match, [
        ["红包", "hóngbāo", "enveloppe rouge", "red envelope"],
        ["饺子", "jiǎozi", "raviolis", "dumplings"],
        ["月饼", "yuèbing", "gâteau de lune", "mooncake"],
        ["老家", "lǎojiā", "ville natale", "hometown"],
        ["礼物", "lǐwù", "cadeau", "gift"],
      ]),
      choice(t("Tu proposes à un ami d'aller voir les lanternes ensemble. Quelle phrase est la plus naturelle ?", "You suggest to a friend going to see the lanterns together. Which is most natural?"), ["我们一起去看灯吧！", "我们一起去看灯呢！", "我们一起去看灯了！", "我们一起去看灯的！"], 0, { explain: t("吧 marque une proposition.", "吧 marks a suggestion.") }),
    ],
  },

  // ───────────────────────── L07 — Weather & seasons ─────────────────────────
  {
    id: "hsk2-l07",
    level: 2,
    order: 7,
    title: t("Il fait de plus en plus froid", "It's Getting Colder"),
    subtitle: t("Météo, saisons et comparaisons", "Weather, seasons and comparisons"),
    theme: "weather",
    goals: [
      t("Comparer avec 比 et préciser l'écart", "Compare with 比 and specify the difference"),
      t("Décrire une évolution avec 越来越", "Describe a trend with 越来越"),
      t("Signaler un changement avec le 了 final", "Signal a change with sentence-final 了"),
      t("Donner une température approximative (左右, 多)", "Give an approximate temperature (左右, 多)"),
    ],
    dialogue: {
      context: t(
        "Un matin de novembre à Pékin, Anna et Xiao Lin sortent du bureau.",
        "One November morning in Beijing, Anna and Xiao Lin step out of the office.",
      ),
      lines: [
        ln("小林", "今天比昨天冷多了！", "Jīntiān bǐ zuótiān lěng duō le!", "Il fait beaucoup plus froid qu'hier !", "It's much colder than yesterday!"),
        ln("安娜", "是啊，刮风了。今天多少度？", "Shì a, guā fēng le. Jīntiān duōshao dù?", "Oui, le vent s'est levé. Il fait combien aujourd'hui ?", "Yeah, the wind's picked up. What's the temperature today?"),
        ln("小林", "手机上说最高十度左右，最低只有两度。", "Shǒujī shang shuō zuì gāo shí dù zuǒyòu, zuì dī zhǐ yǒu liǎng dù.", "D'après mon téléphone, dix degrés maximum environ, et seulement deux au minimum.", "My phone says a high of about ten and a low of just two."),
        ln("安娜", "天气越来越冷了。北京的冬天冷不冷？", "Tiānqì yuè lái yuè lěng le. Běijīng de dōngtiān lěng bu lěng?", "Il fait de plus en plus froid. L'hiver à Pékin, c'est froid ?", "It's getting colder and colder. Are Beijing winters cold?"),
        ln("小林", "很冷，比巴黎冷得多，可是很少下雨。", "Hěn lěng, bǐ Bālí lěng de duō, kěshì hěn shǎo xià yǔ.", "Très froid, bien plus qu'à Paris, mais il pleut rarement.", "Very cold — much colder than Paris, but it rarely rains."),
        ln("安娜", "会下雪吗？", "Huì xià xuě ma?", "Il neige ?", "Does it snow?"),
        ln("小林", "有时候下。下雪的时候特别漂亮。", "Yǒu shíhou xià. Xià xuě de shíhou tèbié piàoliang.", "Parfois. Quand il neige, c'est magnifique.", "Sometimes. It's beautiful when it snows."),
        ln("安娜", "你最喜欢哪个季节？", "Nǐ zuì xǐhuan nǎge jìjié?", "Quelle est ta saison préférée ?", "Which season do you like best?"),
        ln("小林", "秋天。北京的秋天不冷也不热，天很蓝。", "Qiūtiān. Běijīng de qiūtiān bù lěng yě bú rè, tiān hěn lán.", "L'automne. À Pékin, il ne fait ni froid ni chaud, et le ciel est tout bleu.", "Autumn. Beijing autumns are neither cold nor hot, and the sky is really blue."),
        ln("安娜", "我喜欢春天，可是北京春天风太大了。", "Wǒ xǐhuan chūntiān, kěshì Běijīng chūntiān fēng tài dà le.", "Moi, j'aime le printemps, mais à Pékin il y a trop de vent au printemps.", "I like spring, but it's far too windy in Beijing in spring."),
        ln("小林", "你看，下雨了！你带伞了吗？", "Nǐ kàn, xià yǔ le! Nǐ dài sǎn le ma?", "Regarde, il pleut ! Tu as pris un parapluie ?", "Look, it's started raining! Did you bring an umbrella?"),
        ln("安娜", "没带……我们快走吧！", "Méi dài…… Wǒmen kuài zǒu ba!", "Non… Dépêchons-nous !", "No… Let's hurry!"),
      ],
    },
    vocab: ["天气", "冷", "热", "暖和", "凉快", "度", "刮风", "风", "下雨", "下雪", "雨", "雪", "晴", "阴", "季节", "春天", "夏天", "秋天", "冬天", "比", "越来越", "左右", "最高", "最低", "伞", "带", "蓝", "太阳", "天气预报", "北方", "南方"],
    grammar: ["hsk2-g30", "hsk2-g31", "hsk2-g32", "hsk2-g33", "hsk2-g34"],
    culture: {
      title: t("Le chauffage central au nord de la rivière Huai", "Central heating north of the Huai River"),
      body: t(
        "La Chine est coupée en deux par une ligne invisible : la **ligne Qinling–Huaihe**. Au **nord** (北方), les villes allument le **chauffage central** (暖气 nuǎnqì) — à Pékin, officiellement le **15 novembre**. Au **sud** (南方), il n'y a traditionnellement pas de chauffage collectif : les hivers à Shanghai, humides et autour de 5 °C, peuvent sembler plus froids à l'intérieur qu'à Pékin !\n\nLe calendrier traditionnel divise l'année en **24 périodes solaires** (二十四节气), comme 立春 (début du printemps) ou 冬至 (solstice d'hiver, où l'on mange des raviolis dans le nord). Elles sont inscrites au patrimoine immatériel de l'UNESCO.",
        "China is split by an invisible line: the **Qinling–Huaihe line**. In the **north** (北方), cities switch on **central heating** (暖气 nuǎnqì) — officially on **15 November** in Beijing. In the **south** (南方), there's traditionally no district heating: Shanghai's damp winters at around 5 °C can feel colder indoors than Beijing's!\n\nThe traditional calendar divides the year into **24 solar terms** (二十四节气), such as 立春 (start of spring) or 冬至 (winter solstice, when northerners eat dumplings). They're on UNESCO's intangible heritage list.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Aujourd'hui il fait un peu plus chaud qu'hier.", "Today is a bit warmer than yesterday."), t("Aujourd'hui il fait beaucoup plus froid qu'hier.", "Today is much colder than yesterday."), t("Hier il faisait plus froid qu'aujourd'hui.", "Yesterday was colder than today."), t("Aujourd'hui il fait aussi froid qu'hier.", "Today is as cold as yesterday.")], 1, { zh: "今天比昨天冷多了。", pinyin: "Jīntiān bǐ zuótiān lěng duō le." }),
      choice(P.correct, ["今天比昨天很冷。", "今天冷比昨天。", "今天比昨天冷一点儿。", "今天比昨天有点儿冷。"], 2, { explain: t("Pas de 很 ni de 有点儿 avec 比 ; l'écart se place après l'adjectif.", "No 很 or 有点儿 with 比; the difference goes after the adjective.") }),
      choice(P.correct, ["他比我两岁大。", "他比我大两岁。", "他两岁比我大。", "他大比我两岁。"], 1),
      fill(P.fill, "天气越来越", "了。", ["冷", "很冷", "非常冷", "冷多"], 0, t("Il fait de plus en plus froid.", "It's getting colder and colder."), t("Pas d'adverbe de degré après 越来越.", "No degree adverb after 越来越.")),
      fill(P.fill, "明天最高气温二十五度", "。", ["左右", "多少", "几", "以前"], 0, t("Demain, la température maximale sera d'environ 25 degrés.", "Tomorrow's high will be about 25 degrees.")),
      fill(P.fill, "你看，下雪", "！", ["了", "过", "着", "的"], 0, t("Regarde, il neige !", "Look, it's snowing!"), t("Le 了 final indique un changement : il ne neigeait pas avant.", "Final 了 signals a change: it wasn't snowing before.")),
      order(P.order, ["北京的冬天", "比", "上海", "冷", "多了"], t("L'hiver à Pékin est bien plus froid qu'à Shanghai.", "Beijing winters are much colder than Shanghai's.")),
      order(P.order, ["雨", "下了", "两个多", "小时"], t("Il a plu pendant plus de deux heures.", "It rained for over two hours.")),
      listen("明天阴，可能有小雨。", ["明天晴，可能有小雨。", "明天阴，可能有小雨。", "明天阴，可能有大雪。", "今天阴，可能有小雨。"], 1, t("Demain, temps couvert, peut-être quelques gouttes.", "Tomorrow: cloudy, possibly light rain.")),
      listen("秋天到了，天气凉快了。", ["秋天到了，天气凉快了。", "春天到了，天气暖和了。", "秋天到了，天气越来越热。", "冬天到了，天气冷了。"], 0, t("L'automne est arrivé, il fait plus frais.", "Autumn is here, it's turned cool.")),
      match(P.match, [
        ["暖和", "nuǎnhuo", "doux, tiède", "warm, mild"],
        ["凉快", "liángkuai", "frais (agréable)", "cool (pleasant)"],
        ["刮风", "guā fēng", "il y a du vent", "be windy"],
        ["季节", "jìjié", "saison", "season"],
        ["伞", "sǎn", "parapluie", "umbrella"],
        ["晴", "qíng", "ensoleillé", "sunny, clear"],
      ]),
      choice(t("Il ne pleuvait pas, et maintenant il pleut. Tu dis :", "It wasn't raining, and now it is. You say:"), ["下雨。", "下雨了。", "下过雨。", "在下雨过。"], 1),
    ],
  },

  // ───────────────────────── L08 — Workplace ─────────────────────────
  {
    id: "hsk2-l08",
    level: 2,
    order: 8,
    title: t("Une journée au bureau", "A Day at the Office"),
    subtitle: t("Où en est ton travail ?", "How far along is your work?"),
    theme: "work",
    goals: [
      t("Dire ce qu'on est en train de faire (正在…呢)", "Say what you're doing right now (正在…呢)"),
      t("Faire le point : 已经…了 / 还没…呢", "Give updates: 已经…了 / 还没…呢"),
      t("Dire qu'une tâche est finie ou prête (完 / 好)", "Say a task is finished or ready (完 / 好)"),
      t("Parler du passé proche avec 刚 et 刚才", "Talk about the recent past with 刚 and 刚才"),
    ],
    dialogue: {
      context: t(
        "Il est 16 h. Mme Chen, la directrice, passe voir Marc à son poste.",
        "It's 4 p.m. Ms Chen, the manager, stops by Marc's desk.",
      ),
      lines: [
        ln("陈经理", "马克，明天开会的材料准备好了吗？", "Mǎkè, míngtiān kāihuì de cáiliào zhǔnbèi hǎo le ma?", "Marc, les documents pour la réunion de demain sont prêts ?", "Marc, are the documents for tomorrow's meeting ready?"),
        ln("马克", "还没呢，我正在写报告。", "Hái méi ne, wǒ zhèngzài xiě bàogào.", "Pas encore, je suis en train d'écrire le rapport.", "Not yet, I'm writing the report right now."),
        ln("陈经理", "已经四点了，你几点能写完？", "Yǐjīng sì diǎn le, nǐ jǐ diǎn néng xiěwán?", "Il est déjà 16 h. Tu auras fini à quelle heure ?", "It's already four. What time can you finish?"),
        ln("马克", "六点以前一定能写完。", "Liù diǎn yǐqián yídìng néng xiěwán.", "Avant 18 h, c'est sûr.", "Before six, for sure."),
        ln("陈经理", "好。刚才客户给你打电话了吗？", "Hǎo. Gāngcái kèhù gěi nǐ dǎ diànhuà le ma?", "Bien. Le client t'a appelé tout à l'heure ?", "Good. Did the client call you just now?"),
        ln("马克", "打了，我刚跟他说完。他明天上午十点来公司。", "Dǎ le, wǒ gāng gēn tā shuōwán. Tā míngtiān shàngwǔ shí diǎn lái gōngsī.", "Oui, je viens de raccrocher. Il vient demain à 10 h.", "Yes, I just finished talking to him. He's coming to the office at ten tomorrow."),
        ln("陈经理", "会议室订好了没有？", "Huìyìshì dìnghǎo le méiyǒu?", "La salle de réunion est réservée ?", "Is the meeting room booked?"),
        ln("马克", "已经订好了，在三楼。", "Yǐjīng dìnghǎo le, zài sān lóu.", "Oui, c'est fait, au troisième étage.", "Already booked — it's on the third floor."),
        ln("陈经理", "很好。打印纸用完了，你告诉小王一下。", "Hěn hǎo. Dǎyìnzhǐ yòngwán le, nǐ gàosu Xiǎo Wáng yíxià.", "Très bien. Il n'y a plus de papier pour l'imprimante, préviens Xiao Wang.", "Great. We're out of printer paper — let Xiao Wang know."),
        ln("马克", "小王正在开会呢，我等一会儿去买吧。", "Xiǎo Wáng zhèngzài kāihuì ne, wǒ děng yíhuìr qù mǎi ba.", "Xiao Wang est en réunion, j'irai en acheter tout à l'heure.", "Xiao Wang is in a meeting — I'll go and buy some in a bit."),
        ln("陈经理", "谢谢。今天别加班了，早点儿回家。", "Xièxie. Jīntiān bié jiābān le, zǎo diǎnr huí jiā.", "Merci. Ne fais pas d'heures sup ce soir, rentre tôt.", "Thanks. Don't work late today — go home early."),
        ln("马克", "好的，写完报告我就下班。", "Hǎo de, xiěwán bàogào wǒ jiù xiàbān.", "D'accord, dès que j'ai fini le rapport, je pars.", "OK, I'll leave as soon as I finish the report."),
      ],
    },
    vocab: ["公司", "办公室", "经理", "同事", "客户", "会议", "开会", "会议室", "报告", "材料", "打印", "纸", "电脑", "邮件", "上班", "下班", "加班", "工作", "忙", "已经", "正在", "刚", "刚才", "完", "准备", "一定", "告诉", "问题", "一会儿"],
    grammar: ["hsk2-g35", "hsk2-g36", "hsk2-g37", "hsk2-g38", "hsk2-g39"],
    culture: {
      title: t("Sieste, WeChat et « 996 »", "Naps, WeChat and \"996\""),
      body: t(
        "Dans beaucoup de bureaux chinois, la pause déjeuner inclut une **sieste** (午休 wǔxiū) : on voit des employés dormir sur leur bureau ou sur un lit pliant, lumières éteintes. C'est parfaitement normal !\n\nLe travail passe énormément par **WeChat** : chaque équipe a son **groupe** (工作群), et on attend souvent des réponses rapides, même le soir. Le fameux **« 996 »** (de 9 h à 21 h, 6 jours par semaine) désigne les horaires très lourds de certaines entreprises tech — une pratique critiquée et officiellement illégale.\n\nPolitesse : on s'adresse à un supérieur avec son **nom + titre** : 陈经理 (directrice Chen), 王老师, 李总 (patron Li).",
        "In many Chinese offices, the lunch break includes a **nap** (午休 wǔxiū): you'll see staff sleeping on their desks or on folding beds, lights off. Totally normal!\n\nWork runs heavily through **WeChat**: every team has its **group chat** (工作群), and quick replies are often expected, even in the evening. The infamous **\"996\"** (9 a.m. to 9 p.m., 6 days a week) describes the gruelling hours at some tech firms — widely criticised and officially illegal.\n\nEtiquette: address superiors by **surname + title**: 陈经理 (Manager Chen), 王老师, 李总 (Boss Li).",
      ),
    },
    exercises: [
      choice(P.meaning, [t("J'ai déjà fini le rapport.", "I've already finished the report."), t("Je suis en train d'écrire le rapport.", "I'm writing the report right now."), t("Je n'ai pas encore écrit le rapport.", "I haven't written the report yet."), t("Je viens d'écrire le rapport.", "I've just written the report.")], 1, { zh: "我正在写报告呢。", pinyin: "Wǒ zhèngzài xiě bàogào ne." }),
      choice(t("Ton chef demande : 你吃饭了吗？ Tu n'as pas encore mangé. Tu réponds :", "Your boss asks 你吃饭了吗？ You haven't eaten yet. You answer:"), ["还没吃了。", "还没呢。", "不吃了。", "已经没吃。"], 1),
      choice(P.correct, ["刚我到公司。", "我刚才到了公司。", "我刚没到公司。", "刚我到了公司。"], 1, { explain: t("刚 se place devant le verbe ; 刚才 peut prendre 了.", "刚 sits before the verb; 刚才 can take 了.") }),
      fill(P.fill, "你的工作做", "了吗？", ["完", "见", "懂", "在"], 0, t("Tu as fini ton travail ?", "Have you finished your work?")),
      fill(P.fill, "", "八点了，快起床！", ["已经", "正在", "过", "还没"], 0, t("Il est déjà huit heures, lève-toi !", "It's already eight, get up!")),
      fill(P.fill, "我还没做完，", "等我一下。", ["请", "过", "刚", "了"], 0, t("Je n'ai pas encore fini, attends-moi une seconde, s'il te plaît.", "I'm not finished yet, please wait a moment.")),
      order(P.order, ["会议的", "材料", "我", "准备好", "了"], t("J'ai préparé les documents de la réunion.", "I've got the meeting documents ready.")),
      order(P.order, ["经理", "正在", "开会", "呢"], t("Le directeur est en réunion.", "The manager is in a meeting.")),
      listen("客户还没回邮件。", ["客户已经回邮件了。", "客户还没回邮件。", "客户还没打电话。", "经理还没回邮件。"], 1, t("Le client n'a pas encore répondu à l'e-mail.", "The client hasn't replied to the email yet.")),
      listen("我刚到办公室。", ["我刚到办公室。", "我刚才去办公室了。", "我快到办公室了。", "我还没到办公室。"], 0, t("Je viens d'arriver au bureau.", "I've just arrived at the office.")),
      match(P.match, [
        ["加班", "jiābān", "faire des heures sup", "work overtime"],
        ["客户", "kèhù", "client", "client"],
        ["报告", "bàogào", "rapport", "report"],
        ["会议室", "huìyìshì", "salle de réunion", "meeting room"],
        ["同事", "tóngshì", "collègue", "colleague"],
      ]),
      choice(P.correct, ["我不做完作业。", "我没做完作业。", "我做了完作业。", "我没做作业完。"], 1, { explain: t("On nie un complément de résultat avec 没.", "Negate a result complement with 没.") }),
    ],
  },

  // ───────────────────────── L09 — Study ─────────────────────────
  {
    id: "hsk2-l09",
    level: 2,
    order: 9,
    title: t("En cours de chinois", "In Chinese Class"),
    subtitle: t("Comprendre, se tromper, progresser", "Understanding, making mistakes, improving"),
    theme: "school",
    goals: [
      t("Dire si on a compris, vu, trouvé (懂, 见, 到…)", "Say whether you understood, saw, found (懂, 见, 到…)"),
      t("Compter les répétitions : 次, 遍", "Count repetitions: 次, 遍"),
      t("Expliquer une cause (因为…所以) et une concession (虽然…但是)", "Give reasons (因为…所以) and concessions (虽然…但是)"),
      t("Parler de ses centres d'intérêt avec 对…感兴趣", "Talk about interests with 对…感兴趣"),
    ],
    dialogue: {
      context: t(
        "Après le cours, Anna pose des questions à sa professeure, Mme Liu.",
        "After class, Anna asks her teacher, Ms Liu, some questions.",
      ),
      lines: [
        ln("刘老师", "安娜，昨天的作业你做完了吗？", "Ānnà, zuótiān de zuòyè nǐ zuòwán le ma?", "Anna, tu as fini les devoirs d'hier ?", "Anna, did you finish yesterday's homework?"),
        ln("安娜", "做完了。可是有几个句子我没看懂。", "Zuòwán le. Kěshì yǒu jǐ ge jùzi wǒ méi kàndǒng.", "Oui, mais il y a quelques phrases que je n'ai pas comprises.", "Yes. But there are a few sentences I didn't understand."),
        ln("刘老师", "哪个？我给你讲一下。", "Nǎge? Wǒ gěi nǐ jiǎng yíxià.", "Lesquelles ? Je vais t'expliquer.", "Which ones? Let me explain."),
        ln("安娜", "这个。“就”和“才”有什么不一样？", "Zhège. “Jiù” hé “cái” yǒu shénme bù yíyàng?", "Celle-ci. Quelle est la différence entre « jiù » et « cái » ?", "This one. What's the difference between \"jiù\" and \"cái\"?"),
        ln("刘老师", "这个有点儿难，下次上课我再讲一遍。", "Zhège yǒudiǎnr nán, xià cì shàngkè wǒ zài jiǎng yí biàn.", "C'est un peu difficile, je le réexpliquerai au prochain cours.", "That's a bit tricky — I'll go over it again next class."),
        ln("安娜", "谢谢老师！虽然汉字很难，但是我很喜欢。", "Xièxie lǎoshī! Suīrán Hànzì hěn nán, dànshì wǒ hěn xǐhuan.", "Merci ! Les caractères sont difficiles, mais je les adore.", "Thank you! Although characters are hard, I love them."),
        ln("刘老师", "你对汉字很感兴趣吗？", "Nǐ duì Hànzì hěn gǎn xìngqù ma?", "Les caractères t'intéressent beaucoup ?", "Are you very interested in characters?"),
        ln("安娜", "是的。因为每个字都像一张画，所以我觉得很有意思。", "Shì de. Yīnwèi měi ge zì dōu xiàng yì zhāng huà, suǒyǐ wǒ juéde hěn yǒu yìsi.", "Oui. Chaque caractère ressemble à un petit dessin, c'est pour ça que je trouve ça passionnant.", "Yes. Each character is like a little picture, so I find them fascinating."),
        ln("刘老师", "这个字你写错了，少了一点。", "Zhège zì nǐ xiěcuò le, shǎole yì diǎn.", "Tu as mal écrit ce caractère, il manque un point.", "You wrote this character wrong — there's a dot missing."),
        ln("安娜", "啊，我看见了。我再写一遍。", "À, wǒ kànjiàn le. Wǒ zài xiě yí biàn.", "Ah, je vois. Je le réécris.", "Oh, I see it. I'll write it again."),
        ln("刘老师", "下个月的HSK考试，你准备得怎么样了？", "Xià ge yuè de HSK kǎoshì, nǐ zhǔnbèi de zěnmeyàng le?", "Et l'examen HSK du mois prochain, tu en es où ?", "How's your preparation for next month's HSK going?"),
        ln("安娜", "还可以。我每天听三遍课文，希望能考好！", "Hái kěyǐ. Wǒ měi tiān tīng sān biàn kèwén, xīwàng néng kǎohǎo!", "Ça va. J'écoute le texte trois fois par jour, j'espère réussir !", "Not bad. I listen to the texts three times a day — I hope I'll do well!"),
      ],
    },
    vocab: ["学习", "复习", "作业", "考试", "成绩", "汉字", "句子", "课文", "词", "懂", "听懂", "看懂", "错", "遍", "次", "讲", "问题", "虽然", "但是", "因为", "所以", "对", "感兴趣", "有意思", "难", "容易", "认真", "希望", "图书馆", "字典", "练习", "觉得"],
    grammar: ["hsk2-g40", "hsk2-g41", "hsk2-g42", "hsk2-g43", "hsk2-g44"],
    culture: {
      title: t("Copier pour retenir : la tradition du 抄写", "Copying to remember: the 抄写 tradition"),
      body: t(
        "Les écoliers chinois apprennent les caractères en les **recopiant** des dizaines de fois dans des cahiers quadrillés (田字格 tiánzìgé, une grille en forme de 田). L'**ordre des traits** (笔顺) est très important : il rend l'écriture plus fluide et lisible.\n\nLe grand examen de fin de lycée, le **gaokao** (高考), décide de l'entrée à l'université : c'est l'événement le plus stressant de la vie de beaucoup de jeunes Chinois.\n\nPour les étrangers, le **HSK** (汉语水平考试) est l'examen officiel de chinois. La version **HSK 3.0** compte **9 niveaux**, et ce cours suit son programme officiel.",
        "Chinese pupils learn characters by **copying** them dozens of times in grid notebooks (田字格 tiánzìgé, a grid shaped like 田). **Stroke order** (笔顺) matters a lot: it makes handwriting smoother and more legible.\n\nThe big end-of-school exam, the **gaokao** (高考), decides university entrance: it's the most stressful event in many young Chinese people's lives.\n\nFor foreigners, the **HSK** (汉语水平考试) is the official Chinese test. The **HSK 3.0** version has **9 levels**, and this course follows its official syllabus.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Je n'ai pas écouté le prof.", "I didn't listen to the teacher."), t("Je n'ai pas compris ce que le prof a dit.", "I didn't understand what the teacher said."), t("Je n'ai pas entendu le prof.", "I didn't hear the teacher."), t("Le prof ne m'a pas compris.", "The teacher didn't understand me.")], 1, { zh: "老师说的话我没听懂。", pinyin: "Lǎoshī shuō de huà wǒ méi tīngdǒng." }),
      choice(P.correct, ["我感兴趣中国历史。", "我对中国历史很感兴趣。", "我很感兴趣对中国历史。", "中国历史对我感兴趣。"], 1),
      choice(t("Tu veux que le prof répète toute la phrase. Tu dis :", "You want the teacher to repeat the whole sentence. You say:"), ["请再说一次。", "请再说一遍。", "请又说一遍。", "请说再一遍。"], 1, { explain: t("遍 = une fois du début à la fin ; 再 pour une répétition à venir.", "遍 = once from start to finish; 再 for a repetition still to come.") }),
      fill(P.fill, "", "汉字很难，但是很有意思。", ["虽然", "因为", "所以", "如果"], 0, t("Les caractères sont difficiles, mais passionnants.", "Although characters are hard, they're really interesting.")),
      fill(P.fill, "因为明天考试，", "我今天得复习。", ["但是", "所以", "虽然", "还是"], 1, t("Comme j'ai un examen demain, je dois réviser aujourd'hui.", "Because I have an exam tomorrow, I need to revise today.")),
      fill(P.fill, "这个字你写", "了，应该这样写。", ["错", "懂", "见", "会"], 0, t("Tu as mal écrit ce caractère, il s'écrit comme ça.", "You wrote this character wrong — it should be written like this.")),
      order(P.order, ["这个课文", "我", "听了", "三遍"], t("J'ai écouté ce texte trois fois.", "I listened to this text three times.")),
      order(P.order, ["多听多说", "对", "学中文", "很有帮助"], t("Écouter et parler beaucoup aide énormément à apprendre le chinois.", "Listening and speaking a lot really helps with learning Chinese.")),
      listen("我找到那本书了！", ["我找那本书了。", "我买到那本书了！", "我找到那本书了！", "我看完那本书了！"], 2, t("J'ai trouvé ce livre !", "I found that book!")),
      listen("我一个星期上两次中文课。", ["我一个星期上两次中文课。", "我一个月上两次中文课。", "我一个星期上三次中文课。", "我两个星期上一次中文课。"], 0, t("J'ai cours de chinois deux fois par semaine.", "I have Chinese class twice a week.")),
      match(P.match, [
        ["复习", "fùxí", "réviser", "revise, review"],
        ["作业", "zuòyè", "devoirs", "homework"],
        ["成绩", "chéngjì", "notes, résultats", "grades, results"],
        ["句子", "jùzi", "phrase", "sentence"],
        ["认真", "rènzhēn", "sérieux, appliqué", "diligent, serious"],
      ]),
      choice(t("听 et 听见 : quelle phrase veut dire « Tu as entendu ? »", "听 vs 听见: which sentence means \"Did you hear it?\""), ["你听了吗？", "你听见了吗？", "你听懂吗？", "你在听吗？"], 1),
    ],
  },

  // ───────────────────────── L10 — Directions ─────────────────────────
  {
    id: "hsk2-l10",
    level: 2,
    order: 10,
    title: t("Demander son chemin", "Asking for Directions"),
    subtitle: t("Se repérer en ville à pied et en métro", "Getting around the city on foot and by subway"),
    theme: "city",
    goals: [
      t("Comprendre un itinéraire : 往前走, 往左拐…", "Follow directions: 往前走, 往左拐…"),
      t("Demander la distance et la durée (多远, 多长时间)", "Ask about distance and time (多远, 多长时间)"),
      t("Décrire un mouvement avec 来 / 去 et 过, 进, 出…", "Describe movement with 来 / 去 and 过, 进, 出…"),
      t("Enchaîner deux actions avec 一…就…", "Link two actions with 一…就…"),
    ],
    dialogue: {
      context: t(
        "Marc cherche le parc du Peuple. Il demande son chemin à une passante.",
        "Marc is looking for People's Park. He asks a passer-by for directions.",
      ),
      lines: [
        ln("马克", "请问，去人民公园怎么走？", "Qǐngwèn, qù Rénmín Gōngyuán zěnme zǒu?", "Excusez-moi, pour aller au parc du Peuple ?", "Excuse me, how do I get to People's Park?"),
        ln("路人", "人民公园啊？你一直往前走，到了第二个路口往左拐。", "Rénmín Gōngyuán a? Nǐ yìzhí wǎng qián zǒu, dàole dì-èr ge lùkǒu wǎng zuǒ guǎi.", "Le parc du Peuple ? Allez tout droit, et au deuxième carrefour, tournez à gauche.", "People's Park? Go straight ahead and turn left at the second intersection."),
        ln("马克", "离这儿有多远？", "Lí zhèr yǒu duō yuǎn?", "C'est à quelle distance d'ici ?", "How far is it from here?"),
        ln("路人", "不太远，一公里左右。", "Bú tài yuǎn, yì gōnglǐ zuǒyòu.", "Pas très loin, un kilomètre environ.", "Not too far, about a kilometre."),
        ln("马克", "走路要多长时间？", "Zǒulù yào duō cháng shíjiān?", "Ça prend combien de temps à pied ?", "How long does it take on foot?"),
        ln("路人", "十五分钟吧。你也可以坐地铁，坐两站就到了。", "Shíwǔ fēnzhōng ba. Nǐ yě kěyǐ zuò dìtiě, zuò liǎng zhàn jiù dào le.", "Un quart d'heure, je pense. Vous pouvez aussi prendre le métro : deux stations et vous y êtes.", "About fifteen minutes. You could also take the subway — it's just two stops."),
        ln("马克", "地铁站在哪儿？", "Dìtiězhàn zài nǎr?", "Où est la station de métro ?", "Where's the subway station?"),
        ln("路人", "过了马路就是。你一出地铁站就能看见公园的大门。", "Guòle mǎlù jiù shì. Nǐ yì chū dìtiězhàn jiù néng kànjiàn gōngyuán de dàmén.", "Juste de l'autre côté de la rue. Dès que vous sortez du métro, vous verrez l'entrée du parc.", "Just across the road. As soon as you exit the station, you'll see the park gate."),
        ln("马克", "我还是走过去吧，今天天气很好。", "Wǒ háishi zǒu guòqu ba, jīntiān tiānqì hěn hǎo.", "Je vais plutôt y aller à pied, il fait beau aujourd'hui.", "I think I'll walk — the weather's nice today."),
        ln("路人", "好。往左拐以后，再往前走五百米。", "Hǎo. Wǎng zuǒ guǎi yǐhòu, zài wǎng qián zǒu wǔbǎi mǐ.", "D'accord. Après avoir tourné à gauche, continuez encore 500 mètres.", "OK. After you turn left, keep going another 500 metres."),
        ln("马克", "明白了，谢谢您！", "Míngbai le, xièxie nín!", "Compris, merci beaucoup !", "Got it, thank you!"),
        ln("路人", "不客气！找不到的话，再问问别人。", "Búkèqi! Zhǎo bu dào dehuà, zài wènwen biérén.", "De rien ! Si vous ne trouvez pas, redemandez à quelqu'un.", "You're welcome! If you can't find it, just ask someone else."),
      ],
    },
    vocab: ["路", "马路", "路口", "往", "前", "左", "右", "拐", "一直", "走", "过", "进", "出", "回", "地铁", "站", "公交车", "米", "公里", "多远", "东", "西", "南", "北", "门", "看见", "找", "地址", "别人", "明白"],
    grammar: ["hsk2-g45", "hsk2-g46", "hsk2-g47", "hsk2-g48", "hsk2-g49"],
    culture: {
      title: t("Nord, sud, est, ouest : s'orienter à la chinoise", "North, south, east, west: finding your way the Chinese way"),
      body: t(
        "À **Pékin** et dans beaucoup de villes du nord, construites sur un plan en damier orienté selon les points cardinaux, on indique souvent le chemin avec **东南西北** plutôt qu'avec gauche et droite : « 往北走，然后往东拐 ». Les noms de rues le reflètent : 东直门, 西单, 北京南站…\n\nDans le sud, aux rues plus sinueuses, on utilise davantage **左 / 右**.\n\nAstuce métro : les grandes stations ont de nombreuses **sorties** (出口) nommées A, B, C, D… Avant de sortir, vérifie laquelle est la plus proche de ta destination — ça peut t'éviter 10 minutes de marche !",
        "In **Beijing** and many northern cities, built on a grid aligned with the compass, people often give directions using **东南西北** rather than left and right: \"往北走，然后往东拐\". Street names reflect it: 东直门, 西单, 北京南站…\n\nIn the south, where streets wind more, people use **左 / 右** more often.\n\nSubway tip: big stations have many **exits** (出口) labelled A, B, C, D… Check which one is closest to your destination before leaving — it can save you a 10-minute walk!",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Tournez à droite au carrefour.", "Turn right at the intersection."), t("Allez tout droit, puis tournez à gauche au carrefour.", "Go straight, then turn left at the intersection."), t("Allez tout droit jusqu'au carrefour.", "Go straight to the intersection."), t("Tournez à gauche, puis allez tout droit.", "Turn left, then go straight.")], 1, { zh: "一直往前走，到了路口往左拐。", pinyin: "Yìzhí wǎng qián zǒu, dàole lùkǒu wǎng zuǒ guǎi." }),
      choice(P.correct, ["走往前。", "往前走。", "前往走。", "走前往。"], 1),
      choice(P.correct, ["他回来家了。", "他回家来了。", "他来回家了。", "他家回来了。"], 1, { explain: t("Le lieu se place entre le verbe et 来 / 去.", "The place goes between the verb and 来 / 去.") }),
      fill(P.fill, "火车站离这儿有", "远？", ["多", "多少", "几", "怎么"], 0, t("La gare est à quelle distance d'ici ?", "How far is the train station from here?")),
      fill(P.fill, "你一出地铁站", "能看见银行。", ["就", "才", "再", "也"], 0, t("Dès que tu sors du métro, tu verras la banque.", "As soon as you leave the subway, you'll see the bank.")),
      fill(P.fill, "我在家等你，你快回", "吧！", ["来", "去", "过", "出"], 0, t("Je t'attends à la maison, rentre vite !", "I'm waiting for you at home, come back soon!"), t("La personne qui parle est à la maison : mouvement vers elle → 来.", "The speaker is at home: movement towards them → 来.")),
      order(P.order, ["到了", "路口", "往", "右", "拐"], t("Au carrefour, tourne à droite.", "Turn right at the intersection.")),
      order(P.order, ["我", "一到", "就", "给你", "打电话"], t("Je t'appelle dès que j'arrive.", "I'll call you as soon as I arrive.")),
      listen("走路要十五分钟左右。", ["走路要五十分钟左右。", "坐车要十五分钟左右。", "走路要十五分钟左右。", "走路要一个小时左右。"], 2, t("À pied, il faut environ quinze minutes.", "It's about fifteen minutes on foot.")),
      listen("过了马路就是地铁站。", ["过了马路就是地铁站。", "过了马路就是火车站。", "马路对面没有地铁站。", "过了路口就是地铁站。"], 0, t("Juste de l'autre côté de la rue, c'est le métro.", "The subway station is just across the road.")),
      match(P.match, [
        ["路口", "lùkǒu", "carrefour", "intersection"],
        ["拐", "guǎi", "tourner", "turn"],
        ["一直", "yìzhí", "tout droit ; sans arrêt", "straight on; continuously"],
        ["马路", "mǎlù", "rue, route", "road, street"],
        ["地址", "dìzhǐ", "adresse", "address"],
      ]),
      choice(t("Tu veux savoir combien de temps prend le trajet. Tu demandes :", "You want to know how long the trip takes. You ask:"), ["要多远？", "要多长时间？", "要多少钱？", "要几个？"], 1),
    ],
  },
];
