import type { Lesson } from "../../types";
import { P, choice, fill, listen, ln, match, order, t } from "./helpers";

export const lessonsC: Lesson[] = [
  // ───────────────────────── L11 — Online shopping ─────────────────────────
  {
    id: "hsk2-l11",
    level: 2,
    order: 11,
    title: t("Acheter en ligne", "Shopping Online"),
    subtitle: t("Prix, livraison et retours", "Prices, delivery and returns"),
    theme: "tech",
    goals: [
      t("Poser une condition avec 如果…就…", "State a condition with 如果…就…"),
      t("Juger un délai ou un prix avec 就 et 才", "Judge a time or price with 就 and 才"),
      t("Lire et dire les grands nombres (百, 千, 万)", "Read and say big numbers (百, 千, 万)"),
      t("Dire « tout / rien » avec 什么都 (不)", "Say \"everything / nothing\" with 什么都 (不)"),
    ],
    dialogue: {
      context: t(
        "Début novembre. Anna trouve Xiao Lin les yeux rivés sur son téléphone.",
        "Early November. Anna finds Xiao Lin glued to her phone.",
      ),
      lines: [
        ln("安娜", "小林，你在看什么呢？", "Xiǎo Lín, nǐ zài kàn shénme ne?", "Xiao Lin, qu'est-ce que tu regardes ?", "Xiao Lin, what are you looking at?"),
        ln("小林", "我在网上买东西。“双十一”快到了，很多东西都打折。", "Wǒ zài wǎng shang mǎi dōngxi. “Shuāng Shíyī” kuài dào le, hěn duō dōngxi dōu dǎzhé.", "Je fais des achats en ligne. C'est bientôt le « Double 11 », plein de choses sont en promo.", "I'm shopping online. \"Double 11\" is coming, lots of things are on sale."),
        ln("安娜", "网上什么都能买到吗？", "Wǎng shang shénme dōu néng mǎidào ma?", "On peut tout acheter en ligne ?", "Can you buy everything online?"),
        ln("小林", "对，衣服、水果、电脑……什么都有。你看，这个手机才两千九百块！", "Duì, yīfu, shuǐguǒ, diànnǎo…… shénme dōu yǒu. Nǐ kàn, zhège shǒujī cái liǎngqiān jiǔbǎi kuài!", "Oui : vêtements, fruits, ordinateurs… il y a tout. Regarde, ce téléphone ne coûte que 2 900 yuans !", "Yes — clothes, fruit, computers… everything. Look, this phone is only 2,900 yuan!"),
        ln("安娜", "真便宜！可是如果不喜欢，怎么办？", "Zhēn piányi! Kěshì rúguǒ bù xǐhuan, zěnme bàn?", "Pas cher du tout ! Mais si on n'aime pas, on fait comment ?", "That's cheap! But what if you don't like it?"),
        ln("小林", "如果不满意，就可以退货。", "Rúguǒ bù mǎnyì, jiù kěyǐ tuìhuò.", "Si tu n'es pas satisfaite, tu peux le renvoyer.", "If you're not satisfied, you can return it."),
        ln("安娜", "快递要几天才能到？", "Kuàidì yào jǐ tiān cái néng dào?", "Il faut combien de jours pour la livraison ?", "How many days does delivery take?"),
        ln("小林", "很快！我上次今天下单，明天就到了。", "Hěn kuài! Wǒ shàng cì jīntiān xiàdān, míngtiān jiù dào le.", "C'est rapide ! La dernière fois, j'ai commandé un jour, c'est arrivé dès le lendemain.", "Really fast! Last time I ordered one day and it arrived the next."),
        ln("安娜", "我上个月买了一件衣服，一个星期才到。", "Wǒ shàng ge yuè mǎile yí jiàn yīfu, yí ge xīngqī cái dào.", "Le mois dernier, j'ai acheté un vêtement, il a mis une semaine à arriver.", "Last month I bought a top and it took a whole week to arrive."),
        ln("小林", "买东西以前，你要认真地看评价。", "Mǎi dōngxi yǐqián, nǐ yào rènzhēn de kàn píngjià.", "Avant d'acheter, il faut bien lire les avis.", "Before you buy, read the reviews carefully."),
        ln("安娜", "这家店有两万多个评价，应该不错。", "Zhè jiā diàn yǒu liǎngwàn duō ge píngjià, yīnggāi búcuò.", "Cette boutique a plus de 20 000 avis, elle doit être bien.", "This shop has over 20,000 reviews — it should be good."),
        ln("小林", "对。好了，我下单了！", "Duì. Hǎo le, wǒ xiàdān le!", "Exactement. Voilà, j'ai commandé !", "Right. Done — I've placed my order!"),
      ],
    },
    vocab: ["网上", "上网", "买", "卖", "东西", "手机", "电脑", "衣服", "打折", "便宜", "贵", "价格", "快递", "下单", "退货", "满意", "评价", "店", "如果", "就", "才", "百", "千", "万", "块", "元", "付钱", "认真", "怎么办"],
    grammar: ["hsk2-g50", "hsk2-g51", "hsk2-g52", "hsk2-g53", "hsk2-g54"],
    culture: {
      title: t("Le « Double 11 » (双十一)", "\"Double 11\" (双十一)"),
      body: t(
        "Le **11 novembre** (11/11) était à l'origine la « fête des célibataires » (光棍节), à cause des quatre « 1 » qui ressemblent à des personnes seules. En 2009, Alibaba en a fait une journée de promotions géantes : c'est aujourd'hui le **plus grand événement commercial du monde**, bien devant le Black Friday.\n\nLes Chinois achètent en ligne sur **淘宝** (Taobao), **京东** (JD) ou **拼多多** (Pinduoduo), et de plus en plus via des **lives** de vente sur Douyin (le TikTok chinois).\n\nLa livraison (**快递** kuàidì) est ultra-rapide et bon marché : les colis attendent souvent dans des **casiers automatiques** (快递柜) en bas des immeubles, qu'on ouvre avec un code.",
        "**11 November** (11/11) was originally \"Singles' Day\" (光棍节), because the four \"1\"s look like people standing alone. In 2009 Alibaba turned it into a massive sales day: it's now the **world's biggest shopping event**, far ahead of Black Friday.\n\nChinese shoppers buy on **淘宝** (Taobao), **京东** (JD) or **拼多多** (Pinduoduo), and increasingly through **live-stream sales** on Douyin (Chinese TikTok).\n\nDelivery (**快递** kuàidì) is super fast and cheap: parcels often wait in **smart lockers** (快递柜) at the foot of apartment buildings, opened with a code.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Le colis est arrivé tôt, dès le lendemain.", "The parcel arrived early, the next day."), t("Le colis a mis une semaine à arriver (c'est long).", "The parcel took a whole week to arrive (that's slow)."), t("Le colis arrive dans une semaine.", "The parcel will arrive in a week."), t("Le colis n'est pas arrivé.", "The parcel hasn't arrived.")], 1, { zh: "快递一个星期才到。", pinyin: "Kuàidì yí ge xīngqī cái dào." }),
      choice(P.correct, ["他十点才起床了。", "他十点才起床。", "才他十点起床。", "他才十点起床了。"], 1, { explain: t("Pas de 了 avec 才.", "No 了 with 才.") }),
      choice(t("Comment dit-on 20 000 en chinois ?", "How do you say 20,000 in Chinese?"), ["二十千", "两千", "两万", "二百万"], 2, { explain: t("Le chinois compte par 万 (10 000).", "Chinese counts in 万 (10,000).") }),
      fill(P.fill, "如果太贵，我", "不买了。", ["就", "才", "都", "还"], 0, t("Si c'est trop cher, je ne l'achète pas.", "If it's too expensive, I won't buy it.")),
      fill(P.fill, "我今天什么", "不想买。", ["都", "就", "才", "很"], 0, t("Aujourd'hui, je ne veux rien acheter.", "I don't want to buy anything today.")),
      fill(P.fill, "请慢慢", "说。", ["地", "得", "的", "了"], 0, t("Parle lentement, s'il te plaît.", "Please speak slowly."), t("Adverbe de manière avant le verbe → 地.", "Manner adverbial before the verb → 地.")),
      order(P.order, ["如果", "不满意", "你", "就", "可以退货"], t("Si tu n'es pas satisfait, tu peux renvoyer l'article.", "If you're not satisfied, you can return it.")),
      order(P.order, ["这个", "手机", "才", "两千块"], t("Ce téléphone ne coûte que 2 000 yuans.", "This phone is only 2,000 yuan.")),
      listen("一共三千八百块。", ["一共三千八百块。", "一共八千三百块。", "一共三百八十块。", "一共三千零八块。"], 0, t("Ça fait 3 800 yuans en tout.", "That's 3,800 yuan in total.")),
      listen("我昨天下单，今天就到了。", ["我昨天下单，明天就到。", "我今天下单，昨天就到了。", "我昨天下单，今天就到了。", "我昨天下单，今天还没到。"], 2, t("J'ai commandé hier et c'est déjà arrivé aujourd'hui.", "I ordered yesterday and it arrived today already.")),
      match(P.match, [
        ["快递", "kuàidì", "colis, livraison express", "parcel, courier"],
        ["打折", "dǎzhé", "faire une remise", "give a discount"],
        ["退货", "tuìhuò", "retourner un article", "return goods"],
        ["评价", "píngjià", "avis, évaluation", "review, rating"],
        ["满意", "mǎnyì", "satisfait", "satisfied"],
      ]),
      choice(P.correct, ["我不想买什么都。", "我什么都不想买。", "我都什么不想买。", "什么我不都想买。"], 1),
    ],
  },

  // ───────────────────────── L12 — Invitations ─────────────────────────
  {
    id: "hsk2-l12",
    level: 2,
    order: 12,
    title: t("Tu viens samedi ?", "Are You Coming on Saturday?"),
    subtitle: t("Inviter, accepter et s'étonner", "Inviting, accepting and showing surprise"),
    theme: "society",
    goals: [
      t("Vérifier une supposition avec 是不是", "Check an assumption with 是不是"),
      t("Proposer de façon détendue : 聊聊, 唱唱歌, V一下", "Make casual suggestions: 聊聊, 唱唱歌, V一下"),
      t("Faire deux choses à la fois : 一边…一边…", "Do two things at once: 一边…一边…"),
      t("Demander pourquoi et exprimer la surprise (为什么, 怎么)", "Ask why and show surprise (为什么, 怎么)"),
      t("Distinguer 再 et 又", "Tell 再 and 又 apart"),
    ],
    dialogue: {
      context: t(
        "Marc appelle Wang Li pour l'inviter à son anniversaire.",
        "Marc calls Wang Li to invite her to his birthday.",
      ),
      lines: [
        ln("马克", "喂，王丽，你周六是不是有空？", "Wéi, Wáng Lì, nǐ zhōuliù shì bu shì yǒu kòng?", "Allô, Wang Li ? Tu es libre samedi, non ?", "Hello, Wang Li? You're free on Saturday, aren't you?"),
        ln("王丽", "周六？有空啊。怎么了？", "Zhōuliù? Yǒu kòng a. Zěnme le?", "Samedi ? Oui, pourquoi ?", "Saturday? Yes, I'm free. What's up?"),
        ln("马克", "我过生日，想请几个朋友来我家吃饭。你能来吗？", "Wǒ guò shēngrì, xiǎng qǐng jǐ ge péngyou lái wǒ jiā chī fàn. Nǐ néng lái ma?", "C'est mon anniversaire, j'invite quelques amis à dîner chez moi. Tu peux venir ?", "It's my birthday — I'm inviting a few friends over for dinner. Can you come?"),
        ln("王丽", "当然能！生日快乐！几点？", "Dāngrán néng! Shēngrì kuàilè! Jǐ diǎn?", "Bien sûr ! Joyeux anniversaire ! À quelle heure ?", "Of course! Happy birthday! What time?"),
        ln("马克", "晚上六点。我们一边吃饭一边聊天，吃完再一起唱唱歌。", "Wǎnshang liù diǎn. Wǒmen yìbiān chī fàn yìbiān liáotiān, chīwán zài yìqǐ chàngchang gē.", "18 h. On discutera en mangeant, et après on chantera un peu ensemble.", "Six p.m. We'll chat over dinner, and then sing a bit together afterwards."),
        ln("王丽", "太好了！小张也来吗？", "Tài hǎo le! Xiǎo Zhāng yě lái ma?", "Super ! Xiao Zhang vient aussi ?", "Great! Is Xiao Zhang coming too?"),
        ln("马克", "他说他不来，我也不知道为什么。", "Tā shuō tā bù lái, wǒ yě bù zhīdào wèi shénme.", "Il a dit qu'il ne viendrait pas, je ne sais pas pourquoi.", "He said he's not coming — I don't know why."),
        ln("王丽", "他怎么又不来？上次聚会他也没来。", "Tā zěnme yòu bù lái? Shàng cì jùhuì tā yě méi lái.", "Comment ça, il ne vient encore pas ? Il n'était pas venu à la dernière fête non plus.", "How come he's not coming again? He didn't come to the last party either."),
        ln("马克", "可能他太忙了吧。你帮我问问他，好吗？", "Kěnéng tā tài máng le ba. Nǐ bāng wǒ wènwen tā, hǎo ma?", "Il est peut-être trop occupé. Tu peux lui demander pour moi ?", "Maybe he's too busy. Could you ask him for me?"),
        ln("王丽", "好，我等一下给他打电话。需要我带什么吗？", "Hǎo, wǒ děng yíxià gěi tā dǎ diànhuà. Xūyào wǒ dài shénme ma?", "D'accord, je l'appelle tout à l'heure. Je dois apporter quelque chose ?", "OK, I'll call him in a bit. Do you need me to bring anything?"),
        ln("马克", "什么都不用带，你人来就行！", "Shénme dōu búyòng dài, nǐ rén lái jiù xíng!", "N'apporte rien, viens juste !", "Don't bring anything — just come!"),
        ln("王丽", "那周六见！", "Nà zhōuliù jiàn!", "Alors à samedi !", "See you Saturday, then!"),
      ],
    },
    vocab: ["请", "生日", "快乐", "聚会", "有空", "参加", "聊天", "唱歌", "跳舞", "一边", "为什么", "怎么", "又", "再", "帮", "问", "需要", "带", "蛋糕", "客人", "欢迎", "喂", "电话", "忙", "知道", "上次", "当然", "见"],
    grammar: ["hsk2-g55", "hsk2-g56", "hsk2-g57", "hsk2-g58", "hsk2-g59"],
    culture: {
      title: t("Refuser pour la forme : le 客气 chinois", "Polite refusals: Chinese 客气"),
      body: t(
        "Quand on propose quelque chose (un cadeau, un plat, de l'aide), la politesse chinoise veut souvent qu'on **refuse une ou deux fois** avant d'accepter : 不用不用！/ 太客气了！ L'hôte, lui, **insiste**. C'est un petit jeu de **客气** (kèqi, « politesse, retenue ») que tout le monde connaît.\n\nSi on t'invite, apporte un petit cadeau : **fruits**, thé, spécialité de ton pays. Évite les **horloges** (送钟 sonne comme 送终, « accompagner un mourant ») et les objets par **quatre** (四 sì ressemble à 死 sǐ, « mourir »).\n\nEt quand quelqu'un dit 我请客 (« c'est moi qui invite »), ça veut dire qu'il **paie** !",
        "When something is offered (a gift, food, help), Chinese etiquette often calls for **declining once or twice** before accepting: 不用不用！/ 太客气了！ The host **insists**. It's a little ritual of **客气** (kèqi, \"politeness, restraint\") everyone knows.\n\nIf you're invited, bring a small gift: **fruit**, tea, a speciality from your country. Avoid **clocks** (送钟 sounds like 送终, \"attend a deathbed\") and things in **fours** (四 sì sounds like 死 sǐ, \"die\").\n\nAnd when someone says 我请客 (\"it's my treat\"), it means they're **paying**!",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Tu es libre samedi, non ?", "You're free on Saturday, aren't you?"), t("Tu n'es pas libre samedi.", "You're not free on Saturday."), t("Tu étais libre samedi ?", "Were you free on Saturday?"), t("Pourquoi tu es libre samedi ?", "Why are you free on Saturday?")], 0, { zh: "你周六是不是有空？", pinyin: "Nǐ zhōuliù shì bu shì yǒu kòng?" }),
      choice(P.correct, ["他昨天来了，今天再来了。", "他昨天来了，今天又来了。", "他昨天来了，今天又来。", "他昨天来了，今天来又了。"], 1, { explain: t("Répétition déjà réalisée → 又 + V + 了.", "Repetition that already happened → 又 + V + 了.") }),
      choice(P.correct, ["我们去公园散步散步吧。", "我们去公园散散步吧。", "我们去公园散步步吧。", "我们去公园散散步步吧。"], 1, { explain: t("Verbe séparable : on ne redouble que la partie verbale (散散步).", "Separable verb: only the verb part repeats (散散步).") }),
      fill(P.fill, "我们一边吃饭", "聊天吧。", ["一边", "又", "也", "还"], 0, t("Discutons en mangeant.", "Let's chat while we eat.")),
      fill(P.fill, "欢迎你下次", "来！", ["再", "又", "还是", "才"], 0, t("Reviens quand tu veux !", "Come again next time!")),
      fill(P.fill, "你", "了？不舒服吗？", ["怎么", "为什么", "什么", "哪儿"], 0, t("Qu'est-ce qui t'arrive ? Tu ne te sens pas bien ?", "What's wrong? Are you unwell?")),
      order(P.order, ["他", "喜欢", "一边", "听音乐", "一边", "跑步"], t("Il aime courir en écoutant de la musique.", "He likes to run while listening to music.")),
      order(P.order, ["你", "为什么", "不去", "参加", "聚会"], t("Pourquoi tu ne vas pas à la fête ?", "Why aren't you going to the party?")),
      listen("你帮我问问他，好吗？", ["你帮我问问他，好吗？", "你帮我看看他，好吗？", "你帮他问问我，好吗？", "你去问问他，好吗？"], 0, t("Tu peux lui demander pour moi ?", "Could you ask him for me?")),
      listen("你怎么还没到？大家都在等你。", ["你怎么还没到？大家都在找你。", "你为什么没来？大家都在等你。", "你怎么还没到？大家都在等你。", "你怎么已经到了？大家都在等你。"], 2, t("Comment ça, tu n'es pas encore là ? Tout le monde t'attend.", "How come you're not here yet? Everyone's waiting for you.")),
      match(P.match, [
        ["聚会", "jùhuì", "fête, soirée", "party, get-together"],
        ["聊天", "liáotiān", "bavarder", "chat"],
        ["有空", "yǒu kòng", "être libre", "be free"],
        ["蛋糕", "dàngāo", "gâteau", "cake"],
        ["需要", "xūyào", "avoir besoin", "need"],
      ]),
      choice(t("Ton ami arrive en retard sans prévenir. Tu es surpris et un peu fâché. Tu dis :", "Your friend turns up late without warning. You're surprised and a bit annoyed. You say:"), ["你怎么才来？", "你怎么样来？", "你是不是来？", "你再来了？"], 0),
    ],
  },

  // ───────────────────────── L13 — Comparing things ─────────────────────────
  {
    id: "hsk2-l13",
    level: 2,
    order: 13,
    title: t("Lequel choisir ?", "Which One to Choose?"),
    subtitle: t("Comparer deux produits avant d'acheter", "Comparing two products before buying"),
    theme: "shopping",
    goals: [
      t("Dire que deux choses sont pareilles ou différentes (跟…一样)", "Say two things are the same or different (跟…一样)"),
      t("Dire « pas aussi… que » avec 没有", "Say \"not as… as\" with 没有"),
      t("Renforcer une comparaison : 更, 最, 这么, 那么", "Strengthen comparisons: 更, 最, 这么, 那么"),
      t("Désigner un objet sans le nommer : 白的, 便宜一点儿的", "Refer to things without naming them: 白的, 便宜一点儿的"),
    ],
    dialogue: {
      context: t(
        "Anna veut changer de téléphone. Elle hésite dans un magasin avec Xiao Lin.",
        "Anna wants a new phone. She's hesitating in a shop with Xiao Lin.",
      ),
      lines: [
        ln("安娜", "小林，这两个手机，你觉得哪个好？", "Xiǎo Lín, zhè liǎng ge shǒujī, nǐ juéde nǎge hǎo?", "Xiao Lin, entre ces deux téléphones, lequel tu préfères ?", "Xiao Lin, which of these two phones do you think is better?"),
        ln("小林", "白的比黑的小一点儿，可是黑的更便宜。", "Bái de bǐ hēi de xiǎo yìdiǎnr, kěshì hēi de gèng piányi.", "Le blanc est un peu plus petit que le noir, mais le noir est moins cher.", "The white one is a bit smaller than the black one, but the black one is cheaper."),
        ln("安娜", "请问，黑的多少钱？", "Qǐngwèn, hēi de duōshao qián?", "Excusez-moi, le noir coûte combien ?", "Excuse me, how much is the black one?"),
        ln("售货员", "黑的三千二，白的三千八。", "Hēi de sānqiān èr, bái de sānqiān bā.", "Le noir 3 200, le blanc 3 800.", "The black one is 3,200, the white one 3,800."),
        ln("安娜", "这两个手机颜色不一样，别的都一样吗？", "Zhè liǎng ge shǒujī yánsè bù yíyàng, bié de dōu yíyàng ma?", "Ils n'ont pas la même couleur, mais le reste est identique ?", "They're different colours — is everything else the same?"),
        ln("售货员", "不太一样。黑的没有白的那么快，照相也没有白的好。", "Bú tài yíyàng. Hēi de méiyǒu bái de nàme kuài, zhàoxiàng yě méiyǒu bái de hǎo.", "Pas tout à fait. Le noir n'est pas aussi rapide que le blanc, et l'appareil photo est moins bon.", "Not quite. The black one isn't as fast as the white one, and the camera isn't as good."),
        ln("安娜", "我最喜欢照相，那我要白的吧。", "Wǒ zuì xǐhuan zhàoxiàng, nà wǒ yào bái de ba.", "Ce que je préfère, c'est prendre des photos. Alors je prends le blanc.", "Photography is my favourite thing, so I'll take the white one."),
        ln("小林", "可是白的贵六百块呢。有没有便宜一点儿的？", "Kěshì bái de guì liùbǎi kuài ne. Yǒu méiyǒu piányi yìdiǎnr de?", "Mais le blanc coûte 600 de plus. Vous n'en avez pas un un peu moins cher ?", "But the white one is 600 more. Do you have a cheaper one?"),
        ln("售货员", "这个蓝的跟白的一样，只是小一点儿，才三千五。", "Zhège lán de gēn bái de yíyàng, zhǐshì xiǎo yìdiǎnr, cái sānqiān wǔ.", "Ce bleu est pareil que le blanc, juste un peu plus petit, et seulement 3 500.", "This blue one is the same as the white one, just a bit smaller — only 3,500."),
        ln("安娜", "这个颜色真好看！没想到蓝的这么漂亮。", "Zhège yánsè zhēn hǎokàn! Méi xiǎngdào lán de zhème piàoliang.", "Cette couleur est super jolie ! Je ne pensais pas que le bleu serait si beau.", "What a lovely colour! I didn't expect the blue one to be so pretty."),
        ln("小林", "我也觉得蓝的最好看。", "Wǒ yě juéde lán de zuì hǎokàn.", "Moi aussi, je trouve que le bleu est le plus joli.", "I think the blue one looks best too."),
        ln("安娜", "好，就要这个蓝的！", "Hǎo, jiù yào zhège lán de!", "Allez, je prends le bleu !", "OK, I'll take the blue one!"),
      ],
    },
    vocab: ["比较", "一样", "不一样", "没有", "这么", "那么", "更", "最", "颜色", "白", "黑", "红", "蓝", "大小", "新", "旧", "贵", "便宜", "好看", "照相", "手机", "商场", "售货员", "觉得", "别的", "快", "用", "选"],
    grammar: ["hsk2-g60", "hsk2-g61", "hsk2-g62", "hsk2-g63", "hsk2-g64"],
    culture: {
      title: t("Le chiffre 8 et l'art de marchander", "The number 8 and the art of bargaining"),
      body: t(
        "Tu as remarqué les prix en **8** (3 888, 168…) ? **八** (bā) sonne comme **发** (fā, « s'enrichir ») : c'est le chiffre porte-bonheur. Les JO de Pékin ont commencé le 08/08/2008 à 20 h 08 !\n\nDans les centres commerciaux et en ligne, les prix sont **fixes**. Mais sur les **marchés** et dans les petites boutiques touristiques, on **marchande** (讲价 jiǎngjià) : commence à environ la moitié du prix annoncé, souris, et fais mine de partir — le vendeur te rappellera souvent : 好好好，便宜一点儿给你！",
        "Noticed prices ending in **8** (3,888, 168…)? **八** (bā) sounds like **发** (fā, \"get rich\"): it's the lucky number. The Beijing Olympics opened on 08/08/2008 at 8:08 p.m.!\n\nIn malls and online, prices are **fixed**. But at **markets** and small tourist shops, people **bargain** (讲价 jiǎngjià): start at about half the asking price, smile, and pretend to walk away — the seller will often call you back: 好好好，便宜一点儿给你！",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Le métro est plus rapide que le taxi.", "The subway is faster than a taxi."), t("Le métro n'est pas aussi rapide que le taxi.", "The subway isn't as fast as a taxi."), t("Le métro est aussi rapide que le taxi.", "The subway is as fast as a taxi."), t("Il n'y a pas de métro ni de taxi.", "There's no subway or taxi.")], 1, { zh: "地铁没有出租车那么快。", pinyin: "Dìtiě méiyǒu chūzūchē nàme kuài." }),
      choice(P.correct, ["这个一样大跟那个。", "这个跟那个一样大。", "这个跟那个大一样。", "跟那个这个一样大。"], 1),
      choice(t("Tu veux le modèle rouge. Tu dis :", "You want the red model. You say:"), ["我要红。", "我要红的。", "我要红了。", "我要很红。"], 1, { explain: t("On garde 的 quand on supprime le nom.", "Keep 的 when you drop the noun.") }),
      fill(P.fill, "这个没有那个", "贵。", ["那么", "很", "更", "最"], 0, t("Celui-ci n'est pas aussi cher que celui-là.", "This one isn't as expensive as that one.")),
      fill(P.fill, "三个手机里，这个", "便宜。", ["最", "更", "比", "一样"], 0, t("Parmi les trois téléphones, celui-ci est le moins cher.", "Of the three phones, this one is the cheapest.")),
      fill(P.fill, "我的手机", "你的一样。", ["跟", "比", "没有", "对"], 0, t("J'ai le même téléphone que toi.", "My phone is the same as yours.")),
      order(P.order, ["坐高铁", "比", "坐飞机", "更", "方便"], t("Le TGV est encore plus pratique que l'avion.", "Taking the high-speed train is even more convenient than flying.")),
      order(P.order, ["有没有", "便宜", "一点儿", "的"], t("Vous en avez un un peu moins cher ?", "Do you have a slightly cheaper one?")),
      listen("这两件衣服的颜色不一样。", ["这两件衣服的颜色一样。", "这两件衣服的大小不一样。", "这两件衣服的颜色不一样。", "这两双鞋的颜色不一样。"], 2, t("Ces deux vêtements n'ont pas la même couleur.", "These two garments are different colours.")),
      listen("中文没有你想的那么难。", ["中文没有你想的那么难。", "中文比你想的更难。", "中文跟你想的一样难。", "英文没有你想的那么难。"], 0, t("Le chinois n'est pas aussi difficile que tu le penses.", "Chinese isn't as hard as you think.")),
      match(P.match, [
        ["一样", "yíyàng", "pareil", "the same"],
        ["颜色", "yánsè", "couleur", "colour"],
        ["更", "gèng", "encore plus", "even more"],
        ["旧", "jiù", "vieux, usé", "old, used"],
        ["售货员", "shòuhuòyuán", "vendeur", "shop assistant"],
      ]),
      choice(P.correct, ["这个比那个不贵。", "这个没有那个很贵。", "这个没有那个贵。", "这个不有那个贵。"], 2),
    ],
  },

  // ───────────────────────── L14 — Describing people ─────────────────────────
  {
    id: "hsk2-l14",
    level: 2,
    order: 14,
    title: t("Qui est sur la photo ?", "Who's in the Photo?"),
    subtitle: t("Décrire l'apparence et le caractère", "Describing looks and personality"),
    theme: "family",
    goals: [
      t("Décrire l'apparence physique avec 长得 + adjectif", "Describe appearance with 长得 + adjective"),
      t("Décrire des vêtements et accessoires avec 着", "Describe clothing and accessories with 着"),
      t("Décrire une scène : 墙上挂着…", "Describe a scene: 墙上挂着…"),
      t("Parler d'un groupe avec 有的…有的…", "Talk about a group with 有的…有的…"),
    ],
    dialogue: {
      context: t(
        "Marc est invité chez Wang Li. Il remarque une photo au mur du salon.",
        "Marc is visiting Wang Li. He notices a photo on the living-room wall.",
      ),
      lines: [
        ln("马克", "墙上挂着的这张照片是你们的全家福吗？", "Qiáng shang guàzhe de zhè zhāng zhàopiàn shì nǐmen de quánjiāfú ma?", "La photo accrochée au mur, c'est votre photo de famille ?", "Is the photo on the wall your family portrait?"),
        ln("王丽", "对，是去年春节照的。", "Duì, shì qùnián Chūnjié zhào de.", "Oui, elle a été prise à la fête du Printemps l'an dernier.", "Yes, it was taken at Spring Festival last year."),
        ln("马克", "这个戴着眼镜的人是谁？", "Zhège dàizhe yǎnjìng de rén shì shéi?", "Qui est la personne avec des lunettes ?", "Who's the person wearing glasses?"),
        ln("王丽", "是我爸爸。他个子很高，一米八。", "Shì wǒ bàba. Tā gèzi hěn gāo, yì mǐ bā.", "C'est mon père. Il est très grand, 1,80 m.", "That's my dad. He's very tall — 1.8 metres."),
        ln("马克", "你长得跟你妈妈很像，眼睛大大的。", "Nǐ zhǎng de gēn nǐ māma hěn xiàng, yǎnjing dàdà de.", "Tu ressembles beaucoup à ta mère, avec tes grands yeux.", "You look a lot like your mom — big eyes."),
        ln("王丽", "大家都这么说！你看，旁边穿着红衣服的是我妹妹。", "Dàjiā dōu zhème shuō! Nǐ kàn, pángbiān chuānzhe hóng yīfu de shì wǒ mèimei.", "Tout le monde le dit ! Regarde, à côté, celle en rouge, c'est ma petite sœur.", "Everyone says that! Look, the one next to her in red is my little sister."),
        ln("马克", "她头发长长的，真漂亮。她人怎么样？", "Tā tóufa chángcháng de, zhēn piàoliang. Tā rén zěnmeyàng?", "Elle a de longs cheveux, elle est très jolie. Elle est comment, comme personne ?", "She has long hair — very pretty. What's she like?"),
        ln("王丽", "她很热情，也很爱笑。", "Tā hěn rèqíng, yě hěn ài xiào.", "Elle est très chaleureuse, et elle rit tout le temps.", "She's very warm, and she's always smiling."),
        ln("马克", "你的朋友们呢？都是什么样的人？", "Nǐ de péngyoumen ne? Dōu shì shénme yàng de rén?", "Et tes amis ? Ils sont comment ?", "And your friends? What are they like?"),
        ln("王丽", "有的很安静，有的很爱说话。", "Yǒude hěn ānjìng, yǒude hěn ài shuōhuà.", "Certains sont très calmes, d'autres très bavards.", "Some are very quiet, some are real chatterboxes."),
        ln("马克", "那我呢？你觉得我怎么样？", "Nà wǒ ne? Nǐ juéde wǒ zěnmeyàng?", "Et moi ? Tu me trouves comment ?", "And me? What do you think of me?"),
        ln("王丽", "你啊，人很好，就是有点儿爱迟到！", "Nǐ a, rén hěn hǎo, jiùshì yǒudiǎnr ài chídào!", "Toi ? Tu es très gentil, mais tu as un peu tendance à être en retard !", "You? You're a great guy — just a bit prone to being late!"),
      ],
    },
    vocab: ["长", "像", "个子", "高", "矮", "胖", "瘦", "头发", "眼睛", "脸", "穿", "戴", "眼镜", "衬衫", "裤子", "裙子", "鞋", "帽子", "照片", "挂", "墙", "热情", "安静", "漂亮", "帅", "爱", "笑", "年轻", "迟到"],
    grammar: ["hsk2-g65", "hsk2-g66", "hsk2-g67", "hsk2-g68", "hsk2-g69"],
    culture: {
      title: t("Compliments, modestie et franchise", "Compliments, modesty and frankness"),
      body: t(
        "Quand on reçoit un compliment en Chine, la réponse traditionnelle est de le **refuser modestement** : **哪里哪里** (« où ça, où ça ? ») ou **没有没有**. Aujourd'hui, un simple 谢谢 est aussi très courant chez les jeunes.\n\nÀ l'inverse, certains commentaires sur le **physique** qui paraîtraient impolis en France sont souvent dits avec bienveillance : **你胖了** (« tu as grossi ») ou **你瘦了** (« tu as maigri ») peuvent simplement montrer qu'on fait attention à toi.\n\nLa taille se dit souvent en mètres : **一米七** = 1,70 m.",
        "When you get a compliment in China, the traditional response is to **modestly deflect** it: **哪里哪里** (\"where, where?\") or **没有没有**. Nowadays, a simple 谢谢 is also common among young people.\n\nConversely, some comments on **appearance** that would seem rude in the West are often meant kindly: **你胖了** (\"you've put on weight\") or **你瘦了** (\"you've lost weight\") can simply show someone is paying attention to you.\n\nHeight is usually given in metres: **一米七** = 1.70 m.",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Elle achète des lunettes.", "She's buying glasses."), t("Elle porte des lunettes.", "She's wearing glasses."), t("Elle est en train de mettre ses lunettes.", "She's putting her glasses on."), t("Elle n'a pas de lunettes.", "She doesn't have glasses.")], 1, { zh: "她戴着眼镜。", pinyin: "Tā dàizhe yǎnjìng." }),
      choice(P.correct, ["一张照片挂着墙上。", "墙上挂着一张照片。", "墙上一张照片挂着。", "挂着墙上一张照片。"], 1, { explain: t("Phrase d'existence : lieu + V着 + chose.", "Existential sentence: place + V着 + thing.") }),
      choice(P.correct, ["她有很大大的眼睛。", "她有一双大大的眼睛。", "她有一双很大大的眼睛。", "她有一双大的大的眼睛。"], 1, { explain: t("Pas de 很 avec un adjectif redoublé.", "No 很 with a reduplicated adjective.") }),
      fill(P.fill, "他长", "很帅。", ["得", "的", "地", "着"], 0, t("Il est très beau.", "He's very handsome.")),
      fill(P.fill, "那个穿", "白衬衫的人是我哥哥。", ["着", "在", "得", "地"], 0, t("L'homme en chemise blanche, c'est mon grand frère.", "The man in the white shirt is my older brother.")),
      fill(P.fill, "我的同事有的很高，", "很矮。", ["有的", "有", "没有", "都"], 0, t("Parmi mes collègues, certains sont grands, d'autres petits.", "Some of my colleagues are tall, some are short.")),
      order(P.order, ["你", "长得", "跟你爸爸", "很像"], t("Tu ressembles beaucoup à ton père.", "You look a lot like your dad.")),
      order(P.order, ["桌子上", "放着", "很多", "书"], t("Il y a plein de livres posés sur la table.", "There are lots of books on the table.")),
      listen("我妹妹的头发长长的。", ["我妹妹的头发短短的。", "我妹妹的头发长长的。", "我姐姐的头发长长的。", "我妹妹的眼睛大大的。"], 1, t("Ma petite sœur a de longs cheveux.", "My little sister has long hair.")),
      listen("她人怎么样？", ["她长得怎么样？", "她人怎么样？", "她是什么人？", "她怎么了？"], 1, t("Elle est comment, comme personne ?", "What's she like as a person?")),
      match(P.match, [
        ["个子", "gèzi", "taille (d'une personne)", "height, build"],
        ["瘦", "shòu", "mince", "thin"],
        ["戴", "dài", "porter (lunettes, chapeau)", "wear (glasses, hat)"],
        ["热情", "rèqíng", "chaleureux", "warm, friendly"],
        ["帽子", "màozi", "chapeau", "hat"],
      ]),
      choice(P.correct, ["门不开着。", "门没开着。", "门开着没。", "门没开了着。"], 1, { explain: t("On nie V + 着 avec 没.", "Negate V + 着 with 没.") }),
    ],
  },

  // ───────────────────────── L15 — Past experiences ─────────────────────────
  {
    id: "hsk2-l15",
    level: 2,
    order: 15,
    title: t("Tu es déjà allé à la Grande Muraille ?", "Have You Been to the Great Wall?"),
    subtitle: t("Raconter ses expériences et ses souvenirs", "Talking about experiences and memories"),
    theme: "travel",
    goals: [
      t("Parler de ce qu'on a déjà fait (ou jamais) avec 过", "Talk about what you have (or never) done with 过"),
      t("Donner des détails sur un fait passé avec 是…的", "Give details about a past event with 是…的"),
      t("Raconter avec 以前 / 以后 et V + 了 + quantité", "Narrate with 以前 / 以后 and V + 了 + amount"),
      t("Insister sur une négation : 一次也没, 一点儿也不", "Stress a negative: 一次也没, 一点儿也不"),
    ],
    dialogue: {
      context: t(
        "Pendant la pause déjeuner, Xiao Zhang interroge Anna sur ses voyages en Chine.",
        "Over lunch, Xiao Zhang asks Anna about her travels in China.",
      ),
      lines: [
        ln("小张", "安娜，你去过长城吗？", "Ānnà, nǐ qùguo Chángchéng ma?", "Anna, tu es déjà allée à la Grande Muraille ?", "Anna, have you ever been to the Great Wall?"),
        ln("安娜", "去过两次。第一次是跟我父母一起去的。", "Qùguo liǎng cì. Dì-yī cì shì gēn wǒ fùmǔ yìqǐ qù de.", "Deux fois. La première fois, j'y suis allée avec mes parents.", "Twice. The first time, I went with my parents."),
        ln("小张", "是什么时候去的？", "Shì shénme shíhou qù de?", "C'était quand ?", "When was that?"),
        ln("安娜", "二〇一八年。那时候我一句中文也不会说。", "Èr líng yī bā nián. Nà shíhou wǒ yí jù Zhōngwén yě bú huì shuō.", "En 2018. À l'époque, je ne savais pas dire un mot de chinois.", "In 2018. Back then I couldn't say a single word of Chinese."),
        ln("小张", "真的吗？你们是怎么去的？", "Zhēn de ma? Nǐmen shì zěnme qù de?", "C'est vrai ? Vous y êtes allés comment ?", "Really? How did you get there?"),
        ln("安娜", "我们是坐公共汽车去的。那天我们爬了四个小时，拍了很多照片。", "Wǒmen shì zuò gōnggòng qìchē qù de. Nà tiān wǒmen pále sì ge xiǎoshí, pāile hěn duō zhàopiàn.", "En bus. Ce jour-là, on a marché quatre heures et pris plein de photos.", "By bus. That day we climbed for four hours and took loads of photos."),
        ln("小张", "累不累？", "Lèi bu lèi?", "C'était fatigant ?", "Was it tiring?"),
        ln("安娜", "我父母很累，我一点儿也不累！", "Wǒ fùmǔ hěn lèi, wǒ yìdiǎnr yě bú lèi!", "Mes parents étaient épuisés, moi pas du tout !", "My parents were exhausted, but I wasn't tired at all!"),
        ln("小张", "你吃过北京烤鸭没有？", "Nǐ chīguo Běijīng kǎoyā méiyǒu?", "Tu as déjà mangé du canard laqué ?", "Have you ever had Peking duck?"),
        ln("安娜", "吃过！来中国以前我就很想吃。你呢，你出过国吗？", "Chīguo! Lái Zhōngguó yǐqián wǒ jiù hěn xiǎng chī. Nǐ ne, nǐ chūguo guó ma?", "Oui ! Avant même de venir en Chine, j'avais très envie d'en goûter. Et toi, tu es déjà allé à l'étranger ?", "Yes! I wanted to try it even before I came to China. What about you — have you been abroad?"),
        ln("小张", "我一次也没出过国。以后我想去法国看看。", "Wǒ yí cì yě méi chūguo guó. Yǐhòu wǒ xiǎng qù Fǎguó kànkan.", "Jamais, pas une seule fois. Plus tard, j'aimerais aller voir la France.", "Never, not even once. Someday I'd like to visit France."),
        ln("安娜", "好啊！你来法国的时候，我带你去玩儿！", "Hǎo a! Nǐ lái Fǎguó de shíhou, wǒ dài nǐ qù wánr!", "Super ! Quand tu viendras en France, je te ferai visiter !", "Great! When you come to France, I'll show you around!"),
      ],
    },
    vocab: ["过", "以前", "以后", "那时候", "第一次", "次", "长城", "烤鸭", "爬", "拍", "照片", "父母", "出国", "国家", "从来", "去年", "小时候", "记得", "忘", "旅游", "公共汽车", "带", "玩儿", "句", "累", "年"],
    grammar: ["hsk2-g70", "hsk2-g71", "hsk2-g72", "hsk2-g73", "hsk2-g74"],
    culture: {
      title: t("« Qui n'a pas gravi la Grande Muraille n'est pas un héros »", "\"You're not a hero until you've climbed the Great Wall\""),
      body: t(
        "Ce vers de Mao Zedong, **不到长城非好汉**, est devenu un slogan touristique : tout le monde veut « prouver » sa visite par une photo (et parfois un certificat vendu sur place !).\n\nLa section la plus connue, **Badaling** (八达岭), est aussi la plus bondée. Beaucoup préfèrent **Mutianyu** (慕田峪), plus calme et bien restaurée, ou les sections « sauvages » comme **Jiankou** (箭扣), réservées aux randonneurs expérimentés.\n\nContrairement à une idée reçue, la Grande Muraille **n'est pas visible à l'œil nu depuis l'espace**. Mais elle mesure plus de **21 000 km** en comptant toutes ses sections !",
        "This line by Mao Zedong, **不到长城非好汉**, has become a tourist slogan: everyone wants to \"prove\" their visit with a photo (and sometimes a certificate sold on site!).\n\nThe best-known section, **Badaling** (八达岭), is also the most crowded. Many prefer **Mutianyu** (慕田峪), quieter and well restored, or \"wild\" sections like **Jiankou** (箭扣), for experienced hikers only.\n\nContrary to popular belief, the Great Wall **isn't visible to the naked eye from space**. But counting all its sections, it's over **21,000 km** long!",
      ),
    },
    exercises: [
      choice(P.meaning, [t("Je vais en Chine.", "I'm going to China."), t("Je suis déjà allé en Chine (au moins une fois).", "I've been to China (at least once)."), t("Je suis en Chine en ce moment.", "I'm in China right now."), t("Je ne suis jamais allé en Chine.", "I've never been to China.")], 1, { zh: "我去过中国。", pinyin: "Wǒ qùguo Zhōngguó." }),
      choice(P.correct, ["我没去过了长城。", "我没去过长城。", "我不去过长城。", "我没去长城过。"], 1, { explain: t("Négation de l'expérience : 没 + V + 过, sans 了.", "Negating experience: 没 + V + 过, no 了.") }),
      choice(P.correct, ["我是坐飞机来了。", "我是坐飞机来的。", "我坐飞机是来的。", "我是来的坐飞机。"], 1, { explain: t("Pour insister sur le moyen d'un fait passé : 是…的.", "To stress how a past event happened: 是…的.") }),
      fill(P.fill, "你吃", "北京烤鸭吗？", ["过", "着", "得", "地"], 0, t("Tu as déjà mangé du canard laqué ?", "Have you ever had Peking duck?")),
      fill(P.fill, "那个地方我一次", "没去过。", ["也", "就", "才", "还"], 0, t("Je ne suis jamais allé là-bas, pas une seule fois.", "I've never been there, not even once.")),
      fill(P.fill, "来中国", "，我一句中文也不会说，现在会说很多了。", ["以前", "以后", "的时候以前", "前以"], 0, t("Avant de venir en Chine, je ne savais pas dire un mot de chinois ; maintenant, j'en parle beaucoup.", "Before coming to China, I couldn't speak a word of Chinese; now I can say a lot.")),
      order(P.order, ["你", "是", "什么时候", "来中国", "的"], t("Tu es arrivé en Chine quand ?", "When did you come to China?")),
      order(P.order, ["去年", "我", "去了", "三个", "国家"], t("L'année dernière, je suis allé dans trois pays.", "Last year I went to three countries.")),
      listen("我从来没坐过高铁。", ["我从来没坐过高铁。", "我坐过两次高铁。", "我从来没坐过飞机。", "我昨天没坐高铁。"], 0, t("Je n'ai jamais pris le TGV chinois.", "I've never taken the high-speed train.")),
      listen("爬了一天山，我一点儿也不累。", ["爬了一天山，我有点儿累。", "爬了一天山，我累极了。", "爬了一天山，我一点儿也不累。", "爬了两天山，我一点儿也不累。"], 2, t("J'ai marché en montagne toute la journée, et je ne suis pas du tout fatigué.", "I hiked all day and I'm not tired at all.")),
      match(P.match, [
        ["出国", "chūguó", "aller à l'étranger", "go abroad"],
        ["拍", "pāi", "prendre (une photo)", "take (a photo)"],
        ["从来", "cónglái", "jamais (avec 没/不)", "never (with 没/不)"],
        ["父母", "fùmǔ", "parents", "parents"],
        ["记得", "jìde", "se souvenir", "remember"],
      ]),
      choice(t("Quelle phrase veut dire « Je n'y suis jamais allé » ?", "Which sentence means \"I've never been there\"?"), ["我没去。", "我没去过。", "我不去了。", "我去过了。"], 1),
    ],
  },
];
