import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsB: Lesson[] = [
  // ───────────────────────── L04 · Histoire ─────────────────────────
  {
    id: "hsk5-l04",
    level: 5,
    order: 4,
    title: t("Zhang Qian, l'homme qui ouvrit la route de la soie", "Zhang Qian, the man who opened the Silk Road"),
    subtitle: t("Histoire : lire un récit historique", "History: reading a historical narrative"),
    theme: "culture",
    goals: [
      t("Comprendre le passif écrit 为…所…", "Understand the written passive 为…所…"),
      t("Utiliser …之一 et 所 + V", "Use …之一 and 所 + V"),
      t("Marquer un retournement avec 不料", "Mark a twist with 不料"),
      t("Exprimer la surprise avec 竟然", "Express surprise with 竟然"),
    ],
    dialogue: {
      context: t(
        "Un court texte de vulgarisation historique sur Zhang Qian, envoyé de l'empereur Wu des Han au IIe siècle av. J.-C.",
        "A short popular-history text about Zhang Qian, envoy of Emperor Wu of Han in the 2nd century BC.",
      ),
      lines: [
        ln("—", "丝绸之路是人类历史上最重要的贸易路线之一。", "Sīchóu zhī Lù shì rénlèi lìshǐ shang zuì zhòngyào de màoyì lùxiàn zhī yī.", "La route de la soie est l'une des routes commerciales les plus importantes de l'histoire de l'humanité.", "The Silk Road is one of the most important trade routes in human history."),
        ln("—", "可是，打通这条路的张骞，他的故事却很少为人所知。", "Kěshì, dǎtōng zhè tiáo lù de Zhāng Qiān, tā de gùshi què hěn shǎo wéi rén suǒ zhī.", "Pourtant, l'histoire de Zhang Qian, qui a ouvert cette route, est peu connue.", "Yet the story of Zhang Qian, who opened this route, is little known."),
        ln("—", "两千多年前，汉朝的皇帝派张骞出使西域，希望联合其他国家对付匈奴。", "Liǎng qiān duō nián qián, Hàncháo de huángdì pài Zhāng Qiān chūshǐ Xīyù, xīwàng liánhé qítā guójiā duìfu Xiōngnú.", "Il y a plus de deux mille ans, l'empereur des Han envoya Zhang Qian en mission dans les « Contrées de l'Ouest », pour s'allier à d'autres royaumes contre les Xiongnu.", "Over two thousand years ago, the Han emperor sent Zhang Qian on a mission to the Western Regions to ally with other states against the Xiongnu."),
        ln("—", "不料，张骞刚出发不久，就被匈奴抓住了。", "Búliào, Zhāng Qiān gāng chūfā bùjiǔ, jiù bèi Xiōngnú zhuāzhù le.", "Mais contre toute attente, peu après son départ, Zhang Qian fut capturé par les Xiongnu.", "Unexpectedly, soon after setting out, Zhang Qian was captured by the Xiongnu."),
        ln("—", "他在匈奴生活了十年，竟然还在那里结婚生子。", "Tā zài Xiōngnú shēnghuó le shí nián, jìngrán hái zài nàlǐ jiéhūn shēng zǐ.", "Il vécut dix ans chez eux, et alla même jusqu'à s'y marier et avoir un enfant.", "He lived among the Xiongnu for ten years, and even married and had a child there."),
        ln("—", "可是他始终没有忘记自己的任务，最后终于找到机会逃了出来。", "Kěshì tā shǐzhōng méiyǒu wàngjì zìjǐ de rènwu, zuìhòu zhōngyú zhǎodào jīhuì táo le chūlái.", "Mais il n'oublia jamais sa mission et finit par trouver l'occasion de s'échapper.", "But he never forgot his mission, and finally found a chance to escape."),
        ln("—", "他继续向西走，到达了许多当时中原人从来没听说过的国家。", "Tā jìxù xiàng xī zǒu, dàodá le xǔduō dāngshí Zhōngyuán rén cónglái méi tīngshuō guo de guójiā.", "Il poursuivit vers l'ouest et atteignit de nombreux pays dont les Chinois de l'époque n'avaient jamais entendu parler.", "He carried on west and reached many countries the Chinese of the time had never heard of."),
        ln("—", "回国时，他又一次被抓，直到第十三年才回到长安。", "Huí guó shí, tā yòu yí cì bèi zhuā, zhídào dì-shísān nián cái huí dào Cháng'ān.", "Sur le chemin du retour, il fut de nouveau capturé et ne revint à Chang'an que la treizième année.", "On the way back he was captured again, and only returned to Chang'an in the thirteenth year."),
        ln("—", "出发时一百多人，回来的竟然只有两个人。", "Chūfā shí yìbǎi duō rén, huílái de jìngrán zhǐyǒu liǎng ge rén.", "Partis à plus de cent, ils ne furent que deux à revenir.", "Over a hundred set out; incredibly, only two came back."),
        ln("—", "张骞虽然没有完成联合的任务，但他所带回的信息，让汉朝第一次真正了解了西方。", "Zhāng Qiān suīrán méiyǒu wánchéng liánhé de rènwu, dàn tā suǒ dài huí de xìnxī, ràng Hàncháo dì-yī cì zhēnzhèng liǎojiě le xīfāng.", "Zhang Qian n'accomplit pas l'alliance, mais les informations qu'il rapporta permirent aux Han de connaître vraiment l'Occident pour la première fois.", "Though he didn't secure the alliance, the information he brought back let the Han truly understand the West for the first time."),
        ln("—", "从此，丝绸、茶叶从这里运往西方，葡萄等水果也传入了中国。", "Cóngcǐ, sīchóu, cháyè cóng zhèlǐ yùn wǎng xīfāng, pútao děng shuǐguǒ yě chuánrù le Zhōngguó.", "Dès lors, la soie et le thé partirent vers l'Ouest, tandis que le raisin et d'autres fruits arrivaient en Chine.", "From then on, silk and tea were shipped west, and fruits such as grapes came into China."),
        ln("—", "他的勇气和坚持，至今仍为人们所敬佩。", "Tā de yǒngqì hé jiānchí, zhìjīn réng wéi rénmen suǒ jìngpèi.", "Son courage et sa persévérance sont aujourd'hui encore admirés.", "His courage and perseverance are still admired today."),
      ],
    },
    vocab: ["丝绸", "人类", "历史", "贸易", "路线", "之一", "故事", "皇帝", "派", "联合", "对付", "不料", "出发", "抓", "竟然", "结婚", "始终", "忘记", "任务", "逃", "继续", "到达", "许多", "当时", "直到", "信息", "了解", "真正", "从此", "茶叶", "运", "传", "勇气", "至今", "敬佩", "机会"],
    grammar: ["hsk5-g21", "hsk5-g22", "hsk5-g25", "hsk5-g30", "hsk5-g32"],
    culture: {
      title: t("Des Han au « Nouvelles routes de la soie »", "From the Han to the \"Belt and Road\""),
      body: t(
        "La dynastie **Han** (206 av. J.-C. – 220 apr. J.-C.) a tellement marqué la Chine que les Chinois se désignent encore comme **汉族** (ethnie han), leur langue comme **汉语** et leur écriture comme **汉字**.\n\nL'expression « route de la soie » (**丝绸之路**) a en fait été inventée en 1877 par le géographe allemand Ferdinand von Richthofen. En 2013, la Chine a lancé le projet **« 一带一路 »** (« la Ceinture et la Route »), qui reprend explicitement l'image de Zhang Qian pour promouvoir des infrastructures entre l'Asie, l'Afrique et l'Europe.",
        "The **Han** dynasty (206 BC – 220 AD) left such a mark that Chinese people still call themselves **汉族** (Han ethnicity), their language **汉语** and their characters **汉字**.\n\nThe term \"Silk Road\" (**丝绸之路**) was actually coined in 1877 by German geographer Ferdinand von Richthofen. In 2013 China launched the **\"一带一路\"** (Belt and Road) initiative, explicitly invoking Zhang Qian to promote infrastructure links across Asia, Africa and Europe.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Que signifie 他的故事很少为人所知 ?", "What does 他的故事很少为人所知 mean?"),
        options: [
          t("Son histoire est peu connue.", "His story is little known."),
          t("Il connaît peu d'histoires.", "He knows few stories."),
          t("Il a raconté peu d'histoires.", "He told few stories."),
          t("Son histoire est très connue.", "His story is very well known."),
        ],
        answer: 0,
        explain: t("为 + agent + 所 + V = passif écrit (= 被人知道).", "为 + agent + 所 + V = written passive (= 被人知道)."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon mot.", "Fill in the right word."),
        before: "长城是世界上最有名的建筑",
        after: "。",
        options: ["之一", "一个", "之中", "其一"],
        answer: 0,
        tr: t("La Grande Muraille est l'une des constructions les plus célèbres au monde.", "The Great Wall is one of the world's most famous structures."),
        explain: t("…之一 = « l'un des… », toujours en fin de groupe.", "…之一 = \"one of…\", always at the end."),
      },
      {
        type: "fill",
        prompt: t("Complète le récit.", "Complete the story."),
        before: "本来计划周末去爬山，",
        after: "下了一场大雨。",
        options: ["不料", "于是", "从而", "何况"],
        answer: 0,
        tr: t("On avait prévu d'aller en montagne, mais contre toute attente, il a plu à verse.", "We'd planned to go hiking, but unexpectedly it poured."),
        explain: t("不料 introduit un retournement par rapport au plan.", "不料 introduces a twist against the plan."),
      },
      {
        type: "choice",
        prompt: t("Où placer 竟然 ?", "Where does 竟然 go?"),
        options: ["一个农民竟然当上了皇帝。", "竟然一个农民当上了皇帝吗？", "一个农民当上了竟然皇帝。", "一个农民当上了皇帝竟然。"],
        answer: 0,
        explain: t("竟然 est un adverbe : après le sujet, devant le verbe.", "竟然 is an adverb: after the subject, before the verb."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "据我",
        after: "知，这座寺庙建于唐朝。",
        options: ["所", "为", "之", "其"],
        answer: 0,
        tr: t("À ma connaissance, ce temple a été construit sous les Tang.", "As far as I know, this temple was built under the Tang."),
        explain: t("据我所知 = « à ma connaissance » (所 + V).", "据我所知 = \"as far as I know\" (所 + V)."),
      },
      {
        type: "choice",
        prompt: t("Combien de personnes sont revenues avec Zhang Qian ?", "How many people came back with Zhang Qian?"),
        options: [
          t("Deux", "Two"),
          t("Plus de cent", "Over a hundred"),
          t("Treize", "Thirteen"),
          t("Dix", "Ten"),
        ],
        answer: 0,
        explain: t("出发时一百多人，回来的竟然只有两个人。", "出发时一百多人，回来的竟然只有两个人。"),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["丝绸之路", "是", "最重要的", "贸易路线", "之一"],
        tr: t("La route de la soie est l'une des routes commerciales les plus importantes.", "The Silk Road is one of the most important trade routes."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["他的勇气", "至今", "仍", "为人们所", "敬佩"],
        tr: t("Son courage est aujourd'hui encore admiré.", "His courage is still admired today."),
      },
      {
        type: "listen",
        zh: "不料，张骞刚出发不久，就被匈奴抓住了。",
        options: ["不料，张骞刚出发不久，就被匈奴抓住了。", "于是，张骞刚出发不久，就被匈奴抓住了。", "不料，张骞刚回来不久，就被匈奴抓住了。", "不料，张骞出发很久，才被匈奴抓住。"],
        answer: 0,
        tr: t("Contre toute attente, peu après son départ, Zhang Qian fut capturé par les Xiongnu.", "Unexpectedly, soon after setting out, Zhang Qian was captured by the Xiongnu."),
      },
      {
        type: "listen",
        zh: "他竟然还在那里结婚生子。",
        options: ["他竟然还在那里结婚生子。", "他居然没在那里结婚。", "他竟然还在那里生活了十年。", "他始终没在那里结婚生子。"],
        answer: 0,
        tr: t("Il alla même jusqu'à s'y marier et avoir un enfant.", "He even married and had a child there."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "贸易", pinyin: "màoyì", tr: t("commerce", "trade") },
          { zh: "皇帝", pinyin: "huángdì", tr: t("empereur", "emperor") },
          { zh: "勇气", pinyin: "yǒngqì", tr: t("courage", "courage") },
          { zh: "始终", pinyin: "shǐzhōng", tr: t("du début à la fin, toujours", "from start to finish") },
          { zh: "敬佩", pinyin: "jìngpèi", tr: t("admirer, respecter", "to admire") },
        ],
      },
    ],
  },

  // ───────────────────────── L05 · Style littéraire ─────────────────────────
  {
    id: "hsk5-l05",
    level: 5,
    order: 5,
    title: t("La librairie de mon père", "My father's bookshop"),
    subtitle: t("Littérature : lire un extrait de nouvelle", "Literature: reading a short-story excerpt"),
    theme: "culture",
    goals: [
      t("Reconnaître le style écrit (书面语) d'un récit", "Recognise written style (书面语) in a narrative"),
      t("Comprendre et placer des 成语 dans la phrase", "Understand 成语 and place them in a sentence"),
      t("Exprimer un choix résolu avec 宁可…也不…", "Express a resolute choice with 宁可…也不…"),
      t("Nuancer avec 倒 et exprimer la contrariété avec 偏偏", "Nuance with 倒 and express frustration with 偏偏"),
    ],
    dialogue: {
      context: t(
        "Extrait d'une nouvelle (texte original, écrit pour Hanlu) : le narrateur raconte la vieille librairie de son père.",
        "Excerpt from a short story (original text written for Hanlu): the narrator recalls his father's old bookshop.",
      ),
      lines: [
        ln("—", "老街尽头有一家小书店，是父亲开了三十年的。", "Lǎo jiē jìntóu yǒu yì jiā xiǎo shūdiàn, shì fùqīn kāi le sānshí nián de.", "Au bout de la vieille rue se trouvait une petite librairie, que mon père tenait depuis trente ans.", "At the end of the old street stood a little bookshop my father had run for thirty years."),
        ln("—", "店面不大，书倒是不少，从古典诗词到外国小说，应有尽有。", "Diànmiàn bú dà, shū dàoshì bù shǎo, cóng gǔdiǎn shīcí dào wàiguó xiǎoshuō, yīng yǒu jìn yǒu.", "La boutique n'était pas grande, mais les livres, eux, ne manquaient pas : de la poésie classique aux romans étrangers, il y avait de tout.", "The shop wasn't big, but it had plenty of books — from classical poetry to foreign novels, everything you could want."),
        ln("—", "这些年，来买书的人越来越少，书店的生意一天不如一天。", "Zhèxiē nián, lái mǎi shū de rén yuè lái yuè shǎo, shūdiàn de shēngyi yì tiān bùrú yì tiān.", "Ces dernières années, les clients se faisaient de plus en plus rares, et les affaires déclinaient de jour en jour.", "In recent years, fewer and fewer people came to buy books, and business got worse by the day."),
        ln("我", "爸，现在大家都在网上买书，咱们把店卖了吧。", "Bà, xiànzài dàjiā dōu zài wǎng shang mǎi shū, zánmen bǎ diàn mài le ba.", "Papa, aujourd'hui tout le monde achète ses livres en ligne. Vendons la boutique.", "Dad, everyone buys books online now. Let's sell the shop."),
        ln("父亲", "不卖。我宁可每天少吃一顿饭，也不能让这家店关门。", "Bú mài. Wǒ nìngkě měi tiān shǎo chī yí dùn fàn, yě bù néng ràng zhè jiā diàn guānmén.", "Non. Je préfère sauter un repas par jour plutôt que de fermer cette boutique.", "No. I'd rather skip a meal a day than let this shop close."),
        ln("—", "父亲的脾气我是知道的，别人越劝，他偏偏越不听。", "Fùqīn de píqi wǒ shì zhīdào de, biérén yuè quàn, tā piānpiān yuè bù tīng.", "Je connaissais le caractère de mon père : plus on essayait de le convaincre, plus il s'entêtait.", "I knew my father's temper: the more people tried to persuade him, the more stubbornly he refused."),
        ln("—", "那年冬天特别冷，偏偏店里的暖气又坏了。", "Nà nián dōngtiān tèbié lěng, piānpiān diàn lǐ de nuǎnqì yòu huài le.", "Cet hiver-là fut particulièrement froid, et comme par hasard, le chauffage de la boutique tomba encore en panne.", "That winter was especially cold, and of course the shop's heating broke down again."),
        ln("—", "父亲穿着旧大衣，坐在柜台后面，全神贯注地读着一本发黄的书。", "Fùqīn chuān zhe jiù dàyī, zuò zài guìtái hòumiàn, quán shén guàn zhù de dú zhe yì běn fā huáng de shū.", "Mon père, dans son vieux manteau, était assis derrière le comptoir, absorbé dans la lecture d'un livre jauni.", "In his old coat, my father sat behind the counter, utterly absorbed in a yellowed book."),
        ln("—", "一个下雪的傍晚，一位白发老人推门进来，说要找一本早已买不到的诗集。", "Yí ge xià xuě de bàngwǎn, yí wèi bái fà lǎorén tuī mén jìnlái, shuō yào zhǎo yì běn zǎo yǐ mǎi bu dào de shījí.", "Un soir de neige, un vieil homme aux cheveux blancs poussa la porte et demanda un recueil de poèmes introuvable depuis longtemps.", "One snowy evening, a white-haired old man pushed the door open, looking for a poetry collection long out of print."),
        ln("—", "父亲二话不说，从书架最高处取下一本，轻轻擦去上面的灰。", "Fùqīn èr huà bù shuō, cóng shūjià zuì gāo chù qǔ xià yì běn, qīngqīng cā qù shàngmian de huī.", "Sans un mot, mon père en prit un sur la plus haute étagère et en essuya doucement la poussière.", "Without a word, my father took one down from the top shelf and gently wiped off the dust."),
        ln("—", "老人双手接过书，百感交集：“找了二十年，没想到在这儿找到了。”", "Lǎorén shuāng shǒu jiē guò shū, bǎi gǎn jiāo jí: “Zhǎo le èrshí nián, méi xiǎngdào zài zhèr zhǎodào le.”", "Le vieil homme prit le livre à deux mains, submergé par l'émotion : « Vingt ans que je le cherche, et c'est ici que je le trouve. »", "The old man took it in both hands, overwhelmed: \"Twenty years I've searched, and here it is.\""),
        ln("—", "那一刻我忽然明白，父亲守着的，不仅仅是一家书店。", "Nà yí kè wǒ hūrán míngbai, fùqīn shǒu zhe de, bù jǐnjǐn shì yì jiā shūdiàn.", "À cet instant, j'ai compris d'un coup que ce que mon père protégeait, c'était bien plus qu'une librairie.", "At that moment I suddenly understood that what my father was guarding was more than just a bookshop."),
      ],
    },
    vocab: ["尽头", "书店", "古典", "诗", "小说", "应有尽有", "生意", "宁可", "顿", "关门", "脾气", "劝", "偏偏", "暖气", "大衣", "全神贯注", "傍晚", "推", "早已", "书架", "取", "擦", "灰", "双手", "百感交集", "忽然", "明白", "守", "仅仅", "二话不说", "倒是", "柜台", "外国"],
    grammar: ["hsk5-g03", "hsk5-g13", "hsk5-g27", "hsk5-g28", "hsk5-g31"],
    culture: {
      title: t("Du chinois classique au 白话 : la révolution de 1919", "From Classical Chinese to 白话: the 1919 revolution"),
      body: t(
        "Jusqu'au début du XXe siècle, on écrivait en **文言文** (chinois classique), très différent de la langue parlée. En 1917-1919, lors du **Mouvement du 4 Mai** (五四运动), des intellectuels comme **胡适** et **鲁迅** ont défendu le **白话文**, l'écriture en langue vernaculaire. Le *Journal d'un fou* (《狂人日记》, 1918) de Lu Xun est considéré comme la première nouvelle moderne en 白话.\n\nMais le classique n'a jamais disparu : on le retrouve dans les **成语**, dans le **书面语** (于、此、其、早已…) et dans le style soutenu des récits. Maîtriser ce mélange est ce qui fait passer un lecteur du niveau intermédiaire au niveau avancé.",
        "Until the early 20th century, people wrote in **文言文** (Classical Chinese), very different from speech. In 1917–1919, during the **May Fourth Movement** (五四运动), intellectuals like **Hu Shi** and **Lu Xun** championed **白话文**, writing in the vernacular. Lu Xun's *Diary of a Madman* (《狂人日记》, 1918) is seen as the first modern short story in 白话.\n\nBut the classical language never vanished: it lives on in **成语**, in **written style** (于、此、其、早已…) and in formal narrative. Mastering this mix is what takes a reader from intermediate to advanced.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase du père.", "Complete the father's sentence."),
        before: "我宁可每天少吃一顿饭，",
        after: "不能让这家店关门。",
        options: ["也", "就", "才", "不如"],
        answer: 0,
        tr: t("Je préfère sauter un repas par jour plutôt que de fermer cette boutique.", "I'd rather skip a meal a day than let this shop close."),
        explain: t("宁可 A，也不 B : A est le sacrifice accepté, B est refusé.", "宁可 A，也不 B: A is the accepted sacrifice, B is refused."),
      },
      {
        type: "choice",
        prompt: t("« 店面不大，书倒是不少 » : quel est le rôle de 倒 ?", "\"店面不大，书倒是不少\": what does 倒 do?"),
        options: [
          t("Il marque un contraste avec ce qui précède.", "It marks a contrast with what came before."),
          t("Il signifie « tomber ».", "It means \"to fall\"."),
          t("Il indique une cause.", "It indicates a cause."),
          t("Il indique le futur.", "It marks the future."),
        ],
        answer: 0,
        explain: t("倒 (dào) = contraste : la boutique est petite, mais les livres, eux, sont nombreux.", "倒 (dào) = contrast: the shop is small, but the books are many."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon adverbe.", "Fill in the right adverb."),
        before: "我正要出门，",
        after: "下起了大雨。",
        options: ["偏偏", "正好", "终于", "毕竟"],
        answer: 0,
        tr: t("J'allais sortir, et justement il s'est mis à pleuvoir.", "I was about to go out when, of course, it started pouring."),
        explain: t("偏偏 = hasard contrariant. 正好 = heureux hasard.", "偏偏 = annoying coincidence. 正好 = lucky coincidence."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase utilise le 成语 correctement ?", "Which sentence uses the 成语 correctly?"),
        options: ["他全神贯注地读书。", "他很全神贯注地读书。", "他全神贯注了书。", "他读书得全神贯注地。"],
        answer: 0,
        explain: t("成语 + 地 + verbe (adverbial) ; pas de 很 devant un 成语 qui exprime déjà l'intensité.", "成语 + 地 + verb (adverbial); no 很 before a 成语 that already expresses intensity."),
      },
      {
        type: "choice",
        prompt: t("Quelle est la version orale de « 早已买不到 » ?", "What's the spoken version of \"早已买不到\"?"),
        options: ["早就买不到了", "早上买不到", "已经买到了", "马上买不到"],
        answer: 0,
        explain: t("早已 (écrit) = 早就…了 (oral) : « depuis longtemps ».", "早已 (written) = 早就…了 (spoken): \"long since\"."),
      },
      {
        type: "fill",
        prompt: t("Choisis le 成语 qui convient.", "Choose the fitting 成语."),
        before: "这家书店很小，可是各种书",
        after: "。",
        options: ["应有尽有", "二话不说", "百感交集", "全神贯注"],
        answer: 0,
        tr: t("Cette librairie est petite, mais on y trouve toutes sortes de livres.", "This bookshop is small, but it has every kind of book."),
        explain: t("应有尽有 = « tout ce qu'on peut souhaiter s'y trouve ».", "应有尽有 = \"everything one could wish for is there\"."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["别人越劝", "他", "偏偏", "越", "不听"],
        tr: t("Plus on essayait de le convaincre, plus il s'entêtait.", "The more people urged him, the more stubbornly he refused."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["父亲", "二话不说", "从书架上", "取下", "一本"],
        tr: t("Sans un mot, mon père en prit un sur l'étagère.", "Without a word, my father took one from the shelf."),
      },
      {
        type: "listen",
        zh: "书店的生意一天不如一天。",
        options: ["书店的生意一天不如一天。", "书店的生意一天比一天好。", "书店的生意跟以前一样。", "饭店的生意一天不如一天。"],
        answer: 0,
        tr: t("Les affaires de la librairie déclinaient de jour en jour.", "The bookshop's business got worse day by day."),
      },
      {
        type: "listen",
        zh: "父亲守着的，不仅仅是一家书店。",
        options: ["父亲守着的，不仅仅是一家书店。", "父亲开着的，仅仅是一家书店。", "父亲守着的，只是一家书店。", "父亲卖掉的，不仅仅是一家书店。"],
        answer: 0,
        tr: t("Ce que mon père protégeait, c'était bien plus qu'une librairie.", "What my father guarded was more than just a bookshop."),
      },
      {
        type: "match",
        prompt: t("Associe chaque 成语 à son sens.", "Match each 成语 to its meaning."),
        pairs: [
          { zh: "应有尽有", pinyin: "yīng yǒu jìn yǒu", tr: t("il y a de tout", "everything one could want") },
          { zh: "全神贯注", pinyin: "quán shén guàn zhù", tr: t("totalement concentré", "fully absorbed") },
          { zh: "二话不说", pinyin: "èr huà bù shuō", tr: t("sans discuter, sans un mot", "without a word") },
          { zh: "百感交集", pinyin: "bǎi gǎn jiāo jí", tr: t("submergé par les émotions", "overwhelmed with emotion") },
        ],
      },
    ],
  },

  // ───────────────────────── L06 · Psychologie ─────────────────────────
  {
    id: "hsk5-l06",
    level: 5,
    order: 6,
    title: t("L'angoisse du diplôme", "Graduation anxiety"),
    subtitle: t("Psychologie : une séance chez la psychologue", "Psychology: a counselling session"),
    theme: "feelings",
    goals: [
      t("Dédramatiser avec 难免 et 不至于", "Reassure with 难免 and 不至于"),
      t("Minimiser avec 只不过…而已", "Minimise with 只不过…而已"),
      t("Conseiller avec la question rhétorique 何必", "Advise with the rhetorical question 何必"),
      t("Délimiter un angle d'analyse avec 就…而言", "Set an angle of analysis with 就…而言"),
    ],
    dialogue: {
      context: t(
        "Xiao Chen, étudiant en dernière année, consulte la psychologue du service universitaire. C'est leur deuxième séance.",
        "Xiao Chen, a final-year student, sees the university counsellor. It's their second session.",
      ),
      lines: [
        ln("咨询师", "小陈，这两周感觉怎么样？", "Xiǎo Chén, zhè liǎng zhōu gǎnjué zěnmeyàng?", "Xiao Chen, comment tu te sens ces deux dernières semaines ?", "Xiao Chen, how have you been feeling these past two weeks?"),
        ln("小陈", "还是很焦虑。快毕业了，工作还没找到，晚上老是失眠。", "Háishi hěn jiāolǜ. Kuài bìyè le, gōngzuò hái méi zhǎodào, wǎnshang lǎoshì shīmián.", "Toujours très angoissé. Le diplôme approche, je n'ai pas encore trouvé de travail, et je n'arrête pas de faire des insomnies.", "Still very anxious. Graduation is close, I haven't found a job, and I keep having insomnia."),
        ln("咨询师", "面对这么大的变化，紧张是难免的，这很正常。", "Miànduì zhème dà de biànhuà, jǐnzhāng shì nánmiǎn de, zhè hěn zhèngcháng.", "Face à un changement aussi important, c'est inévitable d'être stressé. C'est tout à fait normal.", "Facing such a big change, it's inevitable to feel nervous. That's perfectly normal."),
        ln("小陈", "可是我的同学都拿到了好几个工作机会，就我一个没有。", "Kěshì wǒ de tóngxué dōu ná dào le hǎo jǐ ge gōngzuò jīhuì, jiù wǒ yí ge méiyǒu.", "Mais mes camarades ont tous décroché plusieurs offres, il n'y a que moi qui n'ai rien.", "But my classmates have all got several job offers — I'm the only one without any."),
        ln("小陈", "我觉得自己特别失败，以后恐怕连房租都付不起。", "Wǒ juéde zìjǐ tèbié shībài, yǐhòu kǒngpà lián fángzū dōu fù bu qǐ.", "Je me sens complètement nul, j'ai peur de ne même pas pouvoir payer un loyer plus tard.", "I feel like a total failure; I'm afraid I won't even be able to pay rent later."),
        ln("咨询师", "先别急着下结论。你只不过是比别人慢了一点儿而已，还不至于这么严重吧？", "Xiān bié jí zhe xià jiélùn. Nǐ zhǐbúguò shì bǐ biérén màn le yìdiǎnr éryǐ, hái bú zhìyú zhème yánzhòng ba?", "Ne tire pas de conclusions trop vite. Tu es simplement un peu plus lent que les autres, ce n'est quand même pas si grave, si ?", "Don't jump to conclusions. You're just a bit slower than others — it's surely not that serious?"),
        ln("咨询师", "而且，你何必总拿自己跟别人比呢？每个人的节奏不一样。", "Érqiě, nǐ hébì zǒng ná zìjǐ gēn biérén bǐ ne? Měi ge rén de jiézòu bù yíyàng.", "Et puis, à quoi bon te comparer sans cesse aux autres ? Chacun a son propre rythme.", "Besides, why keep comparing yourself to others? Everyone has their own pace."),
        ln("小陈", "道理我都明白，可是心里就是放不下。", "Dàolǐ wǒ dōu míngbai, kěshì xīn lǐ jiù shì fàng bu xià.", "Je comprends tout ça en théorie, mais je n'arrive pas à lâcher prise.", "I understand it in theory, but I just can't let it go."),
        ln("咨询师", "就心理学而言，焦虑本身并不是坏事，它提醒你要重视这件事。", "Jiù xīnlǐxué ér yán, jiāolǜ běnshēn bìng bú shì huài shì, tā tíxǐng nǐ yào zhòngshì zhè jiàn shì.", "Du point de vue de la psychologie, l'anxiété n'est pas mauvaise en soi : elle te rappelle que la chose compte pour toi.", "From a psychological point of view, anxiety itself isn't bad: it reminds you to take this seriously."),
        ln("咨询师", "问题在于，过度的焦虑会影响你的判断和行动。", "Wèntí zàiyú, guòdù de jiāolǜ huì yǐngxiǎng nǐ de pànduàn hé xíngdòng.", "Le problème, c'est qu'une anxiété excessive perturbe ton jugement et tes actions.", "The problem is that excessive anxiety affects your judgement and actions."),
        ln("小陈", "那我应该怎么调整呢？", "Nà wǒ yīnggāi zěnme tiáozhěng ne?", "Alors, comment je peux m'ajuster ?", "So how should I adjust?"),
        ln("咨询师", "试着把大目标分成小步骤，每天完成一点，再给自己一点肯定。", "Shìzhe bǎ dà mùbiāo fēn chéng xiǎo bùzhòu, měi tiān wánchéng yìdiǎn, zài gěi zìjǐ yìdiǎn kěndìng.", "Essaie de découper ton grand objectif en petites étapes, d'en accomplir un peu chaque jour, et de te féliciter un peu.", "Try splitting your big goal into small steps, finish a little each day, and give yourself some credit."),
        ln("小陈", "好的，我试试。跟您聊完，心里轻松多了。", "Hǎo de, wǒ shìshi. Gēn nín liáo wán, xīn lǐ qīngsōng duō le.", "D'accord, je vais essayer. Après avoir parlé avec vous, je me sens beaucoup plus léger.", "OK, I'll try. After talking with you, I feel much lighter."),
      ],
    },
    vocab: ["感觉", "焦虑", "毕业", "失眠", "面对", "变化", "紧张", "难免", "正常", "失败", "房租", "结论", "只不过", "而已", "不至于", "严重", "何必", "节奏", "道理", "心理", "本身", "提醒", "重视", "在于", "过度", "影响", "判断", "行动", "调整", "目标", "步骤", "肯定", "轻松", "聊"],
    grammar: ["hsk5-g09", "hsk5-g11", "hsk5-g18", "hsk5-g19", "hsk5-g24"],
    culture: {
      title: t("Santé mentale : un sujet qui sort de l'ombre", "Mental health: a topic coming out of the shadows"),
      body: t(
        "Longtemps, parler de ses problèmes psychologiques était mal vu en Chine : on craignait de **丢面子** (perdre la face) ou d'être jugé « fragile ». Les choses changent vite : les universités ont désormais des **心理咨询中心** (centres de consultation psychologique) et les jeunes parlent ouvertement d'**焦虑** (anxiété) ou d'**抑郁** (dépression) sur les réseaux sociaux.\n\nChaque été, près de **12 millions** de jeunes diplômés arrivent sur le marché du travail. Beaucoup préparent le concours de la fonction publique (**考公**), perçu comme un « bol de riz en fer » (**铁饭碗**), c'est-à-dire un emploi stable à vie.",
        "For a long time, talking about psychological problems was frowned upon in China: people feared **丢面子** (losing face) or being seen as \"weak\". That's changing fast: universities now have **心理咨询中心** (counselling centres), and young people openly discuss **焦虑** (anxiety) or **抑郁** (depression) on social media.\n\nEvery summer, nearly **12 million** new graduates enter the job market. Many prepare for the civil-service exam (**考公**), seen as an \"iron rice bowl\" (**铁饭碗**) — a job for life.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "刚开始工作，犯点儿错是",
        after: "的。",
        options: ["难免", "不免", "未必", "何必"],
        answer: 0,
        tr: t("Quand on débute, faire quelques erreurs, c'est inévitable.", "When you've just started, a few mistakes are inevitable."),
        explain: t("难免 peut être attribut (是难免的) ; 不免 est seulement adverbe.", "难免 can be a predicate (是难免的); 不免 is only an adverb."),
      },
      {
        type: "choice",
        prompt: t("Que veut dire « 还不至于这么严重吧 » ?", "What does \"还不至于这么严重吧\" mean?"),
        options: [
          t("Ce n'est quand même pas si grave.", "It's surely not that serious."),
          t("C'est très grave.", "It's very serious."),
          t("Ce n'est pas encore arrivé.", "It hasn't happened yet."),
          t("Ça va devenir grave.", "It's going to get serious."),
        ],
        answer: 0,
        explain: t("不至于 = ça ne va pas jusqu'à un résultat aussi extrême.", "不至于 = it doesn't go as far as such an extreme result."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "我只不过是开个玩笑",
        after: "，你别当真。",
        options: ["而已", "而且", "然而", "因而"],
        answer: 0,
        tr: t("Je ne faisais que plaisanter, ne le prends pas au sérieux.", "I was only joking — don't take it seriously."),
        explain: t("只不过…而已 = « ce n'est que…, rien de plus ».", "只不过…而已 = \"merely…, nothing more\"."),
      },
      {
        type: "choice",
        prompt: t("« 你何必总拿自己跟别人比呢？ » : que conseille la psychologue ?", "\"你何必总拿自己跟别人比呢？\": what is the counsellor advising?"),
        options: [
          t("Arrêter de se comparer aux autres", "Stop comparing yourself to others"),
          t("Se comparer davantage aux autres", "Compare yourself to others more"),
          t("Demander pourquoi on se compare", "Ask why you compare yourself"),
          t("Se comparer seulement aux meilleurs", "Only compare yourself to the best"),
        ],
        answer: 0,
        explain: t("何必 = question rhétorique : « inutile de… ».", "何必 = rhetorical question: \"there's no need to…\"."),
      },
      {
        type: "fill",
        prompt: t("Complète la structure.", "Complete the structure."),
        before: "就心理健康",
        after: "，睡眠和运动同样重要。",
        options: ["而言", "来看而言", "而且", "看来"],
        answer: 0,
        tr: t("En matière de santé mentale, le sommeil et le sport sont tout aussi importants.", "As far as mental health goes, sleep and exercise matter equally."),
        explain: t("就…而言 = « en ce qui concerne… ».", "就…而言 = \"as far as… is concerned\"."),
      },
      {
        type: "choice",
        prompt: t("Quel conseil pratique la psychologue donne-t-elle ?", "What practical advice does the counsellor give?"),
        options: [
          t("Découper l'objectif en petites étapes", "Break the goal into small steps"),
          t("Arrêter de chercher du travail", "Stop looking for work"),
          t("Dormir plus longtemps le matin", "Sleep in later"),
          t("Parler à ses camarades", "Talk to classmates"),
        ],
        answer: 0,
        explain: t("把大目标分成小步骤，每天完成一点。", "把大目标分成小步骤，每天完成一点。"),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["面对", "这么大的变化", "紧张", "是", "难免的"],
        tr: t("Face à un tel changement, c'est inévitable d'être stressé.", "Facing such a big change, feeling nervous is inevitable."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["过度的焦虑", "会", "影响", "你的判断", "和行动"],
        tr: t("Une anxiété excessive perturbe ton jugement et tes actions.", "Excessive anxiety affects your judgement and actions."),
      },
      {
        type: "listen",
        zh: "你只不过是比别人慢了一点儿而已。",
        options: ["你只不过是比别人慢了一点儿而已。", "你只不过是比别人快了一点儿而已。", "你不仅比别人慢了很多。", "你只是比别人晚来了一会儿。"],
        answer: 0,
        tr: t("Tu es simplement un peu plus lent que les autres, c'est tout.", "You're just a little slower than others, that's all."),
      },
      {
        type: "listen",
        zh: "道理我都明白，可是心里就是放不下。",
        options: ["道理我都明白，可是心里就是放不下。", "道理我都不明白，所以心里放不下。", "道路我都明白，可是心里就是放不下。", "道理我都明白，所以心里放下了。"],
        answer: 0,
        tr: t("Je comprends tout ça, mais je n'arrive pas à lâcher prise.", "I understand it all, but I just can't let it go."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "失眠", pinyin: "shīmián", tr: t("insomnie", "insomnia") },
          { zh: "节奏", pinyin: "jiézòu", tr: t("rythme", "rhythm, pace") },
          { zh: "调整", pinyin: "tiáozhěng", tr: t("ajuster", "to adjust") },
          { zh: "步骤", pinyin: "bùzhòu", tr: t("étape", "step") },
          { zh: "过度", pinyin: "guòdù", tr: t("excessif", "excessive") },
        ],
      },
    ],
  },
];
