import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsA: Lesson[] = [
  // ───────────────────────── L01 · Économie ─────────────────────────
  {
    id: "hsk5-l01",
    level: 5,
    order: 1,
    title: t("Des pommes vendues en direct", "Apples sold on livestream"),
    subtitle: t("Économie : e-commerce rural et nouvelles opportunités", "Economy: rural e-commerce and new opportunities"),
    theme: "society",
    goals: [
      t("Mettre l'accent sur une cause avec 之所以…是因为…", "Put the focus on a cause with 之所以…是因为…"),
      t("Enchaîner mesure et résultat avec 从而 et 以致", "Link measure and result with 从而 and 以致"),
      t("Décrire un contexte avec 在…下 et 一旦…就…", "Describe a context with 在…下 and 一旦…就…"),
      t("Lire les verbes formels en 于 (位于、高于、有助于)", "Read formal 于-verbs (位于、高于、有助于)"),
    ],
    dialogue: {
      context: t(
        "Une journaliste économique interviewe M. Zhou, un jeune entrepreneur qui vend en livestream les pommes de son village du Shaanxi.",
        "A business reporter interviews Mr Zhou, a young entrepreneur who sells his Shaanxi village's apples via livestream.",
      ),
      lines: [
        ln("记者", "周先生，听说您的网店去年的销售额高于一千万元？", "Zhōu xiānsheng, tīngshuō nín de wǎngdiàn qùnián de xiāoshòu'é gāo yú yìqiān wàn yuán?", "Monsieur Zhou, il paraît que le chiffre d'affaires de votre boutique en ligne a dépassé les dix millions de yuans l'an dernier ?", "Mr Zhou, I hear your online shop's sales topped ten million yuan last year?"),
        ln("小周", "是的。说实话，我们之所以能做得这么好，是因为赶上了直播带货的好时机。", "Shì de. Shuō shíhuà, wǒmen zhīsuǒyǐ néng zuò de zhème hǎo, shì yīnwèi gǎn shàng le zhíbō dài huò de hǎo shíjī.", "Oui. Franchement, si on a si bien réussi, c'est qu'on a su saisir le bon moment de la vente en livestream.", "Yes. Honestly, the reason we've done so well is that we caught the right moment for livestream selling."),
        ln("记者", "您的公司位于一个小山村，一开始有人相信你们吗？", "Nín de gōngsī wèiyú yí ge xiǎo shāncūn, yì kāishǐ yǒu rén xiāngxìn nǐmen ma?", "Votre entreprise se trouve dans un petit village de montagne. Au début, les gens vous faisaient confiance ?", "Your company is based in a small mountain village. Did anyone believe in you at first?"),
        ln("小周", "没有。村里的苹果质量很好，可是交通不便，以致很多水果烂在了地里。", "Méiyǒu. Cūn lǐ de píngguǒ zhìliàng hěn hǎo, kěshì jiāotōng búbiàn, yǐzhì hěn duō shuǐguǒ làn zài le dì lǐ.", "Non. Les pommes du village étaient excellentes, mais les transports étaient si mauvais que beaucoup de fruits pourrissaient dans les champs.", "No. The village apples were great, but transport was so poor that lots of fruit rotted in the fields."),
        ln("小周", "后来在政府的支持下，村里修了路，通了网络。", "Hòulái zài zhèngfǔ de zhīchí xià, cūn lǐ xiū le lù, tōng le wǎngluò.", "Ensuite, avec le soutien du gouvernement, le village a eu des routes et Internet.", "Later, with government support, the village got roads and internet access."),
        ln("小周", "我们通过直播直接把苹果卖给消费者，从而减少了中间环节。", "Wǒmen tōngguò zhíbō zhíjiē bǎ píngguǒ mài gěi xiāofèizhě, cóng'ér jiǎnshǎo le zhōngjiān huánjié.", "Grâce au livestream, nous vendons directement aux consommateurs, ce qui supprime des intermédiaires.", "Through livestreaming we sell apples straight to consumers, thereby cutting out middlemen."),
        ln("记者", "这对农民的收入有什么影响？", "Zhè duì nóngmín de shōurù yǒu shénme yǐngxiǎng?", "Quel impact cela a-t-il sur les revenus des agriculteurs ?", "What effect has this had on farmers' incomes?"),
        ln("小周", "影响很大。现在农民的收入比以前增加了一倍，也有助于年轻人回乡创业。", "Yǐngxiǎng hěn dà. Xiànzài nóngmín de shōurù bǐ yǐqián zēngjiā le yí bèi, yě yǒu zhù yú niánqīngrén huí xiāng chuàngyè.", "Un impact énorme. Les revenus des agriculteurs ont doublé, et ça encourage les jeunes à revenir créer leur entreprise au pays.", "A big one. Farmers' incomes have doubled, and it also helps young people come home to start businesses."),
        ln("记者", "不过，也有人担心直播行业竞争太激烈。", "Búguò, yě yǒu rén dānxīn zhíbō hángyè jìngzhēng tài jīliè.", "Certains craignent pourtant que la concurrence dans le livestream soit trop féroce.", "Still, some worry competition in livestreaming is too fierce."),
        ln("小周", "确实。一旦产品质量出了问题，顾客就会失去信任，网店很快就会倒闭。", "Quèshí. Yídàn chǎnpǐn zhìliàng chū le wèntí, gùkè jiù huì shīqù xìnrèn, wǎngdiàn hěn kuài jiù huì dǎobì.", "C'est vrai. Dès qu'il y a un problème de qualité, les clients perdent confiance et la boutique fait vite faillite.", "True. Once there's a quality problem, customers lose trust and the shop soon goes under."),
        ln("小周", "所以我们对每一箱苹果都进行严格检查。", "Suǒyǐ wǒmen duì měi yì xiāng píngguǒ dōu jìnxíng yángé jiǎnchá.", "C'est pourquoi nous contrôlons rigoureusement chaque caisse de pommes.", "That's why we strictly inspect every box of apples."),
        ln("记者", "最后，您对想创业的年轻人有什么建议？", "Zuìhòu, nín duì xiǎng chuàngyè de niánqīngrén yǒu shénme jiànyì?", "Pour finir, quel conseil donneriez-vous aux jeunes qui veulent se lancer ?", "Finally, what advice do you have for young people who want to start a business?"),
        ln("小周", "别只看到赚钱的一面。在市场经济下，诚信才是最大的财富。", "Bié zhǐ kàndào zhuàn qián de yí miàn. Zài shìchǎng jīngjì xià, chéngxìn cái shì zuì dà de cáifù.", "Ne regardez pas que l'argent. Dans une économie de marché, l'honnêteté est la plus grande richesse.", "Don't just look at the money side. In a market economy, integrity is the greatest asset."),
      ],
    },
    vocab: ["网店", "销售", "高于", "之所以", "直播", "时机", "位于", "质量", "交通", "以致", "烂", "政府", "支持", "网络", "消费者", "从而", "减少", "环节", "农民", "收入", "增加", "倍", "有助于", "创业", "行业", "竞争", "激烈", "确实", "一旦", "产品", "顾客", "失去", "信任", "倒闭", "严格", "检查", "市场", "诚信", "财富"],
    grammar: ["hsk5-g01", "hsk5-g06", "hsk5-g08", "hsk5-g14", "hsk5-g17", "hsk5-g29"],
    culture: {
      title: t("Les « villages Taobao » et le livestream", "\"Taobao villages\" and livestream selling"),
      body: t(
        "Depuis les années 2010, des milliers de **淘宝村** (« villages Taobao ») sont apparus : des villages où une grande partie des familles vivent du commerce en ligne. Avec la pandémie, le **直播带货** (vente en livestream) a explosé : des agriculteurs, des maires de village et des stars vendent en direct fruits, thé ou vêtements à des millions de spectateurs.\n\nLe 11 novembre, **双十一** (« double onze »), est la plus grande journée de shopping au monde. Mais les scandales de faux produits ont rappelé l'importance du **诚信** (honnêteté, fiabilité), une valeur centrale du commerce chinois depuis l'Antiquité.",
        "Since the 2010s, thousands of **淘宝村** (\"Taobao villages\") have emerged, where much of the village lives off e-commerce. With the pandemic, **直播带货** (livestream selling) exploded: farmers, village heads and celebrities sell fruit, tea or clothes live to millions of viewers.\n\n11 November, **双十一** (\"Double Eleven\"), is the world's biggest shopping day. But fake-product scandals have highlighted **诚信** (integrity, trustworthiness), a core value in Chinese commerce since ancient times.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["他之所以成功，是因为很努力。", "之所以他成功，是因为很努力。", "他之所以成功，所以很努力。", "因为他很努力，之所以成功。"],
        answer: 0,
        explain: t("之所以 se place après le sujet et la seconde partie commence par 是因为.", "之所以 follows the subject, and the second part starts with 是因为."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon connecteur.", "Fill in the right connector."),
        before: "政府降低了税收，",
        after: "促进了消费。",
        options: ["从而", "以致", "以免", "何况"],
        answer: 0,
        tr: t("Le gouvernement a baissé les impôts, ce qui a stimulé la consommation.", "The government cut taxes, thereby boosting consumption."),
        explain: t("从而 = résultat logique (souvent positif) d'une mesure. 以致 = conséquence fâcheuse.", "从而 = logical (often positive) result of a measure. 以致 = unfortunate consequence."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon connecteur.", "Fill in the right connector."),
        before: "公司盲目扩大生产，",
        after: "产品卖不出去。",
        options: ["以致", "从而", "以免", "况且"],
        answer: 0,
        tr: t("L'entreprise a augmenté sa production à l'aveugle, si bien que ses produits ne se vendaient plus.", "The company blindly expanded production, so its goods wouldn't sell."),
        explain: t("以致 introduit une conséquence négative qui s'est produite.", "以致 introduces a negative consequence that happened."),
      },
      {
        type: "fill",
        prompt: t("Complète la structure.", "Complete the structure."),
        before: "在政府的支持",
        after: "，村里通了网络。",
        options: ["下", "上", "中", "里"],
        answer: 0,
        tr: t("Avec le soutien du gouvernement, le village a eu Internet.", "With government support, the village got internet."),
        explain: t("在…的支持/帮助/影响下 : sous l'effet ou avec l'aide de.", "在…的支持/帮助/影响下: with the support/help/influence of."),
      },
      {
        type: "choice",
        prompt: t("« Cette année, la croissance est plus élevée que l'an dernier. » Quelle phrase est correcte ?", "\"This year's growth is higher than last year's.\" Which is correct?"),
        options: ["今年的增长高于去年。", "今年的增长比去年高于。", "今年的增长高于在去年。", "今年的增长于去年高。"],
        answer: 0,
        explain: t("高于 + N = « plus élevé que » ; on ne combine pas 比 et 于.", "高于 + N = \"higher than\"; don't combine 比 and 于."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "",
        after: "失去信任，就很难再找到合作伙伴。",
        options: ["一旦", "一直", "一边", "一下"],
        answer: 0,
        tr: t("Une fois la confiance perdue, il est très difficile de retrouver des partenaires.", "Once trust is lost, it's very hard to find partners again."),
        explain: t("一旦…就… : événement décisif et ses conséquences.", "一旦…就…: a decisive event and its consequences."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["我们", "之所以", "做得这么好", "是因为", "赶上了好时机"],
        tr: t("Si nous avons si bien réussi, c'est que nous avons saisi le bon moment.", "We've done so well because we caught the right moment."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["在市场经济下", "诚信", "才是", "最大的", "财富"],
        tr: t("Dans une économie de marché, l'honnêteté est la plus grande richesse.", "In a market economy, integrity is the greatest asset."),
      },
      {
        type: "listen",
        zh: "交通不便，以致很多水果烂在了地里。",
        options: ["交通不便，以致很多水果烂在了地里。", "交通方便，从而很多水果卖了出去。", "交通不便，以免很多水果烂在地里。", "交通不便，所以很多水果放在了家里。"],
        answer: 0,
        tr: t("Les transports étaient si mauvais que beaucoup de fruits pourrissaient dans les champs.", "Transport was so poor that lots of fruit rotted in the fields."),
      },
      {
        type: "listen",
        zh: "农民的收入增加了一倍。",
        options: ["农民的收入增加了一倍。", "农民的收入减少了一半。", "农民的收入增加了一点儿。", "农民的收入没有增加。"],
        answer: 0,
        tr: t("Les revenus des agriculteurs ont doublé.", "Farmers' incomes have doubled."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "创业", pinyin: "chuàngyè", tr: t("créer une entreprise", "to start a business") },
          { zh: "消费者", pinyin: "xiāofèizhě", tr: t("consommateur", "consumer") },
          { zh: "倒闭", pinyin: "dǎobì", tr: t("faire faillite", "to go bankrupt") },
          { zh: "诚信", pinyin: "chéngxìn", tr: t("honnêteté, fiabilité", "integrity") },
          { zh: "竞争", pinyin: "jìngzhēng", tr: t("concurrence", "competition") },
        ],
      },
    ],
  },

  // ───────────────────────── L02 · Débat éducation ─────────────────────────
  {
    id: "hsk5-l02",
    level: 5,
    order: 2,
    title: t("Faut-il des cours du soir ?", "Should kids go to cram school?"),
    subtitle: t("Éducation : un débat entre parents", "Education: a debate between parents"),
    theme: "school",
    goals: [
      t("Argumenter de façon nuancée avec 固然…但…", "Argue with nuance using 固然…但…"),
      t("Comparer deux options avec 与其…不如…", "Weigh two options with 与其…不如…"),
      t("Reformuler une idée avec 与其说…不如说…", "Reframe an idea with 与其说…不如说…"),
      t("Contredire poliment avec 未必 et relativiser avec 毕竟", "Disagree politely with 未必 and put things in perspective with 毕竟"),
    ],
    dialogue: {
      context: t(
        "Dans une émission de télévision, deux parents débattent : Mme Zhang défend les cours de soutien privés, M. Li s'y oppose.",
        "On a TV show, two parents debate: Ms Zhang supports private tutoring classes, Mr Li is against them.",
      ),
      lines: [
        ln("主持人", "今天我们讨论的话题是：孩子该不该上补习班？", "Jīntiān wǒmen tǎolùn de huàtí shì: háizi gāi bu gāi shàng bǔxíbān?", "Notre sujet aujourd'hui : faut-il inscrire les enfants aux cours du soir ?", "Today's topic: should children go to cram school?"),
        ln("张女士", "我认为应该上。考试成绩固然不是一切，但在中国，高考毕竟决定了很多人的未来。", "Wǒ rènwéi yīnggāi shàng. Kǎoshì chéngjì gùrán bú shì yíqiè, dàn zài Zhōngguó, gāokǎo bìjìng juédìng le hěn duō rén de wèilái.", "Je pense que oui. Les notes ne sont pas tout, certes, mais en Chine le gaokao détermine quand même l'avenir de beaucoup de gens.", "I think they should. Exam results aren't everything, granted, but in China the gaokao does decide many people's future, after all."),
        ln("张女士", "别的孩子都在学，我们不学，要么落后，要么以后花更多时间补。", "Biéde háizi dōu zài xué, wǒmen bù xué, yàome luòhòu, yàome yǐhòu huā gèng duō shíjiān bǔ.", "Tous les autres enfants y vont. Si on n'y va pas, soit on prend du retard, soit on passe encore plus de temps à rattraper plus tard.", "All the other kids are studying. If we don't, either we fall behind or we spend even more time catching up later."),
        ln("李先生", "我不同意。补习班上得多，成绩未必就好。", "Wǒ bù tóngyì. Bǔxíbān shàng de duō, chéngjì wèibì jiù hǎo.", "Je ne suis pas d'accord. Multiplier les cours du soir ne garantit pas de meilleures notes.", "I disagree. Lots of cram classes don't necessarily mean better grades."),
        ln("李先生", "我儿子以前每个周末上四个班，结果越学越没兴趣。", "Wǒ érzi yǐqián měi ge zhōumò shàng sì ge bān, jiéguǒ yuè xué yuè méi xìngqù.", "Mon fils avait quatre cours chaque week-end : résultat, plus il étudiait, moins ça l'intéressait.", "My son used to have four classes every weekend, and the more he studied, the less interested he got."),
        ln("李先生", "与其让孩子被动地学，不如培养他自己学习的能力。", "Yǔqí ràng háizi bèidòng de xué, bùrú péiyǎng tā zìjǐ xuéxí de nénglì.", "Plutôt que de faire apprendre un enfant passivement, mieux vaut développer sa capacité à apprendre seul.", "Rather than making kids learn passively, it's better to build their ability to learn on their own."),
        ln("主持人", "张女士，您怎么看李先生的观点？", "Zhāng nǚshì, nín zěnme kàn Lǐ xiānsheng de guāndiǎn?", "Madame Zhang, que pensez-vous du point de vue de M. Li ?", "Ms Zhang, what do you think of Mr Li's view?"),
        ln("张女士", "他说的有道理。可是自学能力不是一天两天就能培养出来的。", "Tā shuō de yǒu dàolǐ. Kěshì zìxué nénglì bú shì yì tiān liǎng tiān jiù néng péiyǎng chūlái de.", "Il n'a pas tort. Mais l'autonomie, ça ne se construit pas en un jour ou deux.", "He has a point. But independent learning isn't something you build in a day or two."),
        ln("李先生", "所以更要从小开始。我觉得，家长的焦虑与其说是为了孩子，不如说是怕孩子输给别人。", "Suǒyǐ gèng yào cóng xiǎo kāishǐ. Wǒ juéde, jiāzhǎng de jiāolǜ yǔqí shuō shì wèile háizi, bùrú shuō shì pà háizi shū gěi biérén.", "Raison de plus pour commencer tôt. À mon avis, l'angoisse des parents tient moins au bien de l'enfant qu'à la peur qu'il soit battu par les autres.", "All the more reason to start early. I think parents' anxiety is less about the child than about fear of the child losing out to others."),
        ln("张女士", "这一点我承认。现在的教育竞争太激烈了，谁都不敢放松。", "Zhè yì diǎn wǒ chéngrèn. Xiànzài de jiàoyù jìngzhēng tài jīliè le, shéi dōu bù gǎn fàngsōng.", "Ça, je le reconnais. La compétition scolaire est si féroce aujourd'hui que personne n'ose relâcher la pression.", "I'll admit that. Competition in education is so fierce now that nobody dares ease off."),
        ln("主持人", "看来两位都同意，教育的目的不应该只是分数。", "Kàn lái liǎng wèi dōu tóngyì, jiàoyù de mùdì bù yīnggāi zhǐ shì fēnshù.", "Il semble que vous soyez tous deux d'accord : l'éducation ne devrait pas se résumer aux notes.", "It seems you both agree that education shouldn't just be about scores."),
        ln("李先生", "对。孩子毕竟是孩子，快乐和健康同样重要。", "Duì. Háizi bìjìng shì háizi, kuàilè hé jiànkāng tóngyàng zhòngyào.", "Oui. Un enfant reste un enfant, après tout : le bonheur et la santé comptent tout autant.", "Right. Kids are kids, after all — happiness and health matter just as much."),
      ],
    },
    vocab: ["话题", "补习班", "认为", "固然", "一切", "毕竟", "决定", "未来", "要么", "落后", "补", "同意", "未必", "结果", "兴趣", "与其", "不如", "被动", "培养", "能力", "观点", "道理", "自学", "家长", "焦虑", "承认", "教育", "竞争", "激烈", "放松", "目的", "分数", "同样", "快乐"],
    grammar: ["hsk5-g02", "hsk5-g10", "hsk5-g12", "hsk5-g16", "hsk5-g20", "hsk5-g33"],
    culture: {
      title: t("Le gaokao et la réforme « double réduction »", "The gaokao and the \"double reduction\" reform"),
      body: t(
        "Le **高考**, examen national d'entrée à l'université, a lieu chaque année les 7 et 8 juin. Plus de **13 millions** de lycéens le passent : il détermine en grande partie l'université, donc souvent la carrière. Les jours d'examen, on détourne la circulation autour des centres et les chantiers s'arrêtent pour ne pas déranger les candidats.\n\nFace à l'explosion des cours privés et à la pression sur les familles, l'État a lancé en 2021 la politique **双减** (« double réduction ») : moins de devoirs et interdiction des cours de soutien à but lucratif pour les matières principales. Le débat continue : beaucoup de familles se tournent vers des professeurs particuliers discrets.",
        "The **高考**, the national university entrance exam, takes place every year on 7–8 June. Over **13 million** students sit it; it largely decides which university — and often which career. On exam days, traffic is diverted around test centres and building sites fall silent.\n\nFacing booming private tutoring and pressure on families, the state launched the **双减** (\"double reduction\") policy in 2021: less homework and a ban on for-profit tutoring in core subjects. The debate goes on — many families have turned to discreet private tutors.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "与其在家里抱怨，",
        after: "出去找找机会。",
        options: ["不如", "还是", "而是", "不但"],
        answer: 0,
        tr: t("Plutôt que de te plaindre à la maison, va chercher des occasions.", "Rather than complaining at home, go and look for opportunities."),
        explain: t("与其 A，不如 B : on rejette A et on préfère B.", "与其 A，不如 B: reject A, prefer B."),
      },
      {
        type: "choice",
        prompt: t("Que veut dire M. Li par « 补习班上得多，成绩未必就好 » ?", "What does Mr Li mean by \"补习班上得多，成绩未必就好\"?"),
        options: [
          t("Beaucoup de cours ne garantissent pas de bonnes notes.", "Lots of classes don't guarantee good grades."),
          t("Beaucoup de cours donnent forcément de mauvaises notes.", "Lots of classes definitely lead to bad grades."),
          t("Il faut suivre beaucoup de cours pour avoir de bonnes notes.", "You need lots of classes to get good grades."),
          t("Les cours n'ont aucun rapport avec les notes.", "Classes have nothing to do with grades."),
        ],
        answer: 0,
        explain: t("未必 = « pas forcément », une négation atténuée.", "未必 = \"not necessarily\", a softened negation."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "成绩",
        after: "重要，但健康更重要。",
        options: ["固然", "毕竟", "未必", "要么"],
        answer: 0,
        tr: t("Les notes comptent, certes, mais la santé compte davantage.", "Grades matter, granted, but health matters more."),
        explain: t("固然 concède un argument avant un « mais ».", "固然 grants a point before a \"but\"."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "别怪他了，他",
        after: "还是个孩子。",
        options: ["毕竟", "固然", "终于", "未必"],
        answer: 0,
        tr: t("Ne lui en veux pas, ce n'est qu'un enfant, après tout.", "Don't blame him — he's only a child, after all."),
        explain: t("毕竟 = « après tout » : rappelle un fait décisif. 终于 = « enfin » (fin d'un processus).", "毕竟 = \"after all\": a decisive fact. 终于 = \"finally\" (end of a process)."),
      },
      {
        type: "choice",
        prompt: t("« Son succès tient moins à la chance qu'au travail. » Quelle traduction ?", "\"His success is less luck than hard work.\" Which translation?"),
        options: ["他的成功与其说是运气，不如说是努力。", "他的成功与其是运气，不如是努力。", "他的成功不如说是运气，与其说是努力。", "他的成功要么是运气，要么是努力。"],
        answer: 0,
        explain: t("与其说 A，不如说 B : B est la description la plus juste.", "与其说 A，不如说 B: B is the more accurate description."),
      },
      {
        type: "fill",
        prompt: t("Complète l'alternative.", "Complete the alternative."),
        before: "毕业以后，要么考研，",
        after: "直接工作。",
        options: ["要么", "而且", "还是", "不然"],
        answer: 0,
        tr: t("Après le diplôme, soit on passe le concours du master, soit on travaille directement.", "After graduating, either you sit the master's exam or you go straight to work."),
        explain: t("要么…要么… : alternative fermée, en parallèle.", "要么…要么…: a closed, parallel alternative."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["与其", "让孩子被动地学", "不如", "培养", "他自己学习的能力"],
        tr: t("Plutôt que de faire apprendre l'enfant passivement, mieux vaut développer son autonomie.", "Rather than passive learning, better to build the child's own learning ability."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["孩子", "毕竟", "是孩子", "快乐和健康", "同样重要"],
        tr: t("Un enfant reste un enfant : bonheur et santé comptent tout autant.", "Kids are kids: happiness and health matter just as much."),
      },
      {
        type: "listen",
        zh: "考试成绩固然不是一切，但高考毕竟很重要。",
        options: ["考试成绩固然不是一切，但高考毕竟很重要。", "考试成绩当然是一切，所以高考很重要。", "考试成绩未必重要，高考也不重要。", "考试成绩固然重要，但高考不是一切。"],
        answer: 0,
        tr: t("Les notes ne sont pas tout, certes, mais le gaokao reste très important.", "Grades aren't everything, granted, but the gaokao is important after all."),
      },
      {
        type: "listen",
        zh: "谁都不敢放松。",
        options: ["谁都不敢放松。", "谁都不想放假。", "谁都可以放松。", "谁都不肯放手。"],
        answer: 0,
        tr: t("Personne n'ose relâcher la pression.", "Nobody dares to ease off."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "焦虑", pinyin: "jiāolǜ", tr: t("angoisse, anxieux", "anxiety") },
          { zh: "培养", pinyin: "péiyǎng", tr: t("former, développer", "to cultivate, train") },
          { zh: "落后", pinyin: "luòhòu", tr: t("prendre du retard", "to fall behind") },
          { zh: "承认", pinyin: "chéngrèn", tr: t("reconnaître, admettre", "to admit") },
          { zh: "被动", pinyin: "bèidòng", tr: t("passif", "passive") },
        ],
      },
    ],
  },

  // ───────────────────────── L03 · Environnement ─────────────────────────
  {
    id: "hsk5-l03",
    level: 5,
    order: 3,
    title: t("Quel déchet es-tu ?", "What kind of rubbish are you?"),
    subtitle: t("Environnement : le tri des déchets à Shanghai", "Environment: waste sorting in Shanghai"),
    theme: "nature",
    goals: [
      t("Énoncer une règle générale avec 凡是…都…", "State a general rule with 凡是…都…"),
      t("Expliquer une précaution avec 以免", "Explain a precaution with 以免"),
      t("Raisonner a fortiori avec 何况", "Reason a fortiori with 何况"),
      t("Lire le style administratif : 以…为…、进行、加以、总之", "Read administrative style: 以…为…、进行、加以、总之"),
    ],
    dialogue: {
      context: t(
        "Anna, une Allemande qui vient d'emménager à Shanghai, demande à Mme Wang, responsable du comité de quartier, comment trier ses déchets.",
        "Anna, a German woman who has just moved to Shanghai, asks Mrs Wang from the neighbourhood committee how to sort her rubbish.",
      ),
      lines: [
        ln("安娜", "王大姐，我刚搬来，听说这里扔垃圾有很多规定？", "Wáng dàjiě, wǒ gāng bān lái, tīngshuō zhèlǐ rēng lājī yǒu hěn duō guīdìng?", "Madame Wang, je viens d'emménager. On m'a dit qu'il y avait beaucoup de règles pour jeter ses déchets ici ?", "Mrs Wang, I've just moved in. I hear there are lots of rules for throwing out rubbish here?"),
        ln("王大姐", "对，上海几年前就开始实行垃圾分类，以减少污染、节约资源为目标。", "Duì, Shànghǎi jǐ nián qián jiù kāishǐ shíxíng lājī fēnlèi, yǐ jiǎnshǎo wūrǎn, jiéyuē zīyuán wéi mùbiāo.", "Oui, Shanghai a mis en place le tri il y a quelques années, avec pour objectif de réduire la pollution et d'économiser les ressources.", "Yes, Shanghai brought in waste sorting a few years ago, aiming to cut pollution and save resources."),
        ln("王大姐", "垃圾分成四类：可回收物、有害垃圾、湿垃圾和干垃圾。", "Lājī fēnchéng sì lèi: kě huíshōu wù, yǒuhài lājī, shī lājī hé gān lājī.", "Les déchets se divisent en quatre catégories : recyclables, dangereux, humides et secs.", "Rubbish is divided into four types: recyclables, hazardous, wet and dry waste."),
        ln("安娜", "这么复杂！我怎么分得清呢？", "Zhème fùzá! Wǒ zěnme fēn de qīng ne?", "C'est compliqué ! Comment je vais m'y retrouver ?", "That's complicated! How will I tell them apart?"),
        ln("王大姐", "很简单。凡是能再利用的，比如纸、塑料瓶，都放进蓝色的桶里。", "Hěn jiǎndān. Fánshì néng zài lìyòng de, bǐrú zhǐ, sùliàopíng, dōu fàng jìn lánsè de tǒng lǐ.", "C'est simple. Tout ce qui est réutilisable, comme le papier ou les bouteilles en plastique, va dans la poubelle bleue.", "It's easy. Anything reusable, like paper or plastic bottles, goes in the blue bin."),
        ln("王大姐", "电池、过期的药属于有害垃圾，要单独扔，以免污染土地和水。", "Diànchí, guòqī de yào shǔyú yǒuhài lājī, yào dāndú rēng, yǐmiǎn wūrǎn tǔdì hé shuǐ.", "Les piles et les médicaments périmés sont des déchets dangereux : il faut les jeter à part pour ne pas polluer les sols et l'eau.", "Batteries and expired medicine are hazardous waste; throw them out separately so they don't pollute the soil and water."),
        ln("安娜", "那吃剩的饭菜呢？", "Nà chī shèng de fàncài ne?", "Et les restes de repas ?", "What about leftover food?"),
        ln("王大姐", "剩饭剩菜是湿垃圾，扔之前要把塑料袋拿掉。", "Shèng fàn shèng cài shì shī lājī, rēng zhīqián yào bǎ sùliàodài ná diào.", "Les restes sont des déchets humides ; avant de les jeter, il faut enlever le sac plastique.", "Leftovers are wet waste; take them out of the plastic bag before throwing them away."),
        ln("安娜", "说实话，有时候我自己都分不清，何况我那些刚来中国的朋友呢？", "Shuō shíhuà, yǒu shíhou wǒ zìjǐ dōu fēn bu qīng, hékuàng wǒ nàxiē gāng lái Zhōngguó de péngyou ne?", "Franchement, même moi je m'y perds parfois, alors mes amis qui viennent d'arriver en Chine…", "Honestly, sometimes even I can't tell, let alone my friends who've just arrived in China."),
        ln("王大姐", "别担心。每天早上都有志愿者在这儿，会对扔错的垃圾进行检查，并且加以说明。", "Bié dānxīn. Měi tiān zǎoshang dōu yǒu zhìyuànzhě zài zhèr, huì duì rēng cuò de lājī jìnxíng jiǎnchá, bìngqiě jiāyǐ shuōmíng.", "Pas d'inquiétude. Chaque matin, des bénévoles sont là : ils vérifient les déchets mal triés et donnent des explications.", "Don't worry. Volunteers are here every morning to check wrongly sorted rubbish and explain."),
        ln("安娜", "真是辛苦你们了。垃圾分类到底有多大效果？", "Zhēn shì xīnkǔ nǐmen le. Lājī fēnlèi dàodǐ yǒu duō dà xiàoguǒ?", "Merci pour tout ce travail. Mais au fond, le tri, ça sert vraiment ?", "Thanks for all your work. But how effective is waste sorting, really?"),
        ln("王大姐", "效果挺明显的，回收的资源多了，环境也干净了。总之，环保要从每个人做起。", "Xiàoguǒ tǐng míngxiǎn de, huíshōu de zīyuán duō le, huánjìng yě gānjìng le. Zǒngzhī, huánbǎo yào cóng měi ge rén zuò qǐ.", "Les effets sont nets : on recycle plus et l'environnement est plus propre. Bref, l'écologie commence par chacun d'entre nous.", "The results are clear: more is recycled and the environment is cleaner. In short, protecting the environment starts with each of us."),
      ],
    },
    vocab: ["垃圾", "规定", "实行", "分类", "减少", "污染", "节约", "资源", "目标", "回收", "有害", "复杂", "凡是", "利用", "塑料", "桶", "电池", "过期", "属于", "单独", "以免", "土地", "剩", "何况", "志愿者", "进行", "检查", "加以", "说明", "辛苦", "效果", "明显", "环境", "总之", "环保"],
    grammar: ["hsk5-g04", "hsk5-g05", "hsk5-g07", "hsk5-g15", "hsk5-g23", "hsk5-g26"],
    culture: {
      title: t("« 你是什么垃圾？ » : quand le tri devient un mème", "\"你是什么垃圾？\": when sorting became a meme"),
      body: t(
        "Le 1er juillet 2019, Shanghai a rendu le **垃圾分类** obligatoire, avec des amendes à la clé. Pendant des semaines, les réseaux sociaux ont été envahis par la question **« 你是什么垃圾？ »** (« Tu es quel type de déchet ? »), qui est devenue une blague — et presque une insulte amicale.\n\nPiège célèbre : les **os de porc** sont des déchets secs (trop durs à composter), mais les **os de poulet** sont humides ! Des applis et mini-programmes WeChat permettent de photographier un objet pour savoir dans quelle poubelle le jeter. Depuis, des dizaines de villes chinoises ont suivi l'exemple.",
        "On 1 July 2019, Shanghai made **垃圾分类** (waste sorting) mandatory, with fines. For weeks, social media was flooded with the question **\"你是什么垃圾？\"** (\"What type of rubbish are you?\"), which became a joke — almost a friendly insult.\n\nFamous trap: **pork bones** are dry waste (too hard to compost), but **chicken bones** are wet! Apps and WeChat mini-programs let you photograph an item to find the right bin. Dozens of Chinese cities have since followed suit.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la règle.", "Complete the rule."),
        before: "凡是能回收的垃圾，",
        after: "要放进蓝色的桶里。",
        options: ["都", "就", "才", "却"],
        answer: 0,
        tr: t("Tous les déchets recyclables doivent aller dans la poubelle bleue.", "All recyclable waste must go in the blue bin."),
        explain: t("凡是… exige 都 dans la seconde partie.", "凡是… requires 都 in the second part."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["电池要单独扔，以免污染环境。", "电池要单独扔，以免不污染环境。", "电池要单独扔，以致不污染环境。", "以免污染环境，电池要单独扔了。"],
        answer: 0,
        explain: t("以免 + ce qu'on veut éviter, sans négation.", "以免 + what you want to avoid, without a negation."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon mot.", "Fill in the right word."),
        before: "这种垃圾连专家都分不清，",
        after: "普通人呢？",
        options: ["何况", "况且", "以免", "总之"],
        answer: 0,
        tr: t("Même les experts n'arrivent pas à trier ça, alors les gens ordinaires…", "Even experts can't sort it, let alone ordinary people."),
        explain: t("连…都…，何况…呢？ = raisonnement a fortiori.", "连…都…，何况…呢？ = a fortiori reasoning."),
      },
      {
        type: "choice",
        prompt: t("Comment se lit 为 dans 以减少污染为目标 ?", "How is 为 read in 以减少污染为目标?"),
        options: ["wéi", "wèi", "wěi", "wēi"],
        answer: 0,
        explain: t("Dans 以…为…, 为 = « comme, être » et se lit wéi (2e ton).", "In 以…为…, 为 means \"as, to be\" and is read wéi (2nd tone)."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase utilise 进行 correctement ?", "Which sentence uses 进行 correctly?"),
        options: ["专家对污染情况进行了调查。", "专家进行调查了污染情况。", "专家进行了查。", "我们进行吃饭吧。"],
        answer: 0,
        explain: t("对 + objet + 进行 + verbe bisyllabique (调查、研究、讨论…).", "对 + object + 进行 + disyllabic verb (调查、研究、讨论…)."),
      },
      {
        type: "fill",
        prompt: t("Complète la conclusion.", "Complete the conclusion."),
        before: "少开车、少用塑料袋……",
        after: "，环保要从小事做起。",
        options: ["总之", "换句话说", "首先", "何况"],
        answer: 0,
        tr: t("Moins de voiture, moins de sacs plastique… bref, l'écologie commence par les petits gestes.", "Drive less, use fewer plastic bags… in short, green living starts with small things."),
        explain: t("总之 résume et conclut une énumération.", "总之 sums up and concludes a list."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["凡是", "能再利用的", "都", "放进", "蓝色的桶里"],
        tr: t("Tout ce qui est réutilisable va dans la poubelle bleue.", "Anything reusable goes in the blue bin."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["志愿者", "会对", "扔错的垃圾", "进行", "检查"],
        tr: t("Les bénévoles vérifient les déchets mal triés.", "Volunteers check wrongly sorted rubbish."),
      },
      {
        type: "listen",
        zh: "有时候我自己都分不清，何况我的朋友呢？",
        options: ["有时候我自己都分不清，何况我的朋友呢？", "有时候我自己都分得清，况且我的朋友也行。", "有时候我的朋友分不清，何况我呢？", "有时候我自己都分不清，所以我的朋友也不行。"],
        answer: 0,
        tr: t("Parfois même moi je ne m'y retrouve pas, alors mes amis…", "Sometimes even I can't tell, let alone my friends."),
      },
      {
        type: "listen",
        zh: "过期的药属于有害垃圾。",
        options: ["过期的药属于有害垃圾。", "过期的药属于可回收物。", "过去的药属于有害垃圾。", "过期的书属于有害垃圾。"],
        answer: 0,
        tr: t("Les médicaments périmés sont des déchets dangereux.", "Expired medicine counts as hazardous waste."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "回收", pinyin: "huíshōu", tr: t("recycler", "to recycle") },
          { zh: "污染", pinyin: "wūrǎn", tr: t("pollution, polluer", "pollution, to pollute") },
          { zh: "资源", pinyin: "zīyuán", tr: t("ressources", "resources") },
          { zh: "有害", pinyin: "yǒuhài", tr: t("nocif, dangereux", "harmful") },
          { zh: "过期", pinyin: "guòqī", tr: t("périmé", "expired") },
        ],
      },
    ],
  },
];
