import type { Lesson } from "../../types";
import { P, line, pair, t } from "./helpers";

/** HSK 1 — lessons 9 to 15. */
export const lessonsB: Lesson[] = [
  // ═══════════════════════════ L09 ═══════════════════════════
  {
    id: "hsk1-l09",
    level: 1,
    order: 9,
    title: t("Où sont les toilettes ?", "Where's the restroom?"),
    subtitle: t("Situer les lieux et les objets", "Locating places and things"),
    theme: "city",
    goals: [
      t("Demander où se trouve un lieu avec 在哪儿", "Ask where a place is with 在哪儿"),
      t("Situer avec les mots de position : 前边, 左边, 旁边, 里…", "Locate things with position words: 前边, 左边, 旁边, 里…"),
      t("Dire « il y a… » avec Lieu + 有", "Say “there is…” with Place + 有"),
      t("Utiliser 在 devant un verbe : 在医院工作", "Use 在 before a verb: 在医院工作"),
    ],
    dialogue: {
      context: t(
        "Marc cherche la bibliothèque sur le campus. Il demande son chemin à une étudiante.",
        "Marc is looking for the library on campus. He asks a student for directions.",
      ),
      lines: [
        line("马克", "请问，图书馆在哪儿？", "Qǐngwèn, túshūguǎn zài nǎr?", "Excuse-moi, où est la bibliothèque ?", "Excuse me, where's the library?"),
        line("同学", "图书馆在前边，在商店的左边。", "Túshūguǎn zài qiánbian, zài shāngdiàn de zuǒbian.", "Elle est devant, à gauche du magasin.", "It's up ahead, to the left of the shop."),
        line("马克", "图书馆里有洗手间吗？", "Túshūguǎn li yǒu xǐshǒujiān ma?", "Il y a des toilettes dans la bibliothèque ?", "Is there a restroom in the library?"),
        line("同学", "有，在一楼。", "Yǒu, zài yī lóu.", "Oui, au rez-de-chaussée.", "Yes, on the ground floor."),
        line("马克", "图书馆旁边有饭店吗？", "Túshūguǎn pángbiān yǒu fàndiàn ma?", "Il y a un restaurant à côté de la bibliothèque ?", "Is there a restaurant next to the library?"),
        line("同学", "没有。饭店在学校外边，在医院后边。", "Méiyǒu. Fàndiàn zài xuéxiào wàibian, zài yīyuàn hòubian.", "Non. Les restaurants sont en dehors du campus, derrière l'hôpital.", "No. The restaurants are off campus, behind the hospital."),
        line("马克", "远吗？", "Yuǎn ma?", "C'est loin ?", "Is it far?"),
        line("同学", "不远，走路一会儿就到。", "Bù yuǎn, zǒulù yíhuìr jiù dào.", "Non, c'est à deux pas à pied.", "No, it's a short walk."),
        line("马克", "谢谢你！", "Xièxie nǐ!", "Merci !", "Thank you!"),
        line("同学", "不客气！", "Bú kèqi!", "De rien !", "You're welcome!"),
      ],
    },
    vocab: ["在", "这儿", "那儿", "这里", "那里", "上", "下", "里", "外", "前", "后", "左", "右", "前边", "后边", "左边", "右边", "旁边", "里边", "外边", "中间", "学校", "医院", "洗手间", "楼", "远", "走路", "路口", "地方", "桌子"],
    grammar: ["hsk1-g30", "hsk1-g31", "hsk1-g32"],
    culture: {
      title: t("« 一楼 » : attention à l'étage !", "“一楼”: mind the floor!"),
      body: t(
        "En Chine, **一楼** (« premier étage ») est le **rez-de-chaussée** : on compte comme en Amérique du Nord. Donc si on te dit 在二楼, monte **un seul** étage !\n\nÀ Pékin, les rues suivent un quadrillage orienté **nord-sud / est-ouest**, et les habitants indiquent souvent le chemin avec les **points cardinaux** : 往北走 (« va vers le nord »), 在东边 (« côté est »), plutôt qu'avec gauche/droite. Garde une boussole sur ton téléphone !\n\nPour les toilettes, cherche **洗手间** (« pièce pour se laver les mains ») ou **厕所** sur les panneaux ; 男 = hommes, 女 = femmes. Pense à avoir des mouchoirs : le papier n'est pas toujours fourni.",
        "In China, **一楼** (“first floor”) is the **ground floor**: counting works as in North America. So if you're told 在二楼, go up just **one** flight!\n\nIn Beijing, streets follow a **north-south / east-west** grid, and locals often give directions with **compass points**: 往北走 (“head north”), 在东边 (“on the east side”), rather than left/right. Keep a compass on your phone!\n\nFor restrooms, look for **洗手间** (“hand-washing room”) or **厕所** on signs; 男 = men, 女 = women. Carry tissues: paper isn't always provided.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Le livre est sur la table. »", "Translate: “The book is on the table.”"),
        options: ["书在桌子上。", "书在上桌子。", "书是桌子上。", "桌子上在书。"],
        answer: 0,
        explain: t("Chose + 在 + nom + mot de position (上).", "Thing + 在 + noun + position word (上)."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Il y a un magasin à côté de l'école. »", "Translate: “There's a shop next to the school.”"),
        options: ["一家商店在学校旁边。", "学校旁边有一家商店。", "在学校旁边是商店有。", "学校有旁边一家商店。"],
        answer: 1,
        explain: t("« Il y a » : Lieu + 有 + chose.", "“There is”: Place + 有 + thing."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "请问，洗手间在",
        after: "？",
        options: ["哪儿", "什么", "谁", "几"],
        answer: 0,
        tr: t("Excusez-moi, où sont les toilettes ?", "Excuse me, where's the restroom?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我妈妈",
        after: "医院工作。",
        options: ["是", "在", "有", "的"],
        answer: 1,
        tr: t("Ma mère travaille à l'hôpital.", "My mom works at the hospital."),
        explain: t("在 + lieu se place avant le verbe.", "在 + place goes before the verb."),
      },
      {
        type: "fill",
        prompt: t("Complète : « Le portable est DANS le cartable. »", "Complete: “The phone is IN the schoolbag.”"),
        before: "手机在书包",
        after: "。",
        options: ["里", "上", "下", "外"],
        answer: 0,
        tr: t("Le portable est dans le cartable.", "The phone is in the schoolbag."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "图书馆",
        after: "有洗手间吗？",
        options: ["在", "是", "里", "的"],
        answer: 2,
        tr: t("Il y a des toilettes dans la bibliothèque ?", "Is there a restroom in the library?"),
      },
      { type: "order", prompt: P.order, tokens: ["学校", "旁边", "有", "一家医院"], tr: t("Il y a un hôpital à côté de l'école.", "There's a hospital next to the school.") },
      { type: "order", prompt: P.order, tokens: ["请问", "洗手间", "在", "哪儿"], tr: t("Excusez-moi, où sont les toilettes ?", "Excuse me, where's the restroom?") },
      {
        type: "listen",
        zh: "饭店在医院后边。",
        options: ["饭店在医院前边。", "饭店在医院后边。", "医院在饭店后边。", "饭店在学校后边。"],
        answer: 1,
        tr: t("Le restaurant est derrière l'hôpital.", "The restaurant is behind the hospital."),
      },
      {
        type: "listen",
        zh: "不远，走路一会儿就到。",
        options: ["很远，走路要一个小时。", "不远，坐车一会儿就到。", "不远，在学校里边。", "不远，走路一会儿就到。"],
        answer: 3,
        tr: t("Ce n'est pas loin, c'est à deux pas à pied.", "It's not far, it's a short walk."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("前边", "qiánbian", "devant", "in front"),
          pair("后边", "hòubian", "derrière", "behind"),
          pair("左边", "zuǒbian", "à gauche", "on the left"),
          pair("右边", "yòubian", "à droite", "on the right"),
          pair("里边", "lǐbian", "dedans", "inside"),
          pair("旁边", "pángbiān", "à côté", "next to"),
        ],
      },
      {
        type: "choice",
        prompt: t("Dans un immeuble chinois, 一楼 correspond à…", "In a Chinese building, 一楼 is…"),
        options: [
          t("le rez-de-chaussée", "the ground floor"),
          t("le premier étage (au-dessus du rez-de-chaussée)", "the floor above the ground floor"),
          t("le sous-sol", "the basement"),
          t("le dernier étage", "the top floor"),
        ],
        answer: 0,
      },
    ],
  },

  // ═══════════════════════════ L10 ═══════════════════════════
  {
    id: "hsk1-l10",
    level: 1,
    order: 10,
    title: t("En route pour l'aéroport", "Off to the airport"),
    subtitle: t("Les transports et les trajets", "Transport and getting around"),
    theme: "travel",
    goals: [
      t("Demander « comment ? » avec 怎么 + verbe", "Ask “how?” with 怎么 + verb"),
      t("Dire comment tu te déplaces : 坐飞机去, 开车去", "Say how you travel: 坐飞机去, 开车去"),
      t("Enchaîner déplacement et but : 去商店买东西", "Chain movement and purpose: 去商店买东西"),
      t("Indiquer un trajet ou une durée avec 从…到…", "Give a route or time span with 从…到…"),
    ],
    dialogue: {
      context: t(
        "La mère de Marc arrive de France demain. Marc en parle à Wang Ming.",
        "Marc's mother is flying in from France tomorrow. Marc tells Wang Ming about it.",
      ),
      lines: [
        line("王明", "马克，你明天去哪儿？", "Mǎkè, nǐ míngtiān qù nǎr?", "Marc, tu vas où demain ?", "Marc, where are you going tomorrow?"),
        line("马克", "我去机场。我妈妈从法国来北京！", "Wǒ qù jīchǎng. Wǒ māma cóng Fǎguó lái Běijīng!", "À l'aéroport. Ma mère vient de France à Pékin !", "To the airport. My mom is coming to Beijing from France!"),
        line("王明", "太好了！你怎么去机场？", "Tài hǎo le! Nǐ zěnme qù jīchǎng?", "Super ! Tu y vas comment ?", "Great! How are you getting to the airport?"),
        line("马克", "我想打车去。", "Wǒ xiǎng dǎchē qù.", "Je pensais prendre un taxi.", "I'm thinking of taking a taxi."),
        line("王明", "打车太贵了。我开车送你去吧！", "Dǎchē tài guì le. Wǒ kāichē sòng nǐ qù ba!", "Le taxi, c'est trop cher. Je t'y emmène en voiture !", "A taxi's too expensive. I'll drive you!"),
        line("马克", "真的吗？太谢谢你了！", "Zhēn de ma? Tài xièxie nǐ le!", "C'est vrai ? Merci mille fois !", "Really? Thanks so much!"),
        line("王明", "不客气。从这儿到机场要一个小时。", "Bú kèqi. Cóng zhèr dào jīchǎng yào yí ge xiǎoshí.", "De rien. D'ici à l'aéroport, il faut une heure.", "No problem. It takes an hour from here to the airport."),
        line("马克", "飞机下午三点到。", "Fēijī xiàwǔ sān diǎn dào.", "L'avion arrive à 15 h.", "The plane lands at three p.m."),
        line("王明", "那我们中午十二点半走吧。", "Nà wǒmen zhōngwǔ shí'èr diǎn bàn zǒu ba.", "Alors partons à midi et demi.", "Then let's leave at twelve thirty."),
        line("马克", "好！", "Hǎo!", "D'accord !", "OK!"),
      ],
    },
    vocab: ["去", "来", "到", "从", "坐", "开", "开车", "车", "汽车", "火车", "飞机", "机场", "车站", "票", "车票", "机票", "打车", "路", "走", "快", "慢", "送", "怎么", "北京", "上车", "下车", "回来"],
    grammar: ["hsk1-g33", "hsk1-g34", "hsk1-g35"],
    culture: {
      title: t("Le train à grande vitesse et la grande migration", "High-speed rail and the great migration"),
      body: t(
        "La Chine possède le **plus grand réseau de trains à grande vitesse** au monde (高铁, gāotiě) : Pékin–Shanghai, 1 300 km, en environ 4 h 30. Les billets s'achètent sur l'application officielle **12306**, avec son passeport.\n\nChaque année, autour du Nouvel An chinois, a lieu le **春运** (chūnyùn) : des centaines de millions de personnes rentrent dans leur famille. C'est la plus grande migration humaine de la planète — les billets partent en quelques minutes !\n\nEn ville, on se déplace en métro, en bus, en VTC (appelé via une appli : **打车**) et à **vélo en libre-service** (共享单车), qu'on déverrouille… en scannant un QR code, bien sûr.",
        "China has the **world's largest high-speed rail network** (高铁, gāotiě): Beijing–Shanghai, 1,300 km, in about 4.5 hours. Tickets are bought on the official **12306** app with your passport.\n\nEvery year around Chinese New Year comes **春运** (chūnyùn): hundreds of millions of people travel home to their families. It's the largest human migration on the planet — tickets sell out in minutes!\n\nIn cities, people get around by metro, bus, ride-hailing (booked in an app: **打车**) and **bike sharing** (共享单车), unlocked… by scanning a QR code, of course.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Je vais à Pékin en avion. »", "Translate: “I'm flying to Beijing.”"),
        options: ["我去北京坐飞机。", "我坐飞机去北京。", "我坐去北京飞机。", "我飞机坐去北京。"],
        answer: 1,
        explain: t("D'abord le moyen (坐飞机), ensuite le déplacement (去北京).", "First the means (坐飞机), then the movement (去北京)."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Je viens de France. »", "Translate: “I come from France.”"),
        options: ["我从法国来。", "我来从法国。", "我法国从来。", "从我法国来。"],
        answer: 0,
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你",
        after: "去机场？——我打车去。",
        options: ["怎么", "什么", "哪儿", "几"],
        answer: 0,
        tr: t("Tu vas à l'aéroport comment ? — En taxi.", "How are you getting to the airport? — By taxi."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "",
        after: "这儿到机场要一个小时。",
        options: ["在", "是", "从", "给"],
        answer: 2,
        tr: t("D'ici à l'aéroport, il faut une heure.", "It takes an hour from here to the airport."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我去商店",
        after: "水果。",
        options: ["坐", "买", "开", "来"],
        answer: 1,
        tr: t("Je vais au magasin acheter des fruits.", "I'm going to the store to buy fruit."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我哥哥每天",
        after: "车去上班。",
        options: ["开", "走", "到", "来"],
        answer: 0,
        tr: t("Mon grand frère va au travail en voiture tous les jours.", "My older brother drives to work every day."),
      },
      { type: "order", prompt: P.order, tokens: ["他", "每天", "坐", "汽车", "去", "学校"], tr: t("Il va à l'école en bus tous les jours.", "He takes the bus to school every day.") },
      { type: "order", prompt: P.order, tokens: ["你", "怎么", "去", "机场"], tr: t("Comment vas-tu à l'aéroport ?", "How are you getting to the airport?") },
      {
        type: "listen",
        zh: "飞机下午三点到。",
        options: ["飞机下午两点到。", "火车下午三点到。", "飞机下午三点到。", "飞机上午三点到。"],
        answer: 2,
        tr: t("L'avion arrive à 15 h.", "The plane arrives at 3 p.m."),
      },
      {
        type: "listen",
        zh: "打车太贵了。",
        options: ["开车太慢了。", "打车太贵了。", "打车不太贵。", "坐车太贵了。"],
        answer: 1,
        tr: t("Le taxi, c'est trop cher.", "Taxis are too expensive."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("飞机", "fēijī", "avion", "plane"),
          pair("火车", "huǒchē", "train", "train"),
          pair("汽车", "qìchē", "voiture, bus", "car, bus"),
          pair("机场", "jīchǎng", "aéroport", "airport"),
          pair("车站", "chēzhàn", "gare, arrêt", "station, stop"),
          pair("票", "piào", "billet", "ticket"),
        ],
      },
      {
        type: "choice",
        prompt: P.meaning,
        zh: "你昨天怎么没来？",
        pinyin: "Nǐ zuótiān zěnme méi lái?",
        options: [
          t("Pourquoi tu n'es pas venu hier ?", "How come you didn't come yesterday?"),
          t("Comment es-tu venu hier ?", "How did you come yesterday?"),
          t("Quand viens-tu ?", "When are you coming?"),
          t("Tu viens demain ?", "Are you coming tomorrow?"),
        ],
        answer: 0,
        explain: t("怎么 + négation exprime la surprise : « comment ça se fait que… ».", "怎么 + negative expresses surprise: “how come…”."),
      },
    ],
  },

  // ═══════════════════════════ L11 ═══════════════════════════
  {
    id: "hsk1-l11",
    level: 1,
    order: 11,
    title: t("Quel temps fait-il ?", "What's the weather like?"),
    subtitle: t("La météo, les sensations et les comparaisons", "Weather, feelings and comparisons"),
    theme: "weather",
    goals: [
      t("Décrire le temps et ce que tu ressens (冷, 热, 累, 饿)", "Describe the weather and how you feel (冷, 热, 累, 饿)"),
      t("Utiliser les adjectifs avec 很, 非常, 真, 最", "Use adjectives with 很, 非常, 真, 最"),
      t("T'exclamer avec 太…了！", "Exclaim with 太…了！"),
      t("Signaler un changement avec 了 : 下雨了！", "Signal a change with 了: 下雨了！"),
      t("Comparer avec 比 et 没有", "Compare with 比 and 没有"),
    ],
    dialogue: {
      context: t(
        "Li Yue propose à Marc une sortie à la montagne parfumée (香山), près de Pékin. Mais le ciel se couvre…",
        "Li Yue suggests a trip to Fragrant Hills (香山) near Beijing. But the sky is clouding over…",
      ),
      lines: [
        line("李月", "马克，明天我们去香山玩儿，好吗？", "Mǎkè, míngtiān wǒmen qù Xiāng Shān wánr, hǎo ma?", "Marc, demain on va se balader aux Collines parfumées, ça te dit ?", "Marc, shall we go to Fragrant Hills tomorrow?"),
        line("马克", "好！明天冷不冷？", "Hǎo! Míngtiān lěng bu lěng?", "Avec plaisir ! Il va faire froid demain ?", "Sure! Will it be cold tomorrow?"),
        line("李月", "明天天气很好，不冷，也不热。", "Míngtiān tiānqì hěn hǎo, bù lěng, yě bú rè.", "Demain, il fera beau : ni froid ni chaud.", "The weather will be nice tomorrow: not cold, not hot."),
        line("马克", "太好了！今天真冷！", "Tài hǎo le! Jīntiān zhēn lěng!", "Génial ! Aujourd'hui, qu'est-ce qu'il fait froid !", "Great! It's really cold today!"),
        line("李月", "对，今天比昨天冷，还有风。", "Duì, jīntiān bǐ zuótiān lěng, hái yǒu fēng.", "Oui, il fait plus froid qu'hier, et il y a du vent.", "Yes, it's colder than yesterday, and it's windy too."),
        line("马克", "你看，下雨了！", "Nǐ kàn, xià yǔ le!", "Regarde, il pleut !", "Look, it's raining!"),
        line("李月", "真的！我们回家吧。", "Zhēn de! Wǒmen huí jiā ba.", "C'est vrai ! Rentrons.", "It really is! Let's go home."),
        line("马克", "我饿了，我们先去吃饭吧。", "Wǒ è le, wǒmen xiān qù chī fàn ba.", "J'ai faim… allons d'abord manger.", "I'm hungry, let's go eat first."),
        line("李月", "好，我也饿了。这儿的包子最好吃！", "Hǎo, wǒ yě è le. Zhèr de bāozi zuì hǎochī!", "D'accord, moi aussi j'ai faim. Les baos d'ici sont les meilleurs !", "OK, I'm hungry too. The buns here are the best!"),
      ],
    },
    vocab: ["天气", "冷", "热", "下雨", "雨", "风", "天", "真", "真的", "太", "非常", "最", "比", "山", "玩儿", "累", "忙", "高", "饿", "白天", "好玩儿", "干净", "难", "一样"],
    grammar: ["hsk1-g36", "hsk1-g37", "hsk1-g38", "hsk1-g39"],
    culture: {
      title: t("Le climat de Pékin et l'eau chaude", "Beijing's climate and hot water"),
      body: t(
        "Pékin a un climat **continental** : des étés chauds et humides (plus de 35 °C), des hivers secs et glacials (−10 °C), un printemps court avec du vent et parfois du sable venu de Mongolie. La meilleure saison ? L'**automne** (septembre-octobre), quand les feuilles rougissent aux Collines parfumées.\n\nEn Chine, on boit beaucoup d'**eau chaude** (热水), même en été : on la considère meilleure pour la digestion et la santé. Si tu tombes malade, attends-toi à entendre le célèbre conseil **多喝热水！** (« bois plus d'eau chaude ! »). Dans les trains et les bureaux, il y a toujours une fontaine d'eau bouillante.",
        "Beijing has a **continental** climate: hot, humid summers (over 35 °C), dry, freezing winters (−10 °C), and a short, windy spring, sometimes with sand from Mongolia. The best season? **Autumn** (September–October), when the leaves turn red at Fragrant Hills.\n\nIn China, people drink a lot of **hot water** (热水), even in summer: it's considered better for digestion and health. If you get sick, expect to hear the famous advice **多喝热水！** (“drink more hot water!”). Trains and offices always have a boiling-water dispenser.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Il fait froid aujourd'hui. »", "Translate: “It's cold today.”"),
        options: ["今天是冷。", "今天很冷。", "今天冷是。", "今天很是冷。"],
        answer: 1,
        explain: t("Pas de 是 devant un adjectif : on utilise 很.", "No 是 before adjectives: use 很."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Aujourd'hui, il fait plus froid qu'hier. »", "Translate: “Today is colder than yesterday.”"),
        options: ["今天比昨天很冷。", "今天冷比昨天。", "今天比昨天冷。", "昨天比今天冷。"],
        answer: 2,
        explain: t("A 比 B + adjectif, sans 很.", "A 比 B + adjective, without 很."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "太好",
        after: "！",
        options: ["了", "吗", "呢", "的"],
        answer: 0,
        tr: t("Génial !", "Great!"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你看，下雨",
        after: "！",
        options: ["很", "是", "了", "不"],
        answer: 2,
        tr: t("Regarde, il pleut !", "Look, it's raining!"),
        explain: t("了 en fin de phrase = changement de situation.", "Sentence-final 了 = change of situation."),
      },
      {
        type: "fill",
        prompt: t("Complète : « Hier, il faisait MOINS chaud qu'aujourd'hui. »", "Complete: “Yesterday was NOT AS hot as today.”"),
        before: "昨天",
        after: "今天热。",
        options: ["比", "没有", "不", "很"],
        answer: 1,
        tr: t("Hier, il faisait moins chaud qu'aujourd'hui.", "Yesterday wasn't as hot as today."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这水果",
        after: "好吃！",
        options: ["是", "比", "了", "真"],
        answer: 3,
        tr: t("Ces fruits sont vraiment délicieux !", "This fruit is really delicious!"),
      },
      { type: "order", prompt: P.order, tokens: ["今天", "比", "昨天", "冷"], tr: t("Il fait plus froid aujourd'hui qu'hier.", "Today is colder than yesterday.") },
      { type: "order", prompt: P.order, tokens: ["这儿的", "包子", "最", "好吃"], tr: t("Les baos d'ici sont les meilleurs.", "The buns here are the best.") },
      {
        type: "listen",
        zh: "明天不冷也不热。",
        options: ["明天不冷也不热。", "明天很冷也很热。", "今天不冷也不热。", "明天不冷，很热。"],
        answer: 0,
        tr: t("Demain, il ne fera ni froid ni chaud.", "Tomorrow it'll be neither cold nor hot."),
      },
      {
        type: "listen",
        zh: "今天有风。",
        options: ["今天有雨。", "今天有风。", "明天有风。", "今天没有风。"],
        answer: 1,
        tr: t("Il y a du vent aujourd'hui.", "It's windy today."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("天气", "tiānqì", "temps (météo)", "weather"),
          pair("冷", "lěng", "froid", "cold"),
          pair("热", "rè", "chaud", "hot"),
          pair("下雨", "xià yǔ", "pleuvoir", "to rain"),
          pair("风", "fēng", "vent", "wind"),
          pair("累", "lèi", "fatigué", "tired"),
        ],
      },
      {
        type: "choice",
        prompt: P.meaning,
        zh: "我的汉语不太好。",
        pinyin: "Wǒ de Hànyǔ bú tài hǎo.",
        options: [
          t("Mon chinois n'est pas très bon.", "My Chinese isn't very good."),
          t("Mon chinois est vraiment mauvais.", "My Chinese is really bad."),
          t("Mon chinois est trop bon.", "My Chinese is too good."),
          t("Mon chinois est meilleur qu'avant.", "My Chinese is better than before."),
        ],
        answer: 0,
        explain: t("不太 + adj. = « pas très » (formule modeste).", "不太 + adj. = “not very” (a modest phrase)."),
      },
    ],
  },

  // ═══════════════════════════ L12 ═══════════════════════════
  {
    id: "hsk1-l12",
    level: 1,
    order: 12,
    title: t("Tes loisirs", "Your hobbies"),
    subtitle: t("Parler de ses goûts et proposer une sortie", "Talking about what you like and suggesting an outing"),
    theme: "hobbies",
    goals: [
      t("Parler de tes loisirs avec 喜欢 et 爱好", "Talk about your hobbies with 喜欢 and 爱好"),
      t("Proposer un choix avec 还是", "Offer a choice with 还是"),
      t("Relier deux noms avec 和 / 跟 (et pas deux verbes !)", "Link two nouns with 和 / 跟 (but not two verbs!)"),
      t("Dire « avec quelqu'un » : 跟朋友一起去", "Say “with someone”: 跟朋友一起去"),
    ],
    dialogue: {
      context: t(
        "Vendredi après les cours. Anna et Wang Ming parlent de leurs loisirs et organisent leur samedi soir.",
        "Friday after class. Anna and Wang Ming talk about their hobbies and plan their Saturday night.",
      ),
      lines: [
        line("安娜", "王明，你有什么爱好？", "Wáng Míng, nǐ yǒu shénme àihào?", "Wang Ming, c'est quoi tes loisirs ?", "Wang Ming, what are your hobbies?"),
        line("王明", "我喜欢唱歌，也喜欢打球。你呢？", "Wǒ xǐhuan chàng gē, yě xǐhuan dǎ qiú. Nǐ ne?", "J'aime chanter, et aussi jouer au ballon. Et toi ?", "I like singing, and I also like playing ball games. And you?"),
        line("安娜", "我喜欢看电影。星期六我常常和朋友一起看电影。", "Wǒ xǐhuan kàn diànyǐng. Xīngqīliù wǒ chángcháng hé péngyou yìqǐ kàn diànyǐng.", "Moi, j'adore le cinéma. Le samedi, je vais souvent voir un film avec des amis.", "I like movies. On Saturdays I often watch a film with friends."),
        line("王明", "你喜欢看中国电影还是美国电影？", "Nǐ xǐhuan kàn Zhōngguó diànyǐng háishi Měiguó diànyǐng?", "Tu préfères les films chinois ou américains ?", "Do you like Chinese movies or American movies?"),
        line("安娜", "中国电影和美国电影，我都喜欢！", "Zhōngguó diànyǐng hé Měiguó diànyǐng, wǒ dōu xǐhuan!", "Les films chinois et américains, j'aime les deux !", "Chinese and American movies — I like both!"),
        line("王明", "星期六晚上电影院有一个新电影，你想去吗？", "Xīngqīliù wǎnshang diànyǐngyuàn yǒu yí ge xīn diànyǐng, nǐ xiǎng qù ma?", "Samedi soir, il y a un nouveau film au cinéma. Ça te dit ?", "There's a new movie at the cinema on Saturday night. Want to go?"),
        line("安娜", "想！马克也喜欢看电影，我们跟他一起去吧。", "Xiǎng! Mǎkè yě xǐhuan kàn diànyǐng, wǒmen gēn tā yìqǐ qù ba.", "Oui ! Marc aussi aime le cinéma, allons-y avec lui.", "Yes! Marc likes movies too, let's go with him."),
        line("王明", "好！看了电影，我们去唱歌还是去吃饭？", "Hǎo! Kànle diànyǐng, wǒmen qù chàng gē háishi qù chī fàn?", "OK ! Après le film, on va au karaoké ou on va manger ?", "OK! After the movie, shall we go singing or go eat?"),
        line("安娜", "先吃饭，再唱歌！", "Xiān chī fàn, zài chàng gē!", "D'abord manger, ensuite chanter !", "Eat first, then sing!"),
      ],
    },
    vocab: ["爱好", "喜欢", "爱", "唱", "歌", "唱歌", "打", "球", "打球", "电影", "电影院", "听", "玩儿", "上网", "电脑", "网上", "网友", "还是", "和", "跟", "一起", "一块儿", "跑", "读书", "好听", "好看"],
    grammar: ["hsk1-g40", "hsk1-g41", "hsk1-g42"],
    culture: {
      title: t("KTV, danse de place et mahjong", "KTV, square dancing and mahjong"),
      body: t(
        "Le **KTV** (karaoké en salle privée) est une sortie incontournable entre amis ou collègues : on loue une pièce à l'heure, on commande à boire et à grignoter, et on chante jusqu'au bout de la nuit. Même ceux qui chantent faux y vont !\n\nLe soir, sur les places et dans les parcs, des groupes (surtout des femmes retraitées, les « tantes ») pratiquent la **danse de place** (广场舞) sur de la musique très forte.\n\nLe **mahjong** (麻将) reste le jeu de société roi, en famille comme entre voisins. Et les jeunes passent beaucoup de temps **en ligne** (上网) : jeux mobiles, vidéos courtes, séries.",
        "**KTV** (karaoke in a private room) is a must-do outing with friends or coworkers: you rent a room by the hour, order drinks and snacks, and sing into the night. Even people who can't sing go!\n\nIn the evening, on squares and in parks, groups (mostly retired women, the “aunties”) do **square dancing** (广场舞) to very loud music.\n\n**Mahjong** (麻将) is still the king of games, with family or neighbors. And young people spend a lot of time **online** (上网): mobile games, short videos, TV series.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Tu bois du thé ou de l'eau ? »", "Translate: “Would you like tea or water?”"),
        options: ["你喝茶还是喝水？", "你喝茶和喝水？", "你喝茶还是喝水吗？", "你喝茶或还是水？"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: t("Traduis : « Je vais au cinéma avec un ami. »", "Translate: “I'm going to the cinema with a friend.”"),
        options: ["我去电影院跟朋友。", "我一起跟朋友去电影院。", "我跟朋友一起去电影院。", "跟朋友我一起去电影院。"],
        answer: 2,
        explain: t("跟 + personne + 一起 se place avant le verbe.", "跟 + person + 一起 goes before the verb."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我喜欢唱歌，",
        after: "喜欢打球。",
        options: ["也", "和", "跟", "还是"],
        answer: 0,
        tr: t("J'aime chanter, et j'aime aussi jouer au ballon.", "I like singing, and I also like playing ball games."),
        explain: t("和 ne relie pas deux phrases : on utilise 也.", "和 can't link two clauses: use 也."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "爸爸",
        after: "妈妈都喜欢看电影。",
        options: ["也", "和", "还是", "都"],
        answer: 1,
        tr: t("Papa et maman aiment tous les deux le cinéma.", "Dad and Mom both like movies."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你是老师",
        after: "学生？",
        options: ["还是", "和", "也", "跟"],
        answer: 0,
        tr: t("Tu es professeur ou étudiant ?", "Are you a teacher or a student?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我们",
        after: "去吧！",
        options: ["和", "跟", "还是", "一起"],
        answer: 3,
        tr: t("Allons-y ensemble !", "Let's go together!"),
      },
      { type: "order", prompt: P.order, tokens: ["我", "跟", "朋友", "一起", "看电影"], tr: t("Je regarde un film avec un ami.", "I'm watching a movie with a friend.") },
      { type: "order", prompt: P.order, tokens: ["你", "有", "什么", "爱好"], tr: t("C'est quoi tes loisirs ?", "What are your hobbies?") },
      {
        type: "listen",
        zh: "我最喜欢唱歌。",
        options: ["我不喜欢唱歌。", "我也喜欢唱歌。", "我最喜欢唱歌。", "我最喜欢打球。"],
        answer: 2,
        tr: t("Ce que je préfère, c'est chanter.", "I like singing best."),
      },
      {
        type: "listen",
        zh: "我们去唱歌还是去吃饭？",
        options: ["我们去唱歌，也去吃饭。", "我们去唱歌还是去吃饭？", "我们先吃饭，再唱歌。", "我们去吃饭还是去打球？"],
        answer: 1,
        tr: t("On va chanter ou on va manger ?", "Shall we go singing or go eat?"),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("爱好", "àihào", "loisir, passion", "hobby"),
          pair("唱歌", "chàng gē", "chanter", "to sing"),
          pair("打球", "dǎ qiú", "jouer au ballon", "to play ball games"),
          pair("电影", "diànyǐng", "film", "movie"),
          pair("上网", "shàngwǎng", "aller sur Internet", "to go online"),
          pair("一起", "yìqǐ", "ensemble", "together"),
        ],
      },
      {
        type: "choice",
        prompt: t("Traduis : « Je suis occupé et fatigué. »", "Translate: “I'm busy and tired.”"),
        options: ["我很忙和很累。", "我很忙，也很累。", "我和很忙很累。", "我很忙还是很累。"],
        answer: 1,
        explain: t("和 relie des noms, pas des adjectifs ni des verbes.", "和 links nouns, not adjectives or verbs."),
      },
    ],
  },

  // ═══════════════════════════ L13 ═══════════════════════════
  {
    id: "hsk1-l13",
    level: 1,
    order: 13,
    title: t("On se voit ce soir ?", "See you tonight?"),
    subtitle: t("Téléphoner et fixer un rendez-vous", "Phone calls and making plans"),
    theme: "tech",
    goals: [
      t("Commencer et terminer un appel téléphonique", "Start and end a phone call"),
      t("Dire si tu peux ou ne peux pas venir avec 能 / 不能", "Say whether you can come with 能 / 不能"),
      t("Distinguer 会 (savoir faire) et 能 (pouvoir)", "Tell 会 (know how) from 能 (be able)"),
      t("Rappeler ou interdire poliment avec 别", "Remind or tell someone not to with 别"),
      t("Dire « appelle-moi » : 给我打电话", "Say “call me”: 给我打电话"),
    ],
    dialogue: {
      context: t(
        "Marc appelle Li Yue pour lui proposer d'aller au centre commercial.",
        "Marc calls Li Yue to suggest going to the mall.",
      ),
      lines: [
        line("马克", "喂，李月吗？我是马克。", "Wéi, Lǐ Yuè ma? Wǒ shì Mǎkè.", "Allô, Li Yue ? C'est Marc.", "Hello, Li Yue? It's Marc."),
        line("李月", "马克，你好！有什么事？", "Mǎkè, nǐ hǎo! Yǒu shénme shì?", "Salut, Marc ! Qu'est-ce qu'il y a ?", "Hi, Marc! What's up?"),
        line("马克", "明天下午你有时间吗？我们一起去商场吧。", "Míngtiān xiàwǔ nǐ yǒu shíjiān ma? Wǒmen yìqǐ qù shāngchǎng ba.", "Tu es libre demain après-midi ? On pourrait aller au centre commercial.", "Are you free tomorrow afternoon? Let's go to the mall together."),
        line("李月", "明天下午我不能去，我要上课。", "Míngtiān xiàwǔ wǒ bù néng qù, wǒ yào shàngkè.", "Demain après-midi, je ne peux pas, j'ai cours.", "I can't tomorrow afternoon, I have class."),
        line("马克", "那晚上呢？", "Nà wǎnshang ne?", "Et le soir, alors ?", "What about the evening?"),
        line("李月", "晚上能。七点在商场门口见，行吗？", "Wǎnshang néng. Qī diǎn zài shāngchǎng ménkǒu jiàn, xíng ma?", "Le soir, oui. On se retrouve à 19 h devant l'entrée du centre commercial ?", "The evening works. Meet at seven at the mall entrance, OK?"),
        line("马克", "行！别忘了！", "Xíng! Bié wàng le!", "Ça marche ! N'oublie pas !", "OK! Don't forget!"),
        line("李月", "我记住了。你到了给我打电话吧。", "Wǒ jìzhù le. Nǐ dào le gěi wǒ dǎ diànhuà ba.", "C'est noté. Appelle-moi quand tu arrives.", "Got it. Give me a call when you get there."),
        line("马克", "好的，明天见！", "Hǎo de, míngtiān jiàn!", "D'accord, à demain !", "OK, see you tomorrow!"),
      ],
    },
    vocab: ["手机", "电话", "打电话", "号", "事", "时间", "能", "别", "忘", "忘记", "记得", "门", "门口", "见面", "等", "告诉", "给", "知道", "明白", "问", "找", "马上", "帮", "帮忙", "没事儿"],
    grammar: ["hsk1-g43", "hsk1-g44", "hsk1-g45"],
    culture: {
      title: t("« 喂 ? » et la super-appli WeChat", "“喂?” and the WeChat super-app"),
      body: t(
        "Au téléphone, on décroche avec **喂** (wéi, au 2e ton, ou wèi) : « allô ? ». Si tu dis 喂 à quelqu'un en face de toi, c'est en revanche un « hé ! » assez sec.\n\nMais en Chine, on appelle de moins en moins : tout passe par **WeChat** (微信), l'application qui sert à la fois de messagerie, de réseau social, de portefeuille et de carte de visite. Au lieu d'échanger des numéros, on scanne le QR code de l'autre : **加个微信吧！** (« ajoutons-nous sur WeChat ! »).\n\nLes Chinois adorent les **messages vocaux** plutôt que les textes. Et pour les rendez-vous, arriver avec 5–10 minutes de retard entre amis est toléré, mais pas pour un rendez-vous professionnel.",
        "On the phone, you pick up with **喂** (wéi, 2nd tone, or wèi): “hello?”. Say 喂 to someone standing in front of you, though, and it's a rather curt “hey!”.\n\nBut in China, people call less and less: everything goes through **WeChat** (微信), the app that's a messenger, social network, wallet and business card all in one. Instead of swapping numbers, you scan each other's QR code: **加个微信吧！** (“let's add each other on WeChat!”).\n\nChinese people love **voice messages** over texts. As for meetups, arriving 5–10 minutes late is fine among friends, but not for business.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Tu veux demander la permission d'entrer. Que dis-tu ?", "You want to ask permission to come in. What do you say?"),
        options: ["我会进来吗？", "我能进来吗？", "我进来能吗？", "我是进来吗？"],
        answer: 1,
        explain: t("能 exprime la permission ; 会 une compétence apprise.", "能 expresses permission; 会 a learned skill."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Appelle-moi ce soir. »", "Translate: “Call me tonight.”"),
        options: ["晚上打电话我吧。", "晚上给我打电话吧。", "晚上我给打电话吧。", "给晚上我打电话吧。"],
        answer: 1,
        explain: t("给 + personne se place avant le verbe 打电话.", "给 + person goes before the verb 打电话."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你",
        after: "说话，孩子在睡觉。",
        options: ["不", "没", "别", "能"],
        answer: 2,
        tr: t("Ne parle pas, l'enfant dort.", "Don't talk, the child is sleeping."),
        explain: t("Pour interdire : 别 + verbe.", "To tell someone not to: 别 + verb."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "明天下午我有课，不",
        after: "去商场。",
        options: ["能", "是", "有", "在"],
        answer: 0,
        tr: t("Demain après-midi, j'ai cours, je ne peux pas aller au centre commercial.", "I have class tomorrow afternoon, I can't go to the mall."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "明天考试，别忘",
        after: "！",
        options: ["吗", "了", "呢", "的"],
        answer: 1,
        tr: t("Il y a l'examen demain, n'oublie pas !", "The exam is tomorrow, don't forget!"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你到了",
        after: "我打电话。",
        options: ["在", "是", "从", "给"],
        answer: 3,
        tr: t("Appelle-moi quand tu arrives.", "Call me when you arrive."),
      },
      { type: "order", prompt: P.order, tokens: ["晚上", "给我", "打电话", "吧"], tr: t("Appelle-moi ce soir.", "Call me tonight.") },
      { type: "order", prompt: P.order, tokens: ["我们", "七点", "在门口", "见"], tr: t("On se retrouve à 7 h devant l'entrée.", "Let's meet at seven at the entrance.") },
      {
        type: "listen",
        zh: "明天下午我不能去。",
        options: ["明天下午我能去。", "明天上午我不能去。", "明天下午我不能去。", "明天下午我不想去。"],
        answer: 2,
        tr: t("Demain après-midi, je ne peux pas y aller.", "I can't go tomorrow afternoon."),
      },
      {
        type: "listen",
        zh: "你有时间吗？",
        options: ["你有时间吗？", "你有手机吗？", "你有事吗？", "你有钱吗？"],
        answer: 0,
        tr: t("Tu as le temps ? / Tu es libre ?", "Do you have time? / Are you free?"),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("打电话", "dǎ diànhuà", "téléphoner", "to make a phone call"),
          pair("手机", "shǒujī", "portable", "mobile phone"),
          pair("时间", "shíjiān", "temps (disponible)", "time"),
          pair("门口", "ménkǒu", "entrée, devant la porte", "entrance, doorway"),
          pair("忘", "wàng", "oublier", "to forget"),
          pair("告诉", "gàosu", "dire à, informer", "to tell"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle phrase exprime une compétence apprise ?", "Which sentence expresses a learned skill?"),
        options: ["我今天能开车。", "我想开车。", "我在开车。", "我会开车。"],
        answer: 3,
        explain: t("会 = savoir faire (appris) ; 能 = pouvoir (conditions, permission).", "会 = know how (learned); 能 = be able (conditions, permission)."),
      },
    ],
  },

  // ═══════════════════════════ L14 ═══════════════════════════
  {
    id: "hsk1-l14",
    level: 1,
    order: 14,
    title: t("Pourquoi tu n'es pas venu ?", "Why weren't you in class?"),
    subtitle: t("L'école, le travail et ce qui s'est passé", "School, work and what happened"),
    theme: "school",
    goals: [
      t("Raconter une action accomplie avec 了", "Talk about completed actions with 了"),
      t("Nier une action passée avec 没 (sans 了)", "Negate a past action with 没 (without 了)"),
      t("Demander si quelque chose a été fait : …了没有？", "Ask whether something was done: …了没有？"),
      t("Dire comment on fait quelque chose avec 地", "Say how something is done with 地"),
      t("Parler des cours, des examens et d'un petit boulot", "Talk about classes, exams and a part-time job"),
    ],
    dialogue: {
      context: t(
        "Lundi matin, Wang Ming retrouve Marc, qui n'était pas en cours la semaine dernière.",
        "Monday morning, Wang Ming runs into Marc, who missed class last week.",
      ),
      lines: [
        line("王明", "马克，你昨天怎么没来上课？", "Mǎkè, nǐ zuótiān zěnme méi lái shàngkè?", "Marc, pourquoi tu n'es pas venu en cours hier ?", "Marc, how come you weren't in class yesterday?"),
        line("马克", "我生病了，去了医院。", "Wǒ shēngbìng le, qùle yīyuàn.", "J'étais malade, je suis allé à l'hôpital.", "I was sick, I went to the hospital."),
        line("王明", "现在好了没有？", "Xiànzài hǎo le méiyǒu?", "Ça va mieux maintenant ?", "Are you better now?"),
        line("马克", "好了，谢谢。昨天老师说了什么？", "Hǎo le, xièxie. Zuótiān lǎoshī shuōle shénme?", "Oui, merci. Qu'est-ce que la prof a dit hier ?", "Yes, thanks. What did the teacher say yesterday?"),
        line("王明", "老师说星期五考试。她说了两次！", "Lǎoshī shuō xīngqīwǔ kǎoshì. Tā shuōle liǎng cì!", "Elle a dit qu'il y a un examen vendredi. Elle l'a dit deux fois !", "She said there's an exam on Friday. She said it twice!"),
        line("马克", "星期五考试？我还没准备！", "Xīngqīwǔ kǎoshì? Wǒ hái méi zhǔnbèi!", "Un examen vendredi ? Je n'ai pas encore révisé !", "An exam on Friday? I haven't prepared yet!"),
        line("王明", "没关系，我们一起去图书馆准备吧。你拿了汉语书没有？", "Méi guānxi, wǒmen yìqǐ qù túshūguǎn zhǔnbèi ba. Nǐ nále Hànyǔ shū méiyǒu?", "Pas de souci, allons réviser ensemble à la bibliothèque. Tu as pris ton livre de chinois ?", "No worries, let's go prepare at the library together. Did you bring your Chinese book?"),
        line("马克", "拿了，在书包里。", "Ná le, zài shūbāo li.", "Oui, il est dans mon sac.", "Yes, it's in my bag."),
        line("王明", "好，我们走吧。今天要认真地学习！", "Hǎo, wǒmen zǒu ba. Jīntiān yào rènzhēn de xuéxí!", "Bien, allons-y. Aujourd'hui, on travaille sérieusement !", "Good, let's go. Today we study seriously!"),
        line("马克", "好！下午五点我还要去上班。", "Hǎo! Xiàwǔ wǔ diǎn wǒ hái yào qù shàngbān.", "D'accord ! À 17 h, je dois aussi aller travailler.", "OK! I also have to go to work at five."),
      ],
    },
    vocab: ["学校", "上课", "下课", "上学", "放学", "考试", "考", "课本", "课文", "书包", "听写", "生病", "病", "看病", "医院", "准备", "拿", "次", "上次", "看见", "听见", "找到", "记住", "工作", "上班", "工人", "大学", "学院", "教", "回答"],
    grammar: ["hsk1-g46", "hsk1-g48", "hsk1-g28"],
    culture: {
      title: t("Le 高考, l'examen qui décide de tout", "The gaokao, the exam that decides everything"),
      body: t(
        "Chaque année, début juin, plus de **13 millions** de lycéens chinois passent le **高考** (gāokǎo), le concours national d'entrée à l'université. Pendant ces deux ou trois jours, on détourne la circulation autour des centres d'examen, on interdit les klaxons, et les parents attendent devant les grilles.\n\nLa scolarité est intense : cours le matin, l'après-midi, puis **études du soir** (晚自习) au lycée. Beaucoup d'élèves ont aussi des cours particuliers le week-end.\n\nÀ l'université, les étudiants vivent en général sur le **campus**, à 4 ou 6 par chambre. Et dans le monde du travail, tu entendras parler du rythme « **996** » (de 9 h à 21 h, 6 jours sur 7), très critiqué aujourd'hui.",
        "Every year in early June, over **13 million** Chinese high-school students sit the **高考** (gāokǎo), the national university entrance exam. For those two or three days, traffic is diverted around exam centers, honking is banned, and parents wait outside the gates.\n\nSchooling is intense: classes in the morning, afternoon, then **evening study** (晚自习) at school. Many students also take private lessons on weekends.\n\nAt university, students usually live **on campus**, four to six per room. And in the working world, you'll hear of the “**996**” schedule (9 a.m. to 9 p.m., six days a week), now heavily criticized.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Je n'ai pas pris de petit-déjeuner. »", "Translate: “I didn't have breakfast.”"),
        options: ["我没吃了早饭。", "我不吃早饭了。", "我没吃早饭。", "我吃没早饭。"],
        answer: 2,
        explain: t("Négation du passé : 没 + verbe, et on supprime 了.", "Past negative: 没 + verb, and drop 了."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Il a acheté deux livres. »", "Translate: “He bought two books.”"),
        options: ["他了买两本书。", "他买了两本书。", "他买两本书了了。", "他两本了书买。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你吃饭了",
        after: "？——还没呢。",
        options: ["吗", "是", "的", "也"],
        answer: 0,
        tr: t("Tu as mangé ? — Pas encore.", "Have you eaten? — Not yet."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "他昨天",
        after: "来上课，他生病了。",
        options: ["不", "没", "别", "了"],
        answer: 1,
        tr: t("Il n'est pas venu en cours hier, il était malade.", "He didn't come to class yesterday, he was sick."),
        explain: t("Fait passé non réalisé : 没, pas 不.", "A past event that didn't happen: 没, not 不."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我们要认真",
        after: "准备考试。",
        options: ["是", "了", "地", "很"],
        answer: 2,
        tr: t("Nous devons préparer l'examen sérieusement.", "We need to prepare for the exam seriously."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你吃早饭了",
        after: "？",
        options: ["没有", "不", "别", "是"],
        answer: 0,
        tr: t("Tu as pris ton petit-déjeuner ?", "Have you had breakfast?"),
      },
      { type: "order", prompt: P.order, tokens: ["我", "昨天", "没", "来", "上课"], tr: t("Je ne suis pas venu en cours hier.", "I didn't come to class yesterday.") },
      { type: "order", prompt: P.order, tokens: ["老师", "说了", "两次"], tr: t("La professeure l'a dit deux fois.", "The teacher said it twice.") },
      {
        type: "listen",
        zh: "我生病了，去了医院。",
        options: ["我生病了，没去医院。", "我生病了，去了医院。", "他生病了，去了医院。", "我没生病，去了学校。"],
        answer: 1,
        tr: t("J'étais malade, je suis allé à l'hôpital.", "I was sick and went to the hospital."),
      },
      {
        type: "listen",
        zh: "我还没准备。",
        options: ["我准备了。", "我没去医院。", "我还要准备。", "我还没准备。"],
        answer: 3,
        tr: t("Je n'ai pas encore révisé.", "I haven't prepared yet."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("考试", "kǎoshì", "examen", "exam"),
          pair("上课", "shàngkè", "aller en cours", "to attend class"),
          pair("生病", "shēngbìng", "tomber malade", "to get sick"),
          pair("书包", "shūbāo", "cartable, sac", "schoolbag"),
          pair("准备", "zhǔnbèi", "préparer", "to prepare"),
          pair("上班", "shàngbān", "aller travailler", "to go to work"),
        ],
      },
      {
        type: "choice",
        prompt: t("On te demande 你看见我的书了吗？ Tu ne l'as pas vu. Que réponds-tu ?", "Someone asks 你看见我的书了吗？ You haven't seen it. What do you say?"),
        options: ["不看见。", "没看见了。", "没看见。", "别看见。"],
        answer: 2,
        explain: t("没 + verbe, sans 了.", "没 + verb, without 了."),
      },
    ],
  },

  // ═══════════════════════════ L15 ═══════════════════════════
  {
    id: "hsk1-l15",
    level: 1,
    order: 15,
    title: t("Le Nouvel An chez Wang Ming", "New Year at Wang Ming's"),
    subtitle: t("Révision : une histoire pour tout reprendre", "Review: a story that brings it all together"),
    theme: "culture",
    goals: [
      t("Comprendre une histoire qui mobilise tout le niveau 1", "Understand a story that uses all of level 1"),
      t("Faire deux choses à la fois avec 一边…一边…", "Do two things at once with 一边…一边…"),
      t("Raconter ce que tu as fait pour quelqu'un : 给…买了…", "Say what you did for someone: 给…买了…"),
      t("Présenter tes vœux et remercier au Nouvel An", "Give New Year greetings and say thank you"),
    ],
    dialogue: {
      context: t(
        "C'est la fête du Printemps. Wang Ming a invité Marc à passer le réveillon dans sa famille.",
        "It's Spring Festival. Wang Ming has invited Marc to spend New Year's Eve with his family.",
      ),
      lines: [
        line("王明", "爸爸、妈妈，这是我的朋友马克。", "Bàba, māma, zhè shì wǒ de péngyou Mǎkè.", "Papa, maman, voici mon ami Marc.", "Dad, Mom, this is my friend Marc."),
        line("马克", "您好！新年好！", "Nín hǎo! Xīnnián hǎo!", "Bonjour ! Bonne année !", "Hello! Happy New Year!"),
        line("王明的妈妈", "新年好！马克，快进来！你会说中文，太好了！", "Xīnnián hǎo! Mǎkè, kuài jìnlái! Nǐ huì shuō Zhōngwén, tài hǎo le!", "Bonne année ! Marc, entre vite ! Tu parles chinois, c'est formidable !", "Happy New Year! Come in, Marc! You speak Chinese, how wonderful!"),
        line("马克", "我会说一点儿。我给你们买了一些水果。", "Wǒ huì shuō yìdiǎnr. Wǒ gěi nǐmen mǎile yìxiē shuǐguǒ.", "Un petit peu. Je vous ai apporté des fruits.", "Just a little. I bought you some fruit."),
        line("王明的爸爸", "谢谢你！来，请坐，请喝茶。你想家吗？", "Xièxie nǐ! Lái, qǐng zuò, qǐng hē chá. Nǐ xiǎng jiā ma?", "Merci ! Viens, assieds-toi, prends du thé. Ta famille ne te manque pas ?", "Thank you! Come, sit down, have some tea. Do you miss home?"),
        line("马克", "有时候想。昨天我给妈妈打了电话。", "Yǒu shíhou xiǎng. Zuótiān wǒ gěi māma dǎle diànhuà.", "Parfois. Hier, j'ai appelé ma mère.", "Sometimes. I called my mom yesterday."),
        line("王明的妈妈", "饭好了！我们一边吃饭，一边看电视吧。", "Fàn hǎo le! Wǒmen yìbiān chī fàn, yìbiān kàn diànshì ba.", "À table ! On mange devant la télé.", "Dinner's ready! Let's eat and watch TV."),
        line("王明的爸爸", "马克，这是给你的红包。", "Mǎkè, zhè shì gěi nǐ de hóngbāo.", "Marc, voici une enveloppe rouge pour toi.", "Marc, here's a red envelope for you."),
        line("马克", "谢谢！今天我非常高兴！", "Xièxie! Jīntiān wǒ fēicháng gāoxìng!", "Merci ! Je suis vraiment très heureux aujourd'hui !", "Thank you! I'm so happy today!"),
        line("王明", "明年你也来我家吧！", "Míngnián nǐ yě lái wǒ jiā ba!", "L'année prochaine, reviens chez nous !", "Come to our place next year too!"),
      ],
    },
    vocab: ["新年", "家人", "家里", "送", "一些", "一边", "进来", "快", "明年", "去年", "老人", "小朋友", "笑", "高兴", "非常", "打电话", "电视", "喝", "茶", "朋友"],
    grammar: ["hsk1-g47", "hsk1-g46", "hsk1-g45", "hsk1-g36"],
    culture: {
      title: t("Le Nouvel An chinois et les enveloppes rouges", "Chinese New Year and red envelopes"),
      body: t(
        "La **fête du Printemps** (春节) est la plus grande fête chinoise : elle tombe entre fin janvier et mi-février selon le calendrier lunaire. La veille, toute la famille se réunit pour le **dîner du réveillon** (年夜饭) — raviolis (饺子) dans le Nord — puis regarde le grand **gala de la télévision** (春晚) en direct.\n\nLes aînés offrent aux enfants (et aux jeunes non mariés) des **enveloppes rouges** (红包) remplies de billets neufs. Le rouge porte chance. On évite les montants avec un **4** et on préfère les sommes paires ou avec des **6** et des **8** (600, 888…). On reçoit l'enveloppe **à deux mains** et on ne l'ouvre pas devant celui qui la donne. Aujourd'hui, on s'envoie aussi des 红包 virtuels sur WeChat !\n\nFormules de vœux : **新年好！** ou **新年快乐！** (niveau 2), et le très populaire **恭喜发财！** (« prospérité ! »).",
        "**Spring Festival** (春节) is the biggest Chinese holiday: it falls between late January and mid-February, following the lunar calendar. On the eve, the whole family gathers for the **reunion dinner** (年夜饭) — dumplings (饺子) in the North — then watches the big **TV gala** (春晚) live.\n\nElders give children (and unmarried young adults) **red envelopes** (红包) filled with crisp new bills. Red brings luck. Amounts with a **4** are avoided; even sums or ones with **6**s and **8**s (600, 888…) are preferred. You take the envelope **with both hands** and don't open it in front of the giver. Today people also send virtual 红包 on WeChat!\n\nGreetings: **新年好！** or **新年快乐！** (level 2), and the ever-popular **恭喜发财！** (“wishing you prosperity!”).",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Il chante en marchant. »", "Translate: “He sings while walking.”"),
        options: ["他一边走路，一边唱歌。", "他一边走路，他一边唱歌。", "一边他走路，一边唱歌。", "他走路一边，唱歌一边。"],
        answer: 0,
        explain: t("Le sujet une seule fois, puis 一边 + verbe, 一边 + verbe.", "Subject once, then 一边 + verb, 一边 + verb."),
      },
      {
        type: "choice",
        prompt: t("Traduis : « Je vous ai acheté des fruits. »", "Translate: “I bought you some fruit.”"),
        options: ["我买了你们一些水果。", "我给你们买了一些水果。", "我给买了你们一些水果。", "我你们给买了水果。"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我们一边吃饭，",
        after: "看电视吧。",
        options: ["一边", "也", "还是", "和"],
        answer: 0,
        tr: t("On mange devant la télé.", "Let's eat while watching TV."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "昨天我给妈妈打",
        after: "电话。",
        options: ["吗", "了", "呢", "吧"],
        answer: 1,
        tr: t("Hier, j'ai appelé ma mère.", "I called my mom yesterday."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "今天我",
        after: "高兴！",
        options: ["是", "比", "非常", "了"],
        answer: 2,
        tr: t("Aujourd'hui, je suis vraiment très heureux !", "I'm so happy today!"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你想家",
        after: "？——有时候想。",
        options: ["吗", "是", "的", "也"],
        answer: 0,
        tr: t("Ta famille te manque ? — Parfois.", "Do you miss home? — Sometimes."),
      },
      { type: "order", prompt: P.order, tokens: ["明年", "你", "也", "来", "我家", "吧"], tr: t("L'année prochaine, viens aussi chez nous !", "Come to our place next year too!") },
      { type: "order", prompt: P.order, tokens: ["我", "给", "妈妈", "打了", "电话"], tr: t("J'ai appelé ma mère.", "I called my mom.") },
      {
        type: "listen",
        zh: "新年好！",
        options: ["你好！", "再见！", "新年好！", "谢谢！"],
        answer: 2,
        tr: t("Bonne année !", "Happy New Year!"),
      },
      {
        type: "listen",
        zh: "饭好了！我们吃饭吧。",
        options: ["饭好了！我们吃饭吧。", "饭好吃！我们吃饭吧。", "饭好了吗？我们吃饭吧。", "饭好了！我们喝茶吧。"],
        answer: 0,
        tr: t("À table ! Mangeons.", "Dinner's ready! Let's eat."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("新年", "xīnnián", "Nouvel An", "New Year"),
          pair("家人", "jiārén", "famille (les membres)", "family members"),
          pair("送", "sòng", "offrir ; raccompagner", "to give; to see off"),
          pair("一些", "yìxiē", "quelques, un peu de", "some"),
          pair("高兴", "gāoxìng", "content, heureux", "happy"),
          pair("明年", "míngnián", "l'année prochaine", "next year"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quel montant vaut-il mieux éviter dans un 红包 ?", "Which amount is best avoided in a 红包?"),
        options: ["六百块", "八百八十八块", "两百块", "四百块"],
        answer: 3,
        explain: t("四 (sì) ressemble à 死 (sǐ, « mort »).", "四 (sì) sounds like 死 (sǐ, “death”)."),
      },
      {
        type: "choice",
        prompt: t("D'après le dialogue : qui Marc a-t-il appelé hier ?", "According to the dialogue: who did Marc call yesterday?"),
        zh: "昨天马克给谁打了电话？",
        pinyin: "Zuótiān Mǎkè gěi shéi dǎle diànhuà?",
        options: [
          t("Wang Ming", "Wang Ming"),
          t("sa mère", "his mom"),
          t("son père", "his dad"),
          t("Li Yue", "Li Yue"),
        ],
        answer: 1,
      },
    ],
  },
];
