import type { Lesson } from "../../types";
import { P, line, pair, t } from "./helpers";

/** HSK 1 — lessons 1 to 8. */
export const lessonsA: Lesson[] = [
  // ═══════════════════════════ L01 ═══════════════════════════
  {
    id: "hsk1-l01",
    level: 1,
    order: 1,
    title: t("Bonjour ! Je m'appelle…", "Hello! My name is…"),
    subtitle: t("Saluer, se présenter, demander un nom", "Greeting people, introducing yourself, asking names"),
    theme: "greetings",
    goals: [
      t("Saluer un ami avec 你好 et un professeur avec 您好 / 老师好", "Greet a friend with 你好 and a teacher with 您好 / 老师好"),
      t("Dire ton nom avec 我叫…", "Say your name with 我叫…"),
      t("Demander le nom de quelqu'un : 你叫什么名字？", "Ask someone's name: 你叫什么名字？"),
      t("Renvoyer une question avec 呢", "Bounce a question back with 呢"),
      t("Remercier, s'excuser et répondre poliment", "Say thank you, apologize and reply politely"),
    ],
    dialogue: {
      context: t(
        "Premier jour de cours dans une université de Pékin. Marc, un étudiant français, rencontre Wang Ming devant la salle de classe. Leur professeure, Mme Li, arrive.",
        "First day of class at a university in Beijing. Marc, a French student, meets Wang Ming outside the classroom. Their teacher, Ms. Li, arrives.",
      ),
      lines: [
        line("王明", "你好！我叫王明。你叫什么名字？", "Nǐ hǎo! Wǒ jiào Wáng Míng. Nǐ jiào shénme míngzi?", "Salut ! Je m'appelle Wang Ming. Et toi, comment tu t'appelles ?", "Hi! I'm Wang Ming. What's your name?"),
        line("马克", "你好，王明！我叫马克。", "Nǐ hǎo, Wáng Míng! Wǒ jiào Mǎkè.", "Salut, Wang Ming ! Moi, c'est Marc.", "Hi, Wang Ming! I'm Marc."),
        line("王明", "认识你很高兴！", "Rènshi nǐ hěn gāoxìng!", "Enchanté !", "Nice to meet you!"),
        line("马克", "认识你，我也很高兴！", "Rènshi nǐ, wǒ yě hěn gāoxìng!", "Moi aussi, enchanté !", "Nice to meet you too!"),
        line("王明", "李老师，您好！", "Lǐ lǎoshī, nín hǎo!", "Bonjour, madame Li !", "Hello, Ms. Li!"),
        line("李老师", "你们好！他叫什么名字？", "Nǐmen hǎo! Tā jiào shénme míngzi?", "Bonjour à vous deux ! Comment il s'appelle ?", "Hello, you two! What's his name?"),
        line("王明", "他叫马克。", "Tā jiào Mǎkè.", "Il s'appelle Marc.", "His name is Marc."),
        line("马克", "老师好！", "Lǎoshī hǎo!", "Bonjour, madame !", "Hello, teacher!"),
        line("李老师", "马克，你好！王明，你的书呢？", "Mǎkè, nǐ hǎo! Wáng Míng, nǐ de shū ne?", "Bonjour, Marc ! Wang Ming, où est ton livre ?", "Hello, Marc! Wang Ming, where's your book?"),
        line("王明", "对不起，老师……我的书在家！", "Duìbuqǐ, lǎoshī…… wǒ de shū zài jiā!", "Pardon, madame… mon livre est resté à la maison !", "Sorry, teacher… my book is at home!"),
      ],
    },
    vocab: ["你", "您", "我", "他", "她", "你们", "我们", "他们", "她们", "们", "好", "叫", "什么", "名字", "认识", "高兴", "也", "很", "老师", "谢谢", "不客气", "对不起", "没关系", "再见", "书", "呢"],
    grammar: ["hsk1-g01", "hsk1-g02", "hsk1-g03", "hsk1-g04"],
    culture: {
      title: t("你好, 您好 ou 老师好 ?", "你好, 您好 or 老师好?"),
      body: t(
        "**你好** est la salutation passe-partout, mais entre amis proches ou en famille, les Chinois la disent assez peu : on s'appelle par son prénom, ou on commente la situation (« tu vas en cours ? »).\n\n**您好** marque le **respect** : pour un professeur, une personne âgée, un client. Avec un titre, la formule la plus naturelle est **titre + 好** : **老师好！**, **李老师好！** C'est ce que disent tous les élèves chinois en entrant en classe.\n\n**你好吗？** existe, mais sonne un peu « manuel scolaire ». Pour demander le nom de famille poliment, tu entendras aussi **您贵姓？** (« quel est votre honorable nom ? ») — on y répond 我姓王 (formule du niveau 2).\n\nEnfin, 王明 : **le nom de famille vient toujours en premier**. On appellera donc le professeur **李老师** (« professeur Li »), jamais par son prénom.",
        "**你好** is the all-purpose greeting, but close friends and family rarely use it: they call each other by name or comment on what's happening (“off to class?”).\n\n**您好** shows **respect**: for a teacher, an older person, a customer. With a title, the most natural formula is **title + 好**: **老师好！**, **李老师好！** Every Chinese pupil says this when entering class.\n\n**你好吗？** exists but sounds a bit “textbook”. To ask a surname politely you'll also hear **您贵姓？** (“what is your honorable name?”) — answered with 我姓王 (a level-2 phrase).\n\nFinally, in 王明 **the family name always comes first**. So the teacher is called **李老师** (“Teacher Li”), never by her given name.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Tu entres en classe. Comment salues-tu poliment ta professeure ?", "You walk into class. How do you greet your teacher politely?"),
        options: ["你们好！", "老师好！", "再见！", "谢谢！"],
        answer: 1,
        explain: t("« Titre + 好 » est la salutation respectueuse typique : 老师好！", "“Title + 好” is the typical respectful greeting: 老师好！"),
      },
      {
        type: "choice",
        prompt: P.meaning,
        zh: "你叫什么名字？",
        pinyin: "Nǐ jiào shénme míngzi?",
        options: [
          t("Comment vas-tu ?", "How are you?"),
          t("D'où viens-tu ?", "Where are you from?"),
          t("Comment tu t'appelles ?", "What's your name?"),
          t("Qui est-ce ?", "Who is that?"),
        ],
        answer: 2,
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "马克。",
        options: ["叫", "什么", "呢", "您"],
        answer: 0,
        tr: t("Je m'appelle Marc.", "My name is Marc."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我叫王明，你",
        after: "？",
        options: ["什么", "呢", "叫", "吗"],
        answer: 1,
        tr: t("Je m'appelle Wang Ming, et toi ?", "I'm Wang Ming, and you?"),
        explain: t("呢 après un pronom renvoie la question : « et toi ? ».", "呢 after a pronoun bounces the question back: “and you?”."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你叫",
        after: "名字？",
        options: ["呢", "我", "什么", "好"],
        answer: 2,
        tr: t("Comment tu t'appelles ?", "What's your name?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "李老师，",
        after: "好！",
        options: ["你们", "她", "您", "我"],
        answer: 2,
        tr: t("Bonjour, madame Li !", "Hello, Ms. Li!"),
        explain: t("On s'adresse à une seule personne, avec respect : 您.", "You're addressing one person respectfully: 您."),
      },
      { type: "order", prompt: P.order, tokens: ["你", "叫", "什么", "名字"], tr: t("Comment tu t'appelles ?", "What's your name?") },
      { type: "order", prompt: P.order, tokens: ["认识你", "很", "高兴"], tr: t("Enchanté.", "Nice to meet you.") },
      {
        type: "listen",
        zh: "认识你很高兴！",
        options: ["我也很高兴！", "认识你很高兴！", "你叫什么名字？", "老师，您好！"],
        answer: 1,
        tr: t("Enchanté !", "Nice to meet you!"),
      },
      {
        type: "listen",
        zh: "我的书呢？",
        options: ["你的书呢？", "我的书在家。", "你呢？", "我的书呢？"],
        answer: 3,
        tr: t("Où est mon livre ?", "Where's my book?"),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("你好", "nǐ hǎo", "bonjour, salut", "hello"),
          pair("谢谢", "xièxie", "merci", "thank you"),
          pair("再见", "zàijiàn", "au revoir", "goodbye"),
          pair("对不起", "duìbuqǐ", "pardon, désolé", "sorry"),
          pair("老师", "lǎoshī", "professeur", "teacher"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelqu'un te dit 谢谢！ Que réponds-tu ?", "Someone says 谢谢！ to you. What do you answer?"),
        options: ["不客气！", "对不起！", "你呢？", "您好！"],
        answer: 0,
        explain: t("不客气 (bú kèqi) = « de rien ». Et à 对不起, on répond 没关系.", "不客气 (bú kèqi) = “you're welcome”. And to 对不起, you answer 没关系."),
      },
    ],
  },

  // ═══════════════════════════ L02 ═══════════════════════════
  {
    id: "hsk1-l02",
    level: 1,
    order: 2,
    title: t("Tu as quel âge ?", "How old are you?"),
    subtitle: t("Les nombres, l'âge et le numéro de téléphone", "Numbers, age and phone numbers"),
    theme: "greetings",
    goals: [
      t("Dire qui tu es avec 是 / 不是", "Say who you are with 是 / 不是"),
      t("Poser une question fermée avec 吗", "Ask a yes/no question with 吗"),
      t("Compter de 0 à 999 et choisir entre 二 et 两", "Count from 0 to 999 and choose between 二 and 两"),
      t("Demander et dire l'âge, un nombre, un numéro de portable", "Ask and give an age, a number, a phone number"),
    ],
    dialogue: {
      context: t(
        "À la résidence universitaire, Marc croise une étudiante chinoise, Li Yue. Ils font connaissance et échangent leurs numéros.",
        "At the dorm, Marc bumps into a Chinese student, Li Yue. They get to know each other and swap numbers.",
      ),
      lines: [
        line("李月", "你是马克吗？", "Nǐ shì Mǎkè ma?", "Tu es Marc ?", "Are you Marc?"),
        line("马克", "是，我是马克。你是学生吗？", "Shì, wǒ shì Mǎkè. Nǐ shì xuésheng ma?", "Oui, c'est moi. Tu es étudiante ?", "Yes, I'm Marc. Are you a student?"),
        line("李月", "是，我是学生。我叫李月。", "Shì, wǒ shì xuésheng. Wǒ jiào Lǐ Yuè.", "Oui, je suis étudiante. Je m'appelle Li Yue.", "Yes, I'm a student. My name is Li Yue."),
        line("马克", "李月，你今年多大？", "Lǐ Yuè, nǐ jīnnián duō dà?", "Li Yue, tu as quel âge ?", "Li Yue, how old are you?"),
        line("李月", "我今年十九岁。你呢？", "Wǒ jīnnián shíjiǔ suì. Nǐ ne?", "J'ai dix-neuf ans. Et toi ?", "I'm nineteen. And you?"),
        line("马克", "我二十一岁。你的手机号是多少？", "Wǒ èrshíyī suì. Nǐ de shǒujī hào shì duōshao?", "J'ai vingt et un ans. C'est quoi ton numéro de portable ?", "I'm twenty-one. What's your phone number?"),
        line("李月", "一三八，六七五九，〇二四一。", "Yāo sān bā, liù qī wǔ jiǔ, líng èr sì yāo.", "138 6759 0241.", "138 6759 0241."),
        line("马克", "一三八，六七五九，〇二四一，对吗？", "Yāo sān bā, liù qī wǔ jiǔ, líng èr sì yāo, duì ma?", "138 6759 0241, c'est ça ?", "138 6759 0241, right?"),
        line("李月", "对。你们班有多少学生？", "Duì. Nǐmen bān yǒu duōshao xuésheng?", "C'est ça. Vous êtes combien d'étudiants dans ta classe ?", "Right. How many students are in your class?"),
        line("马克", "我们班有十五个学生。", "Wǒmen bān yǒu shíwǔ ge xuésheng.", "Nous sommes quinze.", "There are fifteen students in our class."),
      ],
    },
    vocab: ["是", "不", "吗", "学生", "零", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "百", "两", "几", "多少", "多", "大", "岁", "今年", "手机", "号", "对", "班", "朋友", "个"],
    grammar: ["hsk1-g05", "hsk1-g06", "hsk1-g07", "hsk1-g08"],
    culture: {
      title: t("Les chiffres porte-bonheur (et les autres)", "Lucky numbers (and unlucky ones)"),
      body: t(
        "En Chine, les chiffres ont une personnalité ! **八** (bā, 8) sonne comme 发 (fā, « faire fortune ») : c'est le chiffre roi. Les Jeux olympiques de Pékin ont commencé le 08/08/2008 à 8 h 08 du soir, et un numéro de portable plein de 8 peut se vendre très cher.\n\n**六** (liù, 6) évoque 溜 (« couler, fluide ») : tout se passe bien. En ligne, **666** veut dire « trop fort ! ».\n\nÀ l'inverse, **四** (sì, 4) ressemble à 死 (sǐ, « mort ») : beaucoup d'immeubles n'ont pas de 4e étage, et on évite les numéros avec des 4.\n\nAu téléphone, 1 se dit **yāo** pour ne pas le confondre avec 七 (qī). Et pour compter de 6 à 10 d'une seule main, les Chinois utilisent des **gestes spéciaux** : le 6 ressemble au « téléphone » (pouce et petit doigt tendus).",
        "In China, numbers have personalities! **八** (bā, 8) sounds like 发 (fā, “to get rich”): it's the king of numbers. The Beijing Olympics opened on 08/08/2008 at 8:08 p.m., and a phone number full of 8s can sell for a fortune.\n\n**六** (liù, 6) evokes 溜 (“smooth”): things go well. Online, **666** means “awesome!”.\n\nOn the other hand, **四** (sì, 4) sounds like 死 (sǐ, “death”): many buildings skip the 4th floor, and people avoid numbers with 4s.\n\nOn the phone, 1 is read **yāo** so it isn't confused with 七 (qī). And to count 6–10 on one hand, Chinese people use **special gestures**: 6 looks like the “call me” sign (thumb and pinky out).",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment dit-on « 25 » ?", "How do you say “25”?"),
        options: ["五十二", "二十五", "二五", "十二五"],
        answer: 1,
        explain: t("On dit « deux-dix-cinq » : 二十五. 五十二 = 52.", "It's “two-ten-five”: 二十五. 五十二 = 52."),
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « deux personnes » ?", "How do you say “two people”?"),
        options: ["二个人", "两人个", "二人", "两个人"],
        answer: 3,
        explain: t("Devant un spécificatif (个), on utilise 两, pas 二.", "Before a measure word (个), use 两, not 二."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你是学生",
        after: "？",
        options: ["吗", "呢", "什么", "是"],
        answer: 0,
        tr: t("Tu es étudiant ?", "Are you a student?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "老师，我是学生。",
        options: ["不是", "是", "没有", "不"],
        answer: 0,
        tr: t("Je ne suis pas professeur, je suis étudiant.", "I'm not a teacher, I'm a student."),
        explain: t("La négation de 是 est 不是 (bú shì).", "The negative of 是 is 不是 (bú shì)."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你们班有",
        after: "学生？",
        options: ["多少", "几", "什么", "谁"],
        answer: 0,
        tr: t("Combien d'étudiants y a-t-il dans ta classe ?", "How many students are in your class?"),
        explain: t("几 exige un spécificatif (几个学生) ; 多少 peut s'en passer.", "几 needs a measure word (几个学生); 多少 can go without one."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我今年十九",
        after: "。",
        options: ["年", "个", "岁", "号"],
        answer: 2,
        tr: t("J'ai dix-neuf ans.", "I'm nineteen."),
      },
      { type: "order", prompt: P.order, tokens: ["你", "今年", "多大"], tr: t("Tu as quel âge ?", "How old are you?") },
      { type: "order", prompt: P.order, tokens: ["我们班", "有", "十五个", "学生"], tr: t("Il y a quinze étudiants dans notre classe.", "There are fifteen students in our class.") },
      {
        type: "listen",
        zh: "我二十一岁。",
        options: ["我十二岁。", "我二十一岁。", "我二十岁。", "我十一岁。"],
        answer: 1,
        tr: t("J'ai vingt et un ans.", "I'm twenty-one."),
      },
      {
        type: "listen",
        zh: "你是学生吗？",
        options: ["你是老师吗？", "他是学生吗？", "你是学生。", "你是学生吗？"],
        answer: 3,
        tr: t("Tu es étudiant ?", "Are you a student?"),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("零", "líng", "zéro", "zero"),
          pair("七", "qī", "sept", "seven"),
          pair("十", "shí", "dix", "ten"),
          pair("百", "bǎi", "cent", "hundred"),
          pair("两", "liǎng", "deux (+ spécificatif)", "two (+ measure word)"),
          pair("岁", "suì", "an (d'âge)", "year (of age)"),
        ],
      },
      {
        type: "choice",
        prompt: t("On te demande 你是老师吗？ Tu es étudiant. Que réponds-tu ?", "Someone asks 你是老师吗？ You're a student. What do you answer?"),
        options: ["不是，我是学生。", "是，我是学生。", "不，我老师。", "我不是学生。"],
        answer: 0,
        explain: t("On répond en reprenant le verbe : 不是, puis on précise.", "Answer by repeating the verb: 不是, then clarify."),
      },
    ],
  },

  // ═══════════════════════════ L03 ═══════════════════════════
  {
    id: "hsk1-l03",
    level: 1,
    order: 3,
    title: t("Ma famille", "My family"),
    subtitle: t("Présenter sa famille, dire ce qu'on a", "Introducing your family, saying what you have"),
    theme: "family",
    goals: [
      t("Nommer les membres de la famille (frères et sœurs aînés et cadets)", "Name family members (older and younger siblings)"),
      t("Exprimer la possession avec 的", "Express possession with 的"),
      t("Dire ce qu'on a ou n'a pas avec 有 / 没有", "Say what you have or don't have with 有 / 没有"),
      t("Compter avec les spécificatifs 个, 口, 本", "Count with the measure words 个, 口, 本"),
      t("Demander « qui ? » avec 谁", "Ask “who?” with 谁"),
    ],
    dialogue: {
      context: t(
        "Dans la chambre de Marc, Wang Ming regarde les photos de famille posées sur le bureau.",
        "In Marc's room, Wang Ming looks at the family photos on the desk.",
      ),
      lines: [
        line("王明", "马克，这是谁？", "Mǎkè, zhè shì shéi?", "Marc, c'est qui ?", "Marc, who's this?"),
        line("马克", "这是我爸爸，这是我妈妈。", "Zhè shì wǒ bàba, zhè shì wǒ māma.", "C'est mon père, et là, c'est ma mère.", "This is my dad, and this is my mom."),
        line("王明", "这个男孩儿是谁？", "Zhège nánháir shì shéi?", "Et ce garçon, c'est qui ?", "Who's this boy?"),
        line("马克", "他是我弟弟，他十二岁。", "Tā shì wǒ dìdi, tā shí'èr suì.", "C'est mon petit frère, il a douze ans.", "He's my little brother, he's twelve."),
        line("王明", "你家有几口人？", "Nǐ jiā yǒu jǐ kǒu rén?", "Vous êtes combien dans ta famille ?", "How many people are in your family?"),
        line("马克", "我家有五口人：爸爸、妈妈、姐姐、弟弟和我。你有哥哥吗？", "Wǒ jiā yǒu wǔ kǒu rén: bàba, māma, jiějie, dìdi hé wǒ. Nǐ yǒu gēge ma?", "On est cinq : papa, maman, ma grande sœur, mon petit frère et moi. Tu as un grand frère ?", "There are five of us: Dad, Mom, my older sister, my younger brother and me. Do you have an older brother?"),
        line("王明", "我没有哥哥，也没有姐姐。我家有三口人。", "Wǒ méiyǒu gēge, yě méiyǒu jiějie. Wǒ jiā yǒu sān kǒu rén.", "Je n'ai ni grand frère ni grande sœur. Nous sommes trois.", "I don't have an older brother or sister. There are three of us."),
        line("马克", "你爸爸做什么工作？", "Nǐ bàba zuò shénme gōngzuò?", "Qu'est-ce qu'il fait comme travail, ton père ?", "What does your dad do?"),
        line("王明", "我爸爸是医生，我妈妈是老师。", "Wǒ bàba shì yīshēng, wǒ māma shì lǎoshī.", "Mon père est médecin et ma mère est professeure.", "My dad is a doctor and my mom is a teacher."),
        line("马克", "我姐姐也是老师！", "Wǒ jiějie yě shì lǎoshī!", "Ma grande sœur aussi est prof !", "My older sister is a teacher too!"),
      ],
    },
    vocab: ["家", "爸爸", "妈妈", "哥哥", "姐姐", "弟弟", "妹妹", "爷爷", "奶奶", "儿子", "女儿", "孩子", "男孩儿", "女孩儿", "人", "有", "没有", "口", "个", "本", "谁", "的", "这", "医生", "工作", "做", "和", "家人"],
    grammar: ["hsk1-g09", "hsk1-g10", "hsk1-g11", "hsk1-g12"],
    culture: {
      title: t("Grand frère, petit frère : une famille très précise", "Older brother, younger brother: a very precise family"),
      body: t(
        "Le chinois n'a pas de mot simple pour « frère » ou « sœur » : on précise toujours **l'aîné ou le cadet** — 哥哥 (grand frère), 弟弟 (petit frère), 姐姐 (grande sœur), 妹妹 (petite sœur). L'âge compte dans la hiérarchie familiale.\n\nLes grands-parents changent aussi selon le côté : **爷爷 / 奶奶** pour les parents du père, **姥姥 / 姥爷** (ou 外婆 / 外公) pour ceux de la mère.\n\nEt on appelle souvent des **inconnus** avec des mots de famille : un homme de l'âge de tes parents est un **叔叔** (« tonton »), une femme un **阿姨** (« tata ») ; les enfants disent 哥哥 / 姐姐 aux jeunes adultes.\n\nPour les familles nées entre 1980 et 2015, la politique de l'enfant unique explique pourquoi beaucoup de jeunes Chinois, comme Wang Ming, n'ont **ni frère ni sœur**.",
        "Chinese has no simple word for “brother” or “sister”: you always specify **older or younger** — 哥哥 (older brother), 弟弟 (younger brother), 姐姐 (older sister), 妹妹 (younger sister). Age matters in the family hierarchy.\n\nGrandparents also depend on the side: **爷爷 / 奶奶** for Dad's parents, **姥姥 / 姥爷** (or 外婆 / 外公) for Mom's.\n\nPeople often address **strangers** with family words: a man your parents' age is a **叔叔** (“uncle”), a woman an **阿姨** (“auntie”); children call young adults 哥哥 / 姐姐.\n\nFor families from roughly 1980 to 2015, the one-child policy explains why many young Chinese, like Wang Ming, have **no brothers or sisters**.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Quelle est la façon la plus naturelle de dire « ma mère » ?", "What's the most natural way to say “my mom”?"),
        options: ["我妈妈", "妈妈我", "我是妈妈", "妈妈的我"],
        answer: 0,
        explain: t("Pour les proches, on omet souvent 的 : 我妈妈.", "With close relatives, 的 is usually dropped: 我妈妈."),
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « trois livres » ?", "How do you say “three books”?"),
        options: ["三书", "三个本书", "三本书", "书三本"],
        answer: 2,
        explain: t("Nombre + spécificatif + nom : 三本书.", "Number + measure word + noun: 三本书."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我有两",
        after: "中文书。",
        options: ["口", "个", "本", "杯"],
        answer: 2,
        tr: t("J'ai deux livres en chinois.", "I have two Chinese books."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "哥哥，也没有弟弟。",
        options: ["不有", "没有", "不是", "很"],
        answer: 1,
        tr: t("Je n'ai pas de grand frère, ni de petit frère.", "I have no older brother and no younger brother."),
        explain: t("有 se nie toujours avec 没 : 没有. « 不有 » n'existe pas.", "有 is always negated with 没: 没有. “不有” doesn't exist."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这是",
        after: "书？——是我的。",
        options: ["谁的", "谁", "什么", "哪"],
        answer: 0,
        tr: t("C'est le livre de qui ? — C'est le mien.", "Whose book is this? — It's mine."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这是我",
        after: "手机。",
        options: ["是", "有", "的", "个"],
        answer: 2,
        tr: t("C'est mon portable.", "This is my phone."),
      },
      { type: "order", prompt: P.order, tokens: ["我家", "有", "五口", "人"], tr: t("Nous sommes cinq dans ma famille.", "There are five people in my family.") },
      { type: "order", prompt: P.order, tokens: ["你爸爸", "做", "什么", "工作"], tr: t("Que fait ton père comme travail ?", "What does your dad do?") },
      {
        type: "listen",
        zh: "他是我弟弟。",
        options: ["他是我哥哥。", "他是我弟弟。", "她是我妹妹。", "他是我爸爸。"],
        answer: 1,
        tr: t("C'est mon petit frère.", "He's my younger brother."),
      },
      {
        type: "listen",
        zh: "我没有姐姐。",
        options: ["我有姐姐。", "我没有妹妹。", "我没有姐姐。", "我姐姐没有。"],
        answer: 2,
        tr: t("Je n'ai pas de grande sœur.", "I don't have an older sister."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("爸爸", "bàba", "papa", "dad"),
          pair("妈妈", "māma", "maman", "mom"),
          pair("哥哥", "gēge", "grand frère", "older brother"),
          pair("姐姐", "jiějie", "grande sœur", "older sister"),
          pair("弟弟", "dìdi", "petit frère", "younger brother"),
          pair("妹妹", "mèimei", "petite sœur", "younger sister"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle est la bonne réponse à 你家有几口人？", "What's the right answer to 你家有几口人？"),
        options: ["我有三个哥哥。", "我家很好。", "我三岁。", "我家有三口人。"],
        answer: 3,
      },
    ],
  },

  // ═══════════════════════════ L04 ═══════════════════════════
  {
    id: "hsk1-l04",
    level: 1,
    order: 4,
    title: t("Tu viens d'où ?", "Where are you from?"),
    subtitle: t("Nationalités et langues", "Nationalities and languages"),
    theme: "culture",
    goals: [
      t("Demander et dire sa nationalité avec 哪国人", "Ask and give nationality with 哪国人"),
      t("Dire « aussi » et « tous » avec 也 et 都", "Say “also” and “all” with 也 and 都"),
      t("Parler des langues qu'on sait parler avec 会", "Talk about languages you can speak with 会"),
      t("Nier avec 不 et appliquer le changement de ton (bú)", "Negate with 不 and apply its tone change (bú)"),
    ],
    dialogue: {
      context: t(
        "Premier cours de chinois. La professeure Li fait connaissance avec ses nouveaux élèves étrangers, Marc et Anna.",
        "First Chinese class. Ms. Li gets to know her new foreign students, Marc and Anna.",
      ),
      lines: [
        line("李老师", "同学们好！马克，你是哪国人？", "Tóngxuémen hǎo! Mǎkè, nǐ shì nǎ guó rén?", "Bonjour à tous ! Marc, tu es de quelle nationalité ?", "Hello, everyone! Marc, what's your nationality?"),
        line("马克", "我是法国人。", "Wǒ shì Fǎguórén.", "Je suis français.", "I'm French."),
        line("李老师", "安娜，你也是法国人吗？", "Ānnà, nǐ yě shì Fǎguórén ma?", "Anna, tu es française aussi ?", "Anna, are you French too?"),
        line("安娜", "不是，我不是法国人，我是美国人。", "Bú shì, wǒ bú shì Fǎguórén, wǒ shì Měiguórén.", "Non, je ne suis pas française, je suis américaine.", "No, I'm not French, I'm American."),
        line("李老师", "你们都会说汉语吗？", "Nǐmen dōu huì shuō Hànyǔ ma?", "Vous parlez tous les deux chinois ?", "Can you both speak Chinese?"),
        line("马克", "我们都会说一点儿汉语。", "Wǒmen dōu huì shuō yìdiǎnr Hànyǔ.", "On parle tous les deux un peu chinois.", "We both speak a little Chinese."),
        line("李老师", "你们会写汉字吗？", "Nǐmen huì xiě Hànzì ma?", "Et vous savez écrire les caractères ?", "Can you write Chinese characters?"),
        line("安娜", "我会写一点儿。马克不会写。", "Wǒ huì xiě yìdiǎnr. Mǎkè bú huì xiě.", "Moi, un peu. Marc, non.", "I can write a few. Marc can't."),
        line("马克", "老师，我会！我会写“你好”！", "Lǎoshī, wǒ huì! Wǒ huì xiě “nǐ hǎo”!", "Si, madame, je sais ! Je sais écrire « 你好 » !", "I can, teacher! I can write “你好”!"),
        line("李老师", "很好！我们学习汉字吧。", "Hěn hǎo! Wǒmen xuéxí Hànzì ba.", "Très bien ! Alors, étudions les caractères.", "Very good! Let's study characters, then."),
      ],
    },
    vocab: ["国", "中国", "国家", "外国", "哪", "哪儿", "哪里", "会", "说", "说话", "汉语", "中文", "汉字", "外语", "写", "读", "一点儿", "也", "都", "同学", "学", "学习", "住", "不", "字"],
    grammar: ["hsk1-g13", "hsk1-g14", "hsk1-g15", "hsk1-g16"],
    culture: {
      title: t("汉语, 中文, 普通话 : trois noms pour le chinois", "汉语, 中文, 普通话: three names for Chinese"),
      body: t(
        "**汉语** (Hànyǔ) signifie « langue des Han », l'ethnie majoritaire : c'est le terme des manuels et du HSK. **中文** (Zhōngwén) est plus courant au quotidien (« tu parles chinois ? » = 你会说中文吗？). **普通话** (pǔtōnghuà, « langue commune ») désigne précisément le **mandarin standard**, basé sur la prononciation de Pékin — celui que tu apprends ici.\n\nLes noms de pays sont souvent **phonétiques + 国** : 法国 (Fǎguó, France), 美国 (Měiguó, États-Unis), 英国 (Yīngguó, Royaume-Uni). Les caractères choisis sont flatteurs : 美 signifie « beau » ! Et 中国 = « le pays du milieu ».\n\nPour dire la nationalité, ajoute simplement **人** : 中国人, 法国人. Pour la langue, remplace par **语** ou **文** : 法语 / 法文 (le français).",
        "**汉语** (Hànyǔ) means “language of the Han”, the majority ethnic group: it's the textbook and HSK term. **中文** (Zhōngwén) is more common in daily life (“do you speak Chinese?” = 你会说中文吗？). **普通话** (pǔtōnghuà, “common speech”) refers specifically to **Standard Mandarin**, based on Beijing pronunciation — the one you're learning here.\n\nCountry names are often **phonetic + 国**: 法国 (Fǎguó, France), 美国 (Měiguó, USA), 英国 (Yīngguó, UK). The characters are flattering: 美 means “beautiful”! And 中国 = “the Middle Kingdom”.\n\nFor nationality, just add **人**: 中国人, 法国人. For the language, use **语** or **文**: 英语 / 英文 (English).",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment demander la nationalité de quelqu'un ?", "How do you ask someone's nationality?"),
        options: ["你是哪国人？", "你是什么人？", "你是哪儿？", "你国是哪？"],
        answer: 0,
      },
      {
        type: "choice",
        prompt: t("Traduis : « Nous sommes tous étudiants. »", "Translate: “We are all students.”"),
        options: ["都我们是学生。", "我们是都学生。", "我们都是学生。", "我们是学生都。"],
        answer: 2,
        explain: t("都 se place après le sujet, avant le verbe.", "都 goes after the subject, before the verb."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "他是法国人，我",
        after: "是法国人。我们都是法国人。",
        options: ["也", "都", "不", "会"],
        answer: 0,
        tr: t("Il est français, moi aussi. Nous sommes tous les deux français.", "He's French, and so am I. We're both French."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "说一点儿汉语。",
        options: ["会", "是", "都", "哪"],
        answer: 0,
        tr: t("Je parle un peu chinois.", "I can speak a little Chinese."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你们去",
        after: "？",
        options: ["什么", "哪儿", "谁", "几"],
        answer: 1,
        tr: t("Vous allez où ?", "Where are you going?"),
      },
      {
        type: "choice",
        prompt: t("Comment se prononce 不是 ?", "How is 不是 pronounced?"),
        options: ["bù shì", "bú shì", "bǔ shì", "bū shì"],
        answer: 1,
        explain: t("Devant un 4e ton (shì), 不 passe au 2e ton : bú.", "Before a 4th tone (shì), 不 changes to 2nd tone: bú."),
      },
      { type: "order", prompt: P.order, tokens: ["我", "会", "说", "一点儿", "汉语"], tr: t("Je parle un peu chinois.", "I speak a little Chinese.") },
      { type: "order", prompt: P.order, tokens: ["你们", "都", "是", "哪国人"], tr: t("Vous êtes de quelle nationalité, vous tous ?", "What nationality are you all?") },
      {
        type: "listen",
        zh: "我不会写汉字。",
        options: ["我会写汉字。", "我不会说汉语。", "我不会写汉字。", "我会说汉语。"],
        answer: 2,
        tr: t("Je ne sais pas écrire les caractères chinois.", "I can't write Chinese characters."),
      },
      {
        type: "listen",
        zh: "她也是美国人。",
        options: ["她是美国人。", "她也是美国人。", "他们都是美国人。", "她不是美国人。"],
        answer: 1,
        tr: t("Elle aussi est américaine.", "She's American too."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("中国", "Zhōngguó", "Chine", "China"),
          pair("汉语", "Hànyǔ", "langue chinoise", "Chinese language"),
          pair("汉字", "Hànzì", "caractère chinois", "Chinese character"),
          pair("外国", "wàiguó", "pays étranger", "foreign country"),
          pair("写", "xiě", "écrire", "to write"),
          pair("说", "shuō", "parler, dire", "to speak, to say"),
        ],
      },
      {
        type: "choice",
        prompt: P.meaning,
        zh: "我们都不去。",
        pinyin: "Wǒmen dōu bú qù.",
        options: [
          t("Aucun de nous n'y va.", "None of us is going."),
          t("Nous n'y allons pas tous.", "Not all of us are going."),
          t("Nous y allons tous.", "We're all going."),
          t("Nous aussi, nous y allons.", "We're going too."),
        ],
        answer: 0,
        explain: t("都不 = aucun ; 不都 = pas tous.", "都不 = none; 不都 = not all."),
      },
    ],
  },

  // ═══════════════════════════ L05 ═══════════════════════════
  {
    id: "hsk1-l05",
    level: 1,
    order: 5,
    title: t("C'est quand, ton anniversaire ?", "When's your birthday?"),
    subtitle: t("L'heure, les dates et les jours de la semaine", "Clock time, dates and days of the week"),
    theme: "time",
    goals: [
      t("Demander et dire l'heure (点, 分, 半, 差)", "Ask and tell the time (点, 分, 半, 差)"),
      t("Dire une date complète, du plus grand au plus petit", "Say a full date, from biggest to smallest"),
      t("Nommer les jours de la semaine", "Name the days of the week"),
      t("Placer les mots de temps avant le verbe", "Put time words before the verb"),
      t("Fixer un rendez-vous simple", "Set up a simple meeting"),
    ],
    dialogue: {
      context: t(
        "À la sortie du cours, Marc discute avec Li Yue. Il a entendu dire que c'est bientôt son anniversaire…",
        "After class, Marc chats with Li Yue. He's heard that her birthday is coming up…",
      ),
      lines: [
        line("马克", "李月，今天几月几号？", "Lǐ Yuè, jīntiān jǐ yuè jǐ hào?", "Li Yue, on est le combien aujourd'hui ?", "Li Yue, what's the date today?"),
        line("李月", "今天九月二十号，星期五。", "Jīntiān jiǔyuè èrshí hào, xīngqīwǔ.", "Aujourd'hui, c'est vendredi 20 septembre.", "Today is Friday, September 20th."),
        line("马克", "明天是你的生日，对吗？", "Míngtiān shì nǐ de shēngrì, duì ma?", "Demain, c'est ton anniversaire, non ?", "Tomorrow is your birthday, right?"),
        line("李月", "对！我的生日是九月二十一号。", "Duì! Wǒ de shēngrì shì jiǔyuè èrshíyī hào.", "Oui ! Mon anniversaire, c'est le 21 septembre.", "Yes! My birthday is September 21st."),
        line("马克", "明天我们一起吃饭吧！", "Míngtiān wǒmen yìqǐ chī fàn ba!", "Allons manger ensemble demain !", "Let's have dinner together tomorrow!"),
        line("李月", "好！几点？", "Hǎo! Jǐ diǎn?", "D'accord ! À quelle heure ?", "OK! What time?"),
        line("马克", "晚上六点半，行吗？", "Wǎnshang liù diǎn bàn, xíng ma?", "18 h 30, ça te va ?", "Six thirty in the evening, is that OK?"),
        line("李月", "六点半我有课。七点，好吗？", "Liù diǎn bàn wǒ yǒu kè. Qī diǎn, hǎo ma?", "À 18 h 30, j'ai cours. 19 h, ça va ?", "I have class at six thirty. How about seven?"),
        line("马克", "好，明天晚上七点见！", "Hǎo, míngtiān wǎnshang qī diǎn jiàn!", "OK, à demain soir, 19 h !", "OK, see you tomorrow at seven p.m.!"),
      ],
    },
    vocab: ["今天", "明天", "昨天", "年", "月", "号", "日", "星期", "星期日", "星期天", "生日", "点", "分", "半", "现在", "时间", "早上", "上午", "中午", "下午", "晚上", "课", "见", "时候", "行", "差"],
    grammar: ["hsk1-g17", "hsk1-g18", "hsk1-g19"],
    culture: {
      title: t("Des nouilles pour l'anniversaire", "Noodles for your birthday"),
      body: t(
        "En Chine, le plat traditionnel d'anniversaire n'est pas le gâteau mais les **nouilles de longévité** (长寿面) : de très longues nouilles qu'on essaie de ne pas couper, pour une longue vie. On y ajoute souvent un œuf. Aujourd'hui, les jeunes font les deux : nouilles le midi, gâteau le soir !\n\nLes jours de la semaine sont simplement **numérotés** : 星期一 (jour 1 = lundi) jusqu'à 星期六 (samedi). Dimanche est à part : **星期天** ou **星期日** (« jour du soleil »). À l'oral, tu entendras aussi **周一, 周二…** (niveau 2).\n\nBeaucoup de Chinois fêtent aussi leur anniversaire selon le **calendrier lunaire**, dont la date change chaque année dans le calendrier occidental.",
        "In China, the traditional birthday dish isn't cake but **longevity noodles** (长寿面): very long noodles you try not to cut, for a long life. An egg is often added. Today young people do both: noodles at lunch, cake in the evening!\n\nWeekdays are simply **numbered**: 星期一 (day 1 = Monday) up to 星期六 (Saturday). Sunday is special: **星期天** or **星期日** (“sun day”). In speech you'll also hear **周一, 周二…** (level 2).\n\nMany Chinese people also celebrate their birthday by the **lunar calendar**, whose date shifts every year on the Western calendar.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment dit-on « 8 h 30 » ?", "How do you say “8:30”?"),
        options: ["半八点", "八点半", "八半点", "八点三十半"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « 2 h 00 » ?", "How do you say “2:00”?"),
        options: ["二点", "二时", "两个点", "两点"],
        answer: 3,
        explain: t("点 est un spécificatif : on dit 两点, pas 二点.", "点 acts as a measure word: 两点, not 二点."),
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « dimanche » ?", "How do you say “Sunday”?"),
        options: ["星期七", "星期天", "七星期", "星期零"],
        answer: 1,
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "今天几月几",
        after: "？",
        options: ["号", "点", "年", "岁"],
        answer: 0,
        tr: t("On est le combien aujourd'hui ?", "What's the date today?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "现在几",
        after: "？——现在三点。",
        options: ["号", "月", "点", "岁"],
        answer: 2,
        tr: t("Il est quelle heure ? — Il est 3 h.", "What time is it? — It's three o'clock."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "今天九月二十号，",
        after: "五。",
        options: ["月", "星期", "点", "号"],
        answer: 1,
        tr: t("Aujourd'hui, c'est vendredi 20 septembre.", "Today is Friday, September 20th."),
      },
      { type: "order", prompt: P.order, tokens: ["我", "明天晚上", "在家", "看电视"], tr: t("Demain soir, je regarde la télé à la maison.", "Tomorrow evening I'm watching TV at home.") },
      { type: "order", prompt: P.order, tokens: ["今天", "九月", "二十号", "星期五"], tr: t("Aujourd'hui, c'est vendredi 20 septembre.", "Today is Friday, September 20th.") },
      {
        type: "listen",
        zh: "现在差五分九点。",
        options: ["现在九点五分。", "现在差五分九点。", "现在五点九分。", "现在九点半。"],
        answer: 1,
        tr: t("Il est 9 h moins 5.", "It's five to nine."),
      },
      {
        type: "listen",
        zh: "我的生日是五月八号。",
        options: ["我的生日是五月八号。", "我的生日是八月五号。", "我的生日是五月十八号。", "他的生日是五月八号。"],
        answer: 0,
        tr: t("Mon anniversaire, c'est le 8 mai.", "My birthday is May 8th."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("今天", "jīntiān", "aujourd'hui", "today"),
          pair("明天", "míngtiān", "demain", "tomorrow"),
          pair("昨天", "zuótiān", "hier", "yesterday"),
          pair("上午", "shàngwǔ", "matin", "morning"),
          pair("晚上", "wǎnshang", "soir", "evening"),
          pair("星期", "xīngqī", "semaine", "week"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["我去北京明天。", "明天去我北京。", "我明天去北京。", "我去明天北京。"],
        answer: 2,
        explain: t("Le mot de temps se place avant le verbe (ou en tête de phrase), jamais à la fin.", "Time words go before the verb (or at the start), never at the end."),
      },
    ],
  },

  // ═══════════════════════════ L06 ═══════════════════════════
  {
    id: "hsk1-l06",
    level: 1,
    order: 6,
    title: t("Ma journée", "My day"),
    subtitle: t("La routine quotidienne et l'action en cours", "Daily routine and actions in progress"),
    theme: "home",
    goals: [
      t("Décrire ta journée type avec les heures", "Describe your typical day with times"),
      t("Enchaîner deux actions avec 先…再…", "Sequence two actions with 先…再…"),
      t("Dire à quelle fréquence tu fais quelque chose (每天, 常常, 有时候)", "Say how often you do things (每天, 常常, 有时候)"),
      t("Dire ce que tu es en train de faire avec 在 / 正在…呢", "Say what you're doing right now with 在 / 正在…呢"),
    ],
    dialogue: {
      context: t(
        "À la cantine, Marc et Wang Ming comparent leurs habitudes. Le soir, Marc frappe à la porte de Wang Ming.",
        "In the canteen, Marc and Wang Ming compare their routines. That evening, Marc knocks on Wang Ming's door.",
      ),
      lines: [
        line("王明", "马克，你每天几点起床？", "Mǎkè, nǐ měi tiān jǐ diǎn qǐchuáng?", "Marc, tu te lèves à quelle heure tous les jours ?", "Marc, what time do you get up every day?"),
        line("马克", "我每天七点起床。你呢？", "Wǒ měi tiān qī diǎn qǐchuáng. Nǐ ne?", "Tous les jours à 7 h. Et toi ?", "Seven every day. What about you?"),
        line("王明", "我六点半起床。我先看一会儿书，再吃早饭。", "Wǒ liù diǎn bàn qǐchuáng. Wǒ xiān kàn yíhuìr shū, zài chī zǎofàn.", "Moi, à 6 h 30. D'abord je lis un peu, puis je prends mon petit-déjeuner.", "At six thirty. First I read for a bit, then I have breakfast."),
        line("马克", "你常常去图书馆吗？", "Nǐ chángcháng qù túshūguǎn ma?", "Tu vas souvent à la bibliothèque ?", "Do you often go to the library?"),
        line("王明", "有时候去。晚上我常常在家学习。", "Yǒu shíhou qù. Wǎnshang wǒ chángcháng zài jiā xuéxí.", "Parfois. Le soir, j'étudie souvent chez moi.", "Sometimes. In the evening I often study at home."),
        line("马克", "王明，你在做什么呢？", "Wáng Míng, nǐ zài zuò shénme ne?", "Wang Ming, qu'est-ce que tu fais ?", "Wang Ming, what are you doing?"),
        line("王明", "我正在写汉字呢。", "Wǒ zhèngzài xiě Hànzì ne.", "Je suis en train d'écrire des caractères.", "I'm writing characters."),
        line("马克", "你每天都写汉字吗？", "Nǐ měi tiān dōu xiě Hànzì ma?", "Tu en écris tous les jours ?", "Do you write characters every day?"),
        line("王明", "对，每天写半个小时。", "Duì, měi tiān xiě bàn ge xiǎoshí.", "Oui, une demi-heure par jour.", "Yes, half an hour every day."),
        line("马克", "你太认真了！", "Nǐ tài rènzhēn le!", "Tu es vraiment sérieux !", "You're so diligent!"),
      ],
    },
    vocab: ["每", "起床", "睡觉", "睡", "洗", "早饭", "午饭", "晚饭", "吃饭", "上班", "下班", "回家", "休息", "常常", "常", "有时候", "有时", "先", "再", "在", "正在", "正", "马上", "图书馆", "小时", "一会儿", "认真", "看", "电视"],
    grammar: ["hsk1-g20", "hsk1-g21", "hsk1-g22"],
    culture: {
      title: t("« Tu as mangé ? » et la sieste de midi", "“Have you eaten?” and the midday nap"),
      body: t(
        "Une salutation très chinoise : **你吃了吗？** (« tu as mangé ? »). Ce n'est pas une invitation : c'est une façon amicale de dire bonjour, surtout autour des heures de repas. On répond simplement 吃了 ou 还没呢.\n\nLes horaires chinois sont **matinaux** : on déjeune souvent vers 11 h 30–12 h et on dîne vers 18 h. Beaucoup d'écoles et de bureaux ont une pause de midi avec **sieste** (午休) : il est courant de voir des employés dormir sur leur bureau après le déjeuner !\n\nDans les parcs, tôt le matin, tu verras des retraités faire du **taï-chi**, danser ou chanter ensemble.",
        "A very Chinese greeting: **你吃了吗？** (“have you eaten?”). It isn't an invitation: it's a friendly hello, especially around mealtimes. Just answer 吃了 or 还没呢.\n\nChinese schedules start **early**: lunch is often around 11:30–12:00 and dinner around 6 p.m. Many schools and offices have a midday break with a **nap** (午休): it's common to see office workers sleeping at their desks after lunch!\n\nIn parks early in the morning, you'll see retirees doing **tai chi**, dancing or singing together.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Traduis : « Je me lève à 7 h tous les jours. »", "Translate: “I get up at seven every day.”"),
        options: ["我每天七点起床。", "我起床每天七点。", "每天我起床七点。", "我七点每天起床。"],
        answer: 0,
        explain: t("Sujet + temps (du plus général au plus précis) + verbe.", "Subject + time (general to specific) + verb."),
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « chaque jour » ?", "How do you say “every day”?"),
        options: ["每个天", "每天", "天每", "每一个天"],
        answer: 1,
        explain: t("天 n'a pas besoin de spécificatif : 每天.", "天 takes no measure word: 每天."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "吃早饭，再去学校。",
        options: ["先", "再", "常", "在"],
        answer: 0,
        tr: t("D'abord je prends mon petit-déjeuner, ensuite je vais à l'école.", "First I have breakfast, then I go to school."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "他正在写汉字",
        after: "。",
        options: ["吗", "呢", "什么", "的"],
        answer: 1,
        tr: t("Il est en train d'écrire des caractères.", "He's writing characters."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你在做什么？——我",
        after: "看书呢。",
        options: ["是", "有", "在", "先"],
        answer: 2,
        tr: t("Qu'est-ce que tu fais ? — Je lis.", "What are you doing? — I'm reading."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我",
        after: "去图书馆，不是每天去。",
        options: ["每天", "都", "先", "有时候"],
        answer: 3,
        tr: t("Je vais parfois à la bibliothèque, pas tous les jours.", "I sometimes go to the library, not every day."),
      },
      { type: "order", prompt: P.order, tokens: ["我", "先", "洗手", "再", "吃饭"], tr: t("Je me lave les mains, puis je mange.", "I wash my hands, then I eat.") },
      { type: "order", prompt: P.order, tokens: ["他", "晚上", "常常", "在家", "学习"], tr: t("Le soir, il étudie souvent à la maison.", "He often studies at home in the evening.") },
      {
        type: "listen",
        zh: "妈妈在做饭呢。",
        options: ["妈妈在吃饭呢。", "妈妈在做饭呢。", "妈妈不做饭。", "爸爸在做饭呢。"],
        answer: 1,
        tr: t("Maman est en train de cuisiner.", "Mom is cooking."),
      },
      {
        type: "listen",
        zh: "我每天十一点睡觉。",
        options: ["我每天十一点睡觉。", "我每天十点睡觉。", "我每天十一点起床。", "我每天七点起床。"],
        answer: 0,
        tr: t("Je me couche à 23 h tous les jours.", "I go to bed at eleven every day."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("起床", "qǐchuáng", "se lever", "to get up"),
          pair("睡觉", "shuìjiào", "dormir, se coucher", "to sleep, go to bed"),
          pair("早饭", "zǎofàn", "petit-déjeuner", "breakfast"),
          pair("休息", "xiūxi", "se reposer", "to rest"),
          pair("上班", "shàngbān", "aller au travail", "to go to work"),
          pair("回家", "huí jiā", "rentrer à la maison", "to go home"),
        ],
      },
      {
        type: "choice",
        prompt: t("Traduis : « Je ne suis pas en train de regarder la télé. »", "Translate: “I'm not watching TV (right now).”"),
        options: ["我不在看电视。", "我没在看电视。", "我在没看电视。", "我没看电视在。"],
        answer: 1,
        explain: t("L'action en cours se nie avec 没 : 没在 + verbe.", "An ongoing action is negated with 没: 没在 + verb."),
      },
    ],
  },

  // ═══════════════════════════ L07 ═══════════════════════════
  {
    id: "hsk1-l07",
    level: 1,
    order: 7,
    title: t("Au restaurant", "At the restaurant"),
    subtitle: t("Commander à manger et à boire", "Ordering food and drinks"),
    theme: "food",
    goals: [
      t("Dire ce que tu veux avec 想 et 要", "Say what you want with 想 and 要"),
      t("Commander poliment : 我要一杯茶, 请给我…", "Order politely: 我要一杯茶, 请给我…"),
      t("Accueillir et inviter avec 请进, 请坐", "Welcome and invite with 请进, 请坐"),
      t("Faire une proposition avec 吧", "Make a suggestion with 吧"),
    ],
    dialogue: {
      context: t(
        "Marc et Wang Ming entrent dans un petit restaurant près de l'université. Le serveur les accueille.",
        "Marc and Wang Ming walk into a small restaurant near the university. The waiter greets them.",
      ),
      lines: [
        line("服务员", "你们好！请进，请坐。", "Nǐmen hǎo! Qǐng jìn, qǐng zuò.", "Bonjour ! Entrez, asseyez-vous.", "Hello! Come in, have a seat."),
        line("王明", "谢谢。马克，你想吃什么？", "Xièxie. Mǎkè, nǐ xiǎng chī shénme?", "Merci. Marc, qu'est-ce que tu as envie de manger ?", "Thanks. Marc, what would you like to eat?"),
        line("马克", "我想吃包子。你呢？", "Wǒ xiǎng chī bāozi. Nǐ ne?", "J'ai envie de baos. Et toi ?", "I feel like steamed buns. And you?"),
        line("王明", "我要吃面条儿。", "Wǒ yào chī miàntiáor.", "Moi, je prends des nouilles.", "I'll have noodles."),
        line("服务员", "你们喝什么？", "Nǐmen hē shénme?", "Et comme boisson ?", "What would you like to drink?"),
        line("马克", "请给我一杯茶。", "Qǐng gěi wǒ yì bēi chá.", "Un thé, s'il vous plaît.", "A tea, please."),
        line("王明", "我不想喝茶，我喝水吧。", "Wǒ bù xiǎng hē chá, wǒ hē shuǐ ba.", "Moi, je n'ai pas envie de thé… je vais prendre de l'eau.", "I don't feel like tea… I'll just have water."),
        line("服务员", "好，请等一下儿。", "Hǎo, qǐng děng yíxiàr.", "Très bien, un instant s'il vous plaît.", "Sure, just a moment, please."),
        line("马克", "这里的包子太好吃了！", "Zhèli de bāozi tài hǎochī le!", "Les baos d'ici sont délicieux !", "The buns here are delicious!"),
        line("王明", "我们下次再来吧！", "Wǒmen xià cì zài lái ba!", "On reviendra la prochaine fois !", "Let's come again next time!"),
      ],
    },
    vocab: ["吃", "喝", "饭", "米饭", "菜", "包子", "面条儿", "面包", "鸡蛋", "肉", "水果", "水", "茶", "牛奶", "杯", "杯子", "想", "要", "请", "请进", "请坐", "饭店", "好吃", "饿", "渴", "等", "吧", "一下儿", "下次"],
    grammar: ["hsk1-g23", "hsk1-g24", "hsk1-g25"],
    culture: {
      title: t("Les baguettes : quelques règles d'or", "Chopsticks: a few golden rules"),
      body: t(
        "• Ne **plante jamais** tes baguettes verticalement dans le riz : cela rappelle l'encens des funérailles.\n• Ne pointe personne avec tes baguettes, et ne tape pas sur ton bol (c'est ce que faisaient les mendiants).\n• Pour servir quelqu'un, certains utilisent des **baguettes communes** (公筷) : de plus en plus courant.\n\nAu restaurant, les plats sont **partagés** au centre de la table (souvent sur un plateau tournant). Tout le monde pioche dans tous les plats.\n\nEt l'addition ? En Chine, on ne partage pas souvent la note : une personne **invite** (请客), et les amis se « battent » parfois pour payer. La prochaine fois, ce sera ton tour !",
        "• **Never stick** your chopsticks upright in rice: it looks like funeral incense.\n• Don't point at people with your chopsticks, or tap your bowl (that's what beggars used to do).\n• To serve others, some people use **serving chopsticks** (公筷) — more and more common.\n\nIn restaurants, dishes are **shared** in the middle of the table (often on a lazy Susan). Everyone helps themselves from every dish.\n\nAnd the bill? In China people rarely split it: one person **treats** (请客), and friends sometimes “fight” over who pays. Next time, it's your turn!",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment commander un thé ?", "How do you order a tea?"),
        options: ["我是一杯茶。", "我要一杯茶。", "一杯我茶。", "我茶一杯要。"],
        answer: 1,
      },
      {
        type: "choice",
        prompt: t("Quelle est la façon la plus naturelle et polie de dire « Je n'ai pas envie d'y aller » ?", "What's the most natural, polite way to say “I don't feel like going”?"),
        options: ["我不要去。", "我不想去。", "我没想去。", "我想不去。"],
        answer: 1,
        explain: t("不想 est doux et naturel ; 不要去 sonne capricieux ou veut dire « n'y va pas ! ».", "不想 is soft and natural; 不要去 sounds bratty or means “don't go!”."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "请",
        after: "，请坐。",
        options: ["进", "吃", "喝", "要"],
        answer: 0,
        tr: t("Entrez, asseyez-vous.", "Come in, have a seat."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我们走",
        after: "！",
        options: ["吗", "的", "吧", "呢"],
        answer: 2,
        tr: t("Allons-y !", "Let's go!"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "我饿了，我想",
        after: "包子。",
        options: ["喝", "吃", "请", "是"],
        answer: 1,
        tr: t("J'ai faim, j'ai envie de manger des baos.", "I'm hungry, I feel like eating steamed buns."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "请",
        after: "，洗手间在哪儿？",
        options: ["进", "坐", "喝", "问"],
        answer: 3,
        tr: t("Excusez-moi, où sont les toilettes ?", "Excuse me, where's the restroom?"),
      },
      { type: "order", prompt: P.order, tokens: ["请", "给我", "一杯", "茶"], tr: t("Un thé, s'il vous plaît.", "A tea, please.") },
      { type: "order", prompt: P.order, tokens: ["你", "想", "吃", "什么"], tr: t("Qu'est-ce que tu as envie de manger ?", "What would you like to eat?") },
      {
        type: "listen",
        zh: "我不想喝茶，我喝水。",
        options: ["我想喝茶，不喝水。", "我不想喝水，我喝茶。", "我不想喝茶，我喝水。", "我不喝茶，我喝牛奶。"],
        answer: 2,
        tr: t("Je n'ai pas envie de thé, je prends de l'eau.", "I don't feel like tea, I'll have water."),
      },
      {
        type: "listen",
        zh: "这里的包子太好吃了！",
        options: ["这里的包子太好吃了！", "这里的面条儿太好吃了！", "这里的包子不好吃。", "那里的包子太好吃了！"],
        answer: 0,
        tr: t("Les baos d'ici sont délicieux !", "The buns here are delicious!"),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("米饭", "mǐfàn", "riz (cuit)", "(cooked) rice"),
          pair("面条儿", "miàntiáor", "nouilles", "noodles"),
          pair("鸡蛋", "jīdàn", "œuf", "egg"),
          pair("牛奶", "niúnǎi", "lait", "milk"),
          pair("水果", "shuǐguǒ", "fruit", "fruit"),
          pair("茶", "chá", "thé", "tea"),
        ],
      },
      {
        type: "choice",
        prompt: P.meaning,
        zh: "你是王明吧？",
        pinyin: "Nǐ shì Wáng Míng ba?",
        options: [
          t("Tu es Wang Ming, c'est ça ? (je le suppose)", "You're Wang Ming, right? (I assume so)"),
          t("Qui est Wang Ming ?", "Who is Wang Ming?"),
          t("Allons-y, Wang Ming !", "Let's go, Wang Ming!"),
          t("Où est Wang Ming ?", "Where is Wang Ming?"),
        ],
        answer: 0,
        explain: t("吧 dans une question = on suppose déjà la réponse.", "吧 in a question = you already assume the answer."),
      },
    ],
  },

  // ═══════════════════════════ L08 ═══════════════════════════
  {
    id: "hsk1-l08",
    level: 1,
    order: 8,
    title: t("Ça coûte combien ?", "How much is it?"),
    subtitle: t("Faire des achats, parler d'argent", "Shopping and talking about money"),
    theme: "shopping",
    goals: [
      t("Demander un prix avec 多少钱 et comprendre la réponse", "Ask a price with 多少钱 and understand the answer"),
      t("Dire un prix en 块 et 毛", "Say prices in 块 and 毛"),
      t("Désigner des objets avec 这个, 那个, 这些, 别的", "Point to things with 这个, 那个, 这些, 别的"),
      t("Poser une question « oui ou non » avec 贵不贵", "Ask an either-or question like 贵不贵"),
      t("Adoucir une demande : 看看, 试一下儿", "Soften a request: 看看, 试一下儿"),
    ],
    dialogue: {
      context: t(
        "Marc cherche un sac dans une petite boutique près du campus, puis achète des fruits.",
        "Marc is looking for a bag in a small shop near campus, then buys some fruit.",
      ),
      lines: [
        line("马克", "请问，这个多少钱？", "Qǐngwèn, zhège duōshao qián?", "Excusez-moi, combien coûte celui-ci ?", "Excuse me, how much is this one?"),
        line("店员", "这个包一百二十块。", "Zhège bāo yìbǎi èrshí kuài.", "Ce sac fait 120 yuans.", "This bag is 120 yuan."),
        line("马克", "太贵了！那个呢？", "Tài guì le! Nàge ne?", "C'est trop cher ! Et celui-là ?", "That's too expensive! What about that one?"),
        line("店员", "那个五十块。你看看，很好看。", "Nàge wǔshí kuài. Nǐ kànkan, hěn hǎokàn.", "Celui-là, 50 yuans. Regardez, il est très joli.", "That one's 50 yuan. Have a look, it's very nice."),
        line("马克", "我试一下儿。", "Wǒ shì yíxiàr.", "Je vais l'essayer.", "Let me try it."),
        line("店员", "大不大？", "Dà bu dà?", "Il est trop grand ?", "Is it too big?"),
        line("马克", "不大，很好。我要这个。", "Bú dà, hěn hǎo. Wǒ yào zhège.", "Non, il est parfait. Je prends celui-ci.", "No, it's great. I'll take this one."),
        line("店员", "你还要别的吗？", "Nǐ hái yào bié de ma?", "Vous désirez autre chose ?", "Anything else?"),
        line("马克", "这些水果多少钱？", "Zhèxiē shuǐguǒ duōshao qián?", "Combien coûtent ces fruits ?", "How much is this fruit?"),
        line("店员", "十五块五。", "Shíwǔ kuài wǔ.", "15,50 yuans.", "15.50 yuan."),
      ],
    },
    vocab: ["买", "钱", "钱包", "块", "元", "毛", "分", "贵", "东西", "商店", "商场", "包", "书包", "衣服", "试", "好看", "大", "小", "这些", "那些", "那", "别的", "有的", "还", "请问", "新", "多", "少"],
    grammar: ["hsk1-g26", "hsk1-g27", "hsk1-g28", "hsk1-g29"],
    culture: {
      title: t("Payer avec son téléphone… et marchander", "Paying by phone… and bargaining"),
      body: t(
        "En Chine, presque tout se paie avec le **téléphone** : on scanne un **QR code** (扫码) avec WeChat Pay ou Alipay, même chez le vendeur de rue. Les touristes peuvent aujourd'hui relier une carte étrangère à ces applications. Les espèces restent acceptées, mais les commerçants rendent parfois difficilement la monnaie !\n\nDans les **marchés** et les petites boutiques pour touristes, on peut **marchander** : 便宜一点儿吧！ (« un peu moins cher, s'il vous plaît ! » — niveau 2). Dans les supermarchés et centres commerciaux (商场), les prix sont fixes.\n\nÀ l'écrit, le prix s'affiche en **元** (¥) ; à l'oral, tout le monde dit **块**.",
        "In China almost everything is paid by **phone**: you scan a **QR code** (扫码) with WeChat Pay or Alipay, even at street stalls. Tourists can now link a foreign card to these apps. Cash is still accepted, but vendors sometimes struggle to give change!\n\nAt **markets** and small tourist shops, you can **bargain**: 便宜一点儿吧！ (“a bit cheaper, please!” — level 2). In supermarkets and malls (商场), prices are fixed.\n\nIn writing, prices are shown in **元** (¥); in speech everyone says **块**.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Comment dit-on « 9,30 yuans » à l'oral ?", "How do you say “¥9.30” in speech?"),
        options: ["九块三", "三块九", "九毛三", "九块零三"],
        answer: 0,
        explain: t("块 puis 毛, et on omet souvent le dernier 毛 : 九块三.", "块 then 毛, and the final 毛 is often dropped: 九块三."),
      },
      {
        type: "choice",
        prompt: t("Comment dit-on « 105 yuans » ?", "How do you say “¥105”?"),
        options: ["一百五", "一百零五块", "一百五十块", "十五块"],
        answer: 1,
        explain: t("Le 零 marque l'absence de dizaines. 一百五 = 150.", "零 marks the missing tens. 一百五 = 150."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这个",
        after: "钱？",
        options: ["多少", "几", "什么", "谁"],
        answer: 0,
        tr: t("Combien ça coûte ?", "How much is this?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这个包贵",
        after: "贵？",
        options: ["很", "没", "不", "吗"],
        answer: 2,
        tr: t("Ce sac est cher ?", "Is this bag expensive?"),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "这个包很好看，你试",
        after: "吧。",
        options: ["是", "看", "买", "试"],
        answer: 3,
        tr: t("Ce sac est très joli, essaie-le.", "This bag is really nice, try it on."),
        explain: t("试试 = essayer un peu (verbe redoublé).", "试试 = give it a try (reduplicated verb)."),
      },
      {
        type: "fill",
        prompt: P.fill,
        before: "你还要",
        after: "东西吗？",
        options: ["别的", "哪", "什么", "谁"],
        answer: 0,
        tr: t("Vous désirez autre chose ?", "Would you like anything else?"),
      },
      { type: "order", prompt: P.order, tokens: ["这个", "包", "多少", "钱"], tr: t("Combien coûte ce sac ?", "How much is this bag?") },
      { type: "order", prompt: P.order, tokens: ["那些", "东西", "都", "很贵"], tr: t("Ces choses-là sont toutes chères.", "Those things are all expensive.") },
      {
        type: "listen",
        zh: "这个包一百二十块。",
        options: ["这个包一百零二块。", "这个包二十块。", "这个包一百二十块。", "那个包一百二十块。"],
        answer: 2,
        tr: t("Ce sac coûte 120 yuans.", "This bag is 120 yuan."),
      },
      {
        type: "listen",
        zh: "请等一下儿。",
        options: ["请坐一下儿。", "请等一下儿。", "请看一下儿。", "请试一下儿。"],
        answer: 1,
        tr: t("Attendez un instant, s'il vous plaît.", "Please wait a moment."),
      },
      {
        type: "match",
        prompt: P.match,
        pairs: [
          pair("钱", "qián", "argent", "money"),
          pair("块", "kuài", "yuan (à l'oral)", "yuan (spoken)"),
          pair("贵", "guì", "cher", "expensive"),
          pair("买", "mǎi", "acheter", "to buy"),
          pair("衣服", "yīfu", "vêtements", "clothes"),
          pair("商店", "shāngdiàn", "magasin", "shop"),
        ],
      },
      {
        type: "choice",
        prompt: t("Quelle question est correcte ?", "Which question is correct?"),
        options: ["你去不去吗？", "你去不去？", "你不去去？", "你很去不去？"],
        answer: 1,
        explain: t("V 不 V est déjà une question : pas de 吗.", "V 不 V is already a question: no 吗."),
      },
    ],
  },
];
