import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsB: Lesson[] = [
  // ───────────────────────── L04 · Arts ─────────────────────────
  {
    id: "hsk6-l04",
    level: 6,
    order: 4,
    title: t("Les crevettes de Qi Baishi", "Qi Baishi's shrimps"),
    subtitle: t("Arts : visiter une exposition de peinture chinoise", "Arts: visiting a Chinese painting exhibition"),
    theme: "culture",
    goals: [
      t("Formuler une appréciation forte avec 可谓 et 非…莫属", "Give strong praise with 可谓 and 非…莫属"),
      t("Dire « célèbre pour » avec 以…而闻名", "Say \"famous for\" with 以…而闻名"),
      t("Lire les adverbes classiques 皆、均、亦", "Read the classical adverbs 皆、均、亦"),
      t("Reconnaître les moules de quatre caractères (不知不觉、因人而异…)", "Recognise four-character moulds (不知不觉、因人而异…)"),
    ],
    dialogue: {
      context: t(
        "Sophie, une étudiante française en histoire de l'art, visite une exposition consacrée à Qi Baishi à Pékin. Une commissaire d'exposition lui sert de guide.",
        "Sophie, a French art-history student, visits a Qi Baishi exhibition in Beijing. A curator shows her around.",
      ),
      lines: [
        ln("苏菲", "这次齐白石画展的人真多啊，可谓人山人海。", "Zhè cì Qí Báishí huàzhǎn de rén zhēn duō a, kěwèi rén shān rén hǎi.", "Il y a un monde fou à cette exposition Qi Baishi, c'est une véritable marée humaine.", "So many people at this Qi Baishi exhibition — a real sea of people."),
        ln("策展人", "是啊。要说中国近代最受欢迎的画家，非齐白石莫属。", "Shì a. Yào shuō Zhōngguó jìndài zuì shòu huānyíng de huàjiā, fēi Qí Báishí mòshǔ.", "Eh oui. S'il faut nommer le peintre chinois moderne le plus populaire, c'est Qi Baishi, sans conteste.", "Yes. If you had to name modern China's most popular painter, it could only be Qi Baishi."),
        ln("策展人", "这次展出的一百多件作品均来自北京画院，很多是第一次与观众见面。", "Zhè cì zhǎnchū de yìbǎi duō jiàn zuòpǐn jūn láizì Běijīng Huàyuàn, hěn duō shì dì-yī cì yǔ guānzhòng jiànmiàn.", "Les quelque cent œuvres exposées proviennent toutes de l'Académie de peinture de Pékin, et beaucoup sont montrées au public pour la première fois.", "The hundred-plus works on show all come from the Beijing Fine Art Academy, and many are being shown to the public for the first time."),
        ln("苏菲", "他以画什么而闻名？", "Tā yǐ huà shénme ér wénmíng?", "Il est célèbre pour quoi ?", "What is he famous for painting?"),
        ln("策展人", "他以画虾而闻名。你看这幅，只用了几笔，虾就像活的一样。", "Tā yǐ huà xiā ér wénmíng. Nǐ kàn zhè fú, zhǐ yòng le jǐ bǐ, xiā jiù xiàng huó de yíyàng.", "Pour ses crevettes. Regarde celle-ci : quelques coups de pinceau à peine, et les crevettes ont l'air vivantes.", "For his shrimps. Look at this one — just a few brushstrokes, and the shrimps seem alive."),
        ln("苏菲", "真是栩栩如生！", "Zhēn shì xǔxǔ rú shēng!", "On dirait vraiment qu'elles bougent !", "Truly lifelike!"),
        ln("策展人", "齐白石出身农民，当过木匠，五十多岁才真正成名，可谓大器晚成。", "Qí Báishí chūshēn nóngmín, dāng guo mùjiang, wǔshí duō suì cái zhēnzhèng chéngmíng, kěwèi dà qì wǎn chéng.", "Qi Baishi était fils de paysans, il a été menuisier et n'est vraiment devenu célèbre qu'après cinquante ans : un talent tardif, on peut le dire.", "Qi Baishi came from a peasant family, worked as a carpenter and only became truly famous in his fifties — a late bloomer if ever there was one."),
        ln("苏菲", "我发现中国画和西方油画很不一样，好像不太讲究透视。", "Wǒ fāxiàn Zhōngguó huà hé xīfāng yóuhuà hěn bù yíyàng, hǎoxiàng bú tài jiǎngjiu tòushì.", "Je remarque que la peinture chinoise est très différente de la peinture à l'huile occidentale : elle ne semble pas très attachée à la perspective.", "I notice Chinese painting is very different from Western oil painting — it doesn't seem to care much about perspective."),
        ln("策展人", "对。齐白石说，作画妙在“似与不似之间”，追求的不是形似，而是神似。", "Duì. Qí Báishí shuō, zuò huà miào zài “sì yǔ bú sì zhījiān”, zhuīqiú de bú shì xíngsì, ér shì shénsì.", "Exact. Qi Baishi disait que l'art de peindre réside « entre la ressemblance et la non-ressemblance » : on ne cherche pas la ressemblance de la forme, mais celle de l'esprit.", "Right. Qi Baishi said the magic of painting lies \"between likeness and unlikeness\": what matters isn't resemblance of form but of spirit."),
        ln("苏菲", "画上的字和印章也是作品的一部分吗？", "Huà shang de zì hé yìnzhāng yě shì zuòpǐn de yí bùfen ma?", "Les inscriptions et les sceaux sur le tableau font aussi partie de l'œuvre ?", "Are the inscriptions and seals on the painting part of the work too?"),
        ln("策展人", "当然。诗、书、画、印，皆是中国文人艺术的重要元素，缺一不可。", "Dāngrán. Shī, shū, huà, yìn, jiē shì Zhōngguó wénrén yìshù de zhòngyào yuánsù, quē yī bù kě.", "Bien sûr. Poésie, calligraphie, peinture et sceau sont tous des éléments essentiels de l'art des lettrés chinois : aucun ne peut manquer.", "Of course. Poetry, calligraphy, painting and seal are all essential elements of Chinese literati art — none can be left out."),
        ln("策展人", "不过，艺术的感受因人而异，你不必看懂每一个细节。", "Búguò, yìshù de gǎnshòu yīn rén ér yì, nǐ búbì kàn dǒng měi yí ge xìjié.", "Cela dit, le ressenti face à l'art varie selon chacun ; tu n'as pas besoin de comprendre chaque détail.", "That said, how one feels about art varies from person to person; you don't need to understand every detail."),
        ln("苏菲", "我明白了。站在这些画前，我不知不觉就看了一个下午。", "Wǒ míngbai le. Zhàn zài zhèxiē huà qián, wǒ bù zhī bù jué jiù kàn le yí ge xiàwǔ.", "Je comprends. Devant ces tableaux, j'ai passé tout un après-midi sans m'en rendre compte.", "I see. Standing before these paintings, I spent a whole afternoon without realising it."),
        ln("策展人", "这正是好作品的魅力：让人流连忘返，百看不厌。", "Zhè zhèng shì hǎo zuòpǐn de mèilì: ràng rén liú lián wàng fǎn, bǎi kàn bú yàn.", "C'est tout le charme des grandes œuvres : on ne veut plus repartir, on ne s'en lasse jamais.", "That's the charm of great works: you never want to leave, and you never tire of them."),
      ],
    },
    vocab: ["画展", "可谓", "人山人海", "近代", "画家", "均", "展出", "观众", "闻名", "虾", "幅", "栩栩如生", "出身", "木匠", "成名", "大器晚成", "油画", "讲究", "透视", "追求", "作品", "印章", "皆", "元素", "缺一不可", "因人而异", "细节", "不知不觉", "魅力", "流连忘返", "百看不厌", "感受", "艺术", "莫属"],
    grammar: ["hsk6-g09", "hsk6-g14", "hsk6-g16", "hsk6-g18", "hsk6-g32"],
    culture: {
      title: t("Qi Baishi et l'art des lettrés", "Qi Baishi and literati art"),
      body: t(
        "**齐白石** (1864-1957), né dans une famille pauvre du Hunan, est d'abord menuisier-sculpteur avant de devenir l'un des peintres les plus aimés de Chine. Ses **crevettes**, crabes, poussins et légumes, peints en quelques traits d'encre, allient simplicité paysanne et raffinement lettré. En 2011, l'une de ses œuvres a été adjugée plus de **400 millions de yuans**.\n\nLa peinture des **文人** (lettrés) associe quatre arts : **诗** (poésie), **书** (calligraphie), **画** (peinture), **印** (sceau gravé). Elle vise le **神似** (« ressemblance de l'esprit ») plutôt que le **形似** (« ressemblance de la forme ») : saisir l'essence vivante d'un sujet plutôt que le reproduire fidèlement.",
        "**Qi Baishi** (1864–1957), born into a poor Hunan family, was a carpenter-carver before becoming one of China's best-loved painters. His **shrimps**, crabs, chicks and vegetables, done in a few ink strokes, blend peasant simplicity with literati refinement. In 2011, one of his works sold for over **400 million yuan**.\n\n**Literati** (文人) painting combines four arts: **诗** (poetry), **书** (calligraphy), **画** (painting), **印** (carved seal). It aims for **神似** (\"likeness of spirit\") rather than **形似** (\"likeness of form\") — capturing a subject's living essence rather than copying it faithfully.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète l'appréciation.", "Complete the praise."),
        before: "要说中国近代最受欢迎的画家，非齐白石",
        after: "。",
        options: ["莫属", "不可", "而已", "罢了"],
        answer: 0,
        tr: t("Le peintre chinois moderne le plus populaire, c'est Qi Baishi, sans conteste.", "Modern China's most popular painter can only be Qi Baishi."),
        explain: t("非…莫属 = « revient de droit à ». 非…不可 = « il faut absolument ».", "非…莫属 = \"belongs by right to\". 非…不可 = \"absolutely must\"."),
      },
      {
        type: "fill",
        prompt: t("Complète la structure.", "Complete the structure."),
        before: "景德镇以瓷器",
        after: "闻名世界。",
        options: ["而", "为", "所", "则"],
        answer: 0,
        tr: t("Jingdezhen est célèbre dans le monde entier pour sa porcelaine.", "Jingdezhen is world-famous for its porcelain."),
        explain: t("以 + N + 而 + 闻名 : ici 而 relie le moyen au verbe.", "以 + N + 而 + 闻名: here 而 links the means to the verb."),
      },
      {
        type: "choice",
        prompt: t("Dans 诗、书、画、印，皆是…, que signifie 皆 ?", "In 诗、书、画、印，皆是…, what does 皆 mean?"),
        options: ["都", "也", "才", "就"],
        answer: 0,
        explain: t("皆 = 都 (écrit). 亦 = 也.", "皆 = 都 (written). 亦 = 也."),
      },
      {
        type: "choice",
        prompt: t("Quel 四字格 est correct ?", "Which 四字格 is correct?"),
        options: ["不知不觉", "半知不觉", "有知有觉地", "不知半觉"],
        answer: 0,
        explain: t("Moule 不A不B : 不知不觉 = sans s'en rendre compte.", "不A不B mould: 不知不觉 = without realising."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le 成语 qui convient.", "Fill in the fitting 成语."),
        before: "他五十多岁才成名，可谓",
        after: "。",
        options: ["大器晚成", "人山人海", "缺一不可", "因人而异"],
        answer: 0,
        tr: t("Il n'est devenu célèbre qu'après cinquante ans : un talent tardif, on peut le dire.", "He only became famous in his fifties — a late bloomer indeed."),
        explain: t("大器晚成 = « les grands vases sont longs à achever » : réussite tardive.", "大器晚成 = \"great vessels take long to complete\": late success."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "艺术的感受",
        after: "，你不必看懂每一个细节。",
        options: ["因人而异", "以人为本", "人山人海", "百看不厌"],
        answer: 0,
        tr: t("Le ressenti face à l'art varie selon chacun ; tu n'as pas besoin de tout comprendre.", "How one feels about art varies by person; you needn't grasp every detail."),
        explain: t("因 + N + 而 + V : 因人而异 = varier selon les personnes.", "因 + N + 而 + V: 因人而异 = vary from person to person."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["展出的作品", "均", "来自", "北京画院"],
        tr: t("Les œuvres exposées proviennent toutes de l'Académie de peinture de Pékin.", "The works on show all come from the Beijing Fine Art Academy."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["中国画", "追求的", "不是形似", "而是", "神似"],
        tr: t("La peinture chinoise ne cherche pas la ressemblance de la forme, mais celle de l'esprit.", "Chinese painting seeks likeness of spirit, not of form."),
      },
      {
        type: "listen",
        zh: "他以画虾而闻名。",
        options: ["他以画虾而闻名。", "他以画马而闻名。", "他因画虾而出名了吗？", "他以画鱼而闻名。"],
        answer: 0,
        tr: t("Il est célèbre pour ses crevettes.", "He's famous for painting shrimps."),
      },
      {
        type: "listen",
        zh: "这正是好作品的魅力：让人流连忘返，百看不厌。",
        options: ["这正是好作品的魅力：让人流连忘返，百看不厌。", "这正是好作品的问题：让人看一次就厌了。", "这正是好作家的魅力：让人流连忘返。", "这不是好作品的魅力，让人百看就厌。"],
        answer: 0,
        tr: t("C'est tout le charme des grandes œuvres : on ne veut plus repartir, on ne s'en lasse jamais.", "That's the charm of great works: you never want to leave and never tire of them."),
      },
      {
        type: "match",
        prompt: t("Associe chaque expression à son sens.", "Match each expression to its meaning."),
        pairs: [
          { zh: "栩栩如生", pinyin: "xǔxǔ rú shēng", tr: t("plus vrai que nature", "lifelike") },
          { zh: "人山人海", pinyin: "rén shān rén hǎi", tr: t("une marée humaine", "a sea of people") },
          { zh: "缺一不可", pinyin: "quē yī bù kě", tr: t("aucun ne peut manquer", "none can be missing") },
          { zh: "流连忘返", pinyin: "liú lián wàng fǎn", tr: t("ne plus vouloir repartir", "linger and forget to leave") },
          { zh: "百看不厌", pinyin: "bǎi kàn bú yàn", tr: t("dont on ne se lasse jamais", "never tire of seeing") },
        ],
      },
    ],
  },

  // ───────────────────────── L05 · Urbanisation ─────────────────────────
  {
    id: "hsk6-l05",
    level: 6,
    order: 5,
    title: t("Des villages aux mégalopoles", "From villages to megacities"),
    subtitle: t("Urbanisation : logement, hukou et mémoire des lieux", "Urbanisation: housing, hukou and the memory of places"),
    theme: "city",
    goals: [
      t("Raisonner a fortiori avec 尚且…何况…", "Reason a fortiori with 尚且…何况…"),
      t("Opposer deux situations avec 则", "Contrast two situations with 则"),
      t("Exprimer une concession extrême avec 即便 et 纵然", "Express extreme concession with 即便 and 纵然"),
      t("Décrire un changement mesuré avec 有所 et regrouper avec 连同/及其", "Describe a moderate change with 有所 and group items with 连同/及其"),
    ],
    dialogue: {
      context: t(
        "Dans une émission de radio, un présentateur interroge le professeur Zhao, urbaniste, sur quarante ans d'urbanisation en Chine.",
        "On a radio show, a host interviews Professor Zhao, an urban planner, about forty years of urbanisation in China.",
      ),
      lines: [
        ln("主持人", "赵教授，与四十年前相比，中国的城市发生了翻天覆地的变化。", "Zhào jiàoshòu, yǔ sìshí nián qián xiāngbǐ, Zhōngguó de chéngshì fāshēng le fān tiān fù dì de biànhuà.", "Professeur Zhao, par rapport à il y a quarante ans, les villes chinoises ont été complètement bouleversées.", "Professor Zhao, compared with forty years ago, Chinese cities have been utterly transformed."),
        ln("赵教授", "是的。当时城市人口还不到百分之二十五，现在则已经超过了百分之六十五。", "Shì de. Dāngshí chéngshì rénkǒu hái bú dào bǎi fēn zhī èrshíwǔ, xiànzài zé yǐjīng chāoguò le bǎi fēn zhī liùshíwǔ.", "Oui. À l'époque, la population urbaine ne dépassait pas 25 %, alors qu'aujourd'hui elle dépasse 65 %.", "Yes. Back then the urban population was under 25%; now it's over 65%."),
        ln("主持人", "大量农村人口进城，给城市带来了哪些挑战？", "Dàliàng nóngcūn rénkǒu jìn chéng, gěi chéngshì dài lái le nǎxiē tiǎozhàn?", "Quels défis l'arrivée massive de ruraux a-t-elle posés aux villes ?", "What challenges has the mass influx of rural people brought to cities?"),
        ln("赵教授", "首先是住房。大城市的白领尚且买不起房，何况刚进城的农民工呢？", "Shǒuxiān shì zhùfáng. Dà chéngshì de báilǐng shàngqiě mǎi bu qǐ fáng, hékuàng gāng jìn chéng de nóngmíngōng ne?", "D'abord le logement. Si même les cadres des grandes villes ne peuvent pas acheter, que dire des travailleurs migrants qui viennent d'arriver ?", "First, housing. If even big-city white-collar workers can't afford a home, how could newly arrived migrant workers?"),
        ln("赵教授", "即便租房，很多人也只能住在离市中心很远的地方，每天通勤两三个小时。", "Jíbiàn zū fáng, hěn duō rén yě zhǐ néng zhù zài lí shì zhōngxīn hěn yuǎn de dìfang, měi tiān tōngqín liǎng sān ge xiǎoshí.", "Même en location, beaucoup ne peuvent vivre que très loin du centre et passent deux à trois heures par jour dans les transports.", "Even renting, many can only live far from the centre and commute two or three hours a day."),
        ln("主持人", "还有孩子上学的问题吧？", "Hái yǒu háizi shàngxué de wèntí ba?", "Il y a aussi la question de la scolarisation des enfants, non ?", "And there's the question of children's schooling, isn't there?"),
        ln("赵教授", "对。过去户口制度限制了农民工及其子女享受城市的公共服务。", "Duì. Guòqù hùkǒu zhìdù xiànzhì le nóngmíngōng jí qí zǐnǚ xiǎngshòu chéngshì de gōnggòng fúwù.", "Oui. Autrefois, le système du hukou empêchait les travailleurs migrants et leurs enfants de profiter des services publics urbains.", "Yes. In the past, the hukou system barred migrant workers and their children from urban public services."),
        ln("赵教授", "近些年，政策有所调整，不少城市放宽了落户条件。", "Jìn xiē nián, zhèngcè yǒusuǒ tiáozhěng, bù shǎo chéngshì fàngkuān le luòhù tiáojiàn.", "Ces dernières années, la politique s'est quelque peu assouplie, et de nombreuses villes ont allégé les conditions d'obtention du hukou.", "In recent years, policy has been adjusted somewhat, and many cities have relaxed residency requirements."),
        ln("主持人", "城市不断扩张，老城区的命运又怎么样呢？", "Chéngshì búduàn kuòzhāng, lǎo chéngqū de mìngyùn yòu zěnmeyàng ne?", "Les villes ne cessent de s'étendre : quel sort pour les vieux quartiers ?", "As cities keep expanding, what has become of the old districts?"),
        ln("赵教授", "很多胡同连同几百年的老建筑一起被拆掉了，这是很大的遗憾。", "Hěn duō hútòng liántóng jǐ bǎi nián de lǎo jiànzhù yìqǐ bèi chāi diào le, zhè shì hěn dà de yíhàn.", "Beaucoup de hutongs ont été rasés, avec des bâtiments vieux de plusieurs siècles. C'est très regrettable.", "Many hutongs were demolished along with centuries-old buildings — a great pity."),
        ln("赵教授", "纵然新楼再漂亮，也代替不了老街坊之间的人情味。", "Zòngrán xīn lóu zài piàoliang, yě dàitì bu liǎo lǎo jiēfang zhījiān de rénqíngwèi.", "Quand bien même les nouveaux immeubles seraient superbes, ils ne remplaceront jamais la chaleur humaine entre vieux voisins.", "However beautiful the new buildings, they can never replace the warmth between old neighbours."),
        ln("主持人", "那您理想中的城市是什么样的？", "Nà nín lǐxiǎng zhōng de chéngshì shì shénme yàng de?", "Alors, à quoi ressemble votre ville idéale ?", "So what does your ideal city look like?"),
        ln("赵教授", "城市发展的目的是让人生活得更好，而不是一味追求规模。以人为本，才是城市化的方向。", "Chéngshì fāzhǎn de mùdì shì ràng rén shēnghuó de gèng hǎo, ér bú shì yíwèi zhuīqiú guīmó. Yǐ rén wéi běn, cái shì chéngshìhuà de fāngxiàng.", "Le but du développement urbain est d'améliorer la vie des gens, pas de courir aveuglément après la taille. Mettre l'humain au centre, voilà la bonne direction.", "The purpose of urban development is better lives, not blindly chasing scale. Putting people first is the right direction for urbanisation."),
      ],
    },
    vocab: ["翻天覆地", "人口", "则", "超过", "农村", "挑战", "住房", "白领", "尚且", "农民工", "即便", "租", "通勤", "户口", "制度", "限制", "及其", "子女", "享受", "公共", "服务", "有所", "调整", "政策", "放宽", "扩张", "命运", "胡同", "连同", "建筑", "拆", "遗憾", "纵然", "代替", "人情味", "理想", "一味", "规模", "以人为本", "方向"],
    grammar: ["hsk6-g02", "hsk6-g03", "hsk6-g17", "hsk6-g24", "hsk6-g29"],
    culture: {
      title: t("Le hukou, les hutongs et Shenzhen", "Hukou, hutongs and Shenzhen"),
      body: t(
        "Le **户口** (livret d'enregistrement du foyer), créé en 1958, rattache chaque citoyen à un lieu, urbain ou rural. Des centaines de millions de **农民工** (travailleurs migrants) vivent ainsi en ville sans y avoir de hukou, avec un accès limité à l'école ou à l'assurance maladie. Les réformes récentes l'assouplissent, surtout dans les villes moyennes.\n\nÀ Pékin, les **胡同** (ruelles) et leurs **四合院** (maisons à cour carrée) ont été massivement détruits depuis les années 1990, avant que des politiques de protection ne se mettent en place. À l'inverse, **Shenzhen** était un bourg d'environ 30 000 habitants en 1979 : c'est aujourd'hui une métropole de plus de 17 millions d'habitants.",
        "The **户口** (household registration), created in 1958, ties each citizen to a place, urban or rural. Hundreds of millions of **农民工** (migrant workers) live in cities without local hukou, with limited access to schools or health insurance. Recent reforms have eased it, especially in mid-sized cities.\n\nIn Beijing, **胡同** (alleys) and their **四合院** (courtyard houses) were torn down on a massive scale from the 1990s before protection policies took hold. Conversely, **Shenzhen** was a town of about 30,000 people in 1979; today it's a metropolis of over 17 million.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète le raisonnement a fortiori.", "Complete the a fortiori argument."),
        before: "大城市的白领",
        after: "买不起房，何况刚进城的农民工呢？",
        options: ["尚且", "尚未", "况且", "而且"],
        answer: 0,
        tr: t("Si même les cadres des grandes villes ne peuvent pas acheter, que dire des travailleurs migrants ?", "If even city white-collar workers can't afford homes, how could migrant workers?"),
        explain: t("尚且 (cas facile) … 何况 (cas plus difficile). 尚未 = « pas encore ».", "尚且 (easy case)… 何况 (harder case). 尚未 = \"not yet\"."),
      },
      {
        type: "fill",
        prompt: t("Complète le contraste.", "Complete the contrast."),
        before: "当时城市人口不到百分之二十五，现在",
        after: "已经超过了百分之六十五。",
        options: ["则", "却是", "而且", "才"],
        answer: 0,
        tr: t("À l'époque, la population urbaine était inférieure à 25 % ; aujourd'hui, elle dépasse 65 %.", "Back then the urban share was under 25%; now it's over 65%."),
        explain: t("则 après le second sujet (现在) marque le contraste.", "则 after the second subject (现在) marks the contrast."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase utilise 有所 correctement ?", "Which sentence uses 有所 correctly?"),
        options: ["政策有所调整。", "政策有所调。", "政策有所调整了百分之十。", "政策有所很大调整。"],
        answer: 0,
        explain: t("有所 + verbe bisyllabique, sans quantité précise.", "有所 + disyllabic verb, with no exact amount."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon connecteur.", "Fill in the right connector."),
        before: "这项政策适用于农民工",
        after: "子女。",
        options: ["及其", "连同", "以及他", "和其"],
        answer: 0,
        tr: t("Cette politique s'applique aux travailleurs migrants et à leurs enfants.", "This policy applies to migrant workers and their children."),
        explain: t("及其 = « et leur(s) » (écrit), évite de répéter le nom.", "及其 = \"and their\" (written), avoids repeating the noun."),
      },
      {
        type: "fill",
        prompt: t("Complète la concession.", "Complete the concession."),
        before: "",
        after: "新楼再漂亮，也代替不了老街坊之间的人情味。",
        options: ["纵然", "既然", "虽然是", "因为"],
        answer: 0,
        tr: t("Quand bien même les nouveaux immeubles seraient superbes, ils ne remplaceront pas la chaleur des vieux voisins.", "However beautiful new buildings are, they can't replace the warmth of old neighbours."),
        explain: t("纵然 + hypothèse extrême + 也 = « quand bien même ».", "纵然 + extreme hypothesis + 也 = \"even if\"."),
      },
      {
        type: "choice",
        prompt: t("Selon le professeur Zhao, quelle doit être la priorité de l'urbanisation ?", "According to Professor Zhao, what should urbanisation prioritise?"),
        options: [
          t("Le bien-être des habitants", "People's well-being"),
          t("La taille des villes", "City size"),
          t("La construction de nouveaux immeubles", "New buildings"),
          t("La suppression du hukou", "Abolishing hukou"),
        ],
        answer: 0,
        explain: t("以人为本 = « mettre l'humain au centre ».", "以人为本 = \"put people first\"."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["很多胡同", "连同", "老建筑", "一起", "被拆掉了"],
        tr: t("Beaucoup de hutongs ont été rasés avec les vieux bâtiments.", "Many hutongs were torn down along with old buildings."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["即便", "租房", "很多人", "也只能", "住得很远"],
        tr: t("Même en location, beaucoup ne peuvent habiter que loin.", "Even renting, many can only live far away."),
      },
      {
        type: "listen",
        zh: "不少城市放宽了落户条件。",
        options: ["不少城市放宽了落户条件。", "不少城市提高了落户条件。", "不少城市取消了户口制度。", "很少城市放宽了落户条件。"],
        answer: 0,
        tr: t("De nombreuses villes ont assoupli les conditions d'obtention du hukou.", "Many cities have relaxed residency requirements."),
      },
      {
        type: "listen",
        zh: "以人为本，才是城市化的方向。",
        options: ["以人为本，才是城市化的方向。", "以城为本，才是现代化的方向。", "以人为主，就是城市化的目的。", "以钱为本，才是城市化的方向。"],
        answer: 0,
        tr: t("Mettre l'humain au centre, voilà la direction de l'urbanisation.", "Putting people first is the direction for urbanisation."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "户口", pinyin: "hùkǒu", tr: t("enregistrement de résidence (hukou)", "household registration") },
          { zh: "通勤", pinyin: "tōngqín", tr: t("faire la navette domicile-travail", "to commute") },
          { zh: "扩张", pinyin: "kuòzhāng", tr: t("expansion, s'étendre", "to expand") },
          { zh: "人情味", pinyin: "rénqíngwèi", tr: t("chaleur humaine", "human warmth") },
          { zh: "规模", pinyin: "guīmó", tr: t("échelle, taille", "scale") },
        ],
      },
    ],
  },

  // ───────────────────────── L06 · Technologie & IA ─────────────────────────
  {
    id: "hsk6-l06",
    level: 6,
    order: 6,
    title: t("L'IA peut-elle penser ?", "Can AI think?"),
    subtitle: t("Technologie : intelligence artificielle, emploi et éthique", "Technology: artificial intelligence, jobs and ethics"),
    theme: "tech",
    goals: [
      t("Analyser avec 在于 et 取决于", "Analyse with 在于 and 取决于"),
      t("Concéder puis argumenter avec 诚然 et 虽说", "Concede then argue with 诚然 and 虽说"),
      t("Exprimer un but avec 以便 et une réaction immédiate avec 一经…便…", "Express purpose with 以便 and an immediate reaction with 一经…便…"),
      t("Poser des questions de fond avec 何以 et 何在", "Ask deep questions with 何以 and 何在"),
    ],
    dialogue: {
      context: t(
        "Dans un podcast tech, une animatrice discute avec le Dr Li, chercheur en intelligence artificielle.",
        "On a tech podcast, the host talks with Dr Li, an artificial-intelligence researcher.",
      ),
      lines: [
        ln("主持人", "李博士，最近一款新的人工智能模型一经发布，便引起了全网热议。", "Lǐ bóshì, zuìjìn yì kuǎn xīn de réngōng zhìnéng móxíng yìjīng fābù, biàn yǐnqǐ le quán wǎng rèyì.", "Docteur Li, un nouveau modèle d'IA a enflammé Internet dès sa sortie.", "Dr Li, a new AI model recently set the whole internet buzzing the moment it was released."),
        ln("李博士", "是的。它不仅能写文章、写代码，还能分析图片和声音。", "Shì de. Tā bùjǐn néng xiě wénzhāng, xiě dàimǎ, hái néng fēnxī túpiàn hé shēngyīn.", "Oui. Il sait écrire des articles et du code, mais aussi analyser des images et des sons.", "Yes. It can write articles and code, and also analyse images and sound."),
        ln("主持人", "很多人担心，既然机器什么都会，那人类工作的意义何在？", "Hěn duō rén dānxīn, jìrán jīqì shénme dōu huì, nà rénlèi gōngzuò de yìyì hézài?", "Beaucoup s'inquiètent : si les machines savent tout faire, quel sens garde le travail humain ?", "Many worry: if machines can do everything, what's the point of human work?"),
        ln("李博士", "诚然，一些重复性的工作会被替代，但新的职业也会随之出现。", "Chéngrán, yìxiē chóngfùxìng de gōngzuò huì bèi tìdài, dàn xīn de zhíyè yě huì suí zhī chūxiàn.", "Certes, certains emplois répétitifs vont disparaître, mais de nouveaux métiers vont apparaître en même temps.", "Admittedly, some repetitive jobs will be replaced, but new professions will emerge along with them."),
        ln("李博士", "关键在于，我们能否学会和人工智能合作，而不是和它竞争。", "Guānjiàn zàiyú, wǒmen néng fǒu xuéhuì hé réngōng zhìnéng hézuò, ér bú shì hé tā jìngzhēng.", "L'essentiel, c'est de savoir si nous apprendrons à coopérer avec l'IA plutôt qu'à rivaliser avec elle.", "The key is whether we can learn to work with AI rather than compete against it."),
        ln("主持人", "虽说它很聪明，可它有时候也会一本正经地胡说八道。", "Suīshuō tā hěn cōngming, kě tā yǒu shíhou yě huì yì běn zhèng jīng de hú shuō bā dào.", "Bon, elle est très intelligente, mais il lui arrive aussi de raconter n'importe quoi avec le plus grand sérieux.", "Sure, it's clever, but sometimes it talks utter nonsense with a perfectly straight face."),
        ln("李博士", "没错，这叫“幻觉”。模型回答得好不好，很大程度上取决于训练数据的质量。", "Méi cuò, zhè jiào “huànjué”. Móxíng huídá de hǎo bu hǎo, hěn dà chéngdù shang qǔjué yú xùnliàn shùjù de zhìliàng.", "Tout à fait, c'est ce qu'on appelle des « hallucinations ». La qualité des réponses dépend en grande partie de la qualité des données d'entraînement.", "Right, that's called \"hallucination\". How well a model answers largely depends on the quality of its training data."),
        ln("李博士", "所以重要的信息，最好让它注明来源，以便自己核实。", "Suǒyǐ zhòngyào de xìnxī, zuìhǎo ràng tā zhùmíng láiyuán, yǐbiàn zìjǐ héshí.", "Donc, pour les informations importantes, mieux vaut lui demander d'indiquer ses sources, afin de pouvoir vérifier soi-même.", "So for important information, it's best to have it cite sources so you can check them yourself."),
        ln("主持人", "还有隐私问题。用户的数据一经上传，何以保证不被滥用？", "Hái yǒu yǐnsī wèntí. Yònghù de shùjù yìjīng shàngchuán, héyǐ bǎozhèng bú bèi lànyòng?", "Il y a aussi la question de la vie privée. Une fois les données des utilisateurs mises en ligne, comment garantir qu'elles ne seront pas détournées ?", "There's privacy too. Once users' data is uploaded, how can we guarantee it won't be misused?"),
        ln("李博士", "这正是立法需要解决的问题。技术发展得太快，法律往往跟不上。", "Zhè zhèng shì lìfǎ xūyào jiějué de wèntí. Jìshù fāzhǎn de tài kuài, fǎlǜ wǎngwǎng gēn bu shàng.", "C'est précisément ce que la loi doit régler. La technologie évolue si vite que le droit a souvent du retard.", "That's exactly what legislation must address. Technology moves so fast that the law often lags behind."),
        ln("主持人", "最后一个问题：人工智能有一天会拥有意识吗？", "Zuìhòu yí ge wèntí: réngōng zhìnéng yǒu yì tiān huì yōngyǒu yìshí ma?", "Dernière question : l'IA aura-t-elle un jour une conscience ?", "Last question: will AI one day have consciousness?"),
        ln("李博士", "这个问题连科学家也没有定论。不过我认为，技术的价值不在于它像不像人，而在于它能否让人过得更好。", "Zhège wèntí lián kēxuéjiā yě méiyǒu dìnglùn. Búguò wǒ rènwéi, jìshù de jiàzhí bú zàiyú tā xiàng bu xiàng rén, ér zàiyú tā néng fǒu ràng rén guò de gèng hǎo.", "Même les scientifiques n'ont pas tranché. Mais selon moi, la valeur d'une technologie ne tient pas à sa ressemblance avec l'humain, mais à sa capacité à améliorer nos vies.", "Even scientists haven't settled that. But in my view, technology's value lies not in whether it resembles humans, but in whether it makes our lives better."),
      ],
    },
    vocab: ["人工智能", "模型", "一经", "发布", "引起", "热议", "代码", "分析", "意义", "何在", "诚然", "重复", "替代", "职业", "关键", "在于", "能否", "合作", "虽说", "一本正经", "胡说八道", "幻觉", "取决于", "训练", "数据", "质量", "注明", "来源", "以便", "核实", "隐私", "用户", "上传", "何以", "滥用", "立法", "拥有", "意识", "定论", "价值"],
    grammar: ["hsk6-g20", "hsk6-g22", "hsk6-g23", "hsk6-g25", "hsk6-g26"],
    culture: {
      title: t("L'IA en Chine : entre essor et encadrement", "AI in China: rapid growth and regulation"),
      body: t(
        "La Chine est, avec les États-Unis, l'un des deux grands pôles mondiaux de l'IA. Des entreprises comme Baidu, Alibaba ou ByteDance développent leurs propres **大模型** (« grands modèles », LLM), et début 2025 le modèle open source de la start-up **DeepSeek** (深度求索) a fait sensation dans le monde entier.\n\nDès **2023**, la Chine a adopté des **Mesures provisoires sur les services d'IA générative** (生成式人工智能服务管理暂行办法), l'une des premières réglementations au monde dans ce domaine : étiquetage des contenus générés, protection des données personnelles, responsabilité des fournisseurs.",
        "China is, with the US, one of the world's two AI powerhouses. Companies such as Baidu, Alibaba and ByteDance build their own **大模型** (\"large models\", LLMs), and in early 2025 the open-source model from start-up **DeepSeek** (深度求索) caused a global stir.\n\nAs early as **2023**, China adopted **Interim Measures for Generative AI Services** (生成式人工智能服务管理暂行办法), among the world's first rules in this area: labelling generated content, protecting personal data, holding providers responsible.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "模型的表现很大程度上取决",
        after: "训练数据。",
        options: ["于", "在", "到", "对"],
        answer: 0,
        tr: t("Les performances du modèle dépendent en grande partie des données d'entraînement.", "The model's performance largely depends on the training data."),
        explain: t("取决于 = « dépendre de » ; ✗ 取决在.", "取决于 = \"depend on\"; not ✗ 取决在."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "技术的价值不",
        after: "它像不像人。",
        options: ["在于", "由于", "关于", "对于"],
        answer: 0,
        tr: t("La valeur d'une technologie ne tient pas à sa ressemblance avec l'humain.", "Technology's value doesn't lie in whether it resembles humans."),
        explain: t("在于 = « résider dans, tenir à ».", "在于 = \"lie in, consist in\"."),
      },
      {
        type: "fill",
        prompt: t("以便 ou 以免 ?", "以便 or 以免?"),
        before: "最好让它注明来源，",
        after: "自己核实。",
        options: ["以便", "以免", "以致", "以为"],
        answer: 0,
        tr: t("Mieux vaut lui demander d'indiquer ses sources, afin de pouvoir vérifier soi-même.", "Best to have it cite sources so you can check them yourself."),
        explain: t("以便 + ce qu'on veut rendre possible ; 以免 + ce qu'on veut éviter.", "以便 + what you want to make possible; 以免 + what you want to avoid."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["这款手机一经推出，便受到了欢迎。", "这款手机一经推出了，受到欢迎。", "这款手机一经推出，所以受到了欢迎。", "一经这款手机推出，便受到了欢迎。"],
        answer: 0,
        explain: t("Sujet + 一经 + V，便/就 + conséquence immédiate.", "Subject + 一经 + V，便/就 + immediate consequence."),
      },
      {
        type: "choice",
        prompt: t("Où placer 何在 ?", "Where does 何在 go?"),
        options: ["人类工作的意义何在？", "何在人类工作的意义？", "人类工作何在的意义？", "何在是人类工作的意义？"],
        answer: 0,
        explain: t("何在 se place en fin de phrase : « où est… ? / en quoi consiste… ? ».", "何在 goes at the end: \"where is…? / what does… consist of?\"."),
      },
      {
        type: "fill",
        prompt: t("Complète la concession argumentative.", "Complete the argumentative concession."),
        before: "",
        after: "，一些重复性的工作会被替代，但新的职业也会出现。",
        options: ["诚然", "诚实", "既然", "果然"],
        answer: 0,
        tr: t("Certes, certains emplois répétitifs vont disparaître, mais de nouveaux métiers vont apparaître.", "Admittedly, some repetitive jobs will be replaced, but new ones will appear."),
        explain: t("诚然 = « certes » (concession écrite). 诚实 = honnête ; 果然 = comme prévu.", "诚然 = \"admittedly\" (written). 诚实 = honest; 果然 = as expected."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["关键在于", "我们", "能否学会", "和人工智能", "合作"],
        tr: t("L'essentiel est de savoir si nous apprendrons à coopérer avec l'IA.", "The key is whether we can learn to work with AI."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["技术", "发展得太快", "法律", "往往", "跟不上"],
        tr: t("La technologie évolue si vite que le droit a souvent du retard.", "Technology moves so fast that the law often lags."),
      },
      {
        type: "listen",
        zh: "用户的数据一经上传，何以保证不被滥用？",
        options: ["用户的数据一经上传，何以保证不被滥用？", "用户的数据已经上传，所以不会被滥用。", "用户的数据一经下载，何以保证不被滥用？", "用户的数据一经上传，就一定会被滥用。"],
        answer: 0,
        tr: t("Une fois les données mises en ligne, comment garantir qu'elles ne seront pas détournées ?", "Once data is uploaded, how can we guarantee it won't be misused?"),
      },
      {
        type: "listen",
        zh: "它有时候也会一本正经地胡说八道。",
        options: ["它有时候也会一本正经地胡说八道。", "它从来不会一本正经地胡说八道。", "它有时候也会一本一本地读书。", "他有时候也会认认真真地说话。"],
        answer: 0,
        tr: t("Il lui arrive de raconter n'importe quoi avec le plus grand sérieux.", "Sometimes it talks nonsense with a perfectly straight face."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "隐私", pinyin: "yǐnsī", tr: t("vie privée", "privacy") },
          { zh: "滥用", pinyin: "lànyòng", tr: t("abuser, détourner", "to misuse") },
          { zh: "核实", pinyin: "héshí", tr: t("vérifier", "to verify") },
          { zh: "幻觉", pinyin: "huànjué", tr: t("hallucination", "hallucination") },
          { zh: "意识", pinyin: "yìshí", tr: t("conscience", "consciousness") },
          { zh: "定论", pinyin: "dìnglùn", tr: t("conclusion définitive", "final conclusion") },
        ],
      },
    ],
  },
];
