import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsA: Lesson[] = [
  // ───────────────────────── L01 · Philosophie ─────────────────────────
  {
    id: "hsk6-l01",
    level: 6,
    order: 1,
    title: t("Comment sais-tu que les poissons sont heureux ?", "How do you know the fish are happy?"),
    subtitle: t("Philosophie : bonheur, Zhuangzi et l'art de questionner", "Philosophy: happiness, Zhuangzi and the art of asking"),
    theme: "culture",
    goals: [
      t("Réduire une idée à l'essentiel avec 无非", "Reduce an idea to its core with 无非"),
      t("Affirmer prudemment avec 未尝不 et 何尝", "Affirm cautiously with 未尝不 and 何尝"),
      t("Poser des questions rhétoriques avec 岂 et 莫非", "Ask rhetorical questions with 岂 and 莫非"),
      t("Définir et conclure avec 即、乃 et 由此可见", "Define and conclude with 即、乃 and 由此可见"),
    ],
    dialogue: {
      context: t(
        "Dans un séminaire de philosophie à l'université, le professeur Lin discute du bonheur avec deux étudiants, Xiaoyu et Xiaowen.",
        "In a university philosophy seminar, Professor Lin discusses happiness with two students, Xiaoyu and Xiaowen.",
      ),
      lines: [
        ln("林教授", "今天我们讨论一个古老的问题：人到底为什么而活？", "Jīntiān wǒmen tǎolùn yí ge gǔlǎo de wèntí: rén dàodǐ wèi shénme ér huó?", "Aujourd'hui, une très vieille question : au fond, pourquoi vit-on ?", "Today we'll discuss an ancient question: what do we actually live for?"),
        ln("小宇", "我觉得人们追求的，无非是幸福和自由。", "Wǒ juéde rénmen zhuīqiú de, wúfēi shì xìngfú hé zìyóu.", "Je crois que ce que les gens recherchent, ce n'est jamais que le bonheur et la liberté.", "I think what people pursue is nothing other than happiness and freedom."),
        ln("林教授", "那么，幸福又是什么呢？有人说财富即幸福。", "Nàme, xìngfú yòu shì shénme ne? Yǒu rén shuō cáifù jí xìngfú.", "Alors, qu'est-ce que le bonheur ? Certains disent que la richesse, c'est le bonheur.", "Then what is happiness? Some say wealth is happiness."),
        ln("晓雯", "可是很多富人并不快乐。由此可见，幸福与财富没有必然的联系。", "Kěshì hěn duō fùrén bìng bú kuàilè. Yóucǐ kějiàn, xìngfú yǔ cáifù méiyǒu bìrán de liánxì.", "Mais beaucoup de riches ne sont pas heureux du tout. On voit donc que bonheur et richesse ne sont pas nécessairement liés.", "But many rich people aren't happy at all. So clearly happiness and wealth aren't necessarily linked."),
        ln("林教授", "说得好。庄子有一个故事：他和朋友惠子在桥上看鱼，庄子说：“鱼游得多快乐啊！”", "Shuō de hǎo. Zhuāngzǐ yǒu yí ge gùshi: tā hé péngyou Huìzǐ zài qiáo shang kàn yú, Zhuāngzǐ shuō: “Yú yóu de duō kuàilè a!”", "Bien dit. Il y a une histoire de Zhuangzi : sur un pont avec son ami Huizi, il regarde les poissons et dit : « Comme ils nagent joyeusement ! »", "Well said. There's a story about Zhuangzi: on a bridge with his friend Huizi, watching fish, he said, \"How happily the fish swim!\""),
        ln("林教授", "惠子反问：“子非鱼，安知鱼之乐？”意思是，你不是鱼，怎么知道鱼快乐呢？", "Huìzǐ fǎnwèn: “Zǐ fēi yú, ān zhī yú zhī lè?” Yìsi shì, nǐ bú shì yú, zěnme zhīdào yú kuàilè ne?", "Huizi rétorque : « Tu n'es pas un poisson, comment connais-tu la joie des poissons ? »", "Huizi retorted, \"You are not a fish — how do you know the joy of fish?\""),
        ln("小宇", "莫非我们永远无法真正理解别人的感受？", "Mòfēi wǒmen yǒngyuǎn wúfǎ zhēnzhèng lǐjiě biérén de gǎnshòu?", "Se pourrait-il qu'on ne puisse jamais vraiment comprendre ce que ressentent les autres ?", "Could it be that we can never truly understand how others feel?"),
        ln("晓雯", "我倒觉得，这未尝不是一种提醒：别轻易用自己的标准去判断别人。", "Wǒ dào juéde, zhè wèicháng bú shì yì zhǒng tíxǐng: bié qīngyì yòng zìjǐ de biāozhǔn qù pànduàn biérén.", "Moi, je pense plutôt que c'est peut-être un avertissement : ne pas juger trop vite les autres selon ses propres critères.", "I actually think it might well be a reminder: don't casually judge others by your own standards."),
        ln("林教授", "很有意思。如果人人都用同一个标准衡量幸福，岂不是太单调了？", "Hěn yǒu yìsi. Rúguǒ rénrén dōu yòng tóng yí ge biāozhǔn héngliáng xìngfú, qǐ bú shì tài dāndiào le?", "Intéressant. Si chacun mesurait le bonheur à la même aune, ce serait bien monotone, non ?", "Interesting. If everyone measured happiness by the same yardstick, wouldn't that be rather dull?"),
        ln("小宇", "可我何尝不想找到一个标准答案呢？那样至少不会迷茫。", "Kě wǒ hécháng bù xiǎng zhǎodào yí ge biāozhǔn dá'àn ne? Nàyàng zhìshǎo bú huì mímáng.", "Mais vous croyez que je n'aimerais pas trouver une réponse toute faite ? Au moins, je ne serais plus perdu.", "But don't you think I'd love a standard answer? At least I wouldn't feel lost."),
        ln("林教授", "迷茫乃思考的开始。哲学不是给你答案，而是教你提问。", "Mímáng nǎi sīkǎo de kāishǐ. Zhéxué bú shì gěi nǐ dá'àn, ér shì jiāo nǐ tíwèn.", "Le trouble est le commencement de la pensée. La philosophie ne te donne pas de réponses, elle t'apprend à poser des questions.", "Confusion is the beginning of thought. Philosophy doesn't give you answers; it teaches you to ask questions."),
        ln("晓雯", "看来，学会和不确定性相处，本身就是一种智慧。", "Kàn lái, xuéhuì hé bú quèdìngxìng xiāngchǔ, běnshēn jiù shì yì zhǒng zhìhuì.", "Apprendre à vivre avec l'incertitude, c'est donc en soi une forme de sagesse.", "So learning to live with uncertainty is itself a kind of wisdom."),
      ],
    },
    vocab: ["古老", "追求", "无非", "幸福", "自由", "财富", "即", "由此可见", "必然", "联系", "反问", "莫非", "永远", "无法", "理解", "感受", "未尝", "提醒", "轻易", "标准", "判断", "衡量", "岂", "单调", "何尝", "答案", "迷茫", "乃", "思考", "哲学", "提问", "相处", "本身", "智慧", "确定"],
    grammar: ["hsk6-g07", "hsk6-g10", "hsk6-g11", "hsk6-g12", "hsk6-g13", "hsk6-g19"],
    culture: {
      title: t("Zhuangzi et Huizi sur le pont de la Hao", "Zhuangzi and Huizi on the Hao bridge"),
      body: t(
        "Ce dialogue, le **濠梁之辩** (« débat sur le pont de la Hao »), vient du livre **《庄子》** (IVe s. av. J.-C.). Huizi, logicien, veut des preuves ; Zhuangzi, taoïste, répond avec humour : « Tu n'es pas moi, comment sais-tu que je ne sais pas la joie des poissons ? »\n\nZhuangzi est aussi l'auteur du célèbre **庄周梦蝶** : il rêve qu'il est un papillon, puis se demande s'il n'est pas un papillon qui rêve d'être Zhuangzi. Face au confucianisme (**儒家**), centré sur les devoirs sociaux, le taoïsme (**道家**) valorise la spontanéité (**自然**) et le « non-agir » (**无为**). Les deux courants coexistent encore dans la mentalité chinoise.",
        "This exchange, the **濠梁之辩** (\"debate on the Hao bridge\"), comes from the **《庄子》** (4th c. BC). Huizi, a logician, wants proof; Zhuangzi, a Taoist, answers wittily: \"You are not me — how do you know I don't know the joy of fish?\"\n\nZhuangzi also wrote the famous **庄周梦蝶**: he dreams he's a butterfly, then wonders whether he's a butterfly dreaming of being Zhuangzi. Against Confucianism (**儒家**) with its social duties, Taoism (**道家**) prizes spontaneity (**自然**) and \"non-action\" (**无为**). Both still coexist in the Chinese mindset.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "人们追求的，",
        after: "是幸福和自由。",
        options: ["无非", "并非", "莫非", "除非"],
        answer: 0,
        tr: t("Ce que les gens recherchent, ce n'est jamais que le bonheur et la liberté.", "What people pursue is nothing but happiness and freedom."),
        explain: t("无非 = « rien d'autre que ». 并非 = « ce n'est pas du tout ». 莫非 = « se pourrait-il que ».", "无非 = \"nothing but\". 并非 = \"is by no means\". 莫非 = \"could it be that\"."),
      },
      {
        type: "choice",
        prompt: t("Que signifie 这未尝不是一种提醒 ?", "What does 这未尝不是一种提醒 mean?"),
        options: [
          t("Cela peut très bien être un avertissement.", "This may well be a reminder."),
          t("Ce n'est jamais un avertissement.", "This is never a reminder."),
          t("Ce n'est pas encore un avertissement.", "This isn't a reminder yet."),
          t("Il ne faut pas d'avertissement.", "No reminder is needed."),
        ],
        answer: 0,
        explain: t("未尝不 = double négation atténuée → affirmation prudente.", "未尝不 = softened double negative → cautious affirmation."),
      },
      {
        type: "choice",
        prompt: t("« 我何尝不想休息？ » veut dire…", "\"我何尝不想休息？\" means…"),
        options: [
          t("J'aimerais bien me reposer, moi aussi !", "Of course I'd like a rest too!"),
          t("Je ne veux jamais me reposer.", "I never want to rest."),
          t("Quand est-ce que je me repose ?", "When do I rest?"),
          t("Pourquoi voudrais-je me reposer ?", "Why would I want to rest?"),
        ],
        answer: 0,
        explain: t("何尝 + 不 = question rhétorique : le sens réel est positif.", "何尝 + 不 = rhetorical: the real meaning is positive."),
      },
      {
        type: "fill",
        prompt: t("Complète la question rhétorique.", "Complete the rhetorical question."),
        before: "如果人人都只考虑自己，社会",
        after: "乱了套？",
        options: ["岂不是", "莫非是", "何尝是", "即是"],
        answer: 0,
        tr: t("Si chacun ne pensait qu'à soi, la société ne tomberait-elle pas dans le chaos ?", "If everyone thought only of themselves, wouldn't society descend into chaos?"),
        explain: t("岂不是 montre une conséquence absurde ou évidente.", "岂不是 exposes an absurd or obvious consequence."),
      },
      {
        type: "choice",
        prompt: t("莫非 ou 难道 ? « Il n'a pas dit un mot : aurait-il un souci ? »", "莫非 or 难道? \"He hasn't said a word — could he be worried?\""),
        options: ["他一句话也没说，莫非有什么心事？", "他一句话也没说，莫非有什么心事。", "他一句话也没说，何尝有什么心事？", "他一句话也没说，乃有什么心事？"],
        answer: 0,
        explain: t("莫非 exprime une supposition sincère, sous forme de question.", "莫非 expresses a genuine guess, in question form."),
      },
      {
        type: "fill",
        prompt: t("Choisis la copule écrite.", "Choose the written copula."),
        before: "失败",
        after: "成功之母。",
        options: ["乃", "即便", "则", "亦"],
        answer: 0,
        tr: t("L'échec est la mère du succès.", "Failure is the mother of success."),
        explain: t("乃 = 是, avec un ton solennel de maxime.", "乃 = 是, with a solemn, proverbial tone."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["由此可见", "幸福", "与财富", "没有", "必然的联系"],
        tr: t("On voit donc que bonheur et richesse ne sont pas nécessairement liés.", "Thus happiness and wealth aren't necessarily linked."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["哲学", "不是给你答案", "而是", "教你", "提问"],
        tr: t("La philosophie ne te donne pas de réponses, elle t'apprend à poser des questions.", "Philosophy doesn't give answers; it teaches you to ask."),
      },
      {
        type: "listen",
        zh: "迷茫乃思考的开始。",
        options: ["迷茫乃思考的开始。", "迷茫是思考的结束。", "思考乃迷茫的开始。", "迷路乃思考的开始。"],
        answer: 0,
        tr: t("Le trouble est le commencement de la pensée.", "Confusion is the beginning of thought."),
      },
      {
        type: "listen",
        zh: "莫非我们永远无法真正理解别人的感受？",
        options: ["莫非我们永远无法真正理解别人的感受？", "难道我们永远不想理解别人的感受吗？", "莫非我们已经真正理解了别人的感受？", "我们永远可以真正理解别人的感受。"],
        answer: 0,
        tr: t("Se pourrait-il qu'on ne puisse jamais vraiment comprendre ce que ressentent les autres ?", "Could it be that we can never truly understand others' feelings?"),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "智慧", pinyin: "zhìhuì", tr: t("sagesse", "wisdom") },
          { zh: "迷茫", pinyin: "mímáng", tr: t("perdu, désorienté", "lost, confused") },
          { zh: "衡量", pinyin: "héngliáng", tr: t("mesurer, évaluer", "to measure, weigh") },
          { zh: "追求", pinyin: "zhuīqiú", tr: t("rechercher, poursuivre", "to pursue") },
          { zh: "必然", pinyin: "bìrán", tr: t("nécessaire, inévitable", "inevitable, necessary") },
        ],
      },
    ],
  },

  // ───────────────────────── L02 · Mondialisation ─────────────────────────
  {
    id: "hsk6-l02",
    level: 6,
    order: 2,
    title: t("De Chongqing à Duisbourg", "From Chongqing to Duisburg"),
    subtitle: t("Mondialisation : échanges, tensions et équilibre", "Globalisation: trade, tensions and balance"),
    theme: "society",
    goals: [
      t("Situer des données dans le temps avec 截至 et 自…以来", "Date statistics with 截至 and 自…以来"),
      t("Comparer avec 与…相比", "Compare with 与…相比"),
      t("Décrire une progression avec 进而 et 乃至", "Describe progression with 进而 and 乃至"),
      t("Prédire une conséquence avec 势必", "Predict a consequence with 势必"),
    ],
    dialogue: {
      context: t(
        "Un article de magazine économique sur la mondialisation, à travers l'exemple des trains de fret Chine-Europe.",
        "A business-magazine article on globalisation, through the example of China–Europe freight trains.",
      ),
      lines: [
        ln("—", "自二十一世纪初以来，全球化深刻地改变了世界经济的面貌。", "Zì èrshíyī shìjì chū yǐlái, quánqiúhuà shēnkè de gǎibiàn le shìjiè jīngjì de miànmào.", "Depuis le début du XXIe siècle, la mondialisation a profondément transformé le visage de l'économie mondiale.", "Since the early 21st century, globalisation has profoundly reshaped the world economy."),
        ln("—", "与几十年前相比，今天的一部手机可能由十几个国家生产的零件组成。", "Yǔ jǐshí nián qián xiāngbǐ, jīntiān de yí bù shǒujī kěnéng yóu shíjǐ ge guójiā shēngchǎn de língjiàn zǔchéng.", "Contrairement à il y a quelques décennies, un téléphone peut aujourd'hui être assemblé à partir de pièces venues d'une quinzaine de pays.", "Compared with a few decades ago, a single phone today may be made of parts from a dozen or more countries."),
        ln("—", "以中欧班列为例，它从重庆出发，穿过中亚，最终到达德国的杜伊斯堡。", "Yǐ Zhōng-Ōu bānliè wéi lì, tā cóng Chóngqìng chūfā, chuānguò Zhōng-Yà, zuìzhōng dàodá Déguó de Dùyīsībǎo.", "Prenons les trains de fret Chine-Europe : ils partent de Chongqing, traversent l'Asie centrale et arrivent à Duisbourg, en Allemagne.", "Take the China–Europe freight trains: they leave Chongqing, cross Central Asia and end up in Duisburg, Germany."),
        ln("—", "截至去年年底，中欧班列已经开行了十万多列，连接了欧洲二十多个国家。", "Jiézhì qùnián niándǐ, Zhōng-Ōu bānliè yǐjīng kāixíng le shíwàn duō liè, liánjiē le Ōuzhōu èrshí duō ge guójiā.", "À la fin de l'année dernière, plus de cent mille convois avaient circulé, reliant plus de vingt pays européens.", "As of the end of last year, over 100,000 trips had run, linking more than twenty European countries."),
        ln("—", "它不仅降低了运输成本，而且带动了沿线地区的发展，进而改变了当地人的生活。", "Tā bùjǐn jiàngdī le yùnshū chéngběn, érqiě dàidòng le yánxiàn dìqū de fāzhǎn, jìn'ér gǎibiàn le dāngdì rén de shēnghuó.", "Ces trains ont réduit les coûts de transport, stimulé le développement des régions traversées, et, au-delà, changé la vie des habitants.", "They've cut transport costs, driven development along the route and, beyond that, changed local people's lives."),
        ln("—", "然而，全球化并非只有好处。", "Rán'ér, quánqiúhuà bìngfēi zhǐyǒu hǎochu.", "Mais la mondialisation n'a pas que des avantages.", "Yet globalisation is by no means all benefits."),
        ln("—", "一些制造业工作转移到了成本更低的国家，发达国家的部分工人因此失业。", "Yìxiē zhìzàoyè gōngzuò zhuǎnyí dào le chéngběn gèng dī de guójiā, fādá guójiā de bùfen gōngrén yīncǐ shīyè.", "Des emplois industriels ont été délocalisés vers des pays moins chers, et certains ouvriers des pays développés ont perdu leur travail.", "Some manufacturing jobs have moved to cheaper countries, leaving some workers in developed nations unemployed."),
        ln("—", "近年来，贸易摩擦不断，一些国家开始提高关税。", "Jìnnián lái, màoyì mócā búduàn, yìxiē guójiā kāishǐ tígāo guānshuì.", "Ces dernières années, les frictions commerciales se multiplient et certains pays relèvent leurs droits de douane.", "In recent years, trade frictions have kept flaring and some countries have raised tariffs."),
        ln("—", "专家指出，贸易保护主义势必影响全球供应链，乃至整个世界经济的稳定。", "Zhuānjiā zhǐchū, màoyì bǎohù zhǔyì shìbì yǐngxiǎng quánqiú gōngyìngliàn, nǎizhì zhěnggè shìjiè jīngjì de wěndìng.", "Selon les experts, le protectionnisme pèsera forcément sur les chaînes d'approvisionnement mondiales, voire sur la stabilité de toute l'économie mondiale.", "Experts note that protectionism is bound to affect global supply chains, and even the stability of the entire world economy."),
        ln("—", "另一方面，全球化也让不同文化之间的交流更加频繁。", "Lìng yì fāngmiàn, quánqiúhuà yě ràng bùtóng wénhuà zhījiān de jiāoliú gèngjiā pínfán.", "D'un autre côté, la mondialisation a aussi multiplié les échanges entre cultures.", "On the other hand, globalisation has also made cultural exchange more frequent."),
        ln("—", "年轻人看韩国电视剧、听欧美音乐、吃日本料理，这些已经成为日常生活的一部分。", "Niánqīngrén kàn Hánguó diànshìjù, tīng Ōu-Měi yīnyuè, chī Rìběn liàolǐ, zhèxiē yǐjīng chéngwéi rìcháng shēnghuó de yí bùfen.", "Regarder des séries coréennes, écouter de la musique occidentale, manger japonais : tout cela fait désormais partie du quotidien des jeunes.", "Watching Korean dramas, listening to Western music, eating Japanese food — young people now see this as everyday life."),
        ln("—", "如何在开放与保护之间找到平衡，势必是未来几十年各国共同面对的课题。", "Rúhé zài kāifàng yǔ bǎohù zhījiān zhǎodào pínghéng, shìbì shì wèilái jǐshí nián gè guó gòngtóng miànduì de kètí.", "Trouver l'équilibre entre ouverture et protection sera inévitablement le grand défi commun des prochaines décennies.", "How to balance openness and protection will inevitably be a shared challenge for all nations in the decades ahead."),
      ],
    },
    vocab: ["全球化", "深刻", "面貌", "零件", "组成", "穿过", "最终", "截至", "连接", "运输", "成本", "带动", "沿线", "地区", "进而", "当地", "并非", "制造业", "转移", "发达", "失业", "贸易", "摩擦", "关税", "指出", "势必", "乃至", "稳定", "交流", "频繁", "日常", "平衡", "面对", "课题", "开放", "保护"],
    grammar: ["hsk6-g01", "hsk6-g08", "hsk6-g15", "hsk6-g28", "hsk6-g31"],
    culture: {
      title: t("De « l'usine du monde » aux trains de la soie", "From \"the world's factory\" to silk-road trains"),
      body: t(
        "En **2001**, la Chine entre à l'**OMC** (世贸组织). En vingt ans, elle devient **« l'usine du monde »** (世界工厂) et le premier exportateur mondial. Les villes côtières comme Shenzhen ou Dongguan attirent des dizaines de millions de travailleurs venus de l'intérieur.\n\nLes **中欧班列** (trains Chine-Europe), lancés en 2011, mettent environ **deux semaines** pour relier la Chine à l'Europe : deux fois plus vite que le bateau, bien moins cher que l'avion. Ils symbolisent l'initiative **« 一带一路 »**. Aujourd'hui, le mot à la mode est plutôt **« 双循环 »** (« double circulation ») : miser à la fois sur le marché intérieur et sur l'ouverture.",
        "In **2001** China joined the **WTO** (世贸组织). Within twenty years it became **\"the world's factory\"** (世界工厂) and the top exporter. Coastal cities like Shenzhen and Dongguan drew tens of millions of workers from inland provinces.\n\nThe **中欧班列** (China–Europe freight trains), launched in 2011, take about **two weeks** to reach Europe: twice as fast as shipping, far cheaper than air. They symbolise the **\"Belt and Road\"** initiative. Today's buzzword is **\"双循环\"** (\"dual circulation\"): betting on both the domestic market and openness.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("截至 ou 截止 ?", "截至 or 截止?"),
        before: "",
        after: "去年年底，中欧班列已经开行了十万多列。",
        options: ["截至", "截止", "自从", "直到"],
        answer: 0,
        tr: t("À la fin de l'année dernière, plus de cent mille convois avaient circulé.", "As of the end of last year, over 100,000 trips had run."),
        explain: t("截至 + date = « en date du » (arrêt d'une statistique). 截止 = verbe « prendre fin ».", "截至 + date = \"as of\" (cut-off for a figure). 截止 = verb \"to close\"."),
      },
      {
        type: "fill",
        prompt: t("Complète la structure.", "Complete the structure."),
        before: "自加入世贸组织",
        after: "，中国的对外贸易迅速增长。",
        options: ["以来", "以后来", "以前", "从来"],
        answer: 0,
        tr: t("Depuis son entrée à l'OMC, le commerce extérieur de la Chine a connu une croissance rapide.", "Since joining the WTO, China's foreign trade has grown rapidly."),
        explain: t("自…以来 = depuis un point de départ jusqu'à maintenant.", "自…以来 = from a starting point up to now."),
      },
      {
        type: "choice",
        prompt: t("进而 ou 从而 ? « D'abord conquérir le marché intérieur, puis se lancer dans le monde. »", "进而 or 从而? \"First win the home market, then go global.\""),
        options: ["先占领国内市场，进而走向世界。", "先占领国内市场，从而走向世界。", "先占领国内市场，进而所以走向世界。", "进而先占领国内市场，走向世界。"],
        answer: 0,
        explain: t("进而 = étape supplémentaire. 从而 = résultat d'une mesure.", "进而 = a further step. 从而 = the result of a measure."),
      },
      {
        type: "choice",
        prompt: t("Quel ordre est correct avec 乃至 ?", "Which order is correct with 乃至?"),
        options: ["影响了整个亚洲，乃至全世界。", "影响了全世界，乃至整个亚洲。", "影响了乃至全世界整个亚洲。", "乃至影响了整个亚洲全世界。"],
        answer: 0,
        explain: t("乃至 introduit l'élément le plus large de la gradation.", "乃至 introduces the widest item on the scale."),
      },
      {
        type: "fill",
        prompt: t("Complète la prédiction.", "Complete the prediction."),
        before: "贸易保护主义",
        after: "影响全球经济的增长。",
        options: ["势必", "必须", "未必", "不必"],
        answer: 0,
        tr: t("Le protectionnisme pèsera forcément sur la croissance mondiale.", "Protectionism is bound to affect global growth."),
        explain: t("势必 = déduction certaine à partir d'une tendance. 必须 = obligation.", "势必 = a sure deduction from a trend. 必须 = obligation."),
      },
      {
        type: "fill",
        prompt: t("Complète la comparaison.", "Complete the comparison."),
        before: "与几十年前",
        after: "，今天的手机由很多国家的零件组成。",
        options: ["相比", "比较得", "一样", "比起"],
        answer: 0,
        tr: t("Par rapport à il y a quelques décennies, les téléphones sont aujourd'hui faits de pièces de nombreux pays.", "Compared with decades ago, phones today use parts from many countries."),
        explain: t("与 + N + 相比 = « comparé à ».", "与 + N + 相比 = \"compared with\"."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["自二十一世纪初以来", "全球化", "深刻地", "改变了", "世界经济的面貌"],
        tr: t("Depuis le début du XXIe siècle, la mondialisation a profondément changé l'économie mondiale.", "Since the early 21st century, globalisation has profoundly changed the world economy."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["全球化", "并非", "只有", "好处"],
        tr: t("La mondialisation n'a pas que des avantages.", "Globalisation isn't all benefits."),
      },
      {
        type: "listen",
        zh: "一些国家开始提高关税。",
        options: ["一些国家开始提高关税。", "一些国家开始降低关税。", "一些国家开始提高工资。", "所有国家都提高了关税。"],
        answer: 0,
        tr: t("Certains pays commencent à relever leurs droits de douane.", "Some countries have started raising tariffs."),
      },
      {
        type: "listen",
        zh: "全球化也让不同文化之间的交流更加频繁。",
        options: ["全球化也让不同文化之间的交流更加频繁。", "全球化让不同文化之间的交流越来越少。", "全球化也让相同文化之间的交流更加频繁。", "全球化也让不同国家之间的贸易更加频繁。"],
        answer: 0,
        tr: t("La mondialisation a aussi multiplié les échanges entre cultures.", "Globalisation has also made cultural exchanges more frequent."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "关税", pinyin: "guānshuì", tr: t("droits de douane", "tariff") },
          { zh: "摩擦", pinyin: "mócā", tr: t("friction, conflit", "friction") },
          { zh: "制造业", pinyin: "zhìzàoyè", tr: t("industrie manufacturière", "manufacturing") },
          { zh: "平衡", pinyin: "pínghéng", tr: t("équilibre", "balance") },
          { zh: "频繁", pinyin: "pínfán", tr: t("fréquent", "frequent") },
        ],
      },
    ],
  },

  // ───────────────────────── L03 · Droit & éthique ─────────────────────────
  {
    id: "hsk6-l03",
    level: 6,
    order: 3,
    title: t("Faut-il relever une personne âgée ?", "Should you help up an elderly person?"),
    subtitle: t("Droit et éthique : la loi du « bon Samaritain »", "Law & ethics: the \"Good Samaritan\" law"),
    theme: "society",
    goals: [
      t("Comprendre le langage juridique : 鉴于、若…则…、倘若", "Understand legal language: 鉴于、若…则…、倘若"),
      t("Donner un fondement avec 基于 et 本着", "Give grounds with 基于 and 本着"),
      t("Exprimer une conséquence négative avec 致使", "Express a negative consequence with 致使"),
      t("Nuancer avec les doubles négations 不无、无不、不可不", "Nuance with double negatives 不无、无不、不可不"),
    ],
    dialogue: {
      context: t(
        "Lors d'une conférence dans une faculté de droit, l'avocate Wang répond aux questions de deux étudiants, Liu Ming et Chen Jing.",
        "At a law-school talk, lawyer Wang answers questions from two students, Liu Ming and Chen Jing.",
      ),
      lines: [
        ln("刘明", "王律师，我想请教一个问题：看到老人摔倒，到底该不该扶？", "Wáng lǜshī, wǒ xiǎng qǐngjiào yí ge wèntí: kàndào lǎorén shuāidǎo, dàodǐ gāi bu gāi fú?", "Maître Wang, j'aimerais vous poser une question : si on voit une personne âgée tomber, faut-il l'aider à se relever ?", "Ms Wang, may I ask: if you see an elderly person fall, should you help them up or not?"),
        ln("王律师", "这个问题在中国讨论了很多年。早些年曾有好心人扶人反被起诉，致使很多人不敢伸出援手。", "Zhège wèntí zài Zhōngguó tǎolùn le hěn duō nián. Zǎo xiē nián céng yǒu hǎoxīnrén fú rén fǎn bèi qǐsù, zhìshǐ hěn duō rén bù gǎn shēn chū yuánshǒu.", "Cette question fait débat en Chine depuis des années. Autrefois, des personnes bien intentionnées ont été poursuivies en justice par ceux qu'elles avaient aidés, si bien que beaucoup n'osaient plus tendre la main.", "This has been debated in China for years. Some time ago, good Samaritans were sued by the people they helped, which left many afraid to lend a hand."),
        ln("陈静", "我听说过。大家的担心不无道理。", "Wǒ tīngshuō guo. Dàjiā de dānxīn bù wú dàolǐ.", "J'en ai entendu parler. Les craintes des gens ne sont pas sans fondement.", "I've heard about that. People's worries aren't without reason."),
        ln("王律师", "鉴于这种情况，法律后来做了明确规定：因自愿实施紧急救助造成受助人损害的，救助人不承担民事责任。", "Jiànyú zhè zhǒng qíngkuàng, fǎlǜ hòulái zuò le míngquè guīdìng: yīn zìyuàn shíshī jǐnjí jiùzhù zàochéng shòuzhùrén sǔnhài de, jiùzhùrén bù chéngdān mínshì zérèn.", "Face à cette situation, la loi a ensuite clairement établi que celui qui porte secours volontairement en urgence n'engage pas sa responsabilité civile s'il cause un dommage à la personne secourue.", "In view of this, the law later made it explicit: a person who voluntarily gives emergency help bears no civil liability for harm caused to the person helped."),
        ln("陈静", "也就是说，倘若我好心救人，就算不小心造成伤害，也不用负责？", "Yě jiù shì shuō, tǎngruò wǒ hǎoxīn jiù rén, jiùsuàn bù xiǎoxīn zàochéng shānghài, yě búyòng fùzé?", "Autrement dit, si je porte secours de bonne foi, même si je blesse la personne par accident, je ne suis pas responsable ?", "So if I help someone in good faith, even if I accidentally cause harm, I'm not liable?"),
        ln("王律师", "原则上是这样。这条规定正是基于鼓励见义勇为的目的而制定的。", "Yuánzé shang shì zhèyàng. Zhè tiáo guīdìng zhèng shì jīyú gǔlì jiàn yì yǒng wéi de mùdì ér zhìdìng de.", "En principe, oui. Cette disposition a précisément été adoptée dans le but d'encourager les actes de courage civique.", "In principle, yes. The provision was drafted precisely to encourage people to step in and help."),
        ln("刘明", "可是如果有人故意说谎，说是救他的人撞的呢？", "Kěshì rúguǒ yǒu rén gùyì shuōhuǎng, shuō shì jiù tā de rén zhuàng de ne?", "Mais si quelqu'un ment délibérément et accuse son sauveteur de l'avoir renversé ?", "But what if someone deliberately lies and claims their rescuer knocked them down?"),
        ln("王律师", "那就要本着实事求是的原则，看证据。现在到处都有摄像头，说谎的代价很高。", "Nà jiù yào běnzhe shí shì qiú shì de yuánzé, kàn zhèngjù. Xiànzài dàochù dōu yǒu shèxiàngtóu, shuōhuǎng de dàijià hěn gāo.", "Il faut alors s'en tenir aux faits, selon le principe de « chercher la vérité dans les faits », et examiner les preuves. Avec les caméras partout, mentir coûte cher.", "Then you follow the principle of seeking truth from facts and look at the evidence. With cameras everywhere now, lying is costly."),
        ln("王律师", "近年来，也有人为了骗钱不惜伪造证据，最后都受到了法律的惩罚。", "Jìnnián lái, yě yǒu rén wèile piàn qián bùxī wěizào zhèngjù, zuìhòu dōu shòudào le fǎlǜ de chéngfá.", "Ces dernières années, certains sont allés jusqu'à fabriquer de fausses preuves pour extorquer de l'argent ; ils ont tous fini par être punis.", "In recent years, some people even faked evidence to extort money, and all of them were eventually punished."),
        ln("陈静", "这么说，法律不仅要惩罚坏人，也要保护好人。", "Zhème shuō, fǎlǜ bùjǐn yào chéngfá huàirén, yě yào bǎohù hǎorén.", "Donc la loi ne doit pas seulement punir les malhonnêtes, elle doit aussi protéger les gens de bien.", "So the law must not only punish wrongdoers but also protect good people."),
        ln("王律师", "没错。不过法律只是底线，道德才是更高的要求。", "Méi cuò. Búguò fǎlǜ zhǐ shì dǐxiàn, dàodé cái shì gèng gāo de yāoqiú.", "Exactement. Mais la loi n'est qu'un minimum ; la morale exige davantage.", "Exactly. But the law is only the baseline; morality asks more of us."),
        ln("刘明", "听了您的讲解，在场的同学无不觉得受益匪浅。", "Tīng le nín de jiǎngjiě, zài chǎng de tóngxué wú bù juéde shòuyì fěi qiǎn.", "Après vos explications, tous les étudiants présents ont le sentiment d'avoir beaucoup appris.", "After your explanation, every student here feels they've gained a great deal."),
        ln("王律师", "最后提醒大家：救人的时候，也不可不注意保护自己。", "Zuìhòu tíxǐng dàjiā: jiù rén de shíhou, yě bù kě bù zhùyì bǎohù zìjǐ.", "Un dernier conseil : quand vous portez secours, n'oubliez surtout pas de vous protéger vous-mêmes.", "One last reminder: when helping others, you must also take care to protect yourselves."),
      ],
    },
    vocab: ["请教", "摔倒", "扶", "好心", "起诉", "致使", "不无", "鉴于", "明确", "规定", "自愿", "紧急", "救助", "损害", "承担", "责任", "倘若", "伤害", "负责", "原则", "基于", "鼓励", "见义勇为", "制定", "故意", "说谎", "本着", "实事求是", "证据", "代价", "不惜", "伪造", "惩罚", "底线", "道德", "无不", "受益匪浅"],
    grammar: ["hsk6-g04", "hsk6-g05", "hsk6-g06", "hsk6-g21", "hsk6-g27", "hsk6-g30"],
    culture: {
      title: t("De l'affaire Peng Yu à la « loi des bons Samaritains »", "From the Peng Yu case to the \"Good Samaritan law\""),
      body: t(
        "En **2006**, à Nankin, un jeune homme nommé **彭宇** aide une vieille dame tombée à un arrêt de bus. Elle l'accuse ensuite de l'avoir renversée, et un tribunal le condamne à payer une partie des frais, avec un raisonnement devenu célèbre : « s'il ne l'avait pas bousculée, pourquoi l'aurait-il aidée ? ». L'affaire a traumatisé l'opinion : **« 扶不扶 »** (« aider ou pas ? ») est devenu un débat national.\n\nEn **2017**, puis dans le **Code civil de 2021** (民法典, article 184), la Chine a adopté une disposition surnommée **« 好人法 »** (« loi des gens de bien ») : celui qui porte secours volontairement n'est pas civilement responsable des dommages causés. Le 成语 **见义勇为** (« voir ce qui est juste et agir avec courage ») est le terme officiel pour ces actes.",
        "In **2006**, in Nanjing, a young man named **Peng Yu** helped an old woman who had fallen at a bus stop. She then accused him of knocking her down, and a court ordered him to pay part of her costs, with now-infamous reasoning: \"if he hadn't pushed her, why would he help her?\". The case shocked the public, and **\"扶不扶\"** (\"help or not?\") became a national debate.\n\nIn **2017**, then in the **2021 Civil Code** (民法典, Art. 184), China adopted a provision nicknamed the **\"好人法\"** (\"good people's law\"): anyone who voluntarily gives emergency aid isn't civilly liable for resulting harm. The 成语 **见义勇为** (\"see what is right and act bravely\") is the official term for such acts.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Que signifie 大家的担心不无道理 ?", "What does 大家的担心不无道理 mean?"),
        options: [
          t("Les craintes des gens ne sont pas sans fondement.", "People's worries aren't without reason."),
          t("Les craintes des gens n'ont aucun fondement.", "People's worries are groundless."),
          t("Les gens n'ont pas de craintes.", "People have no worries."),
          t("Il ne faut pas s'inquiéter.", "There's no need to worry."),
        ],
        answer: 0,
        explain: t("不无 + N = « pas sans… » : il y a une part de vérité.", "不无 + N = \"not without…\": there's some truth in it."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon verbe causatif.", "Fill in the right causative verb."),
        before: "司机酒后驾驶，",
        after: "两人受伤。",
        options: ["致使", "使得", "以便", "从而"],
        answer: 0,
        tr: t("Le conducteur roulait ivre, ce qui a fait deux blessés.", "The driver drove drunk, injuring two people."),
        explain: t("致使 = entraîner un résultat négatif (style juridique).", "致使 = lead to a negative outcome (legal style)."),
      },
      {
        type: "fill",
        prompt: t("Complète l'ouverture formelle.", "Complete the formal opening."),
        before: "",
        after: "目前的情况，公司决定推迟上市。",
        options: ["鉴于", "由于是", "关于", "对于"],
        answer: 0,
        tr: t("Compte tenu de la situation actuelle, l'entreprise a décidé de reporter son introduction en Bourse.", "In view of the current situation, the company has decided to postpone its IPO."),
        explain: t("鉴于 + situation → décision : registre administratif.", "鉴于 + situation → decision: administrative register."),
      },
      {
        type: "choice",
        prompt: t("基于 ou 本着 ? « …selon le principe d'égalité et de bénéfice mutuel »", "基于 or 本着? \"…on the principle of equality and mutual benefit\""),
        options: ["本着平等互利的原则", "基于平等互利的精神地", "本着以上数据", "鉴于平等互利的原则地"],
        answer: 0,
        explain: t("本着 + principe/esprit ; 基于 + faits/données.", "本着 + principle/spirit; 基于 + facts/data."),
      },
      {
        type: "fill",
        prompt: t("Complète la règle.", "Complete the rule."),
        before: "若违反本规定，",
        after: "需承担相应的责任。",
        options: ["则", "而", "且", "却"],
        answer: 0,
        tr: t("En cas de violation du présent règlement, la responsabilité correspondante sera engagée.", "Breaching these rules incurs the corresponding liability."),
        explain: t("若…，则… = « si…, alors… » (écrit).", "若…，则… = \"if…, then…\" (written)."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "有的企业为了利润，",
        after: "牺牲环境。",
        options: ["不惜", "可惜", "珍惜", "爱惜"],
        answer: 0,
        tr: t("Certaines entreprises n'hésitent pas à sacrifier l'environnement pour le profit.", "Some firms sacrifice the environment for profit without hesitation."),
        explain: t("不惜 + sacrifice = « ne pas reculer devant ». 可惜 = « dommage ».", "不惜 + sacrifice = \"not shrink from\". 可惜 = \"what a pity\"."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["法律", "只是", "底线", "道德", "才是更高的要求"],
        tr: t("La loi n'est qu'un minimum ; la morale exige davantage.", "The law is only the baseline; morality asks more."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["在场的同学", "无不", "觉得", "受益匪浅"],
        tr: t("Tous les étudiants présents ont le sentiment d'avoir beaucoup appris.", "Every student present feels they've gained a lot."),
      },
      {
        type: "listen",
        zh: "倘若我好心救人，也不用负责吗？",
        options: ["倘若我好心救人，也不用负责吗？", "倘若我好心救人，也要负责吗？", "倘若我不救人，也不用负责吗？", "如果我好心帮人，就要负责吗？"],
        answer: 0,
        tr: t("Si je porte secours de bonne foi, je ne suis pas responsable non plus ?", "If I help in good faith, am I also not liable?"),
      },
      {
        type: "listen",
        zh: "说谎的代价很高。",
        options: ["说谎的代价很高。", "说话的代价很高。", "说谎的代价不高。", "说谎的人很多。"],
        answer: 0,
        tr: t("Mentir coûte cher.", "Lying is costly."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "起诉", pinyin: "qǐsù", tr: t("poursuivre en justice", "to sue") },
          { zh: "证据", pinyin: "zhèngjù", tr: t("preuve", "evidence") },
          { zh: "惩罚", pinyin: "chéngfá", tr: t("punir, sanction", "to punish") },
          { zh: "底线", pinyin: "dǐxiàn", tr: t("limite minimale, ligne rouge", "baseline, bottom line") },
          { zh: "见义勇为", pinyin: "jiàn yì yǒng wéi", tr: t("agir avec courage pour une juste cause", "act bravely for a just cause") },
        ],
      },
    ],
  },
];
