import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsA: Lesson[] = [
  // ───────────────────────── L01 · Société ─────────────────────────
  {
    id: "hsk4-l01",
    level: 4,
    order: 1,
    title: t("Les seniors à l'ère du smartphone", "Seniors in the smartphone age"),
    subtitle: t("Société : vieillissement et entraide", "Society: ageing and mutual help"),
    theme: "society",
    goals: [
      t("Parler des changements de la société avec 随着", "Talk about social change with 随着"),
      t("Exprimer un résultat inattendu avec 不但不…反而…", "Express an unexpected outcome with 不但不…反而…"),
      t("Donner un point de vue avec 对…来说 et 在…看来", "Give a viewpoint with 对…来说 and 在…看来"),
      t("Raconter un incident au passif avec 让/叫/给", "Report an incident in the passive with 让/叫/给"),
    ],
    dialogue: {
      context: t(
        "Une journaliste visite un cours de smartphone pour seniors dans un quartier de Pékin. Elle interroge Mme Wang, une participante, et Xiao Lin, un jeune bénévole.",
        "A reporter visits a smartphone class for seniors in a Beijing neighbourhood. She talks to Mrs Wang, a participant, and Xiao Lin, a young volunteer.",
      ),
      lines: [
        ln("记者", "王阿姨，您好！听说您每个星期都来社区的手机课？", "Wáng āyí, nín hǎo! Tīngshuō nín měi ge xīngqī dōu lái shèqū de shǒujī kè?", "Bonjour madame Wang ! Il paraît que vous venez chaque semaine au cours de smartphone du quartier ?", "Hello, Mrs Wang! I hear you come to the neighbourhood phone class every week?"),
        ln("王阿姨", "对啊。随着社会的发展，现在做什么都离不开手机。", "Duì a. Suízhe shèhuì de fāzhǎn, xiànzài zuò shénme dōu lí bu kāi shǒujī.", "Eh oui. Avec l'évolution de la société, on ne peut plus rien faire sans téléphone.", "That's right. As society develops, you can't do anything without a phone now."),
        ln("王阿姨", "对我们老年人来说，挂号、买菜、坐车，甚至去公园都要扫码。", "Duì wǒmen lǎoniánrén lái shuō, guàhào, mǎi cài, zuò chē, shènzhì qù gōngyuán dōu yào sǎo mǎ.", "Pour nous, les personnes âgées, prendre rendez-vous à l'hôpital, faire les courses, prendre le bus, et même aller au parc, il faut scanner un QR code.", "For us older folks, booking at the hospital, buying groceries, taking the bus — even going to the park — all need a QR code scan."),
        ln("记者", "一开始学的时候难吗？", "Yì kāishǐ xué de shíhou nán ma?", "C'était difficile au début ?", "Was it hard when you started learning?"),
        ln("王阿姨", "太难了！有一次我按错了，钱让人骗走了两千块左右。", "Tài nán le! Yǒu yí cì wǒ àn cuò le, qián ràng rén piàn zǒu le liǎng qiān kuài zuǒyòu.", "Terrible ! Une fois, j'ai appuyé au mauvais endroit et on m'a escroqué environ deux mille yuans.", "Really hard! Once I pressed the wrong thing and got scammed out of about two thousand yuan."),
        ln("王阿姨", "我儿子知道以后，不但没批评我，反而给我报名参加了这个课。", "Wǒ érzi zhīdào yǐhòu, búdàn méi pīpíng wǒ, fǎn'ér gěi wǒ bàomíng cānjiā le zhège kè.", "Quand mon fils l'a appris, loin de me gronder, il m'a inscrite à ce cours.", "When my son found out, instead of criticising me, he signed me up for this class."),
        ln("记者", "小林，你是这里的志愿者，为什么想来帮忙？", "Xiǎo Lín, nǐ shì zhèlǐ de zhìyuànzhě, wèishénme xiǎng lái bāngmáng?", "Xiao Lin, tu es bénévole ici. Pourquoi as-tu voulu donner un coup de main ?", "Xiao Lin, you volunteer here. Why did you want to help?"),
        ln("小林", "我爷爷奶奶住在老家，我没法天天陪他们，所以想帮帮身边的老人。", "Wǒ yéye nǎinai zhù zài lǎojiā, wǒ méi fǎ tiāntiān péi tāmen, suǒyǐ xiǎng bāngbang shēnbiān de lǎorén.", "Mes grands-parents vivent dans ma ville natale, je ne peux pas être avec eux tous les jours, alors j'ai voulu aider les personnes âgées autour de moi.", "My grandparents live back in my hometown and I can't be with them every day, so I wanted to help the elderly around me."),
        ln("小林", "在我看来，老人不是不想学，只是需要多一点儿耐心。", "Zài wǒ kàn lái, lǎorén bú shì bù xiǎng xué, zhǐshì xūyào duō yìdiǎnr nàixīn.", "À mon avis, ce n'est pas que les personnes âgées ne veulent pas apprendre : il faut juste un peu plus de patience.", "In my view, it's not that older people don't want to learn — they just need a bit more patience."),
        ln("记者", "现在中国六十岁以上的人很多，这样的课一定很受欢迎吧？", "Xiànzài Zhōngguó liùshí suì yǐshàng de rén hěn duō, zhèyàng de kè yídìng hěn shòu huānyíng ba?", "Il y a aujourd'hui beaucoup de plus de soixante ans en Chine, ce genre de cours doit avoir du succès, non ?", "There are lots of over-sixties in China now; classes like this must be popular?"),
        ln("小林", "是的，每次来二十来个人，有时候教室都坐不下。", "Shì de, měi cì lái èrshí lái ge rén, yǒu shíhou jiàoshì dōu zuò bu xià.", "Oui, il vient une vingtaine de personnes à chaque fois, parfois la salle est trop petite.", "Yes, twenty-odd people come each time; sometimes the room can't seat everyone."),
        ln("王阿姨", "现在我自己会用了，甚至还能教我的老邻居呢！", "Xiànzài wǒ zìjǐ huì yòng le, shènzhì hái néng jiāo wǒ de lǎo línjū ne!", "Maintenant je me débrouille seule, et je peux même apprendre à mes vieux voisins !", "Now I can use it on my own — I can even teach my old neighbours!"),
      ],
    },
    vocab: ["社区", "社会", "发展", "随着", "老年人", "离不开", "挂号", "甚至", "扫", "骗", "左右", "批评", "反而", "报名", "参加", "志愿者", "帮忙", "陪", "身边", "耐心", "需要", "受欢迎", "以上", "邻居", "老家", "只是", "按", "教", "阿姨", "听说", "一开始", "教室"],
    grammar: ["hsk4-g01", "hsk4-g08", "hsk4-g16", "hsk4-g18", "hsk4-g27", "hsk4-g34"],
    culture: {
      title: t("Le vieillissement de la Chine et le « 4-2-1 »", "China's ageing and the \"4-2-1\" family"),
      body: t(
        "La Chine compte aujourd'hui plus de **280 millions** de personnes de plus de 60 ans. Conséquence de la politique de l'enfant unique, beaucoup de familles ont une structure **« 4-2-1 »** : quatre grands-parents, deux parents, un enfant. Les jeunes partis travailler en ville ne peuvent pas s'occuper de leurs aînés au quotidien.\n\nLes **社区** (comités de quartier) jouent donc un rôle clé : cours de smartphone, cantines pour seniors (老年食堂), visites de **志愿者**. La « fracture numérique » (数字鸿沟) est un vrai sujet : en 2020, l'État a même demandé aux hôpitaux et aux gares de garder des guichets « sans smartphone » pour les personnes âgées.",
        "China now has over **280 million** people aged 60+. A legacy of the one-child policy, many families have a **\"4-2-1\"** shape: four grandparents, two parents, one child. Young people working in big cities can't care for elders day to day.\n\nSo **社区** (neighbourhood committees) play a key role: smartphone classes, canteens for seniors (老年食堂), **volunteer** visits. The \"digital divide\" (数字鸿沟) is a real issue: in 2020 the government even asked hospitals and stations to keep \"no-smartphone\" counters for the elderly.",
      ),
    },
    exercises: [
      {
        type: "choice",
        prompt: t("Que signifie la phrase de Mme Wang ?", "What does Mrs Wang's sentence mean?"),
        zh: "我儿子不但没批评我，反而给我报了名。",
        pinyin: "Wǒ érzi búdàn méi pīpíng wǒ, fǎn'ér gěi wǒ bào le míng.",
        options: [
          t("Son fils ne l'a pas grondée ; au contraire, il l'a inscrite au cours.", "Her son didn't scold her; instead, he signed her up."),
          t("Son fils l'a grondée, puis l'a inscrite au cours.", "Her son scolded her, then signed her up."),
          t("Son fils ne l'a ni grondée ni inscrite au cours.", "Her son neither scolded her nor signed her up."),
          t("Son fils l'a grondée parce qu'elle s'était inscrite.", "Her son scolded her for signing up."),
        ],
        answer: 0,
        explain: t("不但没 A，反而 B : A n'arrive pas, c'est même l'inverse (B) qui se produit.", "不但没 A，反而 B: A doesn't happen; the opposite (B) does."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon mot.", "Fill in the right word."),
        before: "对老年人",
        after: "，用手机挂号并不容易。",
        options: ["来说", "看来", "关于", "对于"],
        answer: 0,
        tr: t("Pour les personnes âgées, prendre rendez-vous avec le téléphone n'est pas facile.", "For the elderly, booking appointments by phone isn't easy."),
        explain: t("La structure est 对…来说. 看来 va avec 在 : 在…看来.", "The frame is 对…来说. 看来 pairs with 在: 在…看来."),
      },
      {
        type: "fill",
        prompt: t("Choisis le mot qui convient au passif.", "Choose the word that forms the passive."),
        before: "我的钱包",
        after: "小偷偷走了。",
        options: ["让", "把", "对", "从"],
        answer: 0,
        tr: t("Mon portefeuille a été volé par un pickpocket.", "My wallet was stolen by a pickpocket."),
        explain: t("Passif oral : patient + 让 + agent + verbe + résultat.", "Spoken passive: patient + 让 + agent + verb + result."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "他忙得要命，",
        after: "连饭都没时间吃。",
        options: ["甚至", "反而", "于是", "只是"],
        answer: 0,
        tr: t("Il est débordé, au point de ne même pas avoir le temps de manger.", "He's swamped — he doesn't even have time to eat."),
        explain: t("甚至 + 连…都 : gradation vers l'extrême.", "甚至 + 连…都: climbing to the extreme."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["随着经济的发展，生活越来越方便了。", "随着经济发展得很快，生活越来越方便了。", "生活越来越方便了随着经济的发展。", "随着经济的发展，生活很方便。"],
        answer: 0,
        explain: t("随着 + groupe nominal (X 的发展), en tête, et la principale montre un changement (越来越).", "随着 + noun phrase (X 的发展), at the front, and the main clause shows change (越来越)."),
      },
      {
        type: "fill",
        prompt: t("Choisis la bonne approximation.", "Pick the right approximation."),
        before: "每次上课都来二十",
        after: "个人。",
        options: ["来", "左右", "上下", "以上"],
        answer: 0,
        tr: t("Une vingtaine de personnes viennent à chaque cours.", "Twenty-odd people come to every class."),
        explain: t("来 se place entre le nombre rond et le classificateur ; 左右/上下/以上 se placent après le classificateur.", "来 sits between the round number and the measure word; 左右/上下/以上 come after the measure word."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["在我看来", "老人", "只是", "需要", "多一点儿耐心"],
        tr: t("À mon avis, les personnes âgées ont juste besoin d'un peu plus de patience.", "In my view, older people just need a bit more patience."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["现在", "做什么", "都", "离不开", "手机"],
        tr: t("Aujourd'hui, on ne peut rien faire sans téléphone.", "Nowadays you can't do anything without a phone."),
      },
      {
        type: "listen",
        zh: "钱让人骗走了两千块左右。",
        options: ["钱让人骗走了两千块左右。", "钱被人拿走了两千块左右。", "钱让人骗走了两百块左右。", "钱让我借走了两千块左右。"],
        answer: 0,
        tr: t("On m'a escroqué environ deux mille yuans.", "I was scammed out of about two thousand yuan."),
      },
      {
        type: "listen",
        zh: "对我们老年人来说，甚至去公园都要扫码。",
        options: ["对我们老年人来说，甚至去公园都要扫码。", "对我们年轻人来说，甚至去公园都要扫码。", "在我们老年人看来，去公园不用扫码。", "对我们老年人来说，去医院都要扫码。"],
        answer: 0,
        tr: t("Pour nous, les personnes âgées, même aller au parc exige de scanner un code.", "For us older folks, even going to the park needs a code scan."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "志愿者", pinyin: "zhìyuànzhě", tr: t("bénévole", "volunteer") },
          { zh: "耐心", pinyin: "nàixīn", tr: t("patience", "patience") },
          { zh: "批评", pinyin: "pīpíng", tr: t("critiquer, gronder", "to criticise") },
          { zh: "邻居", pinyin: "línjū", tr: t("voisin", "neighbour") },
          { zh: "报名", pinyin: "bàomíng", tr: t("s'inscrire", "to sign up") },
        ],
      },
    ],
  },

  // ───────────────────────── L02 · Travail ─────────────────────────
  {
    id: "hsk4-l02",
    level: 4,
    order: 2,
    title: t("Un dossier à rendre vendredi", "A proposal due on Friday"),
    subtitle: t("Travail : délais, contraintes et négociation", "Work: deadlines, constraints and negotiation"),
    theme: "work",
    goals: [
      t("Poser une condition indispensable avec 除非…否则…", "Set a must-have condition with 除非…否则…"),
      t("Tirer une conclusion pratique avec 既然…就…", "Draw a practical conclusion with 既然…就…"),
      t("Exprimer une obligation avec 不得不 et 非…不可", "Express obligation with 不得不 and 非…不可"),
      t("Annoncer une mauvaise nouvelle poliment avec 恐怕", "Break bad news politely with 恐怕"),
    ],
    dialogue: {
      context: t(
        "Dans une agence de conseil à Shanghai, la directrice Chen fait le point avec Xiao Wang et Xiao Li sur un dossier client urgent.",
        "At a consulting firm in Shanghai, manager Chen checks in with Xiao Wang and Xiao Li on an urgent client proposal.",
      ),
      lines: [
        ln("陈经理", "小王，客户的方案到底什么时候能交？", "Xiǎo Wáng, kèhù de fāng'àn dàodǐ shénme shíhou néng jiāo?", "Xiao Wang, le dossier du client, il sera rendu quand au juste ?", "Xiao Wang, when exactly can the client proposal be handed in?"),
        ln("小王", "陈经理，恐怕这个星期完成不了了。数据还有很多问题。", "Chén jīnglǐ, kǒngpà zhège xīngqī wánchéng bu liǎo le. Shùjù hái yǒu hěn duō wèntí.", "Madame Chen, j'ai bien peur qu'on ne puisse pas le finir cette semaine. Les données posent encore beaucoup de problèmes.", "Ms Chen, I'm afraid we can't finish it this week. There are still lots of problems with the data."),
        ln("陈经理", "不行，客户下周一就要看，你们非在周五以前交不可。", "Bù xíng, kèhù xià zhōuyī jiù yào kàn, nǐmen fēi zài zhōuwǔ yǐqián jiāo bùkě.", "Impossible, le client veut le voir lundi prochain : vous devez absolument le rendre avant vendredi.", "No way — the client wants it next Monday. You absolutely must hand it in before Friday."),
        ln("小王", "除非再给我们加一个人，否则真的来不及。", "Chúfēi zài gěi wǒmen jiā yí ge rén, fǒuzé zhēn de lái bu jí.", "À moins de nous donner une personne de plus, on n'y arrivera vraiment pas à temps.", "Unless we get one more person, we really won't make it in time."),
        ln("陈经理", "既然人不够，我就让小李去帮你们。", "Jìrán rén bú gòu, wǒ jiù ràng Xiǎo Lǐ qù bāng nǐmen.", "Puisqu'il vous manque du monde, je vais demander à Xiao Li de vous aider.", "Since you're short-handed, I'll have Xiao Li help you."),
        ln("小王", "太好了！不过这样的话，我们周末恐怕不得不加班了。", "Tài hǎo le! Búguò zhèyàng dehuà, wǒmen zhōumò kǒngpà bù dé bù jiābān le.", "Super ! Mais du coup, je crains qu'on soit obligés de travailler ce week-end.", "Great! But in that case, I'm afraid we'll have to work overtime this weekend."),
        ln("陈经理", "辛苦大家了。加班的钱公司会按规定给的。", "Xīnkǔ dàjiā le. Jiābān de qián gōngsī huì àn guīdìng gěi de.", "Merci à tous pour vos efforts. L'entreprise paiera les heures sup' selon le règlement.", "Thanks for all your hard work. The company will pay overtime as per the rules."),
        ln("小李", "陈经理，我手上还有别的任务，到底先做哪个？", "Chén jīnglǐ, wǒ shǒu shang hái yǒu bié de rènwu, dàodǐ xiān zuò nǎge?", "Madame Chen, j'ai d'autres tâches en cours : je commence par laquelle, au juste ?", "Ms Chen, I've got other tasks on my plate — which one should I do first?"),
        ln("陈经理", "先做这个方案，别的可以往后推。", "Xiān zuò zhège fāng'àn, bié de kěyǐ wǎng hòu tuī.", "Commence par ce dossier, le reste peut attendre.", "Do this proposal first; the rest can be pushed back."),
        ln("小李", "好的。那我们下午开个会，把任务分一下，否则容易重复。", "Hǎo de. Nà wǒmen xiàwǔ kāi ge huì, bǎ rènwu fēn yíxià, fǒuzé róngyì chóngfù.", "D'accord. Faisons une réunion cet après-midi pour répartir les tâches, sinon on risque de faire deux fois la même chose.", "OK. Let's meet this afternoon to split the tasks, otherwise we'll end up duplicating work."),
        ln("小王", "行。既然时间这么紧，我们就马上开始吧。", "Xíng. Jìrán shíjiān zhème jǐn, wǒmen jiù mǎshàng kāishǐ ba.", "Ça marche. Puisque les délais sont si serrés, on s'y met tout de suite.", "Right. Since time is so tight, let's get started right away."),
        ln("陈经理", "每天下班以前给我发个简单的报告，有问题及时告诉我。", "Měi tiān xiàbān yǐqián gěi wǒ fā ge jiǎndān de bàogào, yǒu wèntí jíshí gàosu wǒ.", "Envoyez-moi un petit point chaque jour avant de partir, et prévenez-moi tout de suite en cas de problème.", "Send me a short report every day before you leave, and tell me promptly if anything comes up."),
      ],
    },
    vocab: ["经理", "客户", "方案", "到底", "交", "恐怕", "完成", "数据", "除非", "否则", "来不及", "既然", "够", "不得不", "加班", "辛苦", "规定", "任务", "推", "开会", "分", "重复", "紧", "马上", "报告", "及时", "周末", "简单", "按", "公司", "不过"],
    grammar: ["hsk4-g04", "hsk4-g05", "hsk4-g10", "hsk4-g20", "hsk4-g22", "hsk4-g25"],
    culture: {
      title: t("« 996 » et le rapport au travail", "\"996\" and attitudes to work"),
      body: t(
        "Dans certaines entreprises chinoises, surtout dans la tech, on parle du rythme **« 996 »** : de 9 h à 21 h, 6 jours sur 7. Ce modèle a été très critiqué en ligne et la Cour suprême a rappelé en 2021 qu'il était illégal. Beaucoup de jeunes lui opposent aujourd'hui le **躺平** (« rester allongé », refuser la course) ou se plaignent du **内卷** (« involution », concurrence épuisante).\n\nAu bureau, la **hiérarchie** reste importante : on appelle son supérieur par son nom + titre (**陈经理**, « directrice Chen ») et on évite de le contredire frontalement. D'où l'importance des formules qui adoucissent, comme **恐怕** ou **辛苦了** (« merci pour ta peine »).",
        "In some Chinese companies, especially in tech, people talk about the **\"996\"** schedule: 9 am to 9 pm, six days a week. It has been heavily criticised online, and the Supreme Court stated in 2021 that it is illegal. Many young people now answer with **躺平** (\"lying flat\", opting out) or complain about **内卷** (\"involution\", exhausting competition).\n\nAt the office, **hierarchy** matters: you address your boss by surname + title (**陈经理**, \"Manager Chen\") and avoid contradicting them head-on. Hence softening phrases like **恐怕** or **辛苦了** (\"thanks for your hard work\").",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète avec le bon connecteur.", "Fill in the right connector."),
        before: "除非老板同意，",
        after: "我们不能改计划。",
        options: ["否则", "所以", "而且", "因此"],
        answer: 0,
        tr: t("À moins que le patron soit d'accord, on ne peut pas changer le plan.", "Unless the boss agrees, we can't change the plan."),
        explain: t("除非 A，否则 B : B se produit si A n'a pas lieu.", "除非 A，否则 B: B happens if A doesn't."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "既然大家都同意，我们",
        after: "这么办吧。",
        options: ["就", "才", "都", "也"],
        answer: 0,
        tr: t("Puisque tout le monde est d'accord, faisons comme ça.", "Since everyone agrees, let's do it this way."),
        explain: t("既然… se complète par 就 dans la conclusion.", "既然… is completed by 就 in the conclusion."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["你到底去不去？", "你到底去吗？", "到底你去吗？", "你去到底不去？"],
        answer: 0,
        explain: t("到底 s'emploie dans une question ouverte (A不A, mot interrogatif), jamais avec 吗.", "到底 goes in an open question (A-not-A, question word), never with 吗."),
      },
      {
        type: "choice",
        prompt: t("« Ce rapport est crucial, tu dois absolument le lire. » Quelle traduction ?", "\"This report is crucial, you absolutely must read it.\" Which translation?"),
        options: ["这个报告很重要，你非看不可。", "这个报告很重要，你不得看。", "这个报告很重要，你非看。", "这个报告很重要，你不必看。"],
        answer: 0,
        explain: t("非…不可 = nécessité absolue. 不必 = « pas besoin ».", "非…不可 = absolute necessity. 不必 = \"no need\"."),
      },
      {
        type: "fill",
        prompt: t("Choisis le mot le plus poli pour annoncer une mauvaise nouvelle.", "Pick the most polite word to break bad news."),
        before: "",
        after: "我今天不能按时完成了。",
        options: ["恐怕", "害怕", "可怕", "恐怖"],
        answer: 0,
        tr: t("J'ai bien peur de ne pas pouvoir finir à temps aujourd'hui.", "I'm afraid I can't finish on time today."),
        explain: t("恐怕 = adverbe « je crains que ». 害怕 = avoir peur (de quelque chose).", "恐怕 = adverb \"I'm afraid\". 害怕 = to be scared (of something)."),
      },
      {
        type: "choice",
        prompt: t("Dans la ligne 6, pourquoi Xiao Wang dit-il 不得不加班 ?", "In line 6, why does Xiao Wang say 不得不加班?"),
        options: [
          t("Parce qu'ils seront contraints de faire des heures sup'", "Because they'll be forced to work overtime"),
          t("Parce qu'il adore faire des heures sup'", "Because he loves working overtime"),
          t("Parce qu'il n'a pas besoin de faire des heures sup'", "Because he doesn't need to work overtime"),
          t("Parce qu'il refuse les heures sup'", "Because he refuses overtime"),
        ],
        answer: 0,
        explain: t("不得不 = contrainte extérieure, souvent à contrecœur.", "不得不 = external constraint, often reluctant."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["除非", "再加一个人", "否则", "真的", "来不及"],
        tr: t("À moins d'ajouter une personne, on n'y arrivera vraiment pas à temps.", "Unless we add another person, we really won't make it."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["我们", "下午", "开个会", "把任务", "分一下"],
        tr: t("Faisons une réunion cet après-midi pour répartir les tâches.", "Let's have a meeting this afternoon to split the tasks."),
      },
      {
        type: "listen",
        zh: "你们非在周五以前交不可。",
        options: ["你们非在周五以前交不可。", "你们不在周五以前交也可以。", "你们非在周四以前交不可。", "你们在周五以前交不了。"],
        answer: 0,
        tr: t("Vous devez absolument le rendre avant vendredi.", "You absolutely must hand it in before Friday."),
      },
      {
        type: "listen",
        zh: "既然时间这么紧，我们就马上开始吧。",
        options: ["既然时间这么紧，我们就马上开始吧。", "虽然时间这么紧，我们还是明天开始吧。", "既然时间不太紧，我们就休息一下吧。", "因为时间这么紧，所以我们不开始了。"],
        answer: 0,
        tr: t("Puisque les délais sont si serrés, on s'y met tout de suite.", "Since time is so tight, let's start right away."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "客户", pinyin: "kèhù", tr: t("client", "client") },
          { zh: "方案", pinyin: "fāng'àn", tr: t("proposition, plan", "proposal, plan") },
          { zh: "加班", pinyin: "jiābān", tr: t("faire des heures sup'", "to work overtime") },
          { zh: "任务", pinyin: "rènwu", tr: t("tâche, mission", "task") },
          { zh: "及时", pinyin: "jíshí", tr: t("à temps, sans tarder", "promptly") },
        ],
      },
    ],
  },

  // ───────────────────────── L03 · Sciences ─────────────────────────
  {
    id: "hsk4-l03",
    level: 4,
    order: 3,
    title: t("Notre mémoire est-elle en baisse ?", "Is our memory getting worse?"),
    subtitle: t("Sciences : cerveau, expériences et conclusions", "Science: the brain, experiments and conclusions"),
    theme: "tech",
    goals: [
      t("Expliquer une cause et une conséquence avec 由于…因此…", "Explain cause and effect with 由于…因此…"),
      t("Décrire une méthode avec 通过", "Describe a method with 通过"),
      t("Conclure à partir d'un résultat avec 可见", "Conclude from a result with 可见"),
      t("Utiliser les sens figurés de 下去/出来/起来", "Use figurative 下去/出来/起来"),
    ],
    dialogue: {
      context: t(
        "Dans une émission de vulgarisation scientifique à la radio, la présentatrice interroge le professeur Liu, spécialiste du cerveau.",
        "On a popular-science radio show, the host interviews Professor Liu, a brain researcher.",
      ),
      lines: [
        ln("主持人", "刘教授，很多人觉得自己的记忆越来越差，这是真的吗？", "Liú jiàoshòu, hěn duō rén juéde zìjǐ de jìyì yuè lái yuè chà, zhè shì zhēn de ma?", "Professeur Liu, beaucoup de gens ont l'impression que leur mémoire baisse. C'est vrai ?", "Professor Liu, many people feel their memory is getting worse. Is that true?"),
        ln("刘教授", "似乎是这样。由于大家习惯用手机记东西，因此大脑用得少了。", "Sìhū shì zhèyàng. Yóuyú dàjiā xíguàn yòng shǒujī jì dōngxi, yīncǐ dànǎo yòng de shǎo le.", "Il semble que oui. Comme on a pris l'habitude de tout noter sur son téléphone, on se sert moins de son cerveau.", "It seems so. Because people are used to storing things on their phones, they use their brains less."),
        ln("主持人", "科学家是怎么研究这个问题的？", "Kēxuéjiā shì zěnme yánjiū zhège wèntí de?", "Comment les scientifiques étudient-ils cette question ?", "How do scientists study this question?"),
        ln("刘教授", "主要是通过实验。比如让两组人记同样的内容，一组可以拍照，另一组不可以。", "Zhǔyào shì tōngguò shíyàn. Bǐrú ràng liǎng zǔ rén jì tóngyàng de nèiróng, yì zǔ kěyǐ pāizhào, lìng yì zǔ bù kěyǐ.", "Surtout par des expériences. Par exemple, on fait mémoriser le même contenu à deux groupes : l'un a le droit de prendre des photos, l'autre non.", "Mainly through experiments. For example, two groups memorise the same content: one may take photos, the other may not."),
        ln("主持人", "结果呢？", "Jiéguǒ ne?", "Et le résultat ?", "And the result?"),
        ln("刘教授", "第二天，拍照的那组人很多内容都想不起来了。", "Dì-èr tiān, pāizhào de nà zǔ rén hěn duō nèiróng dōu xiǎng bu qǐlái le.", "Le lendemain, le groupe qui avait pris des photos n'arrivait plus à se rappeler une bonne partie du contenu.", "The next day, the group that took photos couldn't recall much of the content."),
        ln("刘教授", "没拍照的人却记得很清楚。可见，自己动脑记的东西更不容易忘。", "Méi pāizhào de rén què jì de hěn qīngchu. Kějiàn, zìjǐ dòng nǎo jì de dōngxi gèng bù róngyì wàng.", "Ceux qui n'avaient pas photographié s'en souvenaient au contraire très bien. On voit donc que ce qu'on mémorise par soi-même s'oublie moins facilement.", "Those who didn't take photos remembered clearly. This shows that what you memorise yourself is harder to forget."),
        ln("主持人", "那我们应该怎么做才能提高记忆呢？", "Nà wǒmen yīnggāi zěnme zuò cái néng tígāo jìyì ne?", "Alors, que faire pour améliorer notre mémoire ?", "So what should we do to improve our memory?"),
        ln("刘教授", "保证睡眠、经常运动，以及多读书，都很有帮助。", "Bǎozhèng shuìmián, jīngcháng yùndòng, yǐjí duō dú shū, dōu hěn yǒu bāngzhù.", "Bien dormir, faire du sport régulièrement, ainsi que lire beaucoup : tout cela aide.", "Getting enough sleep, exercising regularly and reading a lot all help."),
        ln("刘教授", "另外，学了新知识，最好马上讲给别人听，并且坚持复习下去。", "Lìngwài, xué le xīn zhīshi, zuìhǎo mǎshàng jiǎng gěi biérén tīng, bìngqiě jiānchí fùxí xiàqu.", "Par ailleurs, quand on apprend quelque chose de nouveau, le mieux est de l'expliquer tout de suite à quelqu'un, et de continuer à réviser.", "Also, when you learn something new, it's best to explain it to someone right away and keep revising."),
        ln("主持人", "听起来很简单，做起来却不容易。", "Tīng qǐlái hěn jiǎndān, zuò qǐlái què bù róngyì.", "Ça a l'air simple, mais c'est moins facile à faire.", "Sounds simple, but it's not easy to do."),
        ln("刘教授", "没错。大脑就像身体似的，越锻炼越健康。", "Méi cuò. Dànǎo jiù xiàng shēntǐ shìde, yuè duànliàn yuè jiànkāng.", "Exactement. Le cerveau, c'est comme le corps : plus on l'entraîne, plus il est en forme.", "Exactly. The brain is like the body — the more you train it, the healthier it gets."),
      ],
    },
    vocab: ["记忆", "教授", "似乎", "由于", "因此", "习惯", "大脑", "科学家", "研究", "通过", "实验", "组", "同样", "内容", "拍照", "结果", "清楚", "可见", "提高", "保证", "睡眠", "以及", "另外", "知识", "并且", "坚持", "复习", "锻炼", "健康", "主要", "比如", "却"],
    grammar: ["hsk4-g07", "hsk4-g12", "hsk4-g13", "hsk4-g17", "hsk4-g26", "hsk4-g29"],
    culture: {
      title: t("Apprendre par cœur : une tradition chinoise", "Learning by heart: a Chinese tradition"),
      body: t(
        "Pendant des siècles, les candidats aux examens impériaux (**科举**) devaient connaître par cœur les classiques confucéens. Un dicton dit encore : **« 熟读唐诗三百首，不会作诗也会吟 »** — « À force de lire trois cents poèmes Tang, on sait réciter des vers même sans savoir en écrire. »\n\nAujourd'hui encore, les élèves chinois récitent (**背**) poèmes et textes classiques. Les critiques parlent de « bourrage de crâne » (**死记硬背**), mais la recherche montre que la **récitation active** et la **répétition espacée** — que tu pratiques dans Hanlu ! — sont parmi les méthodes les plus efficaces pour mémoriser.",
        "For centuries, candidates for the imperial exams (**科举**) had to know the Confucian classics by heart. A saying still goes: **\"熟读唐诗三百首，不会作诗也会吟\"** — \"Read three hundred Tang poems well, and you can recite verse even if you can't write it.\"\n\nChinese pupils still recite (**背**) poems and classical texts today. Critics call it \"rote learning\" (**死记硬背**), but research shows **active recall** and **spaced repetition** — which you're doing in Hanlu! — are among the most effective ways to memorise.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète avec le bon connecteur.", "Fill in the right connector."),
        before: "由于天气原因，",
        after: "比赛推迟了。",
        options: ["因此", "于是", "否则", "并且"],
        answer: 0,
        tr: t("En raison de la météo, le match a donc été reporté.", "Due to the weather, the match was therefore postponed."),
        explain: t("由于 (cause, écrit) se combine naturellement avec 因此.", "由于 (cause, written) pairs naturally with 因此."),
      },
      {
        type: "choice",
        prompt: t("« 想出来 » ou « 想起来 » ? « Je me suis souvenu de son nom. »", "\"想出来\" or \"想起来\"? \"I remembered his name.\""),
        options: ["我想起来他的名字了。", "我想出来他的名字了。", "我想下去他的名字了。", "我想过来他的名字了。"],
        answer: 0,
        explain: t("想起来 = retrouver un souvenir ; 想出来 = inventer une idée nouvelle.", "想起来 = recall a memory; 想出来 = come up with something new."),
      },
      {
        type: "fill",
        prompt: t("Complète la conclusion.", "Complete the conclusion."),
        before: "他连周末都在实验室，",
        after: "他多么热爱科学。",
        options: ["可见", "看见", "可是", "似乎"],
        answer: 0,
        tr: t("Il est au labo même le week-end : c'est dire s'il aime la science.", "He's in the lab even at weekends, which shows how much he loves science."),
        explain: t("可见 tire une conclusion d'un fait. 看见 = voir avec les yeux.", "可见 draws a conclusion from a fact. 看见 = to see with your eyes."),
      },
      {
        type: "fill",
        prompt: t("Choisis le mot qui relie ces trois noms.", "Choose the word linking these nouns."),
        before: "我们讨论了工资、休假",
        after: "培训等问题。",
        options: ["以及", "并且", "而且", "于是"],
        answer: 0,
        tr: t("Nous avons discuté des salaires, des congés ainsi que de la formation.", "We discussed pay, leave and training."),
        explain: t("以及 relie des noms ; 并且/而且 relient des verbes ou des propositions.", "以及 links nouns; 并且/而且 link verbs or clauses."),
      },
      {
        type: "choice",
        prompt: t("Où placer 通过 ? « Grâce à cette expérience, nous avons trouvé la réponse. »", "Where does 通过 go? \"Through this experiment, we found the answer.\""),
        options: ["通过这个实验，我们找到了答案。", "我们找到了答案通过这个实验。", "我们找到通过这个实验了答案。", "这个实验通过，我们找到了答案。"],
        answer: 0,
        explain: t("通过 + moyen se place en tête de phrase ou devant le verbe, jamais à la fin.", "通过 + means goes at the start or before the verb, never at the end."),
      },
      {
        type: "fill",
        prompt: t("Complète la comparaison.", "Complete the comparison."),
        before: "大脑就像身体",
        after: "，越锻炼越健康。",
        options: ["似的", "似乎", "一起", "好像"],
        answer: 0,
        tr: t("Le cerveau est comme le corps : plus on l'entraîne, plus il est en forme.", "The brain is like the body: the more you train it, the healthier it gets."),
        explain: t("像…似的 : 似的 ferme la comparaison. 似乎 est un adverbe placé devant le verbe.", "像…似的: 似的 closes the comparison. 似乎 is an adverb before the verb."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["由于", "大家习惯用手机", "因此", "大脑", "用得少了"],
        tr: t("Comme on a l'habitude d'utiliser le téléphone, on se sert moins de son cerveau.", "Because people are used to phones, they use their brains less."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["研究", "很难", "但我们", "一定要", "做下去"],
        tr: t("La recherche est difficile, mais nous devons absolument continuer.", "Research is hard, but we must keep going."),
      },
      {
        type: "listen",
        zh: "听起来很简单，做起来却不容易。",
        options: ["听起来很简单，做起来却不容易。", "看起来很简单，做起来也很容易。", "听起来不简单，做起来却很容易。", "说起来很简单，想起来却不容易。"],
        answer: 0,
        tr: t("Ça a l'air simple, mais c'est moins facile à faire.", "Sounds simple, but it's not easy to do."),
      },
      {
        type: "listen",
        zh: "第二天，很多内容都想不起来了。",
        options: ["第二天，很多内容都想不起来了。", "第二天，很多内容都想起来了。", "第一天，很多内容都记不住了。", "第二天，很多内容都看不出来了。"],
        answer: 0,
        tr: t("Le lendemain, beaucoup de contenus étaient impossibles à se rappeler.", "The next day, a lot of the content couldn't be recalled."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "实验", pinyin: "shíyàn", tr: t("expérience (scientifique)", "experiment") },
          { zh: "记忆", pinyin: "jìyì", tr: t("mémoire", "memory") },
          { zh: "睡眠", pinyin: "shuìmián", tr: t("sommeil", "sleep") },
          { zh: "知识", pinyin: "zhīshi", tr: t("connaissances", "knowledge") },
          { zh: "研究", pinyin: "yánjiū", tr: t("rechercher, étudier", "to research") },
        ],
      },
    ],
  },
];
