import type { Lesson } from "../../types";
import { ln, t } from "./_h";

export const lessonsB: Lesson[] = [
  // ───────────────────────── L04 · Voyage & culture ─────────────────────────
  {
    id: "hsk4-l04",
    level: 4,
    order: 4,
    title: t("Une semaine à Xi'an", "A week in Xi'an"),
    subtitle: t("Voyage et culture : préparer un séjour pendant la Golden Week", "Travel & culture: planning a Golden Week trip"),
    theme: "travel",
    goals: [
      t("Dire « peu importe… » avec 无论/不管…都…", "Say \"no matter…\" with 无论/不管…都…"),
      t("Donner un exemple avec 拿…来说", "Give an example with 拿…来说"),
      t("Parler de budget avec 住得起 / 住不起", "Talk about budget with 住得起 / 住不起"),
      t("Prévoir un imprévu avec 假如 et 万一", "Plan for the unexpected with 假如 and 万一"),
    ],
    dialogue: {
      context: t(
        "Marc, étudiant français à Pékin, demande conseil à son ami Zhang Hua pour voyager pendant la fête nationale.",
        "Marc, a French student in Beijing, asks his friend Zhang Hua for advice about travelling over the National Day holiday.",
      ),
      lines: [
        ln("马克", "张华，国庆节我想去旅游，你有什么建议吗？", "Zhāng Huá, Guóqìng Jié wǒ xiǎng qù lǚyóu, nǐ yǒu shénme jiànyì ma?", "Zhang Hua, je voudrais voyager pendant la fête nationale. Tu as des conseils ?", "Zhang Hua, I want to travel over National Day. Any suggestions?"),
        ln("张华", "国庆节人特别多，无论去哪儿，都得提前订票。", "Guóqìng Jié rén tèbié duō, wúlùn qù nǎr, dōu děi tíqián dìng piào.", "Il y a un monde fou pendant la fête nationale : où que tu ailles, il faut réserver ses billets à l'avance.", "It's packed over National Day — wherever you go, you have to book tickets in advance."),
        ln("马克", "我对中国的历史文化很感兴趣，想去西安。", "Wǒ duì Zhōngguó de lìshǐ wénhuà hěn gǎn xìngqù, xiǎng qù Xī'ān.", "Je m'intéresse beaucoup à l'histoire et à la culture chinoises, j'aimerais aller à Xi'an.", "I'm really interested in Chinese history and culture; I'd like to go to Xi'an."),
        ln("张华", "好主意！中国各地都有自己的特色，拿西安来说，除了兵马俑，小吃也很有名。", "Hǎo zhǔyi! Zhōngguó gè dì dōu yǒu zìjǐ de tèsè, ná Xī'ān lái shuō, chúle Bīngmǎyǒng, xiǎochī yě hěn yǒumíng.", "Bonne idée ! Chaque région de Chine a ses spécialités. Prends Xi'an : en plus de l'armée de terre cuite, la street food est célèbre.", "Good idea! Every part of China has its own character. Take Xi'an — besides the Terracotta Warriors, its snacks are famous too."),
        ln("马克", "可是听说那边的酒店很贵，我一个学生恐怕住不起。", "Kěshì tīngshuō nàbiān de jiǔdiàn hěn guì, wǒ yí ge xuésheng kǒngpà zhù bu qǐ.", "Mais on m'a dit que les hôtels là-bas étaient chers. Étudiant comme je suis, j'ai peur de ne pas en avoir les moyens.", "But I heard hotels there are expensive. As a student, I'm afraid I can't afford them."),
        ln("张华", "别担心，可以住青年旅馆，一晚上一百块左右，谁都住得起。", "Bié dānxīn, kěyǐ zhù qīngnián lǚguǎn, yì wǎnshang yìbǎi kuài zuǒyòu, shéi dōu zhù de qǐ.", "Ne t'inquiète pas, tu peux aller en auberge de jeunesse : environ cent yuans la nuit, c'est à la portée de tout le monde.", "Don't worry, you can stay in a youth hostel — about a hundred yuan a night, anyone can afford that."),
        ln("马克", "参观兵马俑需要注意什么？", "Cānguān Bīngmǎyǒng xūyào zhùyì shénme?", "À quoi faut-il faire attention pour visiter l'armée de terre cuite ?", "What should I watch out for when visiting the Terracotta Warriors?"),
        ln("张华", "按照规定，要带护照买票。另外，任何人都不可以随便摸里面的东西。", "Ànzhào guīdìng, yào dài hùzhào mǎi piào. Lìngwài, rènhé rén dōu bù kěyǐ suíbiàn mō lǐmiàn de dōngxi.", "Selon le règlement, il faut ton passeport pour acheter le billet. Et personne n'a le droit de toucher quoi que ce soit à l'intérieur.", "By the rules, you need your passport to buy a ticket. Also, nobody is allowed to touch anything inside."),
        ln("马克", "假如时间够的话，我还想去其他城市看看。", "Jiǎrú shíjiān gòu dehuà, wǒ hái xiǎng qù qítā chéngshì kànkan.", "Si j'ai assez de temps, j'aimerais aussi voir d'autres villes.", "If there's enough time, I'd also like to see other cities."),
        ln("张华", "可以根据天气和你的时间再决定。坐高铁去洛阳只要两个小时。", "Kěyǐ gēnjù tiānqì hé nǐ de shíjiān zài juédìng. Zuò gāotiě qù Luòyáng zhǐ yào liǎng ge xiǎoshí.", "Tu décideras en fonction de la météo et de ton temps. Luoyang n'est qu'à deux heures en TGV.", "You can decide based on the weather and your time. Luoyang is only two hours by high-speed train."),
        ln("马克", "太好了。万一我迷路了，可以给你打电话吗？", "Tài hǎo le. Wànyī wǒ mílù le, kěyǐ gěi nǐ dǎ diànhuà ma?", "Génial. Si jamais je me perds, je peux t'appeler ?", "Great. If I happen to get lost, can I call you?"),
        ln("张华", "当然！不管什么时候，都可以找我。", "Dāngrán! Bùguǎn shénme shíhou, dōu kěyǐ zhǎo wǒ.", "Bien sûr ! Tu peux me joindre à n'importe quelle heure.", "Of course! You can reach me any time."),
      ],
    },
    vocab: ["国庆节", "建议", "无论", "提前", "订", "历史", "文化", "感兴趣", "各", "特色", "小吃", "有名", "酒店", "担心", "参观", "注意", "按照", "规定", "护照", "另外", "任何", "随便", "摸", "假如", "其他", "城市", "根据", "决定", "高铁", "万一", "迷路", "不管", "当然", "除了"],
    grammar: ["hsk4-g03", "hsk4-g15", "hsk4-g19", "hsk4-g31", "hsk4-g32", "hsk4-g33"],
    culture: {
      title: t("La « Golden Week » et l'armée de terre cuite", "Golden Week and the Terracotta Army"),
      body: t(
        "Autour du **1er octobre** (fête nationale), la Chine a une semaine de congés appelée **黄金周** (« semaine d'or »). Des centaines de millions de personnes voyagent en même temps : sites saturés, billets de train épuisés en quelques minutes. Les Chinois ont même un mot pour ça : **人山人海** (« des montagnes et des mers de gens »).\n\n**Xi'an** (西安), ancienne capitale de treize dynasties, abrite les **兵马俑**, l'armée de terre cuite du premier empereur Qin Shi Huang (IIIe siècle av. J.-C.), découverte par des paysans en 1974. Chaque soldat a un visage différent ! Et le soir, on va goûter les **小吃** (en-cas) du quartier musulman : 肉夹馍 (sorte de burger chinois), 羊肉泡馍 (soupe de mouton au pain).",
        "Around **1 October** (National Day), China has a week off called **黄金周** (\"Golden Week\"). Hundreds of millions travel at once: packed sights, train tickets gone in minutes. There's even an idiom for it: **人山人海** (\"mountains and seas of people\").\n\n**Xi'an** (西安), capital of thirteen dynasties, is home to the **兵马俑**, the Terracotta Army of the first emperor Qin Shi Huang (3rd century BC), discovered by farmers in 1974. Every soldier has a different face! In the evening, try the **小吃** (snacks) of the Muslim Quarter: 肉夹馍 (a kind of Chinese burger), 羊肉泡馍 (mutton soup with bread).",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "无论去哪儿，",
        after: "得提前订票。",
        options: ["都", "就", "才", "还"],
        answer: 0,
        tr: t("Où que tu ailles, il faut réserver à l'avance.", "Wherever you go, you must book ahead."),
        explain: t("无论/不管… appelle 都 dans la seconde proposition.", "无论/不管… calls for 都 in the second clause."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase est correcte ?", "Which sentence is correct?"),
        options: ["不管天气好不好，他都去爬山。", "不管天气很好，他都去爬山。", "不管天气好，他都去爬山。", "不管天气好不好，他去爬山了。"],
        answer: 0,
        explain: t("Après 不管, il faut un choix ouvert (好不好), et 都 dans la seconde partie.", "After 不管 you need an open choice (好不好), plus 都 in the second part."),
      },
      {
        type: "fill",
        prompt: t("Choisis la bonne préposition.", "Choose the right preposition."),
        before: "",
        after: "天气预报，明天有大雨。",
        options: ["根据", "按照", "关于", "对于"],
        answer: 0,
        tr: t("D'après la météo, il y aura de fortes pluies demain.", "According to the forecast, there'll be heavy rain tomorrow."),
        explain: t("根据 = s'appuyer sur une source d'information ; 按照 = suivre une règle ou un plan.", "根据 = based on a source of information; 按照 = follow a rule or plan."),
      },
      {
        type: "fill",
        prompt: t("Complète avec le bon complément.", "Fill in the right complement."),
        before: "这家酒店一晚上三千块，我住",
        after: "。",
        options: ["不起", "不了", "不下", "不到"],
        answer: 0,
        tr: t("Cet hôtel coûte trois mille yuans la nuit, je n'ai pas les moyens.", "This hotel is three thousand a night; I can't afford it."),
        explain: t("V不起 = ne pas avoir les moyens (souvent financiers).", "V不起 = can't afford (usually money)."),
      },
      {
        type: "choice",
        prompt: t("Quand emploie-t-on 万一 plutôt que 假如 ?", "When do you use 万一 rather than 假如?"),
        options: [
          t("Pour un imprévu peu probable et indésirable", "For an unlikely, unwanted event"),
          t("Pour un fait déjà certain", "For a fact that's already certain"),
          t("Pour une bonne nouvelle espérée", "For good news you hope for"),
          t("Pour une habitude", "For a habit"),
        ],
        answer: 0,
        explain: t("万一 = « si jamais » un problème arrive : 万一迷路了怎么办？", "万一 = \"in case\" something goes wrong: 万一迷路了怎么办？"),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "",
        after: "人都不可以随便摸里面的东西。",
        options: ["任何", "各", "其他", "每"],
        answer: 0,
        tr: t("Personne n'a le droit de toucher ce qu'il y a à l'intérieur.", "Nobody is allowed to touch anything inside."),
        explain: t("任何 + N + 都 = « n'importe quel / aucun ». 每 exigerait un classificateur (每个人).", "任何 + N + 都 = \"any / no one\". 每 would need a measure word (每个人)."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["拿西安来说", "除了兵马俑", "小吃", "也", "很有名"],
        tr: t("Prends Xi'an : en plus de l'armée de terre cuite, la street food est célèbre.", "Take Xi'an: besides the Terracotta Warriors, the snacks are famous too."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["假如", "时间够的话", "我", "还想去", "其他城市"],
        tr: t("Si j'ai assez de temps, j'aimerais aussi aller dans d'autres villes.", "If there's time, I'd also like to go to other cities."),
      },
      {
        type: "listen",
        zh: "万一我迷路了，可以给你打电话吗？",
        options: ["万一我迷路了，可以给你打电话吗？", "如果我没路了，可以给你打电话吗？", "万一我迟到了，可以给你打电话吗？", "万一你迷路了，可以给我打电话。"],
        answer: 0,
        tr: t("Si jamais je me perds, je peux t'appeler ?", "If I get lost, can I call you?"),
      },
      {
        type: "listen",
        zh: "一晚上一百块左右，谁都住得起。",
        options: ["一晚上一百块左右，谁都住得起。", "一晚上一千块左右，谁都住不起。", "一晚上一百块以上，谁都住不起。", "一个月一百块左右，谁都住得起。"],
        answer: 0,
        tr: t("Environ cent yuans la nuit : tout le monde peut se le permettre.", "About a hundred yuan a night — anyone can afford it."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "特色", pinyin: "tèsè", tr: t("caractéristique, spécialité", "distinctive feature") },
          { zh: "提前", pinyin: "tíqián", tr: t("à l'avance", "in advance") },
          { zh: "迷路", pinyin: "mílù", tr: t("se perdre", "to get lost") },
          { zh: "护照", pinyin: "hùzhào", tr: t("passeport", "passport") },
          { zh: "小吃", pinyin: "xiǎochī", tr: t("en-cas, street food", "snack") },
        ],
      },
    ],
  },

  // ───────────────────────── L05 · Santé ─────────────────────────
  {
    id: "hsk4-l05",
    level: 4,
    order: 5,
    title: t("Des maux de tête qui ne passent pas", "Headaches that won't go away"),
    subtitle: t("Santé : chez le médecin, stress et hygiène de vie", "Health: at the doctor's, stress and lifestyle"),
    theme: "health",
    goals: [
      t("Décrire un problème persistant avec 尽管…仍然…", "Describe an ongoing problem with 尽管…仍然…"),
      t("Parler de ses habitudes avec 从来不 / 从来没", "Talk about habits with 从来不 / 从来没"),
      t("Analyser deux causes avec 一方面…另一方面…", "Analyse two causes with 一方面…另一方面…"),
      t("Prendre une résolution avec 即使…也…", "Make a resolution with 即使…也…"),
    ],
    dialogue: {
      context: t(
        "M. Li, cadre de 35 ans, consulte un médecin dans un hôpital de Canton pour des maux de tête.",
        "Mr Li, a 35-year-old office worker, sees a doctor at a Guangzhou hospital about his headaches.",
      ),
      lines: [
        ln("医生", "李先生，您哪儿不舒服？", "Lǐ xiānsheng, nín nǎr bù shūfu?", "Monsieur Li, qu'est-ce qui ne va pas ?", "Mr Li, what seems to be the problem?"),
        ln("李先生", "最近总是头疼，睡不好。尽管吃了药，但是仍然没什么效果。", "Zuìjìn zǒngshì tóu téng, shuì bu hǎo. Jǐnguǎn chī le yào, dànshì réngrán méi shénme xiàoguǒ.", "Ces derniers temps, j'ai sans arrêt mal à la tête et je dors mal. J'ai pris des médicaments, mais ça ne fait toujours pas grand-chose.", "Lately I keep getting headaches and I sleep badly. I've taken medicine, but it still isn't helping much."),
        ln("医生", "您平时工作忙吗？每天睡几个小时？", "Nín píngshí gōngzuò máng ma? Měi tiān shuì jǐ ge xiǎoshí?", "Vous êtes très pris au travail d'habitude ? Vous dormez combien d'heures par nuit ?", "Are you usually busy at work? How many hours do you sleep a night?"),
        ln("李先生", "很忙，经常加班到十二点，有时候把咖啡当作晚饭。", "Hěn máng, jīngcháng jiābān dào shí'èr diǎn, yǒu shíhou bǎ kāfēi dàng zuò wǎnfàn.", "Très. Je fais souvent des heures sup' jusqu'à minuit, et parfois un café me tient lieu de dîner.", "Very. I often work until midnight, and sometimes coffee is my dinner."),
        ln("医生", "您运动吗？", "Nín yùndòng ma?", "Vous faites du sport ?", "Do you exercise?"),
        ln("李先生", "说实话，我从来不运动，连楼梯都很少爬。", "Shuō shíhuà, wǒ cónglái bú yùndòng, lián lóutī dōu hěn shǎo pá.", "Pour être honnête, je ne fais jamais de sport, je prends même rarement les escaliers.", "To be honest, I never exercise — I hardly even take the stairs."),
        ln("医生", "问题就在这儿。您一方面压力太大，另一方面缺少锻炼。", "Wèntí jiù zài zhèr. Nín yì fāngmiàn yālì tài dà, lìng yì fāngmiàn quēshǎo duànliàn.", "Voilà le problème. D'un côté vous êtes trop stressé, de l'autre vous manquez d'exercice.", "That's the problem. On the one hand you're under too much stress; on the other, you don't get enough exercise."),
        ln("医生", "别把头疼看成小事。长期这样下去，身体会出大问题。", "Bié bǎ tóu téng kàn chéng xiǎo shì. Chángqī zhèyàng xiàqu, shēntǐ huì chū dà wèntí.", "Ne prenez pas les maux de tête à la légère. Si ça continue comme ça longtemps, vous aurez de gros problèmes de santé.", "Don't treat headaches as a small thing. If this goes on for long, you'll have serious health problems."),
        ln("李先生", "可是我真的没时间去健身房。", "Kěshì wǒ zhēn de méi shíjiān qù jiànshēnfáng.", "Mais je n'ai vraiment pas le temps d'aller à la salle de sport.", "But I really don't have time for the gym."),
        ln("医生", "即使没时间去健身房，也可以每天走路半小时。", "Jíshǐ méi shíjiān qù jiànshēnfáng, yě kěyǐ měi tiān zǒulù bàn xiǎoshí.", "Même sans temps pour la salle de sport, vous pouvez marcher une demi-heure par jour.", "Even without time for the gym, you can walk half an hour a day."),
        ln("医生", "另外，晚上少喝咖啡，睡觉前别看手机。", "Lìngwài, wǎnshang shǎo hē kāfēi, shuìjiào qián bié kàn shǒujī.", "Et puis, moins de café le soir, et pas de téléphone avant de dormir.", "Also, less coffee in the evening, and no phone before bed."),
        ln("李先生", "明白了。即使工作再忙，我也要把健康放在第一位。", "Míngbai le. Jíshǐ gōngzuò zài máng, wǒ yě yào bǎ jiànkāng fàng zài dì-yī wèi.", "Compris. Même si le travail est très prenant, je vais mettre ma santé en priorité.", "Got it. However busy work gets, I'll put my health first."),
      ],
    },
    vocab: ["舒服", "最近", "总是", "头疼", "尽管", "药", "仍然", "效果", "平时", "经常", "加班", "当作", "从来", "说实话", "楼梯", "爬", "一方面", "另一方面", "压力", "缺少", "锻炼", "长期", "健身房", "即使", "走路", "另外", "睡觉", "明白", "健康", "咖啡", "身体", "医生", "放"],
    grammar: ["hsk4-g02", "hsk4-g06", "hsk4-g09", "hsk4-g24", "hsk4-g28", "hsk4-g30"],
    culture: {
      title: t("« 养生 » : l'art chinois de prendre soin de soi", "\"养生\": the Chinese art of looking after yourself"),
      body: t(
        "**养生** (« nourrir la vie ») est une préoccupation omniprésente en Chine, inspirée de la médecine chinoise (**中医**) : boire de l'**eau chaude** (多喝热水 !), éviter les boissons glacées, se coucher tôt, manger selon les saisons.\n\nLe matin, on voit des retraités pratiquer le **太极拳** dans les parcs, et le soir les fameuses **广场舞** (danses collectives sur les places). Les jeunes citadins, eux, parlent avec humour de **« 朋克养生 »** (« santé punk ») : boire de la bière… avec des baies de goji dedans !",
        "**养生** (\"nourishing life\") is everywhere in China, inspired by traditional Chinese medicine (**中医**): drink **hot water** (多喝热水!), avoid iced drinks, go to bed early, eat with the seasons.\n\nIn the morning, retirees practise **太极拳** in parks; in the evening come the famous **广场舞** (square dancing). Young urbanites joke about **\"朋克养生\"** (\"punk wellness\"): drinking beer… with goji berries in it!",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "即使没时间去健身房，",
        after: "可以每天走路半小时。",
        options: ["也", "就", "才", "还是"],
        answer: 0,
        tr: t("Même sans temps pour la salle de sport, on peut marcher une demi-heure par jour.", "Even without gym time, you can walk half an hour a day."),
        explain: t("即使… appelle 也 dans la seconde proposition.", "即使… calls for 也 in the second clause."),
      },
      {
        type: "choice",
        prompt: t("« Je ne suis jamais allé à l'hôpital. » Quelle phrase est correcte ?", "\"I've never been to hospital.\" Which is correct?"),
        options: ["我从来没去过医院。", "我从来不去过医院。", "我从来没去医院。", "我没从来去过医院。"],
        answer: 0,
        explain: t("Pour une expérience : 从来没(有) + V + 过.", "For an experience: 从来没(有) + V + 过."),
      },
      {
        type: "choice",
        prompt: t("Quelle différence entre 尽管 et 即使 ?", "What's the difference between 尽管 and 即使?"),
        options: [
          t("尽管 = fait réel ; 即使 = hypothèse", "尽管 = real fact; 即使 = hypothesis"),
          t("尽管 = hypothèse ; 即使 = fait réel", "尽管 = hypothesis; 即使 = real fact"),
          t("Aucune, ils sont interchangeables", "None, they're interchangeable"),
          t("尽管 est oral, 即使 est écrit", "尽管 is spoken, 即使 is written"),
        ],
        answer: 0,
        explain: t("尽管吃了药 (il a vraiment pris le médicament) ; 即使没时间 (même si on n'a pas le temps).", "尽管吃了药 (he really took it); 即使没时间 (even if there's no time)."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "别把头疼看",
        after: "小事。",
        options: ["成", "到", "出", "见"],
        answer: 0,
        tr: t("Ne prends pas les maux de tête pour une broutille.", "Don't treat headaches as a trivial thing."),
        explain: t("把 A 看成 B = considérer A comme B.", "把 A 看成 B = regard A as B."),
      },
      {
        type: "fill",
        prompt: t("Complète la phrase.", "Complete the sentence."),
        before: "吃了三天药，他",
        after: "咳嗽。",
        options: ["仍然", "从来", "反而", "于是"],
        answer: 0,
        tr: t("Après trois jours de médicaments, il tousse toujours.", "After three days of medicine, he's still coughing."),
        explain: t("仍然 = la situation n'a pas changé.", "仍然 = the situation hasn't changed."),
      },
      {
        type: "choice",
        prompt: t("Selon le médecin, quelles sont les deux causes des maux de tête ?", "According to the doctor, what are the two causes of the headaches?"),
        options: [
          t("Le stress et le manque d'exercice", "Stress and lack of exercise"),
          t("Le café et les escaliers", "Coffee and stairs"),
          t("Les médicaments et le sommeil", "Medicine and sleep"),
          t("La salle de sport et le téléphone", "The gym and the phone"),
        ],
        answer: 0,
        explain: t("一方面压力太大，另一方面缺少锻炼。", "一方面压力太大，另一方面缺少锻炼。"),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["他", "一方面", "压力太大", "另一方面", "缺少锻炼"],
        tr: t("D'un côté il est trop stressé, de l'autre il manque d'exercice.", "On the one hand he's too stressed; on the other he lacks exercise."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["我", "要", "把健康", "放在", "第一位"],
        tr: t("Je veux mettre la santé en priorité.", "I want to put health first."),
      },
      {
        type: "listen",
        zh: "尽管吃了药，但是仍然没什么效果。",
        options: ["尽管吃了药，但是仍然没什么效果。", "即使吃了药，也没什么效果。", "尽管没吃药，但是效果很好。", "因为吃了药，所以很有效果。"],
        answer: 0,
        tr: t("J'ai pris des médicaments, mais ça ne fait toujours pas grand-chose.", "I took medicine, but it's still not doing much."),
      },
      {
        type: "listen",
        zh: "说实话，我从来不运动。",
        options: ["说实话，我从来不运动。", "说实话，我从来没运动过。", "说实话，我每天都运动。", "实话说，我从来不走路。"],
        answer: 0,
        tr: t("Pour être honnête, je ne fais jamais de sport.", "To be honest, I never exercise."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "效果", pinyin: "xiàoguǒ", tr: t("effet, résultat", "effect") },
          { zh: "压力", pinyin: "yālì", tr: t("stress, pression", "pressure, stress") },
          { zh: "缺少", pinyin: "quēshǎo", tr: t("manquer de", "to lack") },
          { zh: "长期", pinyin: "chángqī", tr: t("à long terme", "long-term") },
          { zh: "健身房", pinyin: "jiànshēnfáng", tr: t("salle de sport", "gym") },
        ],
      },
    ],
  },

  // ───────────────────────── L06 · Médias ─────────────────────────
  {
    id: "hsk4-l06",
    level: 4,
    order: 6,
    title: t("Vraie ou fausse info ?", "Real or fake news?"),
    subtitle: t("Médias : vidéos courtes et esprit critique", "Media: short videos and critical thinking"),
    theme: "tech",
    goals: [
      t("Distinguer 关于 (sujet) et 对于 (attitude envers)", "Tell 关于 (topic) from 对于 (attitude towards)"),
      t("Exprimer la surprise ou le reproche avec 难道…吗", "Express surprise or reproach with 难道…吗"),
      t("Raconter un enchaînement avec 于是", "Narrate a sequence with 于是"),
      t("Clore une discussion avec 反正", "Wrap up an argument with 反正"),
    ],
    dialogue: {
      context: t(
        "Xiao Yu et Dawei, deux colocataires, discutent d'une vidéo virale sur le café.",
        "Flatmates Xiao Yu and Dawei talk about a viral video about coffee.",
      ),
      lines: [
        ln("小雨", "你看到那条新闻了吗？说喝咖啡能让人活得更长。", "Nǐ kàndào nà tiáo xīnwén le ma? Shuō hē kāfēi néng ràng rén huó de gèng cháng.", "Tu as vu cette info ? Elle dit que boire du café fait vivre plus longtemps.", "Did you see that news? It says coffee makes you live longer."),
        ln("大伟", "看到了，是一个短视频里说的。可是关于这个问题，专家的看法并不一样。", "Kàndào le, shì yí ge duǎn shìpín lǐ shuō de. Kěshì guānyú zhège wèntí, zhuānjiā de kànfǎ bìng bù yíyàng.", "Oui, c'était dans une vidéo courte. Mais sur cette question, les experts ne sont pas du tout d'accord.", "Yeah, it was in a short video. But on this question, experts don't agree at all."),
        ln("小雨", "难道视频里说的都是假的吗？它有几百万人点赞呢！", "Nándào shìpín lǐ shuō de dōu shì jiǎ de ma? Tā yǒu jǐ bǎi wàn rén diǎnzàn ne!", "Tu ne vas pas me dire que tout est faux dans la vidéo ? Elle a des millions de likes !", "Surely the video isn't all false? It's got millions of likes!"),
        ln("大伟", "点赞的人多，不一定说明内容是真的。", "Diǎnzàn de rén duō, bù yídìng shuōmíng nèiróng shì zhēn de.", "Beaucoup de likes, ça ne prouve pas que le contenu est vrai.", "Lots of likes doesn't necessarily mean the content is true."),
        ln("大伟", "上个月我也看到一条“新闻”，于是马上转发给了家人。", "Shàng ge yuè wǒ yě kàndào yì tiáo “xīnwén”, yúshì mǎshàng zhuǎnfā gěi le jiārén.", "Le mois dernier, moi aussi j'ai vu une « info », et du coup je l'ai tout de suite transférée à ma famille.", "Last month I saw a \"news story\" too, so I forwarded it to my family right away."),
        ln("大伟", "结果第二天就有记者说那是假消息，我觉得特别不好意思。", "Jiéguǒ dì-èr tiān jiù yǒu jìzhě shuō nà shì jiǎ xiāoxi, wǒ juéde tèbié bù hǎoyìsi.", "Et dès le lendemain, un journaliste a dit que c'était une fausse info. J'étais super gêné.", "The very next day a journalist said it was fake, and I felt really embarrassed."),
        ln("小雨", "那对于网上的消息，我们应该怎么判断呢？", "Nà duìyú wǎng shang de xiāoxi, wǒmen yīnggāi zěnme pànduàn ne?", "Alors, face aux infos en ligne, comment on fait pour juger ?", "So how should we judge information online?"),
        ln("大伟", "先看消息是从哪儿来的，再看看其他媒体有没有报道。", "Xiān kàn xiāoxi shì cóng nǎr lái de, zài kànkan qítā méitǐ yǒu méiyǒu bàodào.", "D'abord regarder d'où vient l'info, ensuite vérifier si d'autres médias en parlent.", "First check where it came from, then see whether other media reported it."),
        ln("小雨", "这么麻烦啊！反正我只是看看，又不转发。", "Zhème máfan a! Fǎnzhèng wǒ zhǐshì kànkan, yòu bù zhuǎnfā.", "C'est compliqué ! De toute façon, moi je ne fais que regarder, je ne partage pas.", "What a hassle! Anyway, I only watch — I don't share."),
        ln("大伟", "难道看了不会影响你的想法吗？", "Nándào kàn le bú huì yǐngxiǎng nǐ de xiǎngfǎ ma?", "Tu crois vraiment que regarder n'influence pas ta façon de penser ?", "Do you really think watching doesn't affect how you think?"),
        ln("小雨", "你说得也有道理。看来以后我得多想一想再相信。", "Nǐ shuō de yě yǒu dàolǐ. Kàn lái yǐhòu wǒ děi duō xiǎng yi xiǎng zài xiāngxìn.", "Tu n'as pas tort. Bon, à l'avenir je réfléchirai avant de croire.", "You have a point. Looks like I should think twice before believing things."),
        ln("大伟", "对，反正多花一分钟，也没什么坏处。", "Duì, fǎnzhèng duō huā yì fēnzhōng, yě méi shénme huàichu.", "Voilà. De toute façon, prendre une minute de plus, ça ne fait pas de mal.", "Right. Anyway, taking an extra minute doesn't hurt."),
      ],
    },
    vocab: ["新闻", "视频", "关于", "专家", "看法", "并", "难道", "假", "点赞", "说明", "内容", "条", "于是", "转发", "结果", "记者", "消息", "不好意思", "对于", "判断", "媒体", "报道", "麻烦", "反正", "只是", "影响", "想法", "道理", "看来", "相信", "坏处", "家人"],
    grammar: ["hsk4-g11", "hsk4-g14", "hsk4-g21", "hsk4-g23"],
    culture: {
      title: t("Les médias en Chine : WeChat, Douyin et le « 新闻联播 »", "Media in China: WeChat, Douyin and the \"新闻联播\""),
      body: t(
        "Les Chinois s'informent surtout sur leur téléphone : les comptes publics de **微信** (WeChat), les vidéos courtes de **抖音** (Douyin, la version chinoise de TikTok) et le réseau **微博** (Weibo). Tous les soirs à 19 h, la télévision centrale diffuse depuis 1978 le journal **《新闻联播》**, que beaucoup de familles regardent encore.\n\nLes fausses informations (**谣言**, « rumeurs ») circulent vite, notamment dans les groupes familiaux WeChat : des articles de santé alarmistes que les parents transfèrent à leurs enfants. Les plateformes ont créé des services de **辟谣** (« démentir une rumeur ») pour les contrer.",
        "Chinese people mostly get news on their phones: **微信** (WeChat) official accounts, short videos on **抖音** (Douyin, China's TikTok) and **微博** (Weibo). Every evening at 7 pm since 1978, state TV has aired **《新闻联播》** (the national news), which many families still watch.\n\nFake news (**谣言**, \"rumours\") spreads fast, especially in family WeChat groups: alarming health articles that parents forward to their kids. Platforms have set up **辟谣** (\"rumour-busting\") services to fight them.",
      ),
    },
    exercises: [
      {
        type: "fill",
        prompt: t("关于 ou 对于 ?", "关于 or 对于?"),
        before: "我看了一个",
        after: "中国历史的节目。",
        options: ["关于", "对于", "对", "跟"],
        answer: 0,
        tr: t("J'ai regardé une émission sur l'histoire de la Chine.", "I watched a programme about Chinese history."),
        explain: t("关于 + thème + 的 + N : « au sujet de ».", "关于 + topic + 的 + N: \"about\"."),
      },
      {
        type: "fill",
        prompt: t("关于 ou 对于 ?", "关于 or 对于?"),
        before: "",
        after: "年轻人来说，找工作越来越难了。",
        options: ["对于", "关于", "由于", "至于"],
        answer: 0,
        tr: t("Pour les jeunes, trouver du travail devient de plus en plus difficile.", "For young people, finding a job is getting harder."),
        explain: t("对(于)…来说 : du point de vue de quelqu'un.", "对(于)…来说: from someone's perspective."),
      },
      {
        type: "choice",
        prompt: t("Que veut vraiment dire : 难道你没看新闻吗？", "What does 难道你没看新闻吗？ really mean?"),
        options: [
          t("Tu as forcément vu les infos, voyons !", "Surely you've seen the news!"),
          t("Est-ce que tu as vu les infos ? (simple question)", "Did you see the news? (plain question)"),
          t("Ne regarde pas les infos.", "Don't watch the news."),
          t("Je n'ai pas vu les infos.", "I didn't see the news."),
        ],
        answer: 0,
        explain: t("难道…吗 est une question rhétorique : elle exprime surprise ou reproche.", "难道…吗 is rhetorical: it expresses surprise or reproach."),
      },
      {
        type: "fill",
        prompt: t("Complète le récit.", "Complete the story."),
        before: "我看到一条新闻，",
        after: "马上转发给了家人。",
        options: ["于是", "否则", "可见", "反正"],
        answer: 0,
        tr: t("J'ai vu une info, du coup je l'ai tout de suite transférée à ma famille.", "I saw a news story, so I forwarded it to my family right away."),
        explain: t("于是 relie deux actions passées : la seconde est la réaction à la première.", "于是 links two past actions: the second reacts to the first."),
      },
      {
        type: "choice",
        prompt: t("Quelle phrase utilise 反正 correctement ?", "Which sentence uses 反正 correctly?"),
        options: ["不管你去不去，反正我去。", "他不但没生气，反正很高兴。", "反正明天会下雨，于是你带伞吧。", "你反正去不去？"],
        answer: 0,
        explain: t("反正 = « de toute façon », souvent après 不管…. Ne le confonds pas avec 反而.", "反正 = \"anyway\", often after 不管…. Don't confuse it with 反而."),
      },
      {
        type: "choice",
        prompt: t("Selon Dawei, comment juger une info en ligne ?", "According to Dawei, how should you judge online news?"),
        options: [
          t("Vérifier la source et voir si d'autres médias en parlent", "Check the source and whether other media report it"),
          t("Compter le nombre de likes", "Count the likes"),
          t("Demander à sa famille", "Ask your family"),
          t("La transférer tout de suite", "Forward it right away"),
        ],
        answer: 0,
        explain: t("先看消息是从哪儿来的，再看看其他媒体有没有报道。", "先看消息是从哪儿来的，再看看其他媒体有没有报道。"),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["关于这个问题", "专家的", "看法", "并", "不一样"],
        tr: t("Sur cette question, les experts ne sont pas du tout d'accord.", "On this question, experts don't agree at all."),
      },
      {
        type: "order",
        prompt: t("Remets la phrase dans l'ordre.", "Put the sentence in order."),
        tokens: ["点赞的人多", "不一定", "说明", "内容", "是真的"],
        tr: t("Beaucoup de likes ne prouve pas que le contenu est vrai.", "Lots of likes doesn't prove the content is true."),
      },
      {
        type: "listen",
        zh: "难道看了不会影响你的想法吗？",
        options: ["难道看了不会影响你的想法吗？", "看了会影响你的想法吗？", "难道看了会影响你的办法吗？", "难道听了不会影响你的想法吗？"],
        answer: 0,
        tr: t("Tu crois vraiment que regarder n'influence pas ta façon de penser ?", "Do you really think watching doesn't affect how you think?"),
      },
      {
        type: "listen",
        zh: "反正多花一分钟，也没什么坏处。",
        options: ["反正多花一分钟，也没什么坏处。", "反而多花一分钟，也没什么好处。", "反正少花一分钟，也没什么坏处。", "反正多花十分钟，也没什么坏处。"],
        answer: 0,
        tr: t("De toute façon, prendre une minute de plus, ça ne fait pas de mal.", "Anyway, an extra minute doesn't hurt."),
      },
      {
        type: "match",
        prompt: t("Associe chaque mot à son sens.", "Match each word to its meaning."),
        pairs: [
          { zh: "转发", pinyin: "zhuǎnfā", tr: t("transférer, partager", "to forward, share") },
          { zh: "点赞", pinyin: "diǎnzàn", tr: t("liker", "to like (a post)") },
          { zh: "媒体", pinyin: "méitǐ", tr: t("médias", "media") },
          { zh: "判断", pinyin: "pànduàn", tr: t("juger, évaluer", "to judge") },
          { zh: "报道", pinyin: "bàodào", tr: t("reportage, rendre compte", "to report") },
          { zh: "专家", pinyin: "zhuānjiā", tr: t("expert", "expert") },
        ],
      },
    ],
  },
];
